### ISSUE TITLE
Memory leakage in the GPU Package compiled with OpenCL

### ISSUE THREAD

**Issue by vvsteg** [lammps/lammps#1006]
The memory leakage has been detected for the GPU Package compiled for OpenCL. 
There is no such a problem in the case of the GPU Package compiled with CUDA.

The bug is visible for the serial LAMMPS binary (lmp_serial) linked to libgpu.a compiled with OpenCL (Makefile.linux_opencl). Or any other compilation variants (g++_mpich etc.) Using the standard 'top' or 'free' linux commands, it is possible to notice the increase in the memory consumed after several minutes of the LAMMPS execution.

The simplest way to reproduce the bug is to run in.melt from examples/melt:
mpirun -np 6 ../../src/lmp_g++_mpich -sf gpu -pk gpu 1 -in in.melt
or
../../src/lmp_serial -sf gpu -pk gpu 1 -in in.melt

Tests of other MD models (EAM, pair potentials for OPLS) show the same memory leakage behaviour.

The bug has been reproduced with the 11Aug17 and 29Jun18 versions built with gcc 4.3.3 and MPICH version 3.0.4 both with AMD FireProS9150 (for OCL_TUNE = -DGENERIC_OCL and for OCL_TUNE = -DCYPRESS_OCL) and Nvidia GTX1070 accelerators (for OCL_TUNE = -DGENERIC_OCL and for OCL_TUNE=-DFERMI_OCL).

The bug has been reproduced for the 29Jun18 version with gcc 4.8.5 and openMPI 1.10.6 as well.

**Comment by akohlmey** [comment]
Thanks for reporting this here. I can confirm the leak with the latest LAMMPS development version as of july 18th 2018, Fedora 28, GCC 8.1.1, Nvidia Geforce GTX 1060 and Driver 390.59 using MPICH 3.2.1.

Sadly, this is difficult to trace down, as neither valgrind nor GCC's address sanitizer seem to function or provide helpful data.

**Comment by rbberger** [comment]
@vvsteg @akohlmey @ndtrung81 found the leak, preparing patch now...

**Comment by ndtrung81** [comment]
@rbberger : Thanks for looking at this issue! I spent a couple of days but couldn't figure out how to resolve it.

**Comment by akohlmey** [comment]
Unfortunately, fixing the memory leak causes segfaults with some pair styles. We need to investigate further... :-(

**Comment by akohlmey** [comment]
PR #1009 helps avoiding segfaults in several manybody pair styles after applying #1007. We still need an idea to address segfault issues with pair styles like lj/cut/coul/cut or lj/cut/coul/long triggered by plugging the memory leak.

**Comment by akohlmey** [comment]
No (major) memory leaks or segfaults were found with GPU package styles using either CUDA or OpenCL on a significant variety of inputs after merging PR #1009. Please submit a new issue, if problems persist and report the circumstances required to reproduce. Thanks again for reporting.

**Comment by vvsteg** [comment]
Thank you and the colleagues for this fix! Our tests of the updated version show no visible memory leaks as well.
