### ISSUE TITLE
case insensitive file names

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#1054]
## Summary

Recent docs work (as of 28c03e45182d267d0c951d8ca66ae5017e9b5350) 
has created two files with the same name up to case:

doc/src/Commands.txt
doc/src/Python.txt

## Type of Issue

This is a problem on osX which, by default, has a case-respecting but insensitive file system.

**Comment by rbberger** [comment]
@sjplimp did you see this?

**Comment by sjplimp** [comment]
Nope - good catch @ellio167.  @rbberger Changing commands.txt is easy, right, it's kind of hidden from
users anyway.  Need to think about P/p ython.txt.  Why did osX ever think that was a good idea?

**Comment by rbberger** [comment]
Fixed with PR #1048
