### ISSUE TITLE
no-manual-page-for-binary lmp

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1072]
rpmlint is complaining that `lmp` has no manual page, something for the next stable release.

**Comment by rbberger** [comment]
how does it detect that?

Command-line options are documented... https://lammps.sandia.gov/doc/Run_options.html

**Comment by rbberger** [comment]
more importantly, who cares if we make rpmlint happy? Does it have any real damaging effect on the RPM builds?

**Comment by akohlmey** [comment]
whoever cares can spend some quality time with nroff to convert this to a manpage. i've had my share already. so thanks but no thanks. ;-)

**Comment by akohlmey** [comment]
learned from the debian/ubuntu maintainer of the LAMMPS package today, that they have a man page for it already. should be easy to grab it and add here.
