### ISSUE TITLE
cmake -DPKG_USER-OMP doesn't make 'package omp' available

### ISSUE THREAD

**Issue by ExpHP** [lammps/lammps#1102]
I compiled lammps through cmake on the latest patch release put out just today (`patch_stable5Sep2018`).

I used the following command:
```
cmake .. \
    -DPKG_MANYBODY=yes \
    -DPKG_USER-MISC=yes \
    -DPKG_USER-OMP=yes \
    -DBUILD_MPI=yes \
    -DLAMMPS_EXCEPTIONS=yes \
    -DCMAKE_INSTALL_PREFIX=/home/lampam/lammps-herpaderp \
    -DCMAKE_BUILD_TYPE=Debug
```

## Actual behavior

When I run the compiled lammps and try to invoke `package omp`, I get:

```
package omp 0
ERROR: Package omp command without USER-OMP package installed (src/input.cpp:1753)
```

## Expected Behavior

I would expect the command should succeed, the same way it does when using the makefile build system.

```sh
# The old way...
$ make yes-user-omp
$ make yes-manybody
$ make yes-user-misc
$ make mymachine

# If I run the resulting lammps and type "package omp 0", I get this (successful) output:
package omp 0
using multi-threaded neighbor list subroutines
```

## Further Information, Files, and Links

I tried compiling with `-DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` to compare compiler flags with and without cmake. I can see that the c++ compiler is now being given the `-DLMP_USER_OMP` flag, thanks to recent bugfixes after the `stable_22Aug2018` release.

However, looking at `(cmake-build-dir)/styles/style_fix.h`, I see that `fix_omp` is still missing (whereas it is present when using the makefile system)

---

Lammps `patch_5Sep2018`

**Comment by rbberger** [comment]
Confirmed. Thanks for reporting.
