### ISSUE TITLE
Plug memory leaks in fix bocs

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1109]
## Summary

Fix bocs does malloc()/calloc() small chunks of memory all over the place but doesn't seem to free() them.

## Type of Issue

Bug report

## Detailed Description (Enhancement Suggestion)

The code should use either stack allocations or call free() on 

## LAMMPS Version (Bug Report)

Observed with version 5 Sep 2018, but has been in the code since the package was added.

## Expected Behavior (Bug Report)

No memory leak.

**Comment by eagunn** [comment]
I'm volunteering to work on this.

**Comment by akohlmey** [comment]
> I'm volunteering to work on this.

ok. assigned it to you.

**Comment by eagunn** [comment]
I'm going to make some notes-to-self-and-others here, as I figure out the code, until/unless someone tells me this creates too much chatter for core devs. 

Thanks to an input file contributed by one of the Penn State devs, Michael, I'm able to execute a run with the fix-bocs code for a cubic spline analysis that generates a variety of valgrind errors including some "definitely lost". But, so far, I'm not seeing a pathological memory leak. That is, the code definitely does not free some memory that is calloc'd. But it does not, as far as I've been able to observe, do so within the code that iterates in steps. The memory requirement is proportional to the number of data values in the input files; it does not increase as the number of steps increase.

**Comment by eagunn** [comment]
@akohlmey, Outside of the big in-memory data[] array for which you already applied some corrections to fix_bocs.cpp, there are two places where memory is calloc'd and not freed for local variables that do not need to survive the function in which they are used.

The simplest fix is to change a line like:
`  char * line = (char *) calloc(200,sizeof(char));`
in read_F_table to 
`char line[200];`

But for data being read in from a file or used to output an error message, it seems to me a much preferred fix would be to simply use the string data type, as in:
string line;
There's a lot less chance of guessing the needed string length wrong.

With a grep I can see some code in /src that uses string variables, but not a lot. Is there a fundamental reason to prefer char arrays over strings? And, if it is performance, note that the code I'm talking about here is either run only at initialization or in error/warning messages. It's not code that runs every step.

**Comment by akohlmey** [comment]
> I'm going to make some notes-to-self-and-others here, as I figure out the code, until/unless someone tells me this creates too much chatter for core devs.
> 
> Thanks to an input file contributed by one of the Penn State devs, Michael, I'm able to execute a run with the fix-bocs code for a cubic spline analysis that generates a variety of valgrind errors including some "definitely lost". But, so far, I'm not seeing a pathological memory leak. That is, the code definitely does not free some memory that is calloc'd. But it does not, as far as I've been able to observe, do so within the code that iterates in steps. The memory requirement is proportional to the number of data values in the input files; it does not increase as the number of steps increase.

this is still a leak, as it will increase memory consumption, when the fix is removed and recreated via unfix/fix, or the LAMMPS instance is freed and and recreated via the clear command, or an external user creates multiple LAMMPS instances repeatedly via the library interface. while those are not likely to become critical, we try to avoid those, too, since they may obscure other, more serious leaks. this is the same reason, why we try to minimize (harmless) compiler warnings, as they can obscure those that are indications of a serious problem.

**Comment by akohlmey** [comment]
> @akohlmey, Outside of the big in-memory data[] array for which you already applied some corrections to fix_bocs.cpp, there are two places where memory is calloc'd and not freed for local variables that do not need to survive the function in which they are used.
> 
> The simplest fix is to change a line like:
> ` char * line = (char *) calloc(200,sizeof(char));`
> in read_F_table to
> `char line[200];`
> 
> But for data being read in from a file or used to output an error message, it seems to me a much preferred fix would be to simply use the string data type, as in:
> string line;
> There's a lot less chance of guessing the needed string length wrong.
> 
> With a grep I can see some code in /src that uses string variables, but not a lot. Is there a fundamental reason to prefer char arrays over strings? And, if it is performance, note that the code I'm talking about here is either run only at initialization or in error/warning messages. It's not code that runs every step.

using the string class is ok, especially for only local variables. the bigger problem in the case reading/parsing files is that this requires using iostreams, which we try to avoid. LAMMPS historically was written in a C with classes style and makes use of the C library and stdio instead of STL and iostreams. we are slowly transitioning toward a more C++ style and lifting some of the limits to STL (best example are the functions in the file utils.cpp, which are - among other things - meant to explore how a future LAMMPS version could be written (using string class for safer string processing and inline documentation for a future programmer's guide). but iostreams is in many ways clumsy and annoying (for formatted output, for example), so that is not going to be popular among LAMMPS developers.
lots of pair styles in the MANYBODY package read files, perhaps you can adapt what those are doing?

**Comment by eagunn** [comment]
@akohlmey, you wrote
> this is still a leak, as it will increase memory consumption, when the fix is removed and recreated via unfix/fix, or the LAMMPS instance is freed and and recreated via the clear command, or an external user creates multiple LAMMPS instances repeatedly via the library interface. while those are not likely to become critical, we try to avoid those, too, since they may obscure other, more serious leaks. this is the same reason, why we try to minimize (harmless) compiler warnings, as they can obscure those that are indications of a serious problem.

Good. I was looking for a good reason to invest the work. Thanks for the background info.

**Comment by eagunn** [comment]
> using the string class is ok, especially for only local variables. 
>
> lots of pair styles in the MANYBODY package read files, perhaps you can adapt what those are doing?

Good. I'll use string cautiously but it should be a nice simplification for local variables.

And I'll take a look at the file reading in the MANYBODY code.

**Comment by eagunn** [comment]
Please keep me assigned to this task unless fixing it becomes time critical. I'll be off the grid for a couple of weeks but would like to continue working on it after I get back.

**Comment by eagunn** [comment]
@mdelyser I'm back online. I hope to get my code sync'd up with master tomorrow morning and then figure out where I left off and what's a good next step. Please let me know if anything changed with your view of this work while I was offline.

**Comment by eagunn** [comment]
@mdelyser As you can see from radio silence, once my teaching semester began, I lost all time to work on this defect. But we were on the right track and making progress. I'm hoping that once my fall semester is over, mid-December or so, I can use some of my free weeks till mid-January to work on and perhaps even complete this small project. I'll be in touch with you in December to see if you are still up for working together on this.
