### ISSUE TITLE
Installed Eigen3 package not found by cmake on Fedora 28

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1110]
## Summary

Cmake does not find the Eigen3 package on my Fedora 28 machine.

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

I have the Eigen3 headers installed
```
$ rpm -qa eigen3-devel
eigen3-devel-3.3.5-1.fc28.noarch
```
but cmake does not seem to be able to detect it:
```
$ cmake . -DPKG_USER-SMD=1 
-- Running check for auto-generated files from make-based build system
CMake Error at CMakeLists.txt:555 (message):
  Eigen3 not found, help CMake to find it by setting EIGEN3_INCLUDE_DIR, or
  set DOWNLOAD_EIGEN3=ON to download it


-- Configuring incomplete, errors occurred!
See also "/home/akohlmey/compile/lammps/build-multi/CMakeFiles/CMakeOutput.log".
```
and setting EIGEN3_INCLUDE_DIR does not help either
```
$ cmake . -DEIGEN3_INCLUDE_DIR=/usr/include/eigen3
-- Running check for auto-generated files from make-based build system
CMake Error at CMakeLists.txt:555 (message):
  Eigen3 not found, help CMake to find it by setting EIGEN3_INCLUDE_DIR, or
  set DOWNLOAD_EIGEN3=ON to download it


-- Configuring incomplete, errors occurred!
See also "/home/akohlmey/compile/lammps/build-multi/CMakeFiles/CMakeOutput.log".
```
## LAMMPS Version (Bug Report)

5 September 20018

## Expected Behavior (Bug Report)

Cmake should pick up the local Eigen3 installation (it *does* bundle an Eigen3.cmake file)

## Actual Behavior (Bug Report)

To successfully compile LAMMPS with the USER-SMD package, using the flag `-DDOWNLOAD_EIGEN3=1` is currently required.

**Comment by junghans** [comment]
Works on my Fedora 28 box.

It also working in a vanilla Fedora 28 docker container with the following dockerfile:
```
FROM fedora:28
RUN dnf install -y git cmake make gcc-c++ eigen3-devel
RUN git clone --depth=1 -b patch_5Sep2018 https://github.com/lammps/lammps.git
WORKDIR lammps/build
RUN cmake -DPKG_USER-SMD=1 ../cmake
```
gives:
```
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
```
so it must be your machine!

**Comment by akohlmey** [comment]
it works for me, too, if i use cmake directly as shown. but try using ccmake or cmake-gui. please also note, that ccmake or cmake-gui display an Eigen3_DIR variable that is not found, while the error message points to a variable EIGEN3_INCLUDE_DIR. once ccmake or cmake-gui have been run once, cmake doesn't work anymore either.

so this is genuine and rather unexpected.

**Comment by junghans** [comment]
Well, it is not im our control what variables get defined in `FindEigen3.cmake` as it comes with `eigen3-devel`, we could certainly add `Eigen3_DIR` to the error message, however according to https://cmake.org/cmake/help/v3.0/command/find_package.html `Eigen3_DIR` should point to the directory that contains the config file. So something like `Eigen3_DIR=/usr/share/eigen3/`.

**Comment by junghans** [comment]
I can reproduce this issue by running `ccmake` first and then enable `USER-PKG_SMD` in `ccmake` and then running `cmake`, but I have no idea what triggers that.
