### ISSUE TITLE
Cmake gets confused by emacs lock files

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1111]
## Summary

When editing files with emacs, lockfiles in the format `.#real_file_name.cpp` may be created which cause cmake configuration runs or updates to fail.

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

5 September 2018

## Expected Behavior (Bug Report)

Cmake should ignore editor lock and backup files.

## Actual Behavior (Bug Report)

Cmake fails to complete. Example:
```
-- Using FFTW3 as FFT
-- Configuring done
CMake Error at CMakeLists.txt:1210 (add_executable):
  Cannot find source file:

    /home/akohlmey/compile/lammps/src/USER-SMD/.#fix_smd_integrate_tlsph.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:1210 (add_executable):
  No SOURCES given to target: lmp
```

**Comment by junghans** [comment]
There isn't much we can do about that besides not using `GLOB` in CMake, however then we would have to explicitly list all file or write our own `GLOB` excluding `.#*`.

Details:
https://cmake.org/Bug/view.php?id=7487
https://gitlab.kitware.com/cmake/cmake/issues/7487

**Comment by akohlmey** [comment]
@junghans why not use a globing expression like `[a-z0-9]*.cpp` instead of `*.cpp`?

**Comment by junghans** [comment]
That is actually not too ugly...
