### ISSUE TITLE
Memory alignment can be lost on reallocation (even if LAMMPS_MEMALIGN is set)

### ISSUE THREAD

**Issue by jjegg01** [lammps/lammps#1123]
## Summary

Even if LAMMPS_MEMALIGN is set, Memory::srealloc does not guarantee to return aligned memory.

## Type of Issue

Bug report.

## Detailed Description

Due to LMP_INTEL_NO_TBB being undefined Memory::realloc does not check for memory alignment. Memory::smalloc works as expected. This caused some segfaults when I was writing a custom vectorized fix.

## LAMMPS Version

This happens in version 22Aug18 as well as the current HEAD of master (commit 6ae4bdead5cbe4f7fc768b21295cf346ced23759).

## Expected Behavior

If LAMMPS_MEMALIGN is set, Memory::srealloc should call smalloc if necessary to restore alignment.

## Actual Behavior

Memory::srealloc only calls realloc. See the disassembly for proof (smalloc calls posix_memalign, but srealloc only calls realloc).
[smalloc.txt](https://github.com/lammps/lammps/files/2379260/smalloc.txt)
[srealloc.txt](https://github.com/lammps/lammps/files/2379261/srealloc.txt)

## Steps to Reproduce

(Starting in lammps-master/build)
```
cmake -DLAMMPS_MEMALIGN=64 -DCMAKE_BUILD_TYPE=Debug ../cmake/
gdb ./lmp
>>> disassemble /s 'LAMMPS_NS::Memory::srealloc(void*, long, char const*)'
```

## Further Information

I would suggest removing LMP_INTEL_NO_TBB from line 82 of src/memory.cpp and use the same switches as in smalloc. malloc.h has to be included if LAMMPS_MEMALIGN is defined for this to work.

**Comment by akohlmey** [comment]
The current behavior is the expected behavior. -DLAMMPS_MEMALIGN is not expected to strictly enforce memory alignment. If you want/need that, you have to do what the USER-INTEL package does and link with the malloc wrapper from TBB.
