### ISSUE TITLE
[Feature Request] Remove MEAM and REAX packages

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1129]
## Summary

Both, pair styles `reax` and `meam` were flagged as obsolete for a long time and should be removed after the next stable release.

## Type of Issue

Enhancement

## Detailed Description (Enhancement Suggestion)

Including Fortran libraries complicates the build process, the large static memory allocations for `reax` creates problems when trying to debug or run with valgrind, and reax is not friendly for pre-compiled binaries, since array dimensions may need to be adjusted and the executable recompiled for larger systems. Both packages are incompatible with pair style hybrid. For both there are alternatives written in c++ (`reax/c` and `reax/c/kk`, and `meam/c`). `reax/c` offers more functionality and dynamical memory management (`reax/c/kk` is more robust, though). `meam/c` is a fully compatible re-programming of the Fortran code with performance enhancements (due to avoiding to translate between fortran and c-style data structures and more). Thus `meam/c` is fully backward compatible and we're going to keep support for inputs use the `meam` pair style by making it an (undocumented) alias to `meam/c`. For reax, we'll include a dummy pair style pointing to the last version supporting it or `reax/c`.

Individual steps required:
- [x] make warning about pending removal more drastic and visible
- [x] post a message to lammps-users
- [x] removal of package folders
- [x] removal of library folders
- [x] update of `src/Makefile`
- [x] update of `cmake/CMakelists.txt`
- [x] update of `src/Purge.list`
- [x] update of `src/.gitignore`
- [x] implement dummy pair style class PairObsolete, that will print a meaningful message when obsolete inputs are run (e.g. pointing to the last release containing the package/style) 
- [x] removal or update of pair style and fix style documentation
- [x] removal of all references to REAX or MEAM packages in documentation

## Contingency plan

Users, that insist on using those styles are recommended to use the upcoming stable LAMMPS release and not upgrade, in case they want to keep using REAX or MEAM.

**Comment by athomps** [comment]
This seems reasonable to me.

**Comment by martok** [comment]
Regarding `meam/c`: after some more months of high-throughput work with it, I have found no further obviously wrong results except for degenerate/bad inputs - and for them, all bets are off anyway. Looks like it is safe to transparently alias `meam` to `meam/c`.
