### ISSUE TITLE
possible bug with read_restart command

### ISSUE THREAD

**Issue by ramisetti** [lammps/lammps#1130]
## Summary

_read_restart_ command is restarting run differently than the run which produced the restart file written with _restart_ command followed by two filenames

## Type of Issue

Bug Report (possible)

## Detailed Description (Enhancement Suggestion)

Restarting run is sometimes different when using _read_restart_ command (like **_read_restart_ restart.*.equi**) where **restart.*.equi** are 2 files produced from _restart_ command with two filenames (like **_restart_ restart.1.equi restart.2.equi**). I know that the code for read_restart command is looking for maximum timestep based on the file name and not from the file content and so in my case it is always picking up restart.2.equi file which in some cases may not be the last timestep.

## LAMMPS Version (Bug Report)

2 August 18

## Expected Behavior (Bug Report)

The description for _read_restart_ manual says that "If  a “*” appears in the filename, the directory is searched for all filenames that match the pattern where “*” is replaced with a timestep value. The file with the largest timestep value is read in." However, this description is true in only some cases when restart file name contains timesteps in the file name. 

## Actual Behavior (Bug Report)

I think the description in the manual should also explicitly mention the largest timestep value is chosen based on the filenames and it does not work when restart files are written using _restart_ command with two filenames (e.g.: **_restart_ restart.1.equi restart.2.equi**)

## Steps to Reproduce (Bug Report)

1. run lammps with in.indent.txt (attached) which will create restart.1.equi and restart.2.equi
2. make a copy of restart.1.equi and restart.2.equi
3. run lammps with in_indent_restart.txt (attached)
4. open the log.lammps file and check for the first timestep printed under Step. If the time step is 40000 the restart is as expected.
5. swap the names of the copies of the restart.1.equi and restart.2.equi (from step 2)
6. run lammps with in_indent_restart. Repeat step 4 to check the the first timestep written under Step. This time the timestep is 39000 which is the not the last step of previous run from step 1 (see attached a copy of my log file).

## Further Information, Files, and Links

[in.indent_restart.txt] (https://github.com/lammps/lammps/files/2400785/in.indent_restart.txt)
[in.indent.txt] (https://github.com/lammps/lammps/files/2400786/in.indent.txt)
[log.txt] (https://github.com/lammps/lammps/files/2400789/log.txt)

**Comment by akohlmey** [comment]
No, this is not a bug, but a misuse of a feature. The restart.1.equi and restart.2.equi files do not encode the time step into the file name (i would recommend against using numbers here to avoid this confusion, but call them restart.a.equi and restart.b.equi), so you cannot use a feature that depends on it. The read_restart option including a "*" is meant to be using in conjunction with the restart command using a filename including a "*" (which will be replaced with the current timestep number).
