### ISSUE TITLE
Kokkos package failing at install step

### ISSUE THREAD

**Issue by ocaisa** [lammps/lammps#1134]
## Summary

When trying to build and install the latest stable and patch releases using the CMake procedure, I'm getting failures on the install step related to kokkos.

## Type of Issue

Bug report

## LAMMPS Version (Bug Report)

Tested with latest stable and patch releases

## Expected Behavior (Bug Report)

Successful installaton

## Actual Behavior (Bug Report)

```
-- Final kokkos settings variable:
--   env;KOKKOS_SRC_PATH=/dev/shm/ocaisa/LAMMPS/18Sep2018/intel-para-2018a-kokkos/lammps-patch_18Sep2018/lib/kokkos;KOKKOS_PATH=/dev/shm/ocaisa/LAMMPS/18Sep2018/intel-para-2018a-kokkos/lammps-patch_18Sep2018/lib/kokkos;KOKKOS_INSTALL_PATH=/usr/local/software/jureca/Stages/Devel-2018a/software/LAMMPS/18Sep2018-intel-para-2018a-kokkos;KOKKOS_ARCH=HSW;KOKKOS_DEVICES=OpenMP,Serial;KOKKOS_DEBUG=no;KOKKOS_OPTIONS=disable_dualview_modify_check,enable_eti;KOKKOS_USE_TPLS=librt
-- *****************************************************
-- 
/dev/shm/ocaisa/LAMMPS/18Sep2018/intel-para-2018a-kokkos/lammps-patch_18Sep2018/lib/kokkos/cmake/Makefile.generate_cmake_settings:7: /usr/local/software/jureca/Stages/Devel-2018a/software/LAMMPS/18Sep2018-intel-para-2018a-kokkos/core/src/Makefile.generate_header_lists: No such file or directory
/dev/shm/ocaisa/LAMMPS/18Sep2018/intel-para-2018a-kokkos/lammps-patch_18Sep2018/lib/kokkos/cmake/Makefile.generate_cmake_settings:8: /usr/local/software/jureca/Stages/Devel-2018a/software/LAMMPS/18Sep2018-intel-para-2018a-kokkos/core/src/Makefile.generate_build_files: No such file or directory
make[1]: *** No rule to make target `/usr/local/software/jureca/Stages/Devel-2018a/software/LAMMPS/18Sep2018-intel-para-2018a-kokkos/core/src/Makefile.generate_build_files'.  Stop.
CMake Error at ../lib/kokkos/CMakeLists.txt:43 (message):
  Kokkos settings generation failed:
```
It seems to be looking for the files `Makefile.generate_header_lists` and `Makefile.generate_build_files` in `KOKKOS_INSTALL_PATH` rather than `KOKKOS_SRC_PATH`.

## Steps to Reproduce (Bug Report)

My setup is with the Intel compiler, an MPICH-based MPI, MKL and the required deps for the following CMake command:
```
cmake ./cmake -DCMAKE_INSTALL_PREFIX=/usr/local/software/jureca/Stages/Devel-2018a/software/LAMMPS/18Sep2018-intel-para-2018a-kokkos -DCMAKE_C_COMPILER='mpicc' -DCMAKE_Fortran_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source -fopenmp' -DCMAKE_CXX_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source -fopenmp' -DCMAKE_CXX_COMPILER='mpicxx' -DCMAKE_Fortran_COMPILER='mpif90' -DCMAKE_C_FLAGS='-O2 -xHost -ftz -fp-speculation=safe -fp-model source -fopenmp' -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_MPI=on -DBUILD_OMP=on -DPKG_KOKKOS=on -DPKG_OPT=on -DPKG_USER-OMP=on -DPKG_USER-INTEL=on -DPKG_GPU=on -DPKG_ASPHERE=on -DPKG_BODY=on -DPKG_CLASS2=on -DPKG_COLLOID=on -DPKG_COMPRESS=on -DPKG_CORESHELL=on -DPKG_DIPOLE=on -DPKG_GRANULAR=on -DPKG_KSPACE=on -DPKG_MANYBODY=on -DPKG_MC=on -DPKG_MEAM=on -DPKG_MISC=on -DPKG_MOLECULE=on -DPKG_PERI=on -DPKG_QEQ=on -DPKG_REAX=on -DPKG_REPLICA=on -DPKG_RIGID=on -DPKG_SHOCK=on -DPKG_SNAP=on -DPKG_SRD=on -DPKG_PYTHON=on -DPKG_MPIIO=on -DPKG_POEMS=on -DPKG_USER-ATC=on -DPKG_USER-AWPMD=on -DPKG_USER-CGDNA=on -DPKG_USER-CGSDK=on -DPKG_USER-COLVARS=on -DPKG_USER-DIFFRACTION=on -DPKG_USER-DPD=on -DPKG_USER-DRUDE=on -DPKG_USER-EFF=on -DPKG_USER-FEP=on -DPKG_USER-H5MD=on -DPKG_USER-LB=on -DPKG_USER-MANIFOLD=on -DPKG_USER-MEAMC=on -DPKG_USER-MESO=on -DPKG_USER-MGPT=on -DPKG_USER-MISC=on -DPKG_USER-MOFFF=on -DPKG_USER-MOLFILE=on -DPKG_USER-NETCDF=on -DPKG_USER-PHONON=on -DPKG_USER-QTB=on -DPKG_USER-REAXC=on -DPKG_USER-SMTBQ=on -DPKG_USER-SPH=on -DPKG_USER-TALLY=on -DPKG_USER-UEF=on -DBUILD_LIB=on -DBUILD_EXE=on -DBUILD_SHARED_LIBS=on -DWITH_JPEG=yes -DWITH_PNG=yes -DWITH_GZIP=yes -DFFT=MKL -DFFT_PACK=array -DGPU_API=cuda -DGPU_ARCH=sm_30 -DCUDPP_OPT=on -DKOKKOS_ENABLE_OPENMP=yes -DKOKKOS_ARCH="HSW"
```
To reproduce just `make; make install`

## Further Information, Files, and Links

I'm using [EasyBuild](https://easybuild.readthedocs.io/en/latest/) to do the installation, a working easyconfig without Kokkos for this build can be seen [here](https://gist.github.com/ocaisa/965ee383b4ec156b7e9fc0251411d8ec) (but is specific to the setup at Juelich Supercomputing Centre)

**Comment by junghans** [comment]
I cannot reproduce this in a simple case like:
```
cmake ../cmake/ -DPKG_KOKKOS=ON -DCMAKE_INSTALL_PREFIX=$HOME/lammps
make
make install
```
might be some combination of packages though.

**Comment by junghans** [comment]
Or a combination of Kokkos options.

**Comment by ocaisa** [comment]
I have no idea of the impact of my package selections, I just included everything that didn't require a complicated dependency. For Kokkos, I selected additional options based on the info at https://lammps.sandia.gov/doc/Build_extras.html#kokkos

File system is down at the moment so I can't check a simpler configuration.

**Comment by junghans** [comment]
@stanmoore1: I think the problem is that in the seconds cmake invocation `lib/kokkos/Makefile.kokkos` gets overwritten and a line with a wrong `KOKKOS_PATH` gets written, e.g.:
```
KOKKOS_PATH = /usr/local
```
and then the above error is generated as  `$(KOKKOS_PATH)/core/src/Makefile.generate_header_lists` cannot be included in `/lib/kokkos/cmake/Makefile.generate_cmake_settings`.

@ocaisa: Just do an out-of-source build for now, e.g.:
```
mkdir build 
cd build
cmake ../cmake
```

**Comment by ocaisa** [comment]
Thanks @junghans , confirmed that that fixes the problem for me.

This is ok to close now (not sure if you want to keep the reminder around so I leave it to you).

**Comment by akohlmey** [comment]
@junghans can't we just put a test in the `cmake/CMakeLists.txt` file that requires out-of-source builds? It is the smart thing to do in the first place, and we don't have to care about the headaches of supporting in-source building.

**Comment by junghans** [comment]
@akohlmey we could that is easy to do! But let’s wait for @stanmoore1, maybe there is an easy fix!

**Comment by akohlmey** [comment]
@junghans i think we should do it anyway for the reasons i listed above. if kokkos (or kokkos in LAMMPS) needs fixing, that can be done on top of it. there also is the educational benefit. if we start forcing people to do out-of-source builds, we may promote a habit of doing that, which is a very good thing. out-of-source builds is probably the CMake feature i appreciate the most.

**Comment by stanmoore1** [comment]
I took a look and I'm still not sure why KOKKOS_PATH is getting overwritten. I support enforcing out of source builds.
