### ISSUE TITLE
Update of documentation for binary LAMMPS packages required

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1135]
## Summary

With recent advances in building LAMMPS with CMake and creating packages for Linux distributions, the documentation has gone out of sync and should be updated for the next stable release.

## Type of Issue

This is both, a bug report and a request for enhancement.

## Detailed Description

The file `doc/src/Install_linux.txt` needs to be updated.
- [x] the RPMs on lammps.org, which were based on LAMMPS-ICMS are no longer updated. This section should thus be removed
- [x] Support for LAMMPS has been officially included in SuSE, Fedora, and ??
- [ ] Support for LAMMPS in Debian/Ubuntu has been expanded (not just the daily version), this should be listed and also the correct name of the executable, and which MPI lib is used.
- [x] Gentoo support should be verified and the documentation may need to be updated

## LAMMPS Version

LAMMPS 18 Sep 2018

## Expected Behavior

Documentation should reflect the current status (even though it is a moving target).

## Actual Behavior

Documentation is missing relevant info and has incorrect data.

## Further Information, Files, and Links

Part of the necessary changes are included in PR #1133

**Comment by junghans** [comment]
The Gentoo part (https://lammps.sandia.gov/doc/Install_linux.html#gentoo) seems pretty accurate still.

**Comment by junghans** [comment]
And here is what I send to @sjplimp a while back:
> To install lammps on fedora:
> $ dnf install lammps
> for the openmpi version:
> $ dnf install lammps-openmpi
> 
> On CentOS7 one needs to do
> $ yum install epel-release
> $ yum update
> $ yum install lammps
> 
> For OpenSuse (Leap 15.0 and higher) there is an openmpi-enabled version one can get with:
> $ zypper install lammps

**Comment by junghans** [comment]
> 1) what are the names of the executables in those cases?

On OpenSuse: `lmp`
On Fedora/CentOS: `lmp`

> 2) can the lammps-openmpi and lammps package installed at the same time? if
yes, how do people select the proper LAMMPS executable? does EPEL provide
both lammps, and lammps-openmpi or only lammps and is that then with MPI
included?

Fedora and CentOS are build from the same spec. So CentOS has all the same versions.
On Fedora, you can switch the mpi versions by using e.g. `module load openmpi`, which will update `PATH` etc to point to the right `lmp` executable. All packages can be installed simultaneously.

**Comment by akohlmey** [comment]
@gladk would you mind having a look at https://github.com/lammps/lammps/blob/doc-adjust/doc/src/Install_linux.txt and e-mail me, if needed, an updated version covering your LAMMPS packages for Debian/Ubuntu? or you could submit a pull request relative to the doc-adjust branch (not master).
I recall from the OpenKIM coding sprint that there are now more variants, than the lammps-daily package, but I don't remember the details. Thanks in advance.

**Comment by gladk** [comment]
@akohlmey yes, I am preparing an update.

**Comment by junghans** [comment]
@akohlmey, with this in doc, http://rpm.lammps.org/ needs an update as well.
