### ISSUE TITLE
Convert embedded MathJax to explicitly rendered pictures

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1138]
## Summary

A few LAMMPS doc pages use MathJax to typeset equations. This works ok for HTML pages, but fails for PDF files created with htmldoc.

## Type of Issue

Enhancement(?)

## Detailed Description

The LAMMPS documentation typesets equations by processing single-page latex files into jpeg images. Some recent contributions uses MathJax instead, which is not compatible with the tools used to generate the PDF format manual. Converting those into the common LAMMPS style will improve the PDF manual.

## Further Information, Files, and Links

An alternate approach to create PDF files from the documentation, that does not require txt2html and htmldoc would be preferable and would allow to use RST markup instead of the custom markup from txt2html. at the moment, we convert txt2html files to rst in order to build the visually enhanced html manual version.

**Comment by evoyiatzis** [comment]
is still a volunteer needed?
