### ISSUE TITLE
sign issue in semi grand acceptance criterion 

### ISSUE THREAD

**Issue by sinamoeini** [lammps/lammps#1139]
I think the signs of mu[itype] and mu[jtype] should be reversed, in other words the expression should be

exp(-beta*(energy_after- mu[jtype] - energy_before + mu[itype])))

https://github.com/lammps/lammps/blob/4fe23c3854eabe82af82e107b46cfe7713af0ca5/src/MC/fix_atom_swap.cpp#L381

**Comment by sinamoeini** [comment]
We know the higher the chemical potential associated with an element the higher its concentration will be. Suppose that mu[jtype] tends to infinity, and mu[itype] is a constant. In this situation all the elements should become jtype, and the trial move from itype to jtype must be accepted always. But here the opposite happens if jtype goes to infinity the right side of the inequality becomes 0 and the move will never be accepted.

**Comment by athomps** [comment]
@sinamoeini Yes, you are correct. Effectively the input values of mu are actually -mu.  The acceptance probability is increasing function of mu_new (jtype) and decreasing function of mu_old (itype).  I prefer the following correction, because it mirrors the other Metropolis criterion in the same file:

    if (random_unequal->uniform() <
      exp(beta*(energy_before - energy_after
            + mu[jtype] - mu[itype]))) success = 1;

After this change is made, recovering previous results will require changing sign of mu in input script. This command is not tested in examples/gcmc.

**Comment by sinamoeini** [comment]
There is also another issue, I think expression should be modified further as follows

double extra_fac=sqrt_mass_ratio[jtype][itype]*sqrt_mass_ratio[jtype][itype]*sqrt_mass_ratio[jtype][itype];
if (random_unequal->uniform() <
 extra_fac*exp(beta*(energy_before - energy_after
        + mu[jtype] - mu[itype]))) success = 1;

I think the original paper that this code was based on was only changing the spin of atoms so the masses remained constant in that case. Please take a look at Eq 9.1.18 of Frenkel and Smit (I changed i' to j for convenience)

here \xi_{j}/\xi_i is effectively 
exp(\beta (\mu_j-\mu_i)) (\lambda_i/\lambda_j)^3 
which simplifies to 
exp(\beta (\mu_j-\mu_i)) (m_j/m_i)^(3/2)


Thanks,
Sina

**Comment by athomps** [comment]
@akohlmey, should I go ahead and do a pull request for the sign change?
