### ISSUE TITLE
compute_stress_mop.cpp(400): error: more than one instance of overloaded function "copysign" 

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#1153]
## Summary

Our Kokkos CUDA build is failing to compile:

../compute_stress_mop.cpp(400): error: more than one instance of overloaded function "copysign" matches the argument list:
function "copysign(double, double)"
function "copysign(float, double)"
argument types are: (int, double)

## Type of Issue
Compile Issue

## LAMMPS Version (Bug Report)
Latest master branch

Here are the modules we use:

gcc/5.3.0
cuda/8.0.44
openmpi/2.0.1

**Comment by akohlmey** [comment]
@stanmoore1 this one looks trivial to fix. just needs replacing the `copysign(1,...)` terms with `copysign(1.0,...)`.

if you create a PR, please also include the makefile fix from the mailing list. so we can do a 2 for 1.
```
diff --git a/src/Makefile b/src/Makefile
index eefc64b27..7d31c81c7 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -74,7 +74,7 @@ PACKSYS = compress mpiio python user-lb
 
 PACKINT = gpu kokkos meam message poems reax user-atc user-awpmd user-colvars
 
-PACKEXT = kim mscg voronoi \
+PACKEXT = kim latte mscg voronoi \
          user-h5md user-molfile user-netcdf user-qmmm user-quip \
          user-smd user-vtk
 
```

**Comment by stanmoore1** [comment]
Will do.
