### ISSUE TITLE
'create_atoms remap yes' can't handle atoms on/near the unit cell corner

### ISSUE THREAD

**Issue by ExpHP** [lammps/lammps#1158]
## Bug report

Very specific inputs to `create_atoms` will cause it to skip an atom even when `remap yes` is specified.

## Steps to Reproduce

**Run the following script and observe the output.**
```
processors * * 1
units metal
neigh_modify delay 0
atom_style atomic
thermo_modify lost error
atom_modify map array
atom_modify sort 0 0.0
boundary p p p
box tilt small
region sim prism 0 2 0 2 0 2 0 0 0
create_box 2 sim
mass 1 12.0107
mass 2 12.0107
pair_style none
change_box all x final 0 92.76975077446671 y final 0 80.34096087343929 z final 0 14
change_box all xy final -46.38487538723336 xz final 0 yz final 0

# Try to create atoms at -46.384875387233315 80.34096087343922
# and all 8 points around it with a grid spacing of 0.1

create_atoms 1 single -46.484875387233315 80.24096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.384875387233315 80.24096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.284875387233315 80.24096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.484875387233315 80.34096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.384875387233315 80.34096087343922 7 remap yes  # Created 0 atoms (!!!)
create_atoms 1 single -46.284875387233315 80.34096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.484875387233315 80.44096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.384875387233315 80.44096087343922 7 remap yes  # Created 1 atoms
create_atoms 1 single -46.284875387233315 80.44096087343922 7 remap yes  # Created 1 atoms
```

#### Actual behavior

The script attempts to produce an atom at `(-46.384875387233315, 80.34096087343922)` as well as 8 points around it.  As indicated from the program output in the comments, the eight surrounding points are created, but **the centermost is _not._**

Notably, this atom is practically sitting on the cell corner at (0, 1) in fractional space.

#### Expected behavior

Since all eight positions around it can be created, I would expect that the centermost one can be created as well.

## Digging deeper/Additional tidbits

I tried searching the closest nearby representable floating point numbers.  There are indeed other points *very close* to this point that `remap yes` similarly fails on.

<details>
<summary>Figure of nearby points that can't be created</summary>

**Legend**
* **Purple pixels:** `create_atoms remap yes` cannot produce an atom here
* **Yellow pixels:** `create_atoms remap yes` successfully created an atom here

Units are ULPs (nearest representable floats) and therefore not necessarily constant.

![bad_points](https://user-images.githubusercontent.com/1411280/46845827-22198680-cdab-11e8-87e6-8d11283a322b.png)

</details>

<details>
<summary>Fractional coords of those bad points in the image</summary>

This is what I see when I multiply the bad coords by the inverse of the lattice matrix **(not necessarily the same as the values seen by lammps during the remap process!).**  You may notice that there is a variety of values for `a2` coordinate, but not so many for the `a1` coordinate.

```
              a1                          a2
                       0.0         0.9999999999999946
     5.551115123125783e-17         0.9999999999999948
                       0.0         0.9999999999999949
    1.1102230246251565e-16         0.9999999999999949
    1.6653345369377348e-16         0.9999999999999949
                       0.0         0.9999999999999951
     5.551115123125783e-17         0.9999999999999951
    1.1102230246251565e-16         0.9999999999999953
                       0.0         0.9999999999999954
     5.551115123125783e-17         0.9999999999999954
     5.551115123125783e-17         0.9999999999999957
                       0.0         0.9999999999999958
     5.551115123125783e-17          0.999999999999996
                       0.0         0.9999999999999963
     5.551115123125783e-17         0.9999999999999963
    1.1102230246251565e-16         0.9999999999999966
                       0.0         0.9999999999999967
     5.551115123125783e-17         0.9999999999999967
     5.551115123125783e-17         0.9999999999999969
     5.551115123125783e-17         0.9999999999999972
   -1.6653345369377348e-16         0.9999999999999974
    -5.551115123125783e-17         0.9999999999999974
                       0.0         0.9999999999999974
                       0.0         0.9999999999999976
     5.551115123125783e-17         0.9999999999999976
                       0.0         0.9999999999999978
    1.1102230246251565e-16         0.9999999999999978
    1.6653345369377348e-16         0.9999999999999978
                       0.0         0.9999999999999979
     5.551115123125783e-17         0.9999999999999979
                       0.0         0.9999999999999981
    1.1102230246251565e-16         0.9999999999999981
    1.6653345369377348e-16         0.9999999999999981
     5.551115123125783e-17         0.9999999999999984
                       0.0         0.9999999999999987
     5.551115123125783e-17         0.9999999999999987
                       0.0         0.9999999999999988
     5.551115123125783e-17         0.9999999999999988
                       0.0          0.999999999999999
     5.551115123125783e-17         0.9999999999999992
    1.1102230246251565e-16         0.9999999999999992
                       0.0         0.9999999999999993
    1.1102230246251565e-16         0.9999999999999993
    1.6653345369377348e-16         0.9999999999999993
                       0.0         0.9999999999999996
     5.551115123125783e-17         0.9999999999999996
     5.551115123125783e-17         0.9999999999999997
                       0.0         0.9999999999999999
     5.551115123125783e-17         0.9999999999999999
    1.1102230246251565e-16         1.0000000000000002
   -1.1102230246251565e-16         1.0000000000000004
                       0.0         1.0000000000000004
                       0.0         1.0000000000000004
    1.1102230246251565e-16         1.0000000000000004
                       0.0         1.0000000000000009
                       0.0         1.0000000000000009
    1.1102230246251565e-16          1.000000000000001
    1.1102230246251565e-16          1.000000000000001
   -1.1102230246251565e-16         1.0000000000000013
                       0.0         1.0000000000000013
                       0.0         1.0000000000000013
                       0.0         1.0000000000000018
    1.1102230246251565e-16          1.000000000000002
    1.1102230246251565e-16         1.0000000000000022
    1.1102230246251565e-16         1.0000000000000022
    1.1102230246251565e-16         1.0000000000000024
                       0.0         1.0000000000000024
                       0.0         1.0000000000000024
   -1.1102230246251565e-16         1.0000000000000029
                       0.0         1.0000000000000029
                       0.0         1.0000000000000029
    1.1102230246251565e-16         1.0000000000000029
    1.1102230246251565e-16         1.0000000000000033
                       0.0         1.0000000000000033
                       0.0         1.0000000000000033
                       0.0         1.0000000000000036
                       0.0         1.0000000000000038
    1.1102230246251565e-16          1.000000000000004
```

The actual range of `a1` on the image goes from `-5e-15` to `5e-15` (much greater than the few values seen here!) while `a2` goes from `0.9999999999999939` to `1.0000000000000044`.

For this reason, I suspect that the issue lies specifically in the value of `a1` witnessed by lammps during the remap process. Perhaps it is something troublesome like `-1e-17`? (negative values smaller than epsilon are a pretty big troublemaker for code that tries to map numbers into `[0, 1)`)
</details>

---

## LAMMPS Version

Tested on latest master. 7faa48b4c38da81f47a541eaa163f8c74e6f3b6a (Oct 10 2018)

**Comment by ExpHP** [comment]
## Investigation

I did some print debugging and found the nature of the bug.

```c++
void Domain::remap(double *x, imageint &image)
{
  double *lo,*hi,*period,*coord;
  double lamda[3];
  imageint idim,otherdims;

  debug_vec3("remap1", x);
  if (triclinic == 0) {
    ...
  } else {
    ...
  }
  debug_vec3("remap2", coord);

  if (xperiodic) { ... }
  if (yperiodic) { ... }
  if (zperiodic) { ... }

  debug_vec3("remap3", coord);
  if (triclinic) lamda2x(coord,x);
  debug_vec3("remap4", coord);
}

void CreateAtoms::add_single()
{
  // remap atom if requested

  debug_vec3("single1", xone);
  if (remapflag) {
    imageint imagetmp = ((imageint) IMGMAX << IMG2BITS) |
      ((imageint) IMGMAX << IMGBITS) | IMGMAX;
    domain->remap(xone,imagetmp);
  }
  debug_vec3("single2", xone);

  // if triclinic, convert to lamda coords (0-1)

  double lamda[3],*coord;
  if (triclinic) {
    domain->x2lamda(xone,lamda);
    coord = lamda;
  } else coord = xone;

  debug_vec3("single3", coord);

  // if atom/molecule is in my subbox, create it

  if (coord[0] >= sublo[0] && coord[0] < subhi[0] &&
      coord[1] >= sublo[1] && coord[1] < subhi[1] &&
      coord[2] >= sublo[2] && coord[2] < subhi[2]) {
    if (mode == ATOM) atom->avec->create_atom(ntype,xone);
    else if (quatone[0] == 0.0 && quatone[1] == 0.0 && quatone[2] == 0.0)
      add_molecule(xone);
    else add_molecule(xone,quatone);
  }
}
```

```
single1: -46.384875387233314825 80.340960873439215106 7
remap1: -46.384875387233314825 80.340960873439215106 7
remap2: -5.5511151231257827021e-17 0.99999999999999922284 0.5
remap3: 0 0.99999999999999922284 0.5
remap4: 0 0.99999999999999922284 0.5
single2: -46.384875387233321931 80.340960873439229317 7
single3: -5.5511151231257827021e-17 0.99999999999999933387 0.5
```

Notice that remap4 is inside the box, and single3 is outside of it.  What this means is:

* LAMMPS correctly maps the fractional coordinates of this point into `[0, 1)`
* It then converts this into cartesian, and then back into fractional, and **incorrectly assumes that the result will still be in `[0, 1)`.**

**Comment by ExpHP** [comment]
Another note: Although I may appear to be singling out `create_atoms single` in the above posts, I believe various other methods of creating atoms are also affected.

The first time I ran into this was actually using the `lammps_create_atoms` C API function. (presumably, the issue there is in `Domain::ownatom`)

**Comment by akohlmey** [comment]
@sjplimp @athomps this looks like something one of you knows a lot about and thus should have a look at first.

**Comment by athomps** [comment]
This is a good analysis. All of the failures are occurring for points lying on the strip abs(a1) < eps, where eps is some lower bound on effective precision, say 1e-15. Let's replace a1 with u0 and u1, to indicate initial and final values of u=lamda[0]. Applying the operations lamda2x(lamda,x) followed by x2lamda(x,lamda) results in 0 < abs(u1-u0)<eps due to finite precision. This normally is of no consequence, but for points inside but close to the boundary of [0,1), two problems can occur: 

0 <= u0 < eps then -eps < u1 < eps        // occurs when atom created in strip 0 <= a1 < eps
1 > u0 > 1-eps then 1+eps > u1 > 1-eps  // occurs when atom created in strip 0 >   a1 > -eps

One solution to this problem would be to create a new version of lamda2x that would enforce bounds on u:

u = max(u,0)
u = min(u,umax)

Possibly the same effect could be achieved by just doing:

#define LAMDA0 1.0d0 // or some other value
u += LAMDA0
u -= LAMDA0
assuming the compiler is not smart enough to replace this with NO-OP

**Comment by ExpHP** [comment]
> One solution to this problem would be to create a new version of lamda2x that would enforce bounds on u:
>
> u = max(u,0)
> u = min(u,umax)
 
Personally speaking, I am wary of attempts to solve this sort of problem with clipping (even on the order of machine epsilon), because this would seem to be a biased form of rounding and hence possibly introduce analytical error.  But perhaps it's no big deal in the long run; I'm not sure.

If I were writing this, I would make `x2lamda` keep repeatedly doing `u -= floor(u)` at the end until it eventually *is* in `[0, 1)`.  This always happens eventually; a value like `-1e-18` maps to `1`; `1` maps to `0`; and a value like `-epsilon` maps to `1-epsilon`.  But the reason I can do this is because I only work with periodic systems;  I'm not sure what the correct answer is for something like lammps that supports non-periodic dimensions.

**Comment by athomps** [comment]
Yes, I agree that clipping is dangerous, and there are many cases where it is plain wrong.  However, the `do u -= floor(u)` is using a canon to kill a fly, it hurts performance, and can also fail to terminate if input is unusual.

**Comment by ExpHP** [comment]
Okay then, don't let me stop you from exercising your better judgement! :)  From a user's standpoint, this seems like a pretty ugly bug that's worth fixing however possible.

**Comment by sjplimp** [comment]
@ExpHP Nice analysis.  I think this is only an issue with create atom single, for
triclinic boxes and a periodic boundary.  Create atoms box has its own round-off logic,
and create atoms region explicitly says how it doesn't handle round-off (see doc page).
Also create_atom single for an orthogonal box would not have this issue due
to what domain->remap() does.

So I think the fix is simple: add 3 lines to CreateAtoms::single()

  if (triclinic) {
    domain->x2lamda(xone,lamda);
    if (domain->xperiodic && (lamda[0] < 0.0 || lamda[0] >= 1.0)) lamda[0] = 0.0;  // these 3 lines
    if (domain->yperiodic && (lamda[1] < 0.0 || lamda[1] >= 1.0)) lamda[1] = 0.0;
    if (domain->zperiodic && (lamda[2] < 0.0 || lamda[2] >= 1.0)) lamda[2] = 0.0;
    coord = lamda;
  } else coord = xone;

I'll post a PR.

**Comment by sjplimp** [comment]
Should have added this also is only an issue when the create atoms remap option is set.

**Comment by ExpHP** [comment]
The bug still remains in the C API function `lammps_create_atoms`.

```
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <lammps/library.h>

void main(int argc, char **argv) {
    MPI_Init(&argc, &argv);

    void *lmp;
    char * arg0 = "";
    lammps_open(1, &arg0, MPI_COMM_WORLD, &lmp);
    lammps_commands_string(lmp, "\n\
processors * * 1\n\
units metal\n\
neigh_modify delay 0\n\
atom_style atomic\n\
thermo_modify lost error\n\
atom_modify map array\n\
atom_modify sort 0 0.0\n\
boundary p p p\n\
box tilt small\n\
region sim prism 0 2 0 2 0 2 0 0 0\n\
create_box 2 sim\n\
mass 1 12.0107\n\
mass 2 12.0107\n\
pair_style none\n\
change_box all x final 0 92.76975077446671 y final 0 80.34096087343929 z final 0 14\n\
change_box all xy final -46.38487538723336 xz final 0 yz final 0\n\
");
    double x[] = {
        -46.284875387233315, 80.24096087343922, 7,
        -46.384875387233315, 80.24096087343922, 7,
        -46.484875387233315, 80.24096087343922, 7,
        -46.284875387233315, 80.34096087343922, 7,
        -46.384875387233315, 80.34096087343922, 7,
        -46.484875387233315, 80.34096087343922, 7,
        -46.284875387233315, 80.44096087343922, 7,
        -46.384875387233315, 80.44096087343922, 7,
        -46.484875387233315, 80.44096087343922, 7,
    };
    int type[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1 };
    lammps_create_atoms(lmp, 9, NULL, type, x, NULL, NULL, 1);

    int natoms = lammps_get_natoms(lmp);
    printf("There are now %d atoms.", natoms);
}
```

```
LAMMPS (10 Oct 2018)
  using 4 OpenMP thread(s) per MPI task
Created triclinic box = (0 0 0) to (2 2 2) with tilt (0 0 0)
  1 by 1 by 1 MPI processor grid
Changing box ...
  triclinic box = (0 0 0) to (92.7698 2 2) with tilt (0 0 0)
  triclinic box = (0 0 0) to (92.7698 80.341 2) with tilt (0 0 0)
  triclinic box = (0 0 0) to (92.7698 80.341 14) with tilt (0 0 0)
Changing box ...
  triclinic box = (0 0 0) to (92.7698 80.341 14) with tilt (-46.3849 0 0)
  triclinic box = (0 0 0) to (92.7698 80.341 14) with tilt (-46.3849 0 0)
  triclinic box = (0 0 0) to (92.7698 80.341 14) with tilt (-46.3849 0 0)
WARNING: Library warning in lammps_create_atoms, invalid total atoms 8 9 (src/library.cpp:1521)
There are now 8 atoms.
```

(expected output is 9 atoms)

**Comment by sjplimp** [comment]
@ExpHP can you try adding the same 3 lines to 

  if (triclinic) {
    x2lamda(x,lamda);
    coord = lamda;
  } else coord = x;

in Domain::ownatom(), to see if it fixes the lib interface as well?

**Comment by ExpHP** [comment]
I can verify that the following change fixes the issue.

```
From d6a3891e2f1355ae9d02a8d7564fe98186b781f0 Mon Sep 17 00:00:00 2001
From: Michael Lamparski <diagonaldevice@gmail.com>
Date: Thu, 18 Oct 2018 16:55:34 -0400
Subject: [PATCH] bug fix for lammps_create_atoms and triclinic

---
 src/domain.cpp | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/src/domain.cpp b/src/domain.cpp
index 8238ab7ee..987bc55c5 100644
--- a/src/domain.cpp
+++ b/src/domain.cpp
@@ -1625,6 +1625,12 @@ int Domain::ownatom(int /*id*/, double *x, imageint *image, int shrinkexceed)
 
   if (triclinic) {
     x2lamda(x,lamda);
+    if (domain->xperiodic && (lamda[0] < 0.0 || lamda[0] >= 1.0))
+      lamda[0] = 0.0;
+    if (domain->yperiodic && (lamda[1] < 0.0 || lamda[1] >= 1.0))
+      lamda[1] = 0.0;
+    if (domain->zperiodic && (lamda[2] < 0.0 || lamda[2] >= 1.0))
+      lamda[2] = 0.0;
     coord = lamda;
   } else coord = x;
 
-- 
2.19.0
```

**Comment by ExpHP** [comment]
P.S. I have only tested atom creation.  For now I am largely hoping that the parts of LAMMPS that do the actual physics do not depend too heavily on the result of `x2lamda` being in `[0, 1)`...
