### ISSUE TITLE
CMake make uses wrong directory for potentials

### ISSUE THREAD

**Issue by gvizkel** [lammps/lammps#1175]
## Summary

CMake install puts potentials into the wrong directory or set the LAMMPS_POTENTIALS variable to the wrong directory

## Type of Issue

'Bug Report'

## Detailed Description (Enhancement Suggestion)

N/A
## LAMMPS Version (Bug Report)

lammps-22Aug18

## Expected Behavior (Bug Report)

Directory for potentials and directory set by LAMMPS_POTENTIALS should be the same.

## Actual Behavior (Bug Report)

I used the CMake installation method to install lammps. After installation the potentials were placed in /usr/local/share/lammps/potentials/potentials and lamps.sh and lamps.csh were put into /usr/local/etc/profile.d which set LAMMPS_POTENTIALS to /usr/local/share/lammps/potentials. Obviously, running lammps with this results in potential not found error message. Actually, those scripts are not even executed when a new terminal window start, it has to be sourced from .profile.

## Steps to Reproduce (Bug Report)

Build lammps with CMake and install it.

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by junghans** [comment]
Addressed in #1083 already.
