### ISSUE TITLE
[Bug Report] wrong preprocessor condition in dump_vtk.cpp

### ISSUE THREAD

**Issue by danielque** [lammps/lammps#1196]
## Summary

The change made to the preprocessor directive in commit f394ed94f307b6c7a0fe874bc7c696d23ec511c2 is faulty.

## Type of Issue

'Bug Report'

## Detailed Description (Enhancement Suggestion)

The preprocessor condition https://github.com/lammps/lammps/blob/master/src/USER-VTK/dump_vtk.cpp#L98 is faulty.
The `#error` directive will not be reached by the preprocessor when the file will be compiled with a potential future VTK_MAJOR_VERSION > 8 since the case >8 is already covered by the preceding condition >=7 https://github.com/lammps/lammps/blob/master/src/USER-VTK/dump_vtk.cpp#L96

## LAMMPS Version (Bug Report)

f394ed94f307b6c7a0fe874bc7c696d23ec511c2

## Expected Behavior (Bug Report)

The `#error` directive will be reached by the preprocessor when an untested VTK_MAJOR_VERSION > 8 is used

## Actual Behavior (Bug Report)

The `#error` directive cannot be reached by the preprocessor.

## Steps to Reproduce (Bug Report)

```
#include <iostream>
using namespace std;

int main() {
#define VTK_MAJOR_VERSION 9
#if VTK_MAJOR_VERSION >= 7
  cout << "Hello World! >=7" << endl;
#elif VTK_MAJOR_VERSION > 8
#error This code has only been tested with VTK 5, 6, 7, and 8
#endif
  return 0;
}
```
## Further Information, Files, and Links

Suggested correction:
```
#if VTK_MAJOR_VERSION >= 7
#define InsertNextTupleValue InsertNextTypedTuple
#endif
#if (VTK_MAJOR_VERSION < 5 || VTK_MAJOR_VERSION > 8)
#error This code has only been tested with VTK 5, 6, 7, and 8
#endif
```

**Comment by akohlmey** [comment]
Bugfix is in PR #1197
