### ISSUE TITLE
Typo in doc/src/Build_basics.txt -> cmake ignores the variables

### ISSUE THREAD

**Issue by NicoMittenzwey** [lammps/lammps#1199]
The variables documented under "Choice of compiler and compile/link options" should be "FLAGS" not "FlAGS" - the later is ignored by cmake:

https://github.com/lammps/lammps/blob/1651a21f921df63c774cd316e24bd8f03bfb6edf/doc/src/Build_basics.txt#L140-L142

**Comment by akohlmey** [comment]
Thanks for reporting this. It will be corrected when pull request #1197 is merged.
