### ISSUE TITLE
[Documentation] fix nh time constants

### ISSUE THREAD

**Issue by martok** [lammps/lammps#1208]
A minor nitpick: the documentation for Nose-Hoover integration suggests values for Tdamp and Pdamp time constants, explaining:
>  A good choice for many models is a {Tdamp} of around 100 timesteps.  Note that this is NOT the same as 100 time units for most "units"_units.html settings.

The way I read that, the correct way to follow this suggestion would be using `$(100*dt)`.
However, the example commands use the suggested timestep counts 100/1000 as if the timestep length is 1 time unit, which they only are in the `real` unit system. In `metals` units, the used time constant would be 5 orders of magnitude larger than suggested.

I would suggest modifying the examples to be consistent with the recommended values, such as:
`fix 1 water npt temp 300.0 300.0 $(100.0*dt) iso 0.0 0.0 $(1000.0*dt)`

**Comment by akohlmey** [comment]
Thanks for the suggestion. This part of the documentation has been often misunderstood, regardless of how many times people have tried to rewrite it. This is a nice example for the use of immediate variables, too.
