### ISSUE TITLE
Bug in read_dump (or fix store/state) command

### ISSUE THREAD

**Issue by stukowski** [lammps/lammps#1218]
## Summary

When the ``read_dump`` command is invoked two times, each time reading the same input dump file, stored per-atom data may get corrupted. 

## Type of Issue

Bug report.

## LAMMPS Version (Bug Report)

Current master branch

## Expected Behavior (Bug Report)

Attached is an archive containing a short test case to demonstrate the issue. The LAMMPS script uses ``read_dump`` to load a system of atoms from an external file. It then uses ``fix store/state`` to permanently store a copy of the current XYZ atomic positions. It then calls ``read_dump`` again to read in the same dump file a second time, this time using the ``replace yes`` option. This operation should not alter the current positions of the atoms. The atomic coordinates should still match the ones stored by the ``fix store/state``. Whether or not this is the case is checked by dumping the current atomic positions along with the stored values of the fix to an output file.

## Actual Behavior (Bug Report)

When running the test case on a single processor, it yields the correct results: After the second invocation of ``read_dump`` the current atomic positions and the stored coordinates still match. However, when running the test case on two processors, a mismatch can be observed (see attached file ``output.2.dump``).

## Steps to Reproduce (Bug Report)

Run the attached test case with (at least) two MPI procs. Then check the second output file (``output.2.dump``). When the second and third column do not match, the problem was successfully reproduced. 

## Further Information, Files, and Links

I can only speculate whether this problem lies in the ``read_dump`` command or the ``fix store/state`` command. My feeling is that, during the second call to ``read_dump``, atoms get relabeled for some reason and loose their original unique ID tags. The fix doesn't seem to notice this relabeling of atoms -that's why its stored information becomes inconsistent. I'm not sure though why this only happens during parallel runs.

[test_case.zip](https://github.com/lammps/lammps/files/2605276/test_case.zip)

**Comment by sjplimp** [comment]
@stukowski Hi Alex - you're saying this happens with the original serial read_dump command
(read_dump2 as I recall in the new parallel read dump branch)?  So that it has nothing
to do with the new parallel commands?  But the (wrong) behavior of both the old and new
read_dump is the same for this test?

**Comment by stukowski** [comment]
I made another observation, which may be important:

As mentioned in the bug description above, my test case invokes ``read_dump`` twice: The first time with the ``add yes`` option, the second time with the ``replace yes`` option. After reading [the docs](https://lammps.sandia.gov/doc/read_dump.html) again, I learned that ``read_dump`` also supports an ``add keep`` option, which forces LAMMPS to use the atom IDs from the input dump file. After replacing ``add yes`` with ``add keep``, the problem is gone.

This makes me reconsider my initial assessment. Maybe there is no bug at all. I always assumed the unexpected shuffling of the atoms happened during the second ``read_dump`` call, but it may just have appeared like that due to the missing ``add keep`` flag during the first call. 

I will check if my custom analysis fix works correctly when I use the new ``read_dump`` and ``rerun`` commands in combination for post-processing parallel dump files. If you don't hear from me again today, you can close this issue. I apologize for overlooking the ``keep`` option.

**Comment by stukowski** [comment]
Please don't close this issue yet. There seems to be a problem concerning the ``add keep`` option of the ``read_dump`` command. When I do:

```
read_dump	input.dump 0 x y z box yes add yes 
print 		"NUMBER OF ATOMS: $(atoms)"
```
I see the following log output:
```
Scanning dump file ...
Reading snapshot from dump file ...
  orthogonal box = (0 0 0) to (6.71838 6.71838 6.71838)
  0 atoms before read
  11 atoms in snapshot
  0 atoms purged
  0 atoms replaced
  0 atoms trimmed
  11 atoms added
  11 atoms after read
NUMBER OF ATOMS: 11
```
My dump file indeed contains 11 atoms. So this looks good.

However, when I instead use ``add keep``:
```
read_dump	input.dump 0 x y z box yes add keep 
print 		"NUMBER OF ATOMS: $(atoms)"
```
I see the following output:
```
Reading snapshot from dump file ...
  orthogonal box = (0 0 0) to (6.71838 6.71838 6.71838)
  0 atoms before read
  11 atoms in snapshot
  0 atoms purged
  0 atoms replaced
  0 atoms trimmed
  11 atoms added
  0 atoms after read
NUMBER OF ATOMS: 0
```

That's unexpected. LAMMPS seems to be left in an invalid state. As soon as I do a ``run 0`` now, I get the following error:
```
ERROR: Lost atoms: original 0 current 11 (../thermo.cpp:442)
```
That's not good, right?

**Comment by stukowski** [comment]
I think the problems lies in the following code line, which only gets executed if add==yes but not if add==keep:

https://github.com/lammps/lammps/blob/6e8c5375646b15d1bafbf8b08acec73728caf53f/src/read_dump.cpp#L487

**Comment by sjplimp** [comment]
@stukowski yes, I think that is the issue - good catch!  I will change this in the new read-dump-parallel
branch and also post a separate PR to fix it in master LAMMPS.  That way it will make it into
the upcoming stable release.  The parallel read dump PR will not be merged until (right) after the
stable (I believe that is Axel's plan).
