### ISSUE TITLE
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1224]
## Summary

GPU package fails to compile with:
```
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
```

## Type of Issue

Something is wrong with the way how the `CXXFLAGS` got injected.
```
-- Generating dependency file: 
/home/chakraborty/lammps-22Aug18/build-cuda/CMakeFiles/cuda_compile.dir/__/lib/gpu/cudpp_mini/cuda_compile_generated_radixsort_app.cu.o.NVCC-depend
/usr/local/cuda-7.0/bin/nvcc -M -D__CUDACC__ 
/home/chakraborty/lammps-22Aug18/lib/gpu/cudpp_mini/radixsort_app.cu -o 
/home/chakraborty/lammps-22Aug18/build-cuda/CMakeFiles/cuda_compile.dir/__/lib/gpu/cudpp_mini/cuda_compile_generated_radixsort_app.cu.o.NVCC-depend 
-m64 -DLAMMPS_SMALLBIG -DLAMMPS_MEMALIGN=64 -DLAMMPS_JPEG -DLAMMPS_GZIP 
-DLAMMPS_FFMPEG -Xcompiler ,\"-fopenmp\",\"-O3\",\"-DNDEBUG\" 
$<$<BOOL:>:-Xcompiler=-fPIC> -DUNIX -O3 -Xptxas -v --use_fast_math 
-DUCL_CUDADR -arch=sm_30 -D_SINGLE_DOUBLE -DNVCC 
-I/home/chakraborty/lammps-22Aug18/lib/gpu 
-I/home/chakraborty/lammps-22Aug18/build-cuda/lib/gpu 
-I/home/chakraborty/lammps-22Aug18/lib/gpu/cudpp_mini 
-I/usr/local/cuda-7.0/include -I/usr/lib/openmpi/include 
-I/usr/lib/openmpi/include/openmpi -I/usr/include
nvcc fatal?? : A single input file is required for a non-link phase when 
an outputfile is specified
CMake Error at cuda_compile_generated_radixsort_app.cu.o.cmake:207 
(message):
 ? Error generating
/home/chakraborty/lammps-22Aug18/build-cuda/CMakeFiles/cuda_compile.dir/__/lib/gpu/cudpp_mini/./cuda_compile_generated_radixsort_app.cu.o
```

## Detailed Description (Enhancement Suggestion)

We require cmake-3.1 for the GPU package so I am not why `$<$<BOOL:>:-Xcompiler=-fPIC>` didn't get expanded.

## LAMMPS Version (Bug Report)

15-Nov-2018

## Expected Behavior (Bug Report)

Builds.

## Actual Behavior (Bug Report)

Fails to build.

## Steps to Reproduce (Bug Report)

On Ubuntu 12.04:
```
cmake -D PKG_GPU=yes -D GPU_API=cuda -DGPU_PREC=mixed -D GPU_ARCH=sm_61 ../cmake
make
```

## Further Information, Files, and Links

https://sourceforge.net/p/lammps/mailman/lammps-users/thread/CADTmJ6GZaWxiJP%2BShjUkoZvN7wRo19ym67JSbUyNtw4RV9p5%3Dw%40mail.gmail.com/#msg36477262

**Comment by junghans** [comment]
@akohlmey @rbberger any ideas?

**Comment by akohlmey** [comment]
could it be a bug in the cmake version on ubuntu 12.04?

**Comment by akohlmey** [comment]
a simple workaround would be to always set -fPIC. it does no harm, and i would use it for all libraries anyway (on Linux). That way even libXXX.a can be used to build a shared object (on Linux). On windows, it is not needed, since -fPIC is the default for all objects.

**Comment by akohlmey** [comment]
another workaround would be to not use the inline expansion, but wrap the command into an if()/else()/endif() block.

**Comment by junghans** [comment]
According to https://packages.ubuntu.com/precise/allpackages Ubuntu 12.04 comes with `cmake-2.8.7`, but we require `cmake-2.8.12` in general and `cmake-3.1` for the GPU package specifically.

**Comment by akohlmey** [comment]
but the user wrote:
```
I have tried cuda-7 as well as cuda 8. The cards are K20M and K40. cmake version is 3.4 and gcc 4.8
```

**Comment by junghans** [comment]
Beside the `$<$<BOOL:>:-Xcompiler=-fPIC>`, I also worried about this part `,\"-fopenmp\",\"-O3\",\"-DNDEBUG\"` - the quotes aren't correct I think.

**Comment by akohlmey** [comment]
They don't seem to do any harm, though: here is what i get locally. (cuda 9.1, gcc 4.9, cmake 3.12)
```
#$ gcc -D__CUDA_ARCH__=610 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  "-fopenmp" "-O2" "-DNDEBUG" -O3 -I"/home/akohlmey/compile/lammps/lib/gpu" -I"/home/akohlmey/compile/lammps/build-gpu/lib/gpu" -I"/home/akohlmey/compile/lammps/lib/gpu/cudpp_mini" -I"/usr/local/cuda-9.1/include" -I"/home/akohlmey/compile/lammps/src" -I"/usr/include/mpich-x86_64" -I"/usr/include" "-I/usr/local/cuda-9.1/bin/../targets/x86_64-linux/include"   -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -D"LAMMPS_SMALLBIG" -D"LAMMPS_MEMALIGN=64" -D"LAMMPS_JPEG" -D"LAMMPS_PNG" -D"LAMMPS_GZIP" -D"LAMMPS_FFMPEG" -D"UNIX" -D"UCL_CUDADR" -D"_SINGLE_DOUBLE" -D"NVCC" -include "cuda_runtime.h" -m64 "/home/akohlmey/compile/lammps/lib/gpu/cudpp_mini/radixsort_app.cu" > "/tmp/tmpxft_00000992_00000000-6_radixsort_app.cpp1.ii" 
#$ cicc --gnu_version=40903 --allow_managed   -arch compute_61 -m64 -ftz=1 -prec_div=0 -prec_sqrt=0 -fmad=1 -fast-math --gen_div_approx_ftz --include_file_name "tmpxft_00000992_00000000-2_radixsort_app.fatbin.c" -tused -nvvmir-library "/usr/local/cuda-9.1/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "/tmp/tmpxft_00000992_00000000-3_radixsort_app.module_id" --orig_src_file_name "/home/akohlmey/compile/lammps/lib/gpu/cudpp_mini/radixsort_app.cu" --gen_c_file_name "/tmp/tmpxft_00000992_00000000-5_radixsort_app.cudafe1.c" --stub_file_name "/tmp/tmpxft_00000992_00000000-5_radixsort_app.cudafe1.stub.c" --gen_device_file_name "/tmp/tmpxft_00000992_00000000-5_radixsort_app.cudafe1.gpu"  "/tmp/tmpxft_00000992_00000000-6_radixsort_app.cpp1.ii" -o "/tmp/tmpxft_00000992_00000000-5_radixsort_app.ptx"
#$ ptxas -arch=sm_61 -m64 -v  "/tmp/tmpxft_00000992_00000000-5_radixsort_app.ptx"  -o "/tmp/tmpxft_00000992_00000000-7_radixsort_app.sm_61.cubin" 
```

**Comment by junghans** [comment]
@akohlmey ok that is good information. So then the questions is mainly why is the generator expression not expanded. However we could easily fix that with an `if()` in all places.

**Comment by akohlmey** [comment]
@junghans please check out the PR i just submitted and requested you to review. This implements the workaround with an if, but also builds "fat" binaries, so that it will support any GPU supported by the CUDA toolkit (updated for CUDA 10). I've tried it successfully with CUDA 7.5, 8.0, 9.1 on a GeForce GTX 1060. By making either `sm_20` or `sm_30` the CUDA_ARCH, it would work with 8.0 and 9.1, but not with 7.5. This should help with packaging and deployment on GPU clusters with multiple architectures.
