### ISSUE TITLE
segmentation fault with stress/mop/profile and atom_style sphere

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#1236]
## Summary

LAMMPS crashes with a segmentation fault when trying to compute the kinetic contribution to the stress profile of a system with "atom_style sphere" using the command "compute stress/mop/profile ... kin" 

## Type of Issue

'Bug Report' 

## LAMMPS Version (Bug Report)

Obtained from master branch of GitHub at 30/11/2018

## Expected Behavior (Bug Report)

The simulation should not crash

## Actual Behavior (Bug Report)

The system crashes.

## Steps to Reproduce (Bug Report)

The input files to reproduce the crash are contained in the attached zip file. 
[MOP_sphere.zip](https://github.com/lammps/lammps/files/2633181/MOP_sphere.zip)

## Further Information, Files, and Links

If the "stress/mop/profile" command computes the configurational contribution to the stress tensor then the system does not crash and the simulation proceeds smoothly.

**Comment by akohlmey** [comment]
Thanks for reporting. This is easy to address. The original code only considers per-atom-type masses and not systems with per-atom masses.
