### ISSUE TITLE
Some LAMMPS styles don't support suffixes

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#1256]
## Summary

Some fix/pair/compute styles in LAMMPS don't support suffixes because they check for an exact match. This causes erroneous error messages that prevent the simulation from running. For example, see #1255.

## Type of Issue

Bug report

## LAMMPS Version (Bug Report)

Latest master

## Expected Behavior (Bug Report)

LAMMPS styles should support suffixes.

## Actual Behavior (Bug Report)

LAMMPS stops running with a false error message.

**Comment by akohlmey** [comment]
In addition, existing checks have to be reviewed whether they are too easily resulting in false positives, e.g. by using strstr() instead of strncmp().

**Comment by akohlmey** [comment]
This is mostly done, but leaving the issue open as a reminder for further checks and reviews.

**Comment by akohlmey** [comment]
More corrections were done since the last stable release. We should be consistent now.
