### ISSUE TITLE
packages for LAMMPS stable release 12 Dec 2018 

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1257]
For @junghans 

- [x] OpenSuse: https://build.opensuse.org/request/show/657604
- [x] Fedora: https://src.fedoraproject.org/rpms/lammps/c/d8f9b52134c7eee374aea19da462360d4a27634c?branch=master
  - [x] Fedora 30 (Rawhide): https://koji.fedoraproject.org/koji/taskinfo?taskID=31427417
  - [x] Fedora 29: https://bodhi.fedoraproject.org/updates/FEDORA-2018-85d05cb3cc
  - [x] Fedora 28: https://bodhi.fedoraproject.org/updates/FEDORA-2018-8f21cadc22
  - [x] Fedora 27 - EOL'ed, not possible anymore
  - [x] CentOS 7: https://bodhi.fedoraproject.org/updates/lammps-20181212-1.el7
- [x] Gentoo: https://github.com/gentoo/gentoo/commit/3a5bbf86514d6eb517273f02365cca3025b89e8a
- [x] Spack: https://github.com/spack/spack/pull/10086

For @gladk
- [x] Debian package

For @akohlmey 
- [x] Windows installer packages

For @rbberger & @junghans 
- [x] Docker (also see https://github.com/lammps/lammps/pull/892)

**Comment by junghans** [comment]
@akohlmey, could you make a `patch_12Dec2018` tag as well? (Gentoo and Spack relies on that.)

**Comment by junghans** [comment]
Could you also tag a version in https://github.com/lammps/lammps-testing, which works with that release?

**Comment by akohlmey** [comment]
> Could you also tag a version in https://github.com/lammps/lammps-testing, which works with that release?

that is @rbberger 's domain

**Comment by junghans** [comment]
That raises an interesting question, too, as long as we don't want to guarantee that all future version of the tests will work with any past lammps release, we shouldn't hard-code 
 `master` here: https://github.com/lammps/lammps/blob/master/cmake/CMakeLists.txt#L252

**Comment by akohlmey** [comment]
i do not consider that an interesting question. LAMMPS is a moving target and so are these tests. we put them on github for convenience and as a backup. there are no guarantees of any suitability of any use by others. in fact, i am extremely happy that @rbberger keeps them working and even improves them despite his busy work schedule over the last 2 years and recurring changes that break them (i just broke them again with a pending PR), so i can merge changes and publish releases with more confidence and less guesswork than @sjplimp had to depend on in the past. Please keep in mind, that this is a (mostly) volunteer effort.

**Comment by junghans** [comment]
Ok, then I as the package maintainer just pick https://github.com/lammps/lammps-testing/commit/7869c75cac38cb8a3d2ef7747ea12ec5812f5151 to be included in the rpm.

**Comment by gladk** [comment]
Done. 

* [PPA-lammps-stable](https://launchpad.net/~gladky-anton/+archive/ubuntu/lammps/+packages)
* [Debian Buster](https://packages.debian.org/buster/lammps)
* [Debian Stretch](https://packages.debian.org/stretch-backports/lammps)

**Comment by junghans** [comment]
All done, but docker!

**Comment by rbberger** [comment]
See https://cloud.docker.com/u/lammps/repository/docker/lammps/lammps
