### ISSUE TITLE
USER-OMP and KOKKOS broken after optimizations to child classes

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#126]
The recent changes to lj/charmm/coul/* styles from PR #124 break USER-OMP and KOKKOS with multiple threads as reported by the internal regression testing at SNL. e.g. bench/in.rhodo is reported to result in NaNs.

**Comment by akohlmey** [comment]
update: it looks like the changes in #124 only triggered the issue and the real cause is elsewhere, possibly fix shake...

**Comment by ibethune** [comment]
Can I see the outputs of the regression tester?  I experimented a bit locally, and saw a NaN appear in the pair timings, but not in the actual energies... is that what the regtests showed?

Do you want me to try to debug, but if the bug is elsewhere in code I don't know it might take some time?

```
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 24.936     | 24.936     | 24.936     |   nan | 72.78
Bond    | 1.3045     | 1.3045     | 1.3045     |   0.0 |  3.81
```

**Comment by akohlmey** [comment]
i don't have access to those outputs myself. i could confirm and resolve an issue in fix shake, but there seems to be something else. i'm attaching valgrind outputs from a non-openmp serial compile.
running:
``` cd bench; valgrind lmp_serial -in in.rhodo -sf omp```
and:
```cd examples/peptide; valgrind  lmp_serial -in in.peptide -sf omp```

[peptide-serial.txt](https://github.com/lammps/lammps/files/387129/peptide-serial.txt)
[rhodo-serial.txt](https://github.com/lammps/lammps/files/387133/rhodo-serial.txt)

**Comment by akohlmey** [comment]
Found it! will push fix later after some more testing.

**Comment by ibethune** [comment]
Great!
