### ISSUE TITLE
Package command line switch ignored if no Suffix given

### ISSUE THREAD

**Issue by martok** [lammps/lammps#1260]
## Bug Report
The `-pk/-package` command line switch is silently ignored when no `-sf/-suffix` is set. While this does make a certain amount of sense, it is contrary to the documentation, which sounds very much like the two are independent.

This is caused by [this check](https://github.com/lammps/lammps/blob/master/src/lammps.cpp#L765). I think it's just a matter of replacing the immediate return with a block around the suffix access, but I would assume there was a good reason why it was done the way it was?

## Steps to Reproduce
For example, forcing an explicit `omp_set_num_threads(1)` via the `-pk` switch does not work as expected:
```
$ export OMP_NUM_THREADS=6
$ lammps-serial -pk omp 1 -i ttttt.lmp
LAMMPS (12 Dec 2018)
  using 6 OpenMP thread(s) per MPI task
  using 6 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 3.6 3.6 3.6
```
If a suffix is given (in fact, it doesn't even matter which one!), it works:
```
$ lammps-serial -sf anysuffix -pk omp 1 -i ttttt.lmp
LAMMPS (12 Dec 2018)
  using 6 OpenMP thread(s) per MPI task
set 1 OpenMP thread(s) per MPI task
using multi-threaded neighbor list subroutines
  using 1 OpenMP thread(s) per MPI task
using multi-threaded neighbor list subroutines
Lattice spacing in x,y,z = 3.6 3.6 3.6
```

## Further Information, Files, and Links

[Docs: -pk](https://lammps.sandia.gov/doc/Run_options.html#package)
[Docs: -sf](https://lammps.sandia.gov/doc/Run_options.html#suffix)

**Comment by akohlmey** [comment]
> ## Bug Report
> The `-pk/-package` command line switch is silently ignored when no `-sf/-suffix` is set. While this does make a certain amount of sense, it is contrary to the documentation, which sounds very much like the two are independent.
> 
> This is caused by [this check](https://github.com/lammps/lammps/blob/master/src/lammps.cpp#L765). I think it's just a matter of replacing the immediate return with a block around the suffix access, but I would assume there was a good reason why it was done the way it was?

The only reason i can think of, would be that nobody has considered, that somebody would want to use the package command without the suffix flag. This feature was implemented for a package that doesn't exist anymore, and then incrementally expanded. With the last refactoring, it has become quite flexible and systematic across packages.

I agree, the current behavior is not satisfactory. Either LAMMPS should refuse to accept the package flag without a suffix flag (and error out plus the change in the documentation), or accept each flag independently with the change you are proposing. I have to look at the code for a little bit, but I think allowing both flags to be used independently, is preferable, even though it will be rarely used.

**Comment by martok** [comment]
That makes sense.
I only noticed it for consecutive liblammps uses from python, where OpenMP gets confused if the settings are to be changed from serial to thread-parallel and back and no explicit call seemed to work.
