### ISSUE TITLE
[Feature Request] CMake should automatically regenerate "style_XXX.h" files

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1278]
## Summary

CMake based builds should automatically update the various "style_XXX.h" file when corresponding source files are added, renamed, or removed. Right now one has to explicitly execute `cmake .` to trigger this and avoid missing styles in the executable or error messages.

## Type of Issue

Enhancement

## Detailed Description (Enhancement Suggestion)

After running in `src`, e.g.
```bash
sed -e 's,PairLJCut,PairLJ2Cut,g' -e 's,pair_lj_cut.h,pair_lj2_cut.h,g' -e 's,lj/cut,lj2/cut,g' -e 's,PAIR_LJ_CUT_H,PAIR_LJ2_CUT_H,' pair_lj_cut.h > pair_lj2_cut.h
sed -e 's,PairLJCut,PairLJ2Cut,g' -e 's,pair_lj_cut.h,pair_lj2_cut.h,g' -e 's,lj/cut,lj2/cut,g' -e 's,PAIR_LJ_CUT_H,PAIR_LJ2_CUT_H,' pair_lj_cut.cpp > pair_lj2_cut.cpp
```
There `style_pair.h` needs to be updated, and that would trigger recompilation of `force.o` and `lammps.o`. This currently does not happen. One has to explicitly run `cmake .`
Similarly, when deleting the added sources *after* running `cmake .` an error happens:
```txt
[ 19%] Building CXX object CMakeFiles/lmp.dir/home/akohlmey/compile/lammps/src/force.cpp.o
In file included from /home/akohlmey/compile/lammps/src/force.cpp:22:
/home/akohlmey/compile/lammps/build/styles/style_pair.h:165:10: fatal error: pair_lj2_cut.h: No such file or directory
 #include "pair_lj2_cut.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lmp.dir/build.make:2533: CMakeFiles/lmp.dir/home/akohlmey/compile/lammps/src/force.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/lmp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
The conventional build handles this transparently.

At the very least, this should be properly documented, but it would be nicer to have CMake based builds behave equivalent to the conventional build.  To avoid spurious recompiles, the conventional build rebuilds all `style_XXX.h` files to a temporary name and renames them to the proper name only, if they differ from the existing files.

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by junghans** [comment]
That might be a hard call, if you add `cpp` files CMake doesn't recognize that automatically even if the whole directory was globbed. One could certainly add a magic dependency on some hidden file to always re-trigged a CMake rerun (and hence re-generation of `style_XXX.h` files), but that doesn't feel right to me.

**Comment by akohlmey** [comment]
@sjplimp what is your take on this? if i understand correctly, we would have the choice to either always trigger running `cmake .` at the beginning of each call to `make` to make CMake compilation work like the conventional make builds, which would be somewhat excessive. Or one would have to explicitly call `cmake .` when files are added or removed, which may be somewhat inconvenient and in some cases catch people unaware (see below). 

@junghans do you think it is possible to add some code to trigger an automatic run of `cmake .` in case the hash for the HEAD commit has changed? This would be when updating the checkout with either `git pull`, switching branches with `git checkout` or committing new code. Especially the case of `git pull` could catch less experienced people unaware, as there may be new features (styles) added to LAMMPS but they don't get included automatically in the CMake based builds.

Regardless of the choice, the behavior should be documented as it will differ from how things are handled in the conventional build, where for example 'make package-update' may be required, which does happen with CMake, where no copies of source files need to be maintained.

**Comment by junghans** [comment]
The more I think about it, the less I think re-triggering `cmake` at `make` time automatically is the CMake :tm: way! (Maybe @bradking disagrees).

I guess we could generate the style header at `make` time using something like `add_custom_command(OUTPUT style_XXX.h COMMAND ...)`, but I am not sure how hard that is, maybe @rbberger has more insights.

**Comment by rbberger** [comment]
@akohlmey @junghans I found a mechanism that we might be able to use. I'm not there yet, but I'm now catching at least style header renames and touching style header files. All of these will trigger a configuration run first. See commit above.

**Comment by akohlmey** [comment]
after multiple discussions, i don't see much of a chance to make this work beyond what is currently covered (which is quite a lot). Since this is primarily for development, i'm now looking into implementing what is needed beyond what we have through git hooks.
