### ISSUE TITLE
Use print command but print nothing

### ISSUE THREAD

**Issue by njzjz** [lammps/lammps#1280]
## Summary

I used [print command](https://lammps.sandia.gov/doc/print.html) but nothing appeared on the screen.

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

12 Dec 2018

## Expected Behavior (Bug Report)

The input file was just:
```
print 'test'
```

`test` would be appeared on the screen as expected.

## Actual Behavior (Bug Report)

However, the output on the screen was only:
```
LAMMPS (12 Dec 2018)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:87)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
```
but nothing was printed.

## Steps to Reproduce (Bug Report)

My Lammps is installed by running `cmake ../cmake/ -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DCMAKE_Fortran_COMPILER=ifort -DPKG_USER-INTEL=yes -DPKG_USER-REAXC=yes -DBUILD_OMP=yes -DBUILD_LIB=on -DBUILD_SHARED_LIBS=on -DPKG_PYTHON=on`

**Comment by akohlmey** [comment]
please let us know which version of the intel compiler you are using, which OS/Platform/version you are running on, and what the exact command line is, that you use to run the example. also please make certain, that you have an "end-of-line" in your input (just add a few empty lines).
This same input works as expected on LAMMPS compiled with gcc 8.x on Fedora Linux.

**Comment by njzjz** [comment]
I find what is wrong. When I run `lmp<in.lammps`, nothing is printed. But if I run `lmp -in in.lammps`, here is the result:
```
LAMMPS (12 Dec 2018)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:87)
  using 1 OpenMP thread(s) per MPI task
test
Total wall time: 0:00:00
```

So why cannot `lmp<in.lammps` work?

My system is CentOS 6.8 and my intel compiler version is 2019.0.

**Comment by akohlmey** [comment]
must be an issue with the intel compiler or the MPI library used not handline I/O redirection properly. It is obviously not a LAMMPS issue, since both options work with several other compilers and MPI libs.
