### ISSUE TITLE
automatic deploy of rpms

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1281]
## Summary

When playing around with last stable release on Fedora, I had a look at https://copr.fedorainfracloud.org/, which basically allows continuous deployment of rpms for fedora 27-30, epel 6 & 7, magela and OpenSuse.

## Type of Issue

Suggestion

## Detailed Description (Enhancement Suggestion)

A more detailed description on what can be done, can found here: https://pavel.raiskup.cz/blog/copr-ci-and-custom-source-method.html

I would go for Option 2 and trigger the a package build foreach commit going on master (or release tag?) via a webhook. The webhook wouldn't interfere with our current CI, on the downside there is also no status reporting back to GitHub. On the plus side it would give us testing on a bunch more platforms and architectures (x86_64, i386 and ppc64le).  

I am happy to give it a shot, but I don't want to waste my time either, so @rbberger @akohlmey what do you think?

**Comment by akohlmey** [comment]
Don't think the benefit is significant to warrant the effort. If LAMMPS gets broken on ppc64le, I would expect the folks at ORNL or alike will tell us about it immediately.
