### ISSUE TITLE
[Feature Request] Help implementing a new particle-to-mesh variable

### ISSUE THREAD

**Issue by tabedzki** [lammps/lammps#1345]
**Summary**

I am looking into implementing new fields in LAMMPS to capture chi interactions and density fields of block copolymers to perform something akin to self-consistent field theory with dynamics. Is there an easy way to take the particle to mesh transformation that exists for Coulomb interactions and apply it to  a newly created field? What I am looking for is the documentation that specifies how the Coulomb interactions works using kspace interactions and how to properly apply it for other fields (if the foundation to do it is already specified), and if its not possible as is right now, the part of the code that could be modified to implement this. 

Thanks in advance.

**Comment by akohlmey** [comment]
> **Summary**
> 
> I am looking into implementing new fields in LAMMPS to capture chi interactions and density fields of block copolymers to perform something akin to self-consistent field theory with dynamics. Is there an easy way to take the particle to mesh transformation that exists for Coulomb interactions and apply it to a newly created field?

an easy way? no.

> What I am looking for is the documentation that specifies how the Coulomb interactions works using kspace interactions and how to properly apply it for other fields (if the foundation to do it is already specified), and if its not possible as is right now, the part of the code that could be modified to implement this.

the documentation you look for is the source code. the code that computes the (smeared out) charge distribution on a (polynomial) mesh is in the PPPM class and the classes/functions it calls. for details, you must study the sources. i suggest you start by reading the pppm.h header and then read pppm.cpp

> 
> Thanks in advance.

**Comment by tabedzki** [comment]
Alright. Thanks for suggesting which files.

**Comment by akohlmey** [comment]
> Alright. Thanks for suggesting which files. Where does the Coulomb forces implement the pppm scheme?

@tabedzki can we please move this discussion to the lammps-users mailing list? This may be of interest to more people and the mailing list is archived and well searchable via google. We prefer to have GitHub issues to be focused on either bugs or specific feature requests or specific development related issues. More concept related discussions are better done on the mailing list, where they are also more visible to other LAMMPS developers and users that may want to weigh in.

If you agree, please also close this issue. Thanks.

**Comment by tabedzki** [comment]
Sorry didn't know this was the wrong place. Will do

**Comment by akohlmey** [comment]
> Sorry didn't know this was the wrong place. Will do

no worries. it is not always obvious which is the preferred path.
