### ISSUE TITLE
[BUG]  internal variable type: deleting a variable causes side effects on other variables

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1346]
**Summary**

When a variable of internal type is deleted, variables of internal type that were defined after it have their references shifted. This also happens when the variable is of loop type and is deleted via the next command.

**LAMMPS Version and Platform**

This has been confirmed with the latest master version.

**Steps to Reproduce**

Run the following script:
```
variable v1 internal 1
variable dummy  internal 101
variable v2 internal 2
variable v3 internal 3

print "${v1} ${v2} ${v3}"
variable dummy delete
print "${v1} ${v2} ${v3}"
```

**Expected Behavior**
The expected output is:
> 1 2 3
> 1 2 3

**Actual Behavior**
The actual output is:
> 1 2 3
> 1 101 2

**Comment by akohlmey** [comment]
@donatas-surblys thanks for the report. a fix is underway and should be included in the next patch release.
