### ISSUE TITLE
meam and reax still in standard packages in lammps

### ISSUE THREAD

**Issue by tyst3273** [lammps/lammps#1349]
**Summary**

When compiling lammps from source with the 12Dec2018 tar file on linux, if I include all standard packages with 'make yes-std', It will not compile. It returns an error related to not finding files for MEAM and REAX packages. As I understand it, these packages are deprecated, having been replaced by the user packages MEAMC and REAXC and are no longer supposed to be included (according to the documentation ). 

"A pair style for the modified embedded atom (MEAM) potential translated from the Fortran version in the (obsolete) “MEAM” package to plain C++. The USER-MEAMC fully replaces the MEAM package, which has been removed from LAMMPS after the 12 December 2018 version."

**LAMMPS Version and Platform**

LAMMPS version 12Dec18, downloaded today (02.26.2019) on Ubuntu 18.04, Intel Xeon

make[1]: Entering directory '/home/ty/program_files/lammps/lammps-12Dec18/src'
Gathering installed package information (may take a little while)
make[1]: Leaving directory '/home/ty/program_files/lammps/lammps-12Dec18/src'
Compiling LAMMPS for machine ty
make[1]: Entering directory '/home/ty/program_files/lammps/lammps-12Dec18/src/Obj_ty'
Makefile.package.settings:4: ../../lib/reax/Makefile.lammps: No such file or directory
Makefile.package.settings:5: ../../lib/meam/Makefile.lammps: No such file or directory
make[1]: *** No rule to make target '../../lib/meam/Makefile.lammps'.  Stop.
make[1]: Leaving directory '/home/ty/program_files/lammps/lammps-12Dec18/src/Obj_ty'
make[1]: Entering directory '/home/ty/program_files/lammps/lammps-12Dec18/src/Obj_ty'
Makefile.package.settings:4: ../../lib/reax/Makefile.lammps: No such file or directory
Makefile.package.settings:5: ../../lib/meam/Makefile.lammps: No such file or directory
make[1]: *** No rule to make target '../../lib/meam/Makefile.lammps'.  Stop.
make[1]: Leaving directory '/home/ty/program_files/lammps/lammps-12Dec18/src/Obj_ty'
Makefile:176: recipe for target 'ty' failed
make: *** [ty] Error 2

**Expected Behavior**

I expected lammps to compile without automatically including meam and reax in the standard packages

**Actual Behavior**

meam and reax are included in the standard packages and lammps wont compile without removing them (make no-meam ; make no-reax)

**Steps to Reproduce**

Download the 12Dec2018 tar file and try to compile lammps with all standard packages. 
i.e. make yes-std
make *machine*

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by akohlmey** [comment]
@tyst3273 you are not correct. MEAM and REAX are **still** included in the stable 12 Dec 2018 release. They were removed **after** that release. The issue you are seeing is because you did not follow the installation instructions properly. Both, reax and meam require to first compile a fortran library in the lib/reax and lib/meam folder and then provide a suitable Makefile.lammps file with settings for the fortran compiler used so those libraries can be linked correctly when the packages are added in src. Everything is normal, there is no bug. You just need to read the instructions to compile LAMMPS more carefully.

**Comment by tyst3273** [comment]
Ah! I miss understood 'after' to mean inclusively. In any case, there no longer exists any documentation on meam or reax in the standard package list and the links for meam and reax (elsewhere in the documentation, e.g. https://lammps.sandia.gov/doc/pair_meam.html) return a 404 error.

**Comment by akohlmey** [comment]
The online documentation always reflects the latest patch release, not the stable release. It says so at the beginning.
