### ISSUE TITLE
[BUG] 'group id include molecule' leads to segfault for atom_styles without molecule

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#1362]
**Summary**

Using command `group id include molecule` leads to a segmentation fault when atom_style does not have mol attribute. 

**LAMMPS Version and Platform**

28 Feb 2019, Linux Mint 19

**Expected Behavior**

LAMMPS should raise an error for this situation.

**Actual Behavior**

LAMMPS crashes with a segmentation fault.

**Steps to Reproduce**

Run code below.

region              universe sphere 0 0 0 10
create_box      1 universe
create_atoms  1 random 200 343 universe
group               delete id < 10
group               delete include molecule

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by akohlmey** [comment]
thanks for the report. this is not the only group command option resulting in segfaults when using unavailable atom properties. should be addressed in #1361
