### ISSUE TITLE
[BUG] Possible problem in dump_modify pbc

### ISSUE THREAD

**Issue by mbaeker** [lammps/lammps#1378]
I've encountered a strange behaviour of dump_modify pbc when used with
a tilted box-definition.

When I run the attached in-file in lammps (with the atoms from
test.lammps), the file bug.custom correctly lists the positions as

ITEM: ATOMS id type x y z 
1 2 0 0 0 
2 1 0 1.75978 1.75978 
3 1 1.75978 0 1.75978 
4 1 1.75978 1.75978 0 

When I uncomment the dump_modify command in bug.in to make sure that all
atoms are wrapped to the cell, the outcome changes to

ITEM: ATOMS id type x y z 
1 2 0 0 0 
2 1 0 0.759778 0.759778 
3 1 0.759778 0 0.759778 
4 1 0.759778 0.759778 0 

When I remove the tilt-lines
0.0 0.0 0.0    xy xz yz
from the configuration file test.lammps, everything works as expected.

I'm not sure whether I am doing something stupid with my box
specification in test.lammps or whether this is some kind of bug.

My lammps-version is the current lmp_daily on Ubuntu 16.04, build date
8 Feb 2019.

[bug.zip](https://github.com/lammps/lammps/files/3003760/bug.zip)

**Comment by akohlmey** [comment]
@mbaeker thanks for the submission. I have confirmed the bug and a bugfix will be available in the next patch release.

**Comment by mbaeker** [comment]
good to know it was a bug - did cost me a few hours with me thinking
that I must be stupid somehow (I'm rathe new to LAMMPS)....

Cheers,
Martin.

Am Mon, 25 Mar 2019 16:23:20 +0000 (UTC)
schrieb Axel Kohlmeyer <notifications@github.com>:

> @mbaeker thanks for the submission. I have confirmed the bug and a
> bugfix will be available in the next patch release.
> 



-- 
                   Priv.-Doz. Dr. Martin Bäker
                   Institut für Werkstoffe
                   Technische Universität Braunschweig
                   Langer Kamp 8
                   38106 Braunschweig
                   Germany
                   Tel.: 00-49-531-391-3065  
                   Fax   00-49-531-391-3058
                   e-mail <martin.baeker@tu-bs.de> 
		   http://www.tu-braunschweig.de/ifw/institut/mitarbeiter/baeker
              	   http://www.scienceblogs.de/hier-wohnen-drachen
		   Twitter: @Drachenblog
