### ISSUE TITLE
[BUG]  MPI error when using fix balance rcb with hybrid ellipsoid particles and periodic boundary conditions

### ISSUE THREAD

**Issue by sef43** [lammps/lammps#1385]
**Summary**

The combination of tiled communications with rcb load balancing, hybrid ellipsoid particles and periodic boundary conditions results in a MPI error/deadlock.

**LAMMPS Version and Platform**

LAMMPS (12 Dec 2018) compiled with intel 2017.4 on Scientific Linux release 7.5 (Nitrogen) x86_64

**Expected Behavior**

The attached input script and data file should run without hanging or crashing, if the boundary conditions are changed to "m m m" or fix balance is removed it does run.

**Actual Behavior**

When 4 or more mpi tasks are used the simulation hangs or crashes after a few thousand timesteps.

**Steps to Reproduce**

With the attached files input.txt and data.txt run:

mpirun -np 4 ./lmp_mpi -in input.txt

**Further Information, Files, and Links**

[data.txt](https://github.com/lammps/lammps/files/3009771/data.txt)
[input.txt](https://github.com/lammps/lammps/files/3009775/input.txt)

Mailing list report:
https://sourceforge.net/p/lammps/mailman/message/36623239/

**Comment by akohlmey** [comment]
@sjplimp this is confirmed with the latest code from the master branch using gcc 8.x and MPICH or OpenMPI. Symptoms vary with settings and compiler flags between deadlock, message size mismatch errors, and segmentation faults.
