### ISSUE TITLE
[BUG] lammps cmake process ignores multiple flags

### ISSUE THREAD

**Issue by hjmangalam** [lammps/lammps#1386]
**Summary**

cmake ignores multiple -D flags

**LAMMPS Version and Platform**

lammps-patch_28Feb2019 & lammps-12Dec18
Trying to build with cmake on AMD64, CentOS 6.9, gcc 6.4, OpenMPI 3.1.2

**Expected Behavior**
following the sequence:

$ cmake ../cmake \
> -DVORO_LIBRARY=/data/apps/sources/lammps-12Dec18/lib/voronoi/voro++-0.4.6/src/libvoro++.a \
> -DVORO_INCLUDE_DIR=/data/apps/sources/lammps-12Dec18/lib/voronoi/voro++-0.4.6/src \
> -DPKG_USER-OMP=yes \
> -DPKG_USER-REAXC=yes \
> -DMOLECULE=yes \
> -DVORONOI=yes \
> -DPYTHON=yes \
> -DPYTHON_EXECUTABLE=/data/apps/python/2.7.15/bin/python \
> -DCMAKE_INSTALL_PREFIX:PATH=/data/apps/lammps/12Dec18 \
> -DFFT=FFTW3 \
> -DFFTW3_INCLUDE_DIRS=/data/apps/fftw/3.3.4-no-mpi/include \
> -DFFTW3_LIBRARIES=/data/apps/fftw/3.3.4-no-mpi/lib \
> -DWITH_GZIP=yes \
> -DBUILD_MPI=yes \
> -DBUILD_OMP=yes \
> -DLAMMPS_MACHINE=mpi

to build a lammps version with support for the locally supplied fftw3, python, voronoi, etc

**Actual Behavior**
CMake Warning:
  Manually-specified variables were not used by the project:

    FFT
    FFTW3_INCLUDE_DIRS
    FFTW3_LIBRARIES
    MOLECULE
    PYTHON
    PYTHON_EXECUTABLE
    VORONOI
    VORO_INCLUDE_DIR
    VORO_LIBRARY

**Steps to Reproduce**
as above.

Also please see: <https://termbin.com/h5d2>
for the entire input and output.

**Comment by junghans** [comment]
I think the behavior is as excepted,  `FFT*` is only used when build the kspace package. For `VORO_*` the problem is that you have a typo in the option, i.e. `-DVORONOI` need to be `-DPKG__VORONOI`, same for `PHYTHON` and `MOLECULE`, which will also trigger `PYTHON_EXECUTABLE` to be used.

**Comment by hjmangalam** [comment]
On Tuesday, March 26, 2019 3:00:42 PM PDT Christoph Junghans wrote:
> I think the behavior is as excepted,  `FFT*` is only used when build the
> kspace package. 

OK - I may have missed that. I'll re-RTFM


> For `VORO_*` the problem is that you have a typo in the
> option, i.e. `-DVORONOI` need to be `-DPKG__VORONOI`, same for `PHYTHON`
> and `MOLECULE`, which will also trigger `PYTHON_EXECUTABLE` to be used.




Hmm - strange, the page:
https://lammps.sandia.gov/doc/Build_extras.html#python[1]

does not mention this; neither do other pages that I'm pretty sure I traversed in search 
of the answer. 

ie:
https://lammps.sandia.gov/doc/Build_extras.html#voronoi[2]

Similarly, the entire page describing the Cmake process lacks a single entry for '-D_PKG'.

BUT! there it is on the very top of the page:
https://lammps.sandia.gov/doc/Build_extras.html[3]

OK - when you revamp your doc page, you might include that critical info with each 
stanza:
ie, for the PYTHON package
------------------------------------------------------------
-D PKG_PYTHON               # include the python package
-D PYTHON_EXECUTABLE=path   # path to Python executable to use
------------------------------------------------------------

as you do for a number of options that I did not try to use.

Thanks for the info - after the re-RTFM and some experimentation, I was able to build it 
to the user's specs.


Harry Mangalam, 
Info[4] 

--------
[1] https://lammps.sandia.gov/doc/Build_extras.html#python
[2] https://lammps.sandia.gov/doc/Build_extras.html#voronoi
[3] https://lammps.sandia.gov/doc/Build_extras.html
[4] http://moo.nac.uci.edu/~hjm/hjm.sig.html

**Comment by akohlmey** [comment]
On Wed, Mar 27, 2019 at 7:26 PM Harry Mangalam <notifications@github.com>
wrote:

Hmm - strange, the page:
> https://lammps.sandia.gov/doc/Build_extras.html#python[1]
>
> does not mention this; neither do other pages that I'm pretty sure I
> traversed in search
> of the answer.
>
> ie:
> https://lammps.sandia.gov/doc/Build_extras.html#voronoi[2]
>
> Similarly, the entire page describing the Cmake process lacks a single
> entry for '-D_PKG'.
>

that is not correct. it is explained in
https://lammps.sandia.gov/doc/Build_package.html

which you should have read to learn how to enable/disable packages in the
first place using either CMake or the conventional make process.

while https://lammps.sandia.gov/doc/Build_extras.html

at the very top says, that it only discusses *additional* flags, that have
not been discussed before.

> BUT! there it is on the very top of the page:
> https://lammps.sandia.gov/doc/Build_extras.html[3]
>
> OK - when you revamp your doc page, you might include that critical info
> with each
> stanza:
>

the LAMMPS manual is already far too big and has far too many redundant
descriptions. i don't think we need to explain everything even more
redundantly for people that skip ahead.

**Comment by junghans** [comment]
Also see: https://lammps.sandia.gov/doc/Build_cmake.html and the more comprehensive guide linked in there: 
https://github.com/lammps/lammps/blob/master/cmake/README.md it has all options explicitly listed.
