### ISSUE TITLE
[BUG] compute stress/atom gives zero for USER-INTEL styles

### ISSUE THREAD

**Issue by stevenvdb** [lammps/lammps#1389]
**Summary**

When using the lj/cut style with the USER-INTEL package, all atomic stresses are equal to zero

**LAMMPS Version and Platform**

I am using commit 28a6dcd1c3a215a15f1cc9480890feb285d4a483 compiled on CentOS Linux release 7.6.1810 (Core) with only the USER-INTEL package installed

**Expected Behavior**

Atomic stresses should sum up to the total stress, as is the case when the USER-INTEL package is _not_ used.

**Actual Behavior**

The atomic stresses are all equal to zero when the intel version of lj/cut is used. I suspect intel versions of other terms are affected too. The `ev_tally' functions in src/USER-INTEL/intel_preprocess.h do not seem to update `vatom'

**Steps to Reproduce**

The attached input file runs 10 steps of LJ particles on a bcc lattice.
If you run it without intel styles, the last two columns of thermo output are equal: these contain the pressure obtained as the sum of atomic stresses and the pressure obtained directly.
If you run the same simulation with  -pk intel 0 omp 2 -sf intel, the sum of atomic stresses is equal to zero.
[lj_bcc.txt](https://github.com/lammps/lammps/files/3018482/lj_bcc.txt)

**Comment by akohlmey** [comment]
This is a known issue. https://sourceforge.net/p/lammps/mailman/message/36586562/
it cannot be easily fixed, but there should be a check in the styles, so they error out.
