### ISSUE TITLE
[BUG] _Error on building with the KIM package_

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1396]
**Summary**

Build exits with an error because it is unable to find the `KIM_SimulatorHeaders.h` file.

**LAMMPS Version and Platform**

29Mar2019
Linux kernel 5.0.5
Intel Core i7-6700K

**Behavior**

```
[ 41%] Building CXX object CMakeFiles/lmp.dir/tmp/makepkg/lammps-beta/src/lammps-patch_29Mar2019/src/force.cpp.o
In file included from /tmp/makepkg/lammps-beta/src/lammps-patch_29Mar2019/build/styles/style_pair.h(30),
                 from /tmp/makepkg/lammps-beta/src/lammps-patch_29Mar2019/src/force.cpp(22):
/tmp/makepkg/lammps-beta/src/lammps-patch_29Mar2019/src/KIM/pair_kim.h(69): catastrophic error: cannot open source file "KIM_SimulatorHeaders.h"
  #include "KIM_SimulatorHeaders.h"
                                   ^
```

**Steps to Reproduce**

The cmake flags I use are:

```
-DCMAKE_C_COMPILER=icc
-DCMAKE_C_FLAGS="-xHost -O2 -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high"
-DCMAKE_CXX_COMPILER=icpc
-DCMAKE_CXX_FLAGS="-xHost -O2 -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias -restrict"
-DCMAKE_Fortran_COMPILER=ifort
-DCMAKE_INSTALL_PREFIX="/usr"
-DCMAKE_INSTALL_LIBDIR="lib"
-DCMAKE_INSTALL_LIBEXECDIR="/usr/lib"
-DPKG_KIM=yes
-DPKG_USER-INTEL=yes
-DINTEL_ARCH=cpu
-DPKG_USER-OMP=yes
-DBUILD_OMP=yes
```

**Additional Information**

I have the latest `kim-api` (v2.0.2) installed, and the file that is supposedly inaccessible does exist at:

    /usr/include/kim-api/KIM_SimulatorHeaders.h

@ellio167

**Comment by akohlmey** [comment]
is this in a completely new build folder with running cmake from scratch?

**Comment by ellio167** [comment]
Confirmed. I've reproduced the behavior.  Looking into it...

**Comment by akohlmey** [comment]
> Confirmed. I've reproduced the behavior. Looking into it...

i've only seen this when compiling in an existing build folder with a CMakeCache.txt file.
creating a new build folder, e.g. with:
```
mkdir build-kim
cd build-kim
cmake ../cmake -DPKG_KIM=1 -DDOWNLOAD_KIM=1
make
```
completes and links for me.
```
Large-scale Atomic/Molecular Massively Parallel Simulator - 29 Mar 2019
Git info (master / patch_29Mar2019)

[...]

OS: Linux 5.0.3-200.fc29.x86_64 on x86_64

Compiler: GNU C++ 8.3.1 20190223 (Red Hat 8.3.1-2) with OpenMP 4.5

Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_SMALLBIG

Installed packages:

KIM 
```
This is why i put the note about "configuring from scratch" in the release notes: https://github.com/lammps/lammps/releases/tag/patch_29Mar2019

**Comment by uihsnv** [comment]
@akohlmey Yes, I did build it from scratch, and in an empty directory.

I'm using a slightly modified version of the following build-script:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lammps-beta

Note that I am not using `-DDOWNLOAD_KIM=1`. Instead, I have KIM-API natively installed.

**Comment by uihsnv** [comment]
Thanks! It does build now. I've added that commit as a patch.
