### ISSUE TITLE
[BUG?] Difference between grid parameter checks kspace

### ISSUE THREAD

**Issue by tabedzki** [lammps/lammps#1403]
I was going through the flag check for the KSpace mesh settings. I noticed that there is a discrepancy between how the flag is set for `gridflag` and `gridflag_6`. One check is `&&` and the other check is `||`. I was wondering whether this deliberately done or which one of them should be fixed. 

Line [441 ](https://github.com/lammps/lammps/blob/f73ccc3025ad1003f24f7d1ed36393e96c0986e9/src/kspace.cpp#L441)to [456 ](https://github.com/lammps/lammps/blob/f73ccc3025ad1003f24f7d1ed36393e96c0986e9/src/kspace.cpp#L456)from `kspace.cpp`

```
    if (strcmp(arg[iarg],"mesh") == 0) {
      if (iarg+4 > narg) error->all(FLERR,"Illegal kspace_modify command");
      nx_pppm = nx_msm_max = force->inumeric(FLERR,arg[iarg+1]);
      ny_pppm = ny_msm_max = force->inumeric(FLERR,arg[iarg+2]);
      nz_pppm = nz_msm_max = force->inumeric(FLERR,arg[iarg+3]);
      if (nx_pppm == 0 && ny_pppm == 0 && nz_pppm == 0) gridflag = 0;
      else gridflag = 1;
      iarg += 4;
    } else if (strcmp(arg[iarg],"mesh/disp") == 0) {
      if (iarg+4 > narg) error->all(FLERR,"Illegal kspace_modify command");
      nx_pppm_6 = force->inumeric(FLERR,arg[iarg+1]);
      ny_pppm_6 = force->inumeric(FLERR,arg[iarg+2]);
      nz_pppm_6 = force->inumeric(FLERR,arg[iarg+3]);
      if (nx_pppm_6 == 0 || ny_pppm_6 == 0 || nz_pppm_6 == 0) gridflag_6 = 0;
      else gridflag_6 = 1;
iarg += 4;
```

**Comment by tabedzki** [comment]
Any update on this? Do we know which one it should be?

**Comment by akohlmey** [comment]
@stanmoore1 any ideas? i know the /disp versions are "funny" and thus their logic may be different, but i know too little about this for any yay or nay answer.

**Comment by stanmoore1** [comment]
This is choosing whether the grid is set by the user explicitly or if it should be automatically generated using the accuracy metric. Setting a grid value equal to 0 is not valid and could cause problems, so in that case the /disp version has better behavior. A better answer would probably be to error out if any of the input grid values are 0.

**Comment by stanmoore1** [comment]
In other words, in the regular version, if ALL of the input parameters are 0, it will silently ignore them and automatically size the grid. In the /disp version, of ANY of the input parameters are zero, it will silently ignore all of the inputs and automatically size the grid. It would be best to error out instead of silently ignoring user input.

**Comment by tabedzki** [comment]
Ok. I can do that and make a pull request for that.

**Comment by stanmoore1** [comment]
@tabedzki thanks. It would be good to error out if the input is <= 0. For example, if one specifies a negative number for the grid, it gives this:

```
PPPM initialization ...
  using 12-bit tables for long-range coulomb (../kspace.cpp:319)
  G vector (1/distance) = 0.0211079
  grid = 25 25 -1
  stencil order = 5
  estimated absolute RMS force accuracy = 16.618
  estimated relative force accuracy = 0.0500446
  using double precision FFTs
  3d grid and FFT values/proc = 3600 -625
ERROR on proc 0: Failed to allocate -5000 bytes for array pppm:density_fft (../memory.cpp:64)
```
