### ISSUE TITLE
Replace Makefile.omp with non-MPI version

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#141]
Right now, the Makefile.omp looks like

CC =		mpicxx
CCFLAGS =	-g -O3 -restrict -fopenmp

which doesn't work without MPI installed. I suggest replacing current Makefile.omp to

CC =		g++
CCFLAGS =	-g -O3 -restrict -fopenmp

and adding -fopenmp as default flag in i.e. Makefile.g++_openmpi.

**Comment by akohlmey** [comment]
The various makefiles in the subdirectories are not meant to be an exhaustive list of variants or to provide convenient defaults, but mostly to demonstrate what kind of changes might be needed. If you want the "all-singing, all-dancing makefile able to adapt to everything", then i'd recommend you check out (and augment/improve) Make.py
