### ISSUE TITLE
[BUG] can't use logical NOT in atom variable

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1410]
**Summary**

Using the logical NOT operator "!" inside an atom variable causes a "Invalid syntax in variable formula (../variable.cpp:2274)" error.

**LAMMPS Version and Platform**

Latest master version.

**Steps to Reproduce**

Run the following script:
```
atom_modify map yes
region box block -15 15 -15 15 -15 15
create_box 1 box
create_atoms 1 single 0 0 0

variable evar equal !0
print "This works: ${evar}"
variable avar atom 1
variable evar equal v_avar[1]
print "This also works: ${evar}"
variable avar atom !0
print "This should also work: ${evar}"
```

**Expected Behavior**

Expected output:
> This works: 1
> This also works: 1
> This should also work: 1

**Actual Behavior**

The actual output:
> This works: 1
> This also works: 1
> ERROR: Variable avar: Invalid syntax in variable formula (../variable.cpp:2274)
> Last command: This should also work: ${evar

**Further Information, Files, and Links**

All the other logical operators appear to work correctly with atom variables. Maybe it's because it is the only unary operator?

**Comment by akohlmey** [comment]
Thanks for reporting. It is not the only unary operator, there also is the unary "-". For equal style variable evaluations, both cases are handled, but for atom style variables only the unary "-". The one line fix in commit e359e80118890a6330bb3c3c93e1d6637e16d5ed should address this.
