### ISSUE TITLE
[BUG] “compute stress/atom” The results calculated using pair style reax/c/omp are incorrect

### ISSUE THREAD

**Issue by yangkunbit** [lammps/lammps#1411]
“These lines in an input script for a 3d system should yield that result. I.e. the last 2 columns of thermo output will be the same:

compute        peratom all stress/atom NULL
compute        p all reduce sum c_peratom[1] c_peratom[2] c_peratom[3]
variable       press equal -(c_p[1]+c_p[2]+c_p[3])/(3*vol)
thermo_style   custom step temp etotal press v_press‘’

But we have try many times the last 2 columns of thermo output are not the same. The "v_prerss"  may be thousands of times larger than the "perss"

email: yangkunbit@163.com 

[1500K_rdx.in.txt](https://github.com/lammps/lammps/files/3046800/1500K_rdx.in.txt)
[rdx298k322.data.txt](https://github.com/lammps/lammps/files/3046801/rdx298k322.data.txt)

**Comment by mkanski** [comment]
It's because you use `virial` keyword which excludes the kinetic energy component of pressure. Without it the pressures from the compute and thermo are the same.

**Comment by yangkunbit** [comment]
Thank you very much~
We tried  didn't use virial keyword, But I think the main problem is that the results in Linux and windows versions are inconsistent, and the gap is close to three orders.
For example the press is about -3970.1197, but it will be 287559.69 which calculated by  windows versions.

Following the logfile

LAMMPS (8 Feb 2019) for windows
................
compute 	peratom all stress/atom NULL
compute 	p all reduce sum c_peratom[2] c_peratom[1] c_peratom[3]

variable        press equal (-c_p[2]-c_p[1]-c_p[3])/(3*vol)

thermo 20
thermo_style custom step temp press v_press pe ke etotal enthalpy evdwl ecoul epair ebond eangle edihed eimp emol elong etail vol density cella cellb cellc cellalpha cellbeta cellgamma
.......................
Step Temp Press v_press PotEng KinEng TotEng Enthalpy E_vdwl E_coul E_pair E_bond E_angle E_dihed E_impro E_mol E_long E_tail Volume Density Cella Cellb Cellc CellAlpha CellBeta CellGamma 
       0    290.31107   -3970.1197    287559.69    -130917.4    1162.1814   -129755.22   -130516.22   -125189.93   -5727.4675    -130917.4            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
      20    1038.4865    8674.4674    314227.73   -130771.86     4157.298   -126614.56   -124951.82   -125044.55   -5727.3144   -130771.86            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
      40    1232.5938    25143.284    346096.49    -130134.4    4934.3539   -125200.04    -120380.5   -124404.66    -5729.731    -130134.4            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
------------------------------------------------------------------------------------------------------    
LAMMPS (12 Dec 2018)    for linux

....................................

compute 	peratom all stress/atom NULL

compute 	p all reduce sum c_peratom[2] c_peratom[1] c_peratom[3]

variable        press equal (-c_p[2]-c_p[1]-c_p[3])/(3*vol)

thermo 20
thermo_style custom step temp press v_press pe ke etotal enthalpy evdwl ecoul epair ebond eangle edihed eimp emol elong etail vol density cella cellb cellc cellalpha cellbeta cellgamma
.....................
Step Temp Press v_press PotEng KinEng TotEng Enthalpy E_vdwl E_coul E_pair E_bond E_angle E_dihed E_impro E_mol E_long E_tail Volume Density Cella Cellb Cellc CellAlpha CellBeta CellGamma 
       0    290.31107   -3970.1197   -3970.1197    -130917.4    1162.1814   -129755.22   -130516.22   -125189.93   -5727.4675    -130917.4            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
      20    1038.4865    8674.4913    8674.4913   -130771.86     4157.298   -126614.56   -124951.81   -125044.55   -5727.3143   -130771.86            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
      40    1232.5938    25143.451    25143.451    -130134.4    4934.3539   -125200.04   -120380.47   -124404.66   -5729.7307    -130134.4            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
      60     1293.389    26516.587    26516.587   -129390.54    5177.7307   -124212.81   -119130.03    -123656.4   -5734.1458   -129390.54            0            0            0            0            0            0            0    13143.398     1.795987    26.412689    23.190751    21.457554           90           90           90 
————————————————————————————————
There are some confusions, looking forward to answers.

Thanks you very much!

**Comment by mkanski** [comment]
I still cannot confirm it on Windows 10 and 8 Feb 2019 LAMMPS version both serial and MPI. Please attach the `log.lammps` file showing the issue.

**Comment by yangkunbit** [comment]
The system is Windows 7 64bit  and 8 Feb 2019 LAMMPS（LAMMPS-64bit-latest-MPI）
[log.lammps.txt](https://github.com/lammps/lammps/files/3050356/log.lammps.txt)
[log.lammps_LAMMPS (12 Dec 2018)for linux.txt](https://github.com/lammps/lammps/files/3050357/log.lammps_LAMMPS.12.Dec.2018.for.linux.txt)

**Comment by yangkunbit** [comment]
we found the main reason is the use of OpenMP multi-threading a minute ago，the commond is "lmp_mpi -pk omp 8 -sf omp -in 1500K_RDX.in"

**Comment by mkanski** [comment]
Yes, I can confirm it on both Linux and Windows for any number of OMP threads including one. The bug is somewhere in reax/c/omp. Interestingly, the computed pressure is not deterministic if more than one OMP thread is used. The table below shows the result of the thermo and compute for 2 OMP threads:

Sim no. | press | c_press
--|----------------|------------
1 | 146.581690 | 31.563190 
2 | 146.581690 | 261.600190 
3 | 146.581690 | 261.600190 
4 | 146.581690 | 261.600190 
5 | 146.581690 | 261.600190 
6 | 146.581690 | 31.563190 
7 | 146.581690 | 261.600190 

@akohlmey I'm afraid this issue needs to be reopened. I'm attaching a simpler input script which triggers the bug. 
[reax_c_omp_virial_bug.in.txt](https://github.com/lammps/lammps/files/3050389/reax_c_omp_virial_bug.in.txt)

**Comment by akohlmey** [comment]
reopened with corrected subject

**Comment by akohlmey** [comment]
did some empirical testing and it looks like the result is correct when i add `no_virial_fdotr_compute = 1;` to the constructor of pair style `reax/c/omp`.

**Comment by akohlmey** [comment]
> did some empirical testing and it looks like the result is correct when i add `no_virial_fdotr_compute = 1;` to the constructor of pair style `reax/c/omp`.

unfortunately not correct, only consistent between global and per-atom stress
