### ISSUE TITLE
[Feature Request] Implement per-atom stress in pair style reax/c/omp

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1417]
**Summary**

Per-atom stress is not properly tallied in pair style reax/c/omp. This should be corrected.

**Detailed Description**

When requesting per-atom stress when running pair style reax/c/omp the results are either missing or double counting some contributions. for more details and test inputs, please see issue #1411

**Comment by akohlmey** [comment]
@athomps just noticed this old issue which is likely related to the nofdotr issue we noticed in reax/c

**Comment by athomps** [comment]
Okay. I am working on it now.

**Comment by akohlmey** [comment]
Implemented in PR #2708
