### ISSUE TITLE
[Feature Request] Maintain Singularity/Docker Containers

### ISSUE THREAD

**Issue by kmanalo** [lammps/lammps#1433]
**Summary**

It would be nice to have a Singularity container that follows the latest installation of LAMMPS.

**Detailed Description**

The purpose would be to support more HPC users.  As a non-LAMMP user, but an installer of HPC software, I would like to provide easier ways to deploy containers that have nearly all the packages they would want inside of it.

**Further Information, Files, and Links**

This is a related discussion:
https://github.com/lammps/lammps/pull/892

Similarly, Singularity can simply pull the Dockerfile to reduce maintenance burdens.

There is some emerging work by Intel here, but I would like to see a general open source version as well with just the use of gcc compilers

https://github.com/intel/HPC-containers-from-Intel/blob/master/containers/lammps/Singularity.lammps

There are some groups that have been building it on Singularity Hub as well
https://singularity-hub.org/collections/210

Thanks,
Kevin

**Comment by akohlmey** [comment]
@kmanalo you can get pretty close to what you are looking for by using the CMake build system and the most.cmake preset, which is missing only a few exotic packages and contains only packages requiring external sources where automatic download and compile is supported.

The major challenge to have a docker/singularity container is to find a person willing to maintaining it. The LAMMPS core team is small and we all have lots of commitments already. So we would need somebody else to step up and take care of this.
