### ISSUE TITLE
PyLammps: Add access to thermo output and dump information

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#144]
This is a feature request from multiple participants of the [LAMMPS Tutorial at Temple University in August 2016](https://sites.google.com/site/templesummermd/):

> It would be great if there is an easy way to access the thermo output and data generated by dumps. E.g. by fix ave/chunk.
## Current state:
- [x] Access to thermo output data
- [x] Access to dump data (e.g., ave/chunk)
- [x] Add documentation about these features

**Comment by akohlmey** [comment]
@rbberger is still under consideration? or should we close is issue?

**Comment by rbberger** [comment]
@giacomofiorin can you have a look at this avg/chunk reader? Still need to write some example and/or docs. But it should be usable as follows:

```python
from lammps import AvgChunkFile

c = AvgChunkFile(filename)
c.timesteps # list of timesteps in file
c.chunks    # list of chunks in file

# c.chunks[0][propery_name]
c.chunks[0]['id']
c.chunks[0]['coord']
c.chunks[0]['density/count']  # list of density/count values over time of chunk 1
```

**Comment by giacomofiorin** [comment]
Will do ASAP, thanks for implementing it!

**Comment by rbberger** [comment]
please don't close issues until the PR is merged.
