### ISSUE TITLE
[BUG]  Intel Compiler flags not set correctly

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1441]
**Summary**

The wrong compiler flags are selected, even though I have the intel compilers selected in the cmake options.

**LAMMPS Version and Platform**

30Apr2019

**Actual Behavior**

```
-- Performing Test COMPILER_SUPPORTS-O2 - Failed
-- Performing Test COMPILER_SUPPORTS-fp-model - Failed
-- Performing Test COMPILER_SUPPORTSfast=2 - Failed
-- Performing Test COMPILER_SUPPORTS-no-prec-div - Failed
-- Performing Test COMPILER_SUPPORTS-qoverride-limits - Failed
-- Performing Test COMPILER_SUPPORTS-qopt-zmm-usage=high - Failed
-- Performing Test COMPILER_SUPPORTS-qno-offload - Failed
-- Performing Test COMPILER_SUPPORTS-fno-alias - Failed
-- Performing Test COMPILER_SUPPORTS-ansi-alias - Failed
-- Performing Test COMPILER_SUPPORTS-restrict - Failed

   C++ Compiler     /opt/intel/composerxe/linux/bin/intel64/icpc
       Type         Intel
       Version      19.0.0.20190117
   C++ Flags        -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -restrict -qopenmp -xHost
```

**Correct Behaviour**

The tests should Pass, and the `march` and `mtune` flags should not exist. They are `gcc` flags. Not sure about `pipe` and `plt`.

The correct flags are: `-xHost -O2 -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias`

**Steps to Reproduce**

I'm compiling with the following options:
```
-DCMAKE_C_COMPILER=icc
-DCMAKE_CXX_COMPILER=icpc
-DCMAKE_Fortran_COMPILER=ifort
-DINTEL_ARCH=cpu
-DPKG_USER-INTEL=yes
```
amongst others

**Comment by akohlmey** [comment]
Those gcc compiler flags are nowhere set in the cmake configuration files for LAMMPS. This must be an issue with your local cmake installation.

**Comment by uihsnv** [comment]
I'm using the latest `cmake` version: 3.14.3 . I don't think there is any issue with that. The `-DINTEL_ARCH=cpu` cmake option is supposed to set those options, but for some reason, it is not.

**Comment by akohlmey** [comment]
> I'm using the latest `cmake` version: 3.14.3 . The `COMPILER_SUPPORTS` check is failing for all those options. I don't understand why.
> https://github.com/lammps/lammps/blob/master/cmake/CMakeLists.txt#L1206

those fail because your CMake does add those GCC-only compiler flags **first**, and those are the problem here. As mentioned before, the "-march" and "-mtune" flags are **NOT** added by the CMake configuration files in LAMMPS. Thus they must be added by your local CMake configuration.
