### ISSUE TITLE
[Feature Request] Log distributed samples

### ISSUE THREAD

**Issue by zqex** [lammps/lammps#1442]
**Summary**

fix print and fix ave/time can be used to save global values at regular intervals. It would be very nice with a similar feature to store the result of global variables / computes e.g. mean-square displacements with log spaced time intervals similar to what can be achieved by dump_modify every v_next for dumping configurations. 

**Detailed Description**

MSD data are not only used for measuring diffusion coefficients, but also to study dynamic transitions  e.g. of particles diffusing in crowded media, monomers in polymers and so on. They need to be sampled with high time resolution to cover the dynamics at early times, but also run for long times to sample diffusive dynamics. Hence such data are always plotted in a log-log representation. Sampling them on a linear scale with a fine interval is computationally inefficient and creates excessively large files of mostly uninteresting data that needs to be post-processed before plotting.

**Comment by akohlmey** [comment]
@zqex The thermo command already supports an equal style variable as argument for custom spacing of thermo output lines. In addition, I have just added support for a variable time step spacing to fix print. Doing the same for fix ave/time is more complex, as it is impossible to guarantee that nstep, nrepeat, and nevery are commensurate and not overlapping.

**Comment by zqex** [comment]
Dear Axel,

Excellent having this for fix print solves the problem. I usually use 
the dump_thermo as diagnostic to check if the simulation makes sense. 
but saves the relevant observables to files during the simulation since 
this makes it easier to selectively download and analyse the observables 
of interest.

Yes, fix ave/time would be a mess.

Thanks!

Den 04/05/2019 kl. 20.12 skrev Axel Kohlmeyer:
