### ISSUE TITLE
[BUG] Behavior of read_dump depends on the order of keywords

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#1454]
**Summary**

Atoms are not added if `add yes` keyword is after `format`, e.g. 
`read_dump       dump.lammpstrj 0 x y z format native add yes` won't add atoms but
`read_dump       dump.lammpstrj 0 x y z add yes format native` will.  

**LAMMPS Version and Platform**

Current master.
Linux Mint 18.

**Expected Behavior**

Atoms should be added regardless of the position of `add yes`

**Actual Behavior**

Atoms are not added if `add` keyword is after `format`. 

**Steps to Reproduce**

See attached input file.

**Further Information, Files, and Links**

[input.in.txt](https://github.com/lammps/lammps/files/3147232/input.in.txt)

**Comment by akohlmey** [comment]
Actually, this is the documented behavior. It is due to the format keyword, which must come last, if used.
