### ISSUE TITLE
[BUG] MPI_ERR_COMM: invalid communicator with OpenMPI on Centos7

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1463]
From: https://bugzilla.redhat.com/show_bug.cgi?id=1710518

Description of problem:

I see this error trying to run lmp_openmpi, for example on 2x18 cores or a single 18-core node, with the rhodo benchmark case; I got the same thing with chute (all over TCP, whether or not that's sensible, and I doubt the transport makes a difference).  Also, it's with `OMP_NUM_THREADS=1`.

```
[compute003:11020] *** An error occurred in MPI_Comm_rank
[compute003:11020] *** reported by process [3385851905,21]
[compute003:11020] *** on communicator MPI_COMM_WORLD
[compute003:11020] *** MPI_ERR_COMM: invalid communicator
[compute003:11020] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[compute003:11020] ***    and potentially your MPI job)
```

The same thing works with the mpich package.

**Comment by junghans** [comment]
Reported on Fedora by @loveshack.

**Comment by akohlmey** [comment]
LAMMPS version? OpenMPI version? compiler type and version? any evidence that points at LAMMPS as the culprit?

**Comment by loveshack** [comment]
> LAMMPS version? OpenMPI version? compiler type and version?

As in the current EPEL7 package.

> any evidence that points at LAMMPS as the culprit?

No, given that the MPICH version works, but I haven't have time to debug
it.

**Comment by akohlmey** [comment]
no evidence, no investigation.

**Comment by junghans** [comment]
Update: This seems to be a problem with OpenMPI-4, still investigating...
