### ISSUE TITLE
[BUG] CMake is not propagating all settings to the subordinate builds

### ISSUE THREAD

**Issue by jamie-arcc** [lammps/lammps#1470]
**Summary**

Using the CMake build with Intel 2019 update 3 and mvapich2 2.3.1 and cmake 3.14.0.  It seems that the configurations for the subordinate packages within lammps are not correctly receiving all of the configuration options that were set when running cmake to configure LAMMPS, causing the build to fail. In addition, the `-xHost` flag is getting added implicitly and inappropriately to the CFLAGS/CXXFLAGS/FFLAGS, which then overrides any previous settings of the `-x` flag, such as my case where I need `-xSSE4.2` because I am building this for a heterogeneous cluster.  That should either be made explicit, removed, or PREpended to the flags rather than appended, as intel always uses the most recently read flag in the case of repeats.  at least one build seems to use `CC=gcc`, which then fails because the CFLAGS contains intel-specific flags that it does not recognize.  another is using `LD=ld` when `LD=xild` was explicitly set in CMake as well as exported to the environment, which then causes failures when running with `-ipo` optimization and it seems to be unable to find intel libraries.

**LAMMPS Version and Platform**

patch release 30Apr2019 on CentOS 7.4 x86_64

**Expected Behavior**

Configurations set in the top level CMake configuration should be applied to all subordinate packages and no package should be implicitly/transparently setting potentially breaking (architecture selection, for instance) compiler flags by default.
**Actual Behavior**

Certain packages within LAMMPS do not seem to be receiving all of the configuration options set when CMake was run, causing builds to fail. Compiler flags such as `-xHost` are being set implicitly and transparently, which causes incorrect binaries to be produced when the user had set their own architecture flags, which they expected to be applied.

**Steps to Reproduce**

Try to configure and build LAMMPS with most of the optional packages enabled, using the Intel compiler with custom compiler optimization flags set and the linkers set to `xiar` for 'ar' and `xild` for 'ld'. See attached CMakeCache.txt below.

**Further Information, Files, and Links**

[CMakeCache.txt](https://github.com/lammps/lammps/files/3203622/CMakeCache.txt)
[CMakeOutput.log](https://github.com/lammps/lammps/files/3203623/CMakeOutput.log)

**Comment by junghans** [comment]
Hmm, I am not sure we can accommodate all these wishes for such specialized builds installing lammps through a real package manager like spack might be the better option. However, we can certainly add an option to not overwrite user specified C/CXX flags.

**Comment by akohlmey** [comment]
CMake support is rather new and a work in progress. Thus your feedback is appreciated, but I am not certain, if this is a serious "bug". If you want full customization, please use the conventional build process. It was designed to be more customizable. The primary intent to add support for CMake was to make it easier for people with limited experience compiling software to produce a working version of LAMMPS with all supported features without having to manually edit makefiles.

We are trying to improve, but specifically for the automated downloads, you should consider installing the underlying packages separately and then point the LAMMPS CMake to those installations. This is the recommended procedure. The automated download is primarily meant for in-place testing and development.

**Comment by jamie-arcc** [comment]
> CMake support is rather new and a work in progress. Thus your feedback is appreciated, but I am not certain, if this is a serious "bug". If you want full customization, please use the conventional build process. It was designed to be more customizable. The primary intent to add support for CMake was to make it easier for people with limited experience compiling software to produce a working version of LAMMPS with all supported features without having to manually edit makefiles.
> 
> We are trying to improve, but specifically for the automated downloads, you should consider installing the underlying packages separately and then point the LAMMPS CMake to those installations. This is the recommended procedure. The automated download is primarily meant for in-place testing and development.

Maybe that practice should be mentioned in the documentation

> Hmm, I am not sure we can accommodate all these wishes for such specialized builds installing lammps through a real package manager like spack might be the better option. However, we can certainly add an option to not overwrite user specified C/CXX flags.

Isn't the point of using CMake to do this though? especially since at least one of the packages that is messing up seems to also be configured with CMake, and CMake does definitely have support for handling embedded dependencies at the top level.  Thus far, it only seems to be a small number of packages having the issue and most of this should be trivial, such as making sure that the variables set up top are being used in the configuration process for the subpackages.  For sub projects with CMake, it's as simple as passing the same CMake options used up top (with exceptions where necessary) and for things using Automake/autoconf just making sure that flags like CC, CXX, CFLAGS, CXXFLAGS, LD, AR, and so on are used when running those configuration scripts.  I am not too familiar with actually writing CMake files, but I can look into trying to implement some of this as time permits

**Comment by akohlmey** [comment]
@junghans can you check whether this is something that is now different after your CMake modernization changes? if not, we should label it as wontfix and close this issue. thanks.

**Comment by junghans** [comment]
Yeah, I think this should be possible now as we put the optimization flags into `CMAKE_TUNE_FLAGS` and the user can overwrite those.
