### ISSUE TITLE
[Feature Request] Logarithmic spacing function

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1471]
**Summary**

I'm looking for a function that generates logarithmically spaced integers, given a total duration (steps or run length) and the number of divisions of that space.

**Detailed Description**

There currently exists functions `logfreq()` and `logfreq2`, but neither of them actually do that. The first can only have logarithmic spacings with an integer base, while the latter is just linear spacings.

Very often, non-integer spacings in the interval: (1,2) are required for there to be sufficient sampling of data. This does mean though, that the initial spacing will be linear, but that is fine.

**Further Information, Files, and Links**

The following is some C code that fills an array with exactly such a spacing. It could be a `logfreq3(X,Y)` with the inputs being the number of points required, and the total steps (length) that needs to be divided. There could also be a third input, so that the start and end steps can be specified.

```
#include <math.h>

enum{
    // Number of logarithmic data points to create
    POINTS = 100,
    // The number of steps that needs to be sliced
    STEPS  = 1000
};

// Array of log-spaced values
static unsigned int logSpacing[POINTS];

static void genLogSpace(){
    unsigned int i,index;
    double dindex;
    const double factor = pow((double)STEPS, 1.0/(POINTS-1));

    index = 1;
    dindex = (double)index;
    i=0;
    while( (index >= (unsigned int)dindex) && (i < (POINTS-1)) ){
        logSpacing[i] = index;
        dindex *= factor;
        index++;
        i++;
    }
    while(i < (POINTS-1)){
        logSpacing[i] = (unsigned int)dindex;
        dindex *= factor;
        i++;
    }
    logSpacing[POINTS-1] = STEPS;
}

int main(){
  genLogSpace();
}
```

**Comment by uihsnv** [comment]
A version of the same, updated to include a start and a finish:

```
#include <math.h>

enum{
    // Number of logarithmic data points to create
    POINTS = 50,
    // The bounds (inclusive) of the interval in which log-spaced numbers are required
    START  = 10,
    END  = 1000
};

// Array of log-spaced values
static unsigned int logSpacing[POINTS];

static void genLogSpace(){
    unsigned int i,index;
    double dindex;
    const double factor = pow(((double)END)/START, 1.0/(POINTS-1));

    index = START;
    dindex = (double)index;
    i=0;
    while( (index >= (unsigned int)dindex) && (i < (POINTS-1)) ){
        logSpacing[i] = index;
        dindex *= factor;
        index++;
        i++;
    }
    while(i < (POINTS-1)){
        logSpacing[i] = (unsigned int)dindex;
        dindex *= factor;
        i++;
    }
    logSpacing[POINTS-1] = END;
}

int main(){
    unsigned int i;
    genLogSpace();
}
```

**Comment by akohlmey** [comment]
> **Detailed Description**

> Very often, non-integer spacings in the interval: (1,2) are required for there to be sufficient sampling of data. This does mean though, that the initial spacing will be linear, but that is fine.

too frequent data use in MD simulations **does not** improve data sampling, since those data are highly correlated. the so-called statistical efficiency drops quite substantial for data collected more frequent than, say, 1ps apart for typical molecular/atomic MD simulation setups.

**Comment by uihsnv** [comment]
The spacing is multiplicative, so can have a huge effect for large numbers. For eg., a factor of `1.1` will imply an initial series of singly-spaced steps, but after a while will take off, to give large spacings. Take a look at the example I posted in the documentation part of the PR, or try it out.

**Comment by akohlmey** [comment]
> The spacing is multiplicative, so can have a huge effect for large numbers. For eg., a factor of `1.1` will imply an initial series of singly-spaced steps, but after a while will take off, to give large spacings. Take a look at the example I posted in the documentation part of the PR, or try it out.

you are not addressing my concern. i still don't see a valid use case beyond what LAMMPS already provides. the logarithmic spacing is not useful for any serious data analysis in the first place. it really only makes sense for monitoring of the progress of long-running simulations and for that i am still missing a convincing argument why we need closer spacing. your reasoning of this being used "commonly" or "frequently" only seems to apply to yourself. LAMMPS has been around a very long time, and if this was as common or frequent as you claim, others would have had asked for it a long time ago.

**Comment by uihsnv** [comment]
> your reasoning of this being used "commonly" or "frequently" only seems to apply to yourself. LAMMPS has been around a very long time, and if this was as common or frequent as you claim, others would have had asked for it a long time ago.

That is not a fair argument on your part. Also, that was just a word I used, and not my primary argument. Please base your criticisms on the function itself.

>  the logarithmic spacing is not useful for any serious data analysis in the first place. it really only makes sense for monitoring of the progress of long-running simulations and for that i am still missing a convincing argument why we need closer spacing.

Yes, this is useful for sampling information for systems undergoing very long runs, because integer bases will give too few samples. And by 'sampling' I don't just mean dumping data. It could be a compute or a fix too.

I use it to sample the mean-squared-displacement and various other correlations, that I later plot on a log-log scale. This means that the data is also best sampled at such a frequency as to give me equally spaced points on my plot. With the current `logfreq()` function, the closest spacing I can obtain is with a base of 2. Now if you know how exponential series grow, you will know that this will only give me very very few samples.

My only argument is this: `logfreq3()` lets the person performing the simulation decide what frequency they want to sample at.

**Comment by akohlmey** [comment]
> > your reasoning of this being used "commonly" or "frequently" only seems to apply to yourself. LAMMPS has been around a very long time, and if this was as common or frequent as you claim, others would have had asked for it a long time ago.
> 
> That is not a fair argument on your part. Also, that was just a word I used, and not my primary argument. Please base your criticisms on the function itself.

if you don't want to be criticized on this, then please don't bring it up. you want to change the core code of LAMMPS, not just add some (optional) package code,  so we **do** have to look at what is the benefit of an addition to the majority of users versus the overhead of having to maintain it in the future.

> > the logarithmic spacing is not useful for any serious data analysis in the first place. it really only makes sense for monitoring of the progress of long-running simulations and for that i am still missing a convincing argument why we need closer spacing.
> 
> Yes, this is useful for sampling information for systems undergoing very long runs, because integer bases will give too few samples. And by 'sampling' I don't just mean dumping data. It could be a compute or a fix too.

you are not addressing my concern here. from a statistical point of view generating data on a logarithmic is rarely useful. mostly it matters for plotting results.

> I use it to sample the mean-squared-displacement and various other correlations, that I later plot on a log-log scale. This means that the data is also best sampled at such a frequency as to give me equally spaced points on my plot. With the current `logfreq()` function, the closest spacing I can obtain is with a base of 2. Now if you know how exponential series grow, you will know that this will only give me very very few samples.

but that really is not an issue of the output but rather of post-processing. i've produced plenty of semi- and dual-logarithmic plots during my career, and never used logarithmic data sampling for that. in fact, i would consider it detrimental, since for logarithmic output, you have to know in advance, when your system is properly equilibrated and collection of data can start. with linear output (like most people do), you can choose at a later point without losing anything.

> My only argument is this: `logfreq3()` lets the person performing the simulation decide what frequency they want to sample at.

have you considered implementing this as a python style variable instead?

**Comment by uihsnv** [comment]
> > > your reasoning of this being used "commonly" or "frequently" only seems to apply to yourself. LAMMPS has been around a very long time, and if this was as common or frequent as you claim, others would have had asked for it a long time ago.
> > 
> > 
> > That is not a fair argument on your part. Also, that was just a word I used, and not my primary argument. Please base your criticisms on the function itself.
> 
> if you don't want to be criticized on this, then please don't bring it up. you want to change the core code of LAMMPS, not just add some (optional) package code, so we **do** have to look at what is the benefit of an addition to the majority of users versus the overhead of having to maintain it in the future.
> 

Criticism on that front is perfectly valid. But what I meant was that your statement that "if this was as common or frequent as you claim, others would have had asked for it a long time ago" is unfair, because many people just find a workaround instead of reporting or asking for it (the group I'm part of uses a separate text file with such log-spaced numbers). Also, because to know the answer to that question, you will have to conduct a proper survey, which I'm sure you haven't. So it is a fallacy to assume that there is/will-be no interest. That is why it is an unfair argument: because you assume a null-hypothesis with burden of proof on me, which I evidently can't provide. Additionally, does not me asking for this count as a point of interest?

> > > the logarithmic spacing is not useful for any serious data analysis in the first place. it really only makes sense for monitoring of the progress of long-running simulations and for that i am still missing a convincing argument why we need closer spacing.
> > 
> > 
> > Yes, this is useful for sampling information for systems undergoing very long runs, because integer bases will give too few samples. And by 'sampling' I don't just mean dumping data. It could be a compute or a fix too.
> 
> you are not addressing my concern here. from a statistical point of view generating data on a logarithmic is rarely useful. mostly it matters for plotting results.
> 

Maybe I'm not quite comprehending your question. What do you mean by "statistical point of view"? Sure, this is not appropriate for the cases where a linear spacing is appropriate. Isn't that your argument? What I'm saying is, there are other situations where a log-spacing is appropriate, such as what I describe in my reply below.

> > I use it to sample the mean-squared-displacement and various other correlations, that I later plot on a log-log scale. This means that the data is also best sampled at such a frequency as to give me equally spaced points on my plot. With the current `logfreq()` function, the closest spacing I can obtain is with a base of 2. Now if you know how exponential series grow, you will know that this will only give me very very few samples.
> 
> but that really is not an issue of the output but rather of post-processing. i've produced plenty of semi- and dual-logarithmic plots during my career, and never used logarithmic data sampling for that. in fact, i would consider it detrimental, since for logarithmic output, you have to know in advance, when your system is properly equilibrated and collection of data can start. with linear output (like most people do), you can choose at a later point without losing anything.
> 

No, it is not just an issue of post-processing. Say I would like to analyse structures generated by MD runs, now if I output atom data at linear intervals, I would need much more storage space than I have, and if I wrote it out at integer-base log intervals, I would have very few. Is not convenient data generation something that would be nice in LAMMPS?

I think my mistake is that I'm arguing using my specific case. Let me ask you instead. What is the purpose of the `logfreq()` function? If someone is interested in that, then is this not just a matter of degree of spacing? In that sense, `logfreq3()` is just a generalisation of `logfreq()`. Is that not sufficient reason?

> > My only argument is this: `logfreq3()` lets the person performing the simulation decide what frequency they want to sample at.
> 
> have you considered implementing this as a python style variable instead?

As I mentioned above, I already have a workaround for this: generate it in a file, and read from it. I just thought that it would be nice to have it as a core function. And hopefully useful to other too. We could do a survey of all users to find out, if you'd like.

**Comment by uihsnv** [comment]
> the overhead of having to maintain it in the future.

I modelled it to be as close to `logfreq()` and `logfreq2()` as possible, so as to make it easier to maintain.

**Comment by akohlmey** [comment]
> 
> Criticism on that front is perfectly valid. But what I meant was that your statement that "if this was as common or frequent as you claim, others would have had asked for it a long time ago" is unfair, because many people just find a workaround instead of reporting or asking for it (the group I'm part of uses a separate text file with such log-spaced numbers). Also, because to know the answer to that question, you will have to conduct a proper survey, which I'm sure you haven't. So it is a fallacy to assume that there is/will-be no interest. That is why it is an unfair argument: because you assume a null-hypothesis with burden of proof on me, which I evidently can't provide. Additionally, does not me asking for this count as a point of interest?

you have painted yourself into that corner by making a claim without any proof in the first place.
since it is *you* that want something from the LAMMPS developers, it is also *your* obligation to provide proof, and not our obligation to prove you wrong. besides, how do you know how much i talk to LAMMPS users and developers and how much of an insight of what users want and need and request (outside of what is written here).

yes, you count as a person of interest, but what i am questioning is, is there *another* that is *independent* from you? given my exposure to the requests of LAMMPS users and developers over many years, i believe i would have seen or heard others talking about this. for as long as you make unproven claims and speculate what others do, you have to accept, that i question them in the same way.

**Comment by uihsnv** [comment]
I do accept, given your role in the development of the software, as well as volume of participation in the mailing-list, that you would have a much better sense of the needs of users than me. But would it not be a wee bit hubristic, even for you, to assume that no one would need it?

> since it is you that want something from the LAMMPS developers

Just so we're clear, when you say that, you're referring to the developers taking time to examine the utility (as you are now) and review technical details of my Pull-Request, right? And not taking time to write in the functionality, because I already did so.

> it is also your obligation to provide proof

Say we performed an exercise to determine interest in such a feature. What amount of support would you take as sufficient?

> yes, you count as a person of interest, but what i am questioning is, is there another that is independent from you?

Well, all the other grad students in the group I'm part of would be happy to have it, and so would my supervisor. Other than them, I'd have to ask around.

**Comment by akohlmey** [comment]
we are going in circles now. i have to say all that i want about this.

**Comment by uihsnv** [comment]
Does this imply the death of this issue/request?

**Comment by akohlmey** [comment]
> Does this imply the death of this issue/request?

no. only that i am no longer participating in it.
