### ISSUE TITLE
[BUG] Output of help does not show MC package or fixes

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1478]
**Summary**

In-spite of having built with the MC package, the output of `lmp -h` does not say *MC* under `Installed packages:`. It also does not list any of the commands that the package offers, under relevant headers.

**LAMMPS Version and Platform**

* git clone on 24 May 2019, but running a script says *LAMMPS (15 May 2019)*
* *Linux, Intel i7-6700K*

**Expected Behavior**

The help output should include the MC package as well as all of its fixes, etc.

**Steps to Reproduce**

I compiled it with the following commands:

```
cmake ../cmake \
    -DCMAKE_C_COMPILER=icc \
    -DCMAKE_C_FLAGS="-xHost -O3 -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias -restrict" \
    -DCMAKE_CXX_COMPILER=icpc \
    -DCMAKE_CXX_FLAGS="-O3 -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias" \
    -DCMAKE_Fortran_COMPILER=ifort \
    -DINTEL_ARCH=cpu \
    -DPKG_USER-INTEL=yes \
    -DBUILD_OMP=yes \
    -DPKG_USER-OMP=yes \
    -DPKG_MC=yes

make
```

**Comment by akohlmey** [comment]
I cannot reproduce it. Most likely, you picked the wrong LAMMPS executable while checking (note: `lmp -j` != `./lmp -h`). Please provide matching output or close this issue as 'invalid'

**Comment by uihsnv** [comment]
Oh shoot! You're right. I also have an `lmp`executable in `/usr/bin`, which is my main install of lammps. I am very sorry. How do I add the invalid label?
