### ISSUE TITLE
Inconsistent per atom kinetic energy!!!

### ISSUE THREAD

**Issue by Amingeo** [lammps/lammps#1487]
**Summary**
Dear everyone,
I just recently noticed a strange inconsistency between the calculated per atom kinetic energy and what calculated using velocity values after applying correct conversion factors for units.
Very briefly, I dumped vx, vy and vz and ke/atom (c_xxx ), then I divided the (vx^2+vy^2+vz^2) by the dumped kinetic energy per atom for each atom and expected to get the same number for all atoms (the conversion factor of units*.5*m) but surprisingly I obtained various numbers for each one. I also tried increasing the accuracy of calculations to reduce the round off errors but nothing changed. That seems to be a serious problem. Please check it.

**LAMMPS Version and Platform**

12Dec2018
**

**Comment by akohlmey** [comment]
I cannot reproduce it. If i add the following lines to the peptide example:
```
compute ke all ke/atom
variable ke atom 0.5*mass*(vx*vx+vy*vy+vz*vz)
variable ratio atom c_ke/v_ke

dump ke all custom 10 ke.lammpstrj id c_ke v_ke v_ratio
```
I get 2390.06 for **all** atoms which is the conversion factor for "m/2*v**2" as set in the file update.cpp as:
```
    force->mvv2e = 48.88821291 * 48.88821291;
```

Also, if you look at the source code of `compute ke/atom` it is very obviously correct.

**Comment by Amingeo** [comment]
I already checked, the LAMMPS source code and found it ok. Maybe it happens when distributing atoms between cpu cores. I did just a simple Argon simulation for an ensemble of 500k atoms and 32 cores.

**Comment by Amingeo** [comment]
Please try to recalculate it from the dump file, using vx,vy,vz and ke/atom and you will see what I said

**Comment by Amingeo** [comment]
The inconsistency is found between the dumped vx,vy,vz and ke/atom (it happens somehow during dumping I think, otherwise using the script you wrote and doing it inside LAMMPS, it works alright, I mean after dumping the velocity and energy values)

**Comment by akohlmey** [comment]
> Please try to recalculate it from the dump file, using vx,vy,vz and ke/atom and you will see what I said

you have to prove to us what is exactly the issue and show in detail exactly how you compute it and not the other way around.

**Comment by Amingeo** [comment]
Please try this code (I made it small and it is finished quit fast), Pelase after that, open the dump file, using vx,vz,vy, just calculate (vx^2+vy^2+vz^2) divided by ke/atom of the same atom for just two atom to see the difference I am talking about. Thanks in advance

boundary        p p p                                                   
dimension       3                                                        
units           metal							 
atom_style	atomic
log             1000K.log
####################################  BOX
region		box block 0 250  0 250  0 250  units box
create_box	1 box

##################################### CREATE ATOMS
lattice		sc 25                                
region		cube block 0 250 0 250 0 250 units box
create_atoms	1 region cube

##################################### MASS
mass            1  39.95
velocity        all create 1000 12345 mom yes rot yes dist uniform

##################################### POTENTIAL
pair_style	lj/cut 10         
pair_coeff	1 1 0.0101 3.3952

##################################### ENSEMBLE
fix		1 all nvt temp 1000 1000 0.01  
timestep	0.001 #ps  or 1fs
thermo		2000
thermo_style    custom  step temp press
run		10000
unfix      1                    
#####################################
fix		2 all nve
thermo_style    custom  step temp press   
compute 1 all ke/atom
##################################### TIME STEP
timestep	0.0002 #ps 0.2fs

#####################################  Movie And Run          
dump		1 all custom 5000 dump1000.xyz  vx vy vx c_1
restart         10000   1000k.restart                            
run		10000

**Comment by akohlmey** [comment]
when i change the dump line to 

> Please try this code (I made it small and it is finished quit fast), Pelase after that, open the dump file, using vx,vz,vy, just calculate (vx^2+vy^2+vz^2) divided by ke/atom of the same atom for just two atom to see the difference I am talking about. Thanks in advance

[...]

what i see is an error in your script:

> ##################################### Movie And Run
> dump	1 all custom 5000 dump1000.xyz vx vy vx c_1

this is not dumping vx, vy, and vz, but vx, vy, and **vx**.

**Comment by Amingeo** [comment]
you are right, thanks for prompt checking and sorry for this obvious blunder

**Comment by akohlmey** [comment]
> you are right, thanks for prompt checking and sorry for this obvious blunder

Next time, please follow the recommendations in our issue templates and provide an input example to exactly reproduce an issue. Then this can be resolved right away.
