### ISSUE TITLE
Extend output in finish.cpp to correctly reflect threads used by KOKKOS

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#149]
Currently the run summary output will report OpenMP threads only in relation to their use in the USER-OMP package. In cases where the package is not installed, but KOKKOS is used with OpenMP threads, the output claims that no threads are used. This needs to be amended to report KOKKOS threads as well.

**Comment by akohlmey** [comment]
We also need to consider, that some features, e.g. pair style snap, have OpenMP support without being either part of KOKKOS or USER-OMP.

**Comment by stanmoore** [comment]
This should now be fixed for Kokkos and in the Git repo by tomorrow.
