### ISSUE TITLE
[BUG] Two issues with pair_style extep

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#1493]
**Summary**

I found two issues with pair_style extep:
1. It requires that all elements from the potential file are used in `pair_coeff`.
1. It does not work when `NULL` is used in `pair_coeff`.

**LAMMPS Version and Platform**

Current master, Linux

**Expected Behavior**

1. It should be possible to use line like `pair_coeff B`.
1. When using extep with `pair_style hybrid` line like `pair_coeff * * BN.extep B N NULL` should be accepted.

**Actual Behavior**

1. LAMMPS quits with an error: "ERROR: Incorrect format in ExTeP potential file (../pair_extep.cpp:752)"
2. LAMMPS quits with an error: "ERROR: Insufficient spline parameters in potential file (../pair_extep.cpp:644)"

**Steps to Reproduce**

First:
region      u sphere 0 0 0 10
create_box  1 u
pair_style  extep
pair_coeff  * * BN.extep N

Second:
region      u sphere 0 0 0 10
create_box  3 u
pair_style  hybrid/overlay extep lj/cut 4.0
pair_coeff  * * extep BN.extep N B NULL

**Further Information, Files, and Links**

I'm not sure what is the cause for the first problem, but the second issue can be resolved by changing `atom->ntypes` to `nelements` in line:
https://github.com/lammps/lammps/blob/0849e03d1b6d816bd96966c57dbe3ef18ed134c4/src/USER-MISC/pair_extep.cpp#L708

EDIT: The change fixes problem only if `NULL` is the last atom type(s), so it isn't a whole solution.

**Comment by akohlmey** [comment]
Am looking into it. There are several places where edits are needed for systems with only one element or for use with pair style hybrid.

**Comment by mkanski** [comment]
I think I solved it, please see the PR.
