### ISSUE TITLE
Packages for LAMMPS stable release 05 Jun 2019

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1495]
For @junghans 

- [ ] OpenSuse: https://build.opensuse.org/request/show/708182
- [x] Fedora: https://koji.fedoraproject.org/koji/taskinfo?taskID=35323371
  - [x] Rawhide (F31): https://koji.fedoraproject.org/koji/taskinfo?taskID=35316008
  - [ ] Fedora 30: https://bodhi.fedoraproject.org/updates/FEDORA-2019-78b8f6a93e
  - [ ] Fedora 29: https://bodhi.fedoraproject.org/updates/FEDORA-2019-a6fa217d46
  - [x] Fedora 28 - EOL'ed on 2019-05-28, not possible anymore
  - [ ] CentOS 7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-b725bcf633
- [x] Gentoo: https://github.com/gentoo/gentoo/commit/8755577391662880596e55760860d7ffe65318a5
- [x] Spack: https://github.com/spack/spack/pull/11638

For @gladk
- [ ] Debian package

For @akohlmey 
- [x] Windows installer packages

For @rbberger 
- [ ] Docker

**Comment by uihsnv** [comment]
This may not really count because it isn't a binary build, but more of a Archlinux-specific build-script, but still: https://aur.archlinux.org/packages/lammps/

**Comment by junghans** [comment]
@uihsnv same for gentoo, I will just add Arch to list next time.

**Comment by junghans** [comment]
Thanks @physkets.

**Comment by uihsnv** [comment]
@junghans Would you be interested if I made a Pull Request with additions to the `Install_linux` documentation page, to include information on the Archlinux package?

p.s. I am @physkets

**Comment by junghans** [comment]
> @junghans Would you be interested if I made a Pull Request with additions to the `Install_linux` documentation page, to include information on the Archlinux package?

Why not!

**Comment by ellio167** [comment]
@junghans FYI, I submitted an update for Homebrew and it has been accepted:

https://github.com/Homebrew/homebrew-core/pull/41228

**Comment by akohlmey** [comment]
next LAMMPS stable release is out making this issue obsolete.
