### ISSUE TITLE
Reorganise Vim syntax files

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1500]
**Summary**

The files in `tools/vim/` can be organised to conform to standard installations of vim syntax files, so that it is easier for linux distributions to install them.

**LAMMPS Version and Platform**

 * 5 Jun 2019
 * Linux

**Details**

The recommended way is to put the `lammps.vim` file in a `syntax` directory and the part given in the `README` in a `ftdetect` directory. So if this hierarchy can be made in the `tools/vim/` area of the source, it will make it simple for packagers to add these syntax files.

* `tools/vim/syntax/` containing the current `lammps.vim` file,
* `tools/vim/ftdetect/` containing:

```
augroup filetypedetect
 au! BufRead,BufNewFile in.*           setfiletype lammps
 au! BufRead,BufNewFile *.lmp          setfiletype lammps
augroup END
```
The `if exists()` isn't necessary, and the `filetypedetect` mechanism is supposed to take care that everything is in order.

I've verified that placing those files in said directories, in `/usr/share/vim/vimfiles/` results in lammps files having appropriate syntax colouration.

**Comment by akohlmey** [comment]
Please note that the primary target of the LAMMPS (source) distribution are regular users, not people that re-package LAMMPS for distributions. From your description it looks like all that is needed would be an addition to the README file explaining what has to go where for a `vim-lammps` package instead of a user's $HOME/.vim` folder.

**Comment by uihsnv** [comment]
Putting them in separate folders would actually simplify things for users also, because then, they just have to copy the two directories into their `~/.vim/`.

**Comment by akohlmey** [comment]
> Putting them in separate folders would actually simplify things for users also, because then, they just have to copy the two directories into their `~/.vim/`.

I think we can expect people to be intelligent enough to follow instructions of the kind `copy file 1 to folder X` and `copy file 2 to folder Y` or `create a file 3 with the contents as shown below and copy it to folder Z`.

**Comment by uihsnv** [comment]
Okay, so how about that^ ? I put the stuff in the README in an actual file, so packagers can script its installation, and it isn't sitting inside directories, so typical users can see it in `/tools/vim/`. I also modified the instructions accordingly.

**Comment by uihsnv** [comment]
@junghans This will be especially useful for the various packages that you manage.
