### ISSUE TITLE
[BUG] USER-TALLY computes with hybrid pair styles only store results for last style

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1509]
**Summary**

When several pair styles are used via "pair_style hybrid" or "pair_style hybrid/overlay", only the results from the last pair style are stored in the */tally computes. I've only tested pe/tally and heat/flux/tally, but this is probably valid for other tally computes as well. This appears to be because each pair class calls the "pair_setup_callback" function for the same compute, thus discarding the results computed for previous pair sytes.

**LAMMPS Version and Platform**

Tested with latest master version.

**Steps to Reproduce**

The following script demonstrates the problem:
```
units real
region box block -30 30 -30 30 -30 30
create_box 1 box

pair_style hybrid/overlay lj/cut 12.0 morse 12.0
#pair_style hybrid/overlay morse 12.0 lj/cut 12.0
pair_coeff * * lj/cut 1 3
pair_coeff * * morse  10 2 3
mass * 100

create_atoms 1 single -2 0 0
create_atoms 1 single 2 0 0

compute pe_gg all group/group all
compute pe_tally all pe/tally all

thermo_style custom c_pe_gg c_pe_tally
run 0
```

**Expected Behavior**

Both group/group and pe/tally computes should produce the same result.

**Actual Behavior**

Currently, pe/tally only gives potential energy for Morse. If you swap the order in pair_style command, it will only give the potential energy for LJ.

**Comment by akohlmey** [comment]
Thanks for the report and the example. Pull request #1513 should correct the problem.
