### ISSUE TITLE
update needed for `examples/USER/misc/kolmogorov_crespi_full`

### ISSUE THREAD

**Issue by boyoungzheng** [lammps/lammps#1515]
**Summary**

It may be necessary to update `examples/USER/misc/kolmogorov_crespi_full` as it is done in `examples/USER/misc/kolmogorov_crespi_z`. Namely, from `airebo` to `rebo`.

**LAMMPS Version and Platform**

LAMMPS (31 May 2019)
$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Stepping:              2
CPU MHz:               2494.224
BogoMIPS:              4988.44
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-7

**Details**

_Please explain the issue in detail here_
I was testing `examples/USER/misc/kolmogorov_crespi_full` but it failed with 
```
ERROR on proc 0: Cannot open REBO2 potential file CH.airebo (src/MANYBODY/pair_airebo.cpp:3393)
Last command: pair_coeff  * * rebo                     CH.airebo      NULL C  # chemical
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
I found [this email thread](https://sourceforge.net/p/lammps/mailman/message/36662045/) and the discussion there **fixed** my problem. This thread also suggests file an issue here for a missing update, that is what I am doing now. I also noticed that `examples/USER/misc/kolmogorov_crespi_z` has been updated and runs through with no problem.

**Comment by akohlmey** [comment]
Thanks for reporting. You are correct, this needs to be addressed. Not sure how it escaped checking all inputs when making the change. Will take care of it ASAP.
