### ISSUE TITLE
[BUG] Doc build: doc_anchor_check.py misses many internal anchors

### ISSUE THREAD

**Issue by eagunn** [lammps/lammps#1519]
**Summary**

As part of the work I am doing for #1334, I've modified doc/utils/converters/lammpsdoc/doc_anchor_check.py 
to check the new rst files rather than old txt files. This was a one-line change to the regex expression. 

As a sanity check, I added logging to both versions to verify the same number of links were found by both. Instead, I find that the txt version finds 574 anchor labels while the rst version finds 769. I believe the rst version is finding the right number of links and the txt version was missing a couple of hundred. 

**LAMMPS Version and Platform**

LAMMPS was pulled straight from github master branch about 10 days ago. Last commit in the log:
Merge: 045c312c4 272c53632
Author: Axel Kohlmeyer <akohlmey@gmail.com>
Date:   Tue Jun 4 15:23:13 2019 -0400
    Merge pull request #1490 from akohlmey/next_version
    Step version number for stable release

**Expected Behavior**

New rst version should identify all internal links and does so automatically because of how txt links with preceding text were translated into rst links across multiple lines.

**Actual Behavior**

The difference in results comes from the fact that the txt regex pegs the search to the start of a line:
`anchor_pattern = re.compile(r'^:link\(([^,\)]*)\)')`
So it finds links like
`:link(angle-MacKerell)`
[doc/src/angle_charmm.txt, line 87]
but misses links like
`Serial vs parallel build :h4,link(serial)`
[doc/src/Build_basics.txt, line 23]

I wrote the rst regex to peg to the start of a line also
`anchor_pattern = re.compile(r'^\.\. _(.*):$')`
but in the course of the txt2rst conversion, the second line above was converted to:
`.. _doc:`
` `
`Build the LAMMPS documentation`
which results in the link being found by my regex.

I'm reporting this as a defect in the old code because that seemed like the clearest way to describe it. But this is as much a question about my understanding of the desired behavior of doc_anchor_check.py which, AFAICS, should:
- find internal links
- ignore external links (which are identified by having a comma inside the link parentheses)
- verify there are not multiple links with the same name (which would result in multiple html elements with the same id)

I am not suggesting the old code be fixed until/unless the implementation of #1334 is shelved.

**Steps to Reproduce**

The file references above should be enough for someone (@rbberger  ?) to verify the defect and tell me whether or not the new code is working better or not.

**Further Information, Files, and Links**

Happy to provide more if needed. Just let me know.

**Comment by akohlmey** [comment]
doc_anchor_check.py has been replaced with rst_anchor_check.py, which included the correction mentioned above.
