### ISSUE TITLE
[Feature Request] Clarify the relation between USER-TALLY computes and dynamic groups

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1521]
**Summary**

Although currently all of USER-TALLY computes accept dynamic groups without complaining, this often produces results that are most likely unintended by the user. I am not sure if this can be classified as a bug, therefore I would like this issue to be at least clarified in the documentation.

**Detailed Description**

Dynamic groups are setup during the post_integrate stage. On the other hand, USER-TALLY computes are implemented as callbacks during the pairwise force computations. Because of this, during initial force computation at step 0 dynamic groups are empty, which is unexpected unless one is familiar with the actual implementation details. This can be solved by executing "run 0" before the main computation to force dynamic group construction, therefore this in itself is not a large issue.

Unfortunately, I've found that when executing USER-TALLY computes with dynamic groups without prepending "run 0", which the user might do if he doesn't care about the values at step 0, also produces incorrect values in the subsequent computations. For example, using pe/tally with dynamic groups in the following script:
```
units real

pair_style lj/cut 12

region box block -15 15 -15 15 -15 15
create_box 1 box
pair_coeff * * 1 3
mass * 100
create_atoms 1 random 10 101 box
velocity all create 100 101

region inf block INF INF INF INF INF INF
group dall dynamic all region inf every 1

fix integ all nve
#run 0

compute   pe  all pe
compute stpe  all pe/tally  all
compute dtpe dall pe/tally dall

thermo 1
thermo_style custom step c_pe c_stpe c_dtpe
thermo_modify format float %.17e

run 5
```

Produces these results:

> Step c_pe c_stpe c_dtpe 
>        0 -4.22768097887963948e-02 -4.22768097887964017e-02 0.00000000000000000e+00 
>        1 -4.22735414333879969e-02 -4.22735414333880247e-02 -1.50152175689973015e-02 
>        2 -4.22702580557454272e-02 -4.22702580557454272e-02 -1.50056628371679785e-02 
>        3 -4.22669596321978633e-02 -4.22669596321978494e-02 -1.49961151144276019e-02 
>        4 -4.22636461391601853e-02 -4.22636461391601784e-02 -1.49865743947735428e-02 
>        5 -4.22603175531332254e-02 -4.22603175531332323e-02 -1.49770406722097276e-02 

This has been tested with the latest master version. All computes produce the same values  if "run 0" is executed beforehand. I can understand the 0 for c_dtpe at step 0, but even having cursory look at the source code still did not give me an idea why the values for the subsequent computations are also wrong and why pre-running "run 0" seems to fix all of the issues.

Ideally, it would be desirable that USER-TALLY computes would work with dynamic groups without prepending "run 0", but clearly documenting the issues and workarounds is also acceptable. I would like to not have dynamic group support removed from USER-TALLY computes, as they have some very beneficial use cases.

**Comment by akohlmey** [comment]
A long time ago, when dynamic groups were introduced, it was decided to assume by default that fixes are not compatible and computes are. The computes in the USER-TALLY package are, by the very nature of how they work, not compatible with dynamic groups. Thus they need to be flagged as incompatible. Thanks for pointing this out.

**Comment by donatas-surblys** [comment]
Thank you for the clarification. Shame to not have this functionality as it would have been an easy way to have control areas and control volumes of various shapes and sizes. I guess the "run 0" hack was not sufficient and would break easily. So, if I wanted such functionality in my custom tally compute should I implement it internally like it was done in stress/mop compute or maybe call set_group for dynamic groups from the tally compute pair_setup_callback function?

**Comment by akohlmey** [comment]
>  So, if I wanted such functionality in my custom tally compute should I implement it internally like it was done in stress/mop compute or maybe call set_group for dynamic groups from the tally compute pair_setup_callback function?

The problem is by using the callback mechanism, you collect the information during a different phase of the simulation then when you are accessing it. Access may happen at different times. The only way to make it compatible with dynamic groups is to actually compute the property directly when requested, e.g. via `pair->single()`. That has its own limitations, but then you do the selection of which atoms to look at while you are creating the output, so inconsistencies due to dynamic groups are avoided.
