### ISSUE TITLE
[BUG] Minor cleanup needed for doc/src/Eqs folder

### ISSUE THREAD

**Issue by eagunn** [lammps/lammps#1526]
**Summary**

I've found eight .jpg files in the doc/src/Eqs folder for which no .tex equation source file currently exists. 
- Two of these are simply not equation images and should be moved to folder JPG. 
- For the others, we probably want to find/recreate the source .tex files eventually. For now, they are not causing any problems but are not exemplary if anyone happens to use them as a model for how to add documentation. Having the .tex source will become slightly more urgent if/when we decide to go ahead with implementation of #1334. I assume the goal at that point will be to have only one file for each equation/equation set in Eqs: the .tex source.

**LAMMPS Version and Platform**

Files analyzed are from current Github master branch.

**Expected Behavior**

Virtually all of the .jpg files in doc/src/Eqs are accompanied by a .tex source file.

Every valid equation image should have a companion .tex source checked in.

Non-equation images should be stored in folder doc/src/JPG

**Actual Behavior**

The following two images are not equation images and should be moved to doc/srcs/JPG:
- Eqs/dreiding_hbond.jpg
- Eqs/umbrella.jpg

The following six images are equations for which .tex source files are not currently checked in:
- Eqs/angle_class2_p6.jpg
- Eqs/angle_cosine_buck6d.jpg
- Eqs/improper_inversion_harmonic.jpg
- Eqs/pair_agni.jpg
- Eqs/pair_buck6d.jpg
- Eqs/pair_coul_gauss.jpg

**Steps to Reproduce**

I found these files using a script I'm developing to insert the tex equation markup directly into the .rst versions of the documentation files. That script is only relevant in the context of work on #1334. But you can simply look in the doc/src/Eqs folder and see that these 8 .jpg files do not have accompanying .tex

**Further Information, Files, and Links**

**Comment by eagunn** [comment]
This issue should have a "documentation" label. But I don't see the checkbox I would use to add the label when I try to follow the instructions at:
[How to apply a label](https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests)
It appears I need write access, which I don't have. So I'll assume that this is a privileged operation and not my concern until/unless I hear otherwise.

**Comment by eagunn** [comment]
I'm happy to volunteer to move the two non-equation files to JPG and change the .txt files that refer to them. It would be good practice in walking through the pull/merge cycle with a trivial change.

There are also a couple of the equations in .jpg that I might be able to hack out the markup for but certainly not all of them. Perhaps the originators of the doc files that use them might still have them around. Or be willing to re-engineer.

**Comment by akohlmey** [comment]
> I'm happy to volunteer to move the two non-equation files to JPG and change the .txt files that refer to them. It would be good practice in walking through the pull/merge cycle with a trivial change.

agreed.

> There are also a couple of the equations in .jpg that I might be able to hack out the markup for but certainly not all of them. Perhaps the originators of the doc files that use them might still have them around. Or be willing to re-engineer.

don't worry about the missing .tex files. been using LaTeX for an eternity. i can easily re-create them.

**Comment by akohlmey** [comment]
> This issue should have a "documentation" label. But I don't see the checkbox I would use to add the label when I try to follow the instructions at:
> [How to apply a label](https://help.github.com/en/articles/applying-labels-to-issues-and-pull-requests)
> It appears I need write access, which I don't have. So I'll assume that this is a privileged operation and not my concern until/unless I hear otherwise.

correct. github had traditionally only the option between full write access and read-only access. they are experimenting with new user roles, that would allow people without write access to triage new reports. but we're waiting until that feature has matured.

**Comment by akohlmey** [comment]
> I'm happy to volunteer to move the two non-equation files to JPG and change the .txt files that refer to them. It would be good practice in walking through the pull/merge cycle with a trivial change.
> 
> There are also a couple of the equations in .jpg that I might be able to hack out the markup for but certainly not all of them. Perhaps the originators of the doc files that use them might still have them around. Or be willing to re-engineer.

the missing LaTeX files are regenerated and now included in PR #1525 
one of them wasn't missing, but named by accident .txt instead of .tex.

**Comment by akohlmey** [comment]
moving the non-equation files to the JPG folder and updating the .txt files referencing them has been included in #1525 as well. This issue will be closed automatically, when the PR is merged.
