### ISSUE TITLE
[BUG] _ncachex memory allocation error

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1532]
**Summary**

A memory allocation error appears after reading in a restart file:

Stdout:
`ERROR on proc 1: Failed to allocate -156019200 bytes for array _ncachex (src/memory.cpp:64)`
Stderr:
`Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1`

**LAMMPS Version and Platform**

* LAMMPS (18 Jun 2019)
* Linux
* Intel Core i7-6700K

**Steps to Reproduce**

1. Compile LAMMPS with the INTEL and OMP packages
2. Use: `-suffix hybrid intel omp -package intel 0 omp 2`

I am unable to reliably reproduce this issue. But I'm reporting it anyway.

**Further Information, Files, and Links**

[alloc.txt](https://github.com/lammps/lammps/files/3314658/alloc.txt)

**Comment by wmbrownIntel** [comment]
Thanks for your time in reporting this Vishnu. The above pull-request should fix the problem.
