### ISSUE TITLE
[BUG] pair hybrid doesn't store compute_tally array in restart file

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1536]
**Summary**

Currently, PairHybrid class doesn't store compute_tally array in restart files, leaving the compute_tally array uninitialized when restarting.

**LAMMPS Version and Platform**

Tested on latest master version.

**Steps to Reproduce**

The following script demonstrates the behaviour.
```
region box block -30 30 -30 30 -30 30
create_box 1 box
create_atoms 1 single -1 0 0
create_atoms 1 single 1 0 0
pair_style hybrid/overlay lj/cut 12.0 morse 12.0
pair_coeff * * lj/cut 1 3
pair_coeff * * morse  10 2 3
mass * 100

compute pe all pe/tally all
thermo_style custom step c_pe
run 0
write_restart restart.lmp

clear
units real
pair_style hybrid/overlay lj/cut 12.0 morse 12.0
read_restart restart.lmp
#pair_style hybrid/overlay lj/cut 12.0 morse 12.0
pair_coeff * * lj/cut 1 3
pair_coeff * * morse  10 2 3

compute pe all pe/tally all
thermo_style custom step c_pe
run 0

```

**Expected Behavior**

The script should have produced two identical runs.

**Actual Behavior**

The script segfaults. This can be avoided by calling the pair_modify command after read_restart.

**Comment by akohlmey** [comment]
confirmed. there was also a memory leak related to the compute_tally array. should be fixed in PR #1525
