### ISSUE TITLE
[BUG] Difference between lj96/cut and lj96/cut/gpu

### ISSUE THREAD

**Issue by jdevemy** [lammps/lammps#1549]
**Summary**

The output between the `lj96/cut` and `lj/96/cut/gpu` are different and so the simulation crashes with the GPU accelerated pair_style.

**LAMMPS Version and Platform**

LAMMPS 12 Dec 2018

I tested the bug on 2 machines : both have P100 GPU card, and Intel CPUs working on CentOS 7.6.

I've also tested with _doubledouble_ Cuda Lammps version, but the error is the same.

**Expected Behavior**

I expect to have the same result (except for round-off and precision issues).

**Actual Behavior**

When running the simulation with `lj96/cut`, at **Step 0**, the pressure is around 1.
With `lj96/cut/gpu`, the pressure is around 6000.

In the last case, the simulation crashed at Step 2 because of NANs.

**Steps to Reproduce**

I've attached a file containing the input file, data file and angle table data.

When running :
`mpirun -np 2 lmp_cuda -i in.lmp`
it works well.

but when running :
`mpirun -np 2 lmp_cuda -sf gpu -i in.lmp`
the output is totally different.

**Further Information, Files, and Links**

[bug_gpu_lj96cut.tar.gz](https://github.com/lammps/lammps/files/3350559/bug_gpu_lj96cut.tar.gz)

**Comment by ndtrung81** [comment]
@jdevemy thanks for reporting this issue. Please check out the PR #1550 for the bug fix.

**Comment by jdevemy** [comment]
Thanks for the quick fix, it works for me : thanks !
