### ISSUE TITLE
Memory leak in compute_omega_chunk.cpp

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#157]
In the constructor, it calls allocate() which allocates variables
memory->create(massproc,maxchunk,"omega/chunk:massproc");
  memory->create(masstotal,maxchunk,"omega/chunk:masstotal");
  memory->create(com,maxchunk,3,"omega/chunk:com");
  memory->create(comall,maxchunk,3,"omega/chunk:comall");
  memory->create(inertia,maxchunk,6,"omega/chunk:inertia");
  memory->create(inertiaall,maxchunk,6,"omega/chunk:inertiaall");
  memory->create(angmom,maxchunk,3,"omega/chunk:angmom");
  memory->create(angmomall,maxchunk,3,"omega/chunk:angmomall");
  memory->create(omega,maxchunk,3,"omega/chunk:omega");

but these aren't destroyed in the destructor. Is this a bug or is there some memory handling I don't know about?

**Comment by akohlmey** [comment]
How about you create a minimal input using the compute and run it through valgrind's memcheck?
If you confirm the leak, you can fix it yourself (i.e. assign yourself to the issue and submit a PR) or upload/include the input deck here and pass the buck to me.
