### ISSUE TITLE
Errors building LAMMPS with PLUMED

### ISSUE THREAD

**Issue by GiovanniBussi** [lammps/lammps#1579]
**Summary**

I would like to report a few issues I had to fix while preparing a conda recipe for LAMMPS. Below I describe the issues in detail and how I fixed them by [patching the LAMMPS code base](https://github.com/plumed/conda/blob/master/lammps/build.sh). It might be a good idea to fix LAMMPS code directly.

The first two issues are actual bugs leading to errors. The third one is an unnecessarily linked library that might be ignored (it is harmless).

Thanks!

**LAMMPS Version and Platform**

LAMMPS version I tested is June 5, 2019.

For the three points below:
1. Serial version
2. OSX
3. Any version

**Details**

1. There is a line containing `"setMPIComm"` in `src/USER-PLUMED/fix_plumed.cpp`. That line should only be executed when LAMMPS is compiled with real MPI. Otherwise, users will not be able to combine serial PLUMED with serial LAMMPS since PLUMED will complain that it is receiving a communicator but was not compiled with MPI.

2. In files `cmake/CMakeLists.txt` and `lib/plumed/Makefile.lammps.runtime`, `libplumedKernel.so` should be replaced with `libplumedKernel.dylib` when compiling on OSX.

3. In file `cmake/CMakeLists.txt`, requirement for lapack can be lifted when PLUMED is linked in runtime or ~static~ **shared** mode.

**Comment by GiovanniBussi** [comment]
@akohlmey sorry I just fixed the last point.

**Comment by mkanski** [comment]
There is also a dead link to the PLUMED documentation in the LAMMPS manual. It points to `http://www.plumed.org/documentation` instead of `https://www.plumed.org/doc.html`.
