### ISSUE TITLE
[BUG] Link failure: undefined reference to `__builtin_is_constant_evaluated'

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1585]
**Summary**

The build fails at link-time, with the following output:

```
[100%] Linking CXX executable lmp
ld: CMakeFiles/lmp.dir/tmp/makepkg/lammps-beta/src/lammps-patch_19Jul2019/src/citeme.cpp.o: in function `LAMMPS_NS::CiteMe::add(char const*)':
citeme.cpp:(.text+0x70a): undefined reference to `__builtin_is_constant_evaluated'
ld: citeme.cpp:(.text+0x73d): undefined reference to `__builtin_is_constant_evaluated'
ld: citeme.cpp:(.text+0x780): undefined reference to `__builtin_is_constant_evaluated'
ld: citeme.cpp:(.text+0x7c8): undefined reference to `__builtin_is_constant_evaluated'
ld: citeme.cpp:(.text+0x7fd): undefined reference to `__builtin_is_constant_evaluated'
make[2]: *** [CMakeFiles/lmp.dir/build.make:7350: lmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/lmp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**LAMMPS Version and Platform**

Version: 19Jul2019
Platform: Linux

**Steps to Reproduce**

I'm building with `cmake`, and am using the Intel compilers. I am using a build-script similar to the following, modified for the latest patch release.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lammps-beta

**Comment by rbberger** [comment]
@uihsnv you are not providing sufficient information to reproduce this issue.

If you want anyone to look into this you need to provide more detail. We're regularly building LAMMPS with CMake and the Intel Compiler without any issues.

Which Intel Compiler Version are you using? What is the final CMake command-line that is produced in your build script? What options are you using? What environment variables are you setting?

**Comment by uihsnv** [comment]
```
-- <<< Build configuration >>>
   Build type       
   Install path     /usr
   Compilers and Flags:
   C++ Compiler     /opt/intel/compilers_and_libraries_2019.4.243/linux/mpi/intel64/bin/mpiicpc
       Type         Intel
       Version      19.0.4.20190416
   C++ Flags        -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias -O2 -DLMP_INTEL_USELRT -DLMP_USE_MKL_RNG -restrict -qopenmp -xHost 
   Defines          LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;LAMMPS_FFMPEG;LMP_KIM_CURL;LMP_USER_OMP;LMP_USER_INTEL;LMP_INTEL_USELRT;LMP_USE_MKL_RNG
-- Linker flags:
   Executable      -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
-- Static libraries  
-- Link libraries: /usr/lib/libjpeg.so;/usr/lib/libpng.so;/usr/lib/libz.so;/usr/lib/libcurl.so;-lkim-api;m;/usr/lib/libtbbmalloc.so;/opt/intel/compilers_and_libraries_2019.4.243/linux/mkl/lib/intel64/libmkl_rt.so
```

Also, I'm building the `MC`, `KIM`, `USER-OMP` and `USER-INTEL` packages.

What environment variables should I be looking at?

**Comment by rbberger** [comment]
Again, what is the cmake command you are using? Are you injecting any compiler flags through environment variables or to cmake directly?

I would try removing KIM and see if it compiles.

**Comment by uihsnv** [comment]
I tried the compilation without KIM, but it still fails the same way.

These are the flags I pass on to cmake:

```
-DCMAKE_INSTALL_PREFIX="/usr"
-DCMAKE_INSTALL_LIBDIR="lib"
-DCMAKE_INSTALL_LIBEXECDIR="/usr/lib"
-DCMAKE_C_COMPILER=mpiicc
-DCMAKE_C_FLAGS=-xHost -O2 -fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high
-DCMAKE_CXX_COMPILER=mpiicpc
-DCMAKE_CXX_FLAGS=-fp-model fast=2 -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias -O2 -DLMP_INTEL_USELRT -DLMP_USE_MKL_RNG
-DCMAKE_Fortran_COMPILER=mpiifort
-DPKG_KIM=yes
-DINTEL_ARCH=cpu
-DPKG_USER-INTEL=yes
-DBUILD_OMP=yes
-DPKG_USER-OMP=yes
-DPKG_MC=yes
```

As far as I know, I am not modifying cmake's behaviour in any way.

**Comment by rbberger** [comment]
This is a Intel Compiler issue. See https://software.intel.com/en-us/forums/intel-c-compiler/topic/810447 and the release notes of the Intel compiler.

I was able to reproduce it on my Arch system. Arch has GCC 9.1, which is not officially supported.

As a workaround you can try adding `-std=c++11` or `-std=c++14` to your compilation flags. At least for me that produced a build under Arch Linux.

**Comment by uihsnv** [comment]
This will have to be fixed in the `CMakeLists.txt` for when Intel compilers are used, because GCC 9.x will eventually be supported, and the C++ standard of the code base is probably not going to change. So I do think it is a valid bug, that needs to be fixed, and might as well be fixed now.

Using `-std=c++11` works for me.

**Comment by akohlmey** [comment]
No it is not a valid bug. Using and unsupported combination of tools is a user error. If the intel compilers will support gcc 9.x they will have to take care of issues like that internally from the compiler. The hack you are suggesting may not work in the future and i refuse to put workarounds for unsupported combinations of tools into the configuration management. You can easily set additional compiler flags via CMAKE_CXX_FLAGS when running the cmake configuration, if you insist on continuing the combination of tools like this.
If anything, you could argue that the intel compilers should be more strict and stop with an error when the underlying gcc is not compatible like the nvcc compiler of the nvidia CUDA package does.
