### ISSUE TITLE
[regression] Potentials are installed into potentials/potentials

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#1586]
```5Jun2019``` installed them into ```/usr/local/share/lammps/potentials```, ```19Jul2019``` installs them into ```/usr/local/share/lammps/potentials/potentials```.
Moving them into ```potentials/potentials``` seems wrong.

Found while trying to update the FreeBSD port.

**Comment by akohlmey** [comment]
@yurivict thanks for reporting. i vaguely recall, that this issue had showed up before and was corrected. not sure what made it reappear. the fix is straightforward and will be available in the next LAMMPS release.

**Comment by yurivict** [comment]
https://github.com/lammps/lammps/pull/1588
