### ISSUE TITLE
[BUG] binning using chunk/atom bin/sphere & ave/chunk density/number

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#1589]
**Summary**

I create N radial bins around a fixed position in my simulation box using the compute chunk/atom bin/sphere command. I average the data using the compute ave/chunk command with the density/number option. It seems that all atoms which do not belong to the first N-1 
bins are grouped in the last N-th bin. The same holds true if I use the keyword density/mass. The resulting value for the last bin is too high.

A related issue: srmin and srmax values in chunk/atom bin/sphere can be larger than the length of the simulation box. I would expect that an error or warning would occur in this case. 

**LAMMPS Version and Platform**

latest version from the master branch at Github 

**Expected Behavior**

The last bin should include only the atoms that are spatially located in the given bin distances and not all atoms with a distance greater than the last bin.

**Actual Behavior**

The last bin includes all atoms with a distance greater than the (N-1)-th bin.

**Steps to Reproduce**

A set of input files to reproduce this issue can be find in https://drive.google.com/open?id=1SCZJZbnqV6ByyoXS6rcZmDKDDksBx3l6

**Further Information, Files, a
_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by rbberger** [comment]
This is documented behavior. See the manual for [chunk/atom](https://lammps.sandia.gov/doc/compute_chunk_atom.html):

> If discard is set to **mixed**, which is the **default**, 

> For the bin/sphere style the details are as follows. If discard is set to yes, an out-of-domain atom will have its chunk ID set to 0. If discard is set to no or **mixed**, the atom will have its chunk ID set to the first or last bin, i.e. the innermost or outermost spherical shell. If the distance of the atom from the origin is less than rmin, it will be assigned to the first bin. **If the distance of the atom from the origin is greater than rmax, it will be assigned to the last bin**.

Add `discard yes` and see if this is the behaviour you want.

**Comment by evoyiatzis** [comment]
You are right @rbberger. My "expected" behavior is not the same with the default settings of LAMMPS. 
The addition of discard yes gives the behavior I want.
