### ISSUE TITLE
Manual link is broken

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#159]
Link from main web page is broken: [http://lammps.sandia.gov/doc/Manual.html](http://lammps.sandia.gov/doc/Manual.html)

It just shows 'no title'.

This is also the page you go to if you click the LAMMPS 'icon' (with the house) in the top left corner in any documentation page.

**Comment by akohlmey** [comment]
This must be a side effect to Steve and me trying to work out a way to make better use of git and github and make the associated workflow changes. We've made a lot of progress and I am beginning to get excited about it, as we are approaching a solution that is better than what we had agreed on last week.

**Comment by rbberger** [comment]
Seems to be working again. Closing.
