### ISSUE TITLE
[BUG] Possible bug in calculating (only) coulomb energy via rerun cmd

### ISSUE THREAD

**Issue by hponemyintk** [lammps/lammps#1591]
**Summary**

LAMMPS' coulomb energy output (obtained using "coul/long", and "pe/atom" cmd with "pair" and "kspace" flags turned on as mentioned in the [documentation](https://lammps.sandia.gov/doc/rerun.html)) seems to be including conformational energies of the molecules. For a bulk SPC/E system, LAMMPS output positive coulomb energy for some of the atoms--opposed to the expected negative values for all the atoms (as attractive forces should dominate for equilibrated, liquid water slab). The only way to get rid of these artifacts is to manually delete bond and harmonic data in the initial configuration file and set "bond" and "harmonic" styles to "none" in lammps input script.

**LAMMPS Version and Platform**
This behavior can be reproduced on multiple versions of LAMMPS including the latest stable release:
LAMMPS (5 Jun 2019)
LAMMPS (12 Dec 2018)
LAMMPS (11 Jul 2013)

**Expected Behavior**
Ideally, the Coulomb potential energy per atoms should all be negative for an equilibrated water slab (compare output from, "Coul_NoBond_pe_atom_spce_full.dump" and "Coul_NoBond_pe_atom_spce_nogeo.dump" in the zip file). Also, the Coulomb energy calculated by LAMMPS should also match the one obtained via custom Ewald code.

**Actual Behavior**
This anomaly can be corrected if the topology data are removed from the initial configuration file. Setting the "bond" and "angle" styles to none (and leaving the topology data in the configuration file) has no effect on the Coulomb potential outputs from the rerun (see Coul_NoBond_pe_atom_spce_full.dump). Lammps output the correct coulomb values only when I removed the topology data, and set bond/angle style to zero (see Coul_NoBond_pe_atom_spce_nogeo.dump).

**Steps to Reproduce**

I have attached the input files to equilibrate a slab of SPC/E water in lammps:
1. bash_cmds_for_compilation.txt          ### steps to re-compile LAMMPS I used for this bug report with minial packages turned on 
2. lmp_spce.in                                        ### lammps input script
3. system.data                                       ### lammps initial configuration script
4. sub2Cluster.sh                                  ### PBS script to equilibrate and rerun the data

When we run lmp_spce.in, it will output a trajectory files which will be used later in the rerun scripts. The rerun scripts will write the following dump files:

5. CoulNoBond_full.in -> Coul_NoBond_pe_atom_spce_full.dump.           
**with** 
pair_style coul/long 14
bond_style      none
angle_style     none
read_data **_system.data_**   ### *** this **_include_** topology of water molecules

6. CoulNoBond_nogeo.in -> Coul_NoBond_pe_atom_spce_full.dump
**with** 
pair_style coul/long 14
bond_style      none
angle_style     none
read_data **_system_nogeo.data_**   ### *** this **_exclude_** topology of water molecules

The dump files from step 5 and 6 are very different. The one from step 5 gives negative Coulomb energies whereas, the one from step 6 without initial topology data give correct Ewald values.

**Further Information, Files, and Links**
[Kyaw_lmp_bug_report.zip](https://github.com/lammps/lammps/files/3443637/Kyaw_lmp_bug_report.zip)

**Comment by akohlmey** [comment]
please note, that ecoul only contains the short range contribution to the coulomb energy. you need to add elong to it to get the full coulomb interaction. your comparison for a system with special bonds and without is meaningless. the energies from coul/long plus kspace are consistent with the values of coul/cut in the limit of a long cutoff. this has been tested repeatedly. i don't know what your custom ewald code does, but this is something that has been tested extensively in LAMMPS, so i'd be suspecting that there is something not consistent in your custom ewald code with what it is supposed to compute.

**Comment by amlimaye** [comment]
Hi Axel,

I'm one of Kyaw's collaborators. Thanks for your quick response on this. I'm still a little confused about why the pe/atom compute computing pair + kspace energies should yield different results on a rerun of a system with bonds and without bonds. pe/atom has separate keywords for printing out bond and angle energies, so I would imagine that those are excluded from the pair + kspace energies.

I agree that the discussion of the custom Ewald code is a red herring; I'm sure the LAMMPS energies computed with coul/long + kspace are consistent with coul/cut in the limit of a long cutoff, I just don't understand why the existence of bond/angle terms in a system should change the coul/long + kspace energies on a trajectory re-run.

Thanks in advance.

**Comment by akohlmey** [comment]
> Hi Axel,
> 
> I'm one of Kyaw's collaborators. Thanks for your quick response on this. I'm still a little confused about why the pe/atom compute computing pair + kspace energies should yield different results on a rerun of a system with bonds and without bonds.

because of exclusions. for example when you look at the interaction of a water hydrogen with the oxygen of the same water, then this interaction is computed by the bond potential and the *full* coulomb and lennard-jones interaction for this pair is excluded (forces and energies).

[...]

> I agree that the discussion of the custom Ewald code is a red herring; I'm sure the LAMMPS energies computed with coul/long + kspace are consistent with coul/cut in the limit of a long cutoff, I just don't understand why the existence of bond/angle terms in a system should change the coul/long + kspace energies on a trajectory re-run.

this is common behavior is *any* MD code i know (like CHARMM, Amber, Gromos, Gromacs, NAMD, etc.). you should look it up in a proper text book.

the per-atom energies appear to be correct, since the sum matches the global values. this can be done by adding the line: `compute sum all reduce sum c_peratom` and then printing `c_sum` with the thermo output.

i see no indication of a bug in LAMMPS here anywhere, only incorrect assumptions and considerations. thus i will close this issue now.
> 
> Thanks in advance.
