### ISSUE TITLE
Random crashes in Python wrapper

### ISSUE THREAD

**Issue by joakimstenhammar** [lammps/lammps#16]
I've written a script using the Python wrapper version of LAMMPS. This is supposed to integrate a mobile wall, which is responding to the constant external pressure plus the forces coming from the LJ particles (which are self-propelled). While the code produces sensible results, it is plagued by random crashes occurring after anything between 1 second and 24 hours, without any warning or error message. Each crash seems to be preceded by a random drop or increase in the measured force on the wall a few (10-100) timesteps before crashing, which is definitely unphysical and seems to be indicating a communication fault and/or memory error. The errors are much more frequent using higher CPU numbers, but will always occur sooner or later as soon as the CPU number is > 1. The error is furthermore the same when using mpi4py instead of PyPar, so it is unlikely to be related to the MPI wrapper. 

Attached is a slightly reduced version of the Python script together with an input file that crashes within a few thousand timesteps on at least two machines when running on 8 CPUs. Version information is as follows:

Lammps-10Aug2015 compiled with icc and openMPI 1.8.4
PyPar 2.1.4.94
Python 2.7.9

Run script (test.py): https://dl.dropboxusercontent.com/u/12407652/Lammps-debug/test.py
Lammps input file (in.test): https://dl.dropboxusercontent.com/u/12407652/Lammps-debug/in.test
Starting config (conf.test): https://dl.dropboxusercontent.com/u/12407652/Lammps-debug/conf.test

It is simply executed by running python with mpirun, i.e., "mpirun -np 8 python test.py"

Kind regards, 

Joakim

**Comment by akohlmey** [comment]
I suspect the crashes are caused by the tiled communication with recursive bisectioning. i don't think this has been well tested for 2-d systems. i've seen it misbehave in a few odd cases as well. if i comment out the that command and keep the default "brick" communication, i don't see any crashes within the time frame that previously the input would crash in.

please note that binary restart files are not very portable, when you provide files for testing/debugging, it would be much better to provide a data file instead.

**Comment by joakimstenhammar** [comment]
Thanks a lot; this seems to indeed solve the crashes! I'm now doing a "brick" load balancing instead, which seems to work fine. I suggest adding a warning to the code and/or documentation when using this in conjunction with fix enforce2d to prevent this usage until it's properly tested.

However, it turned out that there was a separate issue leading to the long-time (24 hrs) crashes, namely a memory leak in extract_fix, which allocates a new double every time this function is called until the memory is full after about 30 million timesteps. This feature is indeed documented in library.cpp, which I didn't check until now... Do you know whether it'll be possible to free up this memory directly from my Python script, or will I have to edit the source code? I have very limited experience regarding memory management, so sorry about the stupid question... 

Joakim

**Comment by joakimstenhammar** [comment]
Edit: I solved the issue in a quick-and-dirty way by the following change in extract_def in lammps.py:

    if type == 1:
      self.lib.lammps_extract_fix.restype = POINTER(c_double)
      ptr = self.lib.lammps_extract_fix(self.lmp,id,style,type,i,j)
#    return ptr
      result = ptr[0]
      self.lib.lammps_free(ptr)
      return result

Since I only need the x-component of the force (and the other array elements anyway seem to contain mostly rubbish), this should be fine for my purposes. 

Joakim

**Comment by akohlmey** [comment]
yeah, that is definitely a bug. and it needs to be fixed. it has steve p.'s "i'll do it in a smart way, so i don't have to write the same code n times" handwriting all over it. it looks like in this case, he was trying to be too smart. I think the following code should do it right. The important point is that for global data, regardless of vector or array, always only one datum is returned and not the whole vector or array.
```python
  def extract_fix(self,id,style,type,i=0,j=0):
    if style == 0:
      self.lib.lammps_extract_fix.restype = POINTER(c_double)
      ptr = self.lib.lammps_extract_fix(self.lmp,id,style,type,i,j)
      result = ptr[0]
      self.lib.lammps_free(ptr)
      return result
    elif (style == 1) || (style == 2):
      if type == 1:
        self.lib.lammps_extract_fix.restype = POINTER(c_double)
      elif type == 2:
        self.lib.lammps_extract_fix.restype = POINTER(POINTER(c_double))
      else:
        return None
      ptr = self.lib.lammps_extract_fix(self.lmp,id,style,type,i,j)
      return ptr
    else:
      return None
```

with this change in the library, your example code also needs to be changed (as a bonus, you can actually access the other data now).
```python
pres = presstart                      # Loop over different external pressures
for ipres in xrange (0,npres):
    for istep in xrange (0,nstep):           # Run simulation
        insert_wall(lmp,pos)                 # Implement mobile wall in correct position
        integrate_particles(lmp)             # Update particle positions
        wfx = lmp.extract_fix("w1",0,1,0)     # Calculate force on wall 
        wfy = lmp.extract_fix("w1",0,1,1)     # Calculate force on wall 
        wfz = lmp.extract_fix("w1",0,1,2)     # Calculate force on wall 
        pos += integrate_wall(wfx,pres)    # Update wall position
        if(me == 0): print istep, pres, pos, wfx, wfy, wfz
    pres += dP
```

**Comment by akohlmey** [comment]
corrected for LAMMPS-ICMS in commits a7c5dfeefe91912cc09f1806ec1d7a385598b8a1 and 328f0070fe426e3a0be204217124f8140ddb1072

**Comment by joakimstenhammar** [comment]
This seems to work for my test case (after replacing "||" with "|" in 
the elif statement)! However, I still get garbage for wfy and wfz, which 
I assume is because fix wall actually only calculates the normal force 
(i.e., fwx). But I think there should still be an energy stored in the 
vector as well, which I'm also not able to access. Not that I need it, 
but it'd be good to check the workings of the code! I've read the 
documentation several times, but to be honest I find it rather cryptic:

"This fix computes a global scalar energy and a global vector of forces, 
which can be accessed by various output commands 
<http://lammps.sandia.gov/doc/Section_howto.html#howto-15>. Note that 
the scalar energy is the sum of interactions with all defined walls. If 
you want the energy on a per-wall basis, you need to use multiple fix 
wall commands. The length of the vector is equal to the number of walls 
defined by the fix. Each vector value is the normal force on a specific 
wall. Note that an outward force on a wall will be a negative value for 
/lo/ walls and a positive value for /hi/ walls. The scalar and vector 
values calculated by this fix are “extensive”."

In fix_wall_lj126.cpp, it looks like the energy is stored in element [0] 
and fwx in element [1], but I'm only getting one sensible datum out of 
the fix, which I hope/think is the force... Any explanation for this?

Joakim

**Comment by akohlmey** [comment]
correct. i misread the code.
