### ISSUE TITLE
[BUG] More compile errors

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#1602]
**Summary**

I keep getting random compile errors:

```
./info.cpp: In member function 'void LAMMPS_NS::Info::command(int, char**)':
../info.cpp:357:18: error: 'MPI_MAX_LIBRARY_VERSION_STRING'' was not declared in this scope
     char version[MPI_MAX_LIBRARY_VERSION_STRING];
                  ^
../info.cpp:360:29: error: 'version' was not declared in this scope
     MPI_Get_library_version(version,&len);
                             ^
../info.cpp:360:41: error: 'MPI_Get_library_version' was not declared in this scope
     MPI_Get_library_version(version,&len);
                                         ^
make[1]: *** [info.o] Error 1
```

```

../error.cpp(76): error: pointer to incomplete class type is not allowed

../error.cpp(103): error: pointer to incomplete class type is not allowed

../error.cpp(156): error: pointer to incomplete class type is not allowed

../error.cpp(208): error: pointer to incomplete class type is not allowed

```
**LAMMPS Version and Platform**

Latest master, packages installed: KOKOKS, SNAP, MISC

**Comment by stanmoore1** [comment]
The MPI error is with MPICH2, it doesn't seem to define that variable. The other error is when I used -DLAMMPS_EXCEPTIONS and need to add `#include "update.h"`.

**Comment by akohlmey** [comment]
> The MPI error is with MPICH2, it doesn't seem to define that variable.

the exact same code construct is used in `src/KOKKOS/kokkos.cpp` lines 214 and 215.
if we have to correct `src/info.cpp` for this, we have to update the KOKKOS code, too. i'll be submitting a PR for this later today.

> The other error is when I used -DLAMMPS_EXCEPTIONS, need to add `#include "update.h"` to error.cpp.

yup.
