### ISSUE TITLE
[BUG] Parenthesis missing

### ISSUE THREAD

**Issue by ag949** [lammps/lammps#1609]
There is a parenthesis missing in the line 242 of kokkos.cpp
**LAMMPS Version and Platform**
LAMMPS (31 Jul 2019) against CUDA 10.0+mvapich2+gcc-7.1.0

**Comment by akohlmey** [comment]
@ag949 thanks for reporting. this should be fixed with commit f61cd68ca47aff365b76248d95e816b8b3aac687 and available in the next LAMMPS patch.
