### ISSUE TITLE
[BUG] Compilation error when building MPI version

### ISSUE THREAD

**Issue by alxvov** [lammps/lammps#1629]
**Summary**

When I try to compile the latest stable version of LAMMPS with MPI, I get this error message:

![error_msg](https://user-images.githubusercontent.com/52166105/62945972-4f6e0100-bdcf-11e9-8105-1a52e24fd86b.png)

However, I do not get this error message when I compile the patch_19Jul2019

**LAMMPS Version and Platform**

Latest stable version of LAMMPS (stable_7Aug2019) with Intel compiler 2017 on CentOS Linux 7 (Core).

**Steps to Reproduce**

`make yes-manybody
make yes-SPIN
make serial
make mpi`

**Comment by akohlmey** [comment]
please try deleting the line `#include <mpi.h>` from the file read_dump.h and let us know if that avoids the compilation problem.

**Comment by alxvov** [comment]
Yes, it avoids the compilation problem. Thank you.
