### ISSUE TITLE
Packages for LAMMPS stable release 07 Aug 2019

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1636]
For @junghans 

- [ ] OpenSuse: https://build.opensuse.org/request/show/724135
- [ ] Fedora
  - [x] Rawhide (F32): https://bodhi.fedoraproject.org/updates/FEDORA-2019-063db817b3
  - [x] Fedora 31: https://koji.fedoraproject.org/koji/buildinfo?buildID=1357282
  - [ ] Fedora 30: https://bodhi.fedoraproject.org/updates/FEDORA-2019-33ebabf820
  - [ ] Fedora 29: https://bodhi.fedoraproject.org/updates/FEDORA-2019-3db6bbd805
  - [x] Fedora 28 - EOL'ed on 2019-05-28, not possible anymore
  - [ ] CentOS 7: need to wait for kim-api-2.1.3 (see https://github.com/openkim/kim-api/issues/33)
- [x] Gentoo: https://github.com/gentoo/gentoo/commit/16bfde13bae2672faa61b818d4b951024d738f1e
- [x] Spack: https://github.com/spack/spack/pull/12424

For @gladk
- [ ] Debian package

For @akohlmey 
- [x] Windows installer packages (https://rpm.lammps.org/windows/)

For @rbberger 
- [x] Docker(https://hub.docker.com/r/lammps/lammps/tags)

**Comment by akohlmey** [comment]
we are preparing for the next stable release in about a month, so this is no longer relevant.
