### ISSUE TITLE
adding USER-3SPN2

### ISSUE THREAD

**Issue by fonzg1** [lammps/lammps#1639]
In future releases of lammps would be possible if the USER-3SPN2 package be included in lammps to be configured and build using cmake?

**Comment by akohlmey** [comment]
> In future releases of lammps would be possible if the USER-3SPN2 package be included in lammps to be configured and build using cmake?

that depends on the author(s) of that package to submit it as a pull request for inclusion into the distribution and if the code meets the requirements for inclusion.

**Comment by akohlmey** [comment]
closed due to inactivity
