### ISSUE TITLE
make ps gives many errors/warnings on package USER-OMP

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#164]
This has been here a while. 
If i in src/ do
`make yes-user-omp`
`make ps`

I get a list of all missing USER-OMP files that are in packages not included. It is communicated as if it is an error, but it's not. It looks like this:

Installed  NO: package ASPHERE
Installed  NO: package BODY
Installed  NO: package CLASS2
Installed  NO: package COLLOID
Installed  NO: package COMPRESS
Installed  NO: package CORESHELL
Installed  NO: package DIPOLE
Installed  NO: package GPU
Installed  NO: package GRANULAR
Installed  NO: package KIM
Installed  NO: package KOKKOS
Installed  NO: package KSPACE
Installed  NO: package MANYBODY
Installed  NO: package MC
Installed  NO: package MEAM
Installed  NO: package MISC
Installed  NO: package MOLECULE
Installed  NO: package MPIIO
Installed  NO: package OPT
Installed  NO: package PERI
Installed  NO: package POEMS
Installed  NO: package PYTHON
Installed  NO: package QEQ
Installed  NO: package REPLICA
Installed  NO: package RIGID
Installed  NO: package SHOCK
Installed  NO: package SNAP
Installed  NO: package SRD
Installed  NO: package VORONOI

Installed  NO: package USER-ATC
Installed  NO: package USER-AWPMD
Installed  NO: package USER-CG-CMM
Installed  NO: package USER-COLVARS
Installed  NO: package USER-DIFFRACTION
Installed  NO: package USER-DPD
Installed  NO: package USER-DRUDE
Installed  NO: package USER-EFF
Installed  NO: package USER-FEP
Installed  NO: package USER-H5MD
Installed  NO: package USER-HADRESS
Installed  NO: package USER-INTEL
Installed  NO: package USER-LB
Installed  NO: package USER-MANIFOLD
Installed  NO: package USER-MGPT
Installed  NO: package USER-MISC
Installed  NO: package USER-MOLFILE
Installed YES: package USER-OMP
  src/angle_charmm_omp.cpp does not exist
  src/angle_class2_omp.cpp does not exist
  src/angle_cosine_delta_omp.cpp does not exist
  src/angle_cosine_omp.cpp does not exist
  src/angle_cosine_periodic_omp.cpp does not exist
  src/angle_cosine_shift_exp_omp.cpp does not exist
  src/angle_cosine_shift_omp.cpp does not exist
... and so on.

**Comment by akohlmey** [comment]
Please make a suggestion, that will solve this reliably **and** does not make the <package>/Install.sh files needlessly complex and difficult to maintain. Neither Steve nor me had a viable idea so far, and we've accepted, that the benefit is not worth the effort.

**Comment by akohlmey** [comment]
BTW: it is an issue for all packages with dependencies, not just USER-OMP.

**Comment by andeplane** [comment]
Yeah I figured it was that. Give me some time, but I guess it isn't easy...

**Comment by akohlmey** [comment]
Any progress? or should we close this issue?

**Comment by akohlmey** [comment]
@andeplane last call. If there is no response or update for this issue, i'll close it.

**Comment by andeplane** [comment]
I suggest closing it :)
