### ISSUE TITLE
[BUG]  Segfaults with balance command and KOKKOS

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#1655]
**Summary**

Running balance examples causes segfaults when running with KOKKOS and CUDA.

**LAMMPS Version and Platform**

master

**Expected Behavior**

An error message due to some neighbor list requirement or a successfully completed simulation.

**Actual Behavior**

Segmentation faults, e.g. in `imbalance_neigh.cpp:80` due to garbage in the neighbor list

**Steps to Reproduce**
```
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=$PWD/../lib/kokkos/bin/nvcc_wrapper  -D PKG_KOKKOS=on -DKOKKOS_ENABLE_CUDA=on -DKOKKOS_ARCH=Volta70 ../cmake
make

cd ../examples/balance/
# serial ok
../../build/lmp -in in.balance.clock.static 
# kokkos crashes
../../build/lmp -in in.balance.neigh.static -k on g 1 -sf kk -pk kokkos newton on neigh half
```

**Further Information, Files, and Links**

CI reports:  https://ci.lammps.org/job/lammps/job/master/job/cmake/job/cmake-testing-kokkos-cuda/113/testReport/

**Comment by akohlmey** [comment]
@rbberger is this still an issue?
