### ISSUE TITLE
[BUG] _Fix_ehex_singularity

### ISSUE THREAD

**Issue by Adrian-Diaz** [lammps/lammps#1656]
**Summary**

The coordinate correction in the rescale function of fix ehex can alter atoms by massive displacements (e30 etc.) when the computed rotational kinetic energy is near zero for the reservoir group. 

**LAMMPS Version and Platform**

August 7 2019 version running on the UFRC supercomputer with intel/2018 and openmpi/3.1.0.

**Expected Behavior**

atoms not exploding into infinity

**Actual Behavior**

large atom deformations; first noticed by debugging a deadlock in a remap function that was the result of a while loop slaving away for potentially e26 iterations.

**Steps to Reproduce**

run the attached input script with the attached model using virtually any number of tasks (works with 1).

**Further Information, Files, and Links**

[Cu_heat_model.txt](https://github.com/lammps/lammps/files/3561299/Cu_heat_model.txt)

[in_ehex.txt](https://github.com/lammps/lammps/files/3561298/in_ehex.txt)

**Comment by akohlmey** [comment]
@Adrian-Diaz have you tried contacting the author of fix ehex?

**Comment by Adrian-Diaz** [comment]
> @Adrian-Diaz have you tried contacting the author of fix ehex?

I have not.
