### ISSUE TITLE
[Feature Request] dihedral_style harmonic/kk (Kokkos implementation)

### ISSUE THREAD

**Issue by streeve** [lammps/lammps#1665]
**Summary**

Kokkos version of harmonic dihedrals

**Detailed Description**

For a simulation with DREIDING it is common to use harmonic bonds/angles/dihedrals/impropers, where all but dihedrals have a current Kokkos implementation. As I understand from @stanmoore1 this is not a significant effort

**Comment by jewettaij** [comment]
Hi Streeve
Virtually all of the current dihedral styles can be used for your purpose, including dihedral_style [opls](https://lammps.sandia.gov/doc/dihedral_opls.html#dihedral-style-opls-kk-command), [charmm](https://lammps.sandia.gov/doc/dihedral_charmm.html#dihedral-style-charmm-kk-command), and [class2](https://lammps.sandia.gov/doc/dihedral_class2.html#dihedral-style-class2-kk-command)
(all of which have KOKKOS versions).  Why not use one of these styles?

*(If you are going to request a new kokkos dihedral style, why not pick one with much more general capabilities, such as:
diihedral_style [fourier](https://lammps.sandia.gov/doc/dihedral_fourier.html), [spherical](https://lammps.sandia.gov/doc/dihedral_spherical.html), or [table](https://lammps.sandia.gov/doc/dihedral_table.html)?
Disclaimer: I wrote several of these styles, so I admit that my response is somewhat self-serving.)*

**Comment by jewettaij** [comment]
*(Incidentally, if you know of a public repository somewhere containing a list of DRIEDING parameters and their context, please let me know.  Bill Goddard told me the parameters are normally generated by some in-house code from his group.  I'm wondering what people outside his group do.)*

**Comment by stanmoore1** [comment]
@streeve I ported `dihedral_style harmonic` to Kokkos, see #1669. However, one remaining issues is that there is none of the DRIEDING pair_styles have been ported to Kokkos, so that will spawn some host <-> device data movement as well.

**Comment by streeve** [comment]
Thanks @stanmoore1. We've never used the `hbond/dreiding` styles, just standard LJ, Morse, or Buckingham together with bonds, angles, etc.

@jewettaij, it's fair that I made this request to avoid the work of self-conversion to the other existing styles with Kokkos versions. And to be honest, I wasn't aware of those more general styles since the more specific style has always been available. 

I agree that a full set of DRIEDING parameters would be great; the only thing I'm aware of is this (admittedly closed-source) tool for automatic typing from a group I previously worked with: https://nanohub.org/resources/struc2lammpsdf

**Comment by jewettaij** [comment]
Cool.  Thanks for telling me about struc2lammpsdf.  Perhaps I can persuade someone to open-source this useful tool.
If anyone wants help getting these newer dihedral styles into KOKKOS, please let me know.
