### ISSUE TITLE
[Feature Request] Add Units specifier to dump files

### ISSUE THREAD

**Issue by JensWehner** [lammps/lammps#1671]
**Summary**

Add an `ITEM` to the LAMMPS dump files, which output the unit system (e.g. `real`,`metal`,..) is used. 

**Detailed Description**

For postprocessing software of LAMMPS trajectories it can be very hard to find out, which units were used in a simulation run. This feature would remove this ambiguity. 
For the LAMMPS dump files a simple additional ITEM
`ITEM UNITS: REAL` would suffice. 

I do not know how other LAMMPS output formats are handled, but a specifier to those would also be helpful. 

Codes which to my knowledge suffer from this problem are [OVITO](https://www.ovito.org/)
[VOTCA](https://github.com/votca/votca) and [MDAnalysis](https://www.mdanalysis.org/docs/documentation_pages/coordinates/LAMMPS.html)

**Comment by akohlmey** [comment]
@sjplimp what do you think of this suggestion? It is easy enough to implement (see PR #1672)

**Comment by mkanski** [comment]
Would it be possible to also add something like `ITEM: TIME` with the simulation time? That would be useful for simulations with variable timestep.

**Comment by akohlmey** [comment]
> Would it be possible to also add something like `ITEM: TIME` with the simulation time? That would be useful for simulations with variable timestep.

could be done in a similar fashion as with PR #1672. but better to have that one merged and then submit a new PR with the additional change.
