### ISSUE TITLE
[BUG] GPU Memory Leak

### ISSUE THREAD

**Issue by M-S-Jacobs2727** [lammps/lammps#1678]
**Summary**

Initializing a GPU repeatedly (as in the case of looping over a "run" command) results in a memory leak, leading to the OS terminating the simulation.

**LAMMPS Version and Platform**

LAMMPS versions 7Aug2019 and 16Mar18 were tested on a CentOS 7 cluster. The compute nodes have 2x12-core, 24-thread Intel Xeon processors, 64GB of RAM, and 4xGTX Titan X GPUs.

**Expected Behavior**

LAMMPS should run with stable memory usage.

**Actual Behavior**

LAMMPS memory usage increases to the maximum system memory, at which point the OS kills it.

**Steps to Reproduce**

* Enable GPU acceleration (I've only tested with pair_style lj/cut/gpu, lj/cut/coul/long/gpu, and kspace_style pppm/gpu).
* Create a loop with a run command inside.
* Run the simulation and watch system or process memory.

**Further Information, Files, and Links**

Our testing shows that using the "pre no" keyword with the "run" command eliminates the leak, suggesting that it happens during initialization. Similarly, using a single, long "run" command does not produce the leak.

**Comment by anderscognite** [comment]
Can you also put a small script that reproduces the problem?

**Comment by TheRubikMaster** [comment]
[Here](https://github.com/lammps/lammps/files/3616698/in.melt.txt) is a simple input file. I modified the melt example to loop over a 25-timestep run.

**Comment by ndtrung81** [comment]
Hi, thanks for reporting the issue and for the tests with "pre no".

Can you try rebuild LAMMPS with the attached source files copied to src/?
If they can resolve the memory leak on the device as you observed for the
example input, the bugfixes are possible for other styles, but it will take
sometime for me to propagate them across those pair styles.

Best,
-Trung

**Comment by TheRubikMaster** [comment]
Files were not attached...

**Comment by andeplane** [comment]
If you reply by email @ndtrung81, the attached files do not appear on GitHub (didn't find them in the email either).

**Comment by ndtrung81** [comment]
Let's try this zip file:

[ljcutgpu.zip](https://github.com/lammps/lammps/files/3617261/ljcutgpu.zip)

**Comment by TheRubikMaster** [comment]
![Memory_Test](https://user-images.githubusercontent.com/42037940/65056233-825f6380-d93e-11e9-8e4c-82bb226c26b0.png)
The patch works well! And there is no slowdown that I can tell (based on the code, there might even be a speedup, but I didn't test for that). Thank you so much @ndtrung81 !!!

**Comment by TheRubikMaster** [comment]
I have a couple of questions about implementing this patch elsewhere. So I can put this into lj/cut/coul/long/gpu in a similar fashion just fine, but I'm a bit concerned about pppm/gpu. What should be the corresponding fix for that?

**Comment by ndtrung81** [comment]
@TheRubikMaster glad to hear that it worked and that you can make similar changes to lj/cut/coul/long/gpu. Did you experiment with the existing pppm/gpu, to see if the memory leak persists?

**Comment by TheRubikMaster** [comment]
I did. 
[pppm_gpu.zip](https://github.com/lammps/lammps/files/3626741/pppm_gpu.zip)

I tried this, as well as not including the calls to create_3d_offset in the if statement, but it gave me a segfault both times. I'm afraid my knowledge here is pretty limited.

I also left pppm/gpu alone to see if the memory leak persists with just the changes to lj/cut/coul/long/gpu, and it does, albeit much more slowly.

**Comment by TheRubikMaster** [comment]
[test2.zip](https://github.com/lammps/lammps/files/3626785/test2.zip)

Here is a test file (in.gen) and the output (out2.txt) when I try to run it with the edited pppm/gpu files.

**Comment by M-S-Jacobs2727** [comment]
What I have learned so far:

I can get pppm/gpu to run without a memory leak by encapsulating everything inside of init in the if(!device_allocated) clause. However, I want to change the box size between runs later, and this will not recalculate the mesh grid, thus invalidating my results (please confirm?). The more correct way would be to properly deallocate whatever is building up in memory, though I have no idea how to check that.

I think the pair_styles shouldn't cause an issue with regards to that, because box size won't affect the pair_style (?). The only thing that should affect pair_style parameters should be the pair_style itself, which will be deallocated and reinitialized correctly if called between runs (?).

Please correct me if I'm wrong in anything above, and please offer advice for pppm/gpu.

**Comment by ndtrung81** [comment]
@M-S-Jacobs2727 The existing pppm/gpu is supposed to work correctly if the number of mesh grid points in every dimension stays the same during the run. The box sizes may change, for example, using fix npt or fix deform, and the existing code (in both pppm and pppm/gpu) correctly maps the particle charges on the grid. However, if the box changes dramatically during the run, the original mesh would lead to poor accuracy in the electrostatic forces from the grid, and you may lose atoms, which happens to both pppm and pppm/gpu.

What you did is effectively enforce "pre no" inside pppm/gpu. Let's try the attached source code for pppm/gpu, where I found and fixed a small memory leak with the allocation of the arrays density_brick_gpu and vd_brick in pppm/gpu. Let me know if it resolves the slowly growing memory leak in your runs.

[pppmgpu.zip](https://github.com/lammps/lammps/files/3653090/pppmgpu.zip)

**Comment by M-S-Jacobs2727** [comment]
Thanks for the advice!

The patch did not help, unfortunately. I tested pppm/gpu both with and without the patch, and the results are the same. The memory leaks at almost the same speed. I tested with pppm (no gpu), just to be sure, and the memory is stable.

Thank you so much for your time! I hope we can get this resolved.

![Memtest2](https://user-images.githubusercontent.com/42037940/65621473-ce8b5300-df91-11e9-98e4-b7dd3df89545.png)
[test_files.zip](https://github.com/lammps/lammps/files/3653723/test_files.zip)

**Comment by M-S-Jacobs2727** [comment]
Please disregard that last comment! Somehow I didn't correctly copy the patch before I rebuilt LAMMPS... retesting now...

**Comment by M-S-Jacobs2727** [comment]
I ran with the patch correctly installed, and the memory still leaks. My groupmate and I also noticed the GPU memory increasing (using nvidia-smi). I edited the code to print during pppm/gpu initialization (separate from pppm), and during pppm/gpu destruction. When I ran it, the initialization message printed, but the destructor message did not. Is this expected? Or is the destructor not being called between runs?

[pppm_gpu_verbose.zip](https://github.com/lammps/lammps/files/3654217/pppm_gpu_verbose.zip)

![Screenshot from 2019-09-25 14-15-24](https://user-images.githubusercontent.com/42037940/65628207-fd5bf600-df9e-11e9-81e6-6d3ec46d5304.png)

**Comment by ndtrung81** [comment]
Thanks for running the tests. Can you also share the file ionPair.txt so that I can rerun your input deck on my side? Also, which version of the CUDA toolkit do you use to build the GPU package and run LAMMPS with?

**Comment by M-S-Jacobs2727** [comment]
[ionPair.txt](https://github.com/lammps/lammps/files/3659430/ionPair.txt)

I'm using CUDA 10.0, sm_52 architecture

**Comment by ndtrung81** [comment]
Thanks. Can you try the attached source files for pppm/gpu? It seems to resolve the issue on my side.

[pppmgpu2.zip](https://github.com/lammps/lammps/files/3666369/pppmgpu2.zip)

**Comment by M-S-Jacobs2727** [comment]
The code works wonderfully for NVT! The GPU memory doesn't even fluctuate, and I think it runs faster. 

However, when I tried NPT, the second the grid size changes, the code hangs, so I couldn't test the memory in the case of `old_nzlo_out != nzlo_out`. I attached the input, molecule and output files.

[test_20190930.zip](https://github.com/lammps/lammps/files/3671746/test_20190930.zip)

**Comment by ndtrung81** [comment]
Sorry but it turns out that my workarounds so far for lj/cut/gpu, lj/cut/coul/long/gpu and pppm/gpu didn't actually resolve the issue with initialization. The original implementation is already designed to handle multiple runs with multiple init calls, but for some unknown reason to me, the host memory gets increased after each init call from the GPU library. valgrind does not show obvious leaks rather than those from the CUDA libraries (like with cuInit), and the OpenCL build also shows an increase in host memory consumption.

It will take me more time to resolve this issue than expected. Anyone with any idea or suggestion is more than welcome!

**Comment by ndtrung81** [comment]
@M-S-Jacobs2727 can you try the changes in #1735? First, you rebuild the GPU library, then go to src/, do "make package-update" if you have the modified versions of the /gpu pair styles in src/. This is because the changes here do not involve those in the zip files previously attached in this thread.

**Comment by M-S-Jacobs2727** [comment]
Thank you so much! Works great with everything I've thrown at it. Can't wait to see it committed!
