### ISSUE TITLE
[Feature Request] external callback fix supporting other arrays

### ISSUE THREAD

**Issue by llaniewski** [lammps/lammps#1694]
## Summary

I propose to add support for the `external pf/callback` fix type to be able to read and influence arrays other than `x` and `f`.

## Detailed Description

I am writing a coupling of a CFD code ([TCLB](https://github.com/CFD-GO/TCLB.git)) with LAMMPS. The general structure of the LAMMPS code (as shared library) and `pf/callback` fix is perfect for my purposes. But the callback exposes only *positions* and allows only the *forces* to be modified. I would need *radius*, *velocity* and *angular velocity* exposed, and would need to write in external *moment of force*. But maybe it is a good opportunity to add support for something more general.

## Development
**I am happy to modify the code myself**, make all appropriate checks, keep it backwards compatible, and make a Pull Request. I would like to know what you (the authors) think is the best lane to pursue this idea, so my development will be in accordance with the general design of the code.

### Proposed solution
The way I see it now, is that I would add a new function `set_callback_atom`. Which would add a different type of callbacks, and select the size of the persistent storage space (currently `fexternal`). There would be two callbacks, one for *force calculation* and the other for *force application*. One would be called on every `Ncall` iteration, and another on every `Napply` iteration. Both of them would be supplied with the `atom` structure, and the persistent storage array (that is `fexternal` in case of the normal callbacks).

This would not change the existing interface, but would allow for a more general couplings. It would also open the road for the couplings to influence the particles in different ways. Not only apply *moment of force*, but for example modify mass and radius (eg. melting), or other things.

### Notes
Or maybe there is another way for such coupling that is preferred.

**Comment by akohlmey** [comment]
@llaniewski is this still relevant?
We just recently improved and documented the C-library interface for connecting with fix external.
Note, that it is possible to access much more data from the LAMMPS class instance through the ``ptr`` argument to the callback function. This would be the ``handle`` argument for any calls to library interface functions like `lammps_extract_atom()`.
