### ISSUE TITLE
pair srp + fix deform triclinic flip yes

### ISSUE THREAD

**Issue by timsirk** [lammps/lammps#17]
Pair srp fails with an error when used with combination of triclinic box + fix deform + flip yes + large strain. This happens due to the order that fix deform and fix srp occur in pre_exchange step. Currently fix srp is automatically invoked and runs ~last in pre_exchange. This patch allows the user to (optionally) define the order of fix srp in the input script. The doc page is also updated.

[patch.26Oct15.txt](https://github.com/lammps/lammps/files/33445/patch.26Oct15.txt)

**Comment by akohlmey** [comment]
Been thinking about this for a bit, and not very happy with the proposed change. It makes the interface quite inconsistent. Either one should always have to define fix srp or it should always be automatically defined. As for the latter, i tried moving the fix creation to the constructor and unlike what is indicated by the comments in the source, it seems to be working fine, including restarting.

**Comment by akohlmey** [comment]
Please try out the code in commit 7bf781c1f6e32e807c4bbe7ead3d7b5626809a3a instead.

**Comment by akohlmey** [comment]
Tim,
any updates on this issue? If not, i'll close it as resolved.

**Comment by timsirk** [comment]
one more day please, I haven't been able to test it yet.

**Comment by timsirk** [comment]
Just tested - this change (by itself) only allows restarts to be read if they were written between runs, and not during a run. The core issue is that fix_srp init tries to check if the user reserved an extra unused atom type for the bond particles. This check is fine when reading a datafile or end-of-run restart file, because those only contain the true number of atoms, and not these exotic bond particles. however during-the-run restart files have the bond particle coordinates stored as per-atom data. the check uses the fix->restart_reset flag to decide if the user forgot the extra atom type, or if its legitimate coordinates from a during-the-run restart. 

It looks like fix->restart_reset isn't set during the check if add_fix() is called in the constructor. So in the current form the check will always fail for during-the-run restarts. I do agree it would be a better solution to add the fix in constructor if possible.

**Comment by akohlmey** [comment]
Wouldn't it be simpler and cleaner to just generally delete all atoms of type bptype at the beginning of a run and then create the mid-bond particles for that type? That would make the whole setup process independent from what is stored in a restart or data file (or trajectory file). There could be a warning that says "Deleting X atoms of type Y. Replacing with Z mid-bond particles."  If somebody points bptype at a type with atoms to be kept is is a user error. I always dislike to make behavior of a program dependent on a particular process.

I will look at how this could be done.

**Comment by akohlmey** [comment]
Oh, and i should probably also add a check to verify, if the fix actually is the first in the list, that is run at the required stage.

**Comment by timsirk** [comment]
Yes, deleting / reinserting the bond particles at the beginning of the run should work for any case. That seems robust.

**Comment by timsirk** [comment]
Thanks for looking into this. The warning seems sufficient. And the hard stop checkpoint more trouble than it was worth.

**Comment by akohlmey** [comment]
Tim, please check out the updated code for fix/pair_srp.cpp/h below. This allows to set bptype in the srp pair style directly, and deletes any excess particles particles of bptype before creating new ones. it can start from mid-run and between run restarts and data files converted from either. so everything seems to be working, but the energies are off. i must be missing something, but i am running out of ideas.

https://www.dropbox.com/s/kw79d5rdvyydeno/lammps-srp-refactor.tar.gz?dl=0

**Comment by timsirk** [comment]
Pleas have a look at this patch. Your update was very close to working. The strategy for restarts is good and works well. The energy mismatch was due to the union ubuf in fix_srp. It wasn't giving a readable value. I don't understand aliasing well enough to really get to the bottom of it. The update uses a static cast. 

[patch.srp.txt](https://github.com/lammps/lammps/files/55935/patch.srp.txt)

**Comment by akohlmey** [comment]
thanks a lot. using a cast is fine for the time being, i'll just insert a (runtime) warning noting that pair srp is not fully compatible with 64-bit tags. if that specific part of the code is the problem, i can look into fixing it at a later point. the changes i made were the way they are "supposed to be(tm)", but something must have been overlooked.

**Comment by akohlmey** [comment]
the combined changes are now merged into LAMMPS-ICMS in commit 8446b8cc1b31c81f6ce3e6a4b8284a9d3d396643 and sent to steve for inclusion into upstream. i'll open a new ticket for making srp fully compatible with 64-bit tags or adding a warning.
