### ISSUE TITLE
[BUG]  Gay-Berne pair style do not conserve energy with negative exponents

### ISSUE THREAD

**Issue by matteoeghirotta** [lammps/lammps#1702]
**Summary**

pair_style gayberne does not conserve the energy in NVE simulations  if one or both the exponents mu and upsilon are negative.

**LAMMPS Version and Platform**

The problem was detected with both 11 Aug 2017 and 5 Jun 2019, running on debian 9 and ubuntu 18.04 Linux, x86_64 architecture.

**Expected Behavior**

Running a simulation with biaxial ellipsoidal particles interacting only through pair_style gayberne potential with fix NVE should conserve energy, given a sufficiently small timestep to integrate equations of motion.  

**Actual Behavior**

Running the same NVE simulation with one or both negative exponents results in a steady positive energy drift, while using only positive exponents energy is conserved.

**Steps to Reproduce**

I attach input files for both positive and negative exponents to quickly reproduce the issue. Please notice the energy drift in the thermo log, in particular the rotational energy in the 2nd column. 

**Further Information, Files, and Links**

[gb_bug.zip](https://github.com/lammps/lammps/files/3680936/gb_bug.zip)

**Comment by Pakketeretet2** [comment]
I can confirm with LAMMPS from 19 September 2019. I am not at all familair with Gay Berne potentials; do negative exponents make sense? If so, does it make the interaction very long-ranged? Because if the latter is the case it could be due to the pair cut-off not being appropriate for this potential for negative exponents.

**Comment by matteoeghirotta** [comment]
Negative exponents are present in literature, basically they change the relative weights of the well depth for non-orthogonal configurations, e.g. those know as tee and cross. We choose a negative exponent because it did fit better atomistic interaction potemtial curves. We did check all principal orthogonal interaction curves, and we can say they seem perfectly reasonable. No effect on the long range character of the potential, since the exponents just raise angular terms. 
That said, we couldn't check that for this exponentials choice some discontinuities in the potenial landscape will arise.

**Comment by jewettaij** [comment]
I'm not familiar enough with Gay-Berne to be certain whether this is actually a bug or a problem with the choice of parameters used.  As Matteo (the poster) suggested, perhaps negative μ,ν exponent parameters in the example could cause discontinuities (or singularities in the potential).  If so, this could easily lead to energy drift (or crashes).  A casual glance at equations 8 and 10 from [this paper](http://claudiozannoni.fci.unibo.it/bfz_gb_bxim_cpl95.pdf) makes me suspect that this is the case.  

Boring details:  As rij in equation 10 approaches 0 (as rij→￼0), I would expect ε'→0, and hence ε(w1,w2,r12)→∞ (for negative μ in eq 10).  Is my thinking correct?  (If so, perhaps we should not call this a bug.)

Matteo, are you sure that negative μ exponents are common in the literature?  Would it be possible to use strictly positive exponents in most cases?

That said, I can't figure out how negative ν exponent would cause a singularity...

-Andrew

**Comment by jewettaij** [comment]
> I'm not familiar enough with Gay-Berne to be certain whether this is actually a bug or a problem with the choice of parameters used.  As Matteo (the poster) suggested, perhaps negative μ,ν exponent parameters in the example could cause discontinuities (or singularities in the potential).  If so, this could easily lead to energy drift (or crashes). A casual glance at equations 8 and 10 from [this paper](http://claudiozannoni.fci.unibo.it/bfz_gb_bxim_cpl95.pdf) makes me suspect that this is the case.
> 
> #### details:
> As rij in equation 10 approaches 0 (as rij→0), I would expect ε'→0, and hence ε(w1,w2,r12)→∞ (for negative μ in eq 10). Is my thinking correct? (If so, perhaps we should not call this a bug.)

Nevermind.  I left my brain at the door when I wrote this.  (Those rij in equation 10 are unit vectors.  Even so, I suppose it would be disturbing if the pairwise energy did not diverge as rij approaches 0.)    I don't see how any divergence can occur in the energy for finite rij (and negative μ,ν).  Please disregard my previous post.

I apologize for wasting people's time.

> Matteo, are you sure that negative μ exponents are common in the literature? Would it be possible to use strictly positive exponents in most cases?
> 
> That said, I can't figure out how a negative ν exponent would cause a singularity...
> 
> -Andrew

**Comment by matteoeghirotta** [comment]
Unfortunately the Gay-Berne potential does have some "artifacts", like a region behind the repulsive core with energy going to -infinity in some ellipsoidal configurations and indeed I am not sure the energy drift with negative exponents can be ascribed to a bug. I think the safest thing would be to choose only positive exponents, until we understand the problem better, but probably a note on the parameter validity range in the docs is in order.

**Comment by wmbrownIntel** [comment]
Thanks Andrew for pointing me to this ...and giving me a new memory to haunt me :).

This is indeed a bug that goes back to my derivation of the analytic torque and will also affect positive mu!=1.

Matteo, please try one of these (for whatever flavor you use) and let me know: 

[patched_gb.zip](https://github.com/lammps/lammps/files/3747229/patched_gb.zip)

**Comment by jewettaij** [comment]
It's no fun getting bug reports on something you wrote years ago.  Thank you very much for patching this, Michael.
