### ISSUE TITLE
[BUG] examples/gjf fails

### ISSUE THREAD

**Issue by carlos-pereyra** [lammps/lammps#1715]
**Summary**

Within `examples/gjf` the following input file `in.gjf.vfull` does not work, while `in.gjf.vhalf` works.

**LAMMPS Version and Platform**

Last fetch, LAMMPS 19 Sep 2019. Mac OS X.

**Details**

When I run `mpirun -n 8 ./lmp -in in.gjf.vhalf` I get results.

>Total # of neighbors = 18143
Ave neighs/atom = 20.9988
Ave special neighs/atom = 0
Neighbor list builds = 1809
Dangerous builds = 101
Total wall time: 0:00:09

The issue is when I run `mpirun -n 8 ./lmp -in in.gjf.vfull` I get the following error.

>mpirun noticed that process rank 5 with PID 0 on node Carloss-MacBook-Pro exited on signal 11 (Segmentation fault: 11).

**Comment by akohlmey** [comment]
@carlos-pereyra thanks for reporting. It looks like using `fix langevin gjf vfull` also requires setting `tally yes`. You failed to mention, that the vfull example initially fails because of wrong ordering of the fixes.

@charlessievers please have a look at [the changes in this branch in my personal repo](https://github.com/lammps/lammps/compare/master...akohlmey:gjf-vfull-bugfix)
I haven't tracked down the complete logic, but the current documentation seems to imply that `vfull` is the same as `yes` in the previous implementation. But the code we have now doesn't seem to be consistent with that. Am I missing something?

**Comment by charlessievers** [comment]
> @carlos-pereyra thanks for reporting. It looks like using `fix langevin gjf vfull` also requires setting `tally yes`. You failed to mention, that the vfull example initially fails because of wrong ordering of the fixes.

I do use part of tally to obtain the correct GJF algorithm, but I tested it to run without tally through the use of the osflag. It appears some of my osflag placements are missing, I must have missed a commit. Anyways, that is awkward and I apologize.


> @charlessievers please have a look at [the changes in this branch in my personal repo](https://github.com/lammps/lammps/compare/master...akohlmey:gjf-vfull-bugfix)

The changes seem appropriate and will fix the issue, but my plan was to use the osflag. If we plan to enforce tally yes, I will go through and remove excess osflag placements.

> I haven't tracked down the complete logic, but the current documentation seems to imply that `vfull` is the same as `yes` in the previous implementation. But the code we have now doesn't seem to be consistent with that. Am I missing something?

Some of the documentation I was asked to remove described that vfull is different from the old implementation. I had to change the implementation to obtain the correct onsite velocity described in Niels original paper.

**Comment by akohlmey** [comment]
> > @charlessievers please have a look at [the changes in this branch in my personal repo](https://github.com/lammps/lammps/compare/master...akohlmey:gjf-vfull-bugfix)
> 
> The changes seem appropriate and will fix the issue, but my plan was to use the osflag. If we plan to enforce tally yes, I will go through and remove excess osflag placements.

it would be ok with me to have it either way. we just have to make sure, that we have consistent behavior. it should not be that `osflag` implicitly becomes the same as setting `tallyflag`.

> > I haven't tracked down the complete logic, but the current documentation seems to imply that `vfull` is the same as `yes` in the previous implementation. But the code we have now doesn't seem to be consistent with that. Am I missing something?
> 
> Some of the documentation I was asked to remove to have the pr accepted described that vfull is different from the old implementation. I had to change the implementation to obtain the correct onsite velocity described in Niels original paper.

that is information, that should be in the "backward compatibility" section for the release, not in the manual. the manual should simply describe what is implemented. i only recall a notice that the syntax changes, not some of the details of the implementation. those are not yet officially posted, so we can still fix this.

while on the matter of fixing stuff. i noticed several deviation from the LAMMPS style in source code formatting. there is for example:
```
}
else{
```
which should become:
```
} else {
```
and also for `if` and `for` constructs, there should be a blank before the opening curly brace:
```
if (some_condition) {
```

**Comment by carlos-pereyra** [comment]
@akohlmey  and @charlessievers 

Thank you both for fixing this so swiftly. I look forward to fetching the changes.

**Comment by charlessievers** [comment]
> > The changes seem appropriate and will fix the issue, but my plan was to use the osflag. If we plan to enforce tally yes, I will go through and remove excess osflag placements.
> 
> it would be ok with me to have it either way. we just have to make sure, that we have consistent behavior. it should not be that `osflag` implicitly becomes the same as setting `tallyflag`.

I agree `osflag should not implicitly be the same as `tallyflag`. The difference should come into play during the end of step when energy is actually tallied from the virial. If it is fine, I would like vfull to rely on tally set to yes. What is the best way for me to remove `osflag`? Should I wait until you have pulled your changes into master?

> > > I haven't tracked down the complete logic, but the current documentation seems to imply that `vfull` is the same as `yes` in the previous implementation. But the code we have now doesn't seem to be consistent with that. Am I missing something?


> > Some of the documentation I was asked to remove to have the pr accepted described that vfull is different from the old implementation. I had to change the implementation to obtain the correct onsite velocity described in Niels original paper.
> 
> that is information, that should be in the "backward compatibility" section for the release, not in the manual. the manual should simply describe what is implemented. i only recall a notice that the syntax changes, not some of the details of the implementation. those are not yet officially posted, so we can still fix this.

I see, looking back my PR does leave some information about the change up to the imagination. I will be more forward with the backwards compatibility section in the future.

> while on the matter of fixing stuff. i noticed several deviation from the LAMMPS style in source code formatting. there is for example:

Thank you for pointing that out. I appreciate the patience and support you have shown in improving my contributions to the repo.

**Comment by charlessievers** [comment]
> Thank you both for fixing this so swiftly. I look forward to fetching the changes.

@carlos-pereyra thank you for using GJF and helping to improve it! Also, I recommend using vhalf over vfull in almost every circumstance.

**Comment by akohlmey** [comment]
> I agree `osflag should not implicitly be the same as `tallyflag`. The difference should come into play during the end of step when energy is actually tallied from the virial. If it is fine, I would like vfull to rely on tally set to yes. What is the best way for me to remove `osflag`? Should I wait until you have pulled your changes into master?

i currently have no plans to merge those. otherwise i would have already submitted them as a pull request. i merely intended them to be a starting point for a discussion. i would prefer you to make the changes that you intended from the get go, rather than have changes based on my guesses. 

if you want `gjf vfull` depend on `tally yes`, you should add a test, that checks for that requirement and also document this requirement. from then on you can continue as necessary.

**Comment by akohlmey** [comment]
Fixed in #1725
