### ISSUE TITLE
Re-implement MEAM in C++

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#174]
There are several issues with MEAM being based on a Fortran library: inconsistent performance across compilers (much more than C++), inability to use multiple instances, complication in linking.
Thus a re-implementation as a regular C++ manybody class should be beneficial. Since the existing fortran code is well structured and quite readable, it should not require a complete re-implementation from scratch, but mostly some kind of "translation".

**Comment by martok** [comment]
As a heads-up: I'm currently working on this (because I need the pair_style to be instantiable). My current plan is something like this:

- do a literal translation of lib/meam with minimum changes for diff-ability (about 3/4 done)
- reformat to consistent C style
- convert to C++ class in src/MEAM and use that in pair_meam, remove lib/meam

How does that sound to you? Development currently happens in a test repository off-site, but I would be very happy to send the result as a pull request when it's done.

**Comment by akohlmey** [comment]
@martok, this sounds great.
here are a couple thoughts:
- some of the functions are just required for translation (e.g. from 0-based C++ code to 1-based Fortran), so there is potential to remove unneeded copies.
- we generally prefer to keep the older variant around for reference or to help debugging. so it would be preferable, if the new style would be given a new name, say "meam/c" (cf. "reax" vs. "reax/c").

feel free to submit a pull request even before your work is complete. this way you can get help from LAMMPS developers with integrating your changes. see #371, #497, or #501 as examples.

**Comment by martok** [comment]
Good suggestion, I will do that for the actual C++ port.

About indexing: indeed, I plan to get rid of these eventually. For now, I've defined a few shims to use 1-based indexing in C where required and double-translate. It may not be fast, but makes for simpler translation.

I don't use them yet, but are there performance concerns with 2d dynamic arrays as `double **foo`, or do you generally prefer readability over the little that things like `foo[i+w*j]` might give?

**Comment by Pakketeretet2** [comment]
I think (hope) any decent compiler will convert foo[i][j] into foo[i + w*j] into *( foo + i + w*j ). I would be surprised if it makes a difference. 
Inside lammps itself, atom positions are stored as a 1D array of size 3*N x_, and then an array of pointers x is allocated that has x[0] = x_, x[1] = x_ + 3, etc. If that's good enough for lammps, it's good enough for meam, I guess.

**Comment by akohlmey** [comment]
If you maintain the level of readability that the MEAM fortran code has, it'll be fine. That one is done quite well compared to some of the C++ code in LAMMPS. The biggest potential performance killer for MEAM is actually the exp() function. When using gcc/gfortran on 64-bit linux it is horribly slow (compared to intel compilers, that ship with a replacement math library, which doesn't suffer from the idiosyncrasies of the math library in GNU libc).

**Comment by akohlmey** [comment]
@Pakketeretet2 yes, it does make a difference. It can be up to 20%. The reason are the C/C++ aliasing rules. The compiler is not allowed to assume, that the various position entries overlap. The fact, that LAMMPS is using this construct is due to its origin as Fortran code. People wanted to have the C++ code look similar to the Fotran code and Steve (incorrectly) believed that it would be sufficient to have the coordinates stored contiguously. Basically, the compiler must not leave data in registers, but has to refetch when there is an assignment to ANY of those data structures, in fact ANY pointer to a double or int. Fortran does not allow aliasing which is why its compilers can be more aggressive when optimizing (which leads to some funny behavior in Fortran codes, if you pass the same array as two different arguments).

It gets worse, when you want to use vectorization. Any tutorial on vectorization will tell you, that arrays of arrays are bad, arrays of structs better, and structs of (guaranteed to be aligned) arrays best.

If you look at pair style lj/cut/omp or lj/cut/opt, you can see how with some crazy casting can be done to make the compiler do a better job. in USER-OMP, i've tried hard to maintain the readability of the source in the core parts and remain portable. if you look at lj/cut/intel, you'll see how this can be pushed even further for increased vectorization with intel compilers (as it is dearly needed for good performance on Xeon Phi style hardware).

**Comment by Pakketeretet2** [comment]
@akohlmey Interesting, I was not aware of that. It makes sense, thanks for explaining!

**Comment by akohlmey** [comment]
@Pakketeretet2 just made a quick check on an executable compiled with `make mpi` i.e. standard optimization, **no** multi-threading. When running inputs in the bench folder i get:
- in.lj is 10% faster with -sf omp
- in.eam is 8% faster with -sf omp
- in.rhodo is 12% faster with -sf omp
in all of them the double **x pointer in Atom is cast to a struct {double x,y,z;} *x pointer. there are a few other tricks as well and the performance gain is higher when running multiple MPI ranks (in fact, the higher the more contention for the CPU cache exists).

**Comment by martok** [comment]
I hadn't expected that much of a difference. Huh.

Can someone please verify that [this](https://github.com/lammps/lammps/blob/master/lib/meam/meam_dens_final.F#L106) is supposed to use `shpi`? It looks to me as if that should be `shp`, and `shpi` is actually uninitialised at this point?

**Comment by akohlmey** [comment]
indeed. if i read the code right, there is no need for shpi() at all in this subroutine. the error is likely to be small, though, since after the first trip in the loop it will be set. and if one gets lucky, it'll be 0.0 in the first trip.
i'll try to make some tests and update the fortran version accordingly.

**Comment by akohlmey** [comment]
@martok here is my change for this
https://github.com/lammps/lammps/pull/510/commits/0ecdb998856b2ca3d565e3fb0e973f85b52240f0
I've sent you an invitation to become an 'external developer' for the LAMMPS project on github. please accept it, so i can assign this issue to you as indicator you are working on this.
