### ISSUE TITLE
[Feature Request] Ubuntu 19 installation error

### ISSUE THREAD

**Issue by deng-cy** [lammps/lammps#1743]
When I use the command: 
sudo add-apt-repository ppa:gladky-anton/lammps
The terminal said no release. I am assuming LAMMPS does not support Ubuntu 19.

**Comment by akohlmey** [comment]
You are assuming wrong. You cannot expect a personal repository to be
updated the minute a new release hits the net.
You have to either wait or compile lammps from sources yourself.

--
Dr. Axel Kohlmeyer akohlmey@gmail.com http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste, Italy

**Comment by akohlmey** [comment]
Since there has been no follow-up, I am closing this now. It is not really our job to manage requests to personal projects where people generously donate their time to make LAMMPS binaries available.
