### ISSUE TITLE
Implement tabulation and short neighbor list for 3-body terms in manybody potentials

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#175]
Based on the efforts of Anders Hafreager for pair style vashishta, it should be possible to achieve similar significant speedups applying the same changes (tabulation of 2-body term, short neighbor list for 3-body term computations) to other manybody (and some pairwise additive) potentials.
We should also evaluate accuracy vs. performance behavior of linear vs. spline interpolation.

**Comment by stanmoore** [comment]
>>should be possible to achieve similar significant speedups

I'm curious about this, do you have performance numbers for the different optimizations?

**Comment by akohlmey** [comment]
Anders has made some benchmarks. You can also test test pair style vashishta against vashishta/table yourself. ...and you can also look at the code in #178 and #180
I am currently exploring options that will allow to improve accuracy. Anders' simple linear interpolation in rsq is quite inaccurate for small r unless you use a very large number of tabulation points, which results in a significant drop in performance. i've successfully used cubic splines in another project to tabulate logarithms efficiently and at effectively double precision accuracy: https://github.com/akohlmey/fastermath

**Comment by akohlmey** [comment]
Short neighbor lists are now implemented consistently for sw, tersoff, vashishta, vashishta/table and their USER-OMP variants in #246
Consistent (spline) tabulation is still on the TODO list.

**Comment by athomps** [comment]
Axel,

Great! Thanks for doing this.  I am looking forward to seeing those optimizations relected in Stan's benchmarks.

Aidan


--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011
