### ISSUE TITLE
[BUG] special bonds are not treated correctly when pair_style hybrid has two lj/cut/coul/dsf

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1753]
**Summary**

As can be found by following the discussion in a past thread (https://lammps.sandia.gov/threads/msg42574.html), coul/wolf and coul/dsf (and possibly other related pair styles) don’t completely ignore 1-2, 1-3 and 1-4 coulomb interactions, even when special_bonds is set to 0. Unfortunately, it seems that when pair_style hybrid contains multiple coul/dsf, this special case doesn’t get detected, and the neighboring interactions are completely shut off if spacial_bonds is set to zero.

**LAMMPS Version and Platform**

Latest master version.

**Steps to Reproduce**

Run the following script:
```
units real
atom_style full

region box block -30 30 -30 30 -30 30
create_box 2 box bond/types 1 extra/bond/per/atom 2 extra/special/per/atom 2

# settings for plain pair_style
#pair_style lj/cut/coul/dsf 0.2 12
#pair_coeff * * 3 3

# settings for pair_style hybrid
pair_style hybrid lj/cut/coul/dsf 0.2 12 lj/cut/coul/dsf 0.2 12
pair_coeff * * lj/cut/coul/dsf 1 3 3
pair_coeff 2 2 lj/cut/coul/dsf 2 3 3

bond_style harmonic
bond_coeff 1 0 1

special_bonds lj/coul 0 0 0

mass * 100

# molecule with bonds
create_atoms 1 single -1 0 0
create_atoms 1 single  0 0 0
create_atoms 1 single  1 0 0
create_bonds many all all 1 0.9 1.1

# workaround to make special bonds work with pair_style hybrid
#special_bonds coul 1e-100 1e-100 0

set group all charge 1

variable f1 equal fx[1]

thermo_style custom step v_f1

run 0
```

**Expected Behavior**

Even with **special_bonds lj/coul 0 0 0**, the atom forces should not be 0.
> Step v_f1 
>        0    5.6276699

**Actual Behavior**

The atom forces are 0.
> Step v_f1 
>        0            0  

**Further Information, Files, and Links**

This can be somewhat worked around by setting special_bonds to a very small value: **special_bonds coul 1e-100 1e-100 0**.

There is another side effect unrelated to this bug, that the Coulomb self-energy term is double counted, but this doesn’t affect dynamics and is easy to deal on the user side.

**Comment by sjplimp** [comment]
I don't understand what the expected answer is.
You create 3 atoms.  You add 3 bonds, one between
each pair of atoms.  If you have special 1/2, 1/3, 1/4 all zero.
Then I think there should be 0 force and energy, whether you
use hybrid or not?  Is that correct?

Are you saying that is or is not happening?
For no hybrid or for hybrid?

**Comment by donatas-surblys** [comment]
The result in **Expected Behavior** is what I get with **pair_style lj/cut/coul/dsf**, and I would expect to get the same when using pair_style hybrid. coul/dsf and coul/wolf are a bit like the real part of coul/long, so the special_bond at 0 means that qi*qj/r^2 has to be subtracted from the damped forces, as in the source of pair_lj_cut_coul_dsf.cpp and similar:
`          if (factor_coul < 1.0) forcecoul -= (1.0-factor_coul)*prefactor;`

I think there’s special code in neighbor.cpp to prevent exclusion of neighbors for coul/wolf and coul/dsf when special_bonds is 0, but it doesn’t appear to work for pair_style hybrid in the demonstrated case.

**Comment by akohlmey** [comment]
> I think there’s special code in neighbor.cpp to prevent exclusion of neighbors for coul/wolf and coul/dsf when special_bonds is 0, but it doesn’t appear to work for pair_style hybrid in the demonstrated case.

yes, there is. however, this code will return a "no match" if there are multiple hybrid sub-styles that match the same pattern. so that would need to be updated.
