### ISSUE TITLE
[Feature Request] Implement Widom insertion method

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#1754]
**Summary**

Implement in a "fix" or "compute" the Widom insertion method to compute chemical potentials 

**Detailed Description**

Implementing Widom insertion would enable users to carry out tasks such as:
- parametrization of DPD models based on experimental solubility values following the approach in J Chem Phys. 2017, 147, 094503. doi: 10.1063/1.4992111. 
- direct chemical potential calculations in non-homogeneous liquids following the approach in J Chem Phys. 2018, 149, 072305. doi: 10.1063/1.5024631. The implementation of this approach requires also the coupling of LAMMPS with PLUMED which already exists.
- to speed-up calculations when using soft potentials and performing thermodynamic integration or free energy perturbation (doi 10.1021/ma970383u). For small \lambda values up to 0.15 the free energy can be computed directly by the Widom insertion method.

Most of the code for the geometric insertion & the energy evaluation could be inherited from fix gcmc. Nevertheless, IMHO the code in gcmc needs to be restructured. For instance, the function attempt_atomic_insertion() could be split into separate functions (I) for the insertion, (ii) the energy evaluation & (iii) the acceptance criterion and (iv) the update of all relevant quantities if the insertion is accepted. In this case, there is an additional benefit for GCMC: it will make easier to implement biased schemes for a more efficient grand canonical simulations (for instance see doi 10.1080/00268978000101971 ) as changes in only one place would need to be made.
  
I would like to participate in the implementation.

**Further Information, Files, and Links**

A naive implementation heavily based on the fix gcmc can be found in the attached files.  
[fix_widom.cpp.txt](https://github.com/lammps/lammps/files/3916667/fix_widom.cpp.txt)
[fix_widom.h.txt](https://github.com/lammps/lammps/files/3801726/fix_widom.h.txt)

**Comment by agiliopadua** [comment]
I suppose Widom insertions could be done using compute fep and fix adapt, in one step from \lambda=0 to \lambda=1. Use of soft potentials not required.

**Comment by evoyiatzis** [comment]
The use of soft potentials is related to how someone can make faster thermodynamic integration by performing Widom insertion for small \lambda values. The idea put forward by Gusev & Suter is described in doi 10.1021/ma970383u. I had not included it in the "Feature Request" text. I have added it now.
In my eyes, one aspect to consider is also the computational efficiency when performing Widom insertion. The neighbor lists should not be built from scratch at each insertion. The combination of compute fep and fix adapt may provide the evaluation of the energy but I cannot see how they perform efficiently the geometric insertion at various points.

**Comment by Pakketeretet2** [comment]
fix gcmc already has means to evaluate potential energies of a particle to
be inserted somewhere. One could just borrow this code but never insert to
do the chemical potential sampling.

**Comment by evoyiatzis** [comment]
Thanks for your suggestion @Pakketeretet2 . I have actually worked along these lines and the attached code is actually a suitably adapted version of "fix gcmc" for this task. The reason I request for this feature is because I do not consider copy-pasting code &making small changes to be a best practice. In the present case, nevertheless, it has produced a working code which works fine.

**Comment by XiaohanlPU** [comment]
Just want to correct some mistakes:
in your cpp file, in line 577, 7021, 798, 959, 1994, it seems your equation is wrong. The defination of beta is 1/kT, so for chemical potential calculation, you should use exp(-beta*insertion_energy), rather than exp(-1/beta*insertion_energy) in your code.

**Comment by evoyiatzis** [comment]
Thanks for the correction @XiaohanlPU ! You are right. I made this correction to the cpp file

**Comment by XiaohanlPU** [comment]
Hi, I'm just wondering whether this fix_widom command can be used on multi-processors for full-energy molecules. I remembered that  fix_gcmc was fixed to only one processor because people were reporting error when employing GCMC to full-energy molecule translation and rotation on multi-nodes. However, for widom test particle insertion, we didn't do any translation and rotation (e.g for water). So I'm wondering whether i can delete the error message for full-energy molecules on muti-nodes. Please correct me if I get something wrong.

**Comment by stanmoore1** [comment]
Seems like it wouldn't be hard to also code up the Bennett acceptance ratio method as well, which is more robust than Widom's method in some cases.

**Comment by evoyiatzis** [comment]
closed after #2230
