### ISSUE TITLE
bug in "group include molecule"

### ISSUE THREAD

**Issue by Amingeo** [lammps/lammps#1774]
Hello everyone,
In applying the following command:
#################
region          sph sphere 10.00 10.00 10.00 5
group           sph1 dynamic all region sph every 50
group           sph1 include molecule
dump           1 sph1 custom 50 position.xyz type id  mol x y z
dump_modify 1 sort id
#################
which is a simplified version of a script I need to use to apply a fix for all atoms of the molecules having a part in a 5 Angstrom distance from a specific position in the box, as you can try for any setup containing molecules, it fails to correctly include all atoms of the molecule which is supposed to be done by the command "include molecule" (just see the dump file and check the atoms of all molecules).
I was thinking maybe the error arises due to parallelization but in the serial version (the most recent version, complied in ubuntu) of lammps also I got the same issue.
One more thing, in my input data file, atoms IDs are assigned successively for atoms of molecules. Therefore dump_modify in my case should list all atoms of a molecule bellow each other. I also double checked to make sure missing atoms of a molecule are not listed in other lines of a snapshot.
Would be grateful if you can check it.
Kind regards,
Amin

#################

**Comment by akohlmey** [comment]
This is not an error. This is the expected behavior. The group "include" keyword, like all group keywords, is a one time operation (even the "dynamic" keyword is, as it sets up a fix to redefine the group regularly and the setup is a one time operation, too). Since you redefine the group according to the "dynamic" keyword every 50 steps, the effect of the "include" keyword is lost at that time. The same will happen to any other modification of the "sph1" group happening in between the dynamic redefinitions.

**Comment by Amingeo** [comment]
> 
> 
> This is not an error. This is the expected behavior. The group "include" keyword, like all group keywords, is a one time operation (even the "dynamic" keyword is, as it sets up a fix to redefine the group regularly and the setup is a one time operation, too). Since you redefine the group according to the "dynamic" keyword every 50 steps, the effect of the "include" keyword is lost at that time. The same will happen to any other modification of the "sph1" group happening in between the dynamic redefinitions.

thanks Axel, I guessed that can be the reason and tried to add dynamics to "include molecule too" but it yields error and the syntax has not been defined in lammps? Is there any solution because it can have some crucial applications.

**Comment by akohlmey** [comment]
> thanks Axel, I guessed that can be the reason and tried to add dynamics to "include molecule" too but it yields error and the syntax has not been defined in lammps?

correct. it has not been programmed. there are lots of things in LAMMPS that have not been programmed. feel free to alter the code according to your needs.

> Is there any solution because it can have some crucial applications.

the only "solution" I know would be to alter the code as needed. What would be a "crucial" application? In your example you merely use the dynamic group to have coordinates output to a dump.

**Comment by Amingeo** [comment]
> 
> 
> > thanks Axel, I guessed that can be the reason and tried to add dynamics to "include molecule" too but it yields error and the syntax has not been defined in lammps?
> 
> correct. it has not been programmed. there are lots of things in LAMMPS that have not been programmed. feel free to alter the code according to your needs.
> 
> > Is there any solution because it can have some crucial applications.
> 
> the only "solution" I know would be to alter the code as needed. What would be a "crucial" application? In your example you merely use the dynamic group to have coordinates output to a dump.

What I wrote (as stated) was just a simplified version of the script to simplify check ups. For my current study, I need to use it to apply a fix qeq/shielded to compute fluctuating point charges for nearest atoms withing a cut-off distance to an atom frozen on the position 10 10 10. I cannot apply this fix to all atoms in the cell because it makes the computation too expensive and also during partial passage of molecules from the boundary, it yields strange and unrealistic point charges. The "include molecule" command could be a good solution but in this current features that you mentioned, as it does not includes all atoms of a molecule, fix qeq wont work and again yields very strange point charges.
Also for the simple script I wrote as well, some times ago I needed to use it where I needed to run a long simulation on a relatively large system and needed to have the force and position of few of the atoms not all, closest to a specific position (surface)  and it again didn't work. Therefore I had to dump all position and forces of all particles and get what I need by post processing resulted in a very huge dump file (ca 200GB) which was extremely inconvenient to work with. I think that would be very beneficial to add this feature in upcoming versions of LAMMPS.

**Comment by akohlmey** [comment]
> > > thanks Axel, I guessed that can be the reason and tried to add dynamics to "include molecule" too but it yields error and the syntax has not been defined in lammps?
> > 
> > 
> > correct. it has not been programmed. there are lots of things in LAMMPS that have not been programmed. feel free to alter the code according to your needs.
> > > Is there any solution because it can have some crucial applications.
> > 
> > 
> > the only "solution" I know would be to alter the code as needed. What would be a "crucial" application? In your example you merely use the dynamic group to have coordinates output to a dump.
> 
> What I wrote (as stated) was just a simplified version of the script to simplify check ups. For my current study, I need to use it to apply a fix qeq/shielded to compute fluctuating point charges for nearest atoms withing a cut-off distance to an atom frozen on the position 10 10 10. I cannot apply this fix to all atoms in the cell because it makes the computation too expensive and also I noticed during partial passage of molecules from the boundary, it yields strange and unrealistic point charges. The "include molecule" command could be a good solution but in this current features that you mentioned, as it does not includes all atoms of a molecule, fix qeq wont work and again yields very strange point charges.

I don't think that this can work because, to the best of my knowledge, none of the qeq fixes support dynamic groups (and if i recall correctly, it would be complicated to add support for that, since they need to store and access per-group-atom properties from previous iterations/steps and that would not be compatible with dynamic groups).

> Also for the simple script I wrote as well, some times ago I needed to use it where I needed to run a long simulation on a relatively large system and needed to have the force and position of few of the atoms not all, closest to a specific position (surface) and it again didn't work. Therefore I had to dump all position and forces of all particles and get what I need by post processing resulted in a very huge dump file (ca 200GB) which was extremely inconvenient to work with. I think that would be very beneficial to add this feature in upcoming versions of LAMMPS.

for selecting atoms for outputting them to dump files, there are multiple options. check out the "dump_modify thresh" option.
