### ISSUE TITLE
Bug about lj/cut/coul/long?

### ISSUE THREAD

**Issue by LucienPan0903** [lammps/lammps#1778]
**Summary**

I tried to use lj/cut/coul/long, but I cannot find any code about it in the src/ directory. I can find the description in the document but no code in the stable and master branch of lammps.

**LAMMPS Version and Platform**

Master branch and the latest stable version.

**Expected Behavior**

When I tried to use the command "pair_style hybrid lj/class2/coul/long 10.0 lj/cut/coul/long 10.0", an error was threw out since " lj/cut/coul/long" was not recognized as a valid pair_style.

**Actual Behavior**

The same as above.

**Steps to Reproduce**

Use pair_style hybrid lj/class2/coul/long 10.0 lj/cut/coul/long 10.0 in the input file.

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by stanmoore1** [comment]
Did you enable/install the KSPACE package?

**Comment by LucienPan0903** [comment]
You are right. I did not enable that package.  Thank you very much! I find the lj/cut/coul/long in the KSPACE directory. Thank you very much!
