### ISSUE TITLE
[Feature Request] Need tool or macro to build command tables

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1781]
**Summary**

Updating the tables of commands in the files `doc/src/Commands*.rst` is tedious compared to what we had with the .txt format. So we would need some semi-automated way to (re-)build those tables from simple lists. Right now it is still possible to update the corresponding files in `doc/txt/` and redo the translation, but that will go away soon, and also those patches are needlessly large due to the kind of change needed when rebuilding a table.

**Comment by akohlmey** [comment]
This could be combined with a tool to check, if the lists of commands/styles are complete. I'm working on a code parsing the LAMMPS headers into a suitable data structure.

**Comment by eagunn** [comment]
@akohlmey This looks like something I might be able to accomplish over my college's Christmas break. Can you give me a better idea of what you are thinking of for input files to the builder part?
It will probably be 2 weeks or so before I could look at it in any detail, so if you're in a hurry, I'm out. If its longer term, I'd like to take a stab at it.

**Comment by rbberger** [comment]
I’m already working on a Sphinx extension for this. Haven’t pushed anything yet since getting the LaTeX version to produce something meaningful is more tricky.

**Comment by eagunn** [comment]
@rbberger Ack. Let me know if you could use an alpha tester or output checker in Dec/Jan, then.

**Comment by akohlmey** [comment]
We have now a simplified list format that is converted to tables automatically and a tool to check if styles are missing. That should do the trick for a while.
