### ISSUE TITLE
Short 3-body neighbor list on non-tabulated MANYBODY pair styles

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#179]
Pair styles such as vashishta and sw will get considerably better performance if we during the 2-body force loop build a short 3-body neighbor list like we have in the vashishta/table version.

This doesn't change any computations at all, but reduces extra unnecessary work for the CPU. I suggest we implement this short list in the normal implementations as well?

**Comment by akohlmey** [comment]
PR #246 re-implements this feature in a consistent and less memory consuming fashion, that also takes the different element-vs-element cutoffs into account. USER-OMP support to follow.
