### ISSUE TITLE
[BUG] Python library paths on Debianoids

### ISSUE THREAD

**Issue by martok** [lammps/lammps#1793]
**Summary**

It seems that the library installer in python/install.py when run as root does not seem to play well with Debian's patches to where packages are. Paths below refer to Py3.6 on Ubuntuu 18.04 LTS.

Packages are installed into `/usr/local/lib/python3.6/dist-packages/`, which distutils correctly do.
However, `liblammps.so` is installed into the directory returned by `get_python_lib`, which seems to *not* honor that convention:

```
$ python3 -c "from distutils.sysconfig import *; print(get_python_lib())"
/usr/lib/python3/dist-packages
```

That results in liblammps.so and lammps.py not ending up in the same folder, so loading the library does not work.

Looks like this is a known upstream bug and pops up every now and then, (most recent google hit: <https://bugs.launchpad.net/ubuntu/+source/python3-stdlib-extensions/+bug/1832215>, these go back to at least 2010), but a workaround would be appreciated.

Based on https://stackoverflow.com/a/9155056 I came up with this solution, but it feels super hacky and I'm understandably hesitant to submit this as a patch...

```diff
diff --git a/python/install.py b/python/install.py
index 7f7062103..1adef77fc 100644
--- a/python/install.py
+++ b/python/install.py
@@ -96,6 +96,32 @@ from distutils.sysconfig import get_python_lib
 import site
 tryuser=False

+# locate true install location (needed to work around Debian bug)
+def get_default_lib_install():
+  from distutils.command.install import install
+
+  class install_default_proxy(install):
+    def __init__(self):
+      from distutils.dist import Distribution
+      dist = Distribution()
+      self.distribution = dist
+      self.initialize_options()
+      self._dry_run = None
+      self.verbose = dist.verbose
+      self.force = None
+      self.help = 0
+      self.finalized = 0
+
+  e = install_default_proxy()
+  import distutils.errors
+  try:
+    e.finalize_options()
+  except distutils.errors.DistutilsError:
+    pass
+
+  return e.install_lib
+
+
 try:
   sys.argv = ["setup.py","install"]    # as if had run "python setup.py install"
   setup(name = "lammps",
@@ -106,7 +132,7 @@ try:
         description = "LAMMPS Molecular Dynamics Python module",
         license = "GPL",
         py_modules = ["lammps"],
-        data_files = [(get_python_lib(), [args.lib])])
+        data_files = [(get_default_lib_install(), [args.lib])])
 except:
   tryuser=True
   print ("Installation into global site-packages folder failed.\nTrying user folder %s now." % site.USER_SITE)
```

Is anyone aware of a better solution?

**LAMMPS Version and Platform**

Regardless of LAMMPS Version, affects any Debian and derivatives, such as Ubuntu, Mint, Devuan etc. as long as the maintainer-provided Python is used (own builds from source are fine).

**Comment by akohlmey** [comment]
My feeling is that this either needs to be worked around in the the LAMMPS debian/ubuntu/whatever binary package is generated or people should rather manually install the LAMMPS python wrapper at user level and not as root, which would then place it in $HOME/.local/lib/pythonX.Y/site-packages.
It is my understanding that the liblammps.so shared library is installed in a system location with ubuntu/debian and thus should be found by the python wrapper.
Since this is technically not really a LAMMPS issue, i will close this issue for now. We can reopen it, in case there is a better argument for why there should be a workaround in LAMMPS than installing it at user level.

**Comment by martok** [comment]
> It is my understanding that the liblammps.so shared library is installed in a system location with ubuntu/debian and thus should be found by the python wrapper.

It does not. `install.py` asks setuptools to provide the shared library as a "data file", to be placed wherever Python thinks that may go. The wrapper looks for the library first in it's own directory, which happens to be the same place by default, but not on Debian. Then it looks without path, but for that the installer would have needed to put the .so in `/usr/local/lib`, update ldconfig and load `liblammps.so.0` (that is probably what a package maintainer would do).
I guess it would also possible to fix the library search to take all that into account?
