### ISSUE TITLE
[Feature Request] _Implementation_of_a_Generic_Neural_Network_Force_Field_pair_style_NN

### ISSUE THREAD

**Issue by moradza** [lammps/lammps#1809]
**Summary**

_Please provide a brief and concise description of the suggested feature or change_
Empirical potential like SW and LJ are limited by the analytical form used to describe interactions, furthermore, new potentials require to make *.cpp and *.h files, I suggest to replace table potential for 2body and 3body interaction with NN force field. 

**Detailed Description**

_Please explain how you would like to see LAMMPS enhanced, what feature(s) you are looking for, what specific problems this will solve. If possible, provide references to relevant background information like publications or web pages, and whether you are planning to implement the enhancement yourself or would like to participate in the implementation. If applicable add a reference to an existing bug report or issue that this will address._

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by akohlmey** [comment]
Sorry, but you are suggesting is makes little sense. Neural network based potentials and tabulated potentials (or explicitly formulated empirical potentials for that matter) serve different purposes and have different properties and different computational costs. There is a lot of value in empirical potentials and they can be used for problems, that NN based potentials cannot. And NN based interaction models are not the solution to many MD problems. In fact, they are quite difficult to get right and there are a lot of issues that still need to be worked out.

**Comment by moradza** [comment]
I agree with you on the computational costs of NN potentials but as someone who is training NN potential, I disagree with you. NN potential trained with enough expertise match any tabulated potential, at least based on my ongoing research. I'll send out my paper to you as soon as it got published.

**Comment by akohlmey** [comment]
> I agree with you on the computational costs of NN potentials but as someone who is training NN potential, I disagree with you. NN potential trained with enough expertise match any tabulated potential, at least based on my ongoing research. I'll send out my paper to you as soon as it got published.

No need to send me your paper. There are too many of these papers floating around already and I most likely won't care enough to read it. I am not objecting to your research, but to your claim to remove features that are useful and that we are planning on improving, too. You are missing the point of why tabulated potentials are useful and thus have value. That your NN potentials may be more accurate is irrelevant in this respect. Same goes for empirical potentials.

LAMMPS is built to be easily extensible, so there is no reason remove well working and useful features in favor of new features that have yet prove themselves to be at least equally useful and applicable. There are already machine learning potentials available inside of LAMMPS and, if well written and properly documented, there is room for adding more.
