### ISSUE TITLE
suspected bug in fix_temp_csvr.cpp

### ISSUE THREAD

**Issue by efremdan1** [lammps/lammps#181]
When I run long enough with fix temp/csvr, I tend to get the error message:
> ERROR on proc 0: Non-numeric atom coords - simulation unstable (../domain.cpp:510)

When I change the random number, the timestep at which this error occurs changes.

I did some debugging, and I believe the bug is in the FixTempCSVR::gamdev function in fix_temp_csvr.cpp, lines 51-52 (and perhaps also later on in the same function). If random->uniform() gives 0, then x becomes equal to 0, and log(0) gives inf.

I'm guessing this is due to a float precision error. Doing something like
```
double random=random->uniform();
while (random==0)
  random=randon->uniform();
x *= random
```
fixes things for me, though perhaps it's better to fix this directly in random_mars.cpp.

I'm no expert at random number generation, so I can't guarantee that doing this doesn't make the resulting distribution improper.

Example below, with data file attached.

#settings
units              real
atom_style         bond
neigh_modify       delay 0 every 1
comm_modify        vel yes

#atom and FF definitions
read_data          "system.data.txt"
pair_style         lj/cut 14.0
pair_coeff         1 1 0.195 3.75
bond_style         harmonic
bond_coeff         1 240 1.54

#run settings
timestep           0.5
thermo             200
thermo_style       one
velocity           all create 350.0 12856

#NVT with Bussi thermostat
fix                1 all temp/csvr 350.0 350.0 100.0 54324 
fix                2 all nve
run                2000000

[system.data.txt](https://github.com/lammps/lammps/files/474730/system.data.txt)

**Comment by timattox** [comment]
IMHO: I would be hesitant to prevent random->uniform() from returning zero.  I just did a cursory look within the code repository and didn't find documentation on if random->uniform is mathematically defined as (0..1), [0..1), [0..1], or (0..1].  Preventing a return of zero would change its mathematical definition (wherever it was originally defined).

**Comment by akohlmey** [comment]
@timattox this was already discussed on lammps-users. in this case, it is better to handle it according to what the calling code needs.
