### ISSUE TITLE
[BUG] USER-INTEL hybrid pair styles silently ignore pair_modify pair special settings.

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#1826]
**Summary**

The pair_modify command can be used to selectively modify the special_bonds settings of hybrid pair sub-styles. When switching to USER-INTEL via the -sf intel command line argument, the pair_modify special settings are silently ignored and the global settings are used for all sub-styles.

**LAMMPS Version and Platform**

Latest master version with PR #1817 merged.

**Steps to Reproduce**
The following script creates two identical molecules where only 1-4 interactions are different:
```
units real
atom_style molecular

region box block -30 30 -30 30 -30 30
create_box 2 box bond/types 1 extra/bond/per/atom 1
mass * 100

pair_style hybrid lj/cut 10 lj/cut 10
pair_coeff * * lj/cut 1 1 1
pair_coeff 2 2 lj/cut 2 1 1

create_atoms 1 single  0 0 0
create_atoms 1 single  1 0 0
create_atoms 1 single  2 0 0
create_atoms 1 single  3 0 0

create_atoms 2 single  0 0 15
create_atoms 2 single  1 0 15
create_atoms 2 single  2 0 15
create_atoms 2 single  3 0 15

bond_style harmonic
bond_coeff 1 0 1

create_bonds many all all 1 0.9 1.1
special_bonds lj 1 1 1e-100
pair_modify pair lj/cut 2 special lj 1 1 1

variable fx1 equal fx[1]
variable fx5 equal fx[5]

thermo_style custom step v_fx1 v_fx5

run 0
```

**Actual Behavior**

When running the script with USER-INTEL via the -sf intel command line option, forces acting on atoms 1 and 5 are identical, i.e. pair_modify settings are ignored:

> Step v_fx1 v_fx5 
>        0   -23.818359   -23.818359 

**Expected Behavior**

When running the sample script with non USER-INTEL pair styles, forces acting on atoms 1 and 5 are different due to the difference in 1-4 interactions:

> Step v_fx1 v_fx5 
>        0   -23.818359   -23.807416 

LAMMPS should either produce identical results, bar numerical error, regardless of whenever USER-INTEL pair styles are used, or should produce an error in case that is not possible.

**Comment by akohlmey** [comment]
This cannot be fixed because of the way how this modification is implemented in pair style hybrid and how USER-INTEL prepackages and preprocesses force field settings for better accessibility and performance. I have to think very hard about finding a way to detect it. It probably is only possible from inside pair style hybrid, not from the USER-INTEL styles.
