### ISSUE TITLE
tarball is getting pretty big

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#1839]
```
$ ll -S lammps-*20??.tar.gz
-rw-rw-r--. 1 junghans junghans 110M Dec 11  2018 lammps-stable_12Dec2018.tar.gz
-rw-rw-r--. 1 junghans junghans 104M Aug 22  2018 lammps-stable_22Aug2018.tar.gz
-rw-rw-r--. 1 junghans junghans 104M Jan 14 11:16 lammps-patch_9Jan2020.tar.gz
-rw-rw-r--. 1 junghans junghans 102M Jun  4  2019 lammps-stable_5Jun2019.tar.gz
-rw-rw-r--. 1 junghans junghans 101M Aug 14 14:13 lammps-stable_7Aug2019.tar.gz
-rw-rw-r--. 1 junghans junghans  88M Jun 29  2018 lammps-stable_16Mar2018.tar.gz
-rw-r--r--. 1 junghans junghans  88M Mar  8  2018 lammps-patch_8Mar2018.tar.gz
-rw-rw-r--. 1 junghans junghans  88M Mar  5  2018 lammps-patch_22Feb2018.tar.gz
-rw-rw-r--. 1 junghans junghans  88M Jan 26  2018 lammps-patch_17Jan2018.tar.gz
-rw-rw-r--. 1 junghans junghans  86M Nov  3  2017 lammps-patch_23Oct2017.tar.gz
-rw-rw-r--. 1 junghans junghans  85M Sep 10  2017 lammps-patch_1Sep2017.tar.gz
```
It creeped up slowly, but it is getting pretty big.

Inside the latest tarball:
```
$ du --max-depth=1 -h | sort -h
88K	./.github
396K	./cmake
924K	./python
18M	./tools
29M	./lib
37M	./bench
38M	./src
39M	./potentials
40M	./doc
150M	./examples
349M	.
```
Around 40% are the examples.

**Comment by akohlmey** [comment]
the logical step would be to put the examples into a separate tar file, but that is a discussion you have to have with @sjplimp

**Comment by sjplimp** [comment]
@akohlmey @junghans When I download the Aug 2019 tarball (gzipped ) I get ~140 MB.  You listing says 101M ??  So 100-140 MB is the download size.  The tarball
unpacks to 400 MB.  The size of the git repo on my box looks like 840 MB ?  
Practically speaking, which of those is a problem for the average user?

**Comment by junghans** [comment]
I don't think it is a huge issue, but it would be nice to have a source-only tarball to save some time when download LAMMPS.

**Comment by akohlmey** [comment]
> I don't think it is a huge issue, but it would be nice to have a source-only tarball to save some time when download LAMMPS.

Slow download is mostly an issue when downloading LAMMPS from the Sandia webpage. The fastest way (for me) to get a complete new LAMMPS copy is using `git clone --depth 1 git@github.com:lammps/lammps.git`, which takes me about 10 seconds (the `--depth 1`  omits the commit history and cuts the amount of data in half). Using the anonymous access with https://github.com/lammps/lammps.git adds 50% to make it about 16 seconds. Next is a download from the github release page, which also takes me about 16 seconds. While downloading from the Sandia LAMMPS download page seems to be throttled to less than 200kB/s (from github I get over 20MB/s in comparison) and takes over 12 minutes for the latest patch. The Sandia version is larger because it contains the pre-rendered html pages and the PDF Manual and the Developer PDF, which are all missing from the github repository and thus not included in the github downloads.

**Comment by akohlmey** [comment]
@sjplimp @junghans 
Is there any meaningful action item here?

If the purpose of the download from sandia is to provide a "complete" package with documentation ready, there is little that can be done except perhaps inquiring, whether there is a deliberate bandwidth limit on those downloads, and if that could be changed.
For any automated build tools, it should be most effective to download from github, anyway.

Which reminds me of another thing: perhaps we should have LAMMPS registered with a DOI generating site like Zenodo, which will generate one generic DOI for all versions of the software and a specific DOI for each release that is tagged as a release on the github releases page. I've done this with some of my own packages ( TopoTools VMD plugin https://doi.org/10.5281/zenodo.598373 (generic DOI) https://doi.org/10.5281/zenodo.545655 (version 1.7), https://doi.org/10.5281/zenodo.50249 (version 1.6), TclMPI https://doi.org/10.5281/zenodo.545847 )
This would give people a permanent and consistent, citeable reference.

**Comment by junghans** [comment]
Yeah, Zenodo would be nice.

**Comment by junghans** [comment]
Fedora, OpenSUSE, Spack and Gentoo already download the source from github.

**Comment by ellio167** [comment]
I believe OpenKIM would be happy to do this (DOI minting) for you...

**Comment by akohlmey** [comment]
> I believe OpenKIM would be happy to do this (DOI minting) for you...

Thanks for the offer. There are several services available, but the GitHub integration of Zenodo is hard to beat in terms of convenience.

**Comment by ellio167** [comment]
> > I believe OpenKIM would be happy to do this (DOI minting) for you...
> 
> Thanks for the offer. There are several services available, but the GitHub integration of Zenodo is hard to beat in terms of convenience.

Yeah, that is certainly true.  I just wanted to offer it as an option.

**Comment by akohlmey** [comment]
Here are the latest numbers:
`-rw-r--r-- 1 akohlmey klein 118M Mar 24 22:37 patch_19Mar2020.tar.gz`
and
```
$ du --max-depth=1 -h | sort -h
88K	./.github
404K	./cmake
928K	./python
18M	./tools
27M	./doc
29M	./lib
37M	./bench
39M	./src
123M	./potentials
151M	./examples
```

While the doc folder has shrunk significantly, this was overcompensated by the massive mesocnt potential file.

**Comment by akohlmey** [comment]
I've tried and set up LAMMPS for obtaining a DOI for the latest stable release. This specific release is registered: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3726417.svg)](https://doi.org/10.5281/zenodo.3726417)

There also is a DOI for **all** LAMMPS releases [https://doi.org/10.5281/zenodo.3726416](https://doi.org/10.5281/zenodo.3726416)

**Comment by akohlmey** [comment]
We are now downloading large files on demand, when the corresponding package is installed. For examples instead a git submodule with a separate download would be the preferred option. I think that is all that can be done on this topic for now.
