### ISSUE TITLE
[BUG] PyLammps throws a ValueError if warnings occur during a run

### ISSUE THREAD

**Issue by marlpur** [lammps/lammps#1844]
**Summary**

When using the PyLammps interface, the get_thermo_data() function pulls thermodynamic data from the output of a run. If LAMMPS writes a warning to the output during the run then PyLammps attempts to interpret this as numeric data and crashes. The following is an example.

```
run 1000 
Per MPI rank memory allocation (min/avg/max) = 105.1 | 107.4 | 109.6 Mbytes
Step Temp E_pair E_mol TotEng Press 
  119000    2289.2961   -295436.92            0   -279659.93     18093.84 
WARNING: Fix qeq/reax CG convergence failed after 200 iterations at 119476 step (../fix_qeq_reax.cpp:735) 
  120000    3189.0878   -292083.96            0   -270105.94    34775.495 
Loop time of 70.0175 on 8 procs for 1000 steps with 2288 atoms
```

**LAMMPS Version and Platform**

LAMMPS 07-Aug-2019
Running on CentOS-7

**Expected Behavior**

PyLammps should skip lines containing warnings when reading thermodynamic data from the output rather than trying to interpret all lines as numeric data.

**Actual Behavior**

Instead a ValueError occurs as python tries to interpret "WARNING:" as a floating point:
```
Traceback (most recent call last):
  File "my_script.py", line 359, in <module>
    if rank == 0:
  File "/users/mp/.local/lib/python3.7/site-packages/lammps.py", line 877, in run
    self.runs += get_thermo_data(output)
  File "/users/mp/.local/lib/python3.7/site-packages/lammps.py", line 821, in get_thermo_data
    values = [float(x) for x in line.split()]
  File "/users/mp/.local/lib/python3.7/site-packages/lammps.py", line 821, in <listcomp>
    values = [float(x) for x in line.split()]
ValueError: could not convert string to float: 'WARNING:'
```

**Steps to Reproduce**

Run any input file that will produce a warning during a run via PyLammps  and the issue will occur when the run finishes and PyLammps tries to get the thermodynamic data.

**Comment by akohlmey** [comment]
Thanks for reporting. This is addressed in pull request #1845
