### ISSUE TITLE
[Feature Request] KOKKOS - fix rattle / shake

### ISSUE THREAD

**Issue by JGaed** [lammps/lammps#1849]
**Summary**

Porting fix rattle / shake to kokkos package

**Detailed Description**

As we perform calculations of big systems with a lot of water on a GPU cluster using the Kokkos package we would ask to port the fix shake and/or rattle to the Kokkos package. Is it planned in the future? Thank you in advance!

**Comment by akohlmey** [comment]
@JGaed do you have some performance comparison of your setup for using KOKKOS versus the GPU package, and especially with running the GPU package in such a way, that only the pair style will be run on the GPU and perhaps with a combination of GPU and USER-OMP (in case the optimal GPU oversubscription leaves a half or more of the CPU cores idle and/or you are reaching the communication limit of the 3d-FFTs in pppm)? 
If you are using pppm and are adventurous, you may want to also try out the code in PR #1520 which can speed pppm on the GPU with KOKKOS by also running the FFTs on the GPU.

**Comment by stanmoore1** [comment]
Porting fix shake to Kokkos is high on our to-do list.

**Comment by JGaed** [comment]
@akohlmey Thank you for your advice. We've used the GPU packaged in the past but not in a combination with USER-OMP. I will give it a try and will do some benchmarks in the next days.

@stanmoore1 I am glad to hear that and will be patient.

Thank you both for your fast answer.

**Comment by stanmoore1** [comment]
@JGaed I have fix shake ported to Kokkos in #2441. Testing/debugging now.
