### ISSUE TITLE
[BUG] Cannot use pair_style extep with more than 8 atom types

### ISSUE THREAD

**Issue by pzeiger** [lammps/lammps#1851]
**Summary**

LAMMPS crashes with segfault/memory allocation error if more than 8 atom types are used in conjunction with "pair_style extep".

**LAMMPS Version and Platform**

patch_9Jan2020, Debian 10, linux x86

**Expected Behavior**

Like for "pair_style tersoff", one should be able to use "pair_style extep" with a larger number of atom types (tested Tersoff with up to about 50).

**Actual Behavior**

LAMMPS crashes with segfault/memory allocation error.

**Steps to Reproduce**

Run LAMMPS with the attached file "doesnotwork.in". "works.in" showcases that using one atom type less, the crash does not occur.

**Further Information, Files, and Links**

I have tried to debug the issue myself but I am not familiar enough with C++ and the LAMMPS code base to continue without investing a large amount of time. What I have found thus far is that the error occurs in the read_file() method of the class PairExTeP in source file "pair_extep.cpp". Inside this function the method "atom->count_words()" is called a couple of times. It seems that the exact line where it crashes changes depending on how many print statements I include (or where) for debugging purposes. Now inside the "atom->count_words()"-method, the considered line of the potential file is copied, which seems to be the cause for the troubles.

[extep_bug.zip](https://github.com/lammps/lammps/files/4098179/extep_bug.zip)

**Comment by akohlmey** [comment]
Thanks for the report. However, the crash you see is due to memory corruption and has a different cause. It can be corrected by the following change:
```
$ git diff
  diff --git a/src/USER-MISC/pair_extep.cpp b/src/USER-MISC/pair_extep.cpp
  index f7670d30b..df232e029 100644
  --- a/src/USER-MISC/pair_extep.cpp
  +++ b/src/USER-MISC/pair_extep.cpp
  @@ -719,8 +719,8 @@ void PairExTeP::read_file(char *file)
     words = new char*[params_per_line+1];
   
     // intialize F_corr_data to all zeros
  -  for (int iel=0;iel<atom->ntypes;iel++)
  -    for (int jel=0;jel<atom->ntypes;jel++)
  +  for (int iel=0;iel<nelements;iel++)
  +    for (int jel=0;jel<nelements;jel++)
         for (int in=0;in<4;in++)
           for (int jn=0;jn<4;jn++)
             for (int ivar=0;ivar<3;ivar++)

```
