### ISSUE TITLE
[BUG] New GJF-2GJ langevin integrator

### ISSUE THREAD

**Issue by finkeljos** [lammps/lammps#1871]
**Summary**

When using the newly implemented GJF-2GJ Langevin integrator with the systems I am studying via the command 

fix 1 all langevin 300.0 300.0 100.0 1 gjf vhalf

I get the following warning from LAMMPS:

"Inconsistent image flags (src/domain.cpp:785)"

accompanied by a wild explosion of KE, temperature and pressure.

**LAMMPS Version and Platform**

I am using the Nov 2019 version of LAMMPS on Linux.

**Steps to Reproduce**

This can be seen by simply considering the LAMMPS example file peptide. If you make the following replacement to the input script

fix             1 all langevin 300.0 300.0 100.0 1 gjf vhalf
fix             3 all nve
#fix            1 all nvt temp 275.0 275.0 100.0 tchain 1

The warning will occur.

**Comment by charlessievers** [comment]
The changes I made were put in 14 days ago #1852. I believe the bug you were experience will be fixed if you pull the current master.

**Comment by giacomofiorin** [comment]
@finkeljos Once you confirm that it works don't forget to close this issue.
