### ISSUE TITLE
[BUG] building error

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [lammps/lammps#1887]
**Summary**

[  4%] Built target poems
[  5%] Built target cslib
[  5%] Built target nvc_get_devices
[  5%] Building NVCC (Device) object CMakeFiles/cuda_compile_2.dir/__/lib/gpu/cudpp_mini/cuda_compile_2_generated_scan_app.cu.o
fatbinary fatal   : Could not write file '/tmp/tmpxft_0001930a_00000000-2_scan_app.fatbin.c'
CMake Error at cuda_compile_2_generated_scan_app.cu.o.RelWithDebInfo.cmake:279 (message):
  Error generating file
XXX/lammps/source/lammps-patch_18Feb2020/build/CMakeFiles/cuda_compile_2.dir/__/lib/gpu/cudpp_mini/./cuda_compile_2_generated_scan_app.cu.o

**LAMMPS Version and Platform**

lammps-patch_18Feb2020

**Steps to Reproduce**
export LVER=lammps-patch_18Feb2020
mkdir ~/lammps/source/$LVER/build
cd ~/lammps/source/$LVER/build

cmake -D GPU_API=cuda -D PKG_ASPHERE=yes -D PKG_BODY=yes -D PKG_CLASS2=yes -D PKG_COLLOID=yes -D PKG_COMPRESS=yes -D PKG_CORESHELL=yes -D PKG_DIPOLE=yes -D PKG_GRANULAR=yes -D PKG_KOKKOS=yes -D PKG_KSPACE=yes -D PKG_MANYBODY=yes -D PKG_MC=yes -D PKG_MESSAGE=yes MISC=yes -D PKG_MOLECULE=yes -D PKG_MPIIO=yes -D PKG_OPT=yes -D PKG_PERI=yes -D PKG_POEMS=yes -D PKG_PYTHON=yes -D PKG_QEQ=yes -D PKG_REPLICA=yes -D PKG_RIGID=yes -D PKG_SHOCK=yes -D PKG_SNAP=yes -D PKG_SPIN=yes -D PKG_SRD=yes -D PKG_GPU=yes -D PKG_USER-MOLFILE=yes -D MOLFILE_INCLUDE_DIRS=/software/apps/vmd/1.9.3/lib/vmd/plugins/include -D PKG_USER-MEAMC=yes -D FFT=FFTW3 -D FFTW3_INCLUDE_DIR=/software/apps/fftw3/3.3.8/gcc/5.5.0/include -D FFTW3_LIBRARY=/software/apps/fftw3/3.3.8/gcc/5.5.0/lib/libfftw3.so -D CMAKE_INSTALL_PREFIX=~/lammps/$LVER ../cmake | tee log-configure

make -j8
make install

**Further Information, Files, and Links**

The same building routine worked in last version

**Comment by akohlmey** [comment]
This looks like you have either a permission error on /tmp or you are running out of disk space on that partition. This can happen more often on recent Linux versions, as those use by default a ramdisk (file system type tmpfs), so it is easily flooded. I've been compiling LAMMPS with GPU support on multiple machines recently via CMake and never saw an issue.
