### ISSUE TITLE
[BUG]  call python from a lammps input script

### ISSUE THREAD

**Issue by wqchen007** [lammps/lammps#1951]
**Summary**

Calling python from a lammps input script can't run correctly after installation following instructions

**LAMMPS Version and Platform**

lammps-7Aug19/centos 7.6/python3.7

**Expected Behavior**

Test the example in example/python and calling python from a lammps input script can run correctly after installation following instructions

**Actual Behavior**

after installing the python package, we test the examples in example/python, the file that do not call back from lammps can run correctly but the others which need to call back from lammps (which means may need use the order 'import lammps from lammps','lmp = lammps(ptr= lmpptr)') always have error message: 'Could not process Python string' or 'Python function evaluation failed'

**Comment by akohlmey** [comment]
Thanks for submitting a bug report. Sadly, there is not enough information here to reproduce it and to figure out what is at fault. Based on previous experience, it may just be a user error. Thus you need to provide more details about what **exactly** you did to configure, compile, install, and run LAMMPS and which inputs **exactly** are failing. It is more likely, that you omitted some step during configuration/installation of LAMMPS. Most importantly, you need to confirm that the issue persists with the latest LAMMPS version (19 March 2020) where all inputs have been successfully tested.

**Comment by wqchen007** [comment]
Thanks for your reply! we have tried two version of lammps: 3 March 2020 and 7 Aug 2019, we install them with the orders: $make yes-python $make serial $make mpi, and both of them can run normal test file correctly. we test the example in example/python like 'in.fix_python_invoke' but  it return an error: ERROR: Could not process Python string (../python_impl.cpp:227), and the other task that need call back from lammps have the same problem.
