### ISSUE TITLE
Fixing and Updating HowTo Discussion: 8.1.3. Using LAMMPS with Bash on Windows 

### ISSUE THREAD

**Issue by erny123** [lammps/lammps#1953]
**Summary**

 [HowTo Discussion 8.1.3. Using LAMMPS with Bash on Windows](https://lammps.sandia.gov/doc/Howto_bash.html)  needs updating 

Now that it's easier to use linux on windows, this section should be updated.

**Detailed Description**

1.  Should probably include this link at the beginning: 
[https://docs.microsoft.com/en-us/windows/wsl/install-win10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

2.  In the section "Installing Prerequisite Packages", the second step needs to be fixed. 
In 
`sudo apt install -y build-essential ccache gfortran openmpi-bin libopenmpi-dev libfftw3-dev libjpeg-dev libpng12-dev python-dev python-virtualenv libblas-dev liblapack-dev libhdf5-serial-dev hdf5-tools
`
the `libpng12-dev` is no longer supported and should be changed to `libpng-dev` according to: [https://askubuntu.com/questions/991706/e-package-libpng12-dev-has-no-installation-candidate](https://askubuntu.com/questions/991706/e-package-libpng12-dev-has-no-installation-candidate)

I'm just starting to use LAMMPS so thought I could add some feedback before I forget.

**Comment by rbberger** [comment]
Thanks for reporting! I've fixed the two issues you mentioned in PR  #1962. WSL is a moving target and we'll update the docs. Right now I'm waiting for the general availability of WSL 2.0, which will require a larger rewrite.
