### ISSUE TITLE
[BUG] segfault with uloop on many partitions

### ISSUE THREAD

**Issue by schmidf** [lammps/lammps#1954]
**Summary**

Using a uloop variable to distribute jobs to many partitions sometimes causes a segfault when incrementing the loop variable.

**LAMMPS Version and Platform**

7 Aug 2019, Cluster with SUSE Linux Enterprise Server 12 SP4, Intel compiler, GPFS filesystem

**Expected Behavior**

I want to run otherwise identical simulations for ~2000 different values of a parameter on a cluster with 320 cores. The input script has the following form:
```
variable n_steps index 2000
variable a uloop ${n_steps} pad
[simulation code]
clear

next a
jump SELF
```
LAMMPS is launched with `lmp -in input.lammps -p 320x1`. Most of the time this gives the desired behavior.

**Actual Behavior**

Sometimes (~3/20 runs) one of the 320 processes segfaults when trying to execute the `next a` line. The core dump points to the following line:
https://github.com/lammps/lammps/blob/d08d6b5fb0e4cee067c386ff719b068094567f8f/src/variable.cpp#L685

When the problem has occured, the `tmp.lammps.variable` file has been renamed to `tmp.lammps.variabe.lock`, but is empty. This probably explains the segfault but I am not sure how the file can end up empty.

**Steps to Reproduce**

I could not reproduce the problem on my desktop PC, only on a cluster with many cores.

After hard-coding the uloop size in the input script instead of using the `n_steps` variable, the problem did not occur in 20 runs.

**Comment by akohlmey** [comment]
@schmidf thanks for reporting. this piece of code has a known race condition problem with no clean solution. If you run `git annotate` on that section of code, you can see that @sjplimp worked on that over 6 years ago. Before that change, the race condition was even more severe and would have tasks run simulations multiple times because they would not notice the increment. We should nevertheless make a change to the code that avoids the segmentation fault and I have an idea for how to do it.

**Comment by akohlmey** [comment]
@schmidf could you please try to apply the following change to `src/variable.cpp`, recompile LAMMPS and see, if those segmentation faults will still appear or whether there are other problems. Thanks.

@sjplimp does this kind of change make sense to you? do you see a way to do the same in a simpler fashion?

```
  diff --git a/src/variable.cpp b/src/variable.cpp
  index 1093ce906..67942de5c 100644
  --- a/src/variable.cpp
  +++ b/src/variable.cpp
  @@ -682,10 +682,25 @@ int Variable::next(int narg, char **arg)
         }
         delete random;
   
  -      FILE *fp = fopen("tmp.lammps.variable.lock","r");
  -      fscanf(fp,"%d",&nextindex);
  +      // keep attempting to read until we have a buffer with at
  +      // least 2 bytes read (a single digit and a newline). This
  +      // avoids a segmentation fault if the underlying (networked)
  +      // file system is caching/buffering too aggressively and not
  +      // committing writes immediately.
  +
  +      FILE *fp;
  +      while(1) {
  +        char buf[64];
  +        buf[0] = '\0';
  +        fp = fopen("tmp.lammps.variable.lock","r");
  +        fread(buf,1,64,fp);
  +        fclose(fp);
  +        if (strlen(buf) > 0) {
  +          nextindex = atoi(buf);
  +          break;
  +        }
  +      }
         //printf("READ %d %d\n",universe->me,nextindex);
  -      fclose(fp);
         fp = fopen("tmp.lammps.variable.lock","w");
         fprintf(fp,"%d\n",nextindex+1);
         //printf("WRITE %d %d\n",universe->me,nextindex+1);
```

**Comment by schmidf** [comment]
Thank you for the patch! In my first tests I still observed some segmentation faults, now in `fread()` instead of `fscanf()`.

I now believe that the issue is that `fopen()` sometimes fails and returns a Null pointer. Maybe checking the return value and retrying in case of failure would already be enough. I still don't understand the origin of the empty `tmp.lammps.variable.lock` files though.

Unfortunately I cannot reproduce the error at the moment. Most likely the probability of `fopen()` failing strongly depends on the conditions of the storage cluster. If it shows up again in the future, I can do more testing.

**Comment by akohlmey** [comment]
@schmidf the empty files can happen due to the distributed nature of GPFS and various caching features. The only way to cleanly solve these race conditions would be to "sacrifice" one MPI rank and have that rank be responsible for handing out the next loop value.

The non-existing file is a different variant of the race condition, in this case, two MPI ranks have attempted to rename the file at the same time and one has already updated its content and renamed it back, before the other can read it. in that case, it would be indeed better to start over.
Here is a different modification that will implement this. i have kept the check for the size of the read, but not loop, as that has the potential to have one partition get stuck, so instead i am adding an exit with an error message. so at least there should now be a controlled error with a recognizable error message instead of a generic segmentation fault.

```
diff --git a/src/variable.cpp b/src/variable.cpp
index 1093ce906..e3e3dfa2d 100644
--- a/src/variable.cpp
+++ b/src/variable.cpp
@@ -661,6 +661,8 @@ int Variable::next(int narg, char **arg)
 
   } else if (istyle == UNIVERSE || istyle == ULOOP) {
 
+    uloop_again:
+
     // wait until lock file can be created and owned by proc 0 of this world
     // rename() is not atomic in practice, but no known simple fix
     //   means multiple procs can read/write file at the same time (bad!)
@@ -682,10 +684,26 @@ int Variable::next(int narg, char **arg)
       }
       delete random;
 
-      FILE *fp = fopen("tmp.lammps.variable.lock","r");
-      fscanf(fp,"%d",&nextindex);
-      //printf("READ %d %d\n",universe->me,nextindex);
+      // if the file cannot be found, we may have a race with some
+      // other MPI rank that has called rename at the same time
+      // and we have to start over.
+
+      FILE *fp;
+      fp = fopen("tmp.lammps.variable.lock","r");
+      if (fp == NULL) goto uloop_again;
+
+      char buf[64];
+      buf[0] = '\0';
+      fread(buf,1,64,fp);
       fclose(fp);
+      if (strlen(buf) > 0) {
+        nextindex = atoi(buf);
+      } else {
+        error->one(FLERR,"Unexpected error while incrementing uloop "
+                   "style variable. Please contact LAMMPS developers.");
+      }
+
+      //printf("READ %d %d\n",universe->me,nextindex);
       fp = fopen("tmp.lammps.variable.lock","w");
       fprintf(fp,"%d\n",nextindex+1);
       //printf("WRITE %d %d\n",universe->me,nextindex+1);
```

**Comment by schmidf** [comment]
Today I was able to reproduce the segmentation fault again. After applying your patch, there were no more segmentation faults, but the exit with error gets triggered occasionally.

How about retrying at least a few times? Having a useful error message is nice, but the simulation still fails.

**Comment by akohlmey** [comment]
Thanks for the feedback. Below is a version of the patch combining the two strategies as suggested with a limit to avoid a deadlock.
For debugging it might also be helpful to uncomment the two "printf()" statements, so that you can verify on the screen output, that no instance is run multiple times.

```
diff --git a/src/variable.cpp b/src/variable.cpp
index 1093ce906..0fc53f807 100644
--- a/src/variable.cpp
+++ b/src/variable.cpp
@@ -661,6 +661,8 @@ int Variable::next(int narg, char **arg)
 
   } else if (istyle == UNIVERSE || istyle == ULOOP) {
 
+    uloop_again:
+
     // wait until lock file can be created and owned by proc 0 of this world
     // rename() is not atomic in practice, but no known simple fix
     //   means multiple procs can read/write file at the same time (bad!)
@@ -669,7 +671,7 @@ int Variable::next(int narg, char **arg)
     // delay for random fraction of 1 second before subsequent tries
     // when successful, read next available index and Bcast it within my world
 
-    int nextindex;
+    int nextindex = -1;
     if (me == 0) {
       int seed = 12345 + universe->me + which[find(arg[0])];
       RanMars *random = new RanMars(lmp,seed);
@@ -682,10 +684,33 @@ int Variable::next(int narg, char **arg)
       }
       delete random;
 
-      FILE *fp = fopen("tmp.lammps.variable.lock","r");
-      fscanf(fp,"%d",&nextindex);
+      // if the file cannot be found, we may have a race with some
+      // other MPI rank that has called rename at the same time
+      // and we have to start over.
+      // if the read is short (we need at least one byte) we try reading again.
+
+      FILE *fp;
+      char buf[64];
+      for (int loopmax = 0; loopmax < 100; ++loopmax) {
+        fp = fopen("tmp.lammps.variable.lock","r");
+        if (fp == NULL) goto uloop_again;
+
+        buf[0] = buf[1] = '\0';
+        fread(buf,1,64,fp);
+        fclose(fp);
+
+        if (strlen(buf) > 0) {
+           nextindex = atoi(buf);
+           break;
+        }
+        delay = (int) (1000000*random->uniform());
+        usleep(delay);
+      }
+      if (nextindex < 0)
+        error->one(FLERR,"Unexpected error while incrementing uloop "
+                   "style variable. Please contact LAMMPS developers.");
+
       //printf("READ %d %d\n",universe->me,nextindex);
-      fclose(fp);
       fp = fopen("tmp.lammps.variable.lock","w");
       fprintf(fp,"%d\n",nextindex+1);
       //printf("WRITE %d %d\n",universe->me,nextindex+1);
```

**Comment by schmidf** [comment]
Thank you for the patch. Now the simulations finish successfully.
However, I now see some duplicate (or more) runs:
```
READ 83 345
READ 84 345
WRITE 84 346
WRITE 83 346
Increment via next: value 346 on partition 84
Increment via next: value 346 on partition 83
```

**Comment by akohlmey** [comment]
> Thank you for the patch. Now the simulations finish successfully.
> However, I now see some duplicate (or more) runs:

Yes, this is not unexpected. That is why I asked you to comment out those lines. Due to GPFS's asynchronous I/O optimizations we cannot avoid the race, only avoid crashes. At least we have now the confirmation that the latest patch bypasses any segfaults and thus should be added.  Will have to discuss with @sjplimp possible alternatives.

Thanks again for trying this out and providing helpful feedback.

> 
> ```
> READ 83 345
> READ 84 345
> WRITE 84 346
> WRITE 83 346
> Increment via next: value 346 on partition 84
> Increment via next: value 346 on partition 83
> ```
