### ISSUE TITLE
[BUG] Erronious equation in documentation of the force 2-norm in min_modify

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#1959]
**Summary**

The equation for the 2-norm of the global force vector is shown as the length of the sum of per-particle force vectors, when it should be the square-root of the sum of the squared 2-norms of each per-particle vector.

**LAMMPS Version and Platform**

19 Mar 2020

**Expected Behavior**

||F|| = sqrt( ||F_1||^2 + ||F_2||^2 + ||F_3||^2 + ...  )

**Actual Behavior**

||F|| = sqrt( F_1 + F_2 + F_3 + ...  )

**Link**

https://lammps.sandia.gov/doc/min_modify.html

**Comment by akohlmey** [comment]
@julient31 can you comment on this?
When converting from external tex file to embedded math, the latex code remained unchanged it seems to added those files in commit 56e1a05287c34188eca387dfee62b935434096fd

**Comment by julient31** [comment]
@akohlmey Hey Axel! Hope you're doing well!
Indeed, the definition in the doc does not correspond to the 2-norm (which is what is implemented). 
I also think there is a small issue with the INF norm in the code. I'll check that more carefully tomorrow.
How would you like me to proceed? Encapsulate those corrections in another PR? Or create one just for them?

**Comment by akohlmey** [comment]
> How would you like me to proceed? Encapsulate those corrections in another PR? Or create one just for them?

Just add the documentation changes to whatever else you submit. Unless there is a significant rewrite of the documentation, we do not consider it as major a change as changes to the code. I've been rather liberally tacking on doc changes to whatever other changes were ready (and so does and did steve).

**Comment by julient31** [comment]
Sounds good, I'll do that. Thanks a lot Axel!

**Comment by akohlmey** [comment]
corrected in #1967
