### ISSUE TITLE
[BUG] Building USER-VTK with Intel compiler

### ISSUE THREAD

**Issue by ocaisa** [lammps/lammps#1964]
**Summary**

As part of https://github.com/easybuilders/easybuild-easyconfigs/pull/10191 I'm building LAMMPS with `USER-VTK` on top of the Intel 2020 and GCC 9 compilers. GCC compiled fine but the Intel version errors out with
```
/work/maintainers/CO7/broadwell/software/impi/2019.6.166-iccifort-2020.0.166/intel64/bin/mpiifort: eval: line 709: syntax error near unexpected token `('
/work/maintainers/CO7/broadwell/software/impi/2019.6.166-iccifort-2020.0.166/intel64/bin/mpiifort: eval: line 709: `ifort -DFFT_MKL -DFFT_MKL_THREADS -DLAMMPS_FFMPEG -DLAMMPS_GZIP -DLAMMPS_JPEG -DLAMMPS_MEMALIGN=64 -DLAMMPS_PNG -DLAMMPS_SMALLBIG -DLAMMPS_VTK -DLMP_HAS_NETCDF -DLMP_INTEL_USELRT -DLMP_KIM_CURL -DLMP_KOKKOS -DLMP_MPIIO -DLMP_PYTHON -DLMP_USER_INTEL -DLMP_USER_OMP -DLMP_USE_MKL_RNG -DNC_64BIT_DATA=0x0020 -D__PLUMED_WRAPPER_CXX=1 -DvtkDomainsChemistry_AUTOINIT=2(vtkDomainsChemistryOpenGL2,vtkDomainsParallelChemistry) -DvtkFiltersCore_AUTOINIT=1(vtkFiltersParallelDIY2) -DvtkFiltersParallel_AUTOINIT=2(vtkFiltersParallelDIY2,vtkFiltersParallelGeometry) -DvtkIOExport_AUTOINIT=2(vtkIOExportOpenGL2,vtkIOExportPDF) -DvtkIOGeometry_AUTOINIT=1(vtkIOMPIParallel) -DvtkIOImage_AUTOINIT=1(vtkIOMPIImage) -DvtkIOParallel_AUTOINIT=1(vtkIOMPIParallel) -DvtkRenderingContext2D_AUTOINIT=1(vtkRenderingContextOpenGL2) -DvtkRenderingCore_AUTOINIT=3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2) -DvtkRenderingOpenGL2_AUTOINIT=1(vtkRenderingGL2PSOpenGL2) -DvtkRenderingVolume_AUTOINIT=1(vtkRenderingVolumeOpenGL2) -...
```
The equivalent commands with GCC quote things like
```-DvtkRenderingVolume_AUTOINIT="1(vtkRenderingVolumeOpenGL2"```
so there seems to be some inconsistency between the two build

**LAMMPS Version and Platform**

3Mar2020 on Broadwell

**Expected Behavior**

Successful build similar to GCC version

**Actual Behavior**

Compilation failure due to syntax error

**Steps to Reproduce**

Build with Intel compiler and `USER-VTK`

**Further Information, Files, and Links**

https://github.com/easybuilders/easybuild-easyconfigs/pull/10191

**Comment by akohlmey** [comment]
I don't think that this is due to LAMMPS. This looks like an issue in the `mpiifort` compiler wrapper. You don't say explicitly, but it looks like your are using the CMake build variant and there we simply import the VTK build options from its CMake file, so there is nothing in LAMMPS that changes the quotes.

**Comment by ocaisa** [comment]
Ok, thanks, also seems not to be a new problem:
https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/746611
