### ISSUE TITLE
[Feature Request] Simplify build options by always building the LAMMPS library

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1977]
**Summary**

Right now we have essentially 4 main build options:
- build executable from "static" objects (= no -fpic)
- build executable from "shared" objects (= with -fpic)
- build a static library
- build a shared library

I propose to reduce this to two options: always build the executable and the library, and only select between a shared library and a static library.

For CMake that means to get rid of the `BUILD_EXE` and `BUILD_LIB` options and only switch between `BUILD_SHARED_LIBS` set to **on** or **off**

For the traditional make, this would correspond to replace "mode=exe", "mode=shexe", "mode=lib", "mode=shlib" with "mode=static" and "mode=shared" (and for backward compatibility map "exe" and "lib" to "static" and "shexe" and "shlib" to "shared"). The default would be "static" so the result would be essentially the same except for creating the library in addition.

P.S.: anybody know why `BUILD_SHARED_LIBS` is plural? we only build one library and we enable it with `BUILD_LIB` (not `BUILD_LIBS`), which feels inconsistent.

**Comment by rbberger** [comment]
`BUILD_SHARED_LIBS` is a CMake variable (https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html). The other ones were introduced by us.

**Comment by junghans** [comment]
Sure, I am all for dropping `BUILD_EXE` and `BUILD_LIB` as it would make the lammps CMake more standard.

**Comment by sjplimp** [comment]
@akohlmey In the proposed change, if a static (default) build is done, does
that mean you get two files: an exe and a lib?  How large are those files?
In the old way, you get just the exe and it is the same file as before?

**Comment by akohlmey** [comment]
> @akohlmey In the proposed change, if a static (default) build is done, does
> that mean you get two files: an exe and a lib? How large are those files?
> In the old way, you get just the exe and it is the same file as before?

For the conventional build you get the library and the executable and the library file will be larger because of the additional information stored in it for the linker unless a lot of libraries from lib folder are also linked into the executable.  Here is an example i used for testing:
```
make no-all
make lib-poems args="-m mpi"
make yes-poems
make mpi
$ du -sh Obj_mpi
76M	Obj_mpi
$ ll -h liblammps_mpi.a lmp_mpi 
-rw-r--r-- 1 akohlmey klein 76M Apr  9 11:55 liblammps_mpi.a
-rwxr-xr-x 1 akohlmey klein 31M Apr  9 11:55 lmp_mpi
```
With `mode=shared` you get:
```
$ du -sh Obj_shared_mpi
74M	Obj_shared_mpi
$ ll -h lmp_mpi liblammps_mpi.so 
-rwxr-xr-x 1 akohlmey klein 31M Apr  9 12:03 liblammps_mpi.so
-rwxr-xr-x 1 akohlmey klein 47K Apr  9 12:03 lmp_mpi
```
Since we depend on GNU make, it would technically be possible save the storage space for the object files files, since GNU make may use dependencies from inside a static library file, but that would complicate the process and require more changes. I am trying to keep the changes to the makefiles minimal and platform independent.

As noted in our discussion last friday, we have done worse to the source code distribution itself and have not seen any remarks about this outside of issue #1839 .
```
$ ll -h ../potentials/C_10_10.mesocnt 
-rw-r--r-- 1 akohlmey klein 83M Apr  7 16:21 ../potentials/C_10_10.mesocnt
```

**Comment by sjplimp** [comment]
Thanks for the info - to clarify, the 31M lmp_mpi in the new mode
is an identical file to the lmp_mpi exe in the old mode?
Also, the new mode just takes incrementally longer to build
both, not 2x longer, correct?  What does 76M extra for the lib
grow to if you include most packages?

I think 99% of folks probably just want the exe.
So making the 1% type an extra command to also get the lib
file doesn't seem like a problem. 
But I can also see the argument for simplicity.
Is it easy to have an option to disable the lib creation
if people don't want it?

**Comment by akohlmey** [comment]
> Thanks for the info - to clarify, the 31M lmp_mpi in the new mode
> is an identical file to the lmp_mpi exe in the old mode?
> Also, the new mode just takes incrementally longer to build
> both, not 2x longer, correct? What does 76M extra for the lib
> grow to if you include most packages?

here are the sizes:
```
$ ll -h liblammps*.a lmp_mpi
lrwxrwxrwx 1 akohlmey klein   15 Apr  9 13:29 liblammps.a -> liblammps_mpi.a
-rw-r--r-- 1 akohlmey klein 396M Apr  9 13:20 liblammps_mpi.a
-rwxr-xr-x 1 akohlmey klein 380M Apr  9 13:29 lmp_mpi
```
Installed packages:
```
ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE GRANULAR KSPACE LATTE 
MANYBODY MC MESSAGE MISC MOLECULE MPIIO MSCG OPT PERI POEMS PYTHON QEQ REPLICA 
RIGID SHOCK SNAP SPIN SRD VORONOI USER-ATC USER-AWPMD USER-BOCS USER-CGDNA 
USER-CGSDK USER-COLVARS USER-DIFFRACTION USER-DPD USER-DRUDE USER-EFF USER-FEP 
USER-H5MD USER-INTEL USER-LB USER-MANIFOLD USER-MEAMC USER-MESODPD USER-MGPT 
USER-MISC USER-MOFFF USER-MOLFILE USER-NETCDF USER-OMP USER-PHONON USER-PLUMED 
USER-PTM USER-QTB USER-REACTION USER-REAXC USER-SCAFACOS USER-SMD USER-SMTBQ 
USER-SDPD USER-SPH USER-TALLY USER-UEF USER-YAFF 
```
> 
> I think 99% of folks probably just want the exe.
> So making the 1% type an extra command to also get the lib
> file doesn't seem like a problem.

I see the logic differently: Will the people that want the executable care about the extra storage used? ...and if that is a concern, then there is **much** more savings potential in dropping the '-g' flag. As it will reduce the storage needed by a factor of 5 and for "everything": the executable, the library, **and** the object files:
```
$ strip lmp_mpi 
$ ll -h lmp_mpi
-rwxr-xr-x 1 akohlmey klein 72M Apr  9 13:34 lmp_mpi
```
> But I can also see the argument for simplicity.
> Is it easy to have an option to disable the lib creation
> if people don't want it?

No. The changed build procedure builds a library first and then compiles main.cpp and links that object against the library. This has a (IMO desired) side effect, that executing "make mpi" will always relink the executable. So if somebody updates a library and recompiles it, now "make mpi" will include it instead of stating that 'lmp_mpi' is up to date and thus you are no longer forced to first delete the executable if you want to relink. For the example above doing "make mpi" a second time does this:
```
$ make mpi
Gathering installed package information (may take a little while)
make[1]: Entering directory '/home/akohlmey/compile/lammps/src'
Gathering git version information
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src'
Compiling LAMMPS for machine mpi
make[1]: Entering directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
make[1]: Entering directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
mpicxx -g -O3 main.o -L../../lib/voronoi/liblink -L../../lib/scafacos/liblink -L../../lib/h5md -L../../lib/colvars -L../../lib/awpmd -L../../lib/atc -L../../lib/poems -L../../lib/mscg/liblink -L../../lib/message/cslib/src -L../../lib/latte/liblink            -L../../lib/linalg -L../../lib/linalg    -L../../lib/linalg -fopenmp   liblammps_mpi.a -lvoro++ `grep Libs: ../../lib/scafacos/liblink/pkgconfig/scafacos.pc | cut -d " " -f 2-` -lch5md -lcolvars -lawpmd -latc -lpoems -lmscg -lmessage       "/home/akohlmey/compile/lammps/lib/plumed/plumed2/lib/libplumed.a" -ldl  -lstdc++ -lfftw3 -lgsl -lgslcblas -lz -ldl -llapack -lblas   -rdynamic -Wl,-Bsymbolic -fopenmp   -L/usr/lib64/openmpi/lib -lnetcdf -ldl -lhdf5  -llinalg -lgfortran -llinalg -lgfortran  -L/usr/lib64 -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -lm -lgsl -llapack -lgslcblas -lzmq ../../lib/latte/filelink.o -llatte -llinalg -lgfortran -lz   -o ../lmp_mpi
size ../lmp_mpi
   text	   data	    bss	    dec	    hex	filename
73920162	1084080	23259464	98263706	5db629a	../lmp_mpi
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
```

**Comment by sjplimp** [comment]
@akohlmey can you answer my first Q in the previous message
about identical files (not ballpark size, bitwise identical).

Also, to your last point, you're saying "make mpi" in the new mode will
always re-link to create a new exe, whether anything has changed or not?
If so, I don't think that's good feedback for users.  Someone doing development will think
some source file must have changed, and have to scroll up thru the long
link output to see that nothing was recompiled.  Are you saying cmake
does not treat any of the pulled in libs as dependencies and re-link
only if there is a need to?   I think that is true for make.
Or are you talking just about liblammps, not other libs?

**Comment by sjplimp** [comment]
@akohlmey Or maybe you are saying it is only the lib build that will
now have the screenfuls of *.o files listed, and the exe build
will always be brief, whether anything has changed or not?

**Comment by akohlmey** [comment]
> @akohlmey can you answer my first Q in the previous message
> about identical files (not ballpark size, bitwise identical).

yes. it is bitwise identical. here is the difference with a small example.
Assume three sources files, foo.cpp, bar.cpp and foobar.cpp.
We previously did:
``` bash
g++ -c -g -O3 foo.cpp
g++ -c -g -O3 bar.cpp
g++ -c -g -O3 foobar.cpp
g++ -o foobar.x foobar.o foo.o bar.o
```
Now we do:
```
g++ -c -g -O3 foo.cpp
g++ -c -g -O3 bar.cpp
ar cr libfoobar.a foo.o bar.o
g++ -c -g -O3 foobar.cpp
g++ -o foobar.x foobar.o libfoobar.a
```
This gives me identical executables:
```
$ g++ -o foobar.x foobar.o foo.o bar.o
$ md5sum foobar.x 
ed5b307650f331a899ef250c7b83436f  foobar.x
$ g++ -o foobar.x foobar.o libfoobar.a 
$ md5sum foobar.x 
ed5b307650f331a899ef250c7b83436f  foobar.x
```
> Also, to your last point, you're saying "make mpi" in the new mode will
> always re-link to create a new exe, whether anything has changed or not?
> If so, I don't think that's good feedback for users. Someone doing development will think
> some source file must have changed, and have to scroll up thru the long
> link output to see that nothing was recompiled.

Because of the change described above the link command of the executable is **not** long.
It is clearly visible that nothing has changed and only the executable is relinked, which - as I have argued before - is a desirable change, since the conventional make process does not track dependencies of the libraries in lib and will never trigger a relink. One has to delete the executable first.

The building of the library is long and that is what depends on the sources.
Example:
```
[...] angle_cosine_shift_exp.o fix_qeq_point.o info.o pair_lcbop.o angle_quartic_omp.o fix_gravity.o pair_eff_cut.o pair_reaxc.o compute_reduce_chunk.o compute_temp_partial.o fix_qeq_comb_omp.o pair_lj_charmm_coul_long_soft.o compute_property_local.o ptm_polar.o pair_srp.o fix_nve_dotc_langevin.o improper.o fix_lb_momentum.o npair_half_size_nsq_newtoff_omp.o reaxc_lookup.o pair_lj_cut_thole_long.o nstencil_full_multi_3d.o fix_poems.o fix_atom_swap.o npair_half_size_bin_newton_omp.o pair_dpd_tstat.o bond_fene_omp.o pair_tersoff_mod_omp.o compute_temp_body.o dihedral_multi_harmonic_omp.o npair_half_multi_newtoff_omp.o compute_edpd_temp_atom.o compute_angle.o pppm_cg_omp.o ewald_dipole_spin.o fix_mvv_edpd.o pair_coul_diel_omp.o compute_pe_atom.o pair_zbl.o npair_skip_size_off2on.o pair_buck_omp.o min_hftn.o fix_wall_srd.o fix_nvt_asphere_omp.o pair_born_coul_msm_omp.o fix_qeq_comb.o compute_deprecated.o ptm_initialize_data.o dihedral_cosine_shift_exp_omp.o fix_nh_omp.o dihedral_multi_harmonic.o atom_vec_edpd.o angle_cosine_shift_exp_omp.o pair_buck6d_coul_gauss_long.o npair_skip_respa.o pair_lj_long_coul_long.o angle_cosine_delta_omp.o pair_rebo_intel.o fix_cmap.o pair_coul_msm_omp.o pair_comb.o npair_half_size_nsq_newton.o compute_pressure_grem.o pair_buck_coul_msm_omp.o dump_image.o npair_half_size_bin_newton.o pair_born_coul_wolf_cs.o compute_fep.o fix_ttm_mod.o npair_half_bin_newton_tri_omp.o compute_temp.o pair_tdpd.o compute_pressure.o pair_lj_cut_coul_long_cs.o npair_half_multi_newtoff.o dihedral_table_omp.o fix_ttm.o bond_morse.o
mpicxx -g -O3 main.o -L../../lib/voronoi/liblink -L../../lib/h5md -L../../lib/colvars -L../../lib/awpmd -L../../lib/atc -L../../lib/poems -L../../lib/message/cslib/src            -L../../lib/linalg -L../../lib/linalg     -L. -llammps_mpi -lvoro++ -lch5md -lcolvars -lawpmd -latc -lpoems -lmessage       "/home/akohlmey/compile/lammps/lib/plumed/plumed2/lib/libplumed.a" -ldl  -lstdc++ -lfftw3 -lgsl -lgslcblas -lz -ldl -llapack -lblas   -rdynamic -Wl,-Bsymbolic -fopenmp   -L/usr/lib64/openmpi/lib -lnetcdf -ldl -lhdf5  -llinalg -lgfortran -llinalg -lgfortran  -L/usr/lib64 -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -lzmq -lz   -o ../lmp_mpi
size ../lmp_mpi
   text	   data	    bss	    dec	    hex	filename
39886594	1037752	  54128	40978474	271482a	../lmp_mpi
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src/Obj_mpi'

$ make mpi

Gathering installed package information (may take a little while)
make[1]: Entering directory '/home/akohlmey/compile/lammps/src'
Gathering git version information
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src'
Compiling LAMMPS for machine mpi
make[1]: Entering directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
make[1]: Entering directory '/home/akohlmey/compile/lammps/src/Obj_mpi'
mpicxx -g -O3 main.o -L../../lib/voronoi/liblink -L../../lib/h5md -L../../lib/colvars -L../../lib/awpmd -L../../lib/atc -L../../lib/poems -L../../lib/message/cslib/src            -L../../lib/linalg -L../../lib/linalg     -L. -llammps_mpi -lvoro++ -lch5md -lcolvars -lawpmd -latc -lpoems -lmessage       "/home/akohlmey/compile/lammps/lib/plumed/plumed2/lib/libplumed.a" -ldl  -lstdc++ -lfftw3 -lgsl -lgslcblas -lz -ldl -llapack -lblas   -rdynamic -Wl,-Bsymbolic -fopenmp   -L/usr/lib64/openmpi/lib -lnetcdf -ldl -lhdf5  -llinalg -lgfortran -llinalg -lgfortran  -L/usr/lib64 -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -lzmq -lz   -o ../lmp_mpi
size ../lmp_mpi
   text	   data	    bss	    dec	    hex	filename
39886594	1037752	  54128	40978474	271482a	../lmp_mpi
make[1]: Leaving directory '/home/akohlmey/compile/lammps/src/Obj_mpi'

> Are you saying cmake
> does not treat any of the pulled in libs as dependencies and re-link
> only if there is a need to? I think that is true for make.

No. See my comments above above. You can try it for yourself. Here is an example: build LAMMPS with the GPU package and then rebuild the GPU library after switching from mixed to double precision. If you then type "make mpi" it will not relink even though it should. This has been annoying me personally quite a bit.  Please note, I did not plan on making this change it just so happened as a side effect of the two step build/link approach from trying to keep the changes to the makefiles and overall minimal. When considering how to get the previous behavior back, I concluded that the new behavior is ultimately preferable, especially since it **is** visually quite obvious that no compilation of sources has happened.  The fact that you can tell the difference whether sources in src are recompiled or not was a major contributing factor in this decision.

The CMake build is conceptually different. It tracks *all* libraries (even the downloaded ones), handles dependencies differently and even tracks changes to the compiler/linker flags and will retrigger the CMake configuration run and all necessary rebuilds and links. If anything, it is a bit too cautious.  Since the cmake program itself is adapted to the local machine and OS, it has many more options to do sophisticated processing.  The challenge is then to write the CMake scripting so that it actually is platform independent. With traditional makefiles you are limited to the lowest common denominator of system tools.

**Comment by akohlmey** [comment]
> @akohlmey Or maybe you are saying it is only the lib build that will
> now have the screenfuls of *.o files listed, and the exe build
> will always be brief, whether anything has changed or not?

Exactly. Please see my other reply and the screen outputs in it.

**Comment by akohlmey** [comment]
@sjplimp pull request #1985 is now complete as far as I can tell.
