### ISSUE TITLE
[BUG] _write_coeff in lj/long

### ISSUE THREAD

**Issue by SaraMosalla** [lammps/lammps#1982]
**Summary**

The parameters in write_coeff at the end of the data file using pair_style lj/long/coul/long and lj/long/tip4p/long is completely wrong.

I am using  
**LAMMPS (12 Dec 2018)**

I got the attached coefficients.  I specified the numbers in bold in my data file and the rest are calculated by mix geometric.

![Bug](https://user-images.githubusercontent.com/48093480/78852484-05691800-7a4f-11ea-9479-7c09f7c8efcd.JPG)

**Comment by akohlmey** [comment]
@SaraMosalla thanks for reporting this issue. a fix will be submitted soon and should be available in the next LAMMPS patch release.
