### ISSUE TITLE
folder examples/accelerate needs updating or should be removed

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#1984]
**Summary**

The outputs in the `examples/accelerate` folder are over 6 years old and the instructions outdated.
Same about the corresponding pieces of the documentation in `doc/src/Speed_packages.rst`

**LAMMPS Version and Platform**

LAMMPS 19 March 2020

**Details**

The files and documentation should be updated and tested with the latest version, especially *after* the already merged and still pending changes to the build process. So about a month or so before the next stable release seems a good target date to implement this.

**Comment by sjplimp** [comment]
@akohlmey agree with this

**Comment by akohlmey** [comment]
@sjplimp @stanmoore1 @rbberger @athomps this is also now becoming an urgent matter with the upcoming stable release.
