### ISSUE TITLE
[BUG] bug in coul/long potential calculation

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [lammps/lammps#1987]
**Summary**

The elong in coul/long cause a shift in Coulombic potential

**LAMMPS Version and Platform**

Patch release 19 March 2020

**Actual Behavior**
For both images, the black curve is the theoretical potential 1/r, and the red curve is the total potential in a simulation box constituted with two particles with a same +1 charge. The total potential is measured from thermo_style etotal and 2*etotal is the expected total potential.

![potential](https://user-images.githubusercontent.com/40440788/78962317-fec7b880-7ac1-11ea-84f0-810a9645a6bd.png)
First image is the coul/cut potential, the total potential in the simulation box matches the theoretical 1/r.
![potential coul:long](https://user-images.githubusercontent.com/40440788/78962428-14d57900-7ac2-11ea-92bb-6d93bc218374.png)
Second image is the coul/long potential, the total potential in the simulation box has a shift from the theoretical 1/r, and it is caused by the elong term.
![potential](https://user-images.githubusercontent.com/40440788/78963330-22403280-7ac5-11ea-8e9e-3e2bd7847826.png)
As shown in image 3, If two particles in the simulation box carry opposite charge, elong is correct and the red curve fits the black curve

**Steps to Reproduce**

In files and data file attached

[GM.zip](https://github.com/lammps/lammps/files/4459881/GM.zip)

**Comment by akohlmey** [comment]
I am not so sure, that this is a bug. You are neglecting the fact, that you are looking at an infinitely large sphere built from periodic replica of your system, and a system with only two charges of the same sign will result in divergent term at k=0. This divergent term is ignored and thus your system is modified by being effectively neutralized through a smeared out counter charge, so I would not expect to get an ideal 1/r behavior.
It looks to me that you have proven **why** one should have a neutral system when using long-range electrostatics. LAMMPS will print a warning, if you don't.

**Comment by 2young-2simple-sometimes-naive** [comment]
> I am not so sure, that this is a bug. You are neglecting the fact, that you are looking at an infinitely large sphere built from periodic replica of your system, and a system with only two charges of the same sign will result in divergent term at k=0. This divergent term is ignored and thus your system is modified by being effectively neutralized through a smeared out counter charge, so I would not expect to get an ideal 1/r behavior.
> It looks to me that you have proven **why** one should have a neutral system when using long-range electrostatics. LAMMPS will print a warning, if you don't.

Thanks.
