### ISSUE TITLE
examples/KAPPA/log.heat.1Feb14 & /log.heatflux.1Feb14

### ISSUE THREAD

**Issue by ee10bt** [lammps/lammps#2]
As far as I can tell, these two log files have come from the same calculation, run on separate occasions. I noticed the problem in the header of log.heat, it is supposed to relate to "add/subtract energy to 2 regions via fix heat", not the Green-Kubo method of log.heatflux. As such, the output of running in.heat does not match up with the provided log.heat.

TL;DR, log.heat in examples/KAPPA does not match up with in.heat.

**Comment by junghans** [comment]
Sorry, this a mirror repository, we don't take bug report here, instead please report the issue on lammps' mailing list: lammps-users@lists.sourceforge.net
