### ISSUE TITLE
ERROR: fix rx cannot be combined with fix property/atom

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#2001]
**Summary**

Some of our internal USER-DPD regression tests are failing with `ERROR: fix rx cannot be combined with fix property/atom`. They were working fine before the recent changes.

**LAMMPS Version and Platform**

Latest master

**Comment by akohlmey** [comment]
They were not failing because of a bug in the checking for the conflict.

**Comment by stanmoore1** [comment]
Hmmm, they shouldn't be failing though, so maybe the logic needs to be tweaked. @timattox who should we ping about this?

**Comment by akohlmey** [comment]
please let me use this opportunity to remind folks that the way how USER-DPD uses fix property/atom is rather badly done and can result in all kinds of issues.

**Comment by stanmoore1** [comment]
Many of their test scripts combine `fix rx` with `fix property/atom`. Are you sure *we* didn't mess up the check?

**Comment by akohlmey** [comment]
> Many of their test scripts combine `fix rx` with `fix property/atom`. Are you sure _we_ didn't mess up the check?

why then put in a test and make it so it doesn't work? at the very least it should describe when it is safe to combine it and when not (and then adapt the logic accordingly).

**Comment by akohlmey** [comment]
it also emphasizes that we need to expand the testing on ci.lammps.org to catch these things before we release them.
