### ISSUE TITLE
[BUG] Replicate not copying extra bonds/angles/etc 

### ISSUE THREAD

**Issue by benjamindjensen** [lammps/lammps#2009]
**Summary**

Combination of 3 commands causes an unexpected "Molecule auto special bond generation overflow" error:
 - read_data with extra bonds/angles/etc
 - replicate
-  molecule

**LAMMPS Version and Platform**

LAMMPS (19 Mar 2020)

**Steps to Reproduce**

If you add a "replicate 1 1 2" command immediately after the read_data in the examples/USER/reaction/tiny_nylon/in.tiny_nylon.stabilized, LAMMPS exists with the error: "Molecule auto special bond generation overflow"

**Comment by akohlmey** [comment]
@benjamindjensen thanks for the report. I think I have identified the issue and implemented a fix for this bug. A patch will be coming soon.
