### ISSUE TITLE
[BUG] Gay-Berne pair style does not honour special-bonds in the GPU package

### ISSUE THREAD

**Issue by matteoeghirotta** [lammps/lammps#2017]
**Summary**

Pair style Gay-Berne in the GPU package computes the interactions and updates the relevant accumulators (energy, forces and torques) for connected pairs, even when told not to do so by means of the special_bonds directive.

**LAMMPS Version and Platform**

The problem was detected with LAMMPS version 3 March 2020, running on debian 9 and ubuntu 18.04 Linux, x86_64 architecture.

**Expected Behavior**

The special_bonds command should allow to ignore interactions between bonded particles, by setting one of its parameters to zero. Energies, forces and torques should not be computed between such pairs, or at least result in scalars and vectors with all components set to zero.

**Actual Behavior**

Such interactions are instead computed and correctly result in strongly repulsive forces and torques, given the pair distances.

**Further Information, Files, and Links**

A minimal example for reproducing the bug is attached.
Running with the following command:
lmp_3Mar20-gpu -in ellipsoid_sp.in 
results in a correct energy: evdwl= -5.7673704
Running with the gpu:
lmp_3Mar20-gpu -pk gpu 1 neigh no -sf gpu -in ellipsoid_sp.in
gives a much higher energy: e
[special_bonds.zip](https://github.com/lammps/lammps/files/4520858/special_bonds.zip)

vdwl=80580.483

**Comment by jewettaij** [comment]
Hi Trung.  In case you are curious, Matteo Ricci and Otello Roscioni developed "bond_style ellipsoid" which (as you might have guessed) will allow many people to simulate molecules containing ellipsoids bonded together.  Hopefully many people will use this cool new feature.  

(Thanks again in advance for maintaining LAMMPS code.  We are using fix rigid/small and package GPU in some of our work.  These features are really useful)

**Comment by jewettaij** [comment]
I forgot to include the [link](https://pubs.rsc.org/en/content/articlelanding/2019/cp/c9cp04120f#!divAbstract).

**Comment by ndtrung81** [comment]
@matteoeghirotta thanks for reporting this issue and for sharing the input deck. I can reproduce the issue and will try to resolve it.
@jewettaij thanks for letting me know :-) FYI, fix rigid/small is done by @sjplimp

**Comment by ndtrung81** [comment]
@matteoeghirotta please check out the above PR #2026 to see if the changes resolve the issue you observed. Thanks again for reporting it!

**Comment by matteoeghirotta** [comment]
@ndtrung81 I'm sorry I mistakenly mentioned the command:
lmp_3Mar20-gpu -pk gpu 1 neigh **no** -sf gpu -in ellipsoid_sp.in
above, it should instead have been
lmp_3Mar20-gpu -pk gpu 1 neigh **yes** -sf gpu -in ellipsoid_sp.in

In fact, the first command produce correct results, while the second results in high energies.
In other words, it seems the problem is related to having the neighbor list computed on the gpu, while no problem arises when the list is kept in the cpu (neigh no).
I'm sorry for my mistake..let me know if I should reformulate the issue opening a new one, and close you PR, which does not seem to solve the issue for the case of neighbor list on the gpu (neigh yes).

**Comment by matteoeghirotta** [comment]
@ndtrung81 , sorry for the mess I made, your modifications indeed fixes the issue for the on gpu neighbor list
