### ISSUE TITLE
[BUG] CMAKE v3.10 compatibility

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#2029]
**Summary**

There are bugs/issues with CMAKE v3.10 that the recent updates to the LAMMPS cmake build system do not account for.  If v3.10 compatibility is really desired, fixes and testing with cmake 3.10 should be performed.

**LAMMPS Version and Platform**

Tested with current master (72ff0dd) and CMAKE v3.10.3 on both openSUSE leap and macOS.

**Expected Behavior**

`cmake -DPKG_KIM=ON ../cmake`

completes successfully

**Actual Behavior**

```
.
.
.
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:
-- <<< MPI flags >>>
-- MPI includes:     /usr/local/Cellar/open-mpi/4.0.3/include
-- MPI libraries:    /usr/local/Cellar/open-mpi/4.0.3/lib/libmpi.dylib;
-- Configuring done
CMake Error at CMakeLists.txt:102 (add_library):
  Target "lammps" links to target "CURL::libcurl" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:103 (add_executable):
  Target "lmp" links to target "CURL::libcurl" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:103 (add_executable):
  Target "lmp" links to target "CURL::libcurl" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:102 (add_library):
  Target "lammps" links to target "CURL::libcurl" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: .../lammps/build
```

**Steps to Reproduce**

have cmake version 3.10.3 installed

**Comment by ellio167** [comment]
@junghans There are probably other interactions that may cause trouble.  I guess I should have tested the previous PR more fully, myself; sorry.   

We're also seeing these behaviors:

- If you do `-DPKG_KIM=on -DPKG_KOKKOS=on`, it will fail:

```
-- The project name is: Kokkos
CMake Error at /.../lammps/lib/kokkos/cmake/kokkos_test_cxx_std.cmake:74 (MESSAGE):
 Kokkos requires C++11 or newer!
```

I think this is probably caused by the various settings that are performed by the kim-api cmake config file.  This file was designed to be used with the KIM model codes.  It might not be fully appropriate for other codes (like LAMMPS) to use.  However, I'm certainly open to making changes in the kim-api package to support the sort of config usage that is being attempted here...

**Comment by junghans** [comment]
Re: `CURL::libcurl`, it seems that got added in cmake-3.12, so I will add a workaround.

Re: the `CMAKE_CXX_STANDARD` I guess the problem is that it is set in kim-api's config file (https://github.com/openkim/kim-api/blob/master/cmake/config.cmake.in#L94), which is bad.

So we should just revert #2018.

**Comment by junghans** [comment]
@ellio167 can you test #2030? I added a fix for the missing `CURL::libcurl` as well.
