### ISSUE TITLE
[BUG] USER-MESODPD rename potentially incomplete

### ISSUE THREAD

**Issue by pranjal-s** [lammps/lammps#2038]
**Summary**

The rename of the USER-MESO package to USER-MESODPD (at https://github.com/lammps/lammps/pull/1924) is potentially incomplete.

**LAMMPS Version and Platform**

LAMMPS Version: LAMMPS (3 Mar 2020)
Platform: Linux
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago

**Expected Behavior**

Should be able to use the atom_style mdpd.

**Actual Behavior**

ERROR: Unrecognized atom style 'mdpd' is part of the USER-MESO package which is not enabled in this LAMMPS binary. (src/atom.cpp:511)
Last command: atom_style	        mdpd

**Steps to Reproduce**
Make LAMMPS using:
git clone -b stable https://github.com/lammps/lammps.git mylammps
cd mylammps
mkdir build; cd build
module purge
module load gcc/5.3.1
module load openmpi
cmake -D PKG_MOLECULE=yes -D PKG_ASPHERE=yes -D PKG_MISC=yes -D PKG_USER-DPD=yes -D PKG_USER-MESODPD=yes ../cmake -DBUILD_MPI=yes -DLAMMPS_MACHINE=mylammps
make -j16

Run example input file (at https://github.com/lammps/lammps/tree/master/examples/USER/mesodpd/mdpd) using:
lmp_mylammps < in.mdpd

**Comment by akohlmey** [comment]
The error message is correct and your compilation steps are incorrect for the version of LAMMPS you are compiling. The rename of the package was done **after** the release of the 3 March 2020 (stable) version, so you must request the USER-MESO package as indicated. https://github.com/lammps/lammps/releases/tag/patch_19Mar2020
