### ISSUE TITLE
[Feature Request] Add support for Atomistica

### ISSUE THREAD

**Issue by Flamefire** [lammps/lammps#2039]
**Summary**

The CMakeLists should provide support for Atomistica. This requires only 2 changes:
- Linking `libatomistica` to the `lmp` or `lammps` target
- Setting the linker language to fortran

Alternatively: Provide an imported target (best via a FindAtomistica.cmake) for the atomisitice library which has the language set to Fortran and hope that CMake chooses that over the C++ linker (not 100% it does, can verify if wanted)

**Detailed Description**

Getting Atomistica into lammps is currently hard:
- Copy some source files into lammps tree
- Patch CMakeLists to include the library and the linker language.

With a simple `option` called e.g. `ENABLE_ATOMISTICA` doing those steps it would be a lot easier.

**Further Information, Files, and Links**

https://github.com/Atomistica/atomistica/blob/master/doc/install.lammps.md

**Comment by akohlmey** [comment]
Sorry, but you are barking up the wrong tree here. The burden to provide a suitable integration into LAMMPS is the job of the developers of Atomistica. There are numerous examples of directly supported interfaces to "external" packages, e.g  KIM, QUIP, LATTE, USER-PLUMED, USER-SCAFACOS etc. which have only the code required to integrate the external library into LAMMPS included in LAMMPS as a packages. We'll be more than happy to include a submission from the Atomistica developers in a similar vain.
