### ISSUE TITLE
[BUG] ERROR: Insufficient memory on accelerator (src/GPU/gpu_extra.h:38) melt 20 million atoms

### ISSUE THREAD

**Issue by djygithub** [lammps/lammps#2040]
**Summary**

Similar but older issue from mailing list https://sourceforge.net/p/lammps/mailman/message/31967475/

Memory failures on V100/32GB for lammps 20 million atom test, also started failing for 10 million atoms. This is peculiar; the 20 million atom test worked successfully twice, then started to fail. Cold reboot, resetting the V100 does not clear up the issue, building with make versus cmake same issue, backed up a couple of branches, (19 Mar 2020, 19 Jul 2019) same issue, tried using MPS same issue, tried a different machine with different V100s same issue notice also the ‘31/32 GB’ in the V100 output :

**LAMMPS Version and Platform**

LAMMPS (19 Mar 2020), LAMMPS (19 Jul 2019)
SYS-4029GP-TRT2 5.3.0-46-generic #38~18.04.1-Ubuntu
Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
[in.20m.melt.txt](https://github.com/lammps/lammps/files/4547022/in.20m.melt.txt)

**Expected Behavior**
``` LAMMPS (19 Mar 2020)
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (839.798 167.96 167.96)
  1 by 1 by 1 MPI processor grid
Created 20000000 atoms
  create_atoms CPU = 1.08766 secs

--------------------------------------------------------------------------
- Using acceleration for lj/cut:
-  with 1 proc(s) per device.
--------------------------------------------------------------------------
Device 0: Vega 20, 64 CUs, 32/32 GB, 1.8 GHZ (Double Precision)
--------------------------------------------------------------------------

Initializing Device and compiling on process 0...Done.
Initializing Device 0 on core 0...Done.

Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
Per MPI rank memory allocation (min/avg/max) = 3193 | 3193 | 3193 Mbytes
Step Temp E_pair E_mol TotEng Press
       0            3   -6.7733681            0   -2.2733683   -3.7027174
      50     1.669595   -4.7856647            0   -2.2812723    5.6654026
     100    1.6524741   -4.7589429            0   -2.2802319    5.7977251
     150    1.6456677   -4.7483396            0   -2.2798381    5.8568397
     200    1.6440451   -4.7460612            0   -2.2799936     5.870633
     250    1.6434487    -4.745369            0   -2.2801961    5.8751957
     300    1.6432804      -4.7455            0   -2.2805795     5.875103
     350    1.6431086    -4.745489            0   -2.2808262     5.874611
     400    1.6428664   -4.7455253            0   -2.2812258    5.8745923
     450    1.6429371    -4.745904            0   -2.2814985    5.8727289
     500    1.6426633   -4.7458757            0   -2.2818808    5.8726928
     550    1.6425342   -4.7459415            0   -2.2821404    5.8724678
     600    1.6423274   -4.7460284            0   -2.2825374    5.8717517
     650     1.642208   -4.7460985            0   -2.2827866    5.8712047
     700    1.6418347   -4.7459344            0   -2.2831825    5.8719311
     750    1.6422137   -4.7467664            0    -2.283446    5.8689695
     800    1.6416304    -4.746281            0   -2.2838356    5.8705395
     850    1.6413065   -4.7460599            0   -2.2841003    5.8712727
     900     1.641055   -4.7460654            0    -2.284483    5.8713051
     950    1.6412948   -4.7466834            0   -2.2847413    5.8683462
    1000    1.6411186   -4.7468204            0   -2.2851427    5.8675664
Loop time of 463.359 on 1 procs for 1000 steps with 20000000 atoms

Performance: 932.322 tau/day, 2.158 timesteps/s
98.4% CPU use with 1 MPI tasks x no OpenMP threads
.
.
---------------------------------------------------------------------
      Device Time Info (average):
---------------------------------------------------------------------
Data Transfer:   49.5285 s.
Data Cast/Pack:  121.8439 s.
Neighbor copy:   0.0002 s.
Neighbor build:  12.3439 s.
Force calc:      47.6926 s.
Device Overhead: 0.2110 s.
Average split:   1.0000.
Threads / atom:  4.
Max Mem / Proc:  28370.52 MB.
CPU Driver_Time: 0.1454 s.
CPU Idle_Time:   86.6780 s.
---------------------------------------------------------------------

 ```

**Actual Behavior**
```SYS-4029GP-TRT2:~/lammps20200409/mylammps/examples/melt$ mpirun -np 1  ../../src/lmp_mpi -in in.20m.melt -sf
LAMMPS (19 Mar 2020)
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (839.798 167.96 167.96)
  1 by 1 by 1 MPI processor grid
Created 20000000 atoms
  create_atoms CPU = 1.4781 secs

--------------------------------------------------------------------------
- Using acceleration for lj/cut:
-  with 1 proc(s) per device.
--------------------------------------------------------------------------
Device 0: Tesla V100-PCIE-32GB, 80 CUs, 31/32 GB, 1.4 GHZ (Double Precision)
--------------------------------------------------------------------------

Initializing Device and compiling on process 0...Done.
Initializing Device 0 on core 0...Done.

ERROR: Insufficient memory on accelerator (../gpu_extra.h:38)
Last command: run               1000
Cuda driver error 4 in call at file 'geryon/nvd_device.h' in line 135.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62401,1],0]
  Exit code:    1
--------------------------------------------------------------------------
 ```

**Steps to Reproduce**

```mpirun -np 1  ../../src/lmp_mpi -in in.20m.melt -sf gpu -pk gpu 1```

**Further Information, Files, and Links**

```Tue Apr 28 09:26:54 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:3D:00.0 Off |                  Off |
| N/A   32C    P0    25W / 250W |     41MiB / 32510MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:3F:00.0 Off |                  Off |
| N/A   34C    P0    26W / 250W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     28356      C   nvidia-cuda-mps-server                        29MiB |
+-----------------------------------------------------------------------------+
 ```

Tried using cuda-memcheck and cuda-gdb to no avail.  Any debug assistance is greatly appreciated.  Applied for an ID to the lammps-users mailing list, will also post there.  Thanks

**Comment by akohlmey** [comment]
can you provide the the GPU memory usage on the machine you are running on by providing the output of `nvidia-smi` here?

**Comment by djygithub** [comment]
yes i also updated the original comment thanks
```Tue Apr 28 09:26:54 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:3D:00.0 Off |                  Off |
| N/A   32C    P0    25W / 250W |     41MiB / 32510MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:3F:00.0 Off |                  Off |
| N/A   34C    P0    26W / 250W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     28356      C   nvidia-cuda-mps-server                        29MiB |
+-----------------------------------------------------------------------------+
 ```

**Comment by akohlmey** [comment]
can you try compiling without using CUDPP (setting CUDPP_OPT to empty with the conventional build in the lib/gpu folder, or by using `-DCUDPP_OPT=off` when using CMake?

**Comment by djygithub** [comment]
yes i will try these.

**Comment by rbberger** [comment]
Please also include the output of the CMake configuration/compilation.

**Comment by akohlmey** [comment]
OK, I just made a quick check on a machine with Tesla V100-SXM2-16GB GPUs that I have access to.
The 31/32 GB number is the available GPU RAM vs the total. When running a binary compiled with mixed precision for the I can run up to 6M atoms at which point the process occupies about 9GB RAM on the GPU. anything larger fails.
when I used 4 GPUs instead, I can run the 20M input unchanged and the amount of GPU RAM in use is at 7.5GB per GPU. So it appears you are indeed running out of memory on the GPU. Please note that the amount of RAM required temporarily may be larger than what nvidia-smi displays. just imagine you need to copy data from a large buffer to a larger buffer: you would need the space for both to do the copying, even though later the resident memory use is only that of the larger buffer.
You may not even be able to control this yourself, if this happens inside the runtime or driver library.

**Comment by stanmoore1** [comment]
You can greatly reduce memory use (at the expense of some performance) if you reduce the neighbor skin. In the extreme:
```
neighbor        0.0 bin
neigh_modify    every 1 delay 0 check no
```

I'm also working on getting the Kokkos package to support using UVM to automatically "spill" out of GPU memory into CPU memory via page faulting (again at the expense of some performance), which would allow one to use the 100's of GB of CPU memory.

**Comment by djygithub** [comment]
Built as requested, same error I have attched the cmake, make, and execution output.

[lammpsv100nocudppbuild.melt20m.execution.txt](https://github.com/lammps/lammps/files/4548833/lammpsv100nocudppbuild.melt20m.execution.txt)
``` cmake -D PKG_GPU=yes -D GPU_API=cuda -D GPU_PREC=double -D GPU_ARCH=sm_70  -D CUDPP_OPT=off  ../cmake ```

FWIW I ran with kokkos, uses less GPU memory, 20 million atoms fits on one kokkos GPU.  This is for 4 million atoms:
![image](https://user-images.githubusercontent.com/23084557/80543084-137dca80-8963-11ea-958d-b71d7d8c8a90.png)


This is for 20 million atoms:
![image](https://user-images.githubusercontent.com/23084557/80543133-27293100-8963-11ea-8d68-122c22b5cad0.png)

I will also trys Stan's suggestions, thanks.

**Comment by djygithub** [comment]
https://github.com/stanmoore1 the UVM idea is intriguing, I imagine the overflow would go to HBM memory on the CPU?  It will be interesting to see the relative performance DRAM versus HBM.

**Comment by akohlmey** [comment]
Since there is nothing planned to change the behavior of the GPU package I will close this issue now. It won't be locked, so the discussion can continue. We may add a note about memory usage on the GPU and that it can differ due to driver and accelerator package.

**Comment by stanmoore1** [comment]
So far I haven't been able to get LAMMPS to use UVM to spill from GPU memory into CPU memory--it is crashing in the neighbor list build but on my to-do list to fix. I have spillage working in a different code  so I know it can work.

**Comment by stanmoore1** [comment]
FYI, I fixed the issue with UVM spillage in the Kokkos package (it was actually a 32-bit integer overflowing), see https://github.com/lammps/lammps/pull/2082. So now problem size with Kokkos on NVIDIA V100 GPUs is limited by only by the CPU memory when using UVM, though performance will be slower if spilling out of fast GPU memory.
