### ISSUE TITLE
Documentation server occassionally produces SSL error

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#2042]
**Summary**

When loading LAMMPS documentation form the web, I receive web-browser errors indicating that the site is insecure.

**LAMMPS Version and Platform**

N/A

**Details**

```
% curl -v https://lammps.sandia.gov/doc/Install_linux.html
*   Trying 198.102.155.34...
* TCP_NODELAY set
* Connected to lammps.sandia.gov (198.102.155.34) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES128-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; postalCode=87123; ST=NM; L=Albuquerque; street=1515 Eubank Blvd SE; O=Sandia National
Laboratories; OU=Hosted by Sandia National Laboratories; CN=cert.sandia.gov
*  start date: Jul 13 00:00:00 2018 GMT
*  expire date: Jul 12 23:59:59 2020 GMT
*  subjectAltName: host "lammps.sandia.gov" matched cert's "*.sandia.gov"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization
Validation Secure Server CA
*  SSL certificate verify ok.
> GET /doc/Install_linux.html HTTP/1.1
> Host: lammps.sandia.gov
> User-Agent: curl/7.64.1
> Accept: */*
>
* LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
* Closing connection 0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

**Comment by akohlmey** [comment]
@ellio167 you may consider using https://docs.lammps.org as backup. This one is currently following the changes in PR #1970 but will be linked to the "master" branch (and be updated automatically after every merge) as soon as that PR is merged to master (if you have some comments and suggestions for the new "programmer guide" section, feel free to add them to #1970 
 ;-)).

**Comment by ellio167** [comment]
In fact, I was just using the first link that comes up via google....

**Comment by sjplimp** [comment]
@rbberger I don't know what to do about this.

**Comment by rbberger** [comment]
@sjplimp This is something on the Sandia side. You should forward this to your web admins.

**Comment by sjplimp** [comment]
Do you know if it's a forever problem, or just now?  They've been having issues with the Sandia server (www.sandia.gov, which hosts then LAMMPS webpage) for the last week or two.

**Comment by ellio167** [comment]
I've seen this on-and-off now for (it seems like) a couple of months...

**Comment by akohlmey** [comment]
This is likely an issue with the frontend/backend web server setup where some servers are running a different SSL software stack. Recently some SSL encryption methods have been removed from web browsers and tools like wget or curl or rather the libraries they depend on. which can then lead to handshake issues when being connected to the wrong server.

Also the sandia web servers are obviously throttling downloads to a rather low speed of about 200kB/s. I have the lowest, cheapest and thus slowest tier of cable internet at home (and live in a high-rise with lots of people), but i still often get over 3MB/s for downloads from other sites, e.g. github. ...and that is still slow compared to what i get in my office machine or our clusters, where even uploads can better than 35MB/s and downloads over 50MB/s. Really handy when downloading or building/debugging/uploading container images. ;-)

**Comment by akohlmey** [comment]
Since this is an issue with Sandia's web hosting and not a LAMMPS issue I will close this now. Once we have docs.lammps.org linked to the master branch, we can add notes to the manual and the LAMMPS website at Sandia to list this as an alternate site to look up LAMMPS documentation online.
