### ISSUE TITLE
[BUG] Out of bounds index in compute coord/atom

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#2050]
**Summary**

Pretty sure there is a bug in `compute coord/atom`.

If the optional flags in `compute orientorder/atom` are all zero then `ncol = 5` by default https://github.com/lammps/lammps/blob/master/src/compute_orientorder_atom.cpp#L158:

```c++
  ncol = nqlist;
  if (wlflag) ncol += nqlist;
  if (wlhatflag) ncol += nqlist;
  if (qlcompflag) ncol += 2*(2*qlcomp+1);
```

Then this code in `compute coord/atom` is out of bounds here: https://github.com/lammps/lammps/blob/master/src/compute_coord_atom.cpp#L310

```c++
  for (int m=0; m < 2*(2*l+1); m++) {
    dot_product += normv[i][nqlist+m]*normv[j][nqlist+m];
  }
```

@athomps can you confirm?

**LAMMPS Version and Platform**

Latest master.

**Comment by athomps** [comment]
I would not call this a bug. It's a feature that is documented here:
compute_orientorder_atom.html
"compute must invoke its components option to calculate components of the Ybar_lm vector"
There is also an error check in init(), but it is unreliable, because it checks iqlcomp instead of qlcompflag.

**Comment by stanmoore1** [comment]
@athomps got it thanks
