### ISSUE TITLE
ERROR: Unrecognized atom style 'full' is part of the MOLECULE package which is not enabled in this LAMMPS binary

### ISSUE THREAD

**Issue by conandolley103** [lammps/lammps#2052]
Hi lammps, I got the error unrecognized atom_style full when I run lmp_mpi for lammps-3Mar20 on Linux system. I already installed make yes-MOLECULE package, but still got the error. Can you help me to figure out where file to fix it? Thank you very much.

**Comment by mkanski** [comment]
You need to recompile LAMMPS.

**Comment by conandolley103** [comment]
Thank you very much for your reply. I will do it as your advice.
