### ISSUE TITLE
[BUG] CMAKE_TUNE_FLAGS="-fsanitize=address" doesn't work anymore

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#2084]
**Summary**

Part of the compiler flags validation removes the `=`, which then fails the test and removes the flag.

**LAMMPS Version and Platform**

current master

**Expected Behavior**

Accept valid compiler flag.

**Actual Behavior**

```
-- Performing Test COMPILER_SUPPORTS-fsanitizeaddress
-- Performing Test COMPILER_SUPPORTS-fsanitizeaddress - Failed
CMake Warning at CMakeLists.txt:334 (message):
  -fsanitize=address found in CMAKE_TUNE_FLAGS, but not supported by the
  compiler, skipping
```

**Steps to Reproduce**

```
cmake -D CMAKE_TUNE_FLAGS=-fsanitize=address ../cmake
```

**Comment by junghans** [comment]
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_74601.dir/link.txt --verbose=1
/usr/lib64/ccache/c++   -DCOMPILER_SUPPORTS-fsanitizeaddress    CMakeFiles/cmTC_74601.dir/src.cxx.o  -o cmTC_74601
/usr/bin/ld: CMakeFiles/cmTC_74601.dir/src.cxx.o: in function `_sub_I_00099_0':
src.cxx:(.text+0x10): undefined reference to `__asan_init'
/usr/bin/ld: src.cxx:(.text+0x15): undefined reference to `__asan_version_mismatch_check_v8'
collect2: error: ld returned 1 exit status
```

**Comment by junghans** [comment]
I guess the best might be to skip the check for `-fsanitize=` on the other hand this case is so special you could just use `CMAKE_CXX_FLAGS` directly.

**Comment by junghans** [comment]
I don't think disabling the check is a great idea, one some platforms e.g. on armv5, gcc doesn't support `-march=native` and no it will get injected anyhow.

**Comment by akohlmey** [comment]
> I don't think disabling the check is a great idea, one some platforms e.g. on armv5, gcc doesn't support `-march=native` and no it will get injected anyhow.

Suggest a check that works properly and it will be added. Otherwise, just override the variable with something else or set it to empty.

**Comment by junghans** [comment]
I made two suggestions above, 1.) have the user add `-fsanitize=address` to `CMAKE_CXX_FLAGS`, which is unchecked. Or 2.) skip the check for `-fsanitize=address`.  No response for more than a month. I am happy to implement 2.) if that is what you want.

Adding flags unchecked has the problem that user will end up with either a error at compile time or worse an obscure error when cmake is try to detect the next package and it is internally using an unsupported flags. Both aren't great user experiences. On the plus side currently we only inject`-march=native` and that is relative well supported except for arm.
