### ISSUE TITLE
[BUG] _random_mars.cpp_issues_

### ISSUE THREAD

**Issue by sailer1205** [lammps/lammps#2096]
**Summary**

in random_mars.cpp, the if condition may be a mistake in RanMars::besselexp():
`  if (theta < 0.0 || alpha < 0.0 || alpha < 1.0) `

"alpha < 0.0 || alpha < 1.0" is equal to "alpha < 1.0", shall we use the "alpha < 1.0" instead?
but when I use the master branch to compile and  run the example under  examples/wall,
an error was occurred:

> $ lmp < in.wall.ccl
LAMMPS (19 Mar 2020)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:94)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 10 10 10
Created orthogonal box = (0 0 0) to (100 100 100)
  1 by 1 by 1 MPI processor grid
Created 1000 atoms
  create_atoms CPU = 0.00122748 secs
Neighbor list info ...
  update every 1 steps, delay 10 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 10.5
  ghost atom cutoff = 10.5
  binsize = 5.25, bins = 20 20 20
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair lj/cut, perpetual
      attributes: half, newton on
      pair build: half/bin/atomonly/newton
      stencil: half/bin/3d/newton
      bin: standard
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.001
Per MPI rank memory allocation (min/avg/max) = 3.137 | 3.137 | 3.137 Mbytes
Step Temp E_pair E_mol TotEng Press
       0          300            0            0    38.739265    41.378094
ERROR: Invalid Bessel exponential distribution parameters (src/random_mars.cpp:155)
Last command: run               10000

so, I think the real if condition is " if (theta < 0.0 || alpha < 0.0 || alpha > 1.0)", isn't it?

I found the modification at ceeae571723b4c0b9a99b494d5d75d898adea212, but this change was rolled back at 90ff2eb6c97638be07f8bbddbbfa6daec081cc40, I could not fully understand why to do so, or just a commit mistake? @sjplimp 

**LAMMPS Version and Platform**

master, centos7, x86_64

**Expected Behavior**

the example under examples/wall run normally

**Actual Behavior**

the example under examples/wall run failed

**Steps to Reproduce**

$ cd examples/wall
$ lmp < in.wall.ccl

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
> I found the modification at [ceeae57](https://github.com/lammps/lammps/commit/ceeae571723b4c0b9a99b494d5d75d898adea212), but this change was rolled back at [90ff2eb](https://github.com/lammps/lammps/commit/90ff2eb6c97638be07f8bbddbbfa6daec081cc40), I could not fully understand why to do so, or just a commit mistake? @sjplimp

I believe the second modification was done unintentional, since the change introduced in that commit had nothing to do with bessel function distributed random numbers. More likely the change was implemented separately and then the files were copied over instead of working on a feature branch under git and then not check carefully enough when committing so that the formerly fixed bug was re-introduced. Will be restored in PR #2094

**Comment by sailer1205** [comment]
@akohlmey Thank you for your prompt reply!
