### ISSUE TITLE
[Feature Request] Add more unit test inputs

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2099]
Pull request #2098 adds an infrastructure for adding unit tests for all kinds of force computing styles to LAMMPS. Currently only a handful of tests for a few representative pair styles have been added. Many more are needed to cover the large number of styles supported by LAMMPS.  To contribute tests, no programming knowledge is required, just some knowledge in running LAMMPS, its input file syntax, using git to submit pull requests and and a bit of common sense are required.  Please post a message below or contact akohlmey@gmail.com in case you are interested to contribute.

**Comment by abhiShandy** [comment]
I'm interested in doing this. I have been using LAMMPS for my research since 2016 and have fair experience with submitting PRs. Please let me know how can I contribute.

**Comment by akohlmey** [comment]
> I'm interested in doing this. I have been using LAMMPS for my research since 2016 and have fair experience with submitting PRs. Please let me know how can I contribute.

Thanks for your offer. You would need start the usual development protocol, i.e. create a fork of the LAMMPS repo, make a feature branch based off of the upstream master branch, add changes, commit locally, push the branch to your fork, then submit a pull request. I suggest you submit contributions in batches and start with just a single contribution to get a sense of the workflow.

Please have a look at the source code in the unittest tree and also read through the high-level introduction to testing in https://lammps.sandia.gov/doc/Build_development.html

Then familiarize yourself with running the tests, i.e. compile LAMMPS using CMake with testing enabled and how to run the test via ctest. 

The simplest tests to add would be additional input files in the `unittest/force-styles/tests` folder for pair styles that are not yet covered. For those it is usually simplest to run in the tests (source) folder directly, set your PATH and LAMMPS_POTENTIALS environment variables as needed and then you can run tests with: `test_pair_style test.yaml`. Example:
```
$ test_pair_style mol-pair-lj_cut.yaml 
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from PairStyle
[ RUN      ] PairStyle.plain
[       OK ] PairStyle.plain (31 ms)
[ RUN      ] PairStyle.omp
[       OK ] PairStyle.omp (24 ms)
[ RUN      ] PairStyle.intel
[       OK ] PairStyle.intel (19 ms)
[ RUN      ] PairStyle.opt
[       OK ] PairStyle.opt (8 ms)
[ RUN      ] PairStyle.single
[       OK ] PairStyle.single (21 ms)
[ RUN      ] PairStyle.extract
[       OK ] PairStyle.extract (6 ms)
[----------] 6 tests from PairStyle (110 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test suite ran. (111 ms total)
[  PASSED  ] 6 tests.
$
```

Also run the test with the -v flag added so see the outputs from the underlying LAMMPS commands during execution.

To add a new test, make a copy of an existing .yaml file, best of something similar (example: `cp mol-pair-lj_mdf.yaml mol-pair-lennard_mdf.yaml`), following the naming conventions and edit the yaml file as needed with suitable parameters (those don't have to be meaningful just reasonable so that the tester can run a few MD steps and has no outrageously large or invalid forces and stresses, in this example case: change lj/mdf  to lennard/mdf and compute the pair coefficients A and B from epsilon and sigma). Initially tests may fail since you don't have the exact forces included or the runs may not even complete when you have typos. You can debug this by running, e.g.:
`$ test_pair_style mol-pair-lennard_mdf.yaml -g new.yaml`
if this completes you can compare the two yaml files to see, if the behavior is as expected.
Then you can update the recorded data by either moving new.yaml over mol-pair-lennard_mdf.yaml or by running:
`$ test_pair_style mol-pair-lennard_mdf.yaml -u`
Then validate the file by running the full set of tests:
`$ test_pair_style mol-pair-lennard_mdf.yaml`

If some tests fail you have to figure out why. Sometimes there is a bug in the code, sometimes the epsilon needs to be tweaked just a little bit. In this particular case, the pair style does not support mixing, so i wrote a little python code to manually mix and compute the A, B parameters:
```python
from math import sqrt, pow

epsilon = [0, 0.02, 0.005, 0.005, 0.02, 0.015, 0.015]
sigma   = [0, 2.5, 1.0, 0.5, 3.2, 3.1 , 3.1]

for i in range(1,6):
    for j in range(i,6):
        a = 4.0*(sqrt(epsilon[i]*epsilon[j]))*pow(0.5*(sigma[i]+sigma[j]),12.0)
        b = 4.0*(sqrt(epsilon[i]*epsilon[j]))*pow(0.5*(sigma[i]+sigma[j]),6.0)
        print("  %d %d %.15g %.15g" % (i,j,a,b))
```

Also the extract symbols are different, so they needed to be changed from epsilon and sigma to a and b. Finally, there were still discrepancies with the `Pair::single()` function and those turned out to be a bug in the pair_lennard_mdf.cpp file, so I fixed that, too. As a finishing touch, I also updated the class name to be consistent with the file name and pair style label and other LAMMPS styles. After adding the yaml file and committing the changes to the lennard/mdf pair style, they are now part of a feature branch of mine, that will be included in a future pull request. https://github.com/lammps/lammps/compare/master...akohlmey:collected-small-changes

If you want to do more programming, you can consider writing a tester tool for dihedral and improper styles, similar to what is written for bond and angle.

Or you can expand the atom style tester with support for additional atom styles. For those you have to look a the existing code and adapt it accordingly. For the most part, it should be straightforward.

Or you can add tests for commands or other LAMMPS features. As mentioned in the beginning, there is plenty of stuff missing.

**Comment by abhiShandy** [comment]
Thanks for such a detailed guide.

I have setup my fork and was running the tests on my local machine. I encountered 4 failing tests for angle-styles and figured that the error tolerance (epsilon) was a bit too tight. Once I increased it from 2.5e-13 to 4.0e-13, those tests passed.

For the next step in development guide, when I try to generate the coverage report I get an empty report (as shown below). I feel I'm making some silly mistake. Please help me figure it out.

![image](https://user-images.githubusercontent.com/6998593/88873326-6bd69980-d1ea-11ea-8064-a43064bd1b76.png)

In the meantime, I was going through the YAML files in force-styles/tests. I see that there are 99 tests and they have been classified into atomic, manybody and molecular types. Manually, I figured that the tests for `pair_style agni` and `pair_style coul/soft` are missing. Is there a systematic way to find the missing tests for pair-styles (other than the coverage report)?

**Comment by akohlmey** [comment]
@abhiShandy 
What platform/OS/version/compilers are you running on?
The tests, especially when you plan to generate new reference outputs, should be run without compiler optimization.  You should set `-DCMAKE_BUILD_TYPE=Debug` and best use GNU compilers. Coverage is not required, but can be useful to determine whether certain code paths are not covered. If they can be switched from the pair_style or pair_coeff commands, then multiple test inputs should be created. To get coverage enabled, you also need to set `-DENABLE_COVERAGE=on`. It will only work with certain compilers.

There is no automatic way to display missing tests. In some cases, there are multiple setups for a single pair style. Test are mostly added in a by-package fashion, but there are some exceptions. So far, the primary motivation has been to cover simple to add pair styles and commonly used ones. Some pair styles need special treatment or a missing required features and cannot be tested. I would stay away from inter-layer potentials or machine learning potentials for that reason. I would suggest to start by checking if all "default" pair styles (i.e. those in src) are covered, then move on to MOLECULE, KSPACE, MISC, USER-MISC, COLLOID, CORESHELL, DIPOLE, GRANULAR, USER-SPH, USER-SMD, PERI, SPIN will likely need building new data files and input templates (which is currently a bit of a black art). Then there are multiple USER packages with pair styles USER-CGSDK, USER-MOFF, USER-YAFF that might fit to the current templates. Please note how for styles requiring a long range coulomb solver, those are defined, but their computation is turned off. The same tester program is also used to test KSPACE styles (and then the pair style part of the computation is turned off), so you can also look into checking to complete the tests for kspace solvers.

**Comment by akohlmey** [comment]
I forgot to mention because it is not yet an "official" feature of the integration testing server, but code coverage is also generated automatically and uploaded from the integration testing for the master branch and pull requests. You can look it up online at: https://codecov.io/gh/lammps/lammps/ so there is no need to generate it yourself (it is faster to browse, if it is local, though).

**Comment by akohlmey** [comment]
@abhiShandy a note about finding suitable pair_coeff parameters. copying from the documentation is rarely going to work. a better approach would be to just take the lj/cut parameters and then empirically find some parameters that result in a somewhat similar shape potential. often that is straightforward (e.g. for morse you can quickly tell the minimum location and depth of the potential from the lj parameters and then need to adjust the width of the potential (i often do this empirically using gnuplot or with a little python script and matplotlib)

**Comment by abhiShandy** [comment]
Got it. That way, the energies (and force, stress) will be in the same order. I'll setup a script to find the appropriate parameters for the next set of pair-styles.

How does LAMMPS test energy calculation for just a pair of atoms? Such a test would account for assumptions behind the atomic template and complete the hierarchy of tests: pair of atoms -> set of similar atoms -> set of dissimilar atoms

**Comment by akohlmey** [comment]
> Got it. That way, the energies (and force, stress) will be in the same order. I'll setup a script to find the appropriate parameters for the next set of pair-styles.

please note that the script i wrote for the lennard/mdf style and posted here has a bug (actually two that made it look like there was none, but the output didn't match that of lj/mdf as close as it should. had to dig deeper and found and fixed it this morning).

> How does LAMMPS test energy calculation for just a pair of atoms?

the tester program doesn't really distinguish the different cases explicitly. I will just compute the forces, global stress, per-atom energies and global energies and the sum of the per-atom energy and compares them to the data in the reference file. then it sets up 4 MD steps where energy and stress is computed only on every other step and compares all forces and stress and energies again with the second set of reference data. it does so with newton on and newton off (if supported, otherwise special settings in the yaml file are needed) and also tests with the r-RESPA integrator (if supported) with a 1:1 split that would numerically by the same as velocity verlet. in between these steps either data file or binary restart files are written, read back. Also some other simple tests are conducted and finally a minimal system with just a few atoms (the templates have around 30 atoms) is set up, so that the result from the Pair::compute() and the Pair::single() functions can be compared.  These tests are repeated (if supported and LAMMPS has been compiled as such) with -suffix omp, -suffix opt, and -suffix intel, always comparing against the same reference data.

if you want to start writing a tester for dihedrals (and impropers), you will see, as you need to start from the existing two programs for bonds and angles, but expand and adapt as needed.

the point of having ~30 atoms is that this is still fast enough (in most cases, msm, and pppm/disp are quite slow) yet has atoms at different distances and - ideally - with and without bonds between them.

> Such a test would account for assumptions behind the atomic template and complete the hierarchy of tests: pair of atoms -> set of similar atoms -> set of dissimilar atoms

the fourmol template has the most complexity and thus should be preferred in most cases. exceptions are manybody. for pair styles that cannot run sufficiently stable with available settings for the manybody template, we fall back to the atomic template.

**Comment by akohlmey** [comment]
@abhiShandy Did a chunk more tests, mostly for cases, where building the input is tricky, where changes to the code were needed or where there were bugs in the pair styles.
```
$ make check-tests
Check completeness of force style tests
Parsing style names from C++ tree in:  /home/akohlmey/compile/lammps/src

Tests available for pair styles: 122 of 236
No tests for:  ['agni', 'awpmd/cut', 'body/nparticle', 'body/rounded/polygon', 'body/rounded/polyhedron', 'brownian', 'brownian/poly', 'buck6d/coul/gauss/dsf', 'buck6d/coul/gauss/long', 'coul/cut/soft', 'coul/long/soft', 'dpd', 'dpd/fdt', 'dpd/fdt/energy', 'dpd/tstat', 'drip', 'dsmc', 'e3b', 'edip/multi', 'edpd', 'eff/cut', 'exp6/rx', 'extep', 'gayberne', 'gran/hertz/history', 'gran/hooke', 'gran/hooke/history', 'granular', 'hbond/dreiding/lj', 'hbond/dreiding/morse', 'ilp/graphene/hbn', 'kolmogorov/crespi/full', 'kolmogorov/crespi/z', 'lebedeva/z', 'line/lj', 'list', 'lj/charmm/coul/long/soft', 'lj/class2/coul/cut/soft', 'lj/class2/coul/long/soft', 'lj/class2/soft', 'lj/cut/coul/cut/soft', 'lj/cut/coul/long/soft', 'lj/cut/dipole/cut', 'lj/cut/dipole/long', 'lj/cut/soft', 'lj/cut/thole/long', 'lj/cut/tip4p/long/soft', 'lj/long/dipole/long', 'lj/sf/dipole/sf', 'lj/switch3/coulgauss/long', 'local/density', 'lubricate', 'lubricate/poly', 'lubricateU', 'lubricateU/poly', 'mdpd', 'mdpd/rhosum', 'mesocnt', 'mesont/tpm', 'mgpt', 'mm3/switch3/coulgauss/long', 'momb', 'morse/smooth/linear', 'morse/soft', 'multi/lucy', 'multi/lucy/rx', 'oxdna/coaxstk', 'oxdna/excv', 'oxdna/hbond', 'oxdna/stk', 'oxdna/xstk', 'oxdna2/coaxstk', 'oxdna2/dh', 'oxdna2/excv', 'oxdna2/hbond', 'oxdna2/stk', 'oxdna2/xstk', 'oxrna2/coaxstk', 'oxrna2/dh', 'oxrna2/excv', 'oxrna2/hbond', 'oxrna2/stk', 'oxrna2/xstk', 'peri/eps', 'peri/lps', 'peri/pmb', 'peri/ves', 'quip', 'reax/c', 'resquared', 'sdpd/taitwater/isothermal', 'smd/hertz', 'smd/tlsph', 'smd/tri_surface', 'smd/ulsph', 'smtbq', 'sph/heatconduction', 'sph/idealgas', 'sph/lj', 'sph/rhosum', 'sph/taitwater', 'sph/taitwater/morris', 'spin/dipole/cut', 'spin/dipole/long', 'spin/dmi', 'spin/exchange', 'spin/magelec', 'spin/neel', 'srp', 'table/rx', 'tdpd', 'thole', 'tip4p/long/soft', 'tri/lj']

Tests available for bond styles: 13 of 17
No tests for:  ['oxdna/fene', 'oxdna2/fene', 'oxrna2/fene', 'quartic']

Tests available for angle styles: 18 of 21
No tests for:  ['cosine/buck6d', 'dipole', 'sdk']

Tests available for dihedral styles: 0 of 16
No tests for:  ['charmm', 'charmmfsw', 'class2', 'cosine/shift/exp', 'fourier', 'harmonic', 'helix', 'hybrid', 'multi/harmonic', 'nharmonic', 'opls', 'quadratic', 'spherical', 'table', 'table/cut', 'zero']

Tests available for improper styles: 0 of 13
No tests for:  ['class2', 'cossq', 'cvff', 'distance', 'distharm', 'fourier', 'harmonic', 'hybrid', 'inversion/harmonic', 'ring', 'sqdistharm', 'umbrella', 'zero']

Tests available for kspace styles: 10 of 15
No tests for:  ['ewald/dipole', 'ewald/dipole/spin', 'pppm/dipole', 'pppm/dipole/spin', 'scafacos']

Total tests missing: 155 of 318

```

**Comment by abhiShandy** [comment]
Awesome! I had mental barrier for writing tests for pair styles which I haven't used or don't understand well. I am planning to attempt writing tester programs for dihedral and improper styles in the next burst.

**Comment by akohlmey** [comment]
There are still the /soft pair styles open.

--
Dr. Axel Kohlmeyer akohlmey@gmail.com http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste, Italy

**Comment by abhiShandy** [comment]
Sorry to leave his hanging. I won't be able to devote time to this for next few months. You can take over my draft PR #2290 or assign it to someone else.
