### ISSUE TITLE
/usr/include/armadillo_bits/wrapper_blas.hpp:42: undefined reference to `dgemv_'

### ISSUE THREAD

**Issue by moradza** [lammps/lammps#2112]
**Summary**

I want to use BLAS and LAPACK Libraries but I get the following error during compiling. I use armadillo for data management, but it does only provide me with vector scalar multiplication. 

**LAMMPS Version and Platform**

Git info (stable / stable_3Mar2020-modified)

**Details**

I am using the Armadillo C++ library for matrix manupliation, but when it comes to matrix-vector multiplication it gives me the following error.

/usr/include/armadillo_bits/wrapper_blas.hpp:42: undefined reference to `dgemv_'

**Comment by akohlmey** [comment]
How has this anything to do with LAMMPS?
The answer is trivial and can be easily found with a web search and possibly also by reading the documentation for your C++ library.
