### ISSUE TITLE
[Feature Request] _Eliminate Misleading error messages with hybrid and hybrid/overlay pair styles_

### ISSUE THREAD

**Issue by athomps** [lammps/lammps#2117]
**Summary**

Eliminate misleading error messages when using hybrid pair styles (hybrid and hybrid/overlay).

**Detailed Description**

When using hybrid pair styles, the error message for unrecognized pair styles is misleading. For example, if examples/in.snap.Ta06A is run with a LAMMPS executable that has not been compiled with the SNAP package, the error message is:

ERROR: Illegal pair_style command (../pair_zbl.cpp:180)

when it should be possible to generate something like:

ERROR: Unrecognized pair style 'snap' (../force.cpp:285)

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
@athomps this turned out to be much simpler than anticipated.

**Comment by akohlmey** [comment]
The error message after applying PR #2118 is:

```[akohlmey@silence snap]$ ~/compile/lammps/build-demo/lmp -in in.snap.Ta06A 
LAMMPS (5 May 2020)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 3.316 3.316 3.316
Created orthogonal box = (0 0 0) to (13.264 13.264 13.264)
  1 by 1 by 1 MPI processor grid
Created 128 atoms
  create_atoms CPU = 0.000526667 secs
ERROR: Unrecognized pair style 'snap' is part of the SNAP package which is not enabled in this LAMMPS binary. (src/force.cpp:285)
Last command: pair_style hybrid/overlay zbl ${zblcutinner} ${zblcutouter} snap
```
