### ISSUE TITLE
[BUG] _remove .c_str() is not allowed for write_echo _

### ISSUE THREAD

**Issue by yafshar** [lammps/lammps#2146]
**Summary**

The new modification [remove .c_str() and simplify output in several places ](https://github.com/lammps/lammps/commit/dd11fb3964acfbba94f19513f8d35b10b0a41e60) introduces error at
[ src/KIM/kim_property.cpp](https://github.com/lammps/lammps/commit/dd11fb3964acfbba94f19513f8d35b10b0a41e60#r39832500), since `write_echo` interface is `void write_echo(const char *);` and does not get `string`.

**LAMMPS Version and Platform**
master branch 
commit https://github.com/lammps/lammps/commit/dd11fb3964acfbba94f19513f8d35b10b0a41e60

**Expected Behavior**
compile with no error

**Actual Behavior**
```bash
/lammps/src/KIM/kim_property.cpp:109:23: error: cannot convert ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const char*’
  109 |     input->write_echo(msg);
      |                       ^~~
      |                       |
      |                       std::string {aka std::__cxx11::basic_string<char>}
In file included from /lammps/src/KIM/kim_property.cpp:64:
/lammps/src/input.h:41:19: note:   initializing argument 1 of ‘void LAMMPS_NS::Input::write_echo(const char*)’
   41 |   void write_echo(const char *); // send text to active echo file pointers
      |                   ^~~~~~~~~~~~
```

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
@yafshar please check out PR #2148 and add suggestions, comments or concerns there, if you have any. If you want to make additional changes, you can submit a pull request for that branch into github.com:akohlmey/lammps/

**Comment by yafshar** [comment]
@akohlmey thanks. I checked out PR #2148 and everything seems good to me. It passed my tests as well.

**Comment by akohlmey** [comment]
> @akohlmey thanks. I checked out PR #2148 and everything seems good to me. It passed my tests as well.

excellent! thanks. hopefully, you can see some coding patterns, that you can adopt in new code or future updates. did we ever sent you an invite to become an official collaborator on the LAMMPS project (so we can assign you as a reviewer and similar things)?

**Comment by yafshar** [comment]
> hopefully, you can see some coding patterns, that you can adopt in new code or future updates.

@akohlmey sure, it is a nice feature and convenient to use. 
> did we ever sent you an invite to become an official collaborator on the LAMMPS project (so we can assign you as a reviewer and similar things)?

No, I did not get any invite to become an official collaborator. I would appreciate if you send me that.
