### ISSUE TITLE
[BUG] Traditional Make+Mac+mode=shared fails After April 11th

### ISSUE THREAD

**Issue by charlessievers** [lammps/lammps#2153]
**Summary**

Traditional Makefile no longer creates a shared object library for Mac.

**LAMMPS Version and Platform**

Issue for Mac, problem occurred after PR #1981 

**Expected Behavior**

Traditional Make should ideally produce a shared library for Mac.

**Actual Behavior**

Linking error occurs.
```
f.o write_data.o write_dump.o write_restart.o       -o ../lmp_mpi
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lmp_mpi] Error 1
make: *** [mpi] Error 2
```

**Steps to Reproduce**

- Need to use a Mac

`git clone https://github.com/lammps/lammps`
`cd lammps/src/src`
`make mode=shared mpi`

**Further Information, Files, and Links**

CMake still works to make a shared lib for Mac. I assume this is a file extension issue, since Mac uses .dylib instead of .so

```
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by charlessievers** [comment]
@akohlmey Just saw your response to @athomps on April 15th about this issue.

It might be nice to have an error message. I am willing to close this issue once you have read it.

**Comment by akohlmey** [comment]
> @akohlmey Just saw your response to @athomps on April 15th about this issue.
> 
> It might be nice to have an error message. I am willing to close this issue once you have read it.

Error message how?
The only advice I can give is that if you follow development, it is worth reading the release notes.
Makefiles and other things have been broken in the past, too. There is no way to make this all automatic. That is what we are supporting CMake for. I only use the conventional make when testing these days.

**Comment by charlessievers** [comment]
> Error message how?
No idea, I am closing the issue.

The issue did convert me to only using CMake. I usually only use them for development.
