### ISSUE TITLE
[Feature Request] Embed UNITS: tag with required units setting into potential files

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2158]
**Summary**

Beginners often make the mistake of using the wrong units settings with (manybody) potential files.
By adding a "UNITS:" tag like the current "DATE:" and "CITATION:" tags, we could add a check for compliance, at least for the potential files that are bundled with LAMMPS. Databases that collect such potential files may be willing to add such tags to the files in their repositories.

**Detailed Description**

If added to a comment section, like the existing "DATE:" tag, the additional entry will not alter the file format. And by making the tag optional, LAMMPS will remain compatible with all existing potential files.

However, in addition, we could also embed the most common units setting string into the various pair styles (most crucial would be those in MANYBODY, USER-MEAMC, and USER-REAXC with metal, metal, and real, respectively) and then print a (mild) warning if the choice of units is different from the most common setting.

With the units tag embedded in the potential file, it may also be possible to extend the functionality of current pair styles to include an automatic conversion to a chosen set of units after reading the parameters and then not only accept the native units but units for which conversion factors exist. And by writing a custom test tool, similar but much simpler, than the existing "pair_style" test tool, we could easily confirm the validity of the conversion factors by converting resulting energies and forces back to a common set of units (e.g. metal) and compare to the unconverted potential data.

**Comment by ellio167** [comment]
@akohlmey this looks great.  I would be interested to contribute on the automatic unit conversion idea.

**Comment by akohlmey** [comment]
@ellio167 thanks for the offer. Let us first see what the feedback on PR #2159 is. The first order of business would be to write a test program and then it would probably most straightforward to implement the conversion for pair style table (which only stores data for distance, force and energy). I don't have yet a well formed idea for how to indicate the possible conversions (enum?, bitmask?, list of strings?, and where added?), how to add this to the units check, and how to keep the implementation as generic and reusable as possible.
Once the PR is in, you should probably contact me directly via e-mail and we should do a video call to brainstorm a possible implementation and pick suitable targets.
