### ISSUE TITLE
Sane defaults for CMAKE_TUNE_FLAGS

### ISSUE THREAD

**Issue by sgsaenger** [lammps/lammps#2164]
Compilation with CMake currently defaults to use `-march=native` or `-xHost`.
These flags reduce portability across systems with compatible software, but incompatible hardware configurations.
This is rarely expected from software, and does not reproduce the behavior of the old `make`-based build system.
Especially `-march=native` is also known to [produce slower binaries](https://stackoverflow.com/questions/37513675/clang-osx-march-native-approximately-1-3rd-speed-of-no-optimisation) in some cases.

Given that there is already a preset system in place, i would propose moving all of, but at least the mentioned flags, from `CMAKE_TUNE_DEFAULT` to suitable preset files.
This way they are only activated if and when the user is actively dealing with tuning LAMMPS to their machine.

**Comment by junghans** [comment]
Related https://github.com/votca/csg-tutorials/issues/89, setting -DCMAKE_TUNE_FLAGS='' is the workaround for now.

**Comment by akohlmey** [comment]
What is considered "sane" is a matter of perspective not facts. As explained in a previous conversation, choices are made and for as long as those can be easily changed from the cmake command line or GUI, there really is no need to make changes to the sources.
