### ISSUE TITLE
Fix modify with fix qtb

### ISSUE THREAD

**Issue by sde4** [lammps/lammps#2165]
Summary
It seems that fix modify (temperature) is not implemented correctly for fix_qtb.

LAMMPS Version and Platform
LAMMPS (15 June 2020)

OS name: GNU/Linux
OS release: 3.0.101-108.63-default
Hardware p;atform: x86_64

Expected Behavior
fix modify should be able to provide the ability to work with thermostat biasing.

Actual Behavior
fix modify is doing something currently but not sure what exactly it is doing; target quantum temperature is not achieved in a specified region when used in conjunction with compute temp/region. 

Steps to Reproduce
for thermostat biasing, I did the following:

1. define a region
2. define a compute for temp. of that region
    compute     temp_reg_01     all     temp/region reg_01
3.  used fix qtb to prescribe the target quantum temperature of that region
   variable tdamp  equal 0.5
   variable vseed  equal 12345 
   variable fmax   equal 60.0
   variable Nf     equal 100
   variable temp_b01 equal 330

   fix ff01        all     qtb temp ${temp_b01}  damp ${tdamp} seed ${vseed} f_max ${fmax} N_f ${Nf}
   fix_modify ff01     temp temp_reg_01

**Comment by akohlmey** [comment]
There is no indication in the documentation for fix qtb that it supports thermostat biasing, unlike in the documentation for fixes that do. The general rule in LAMMPS is: if it is not documented it is not supported. You get a different computed temperature, and thus you get different results, but that does not mean that a bias is removed and restored. That requires extra function calls.

**Comment by sde4** [comment]
Hi Axel,

Thanks for clarifying. Will LAMMPS developers consider implementing the fix modify for qtb? I am willing to put a more formal request. Please comment!

**Comment by akohlmey** [comment]
This is contributed code. You should contact its author about this. I am
not even sure that your request has a physical meaning.

--
Dr. Axel Kohlmeyer akohlmey@gmail.com http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste, Italy
