### ISSUE TITLE
[BUG] Kokkos/SNAP gives out-of-bounds errors when running with two atoms without chem-snap

### ISSUE THREAD

**Issue by weinbe2** [lammps/lammps#2166]
**Summary**

The recent chem snap PR appears to introduce a silent bug (i.e., it accidentally gives the right temperature, energies, pressure) for systems with two elements but without the proper modifications for chem snap. (Specific example: the system described by `/examples/snap/in.snap.WBe.PRB2019`). The bug can be diagnosed via compiling with `-DKOKKOS_ENABLE_DEBUG_BOUNDS_CHECK`, which throws errors when out-of-range accesses occur on multi-dimensional Views.

This does not occur with single-atom systems (for ex, `/examples/snap/in.snap.Mo_Chen`) or with two atom systems with chem snap properly configured (for ex, the recent `/examples/snap/in.snap.InP.JCPA2020`).

**LAMMPS Version and Platform**

Commit `77f6fecc868fbeb14a30a1d66a9d1af21aece5e6` (master branch at time of filing), corresponding to merging PR #1971. This issue does not occur in `patch_15Jun2020` as it predates the aforementioned PR.

Reproduced on Ubuntu 18.04.3 and 16.04.6, Kokkos CUDA backend. May not be confined to the CUDA backend only.

**Expected Behavior**

MD simulations with the SNAP potential should not have out-of-range memory accesses as it corresponds to potentially undefined behavior.

**Actual Behavior**

There are out-of-range memory accesses.

**Steps to Reproduce**

Configure LAMMPS with the SNAP and Kokkos packages. Build against the CUDA backend with the pre-processor define `-DKOKKOS_ENABLE_DEBUG_BOUNDS_CHECK`. (For `Makefile` builds, this corresponds to adding `-DKOKKOS_ENABLE_DEBUG_BOUNDS_CHECK` to the `CCFLAGS` and `LINKFLAGS` lines in `Makefile.kokkos_cuda_mpi`. [The latter may not be necessary, but better to be pedantic...].)

Run LAMMPS using the input file `/examples/snap/in.snap.WBe.PRB2019`, i.e., copy/statically link `lmp_kokkos_cuda_mpi` to the directory `/examples/snap/` and run, for ex:

`mpirun -np 1 ./lmp_kokkos_cuda_mpi -k on g 1 -sf kk -pk kokkos newton on neigh half -in in.snap.WBe.PRB2019`

The preprocessing info will print as normal, but then the output will quickly trigger `View bounds` errors, representative:

```
[...]
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.0005
:0: : block: [211,0,0], thread: [0,32,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,33,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,34,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,35,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,36,0] Assertion `View bounds error of view sna:ylist` failed.
[...]
```

A run without out-of-bounds errors would not trigger this. 

As noted above, this does not occur with single-atom systems or two atom systems with chem snap properly configured.

**Further Information, Files, and Links**

This has not been checked against other Kokkos backends (Serial, OpenMP). This has not been checked against the non-Kokkos SNAP implementation either, though in that case one would need a different method to check for memory access errors for flattened multi-dimensional arrays.

**Comment by weinbe2** [comment]
FYI @charlessievers @stanmoore1 @athomps

**Comment by stanmoore1** [comment]
@weinbe2 nice catch. One can also use `KOKKOS_DEBUG=yes` in the Makefile to enable bounds-checking.

**Comment by charlessievers** [comment]
I tested the WBe example quite a few times to ensure it worked... That is frustrating. I'll get a fix by the end of the day.

**Comment by charlessievers** [comment]
> @weinbe2 nice catch. One can also use KOKKOS_DEBUG=yes in the Makefile or CMake -DKokkos_ENABLE_DEBUG=on to enable bounds-checking.

Good catch indeed. I will make sure to enable this in the future while testing.

**Comment by charlessievers** [comment]
I am not getting the view bounds error with -D Kokkos_ENABLE_DEBUG=on , but I did catch a mistake while zeroing the ylist for multi element non chem_snap. I will create a PR with the change, would you test it out @weinbe2?

**Comment by weinbe2** [comment]
> I am not getting the view bounds error with -D Kokkos_ENABLE_DEBUG=on , but I did catch a mistake while zeroing the ylist for multi element non chem_snap. I will create a PR with the change, would you test it out @weinbe2?

Sure, I'll be happy to give it a spin, just tag me whenever you post it!

**Comment by akohlmey** [comment]
@weinbe2 just sent you an invite as external collaborator. That should allow you to be assigned as reviewer.
