### ISSUE TITLE
[BUG] create_atoms rotate keyword manual/code disagreement

### ISSUE THREAD

**Issue by saxtremer** [lammps/lammps#2170]
**Summary**

Documentation suggests that the angle after the rotate keyword in the create_atoms command must be in degrees, but it's coded in radians.

**LAMMPS Version and Platform**

12 Dec 2018 Ubuntu checked, but no related recent (for 6 years) changes to the functionality

**Expected Behavior**

As the manual suggests, the rotation angle should be in degrees:
[https://lammps.sandia.gov/doc/create_atoms.html](url)

> *rotate* values = theta Rx Ry Rz
>   theta = rotation angle for single molecule (**degrees**)
>   Rx,Ry,Rz = rotation vector for single molecule

**Actual Behavior**

The angle is interpreted in radians.

**Steps to Reproduce**

A minimal example is attached. It produces a dump with rotation around the x-axis.

**Further Information, Files, and Links**

Potentially problematic code:
**create_atoms.cpp**

> thetaone = force->numeric(FLERR,arg[iarg+1]);
> ...
> MathExtra::axisangle_to_quat(axisone,thetaone,quatone);

The function uses standard sine function, which expects radians. 

[input file create_atoms_problem.txt](https://github.com/lammps/lammps/files/4805762/create_atoms_problem.txt)
[molecule file tripod.txt](https://github.com/lammps/lammps/files/4805763/tripod.txt)

**Comment by akohlmey** [comment]
@sjplimp do you agree?
this would be a one-liner:
```
  diff --git a/src/create_atoms.cpp b/src/create_atoms.cpp
  index 526a2069e..373266229 100644
  --- a/src/create_atoms.cpp
  +++ b/src/create_atoms.cpp
  @@ -193,7 +193,7 @@ void CreateAtoms::command(int narg, char **arg)
         if (iarg+5 > narg) error->all(FLERR,"Illegal create_atoms command");
         double thetaone;
         double axisone[3];
  -      thetaone = force->numeric(FLERR,arg[iarg+1]);
  +      thetaone = force->numeric(FLERR,arg[iarg+1]) / 180.0 * MY_PI;;
         axisone[0] = force->numeric(FLERR,arg[iarg+2]);
         axisone[1] = force->numeric(FLERR,arg[iarg+3]);
         axisone[2] = force->numeric(FLERR,arg[iarg+4]);

```

**Comment by sjplimp** [comment]
yes, I agree.  Good catch @saxtremer !

**Comment by saxtremer** [comment]
@sjplimp @akohlmey  Thank you for the quick response and your work. LAMMPS rocks.
