### ISSUE TITLE
[BUG] Pressure offset in NPT run with GPU accelerated TIP4P

### ISSUE THREAD

**Issue by rdettori** [lammps/lammps#2175]
**Summary**

The pressure computed during an NPT run with the same input files changes if GPU accelerated version of TIP4P is used. The GPU accelerated version results in a large offset and thus in a wrong density.

**LAMMPS Version and Platform**
I used LAMMPS 3 Mar 2020 and tested on two different machines: one has one GeForce GTX 745 and the other GeForce RTX 2080.  The result is basically the same.

**Problem**
During NPT runs performed on GPU on an ice simulation cell with TIP4P flexible, the computed pressure is much lower than the value set in the input file. I didn't observe this difference when using other force-fields (either for water or different systems) and when the same input file is run on CPU the result is correct. The offset is around ~6.6 kBar and it seems size independent.

I am attaching the plot of two tests I performed and a tar file containing the inputs file to reproduce the run.

**Steps to Reproduce**
GPU runs were executed with

`lmp_gpu -sf gpu -in in.iceIh_120K`

while CPU runs were executed with 

`mpirun.mpich -np 4 lmp_gpu -sf omp -pk omp 2 -in in.iceIh_120K`

![image](https://user-images.githubusercontent.com/19315755/85327891-95323600-b484-11ea-8777-84fd2552c1f1.png)

**Input Files**
[iceIh.tar.gz](https://github.com/lammps/lammps/files/4815267/iceIh.tar.gz)

**Comment by akohlmey** [comment]
What are the precision settings for the GPU runs? Please make sure that those are DOUBLE.

**Comment by akohlmey** [comment]
@Vsevak can you take a look?

**Comment by rdettori** [comment]
This is the output when I compiled using CMake.

```
-- GPU API: CUDA
-- GPU architecture: sm_50
-- GPU precision: MIXED

```
So the precision is mixed. I haven't tried DOUBLE actually.

**Comment by akohlmey** [comment]
> This is the output when I compiled using CMake.
> 
> ```
> -- GPU API: CUDA
> -- GPU architecture: sm_50
> -- GPU precision: MIXED
> ```
> 
> So the precision is mixed. I haven't tried DOUBLE actually.

Ok. Thanks. The difference is too large to be due to precision, but when comparing CPU to GPU results it is best practice to compare the GPU runs with DOUBLE. For those the difference has to be within the range of floating-point truncation errors.

**Comment by Vsevak** [comment]
> @Vsevak can you take a look?

Sure, I will try to figure it out.

**Comment by Vsevak** [comment]
I found something: setting `thermo 1` in the proposed input completely eliminates the bug on my machine (GTX 1070, CUDA with DOUBLE). Otherwise, the wrong output can be found in the per-atom stress tensors. If I understand correctly, this indicates that the error is not in the computing kernel, but somewhere in the "glue code".
