### ISSUE TITLE
[BUG] NULL pointer in KSpace tests

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#2177]
**Summary**

Our extended Kspace regression tests are failing from a recent commit:

```
==4549== Invalid read of size 4
==4549==    at 0x532B60: LAMMPS_NS::Atom::tag_check() (atom.cpp:814)
==4549==    by 0x4D8606: LAMMPS_NS::Replicate::command(int, char**) (replicate.cpp:761)
==4549==    by 0x412675: void LAMMPS_NS::Input::command_creator<LAMMPS_NS::Replicate>(LAMMPS_NS::LAMMPS*, int, char**) (input.cpp:877)
==4549==    by 0x410570: LAMMPS_NS::Input::execute_command() (input.cpp:860)
==4549==    by 0x410DBA: LAMMPS_NS::Input::file() (input.cpp:230)
==4549==    by 0x4082D5: main (main.cpp:61)
==4549==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==4549== 
==4549== 
==4549== Process terminating with default action of signal 11 (SIGSEGV)
==4549==  Access not within mapped region at address 0x0
==4549==    at 0x532B60: LAMMPS_NS::Atom::tag_check() (atom.cpp:814)
==4549==    by 0x4D8606: LAMMPS_NS::Replicate::command(int, char**) (replicate.cpp:761)
==4549==    by 0x412675: void LAMMPS_NS::Input::command_creator<LAMMPS_NS::Replicate>(LAMMPS_NS::LAMMPS*, int, char**) (input.cpp:877)
==4549==    by 0x410570: LAMMPS_NS::Input::execute_command() (input.cpp:860)
==4549==    by 0x410DBA: LAMMPS_NS::Input::file() (input.cpp:230)
==4549==    by 0x4082D5: main (main.cpp:61)
==4549==  If you believe this happened as a result of a stack
```

**LAMMPS Version and Platform**

Latest master

[data.spce.txt](https://github.com/lammps/lammps/files/4815751/data.spce.txt)
[test15.in.txt](https://github.com/lammps/lammps/files/4815753/test15.in.txt)

**Comment by stanmoore1** [comment]
7e2f29bb6576f68bdab06e8ffc8cc80cc6f85f19 passed, while 5148834d23570f1e8338aae8db48334f2d2a5a8f failed.

**Comment by akohlmey** [comment]
I think I know where this is coming from. @sjplimp had talked me into it. Need to think carefully about this though.
This is due to trying to fix an issue with the refactored AtomVec class where pointers were not properly deleted when the atom style was changed. Now it is deleting too aggressively and thus the replicate command has a problem because it keeps two AtomVec instances around.

**Comment by akohlmey** [comment]
FYI: after addressing the segfault issue, the test fails with:
```
ERROR: All pair coeffs are not set (src/pair.cpp:238)
Last command: run             1
```
But that seems valid since there are no coeffs anywhere:
```
$ grep -i coeff data.spce.txt test15.in.txt
$
```

**Comment by stanmoore1** [comment]
This is now fixed, thanks @akohlmey!
