### ISSUE TITLE
[BUG] Accuracy regression in MSM

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#2178]
**Summary**

One of our internal kspace_style MSM tests is failing.

**LAMMPS Version and Platform**

Latest master

**Expected Behavior**

The accuracy of MSM should be close to the estimated accuracy. 

**Actual Behavior**

The accuracy of MSM is way off. This shows there was a bug introduced.

```
estimated absolute RMS force accuracy = 0.003320637100000004
computed absolute RMS force accuracy = 0.239851332013819
```

**Steps to Reproduce**

[test14.in.txt](https://github.com/lammps/lammps/files/4815795/test14.in.txt)

**Comment by stanmoore1** [comment]
May be related to #2177. Almost certainly caused by f78671c1a4d81e5907e929c9341d784e03881bd6.

**Comment by akohlmey** [comment]
Just to be certain: the issue here is that the printed value for the computed accuracy is off, not the forces or energies or anything else, correct?

**Comment by stanmoore1** [comment]
@akohlmey No, the script is comparing MSM forces to a highly refined Ewald sum as the ground truth, so the forces are off.

**Comment by akohlmey** [comment]
> @akohlmey No, the script is comparing MSM forces to the forces from a highly refined Ewald sum as the ground truth, so the MSM forces are off.

that is very peculiar, since we do have tests run via ctest comparing forces, energies, and stress and those do not show a difference since commit 8691579def0e96eab37b2731808dc499cfe6cc54

**Comment by akohlmey** [comment]
I can only speculate what made this work in one case and fail in another. The most likely explanation is that the provided test example here replaces the kspace style and that is not yet tested for in the new tests (there is not yet a tester tool for kspace styles).

**Comment by stanmoore1** [comment]
I confirm this is fixed, thanks!
