### ISSUE TITLE
[Feature Request] delete random atoms by type

### ISSUE THREAD

**Issue by nbobbitt** [lammps/lammps#2193]
It would be very useful to have the ability to delete atoms in a specific region randomly by type (e.g. delete N atoms of Type 1).

**Comment by jrgissing** [comment]
you can achieve this with the new "set type/subset" option. for example, you could create a group of the specific atoms eligible for deletion, set N atoms to a new type and delete all atoms of that type

**Comment by akohlmey** [comment]
yup. that is the way to do it. it is easy to add an atom type with create_box or with the "extra" keywords when reading from a file, if need be, the pair style can be temporarily changed to "zero", which just requires a catchall "pair_coeff * *" statement and then these manipulations are easy. the original force field can then be restored, if needed.
