### ISSUE TITLE
[BUG] Some tests fail in Fedora 32 rpm build

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#2194]
**Summary**

```
The following tests FAILED:
         21 - MolPairStyle:lj_class2_coul_table (Failed)
        104 - Utils (Failed)
        106 - PotentialFileReader (Failed)
Errors while running CTest
```
with
```
[ RUN      ] PairStyle.plain
/home/junghans/packages/lammps/lammps-patch_15Jun2020/unittest/force-styles/pair_style.cpp:589: Failure
Expected: (err) <= (5 * epsilon)
  Actual: 0.00016379107970628394 vs 2.4999999999999998e-06
[  FAILED  ] PairStyle.plain (70 ms)
```
and
```
[ RUN      ] Utils.potential_file
/home/junghans/packages/lammps/lammps-patch_15Jun2020/unittest/utils/test_utils.cpp:314: Failure
Value of: utils::get_potential_units(path, "EAM")
Expected: is equal to 0x5619245b7728 pointing to "metal"
  Actual: ""
[  FAILED  ] Utils.potential_file (42 ms)
```
and
```
106/107 Test #106: PotentialFileReader ...........................***Failed    0.02 sec
[==========] Running 11 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 11 tests from PotentialFileReaderTest
[ RUN      ] PotentialFileReaderTest.Si
```

**LAMMPS Version and Platform**

Lammps: Jun 15 2020
Fedora 32 (gcc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1))

**Expected Behavior**

Tests pass

**Actual Behavior**

Tests fail

**Steps to Reproduce**

```
fedpkg clone lammps
cd lammps
wget https://gist.github.com/junghans/ed292a1376489685e37001536fb7d5d9/raw/42184f742c1f064aa4d4cdce2e02421e9f43e9e4/lammps.spec
spectool -g lammps.spec
fedpkg --release f32 local
```

**Further Information, Files, and Links**

[Build log](https://github.com/lammps/lammps/files/4839782/build.txt.zip)

**Comment by akohlmey** [comment]
With the current test setup, all "coul_table" tests are highly sensitive to choice of compiler and compiler flags and are thus ok to fail with the current setup, if the difference is moderate and happening only for a small number of values. It is not clear at the moment, if this is an intrinsic feature of the table lookup method or due to something else.

The other issues should be fixed in master already.

**Comment by junghans** [comment]
Ok, I will give the next release a try again. Maybe you could make the "coul_table" tests less sensitive or exclude them from the default set of tests. Having tests that are too sensitive and spuratically fail, isn't optimal for the users / hpc admins that just want to see if lammps is compiled correctly on their machines.

**Comment by akohlmey** [comment]
> Ok, I will give the next release a try again. Maybe you could make the "coul_table" tests less sensitive or exclude them from the default set of tests. Having tests that are too sensitive and spuratically fail, isn't optimal for the users / hpc admins that just want to see if lammps is compiled correctly on their machines.

please note that what the pair style tester tool does is complex and not a binary yes/no unittest. making tests of this kind too insensitive is worse as real issues can go past such a test, and that is the priority here. the situation is explained in the documentation.  you can exclude tests yourself through the ctest command line, if you feel the need.

**Comment by junghans** [comment]
> > Ok, I will give the next release a try again. Maybe you could make the "coul_table" tests less sensitive or exclude them from the default set of tests. Having tests that are too sensitive and spuratically fail, isn't optimal for the users / hpc admins that just want to see if lammps is compiled correctly on their machines.
> 
> please note that what the pair style tester tool does is complex and not a binary yes/no unittest. making tests of this kind too insensitive is worse as real issues can go past such a test, and that is the priority here. the situation is explained in the documentation. you can exclude tests yourself through the ctest command line, if you feel the need.

Understood, I know how exclude tests, and I will do that for the rpm packages if needed, but my point was mainly if a normal user follows the standard `cmake`, `make`, `make test` procedure and gets a bunch of failing tests how is he suppose to know if that is due to the tests being too sensitive or having compiled lammps incorrectly.

**Comment by akohlmey** [comment]
> Understood, I know how exclude tests, and I will do that for the rpm packages if needed, but my point was mainly if a normal user follows the standard `cmake`, `make`, `make test` procedure and gets a bunch of failing tests how is he suppose to know if that is due to the tests being too sensitive or having compiled lammps incorrectly.

if people do that and do not read the documentation, then its their problem, as with so many things in LAMMPS.

**Comment by akohlmey** [comment]
please note that testing has to be explicitly enabled. so "normal" people won't get there unless they read the documentation, and then they should also be reading the discussion on what the tests mean. we can discuss changing this when questions about failing tests become a common issue on the mailing list.

**Comment by junghans** [comment]
`ENABLE_TESTING` is pretty standard in CMake as well, but you are right, let's see what happens on the mailings list. And as always if users don't test, they won't see any issues ;-) 

In the end, I just wanted to make sure these falling tests are not critical before I roll the lammps packages for fedora and openSUSE.

**Comment by junghans** [comment]
A small update with the pre-release from Jun30 2020 only one test still fails:
```
[ RUN      ] Utils.potential_file
/home/junghans/packages/lammps/lammps-patch_30Jun2020/unittest/utils/test_utils.cpp:333: Failure
Value of: utils::get_potential_units(path, "EAM")
Expected: is equal to 0x55d303044799 pointing to "metal"
  Actual: ""
[  FAILED  ] Utils.potential_file (37 ms)
...

99% tests passed, 1 tests failed out of 118

Total Test time (real) =  17.95 sec

The following tests FAILED:
	112 - Utils (Failed)
Errors while running CTest
```
