### ISSUE TITLE
LAMMPS docs only builds with enchant installed

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#2208]
**Summary**

Since https://github.com/lammps/lammps/commit/97b11ea746d283a4996c00df0bda8f784cfceb42 the LAMMPS docs can only be built with `enchant` installed. It is no longer optional, because the extension is installed in the venv and thus configured. I would revert to the previous behavior as it causes more problems than it solves or add a better check for detecting the C library.

**LAMMPS Version and Platform**

current master

**Expected Behavior**

Build documentation, e.g. HTML only output.

**Actual Behavior**

```
make html
....
Extension error:
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found and maybe needs to be installed.
See https://pyenchant.github.io/pyenchant/install.html
for details
)
```

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
please check out commit 1815ab610ec67c793bfc0ec485ba4b278ee025ee

**Comment by rbberger** [comment]
@akohlmey looks good!
