### ISSUE TITLE
Seg fault with replicate

### ISSUE THREAD

**Issue by sde4** [lammps/lammps#2221]
Summary
Replicate command is giving segmentation fault with new lammps dev version tagge: patch_15Jun2020 

"line 12: 213850 Segmentation fault"

LAMMPS Version and Platform: patch_15Jun2020 

OS name: GNU/Linux
OS release: 3.0.101-108.63-default
Hardware p;atform: x86_64

Steps to Reproduce
input file:
units       metal

boundary    p p p

box tilt large

atom_style      atomic

read_data       data.si

pair_style      tersoff
pair_coeff      * * SiCGe.tersoff  Si(C)

neighbor    0.3 bin

replicate 3 3 3

data.si
#Si data file for LAMMPS

8 atoms

1 atom types

        0.0000000000         5.4500000000 xlo xhi
        0.0000000000         5.4500000000 ylo yhi
        0.0000000000         5.4500000000 zlo zhi
        0.0000000000         0.0000000000         0.0000000000 xy xz yz

Masses

1        28.0855000000

Atoms

1 1         4.7687500000         4.7687500000         4.7687500000
2 1         4.7687500000         2.0437500000         2.0437500000
3 1         2.0437500000         4.7687500000         2.0437500000
4 1         2.0437500000         2.0437500000         4.7687500000
5 1         0.6812500000         0.6812500000         0.6812500000
6 1         0.6812500000         3.4062500000         3.4062500000
7 1         3.4062500000         0.6812500000         3.406250000
8 1         3.4062500000         3.4062500000         0.6812500000

Potential file: SiCGe.tersoff

Si(B)  Si(B)   Si(B)  3.0 1.0 1.3258 4.8381 2.0417 0.0000 22.956
             0.33675  1.3258  95.373  3.0  0.2  3.2394  3264.7

**Comment by akohlmey** [comment]
This bug should be fixed in the 30 June 2020 version.

**Comment by akohlmey** [comment]
Yup, just confirmed. This does not segfault anymore.

**Comment by sde4** [comment]
yes. Thanks Dr. Axel!
