### ISSUE TITLE
[BUG] reset_ids segfaulting with "sort yes"

### ISSUE THREAD

**Issue by wverestek** [lammps/lammps#2224]
**Summary**

rest_ids leads to a segfault when using the "sort yes" option.

**LAMMPS Version and Platform**

LAMMPS (30 Jun 2020)
Linux Ubuntu (18.04), compiled with cmake  (3.13.2) and Gnu Compiler (7.5.0)

**Expected Behavior**

Reset atom IDs for the system, including all the global IDs stored for bond, angle, dihedral, improper topology data. This will create a set of IDs that are numbered contiguously from 1 to N for a N atoms system. If the sort keyword is used with a setting of yes, then the assignment of new atom IDs will be the same no matter how many processors LAMMPS is running on. This is done by first doing a spatial sort of all the atoms into bins and sorting them within each bin. Because the set of bins is independent of the number of processors, this enables a consistent assignment of new IDs to each atom.

**Actual Behavior**

segfault if option "sort yes"

**Steps to Reproduce**
##############################################
# LAMMPS atomistic input script
units           real
#units		metal
atom_style      full

# Interaction potential definition
pair_style      lj/cut/coul/cut 5
#pair_style	 airebo 2.5 1 0

region          box block 0 20   0 5   0 5
create_box      1 box
create_atoms    1 single 2 2.5 2.5
create_atoms    1 single 4 2.5 2.5
create_atoms    1 single 6 2.5 2.5
create_atoms    1 single 8 2.5 2.5

mass            * 12.0
pair_coeff      * * 0.05400 4.01000
#pair_coeff	* * /opt/lammps_git_master/potentials/CH.airebo	C

reset_ids       sort yes
############################

**Further Information, Files, and Links**

without "sort yes" or setting "sort no" lammps is not segfaulting
[lammps_reset_ids.zip](https://github.com/lammps/lammps/files/4902745/lammps_reset_ids.zip)

**Comment by akohlmey** [comment]
should be fixed with commit 0c89b517a5b6052de2bd804315676461df05c748
the issue was that your system was too small and that atoms all had the same coordinate in some dimension resulting in a zero volume of the bounding box. both of which led to invalid numbers for sorting bins and thus causing the segmentation fault.
