### ISSUE TITLE
Loop through all variables is not possible due to private variables

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#223]
In Atomify, I'd like to list all equal and atom style variables for live plotting. In principle, I could parse all commands and recognize any variable command, but I'd rather access the Variable class directly. In current implementation, variables _nvar_ and _names_ are private, so they remain inaccessible even using the library. There is no way to iterate through all variable names.

After previous discussions we've had about similar issues, I suggest adding an extract function as we have in the Pair class so such variables can be accessed without changing variable access.

**Comment by akohlmey** [comment]
...or could also just modify the Info class to have a suitable "getter" that will return a list of all variables, that test positive on variable->equalstyle() or variable->atomstyle(). It can already print lists of variables.

**Comment by andeplane** [comment]
Or that :P Is a void get_variables(char **names, int &numVariables) reasonable?
I can then work directly with Variable to test equalstyle and atomstyle on each variable.

**Comment by akohlmey** [comment]
i'd rather go for `const char **get_variables(int &num);`. Any error condition could be signaled by returning `NULL`.

**Comment by andeplane** [comment]
Ok!

But isn't names being allocated in Variable::set? So it is NULL until the first variable is being set.

**Comment by akohlmey** [comment]
But that wouldn't make a difference to any code "consuming" the result of such a call to `Info::get_variables()`. You'll have to deal with a NULL result anyway and cannot access any variables in either case. If you want to differentiate, you can store `num = 0;` for no problems, no variables and `num = -1;` otherwise. I currently cannot think of a condition, where the second case would happen anyway.

**Comment by akohlmey** [comment]
You should still keep in mind that a non-NULL return value and `num == 0` would be legal.

**Comment by akohlmey** [comment]
Just submitted a pull request implementing the accessor. You probably also want to have a look at these other APIs in Info, that might be useful to you. So having an instance of `LAMMPS_NS::Info` available inside your code, might be helpful beyond variable names.
```
  bool is_active(const char *, const char *);
  bool is_defined(const char *, const char *);
  bool is_available(const char *, const char *);

  bool has_gzip_support() const;
  bool has_png_support() const;
  bool has_jpeg_support() const;
  bool has_ffmpeg_support() const;
  bool has_exceptions() const;
```

In general, i'd favor using the Info class for introspection with simple abstractions over digging into the individual classes directly (even in cases where it is possible). Going through Info should allow to maintain a consistent API, even in most cases, where the underlying implementation changes.
