### ISSUE TITLE
compiling error on Summit@OLCF

### ISSUE THREAD

**Issue by lwan86** [lammps/lammps#2232]
**Summary**

Compiling error: 
c++: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?

**LAMMPS Version and Platform**

LAMMPS version:
commit 284b1618f9de225b8e7e0a5225b6f29f856dff42
Merge: e2e4305 83291fd
Author: Axel Kohlmeyer <akohlmey@gmail.com>
Date:   Sat Jul 11 18:30:27 2020 -0400

Platform:
Summit
xl/16.1.1-7   
spectrum-mpi/10.3.1.2-20200121   
cuda/10.1.243   
cmake/3.17.3

**Details**

cmake command:
cmake -D PKG_GPU=yes -D GPU_API=cuda -D GPU_ARCH=sm_70 -D PKG_USER-ADIOS=yes -DADIOS2_DIR=/ccs/home/eisen/summit/lib64/cmake/adios2/ -D PKG_MANYBODY=yes -D PKG_KSPACE=yes -D PKG_MOLECULE=yes -D PKG_OPT=yes ../lammps/cmake/

I could build LAMMPS on Summit successfully using the same configuration a few weeks before.
I also tried gcc/6.4.0, same error.

**Comment by akohlmey** [comment]
try adding `-D CMAKE_TUNE_FLAGS=""`

**Comment by akohlmey** [comment]
> try adding `-D CMAKE_TUNE_FLAGS=""`

@lwan86 please let us know whether this workaround resolves your compilation issues. Thanks.

**Comment by lwan86** [comment]
@akohlmey Yes, it works. Thanks for the help! Let me close this ticket.
