### ISSUE TITLE
HAdresS example

### ISSUE THREAD

**Issue by almeida85** [lammps/lammps#2244]
**Summary**
HAdresS example

**LAMMPS Version and Platform**

Latest

**Details**

Hello,
I am new with LAMMPS and want to do Hamiltonian Adaptative Resolution simulations (HAdresS). According to the authors, the method is "now a standard user-contributed feature of LAMMPS", but the example is not in the USER folder. It is however in the branch https://github.com/hadress/lammps/tree/USER-HADRESS/examples/USER/hadress (from the authors), but it is 4 years old.
Was this example removed from the stable LAMMPS release?
I downloaded and installed the USER version of the previous link and tried to run the example, but I got this error:
```
units		real
atom_style	full/hars
ERROR: Unknown atom style (../atom.cpp:507)
```

What should I do?

Thanks in advance

**Comment by junghans** [comment]
HAdresS was never included in mainstream lammps (see #100), you will need to build and run that special version to use it.

Also see: https://sites.google.com/view/hadressmethod/method
