### ISSUE TITLE
[BUG] reset_atom_ids ommits angles, dihedrals and impropers

### ISSUE THREAD

**Issue by wverestek** [lammps/lammps#2251]
**Summary**

reset_atom_ids does not set atom ID for angles, dihedrals and impropers

**LAMMPS Version and Platform**

LAMMPS (21 Jul 2020) on Ubuntu 20.04.1 LTS

**Expected Behavior**

atom IDs angles, dihedrals and improper should be reset according to new atom IDs

**Actual Behavior**

ID for angles, dihedrlas and imropers get initlized as 0 and then not updated. 

**Steps to Reproduce**

see attached file 
[reset_atom_id.in.txt](https://github.com/lammps/lammps/files/4982357/reset_atom_id.in.txt)

**Comment by akohlmey** [comment]
@wverestek thanks for the report. The fix for this issue is in PR #2252

**Comment by wverestek** [comment]
> @wverestek thanks for the report. The fix for this issue is in PR #2252

@akohlmey Thanks for the quick fix
