### ISSUE TITLE
Infinite loop in PRD example if compiled with -DLAMMPS_BIGBIG

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#227]
The PRD code from REPLICA seems to have an issue when compiled using `-DLAMMPS_BIGBIG`. This can easily be reproduced by running the PRD example using `mpirun -np 4`. That example gets stuck forever. `-DLAMMPS_SMALLBIG` works. Tested with both OpenMPI and MPICH.

**Comment by akohlmey** [comment]
@sjplimp pull request #228 fixes this issue for me
