### ISSUE TITLE
GenerateBinaryHeader appears to create multiply defined variables

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#2294]
https://github.com/lammps/lammps/blob/43f6fa4b294d231133f5954336df34fbe0d8351e/cmake/Modules/LAMMPSUtils.cmake#L74-L87

The `foreach` in this function will create multiple definitions of the `${varname}[]` and `${varname}_size` variables when `files` is a list with more than one entry.

**Comment by rbberger** [comment]
Nice catch! Yes, indeed. We only use it with a single file as input in the GPU package, but yes the interface implies something else.

**Comment by ellio167** [comment]
FYI, I tested this on a 5mb file.  xxd takes 1 sec.  cmake takes 14 sec.  (compiling the resulting file takes 5 sec. with `gcc`; all times are with my macbook pro).

So there is a significant overhead to using the native cmake implementation.  (In many use cases you will not have a large file, so this is not a problem.)

Ultimately, something like the proposed `std::embed` is needed 
https://thephd.github.io/vendor/future_cxx/papers/d1040.html

**Comment by rbberger** [comment]
Embedding 5MB binary blobs in a library/executable?

**Comment by ellio167** [comment]
It has been the practice of the KIM project to embed model parameter files in the associated library.  It is conceivable that, there, we would embed files in the 100's MB size range. (This will require splitting the file into chunks so that compile time/memory does not explode.) (Maybe this will need to change in future...)

**Comment by akohlmey** [comment]
> It has been the practice of the KIM project to embed model parameter files in the associated library. It is conceivable that, there, we would embed files in the 100's MB size range. (This will require splitting the file into chunks so that compile time/memory does not explode.) (Maybe this will need to change in future...)

Out of curiosity: do you compress those files before embedding?

**Comment by ellio167** [comment]
Not at the moment;  I've thought about it.  The use cases we already have where large files occur are cases where compression does not result in significant size reduction.
