### ISSUE TITLE
Check all URLs in the LAMMPS manual to be current and valid

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2301]
**Summary**

In preparation for the upcoming stable release we should check whether any URLs in the LAMMPS manual (and README files and sources?) are current and pointing to the expected up-to-date destination.

**Comment by eagunn** [comment]
@akohlmey I'm going through the new documentation now. Mainly for my own education but I will be checking URLs as I go.
Thank you for the huge amount of work. This is a needed and very welcome upgrade.
As I find typos and small issues, do you want me to create a WIP PR against the master branch?
Or do you have another place, perhaps a personal branch, where you would like to consolidate small fixes?

**Comment by akohlmey** [comment]
> @akohlmey I'm going through the new documentation now. Mainly for my own education but I will be checking URLs as I go.
> Thank you for the huge amount of work. This is a needed and very welcome upgrade.
> As I find typos and small issues, do you want me to create a WIP PR against the master branch?
> Or do you have another place, perhaps a personal branch, where you would like to consolidate small fixes?

Thanks for the kind words. How you want to handle this is up to you. You can report issues here and just cut-n-paste `git diff`  output here (as quoted text blocks), or create a draft pull request and accumulate changes there. Please also see PR #2316 to avoid overlaps.

**Comment by akohlmey** [comment]
@eagunn @mmansell7 all usable content from your contributions have been merged into master now. Some with some additional edits and a few slightly differently.  Thanks again for your efforts and your contributions. We are on the path to have the next stable release of LAMMPS be a release that we are going to be particularly proud of.

**Comment by akohlmey** [comment]
I think the main goal of this issue has been achieved.

**Comment by mmansell7** [comment]
Thanks @akohlmey. I appreciate your feedback. If, in the future, I come across any substantially dubious links/references in the documentation or source code, I will bring it to the developers' attention.
