### ISSUE TITLE
[BUG] fix/wall/gran region contacts keyword - per-atom array generated differs from documentation description. Also, an issue with 'compute reduce sum' output.

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#2306]
**Summary**
Refer #2121 
1. Bugs in fix wall/gran/region with the 'contacts' option enabled:
According to the documentation this will generate an 8 column per-atom array f_ID[1], fix_ID[2], ..., f_ID[8].
The table given towards the end of this doc page (https://lammps.sandia.gov/doc/fix_wall_gran_region.html) specifies what each of those 8 columns store.
However, I have found the following potential bugs:

a) As per documentation, f_ID[1] stores 1 if the atom is in contact with wall, 0 otherwise.
My observation: f_ID[1] actually stores the atom ID if it is in contact, 0 otherwise.
Kindly update the documentation saying that f_ID[1] stores the atom ID if grain is in contact. Or update the program so that it stores 1 or 0 depending of the contact status.

b) As per documentation, f_ID[5] stores delta_x between the grain and the wall.
My observation: Although I am not too sure, f_ID[5] seems to be stroing x+radius-dx. The numbers stored in f_ID[5] are very close to (but not exactly equal to) x+radius. [x=x-coord of atom, radius=radius of atom].
Along similar lines, f_ID[6] and f_ID[7] store data which differs from the description given in documentation. f_ID[6] stores values very close to y+radius, and f_ID[7] stores values very close z+radius (0 for 2d) 
Kindly update the documentation to clarify what it does or modify the fix to store delta_x, delta_y, delta_z.

2. Issue with 'compute reduce' command. 
I believe the 'compute reduce sum' which sums up elements in an array and 'compute reduce ave' which evaluates the average of the elements in an array - both seem to be giving the same output (i.e., average value). I have used 'compute reduce sum' and 'compute reduce ave' on a per-atom array and output it via custom thermo command. I see that both the computes output the same numbers (average).
However, if I define an equal styled variable to store the output of compute sum, and then output that variable via thermo output, then the variable output is sum of the array elements as expected.

**LAMMPS Version and Platform**

LAMMPS (21 Jul 2020). 
MacOS 10.15.6.

**Steps to Reproduce**
To reproduce these issues, please run the attached shell script (run_lammps_simulation.sh) and see thermo output to see the 'compute reduce' issue. Check the dump files in 
"dumpforces" (ex: dumpforces/dump.deforces.60000.dump when the grains-walls contact first occurs) to check the issue with fix wall/gran/region 'contacts' keyword.

[lammps_bugreport.zip](https://github.com/lammps/lammps/files/5113537/lammps_bugreport.zip)

**Comment by rbberger** [comment]
> 
> a) As per documentation, f_ID[1] stores 1 if the atom is in contact with wall, 0 otherwise.
> My observation: f_ID[1] actually stores the atom ID if it is in contact, 0 otherwise.
> Kindly update the documentation saying that f_ID[1] stores the atom ID if grain is in contact. Or update the program so that it stores 1 or 0 depending of the contact status.

We updated fix wall/gran to only store 1.0 or 0.0, but forgot to propagate this change to fix wall/gran/region.

> 
> b) As per documentation, f_ID[5] stores delta_x between the grain and the wall.
> My observation: Although I am not too sure, f_ID[5] seems to be stroing x+radius-dx. The numbers stored in f_ID[5] are very close to (but not exactly equal to) x+radius. [x=x-coord of atom, radius=radius of atom].
> Along similar lines, f_ID[6] and f_ID[7] store data which differs from the description given in documentation. f_ID[6] stores values very close to y+radius, and f_ID[7] stores values very close z+radius (0 for 2d)
> Kindly update the documentation to clarify what it does or modify the fix to store delta_x, delta_y, delta_z.

After looking more closely at the code, indices 5,6,7 don't store the delta but the coordinates of the contact point on the wall.

@vikaskok  Thanks for pointing these out, PR #2411 has the necessary changes.
