### ISSUE TITLE
Use Lammps logo for backlink? 

### ISSUE THREAD

**Issue by jan-janssen** [lammps/lammps#2323]
I am the lead develop of pyiron a integrated development environment for computational materials science which uses LAMMPS internally to execute molecular dynamics simulation. We recently updated our website and I was wondering if we can use the LAMMPS logo to reference the integration of LAMMPS and link back to the LAMMPS website: 
https://pyiron.org/collaborators/

**Comment by akohlmey** [comment]
@jan-janssen this should not be a problem, but the final decision on these matters is with @sjplimp

**Comment by sjplimp** [comment]
yes, that's fine - thanks for asking

**Comment by sjplimp** [comment]
also, if you would like the LAMMPS webpage to list a link to pyiron - then just provide me with a blurb
of appropriate text and an image or two if appopriate - see the PrePost or Offsite pages linked to from
the LAMMPS home page
