### ISSUE TITLE
Broken links on the sandia.gov lammps home page

### ISSUE THREAD

**Issue by eagunn** [lammps/lammps#2329]
**Summary**
The links to Slack Channel and IRC Channel pages from the lammps.sandia.gov home page are broken. The user gets a generic 404 page.

**LAMMPS Version and Platform**

NA

**Details**

I've been not-bothering to report this since it is relatively minor. But I noticed @sjplimp offer to do an update to the project homepage as part of the response to #2323, so it seemed like it might be a good time to address other issues on the same page.

I haven't done an exhaustive check of the links on that page. I was simply curious if the Slack channel was available for all devs or only by implementation for core devs, so I clicked on the link one day.

**Comment by akohlmey** [comment]
For matters concerning the homepage at sandia.gov, best contact @sjplimp directly via personal e-mail. It probably got broken during some recent updates of the process of updating it.

Access to the slack channel is open to all people doing programming on LAMMPS, not just core developers. The information that was on that website is also contained in the manual: https://docs.lammps.org/Modify_contribute.html

(note that https://docs.lammps.org follows the development and is automatically updated after pull requests are merged, so it is a good way to verify that your own contributions to the manual were merged correctly).
