### ISSUE TITLE
[BUG] Load balancing may make subdomains too small

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#2337]
**Summary**

One of our run tests (`examples/balance/in.balance.var.dynamic`) sometimes loses atoms due to subdomains becoming too small.

**LAMMPS Version and Platform**

current master

**Expected Behavior**

Subdomain size will stay larger than neighbor skin.

**Actual Behavior**

```
Per MPI rank memory allocation (min/avg/max) = 4.138 | 4.391 | 4.67 Mbytes
Step Temp E_pair E_mol TotEng Press Volume 
     500   0.55526241   -6.2793396            0   -5.4466542   -2.0595015    4738.2137 
     550   0.53879347   -6.2554274            0   -5.4474393   -1.9756834    4738.2137 
     600   0.54275982   -6.2616799            0   -5.4477437   -1.9939993    4738.2137 
     650   0.54526651    -6.265098            0   -5.4474027   -2.0303672    4738.2137 
     700   0.54369381    -6.263201            0   -5.4478642   -1.9921967    4738.2137 
     750   0.54452777   -6.2640839            0   -5.4474964   -1.9658675    4738.2137 
     800   0.55061744   -6.2725556            0   -5.4468359   -2.0100922    4738.2137 
WARNING: Proc sub-domain size < neighbor skin, could lead to lost atoms (src/domain.cpp:964)
     850   0.55371614   -6.2763992            0   -5.4460326   -2.0065329    4738.2137 
WARNING: Proc sub-domain size < neighbor skin, could lead to lost atoms (src/domain.cpp:964)
     900   0.54756622   -6.2668303            0   -5.4456863   -1.9796122    4738.2137 
WARNING: Proc sub-domain size < neighbor skin, could lead to lost atoms (src/domain.cpp:964)
     950   0.54791593   -6.2673161            0   -5.4456477   -1.9598278    4738.2137 
WARNING: Proc sub-domain size < neighbor skin, could lead to lost atoms (src/domain.cpp:964)
ERROR: Lost atoms: original 4000 current 3998 (src/thermo.cpp:428)
```

**Steps to Reproduce**

Run the `examples/balance/in.balance.var.dynamic` example on 8 MPI processes.

**Further Information, Files, and Links**

https://ci.lammps.org/job/dev/job/pull_requests/job/ubuntu/job/run_tests/job/cmake_testing_mpi/73/testReport/junit/tests.test_examples/BalanceTestCase/test_balance_var_dynamic_parallel/attachments/BalanceTestCase_test_balance_var_dynamic_parallel_stdout.log

**Comment by akohlmey** [comment]
This may be related to issue #1655

**Comment by ohenrich** [comment]
I observe lost atoms also with the rcb style. The problem gets progressively worse as the average number of atoms per process decreases.

**Comment by rbberger** [comment]
@sjplimp please take a look at this. Can we enforce a minimal sub-domain size of neighbor skin?

**Comment by sjplimp** [comment]
@rbberger @ohenrich I'll take a look.  But the practical answer is use rcb, not xshift (which in this case is a 1d balancer).
RCB already has the smarts to keep the subbox as cubic as it can be.  I ran this test script on 128 RCB procs w/out any warnings.

**Comment by sjplimp** [comment]
@ohenrich can you post your example script (small and simple as possible) which gives similar warnings with RCB?
And are you using a version of LAMMPS that has a line in src/rcb.cpp which says this:
NEW version: each RCB cut is tested in all dimensions

**Comment by ohenrich** [comment]
@sjplimp @rbberger Yes, I'm using the latest version of LAMMPS in the master branch, which contains the 'NEW version ..." line (commit d1af1aa12d3e9210408fe572940d5ec038604741, Author: Richard Berger <richard.berger@temple.edu>, Date: Thu Nov 19 11:13:50 2020 -0500). The problem persists.

Please find attached the data and input files as well as stdout on 4 (works) and 8 (fails) MPI-tasks with load balancing and 8-MPI tasks without load balancing (works). Thanks!

[files.zip](https://github.com/lammps/lammps/files/5572508/files.zip)

**Comment by sjplimp** [comment]
It's not clear to me this is the same issue.  In Oliver's script there are a zillion warnings about FENE bonds too long, no atoms are lost.  A bond atom is not found at some point, but that's different than a lost atom.
Likely not due to the subdomain being too small.  Maybe due to ghost atoms not being acquired correctly.

**Comment by akohlmey** [comment]
> It's not clear to me this is the same issue. In Oliver's script there are a zillion warnings about FENE bonds too long, no atoms are lost. A bond atom is not found at some point, but that's different than a lost atom.
> Likely not due to the subdomain being too small. Maybe due to ghost atoms not being acquired correctly.

Whatever the cause in that case, we do need some protection from the shift load balancing creating too small subdomains. If we cannot establish a constraint in the optimization process itself, we should make a backup of the original settings and revert to those if the updated settings are creating too small subdomain sizes. I have seen reports like those for a variety of systems but am identifying the load balancing as the underlying problem only now in retrospect.

**Comment by sjplimp** [comment]
I agree we need to do something about shift as well as RCB to avoid too-small domains in a dim, if possible.  I'm testing a couple ideas.  The shift script is not being as aggressive as possible in checking for reneighboring, and it's enough of a toy problem that particles may be moving beyond the skin distance in a single step, both of which can induce problems which are not really the fault of the balancer.  But I think Oliver's script is having problems due to something else.
