### ISSUE TITLE
Ellipsoid-Substrate Potential 

### ISSUE THREAD

**Issue by aershadinia** [lammps/lammps#234]
I am trying to develop a code that calculates the energy of interaction between an ellipsoidal body and a LJ flat surface. The exact formula for this interaction is introduced by M. Babadi and M. R. Ejtehadi (EPL, 77 (2007) 23002). Using this potential formula, I managed to calculate formulas for force and torque that is done by a simple derivation. 

One has to note that the above-mentioned article assumes that inside each ellipsoidal body there are abundance of very small--compared to ellipsoid's diameters--LJ particles. The distribution of these particles are assumed to be superposition of a constant term and and a general quadratic form. 
My code only works for bodies with a uniform distribution of LJ particles, since there it is possible to define other types of ellipsoids in LAMMPS. 

So far I have uploaded a header and it's implementation, named fix_wall_asphere.h fix_wall_asphere.cpp in src/ASPHERE and I am waiting for the response.

**Comment by akohlmey** [comment]
Please note, that external contributions of the kind in #235 are usually added to the USER-MISC package and not to one of the standard packages. Examples would then be added to a folder in examples/USER/. Please also note the various README files in the respective directories.

**Comment by akohlmey** [comment]
closed due to inactivity and the related pull request being withdrawn by submitter.
