### ISSUE TITLE
[Feature Request] Replace instances of NULL with nullptr

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2345]
**Summary**

Since we now require a C++11 compatible compiler to compile LAMMPS, we should also replace uses of `NULL` with `nullptr`.

This has two advantages
1. `nullptr` is an intrinsic element of C++11, no header needs to be included to access it.
2. Contrary to C compilers, C++ compilers define `NULL` as 0 (and not as `(void *)0`), while `nullptr` is a real pointer and thus the compiler can provide warnings if by accident there is a mismatch and one is mixing up a scalar and a pointer variable, it avoids ambiguities or unexpected choices of overloaded alternative functions and more.

**Further Information, Files, and Links**

https://embeddedartistry.com/blog/2017/03/08/migrating-from-c-to-c-null-vs-nullptr/

**Comment by eagunn** [comment]
@akohlmey I would be interested in volunteering for this work. Your description makes it sound reasonably straightforward if done with caution.

I'm not able to reach the blog entry you cite, nor the underlying website, although I certainly see the same URL pop up in search results. It's a pretty old link. I tried to get to it using the Wayback Machine but no joy. Do you have an updated link or contact info for the authors?

**Comment by akohlmey** [comment]
> @akohlmey I would be interested in volunteering for this work. Your description makes it sound reasonably straightforward if done with caution.
> 
> I'm not able to reach the blog entry you cite, nor the underlying website, although I certainly see the same URL pop up in search results. It's a pretty old link. I tried to get to it using the Wayback Machine but no joy. Do you have an updated link or contact info for the authors?

The website and the blog entry work for me just fine at this moment. The blog entry has a note, that it has been updated last year. There will likely be other websites with discussions on the same issue. This is not one that I consider particularly well fitting, but I just googled the topic and linked the first site that had a reasonable discussion of the topic, so that I don't have to give all the details.

**Comment by eagunn** [comment]
And now the page is popping up for me, also. I'll go through it and give the change a trial to see if I run into any obvious problems.

**Comment by eagunn** [comment]
Update: I've found a simple regex that appears to make the change safely while avoiding strings ("NULL") and NULL embedded in longer variable names (MPI_INFO_NULL, VECTOR_NULL, etc).

Unless you are in a hurry for this change, which I doubt, I will work on my local build to make sure I'm building as much of the code as I can before I create a PR. I've been doing fairly limited builds to date.

**Comment by akohlmey** [comment]
@eagunn thanks for the update. our timeline is to have another patch release next week. that will be the last option to include larger changes like this before the next stable release. after that patch release we will go to bugfix-only mode and encourage people to run tests and review the documentation. I expect to mostly have changes to the refine the new programmer guide section of the documentation.  depending on number and severity of bug reports/fixes we will have one or multiple release candidates.

**Comment by eagunn** [comment]
OK. I'll work on my build tomorrow morning to verify as much as I can locally. Then I can go ahead and submit a PR.

Would you prefer a WIP PR? I believe all the code will get built for that. But will the unit-tests get run also? 

This change should be pretty much a no-op but it touches 1000+ files, so I'd like to prove some of the code runs well as well as builds ok.

**Comment by akohlmey** [comment]
@eagunn we can run the full gamut of tests on the pull requests. For some of them, I have to enable it manually. We don't do this for everything because they take so long to run. The tests in the unittest folder are run on every update of a pull request, but they don't report failures, yet, unless the compilation fails. So it is necessary to look those results up. But I do that always, anyway.

**Comment by eagunn** [comment]
@akohlmey So far, I have applied these changes to .cpp and .h files in src and lib folders. Do you want same changes made to C++ code in the unittest folder? Or any other folders?

**Comment by akohlmey** [comment]
> @akohlmey So far, I have applied these changes to .cpp and .h files in src and lib folders. Do you want same changes made to C++ code in the unittest folder? Or any other folders?

Please revert any changes to lib/kokkos and lib/colvars. Those are (slightly adapted) copies from the corresponding upstream projects and thus any updates should be submitted to either https://github.com/Colvars/colvars or https://github.com/kokkos/kokkos, respectively, so the maintainers of those projects get to review and decide on those changes. Colvars, for example, may not be able to accept this kind of  change in the non-LAMMPS specific parts since they have to comply with compatibility requirements of other projects (like VMD) where their code is included.

Updating unittest is fine. Tools should be ok, too, but it may be advisable to check with the contributors of the code, if they are still actively maintaining their tool. For legacy compilation with GNU make on platforms like Centos 7.x an update to the make files may be needed to enable C++11 compatibility on compilers that have it disabled by default (like GNU c++ 4.8).

**Comment by eagunn** [comment]
Will revert changes to lib/kokkos and lib/colvars then see how far we get.

Will wait to make unittest or any other changes until we have a stable build passing all checks.

**Comment by eagunn** [comment]
Have found build log, thank you. Build now failing in lib/poems
I'm inclined to keep reverting problem folders rather than changing build options, for now, but await your direction.

**Comment by akohlmey** [comment]
> Have found build log, thank you. Build now failing in lib/poems
> I'm inclined to keep reverting problem folders rather than changing build options, for now

please keep reverting and see my comment on that subject on the pull request.

**Comment by eagunn** [comment]
PR has now passed all the automatic checks.
For the record, I walked back the nullptr changes to:
- lib/kokkos
- lib/colvars
- lib/poems
- lip/awpmd
- two #defines in STUBS/mpi.h
That last fix might be more correctly made with conditional compiler flag but I'd need some coaching for that.

I'd still like to go in and manually review some places where nullptr has been substituted for NULL in comments. The majority of these seem fine but in a few places NULL seems to have been used as a simple synonym for 0 or nothing and the meaning of the comment may be better preserved by putting the word NULL back. 

But I think I'll let the dust settle and give @akohlmey time to evaluate before I make any more changes.
