### ISSUE TITLE
[BUG]Failed to compile KOKKOS CUDA MPI when using force_uvm

### ISSUE THREAD

**Issue by jorox** [lammps/lammps#2346]
**Summary**

LAMMPS is failing to compile with KOKKOS CUDA MPI and UVM enabled

**LAMMPS Version and Platform**

I am using the 3Mar2020 stable version on Linux for NVIDIA Volta V100 GPU 

- Compiler GCC 7.3.0
- CUDA 10.1 library,
- OpenMPI 4.0.1
- `KOKKOS_ARCH=SNB,Volta70.` (Makefile.kokko_cuda_mpi)
- `KOKKOS_CUDA_OPTIONS ?= "enable_lambda,force_uvm"` (Makefile.kokkos)

**Expected Behavior**
[KOKKOS Extra Build Options](https://lammps.sandia.gov/doc/Build_extras.html#kokkos)
> The CMake option -DKokkos_ENABLE_CUDA_UVM=on or the makefile setting KOKKOS_CUDA_OPTIONS=enable_lambda,force_uvm enables the use of CUDA “Unified Virtual Memory” (UVM) in Kokkos. UVM allows to transparently use RAM on the host to supplement the memory used on the GPU (with some performance penalty) and thus enables running larger problems that would otherwise not fit into the RAM on the GPU.

**Actual Behavior**

LAMMPS fails to compile  at **pair_lj_cut_coul_cut_kokkos.cpp** upon instantiation of **EV_FLOAT**
`../../lib/kokkos/core/src/Kokkos_View.hpp(2006): error: static assertion failed with "Incompatible View copy construction"
`
`../../lib/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(2973): error: static assertion failed with "View assignment must have compatible spaces"
`
##### Affected files

- pair_kokkos.h(91)
- pair_kokkos.h(92)
- pair_kokkos.h(879)
- pair_kokkos.h(911)
- pair_lj_cut_coul_cut_kokkos.cpp(130)
- pair_lj_cut_coul_cut_kokkos.cpp(354)

##### Affected functions:

- LAMMPS_NS::pair_compute
- LAMMPS_NS::pair_compute_neighlist
- LAMMPS_NS::PairComputeFunctor
- LAMMPS_NS::PairLJCutCoulCutKokkos

Removing the `force_uvm` option compiles normally

**Steps to Reproduce**
Add the force_uvm option to Makefile.kokkos and compile LAMMPS
`
make yes-compress
`
`
make yes-manybody
`
`
make yes-misc
`
`
make yes-kokkos
`
`
make kokkos_cuda_mpi
`

``
**Further Information, Files, and Links**

`mpicxx -g -O3  -DLAMMPS_GZIP -DLMP_KOKKOS  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1 -DFFT_CUFFT	   -I./ -I../../lib/kokkos/core/src -I../../lib/kokkos/containers/src -I../../lib/kokkos/algorithms/src -I../../lib/kokkos/core/src/eti --std=c++11 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-lambda -mavx -arch=sm_70 -I/apps/sw/cuda/cuda_10.1.168_418.67/include   -c ../pair_lj_cut_coul_cut_kokkos.cpp
../../lib/kokkos/core/src/Kokkos_View.hpp(2006): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void>::type *) [with DataType=F_FLOAT *[3], Properties=<Kokkos::LayoutRight, LMPHostType>, RT=LMP_FLOAT *[3], RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>]" 
../../lib/kokkos/containers/src/Kokkos_ScatterView.hpp(697): here
            instantiation of "Kokkos::Experimental::ScatterView<DataType, Layout, ExecSpace, Op, 0, contribution>::ScatterView(const Kokkos::View<RT, RP...> &) [with DataType=F_FLOAT *[3], Op=0, ExecSpace=LMPHostType, Layout=Kokkos::LayoutRight, contribution=0, RT=LMP_FLOAT *[3], RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>]" 
../../lib/kokkos/containers/src/Kokkos_ScatterView.hpp(1283): here
            instantiation of "Kokkos::Experimental::ScatterView<RT, Kokkos::ViewTraits<RT, RP...>::array_layout, Kokkos::ViewTraits<RT, RP...>::execution_space, Op, <expression>, <expression>> Kokkos::Experimental::create_scatter_view(const Kokkos::View<RT, RP...> &) [with Op=0, duplication=0, contribution=-1, RT=LMP_FLOAT *[3], RP=<Kokkos::LayoutRight, Kokkos::Device<Kokkos::DefaultHostExecutionSpace, Kokkos::Cuda::memory_space>>]" 
../pair_kokkos.h(90): here
            instantiation of "LAMMPS_NS::PairComputeFunctor<PairStyle, NEIGHFLAG, STACKPARAMS, Specialisation>::PairComputeFunctor(PairStyle *, LAMMPS_NS::NeighListKokkos<LAMMPS_NS::PairComputeFunctor<PairStyle, NEIGHFLAG, STACKPARAMS, Specialisation>::device_type> *) [with PairStyle=LAMMPS_NS::PairLJCutCoulCutKokkos<LMPHostType>, NEIGHFLAG=1, STACKPARAMS=false, Specialisation=void]" 
../pair_kokkos.h(879): here
            instantiation of "EV_FLOAT LAMMPS_NS::pair_compute_neighlist<PairStyle,NEIGHFLAG,Specialisation>(PairStyle *, Kokkos::Impl::enable_if<<expression>, LAMMPS_NS::NeighListKokkos<PairStyle::device_type> *>::type) [with PairStyle=LAMMPS_NS::PairLJCutCoulCutKokkos<LMPHostType>, NEIGHFLAG=1U, Specialisation=void]" 
../pair_kokkos.h(911): here
            instantiation of "EV_FLOAT LAMMPS_NS::pair_compute<PairStyle,Specialisation>(PairStyle *, LAMMPS_NS::NeighListKokkos<PairStyle::device_type> *) [with PairStyle=LAMMPS_NS::PairLJCutCoulCutKokkos<LMPHostType>, Specialisation=void]" 
../pair_lj_cut_coul_cut_kokkos.cpp(130): here
            instantiation of "void LAMMPS_NS::PairLJCutCoulCutKokkos<DeviceType>::compute(int, int) [with DeviceType=LMPHostType]" 
../pair_lj_cut_coul_cut_kokkos.cpp(354): here
`
...
`
6 errors detected in the compilation of 
[make.out.txt](https://github.com/lammps/lammps/files/5177894/make.out.txt)
"/tmp/tmpxft_00015f4f_00000000-6_pair_lj_cut_coul_cut_kokkos.cpp1.ii".
`

**Comment by akohlmey** [comment]
Please try the current patch/development release.
This was possibly fixed in this commit: 2dd737e7655732ea90b7248f53571a9f712ea7bb

**Comment by jorox** [comment]
Checking out master and applying the patch has fixed the problem.
Thank you very much.
