### ISSUE TITLE
[Feature Request] Make memory_usage() member functions consistently report either double or bigint

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2350]
**Summary**

Many classes have a `memory_usage()` member function, but they are inconsistent in the way how they report the final usage.
The majority (~430) returns the number of bytes used as a `double`, but some (41) return a `bigint`.  We should make that consistent and because of `double` being the dominant usage, the ones using `bigint` should be converted. This will minimize breakage with external packages.

This also applies to some functions with other names, e.g. `MyPage<>::size()` that report memory usage.
It may also be worth to make a quick check that we don't have any (32-bit) integer overflows for large systems when computing those usage numbers.

Since we have a few disruptive changes already happening since the last stable release, it would be beneficial to do this right away, to minimize the amount of disruption on future releases.

Comments? Suggestions? Concerns?

**Comment by sjplimp** [comment]
I agree with the Summary, except that I think bigint is the natural choice for tallying memory usage.
I probably wrote the first memory_usage() methods before we added bigints to the code.
How hard would it be to change them all to bigint functions?  Can you automate it?
For external packages, it's probably a 2 line change, so I don't see that as significant.

**Comment by akohlmey** [comment]
> I agree with the Summary, except that I think bigint is the natural choice for tallying memory usage.

Using bigint vs double would matter the most if we would need a perfect tally to the last byte.  However, we only provide a rounded output and the memory usage computation is only done for large allocations.  But even in that case, there should currently not be a representation problem, since memory addresses are limited to less than 64-bit (48-bit on x86_64, IIRC) and a double can represent integers without truncation for up to 52 bits.

> I probably wrote the first memory_usage() methods before we added bigints to the code.
> How hard would it be to change them all to bigint functions? Can you automate it?

It can be semi-automated: i.e. the change itself can be automated, but a manual review of the computations to make certain to avoid overflows and which ancillary functions are called would be required in any case.  With grep-mode in emacs this is rather straightforward.  The recent include file review updated nearly 1200 files and was done in such a hybrid way.

> For external packages, it's probably a 2 line change, so I don't see that as significant.
