### ISSUE TITLE
[Feature Request] Make CMake variables for include files/directories consistent

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2352]
We currently have a mix of `XXX_INCLUDE_DIR` and `XXX_INCLUDE_DIRS` variables in the CMake configuration.
It would be more consistent to have them either all use DIR or DIRS.  Are there some conventions or published best practices that would prefer one over the other?

Suggestions? Comments? Objections?

**Comment by junghans** [comment]
Having a quick look `FindNetCDF.cmake` seems inconsistent.

**Comment by junghans** [comment]
> Having a quick look `FindNetCDF.cmake` seems inconsistent.

Nope that one seems right, too.

**Comment by akohlmey** [comment]
> Having a quick look `FindNetCDF.cmake` seems inconsistent.

There should be more. Or they are not in sync with the documentation. I just refactored the Build_extras.rst to use tabs for CMake vs. GNU make sections and noticed the different uses.

**Comment by junghans** [comment]
> > Having a quick look `FindNetCDF.cmake` seems inconsistent.
> 
> There should be more. Or they are not in sync with the documentation. I just refactored the Build_extras.rst to use tabs for CMake vs. GNU make sections and noticed the different uses.

Yeah, I think the documentation is just wrong, users should only use singular versions.
