### ISSUE TITLE
KOKKOS-accelerated vashishta potential

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#236]
The vashishta potential is very similar to the Stillinger-Weber potential which already has a KOKKOS implementation. 

I suspect that for someone familiar with KOKKOS, it could be a quick thing to do.

**Comment by akohlmey** [comment]
You can give it a try yourself or contact Stan directly. He seems to have a severe case of gitphobia.

**Comment by andeplane** [comment]
Ok, I'll give it a try tomorrow. It seems doable :)

**Comment by andeplane** [comment]
The OMP version works now.

**Comment by andeplane** [comment]
Added an implementation in https://github.com/lammps/lammps/pull/242

**Comment by stanmoore1** [comment]
> He seems to have a severe case of gitphobia.

I'm getting over it...
