### ISSUE TITLE
KOKKOS build broken after variable access change

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#237]
When I try to compile LAMMPS with KOKKOS package, it doesn't compile after commit https://github.com/lammps/lammps/commit/2c8a7a318a4a1a0786c0ebacabbde82cb6d9c683 where the variables
`double point[3],runit[3];`
were changed from public to private, and they are used in region_block_kokkos.cpp.

**Comment by akohlmey** [comment]
This has been fixed in subversion (twice), but is not merged into the git repo:
http://git.lammps.org/git/?p=lammps-ro.git;a=commitdiff;h=c0b98f5299e0b13802ff7ec32f162f477f407682

@sjplimp will hopefully do so soon.
