### ISSUE TITLE
rpmlist warnings on openSUSE

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#2385]
On openSUSE rpmlint shows the following warnings:
```
lammps-data.noarch: W: files-duplicate /usr/share/lammps/potentials/Ni_Zuo_JPCA2020.snapparam /usr/share/lammps/potentials/Cu_Zuo_JPCA2020.snapparam
liblammps0.x86_64: W: shared-lib-calls-exit /usr/lib64/liblammps.so.0 exit@GLIBC_2.2.5
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.
```
Mainly just checking these are just false positives.

Regarding `Ni_Zuo_JPCA2020.snapparam` and `Cu_Zuo_JPCA2020.snapparam` being the same, that might be correct, so just making sure. @athomps, do you know?

Regarding library calling `exit()`, I thought we fixed that at some point when compiling with `LAMMPS_EXCEPTIONS`, which is the case here as `ENABLE_TESTING` is on. @rbberger, any insights?

**Comment by akohlmey** [comment]
> Regarding library calling `exit()`, I thought we fixed that at some point when compiling with `LAMMPS_EXCEPTIONS`, which is the case here as `ENABLE_TESTING` is on. @rbberger, any insights?

`Error::done()` calls exit and does not throw an exception because the user requests an exit through the "quit" input command or runs the LAMMPS executable with either the -help or the -r2data flag.

**Comment by akohlmey** [comment]
The .snapparam files do not provide model specific coefficients (those are in .snapcoeff files) but have general settings for how to apply the SNAP potential. Those may be the same for different models.
