### ISSUE TITLE
[BUG] Segmentation fault with USER-PTM package

### ISSUE THREAD

**Issue by grsmirnov** [lammps/lammps#2386]
**Summary**

compute ptm/atom command (USER-PTM package) causes a segfault in the current version (18Sep2020), works correctly in the  stable_7Aug2019 version

**LAMMPS Version and Platform**
Version: unstable / patch_18Sep2020
OS: Linux on x86_64
Compiler: GNU C++ 7.5.0 with OpenMP not enabled
C++ standard: C++14
MPI v3.1: Open MPI v2.1.1

**Actual Behavior**

Segmentation fault

**Steps to Reproduce**

lammps/examples/USER/ptm/ptm_example.in

**Comment by akohlmey** [comment]
@grsmirnov thanks for your bug report. this will be fixed in the next patch release
