### ISSUE TITLE
[BUG] make yes-WRONG-NAME does not set the error status

### ISSUE THREAD

**Issue by slitvinov** [lammps/lammps#2387]
`src/Makefile` does not set the exit status if the package does not exist
```
$ make yes-WRONG-NAME
Package WRONG-NAME does not exist
$ echo $?
$ 0
```

I think a change like this should be enough: 
```
diff --git a/src/Makefile b/src/Makefile
index 8216d51..af29053 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -365,6 +365,7 @@ yes-%:
          then cp Makefile.package.settings.empty Makefile.package.settings; fi
        @if [ ! -e $(YESDIR) ]; then \
          echo "Package $(@:yes-%=%) does not exist"; \
+         exit 2; \
        elif [ -e $(YESDIR)/Install.sh ]; then \
          echo "Installing package $(@:yes-%=%)"; \
          cd $(YESDIR); $(SHELL) Install.sh 1; cd ..; \
```

**Comment by akohlmey** [comment]
@slitvinov thanks for the report and the suggestion to address it. we will try it out and include it in the next patch if it works well (enough).

**Comment by stanmoore1** [comment]
This broke all of my regression tests. Is there some way to know what packages have been renamed or removed from LAMMPS?

**Comment by stanmoore1** [comment]
For example:

```
make yes-fld
Package FLD does not exist
```

What happened to package FLD?

**Comment by akohlmey** [comment]
> This broke all of my regression tests. Is there some way to know what packages have been renamed or removed from LAMMPS?

"make ps" lists all packages that are available

**Comment by akohlmey** [comment]
> For example:
> 
> ```
> make yes-fld
> Package FLD does not exist
> ```
> 
> What happened to package FLD?

not sure, but from the names of the pair styles it looks like it got merged into the COLLOID package.

**Comment by stanmoore1** [comment]
>"make ps" lists all packages that are available

That won't show if a package is renamed or removed though. I would be nice to have this history somewhere without having to dig through git logs.

**Comment by akohlmey** [comment]
> > "make ps" lists all packages that are available
> 
> That won't show if a package is renamed or removed though. It would be nice to have this history somewhere without having to dig through git logs.

all you have to do is to compare the list of packages you want to use with the list that is available. any discrepancies are packages that have been added, removed, or renamed.

as for keeping a history, that is a question for @sjplimp. I am not good at reading his mind, but I would suspect he will point you to https://lammps.sandia.gov/bug.html and the ones for previous years.
