### ISSUE TITLE
[Feature Request] Add GPU support for pair style adp

### ISSUE THREAD

**Issue by starmm11** [lammps/lammps#2405]
**Summary**

Request for adding GPU support to pair style adp potential

**Detailed Description**

ADP potentials is a generalization of EAM potentials. They have an additional terms of dipole and quadrupole moments. Is the implementation of “adp/gpu” acceleration and GPU support for pair style adp planned for the future?

Thank you.

**Comment by stanmoore1** [comment]
For Kokkos, it looks fairly easy to copy from pair eam/kk and make a new pair adp/kk. I'll put in on my list, but I have a few other things to do first...

**Comment by stanmoore1** [comment]
I started working on a Kokkos version of "adp/kk", shouldn't take too long to finish.

**Comment by vvsteg** [comment]
Could you please make an update about the current status of "adp/kk"?

**Comment by stanmoore1** [comment]
I started working on it here: https://github.com/stanmoore1/lammps/tree/kk_adp, but am currently busy with other work. It needs a little push to get it finished.
