### ISSUE TITLE
[BUG] _Pair coefficients mixing of EAM does not work when it is used as a sub-style of hybrid/overly

### ISSUE THREAD

**Issue by qqlovekerry** [lammps/lammps#2415]
**Summary**
I suspect that the mixing of EAM does not work when it is used as a sub-style with pair_style hybrid/overlay. 
The results of our test shows that for several atoms, if the type of one atom is changed to type 2, for the case only EAM potential is used, the potential energy of the atoms would not change. 
But for the case EAM used as a sub_style, the potential energy of the atom which is changed to type 2 would have a very significant change. It seems the reason is that the mixing of EAM does not work properly. 
Attached is our input file and the generated dump files.
I posted my questions on the mail list, but I am sorry only a few replies are received.
Also, I found two posts on the mail list which may related to this issue.
[EAM Mixing Problem](https://sourceforge.net/p/lammps/mailman/lammps-users/thread/CAENuAmHwjG3hHD4TwwjG57ZbwsoVhi5Su5-3Hfim_Go2a5qQbw%40mail.gmail.com/#msg36073867)
[Pair_Style hybrid with EAM Alloy](https://sourceforge.net/p/lammps/mailman/lammps-users/thread/CADTmJ6EzwTrTH14W3HfqTmk8ExXqpe39nUap7SvqfG_U%3DsNrsg%40mail.gmail.com/#msg34376720)

**LAMMPS Version and Platform**
LAMMPS (22 Aug 2018), Ubuntu 18.04LTS

**Expected Behavior**
The mixing of pair coefficients of EAM functions as the same as when it is used solely. 

**Actual Behavior**
When chagned the type of one atom, the potential energy of the atom changes significantly.
But only change the atom type should not lead to change of potential energy if the coefficients mixing of EAM works as expected.

**Steps to Reproduce**
Attached please find our input file, data files and the generated dump files.
[hybrid_overlay_eam.zip](https://github.com/lammps/lammps/files/5361360/hybrid_overlay_eam.zip)

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
I think what you are seeing is the documented behavior. 
Please carefully review https://docs.lammps.org/pair_hybrid.html#mixing-shift-table-tail-correction-restart-rrespa-info
You have two different pair styles associated with the same pair of atom types and that means that mixing will not occur with hybrid/overlay (since it simply cannot know whether your intention is to have mixed parameters used or not in the hybrid/overlay case.

**Comment by qqlovekerry** [comment]
Dear Axel,
Thank you very much for your reply! It helps a lot.
However, it is somehow kind of contradicting with my intuitive thinking, since I supposed the LJ and the EAM are all overlayed for all atom types.
If this is the expected behavior of hybrid/overlay, I can not find out the way to overcome this problem. Could you please give me some advice? I hope the coefficients mixing of EAM can take effect. And all interactions for all atom types could be superposed. Is using hybrid/overlay with eam/alloy sub-style is a possible solution?
Any help would be much appreciated!

**Comment by akohlmey** [comment]
> Dear Axel,
> Thank you very much for your reply! It helps a lot.
> However, it is somehow kind of contradicting with my intuitive thinking, since I supposed the LJ and the EAM are all overlayed for all atom types.

You are not looking at this correctly. Your intentions are clear for you, but you simply are not thinking like other people are thinking and what kind of uses there could be.

While for atom style hybrid there must be only one pair style per pair of atom types, you can infer whether mixing is intended from the fact that you have have a pair_coeff <i> <i> <style1> and pair_coeff <j> <j> <style1> and no pair_coeff <i> <j>. Then 
 you infer pair_coeff <i> <j> <style1> from mixing. If you wanted to use pair style <style2> with <i> <j> interactions you would explicitly specify it with a pair_coeff command. But with pair_style hybrid/overlay this is not quite so obvious.
How can you tell the difference between a case where you want to only add pair_coeff <i> <i> <style2> and pair_coeff <j> <j> <style2> to the style1 interactions and the case you also want to add pair_coeff <i> <j> <style2>?
So while for hybrid the intention is clear, for hybrid/overlay it is ambiguous and thus LAMMPS does not do mixing. As I already pointed out, this is the intended behavior, it is documented in the manual and that is that.

> If this is the expected behavior of hybrid/overlay.

I already told you that it is and pointed out the documentation where it is explained.

> I can not find out the way to overcome this problem. Could you please give me some advice?

As the documentation says, you can do mixing with hybrid/overlay if the situation is unambiguous and that means if there is only pair_coeff <i> <i> <style1> and pair_coeff <j> <j> and no pair_coeff <i> <i> <style2> or pair_coeff <j> <j> <style2> or pair_coeff <i> <j> <style2> (or some wildcard version of it. please note that a wildcard internally is the same as many individual pair_coeff commands).

> Any help would be much appreciated!

You have essentially two options:

1) You write a small tool that generates the mixed EAM potential files for you. That also means that those files have to be written in a different format (eam/alloy or eam/fs and those files will have to contain the data for *all* pairs of atom types). This is not as complex as you might think. Internally LAMMPS uses the same data structures and data format for all of "eam", "eam/fs" and "eam/alloy" only the parts that read the potential files are different.

2) You implement a modified custom EAM pair style (call it eam/lj) that includes the desired LJ interaction as the 2-body part of the potential.

Honestly, I am surprised that you even expected for such a significantly modified model that you could get away without programming. On top of that, to me the very thought of mixing giving a good result for such a setup is counter-intuitive.  The whole point of having eam/fs or eam/alloy is that you *can* tune the inter-atom-type interactions to better represent mixed system than what you would get from a simple mixing rule. The same is true for lj/cut interactions, where mixing only works reasonably well from atoms that are rather similar. Many force fields have ways to define overrides for pairs of atom types that do not fall into common categories and thus mixing would generate less accurate or completely faulty results.

**Comment by qqlovekerry** [comment]
Dear Axel,
Thank you very very much for the detailed explanation! Your advice is very valuable. I will read them carefully. I think I need some time and some tests to fully understand all the meanings.
I hope you do not mind if I would raise further questions in the future. I will let you know if I can solve this.
Again, thanks very much!

**Comment by qqlovekerry** [comment]
Dear Axel,
Thank you very very much for the detailed explanation! Your advice is very valuable. I will read them carefully. I think I need some time and some tests to fully understand all the meanings.
I hope you do not mind if I would raise further questions in the future. I will let you know if I can solve this.
Again, thanks very much!

**Comment by akohlmey** [comment]
> Dear Axel,
> Thank you very very much for the detailed explanation! Your advice is very valuable. I will read them carefully. I think I need some time and some tests to fully understand all the meanings.
> I hope you do not mind if I would raise further questions in the future. I will let you know if I can solve this.
> Again, thanks very much!

I do mind. This issue is closed as invalid, as this is no bug but documented behavior. These is nothing left to discuss here. I have given you all the advice I am willing and have the time to give. Any further discussion is a discussion you need to have with your advisor or experienced colleagues since it does not concern LAMMPS but your research, and this is not the forum to discuss your research.
