### ISSUE TITLE
[Feature Request] KOKKOS minimize with fix box/relax

### ISSUE THREAD

**Issue by whiffle2k** [lammps/lammps#2428]
**Summary**

I am working with ion-conducting crystal structures using `reax/c`. While using reax I have found that the KOKKOS implementation `reax/c/kk` is significantly more robust and does not suffer many of the memory-related issues commonly encountered with the standard `reax/c`. Specifically for extended periodic systems, `reax/c/kk` has become essential for reliable runs. Furthermore, for this type of system, unit cell parameters of crystal structures are essential metrics for developing accurate force field parameters; a natural approach is to use `minimize` combined with `fix box/relax` to obtain the box dimensions. But `fix box/relax` is not currently compatible with KOKKOS `minimize` due to lack of support for extra global degrees of freedom.

What would it take to implement compatibility between KOKKOS `minimize` and `fix box/relax`?

**Detailed Description**

Here is where LAMMPS notes the incompatibility:

`src/KOKKOS/min_kokkos.cpp:356-358`
```cpp
  if (nextra_global)
    error->all(FLERR,"Cannot yet use extra global DOFs (e.g. fix box/relax) "
     "with Kokkos minimize");
```

I am willing to contribute, but do not consider myself an experienced C++ programmer and only recently started to become familiar with the KOKKOS source code. At the very least I am hoping someone will be able to point me to the most relevant sections of code so that I can become more familiar with them.

**Comment by stanmoore1** [comment]
I don't this would be hard to add, it would mostly be mirroring the calls related to global DOFs from the vanilla minimize files inside the Kokkos versions.

**Comment by stanmoore1** [comment]
Turns out this was even more trivial than I thought, see #2444. Just need to test.
