### ISSUE TITLE
[Feature Request] Support binary native dump files with read_dump and rerun

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2446]
**Summary**

Using binary files can be a space and time saver for reading/post-processing trajectories. It would be nice to have support for that. So far, this can only be done via VMD molfile plugins and the choice of a suitable file format.

**Comment by anjohan** [comment]
Hi @akohlmey,

Is anyone working on implementing this?

I have created 30 TB of binary dump files that need some coordination analysis (which will probably be fastest/easiest using `rerun` in LAMMPS), and I don't particularly want to convert these to 30 TB of text files.

If no one is working on this (or has a burning urge to do so), I can try to stare long and hard at `binary2txt.cpp` and `reader_native/xyz.cpp` and give it a shot myself.

Best wishes,
Anders

**Comment by akohlmey** [comment]
@rbberger had taken a look, but I don't think he did much programming, if anything.
Please note that you would only need to support the "new" binary format unlike for binary2texts.cpp.

**Comment by anjohan** [comment]
Thanks, that's good to know!

I'll let you know if I try and either 1) succeed or 2) get stuck somewhere.

**Comment by nw13slx** [comment]
I tried to implement this and open a pull. But I'm not sure how this can be unit tested. I didn't find one on read_dump native format, to begin with. 

@akohlmey @anjohan  any ideas?
