### ISSUE TITLE
[BUG] Race condition in Kokkos pair forward comm

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#2454]
**Summary**

There was a race condition in Kokkos pair forward comm, which is used in `pair_style multi/lucy/rx/kk` and `pair_style eam*/kk`, which could potentially give the wrong numerics. However, as far as I know this bug never manifest in any of the testing or simulations I ran with those pair styles. It was discovered in #2441 when porting forward comm for fixes on device. The race was coming from directly setting the comm recv buffer to the send buffer, it needed a temp buffer instead. This issue is fixed in #2441 e2ab5f1ce9b7eb1faecf6adbc4a0b982ab6eae85.

**LAMMPS Version and Platform**

Latest Master

**Comment by stanmoore1** [comment]
@akohlmey the relevant part of e2ab5f1 needs to go in the next patch as bugfix. I should have #2441 ready in a day or two, but should I submit a separate PR just to be sure the bugfix gets in?

**Comment by akohlmey** [comment]
> @akohlmey the relevant part of [e2ab5f1](https://github.com/lammps/lammps/commit/e2ab5f1ce9b7eb1faecf6adbc4a0b982ab6eae85) needs to go in the next patch as bugfix. I should have #2441 ready in a day or two, but should I submit a separate PR just to be sure the bugfix gets in?

yes, please do so. today would be the last day for merging bugfixes unless somebody points out some serious "showstopper" kind of bug.

**Comment by stanmoore1** [comment]
Done.
