### ISSUE TITLE
[Feature Request] Add citation information to output file

### ISSUE THREAD

**Issue by tadmor** [lammps/lammps#2461]
**Summary**

LAMMPS currently provides citation information in the log.cite file. This informs users of any references that should be cited based on the simulation that they performed. However, this file and statements to refer to it in the log file and the screen output can be easily overlooked. I suggest instead that all citation information be written directly to the screen output in a prominent fashion in addition to log.cite. This will encourage users to cite the intellectual property that they are using, and encourage contributors to add new content and to include citation information for their work.

**Comment by akohlmey** [comment]
@tadmor that is a discussion you have to have with @sjplimp. My original proposal/implementation was like you describe (and how it is done in other software projects, however, that was rejected and cite.log (plus a command line flag to suppress it) was what we got.

**Comment by akohlmey** [comment]
@sjplimp just noticed that this issue is also still open for discussion and deciding on a final strategy to implement.

**Comment by stanmoore1** [comment]
I thought we came to a decision via email.

**Comment by ellio167** [comment]
Steve asked for our feedback and we haven't managed to respond, but we're going to talk about it today at our regular meeting and get back to him right away.
