### ISSUE TITLE
Parsing script lines with quotes and variable substitions

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#2465]
**Summary**

Is is possible/desirable to be able to construct command arguments which contain quotes and substitute for variables?

**Details**

Use case is the `kim_query` command.  The arguments of this command are to be json arrays and when the entries are strings, they need to be quoted.

```
variable lattice string "diamond"
kim_query a0 get_lattice_constant_cubic crystal=["${lattice}"] species=["Si"] units=["angstrom"]
```
This doesn't work because `${lattice}`  is not replaced.  I guess there is no way to escape the quotes:

```
kim_query a0 get_lattice_constant_cubic crystal=[\"${lattice}\"] species=["Si"] units=["angstrom"]
```
or get a literal single quote
```
kim_query a0 get_lattice_constant_cubic crystal=['"'${lattice}'"'] species=["Si"] units=["angstrom"]
```

Am I missing an option that would allow this to work?  Or is there any openness to adding one of these as a feature?

**Comment by akohlmey** [comment]
Making changes to the input parser in its current incarnation comes with a very high risk of breaking compatibility.
How about you process the arguments inside of "kim_query"? i.e. turn every group with `word=[text]` into `word=["text"]`?

**Comment by ellio167** [comment]
I expected that changing the parser was not a likely option...

At the moment we are just using the raw string arguments.  So, I think we'll have to do what you say: i.e. 
> turn every group with word=[text] into word=["text"]

Unless you have an alternate suggestion, we'll go ahead with that solution.

**Comment by akohlmey** [comment]
We have started refactoring various text parsing operations and that will at some point also be extended to the parsing in input.cpp. That will likely be a disruptive process and require some redefinition or clarification of how corner cases will be handled. That would be the opportunity to make more risky changes, but there is no prediction when that will happen.

**Comment by ellio167** [comment]
Thanks.
