### ISSUE TITLE
Update documentation of 'set command'

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#2480]
_**Summary**_

The documentation of _set command_ can be updated. The command supports setting velocity of particles using the _vx, vy, vz_ as keywords. However that is not mentioned in the top portion of the documentation where the list of keywords is given.

**Details**

See attached image.
<img width="1094" alt="set_command_docs" src="https://user-images.githubusercontent.com/25865956/99030453-135db900-259b-11eb-905d-40d50a668148.png">

**Comment by akohlmey** [comment]
Thanks for reporting. This and another issue in the keyword summary will be fixed soon.
