### ISSUE TITLE
[BUG] _possible error in gC1 and gC2 coefficients of CH.rebo potential file_

### ISSUE THREAD

**Issue by nleconte** [lammps/lammps#2484]
**Summary**

The coefficients of the spline segment of G(cos(theta)) between 70 and 120 degree as defined in CH.rebo seem incorrect to me. I am not 100% familiar yet with the theory behind this, so I'm already sorry in advance if the issue I'm raising turns out the be an error due to my own lack of understanding.

**LAMMPS Version and Platform**

It is the CH.rebo file that is presently available on the master branch of lammps.

**Expected Behavior**

Expected behavior is the one illustrated in Brenner 2002.

![Screen Shot 2020-11-16 at 4 44 56 PM](https://user-images.githubusercontent.com/11783268/99313843-96d12000-28a3-11eb-8c1a-97466294dc27.png)

I refer to Stuart 2000 for the notation that matches the code, more specifically, this equation.

<img width="780" alt="Screenshot 2020-11-17 at 07 15 35" src="https://user-images.githubusercontent.com/11783268/99314757-e8c67580-28a4-11eb-8542-e2e24bdbce14.png">

**Actual Behavior**

The 1st, 2nd and 4th segment are correctly defined:

<img width="398" alt="Screenshot 2020-11-17 at 07 23 22" src="https://user-images.githubusercontent.com/11783268/99315314-d26ce980-28a5-11eb-96b5-ca24e76e5a05.png">

However, the 3th segment between 70 and 120 degrees (i) is defined by the same coefficients for both g1 and g2 in CH.rebo, and (ii) this segment does not link properly with the other segment at 70 degrees:

<img width="411" alt="Screenshot 2020-11-17 at 07 23 07" src="https://user-images.githubusercontent.com/11783268/99315326-d993f780-28a5-11eb-9040-4224a2498a8f.png">

**Steps to Reproduce**

```
import matplotlib.pyplot as plot
import numpy as np

def PolyCoefficients(x, coeffs):
    o = len(coeffs)
    y = 0
    for i in range(o):
        y += coeffs[i]*x**i
    return y

# C1 spline
C1 = np.genfromtxt("C1.txt")[:6]
x = np.linspace(-1,-2/3)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C2")

C1 = np.genfromtxt("C1.txt")[6:12]
x = np.linspace(-2/3,-1/2)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C2")

C1 = np.genfromtxt("C1.txt")[12:18]  # These coefficients seem to be the culprit
x = np.linspace(-1/2,1/3)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C2")

C1 = np.genfromtxt("C1.txt")[18:24]
x = np.linspace(1/3,1)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C2")

# C2 spline
C1 = np.genfromtxt("C2.txt")[:6]
x = np.linspace(-1,-2/3)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C1")

C1 = np.genfromtxt("C2.txt")[6:12]
x = np.linspace(-2/3,-1/2)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C1")

C1 = np.genfromtxt("C2.txt")[12:18] # These coefficients seem to be the culprit
x = np.linspace(-1/2,1/3)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C1")

C1 = np.genfromtxt("C2.txt")[18:24]
x = np.linspace(1/3,1)
plt.plot(np.arccos(x)/np.pi*180, PolyCoefficients(x, C1),c="C1")
```

**Further Information, Files, and Links**

The two sets of coefficients (for gC1 and gC2) to be read by the code above, extracted from CH.rebo.

[C2.txt](https://github.com/lammps/lammps/files/5550044/C2.txt)
[C1.txt](https://github.com/lammps/lammps/files/5550045/C1.txt)

**Comment by akohlmey** [comment]
This is an issue you need to contact @CF17 about and also check out pull requests #986 and #1452 and check out issue #726

**Comment by CF17** [comment]
There is no bug in the code. In fact you have made a mistake in your script. The third segment is defined between x=-1/2 and x=-1/3 (theta=109.476 degrees) instead of x=1/3.

**Comment by nleconte** [comment]
Dear Cyril,

You are right. I'm so sorry I misread the input file.
It behaves properly indeed.
Closing the issue now.

Nicolas
