### ISSUE TITLE
Read me_Github 

### ISSUE THREAD

**Issue by MohanElapolu** [lammps/lammps#2493]
**Summary**

Some of the links in the read me page is  not working

**LAMMPS Version and Platform**

**Details**

The following links in this github read me page is not working. 
(1)  https://lammps.sandia.gov/doc/pg_library.html     LAMMPS programmer guide
(2) https://lammps.sandia.gov/doc/pg_developer.html   LAMMPS programmer guide

**Comment by akohlmey** [comment]
Thanks for reporting. This will be fixed soon.

**Comment by MohanElapolu** [comment]
Okay great..!
