### ISSUE TITLE
Update/Edit documentation of 'fix wall/gran command' (contacts option)

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#2509]
**Summary**

If the 'contacts' option is used, this fix (i.e., fix wall/gran) generates a per-atom array with 8 columns as output.
The values of these columns are listed in the following table: (https://lammps.sandia.gov/doc/fix_wall_gran.html)
The documentation says that f_ID[2,3,4] store Force fx.fy,fz exerted *on* the wall by the grains in contact.
However, I notice that they seem to store force exerted by the wall on the grains.
In other words, they differ in sign (+/-).
<img width="811" alt="fixwalllgrandocs" src="https://user-images.githubusercontent.com/25865956/101270856-457dc780-37a3-11eb-9f53-14c460b46ebb.png">

**LAMMPS Version and Platform**
LAMMPS (21 Jul 2020)
Platform : MacOS 10.15.7

**Details**

Please run the attached shell script to replicate the issue.
I have created a simulation box and built bounding walls using the fix wall/gran command.
Then I drop a grain on to the bottom wall and print out (via thermo)  f_ID[2] ie 'Force fy exerted *on* the wall' as per the documentation.
The grain should exert a force in -Y direction *on* and hence f_ID[2] should be negative. However, the numbers printed out by LAMMPS are positive, meaning the grain is 'pulling' the bottom wall.
Bottomline: The numbers being shown differ by sign.
[fixwallgranissue_github.zip](https://github.com/lammps/lammps/files/5648237/fixwallgranissue_github.zip)

**Comment by rbberger** [comment]
@vikaskok Thanks for reporting and the test case. You are right, I'll update the docs.
