### ISSUE TITLE
[BUG] TAD example test failed

### ISSUE THREAD

**Issue by gongyilun** [lammps/lammps#2519]
I cannot pass the example tad test, if I enable the following two dump commands in the input file
dump events all custom 1 dump.prd id type x y z
dump_modify events thresh c_coord != 4

The error message is bloew:
LAMMPS (29 Oct 2020)
Running on 3 partitions of processors
Setting up TAD ...
Step CPU N M Status Barrier Margin t_lo delt_lo
1000 0.000 0 0 E  0.000 0.000 0.000 0.000
Abort(808522766) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Allgather: Message truncated, error stack:
PMPI_Allgather(401)..........................: MPI_Allgather(sbuf=0x7ffede550618, scount=1, MPI_DOUBLE, rbuf=0x1ba2050, rcount=1, datatype=MPI_DOUBLE, comm=comm=0x84000005) failed
MPIDI_Allgather_intra_composition_alpha(1684):
MPIDI_NM_mpi_allgather(330)..................:
MPIR_Allgather_intra_auto(140)...............: Failure during collective
MPIR_Allgather_intra_auto(136)...............:
MPIR_Allgather_intra_brucks(94)..............:
(unknown)(): Message truncated

The following is the compiling options:

-- <<< Build configuration >>>
   Operating System: Linux
   Build type:       RelWithDebInfo
   Install path:     /home/xxx/.local
   Generator:        Unix Makefiles using /usr/bin/gmake
-- Enabled packages: MANYBODY;REPLICA;USER-MEAMC;USER-OMP
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /opt/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/icpc
      Type:          Intel
      Version:       19.1.3.20200925
      C++ Flags:     -restrict -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;LMP_USER_OMP
      Options:       -xHost
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:
-- <<< MPI flags >>>
-- MPI_defines:      MPICH_SKIP_MPICXX;OMPI_SKIP_MPICXX;_MPICC_H
-- MPI includes:     /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/include
-- MPI libraries:    /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/libmpicxx.so;/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/libmpifort.so;/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release/libmpi.so;/usr/lib64/libdl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so;

**Comment by akohlmey** [comment]
there must have been more modifications to the input than just the dump command. for example there is no compute with the ID "coord" in `in.tad`.

**Comment by akohlmey** [comment]
> there must have been more modifications to the input than just the dump command. for example there is no compute with the ID "coord" in `in.tad`.

sorry. my mistake. found it. didn't realize that there was a initial equilibration in the input deck.

**Comment by akohlmey** [comment]
after some debugging, it seems that I have found an explanation and a workaround for this unexpected behavior.
will have to discuss with my colleagues about whether to introduce this as a general bugfix.
