### ISSUE TITLE
[Feature Request] Reorganize package names and redistribute some styles, especially from USER-MISC

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2525]
**Summary**

There is a need to reorganize the location of some styles for consistency and better maintainability.
Especially the USER-MISC package is getting too big and we should consider creating, e.g. a USER-MANYBODY and/or a USER-MOLECULE and/or a USER-KSPACE package. Similarly, some of the less commonly used styles in src/ could be moved to MISC (or USER-MISC?).

When discussing with contributors it is getting sometimes difficult to justify why they are asked to do things differently than it was for other contributions.

When shuffling things around (and thus confusing some users), we should also consider renaming a few more packages with respect to their status as "user" package (to have the confusion only once and not twice or more often). USER-COLVARS, USER-REAXC, USER-MEAMC, and possibly also USER-OMP could lose the USER prefix and LATTE, MSCG, POEMS, and MPIIO look like it would be justified to add a USER prefix when looking at the maintenance status and type of contribution. I have already multiple times voiced my concern that the designation of user packages as given in the relevant documentation and web pages does not match well with the current reality.

----

After offline discussions with @sjplimp the proposal is now the following:
- we rename some packages that have their names for historical reasons (e.g. USER-MEAMC to MEAM, USER-REAXC to REAX or REAXFF), also file names, class names and style name may be renamed (with backward compatibility, as already available in meam/c)
- we review the contents of USER-MISC and move styles that comply with strict coding standards of the core LAMMPS code to existing packages (e.g. MOLECULE, KSPACE, MANYBODY, MISC) where applicable. 
- less commonly used styles in src are moved to appropriate packages (e.g. MISC)
- we create a few new packages to group thematically styles that don't fit well elsewhere and otherwise would stay in USER or go to MISC. that could be thermostat/time-integrator fixes, pair styles, computes/fixes for analysis.
- new contributions from users that are just a single style are initially added to the USER-MISC package in the same way as is done with USER-MISC right now. depending on the details of the implementation and the application another package may be suggested.
- the conditions for creating a new package are either 1) 3 or more styles that are thematically closely related where the purpose does not match well with existing packages or 2) code that depends on an external or bundled library or use a different programming language (e.g. Fortran, CUDA, etc.)

----

#### Renamed packages
- MLIAP -> **ML-IAP**
- SNAP -> **ML-SNAP**
- USER-ADIOS -> ADIOS
- USER-ATC -> ATC 
- USER-AWPMD -> AWPMD
- USER-BOCS -> BOCS
- USER-BROWNIAN -> BROWNIAN
- USER-CGDNA -> **CG-DNA**
- USER-CGSDK -> **CG-SDK**
- USER-COLVARS -> COLVARS
- USER-DIELECTRIC -> DIELECTRIC
- USER-DIFFRACTION -> DIFFRACTION
- USER-DPD -> **DPD-REACT**
- USER-DRUDE -> DRUDE
- USER-EFF -> EFF
- USER-FEP -> FEP
- USER-H5MD -> H5MD
- USER-HDNNP -> **ML-HDNNP**
- USER-INTEL -> INTEL
- USER-LB -> **LATBOLTZ**
- USER-MANIFOLD -> MANIFOLD
- USER-MEAMC -> **MEAM**
- USER-MESODPD -> **DPD-MESO**
- USER-MDI -> MDI
- USER-MESONT -> MESONT
- USER-MGPT -> MGPT
- USER-MISC -> USER-MISC
- USER-MOFF -> MOFF
- USER-MOLFILE -> MOLFILE
- USER-NETCDF -> NETCDF
- USER-OMP -> **OPENMP**
- USER-PACE -> **ML-PACE**
- USER-PHONON -> PHONON
- USER-PLUMED -> PLUMED
- USER-PTM -> PTM
- USER-QMMM -> QMMM
- USER-QTB -> QTB
- USER-QUIP -> **ML-QUIP**
- USER-RANN -> **ML-RANN**
- USER-REACTION -> REACTION
- USER-REAXC -> **REAXFF**
- USER-SCAFACOS -> SCAFACOS
- USER-SDPD -> **DPD-SMOOTH**
- USER-SMD -> **MACHDYN**
- USER-SMTBQ -> SMTBQ
- USER-SPH -> **SPH**
- USER-TALLY -> TALLY
- USER-UEF -> UEF
- USER-VTK -> VTK
- USER-YAFF -> YAFF

#### Possible new packages
- ANALYSIS for less commonly use computes and related fixes like fix ave/correlate/long
- INTERLAYER (or ILP?) pair styles: drip, ilp/graphene/hbn, kolmogorov/crespi/full, kolmogorov/crespi/z, lebedeva/z
- EXTRA-PAIR for less commonly used pair styles, and pair styles associated with large(r) potential files so that the potential files are no longer bundled, but will be downloaded on the fly, if not already present, during package installation. cf. USER-MESONT

The full list of packages would then become something like (plus any new packages):

ADIOS ASPHERE ATC AWPMD BOCS BODY CGDNA CGSDK CLASS2 COLLOID COLVARS COMPRESS CORESHELL DIFFRACTION DIPOLE DPD-MESO DPD-REACT DPD-SMOOTH DRUDE EFF FEP GPU GRANULAR H5MD INTEL INTERLAYER KIM KOKKOS KSPACE LATTE LATBOLTZ MACHDYN MANIFOLD MANYBODY MC MEAM MESONT MESSAGE MGPT MISC ML-IAP ML-PACE ML-QUIP ML-SNAP MOFFF MOLECULE MOLFILE MPIIO MSCG NETCDF OPENMP OPT PERI PHONON PLUMED POEMS PTM PYTHON QEQ QMMM QTB REACTION REAXFF REPLICA RIGID SCAFACOS SHOCK SMTBQ SPH SPIN SRD TALLY UEF USER-MISC VORONOI VTK YAFF 

### Examples tree

The examples tree will remain mostly the same (for now). The examples/USER folder will be renamed to examples/PACKAGE

**Comment by sjplimp** [comment]
@akohlmey Made a few changes to package names in the long list.  New name first, old name in parens.

**Comment by akohlmey** [comment]
> @akohlmey Made a few changes to package names in the long list. New name first, old name in parens.

also changed CGDNA -> CG-DNA and CGSDK -> CG-SDK for consistency with the DPD styles.

**Comment by athomps** [comment]
I like the proposed changes, and also the idea of doing it all at once, to minimize number of confused user-days.  What about code contributions that consist of many files (mostly non-LAMMPS files), but that don't warrant creating a new top level package.  Could we add them to a subdirectory of USER?

**Comment by akohlmey** [comment]
> I like the proposed changes, and also the idea of doing it all at once, to minimize number of confused user-days. What about code contributions that consist of many files (mostly non-LAMMPS files), but that don't warrant creating a new top level package. Could we add them to a subdirectory of USER?

which (existing) contributions would that be?
as far as I can tell, everything this would apply to is a package already. in some cases the non-LAMMPS files are in a matching lib/ folder in some in the package folder. we have been quite careful with contributions for (quite a while now) to steer contributors adopting a programming style that keep the namespace clean(er) and also improved on the existing code.

this reorganization will also see a re-evaluation of which styles would belong where since we are changing the criteria. and over time we have seen significant improvements and cleanups for some styles so it would be justified move them (same as wf/cut). I expect after this reorganization the USER folder will have less than half the files it has now.

**Comment by athomps** [comment]
Existing examples of this (> 10 files in a package) all have their own packages e.g. USER-REAXC, USER-MEAMC.  However, I know of packages like this that are not currently in the LAMMPS distribution but perhaps would like to be.  I am worried if all of these get added to src/USER, the number of files will become unmanageable.

**Comment by akohlmey** [comment]
> Existing examples of this (> 10 files in a package) all have their own packages e.g. USER-REAXC, USER-MEAMC. However, I know of packages like this that are not currently in the LAMMPS distribution but perhaps would like to be. I am worried if all of these get added to src/USER, the number of files will become unmanageable.

They won't get added to USER, but would become a package of their own. 3-4 (pairs of) files are going to be sufficient to justify a package, if they make sense as separate files in the first place. We are also going to try harder to find categories for bundling styles as packages and then sort existing and new styles into those packages. Some of the existing packages are quite big, too and lump together stuff that is quite diverse.

Unfortunately, some of the discussion of this topic between @sjplimp and me has been offline via e-mail and it became clear that there is no concern about having *many* packages in the distribution.

This change essentially means we're going to stop making a difference between "user" and non-"user" packages.
Only legacy files or code that has sufficient novelty or innovation, but doesn't quite meet all code quality measure (and has nobody on the team willing to improve it to meet them) would end up in USER. The idea behind USER packages was to include code without reviewing it. "if it compiles, it is in" and in some cases it only compiled for a while and then compilation was regularly broken (especially for USER-OMP or similar ;-)).
Now we check *everything* beyond that level and provide the tools (with integration, unit, and regression testing) to document what get broken by a change and won't include changes unless all breakage is mended. So there are better automatic checks, more code review to maintain the same standard for everything and thus the justification for making a distinction between USER and non-USER is going away.

**Comment by akohlmey** [comment]
... and USER won't have to be the "final resting place" of a style. It may be added there, but if somebody adopts and improves it (as has happened on occasion with code in USER-MISC), it would be moved to a more "specific" location.

**Comment by athomps** [comment]
I like this approach.  At some point, we will have too many packages, but it will be a while before that happens.

**Comment by akohlmey** [comment]
> I like this approach. At some point, we will have too many packages, but it will be a while before that happens.

In some way, we already have. Not all code that is in LAMMPS has been or has stayed relevant (or is maintained by the contributor). The strategy to address this is already forming: we'll have "meta packages", i.e. something like the CMake presets to the make yes/no options that install multiple packages.

It is all a balancing act. We have to look for ways to keep LAMMPS maintainable and at the same time remain to be welcoming to contributions. Yet also give people, that want to compile LAMMPS on their own, some simple enough choices of what they would need. The 3-tier system has worked in the past, but not longer reflects our current situation (for users and developers). The purpose of this feature request was to start the discussion on how to best adapt.

**Comment by athomps** [comment]
I am good with these changes.  I like the idea of introducing prefixes for packages that are related, currently DPD- and CG-.  I propose a new prefix Ml- for machine-learning potentials, existing and submitted: ML-SNAP, ML-PACE, ML-NNP, ML-RANN, ML-PINN, possibly ML-QUIP (we should ask Quip developers).  MLIAP could be renamed ML-MLIAP, or ML-IAP, or just leave it as is for now.  There are also MLIAP packages that are distributed separately from LAMMPS: USER-DEEPMD, USER-MLP (Seko), USER-MLIP (Shapeev), USER-AENET, USER-ANI.  We could ask them to change to the ML- prefix.

**Comment by sjplimp** [comment]
If we include (almost) no USER packages in the LAMMPS distro, then having external packages (that others distribute) with names like USER-XYZ seems like a good idea.

**Comment by sjplimp** [comment]
Also, I vote for ML-IAP

**Comment by athomps** [comment]
> If we include (almost) no USER packages in the LAMMPS distro, then having external packages (that others distribute) with names like USER-XYZ seems like a good idea.
Yes, that is true.

**Comment by athomps** [comment]
Here is another idea that probably won't work in practice: create a package tree hierarchy with subdirectories:
MLIAP/SNAP, MLIAP/PACE, MLIAP/NNP, MLIAP/RANN, MLIAP/PINN

**Comment by akohlmey** [comment]
> Here is another idea that probably won't work in practice: create a package tree hierarchy with subdirectories:
> MLIAP/SNAP, MLIAP/PACE, MLIAP/NNP, MLIAP/RANN, MLIAP/PINN

I don't see much of a technical problem with this, but I am concerned about the resulting extra effort in maintenance. It may sound trivial, but after fixing an issue or when using some refactoring, I frequently do search through the source tree with grep for similar cases. With a deeper trajectory tree, this makes this more tedious than it already is with one level of folders.

**Comment by akohlmey** [comment]
Added the ML- renames to the proposed changes.

**Comment by rbberger** [comment]
@sjplimp @akohlmey @athomps note that there is a corresponding Python package `lammps.mliap` and those [shouldn't have any dashes](https://www.python.org/dev/peps/pep-0008/#package-and-module-names). So should that then become `lammps.ml.iap`?

**Comment by athomps** [comment]
I think for python we can just drop the dashes i.e. `lammps.mliap`. Wouldn't `lammps.ml.iap` require defining a package `ml` and then a package `iap`?

**Comment by akohlmey** [comment]
@sjplimp @athomps @rbberger The first chunk of changes has just been submitted as PR #2818. Testing will fail, since that needs updates and also some tweaks to the GNU make build are still missing. Since we do not have the "standard" and "user" setting anymore, should I instead implement the "minimal" and "most" package lists similar to CMake?

To avoid having to change the integration testing multiple times, I would like to add any new packages in the same PR.  Suggestions for new packages (please suggest additional ones. I will create and maintain a full list a the top of the issue.):
- DPD-BASIC  (for pair dpd and dpd/tstat, and the corresponding dpd/ext variants)
- INTERLAYER (for various interlayer potentials)
