### ISSUE TITLE
[BUG] memory error writing restart file when using "fix temp/csvr" or "fix temp/csld"

### ISSUE THREAD

**Issue by TerryBreaksButterfly** [lammps/lammps#2527]
**Summary**

lmp craches during writing restart file when "fix temp/csvr" or "fix temp/csld" is in use.

**LAMMPS Version and Platform**

LAMMPS 29Oct20 or 30Nov20

Compiled on CentOS 8 with:
- gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
- Cuda compilation tools, release 10.2, V10.2.89
- OpenMPI 4.0.3

**Expected Behavior**

write restart file and continue with the simulation

**Actual Behavior**

Crashes with a memory error, either "double free" or "malloc() size error"

**Steps to Reproduce**

use together 1)the "restart" command and 2) the fix mentioned above 

**Further Information, Files, and Links**

the following patch eliminate the memory error and the crash, though not fully verified.

>--- fix_temp_csvr.cpp.ori       2020-12-17 10:27:52.092792995 +0800
>+++ fix_temp_csvr.cpp   2020-12-17 10:30:53.727645052 +0800
>@@ -341,7 +341,7 @@
>   int nsize = (98+2+3)*comm->nprocs+2; // pRNG state per proc + nprocs + energy
>   double *list = nullptr;
>   if (comm->me == 0) {
>\-    list = new double[nsize];
>\+    list = new double[(nsize-2)*comm->nprocs+2];
>     list[0] = energy;
>     list[1] = comm->nprocs;
>   }
>--- fix_temp_csld.cpp.ori       2020-12-17 10:28:52.036074191 +0800
>+++ fix_temp_csld.cpp   2020-12-17 10:17:22.380815797 +0800
>@@ -308,7 +308,7 @@
>   int nsize = (98+2+3)*comm->nprocs+2; // pRNG state per proc + nprocs + energy
>   double *list = nullptr;
>   if (comm->me == 0) {
>\-    list = new double[nsize];
>\+    list = new double[(nsize-2)*comm->nprocs+2];
>     list[0] = energy;
>     list[1] = comm->nprocs;
>   }

[temp_csvr_csld.patch.txt](https://github.com/lammps/lammps/files/5706648/temp_csvr_csld.patch.txt)

**Comment by akohlmey** [comment]
@TerryBreaksButterfly thanks for the report. I have confirmed the issue and implemented a bugfix. The issue is with the MPI_Gather() call, not the memory allocation. The fix will be in the next patch.

**Comment by TerryBreaksButterfly** [comment]
@akohlmey Thanks for the quick fix. Now works fine.
