### ISSUE TITLE
[BUG] Need to add --embed flag to python-config for python 3.8 and above to allow building with python package

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#2529]
**Summary**

In python 3.8 and above, when `python-config --ldflags` is used without the `--embed` flag, the output doesn't contain `-lpython3.8 `, which makes building LAMMPS fail at the final linking stage. Only tested with classic make.

**LAMMPS Version and Platform**

Latest master version, python 3.8.

**Expected Behavior**

LAMMPS should build correctly regardless of python version.

**Actual Behavior**

LAMMPS fails at the linking stage with a lot of "undefined reference" errors such as:
> /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./liblammps_serial.a(pair_python.o): in function `LAMMPS_NS::PairPython::~PairPython()':
> /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'

**Steps to Reproduce**

1. Have a system, where the default python version is at least 3.8.
2. Enable python package with `make yes-python`.
3. Build LAMMPS: `make serial`.

**Further Information, Files, and Links**

This change is described in the python release notes[1]:
> To embed Python into an application, a new --embed option must be passed to python3-config --libs --embed to get -lpython3.8 (link the application to libpython). To support both 3.8 and older, try python3-config --libs --embed first and fallback to python3-config --libs (without --embed) if the previous command fails.

[1] https://docs.python.org/3.8/whatsnew/3.8.html

**Comment by akohlmey** [comment]
Already addressed in PR #2521

**Comment by donatas-surblys** [comment]
Oops, didn't notice. Yeah, that takes care of it.
