### ISSUE TITLE
new style for fix_wall_region

### ISSUE THREAD

**Issue by aershadinia** [lammps/lammps#253]
I want to add another kind of interaction to the fix wall/region. I want to have a block which its walls interact with ellipsoid particles in the way I mentioned in #234 . 
I can do this in two ways. The first is to modify the fix_wall_region.cpp and fix_wall_region.h file in lammps/src directly and the other way is to add new files to lammps/src/USER-MISC directory. Would you please help me to choose?

**Comment by akohlmey** [comment]
Please first complete the pending work on the pull request that is open. It does not even compile as it is.

The best way to add support for aspherical particles should be done in a different file, best as a class derived from the corresponding base class. There rarely is a benefit to mix and match code for different particle styles in the same class. If this is done, it has to be _extremely_ careful to ensure full compatibility with different configurations, i.e. you cannot at any point assume, that the simulation is done with aspherical particles, not even that the ASPHERE package is installed.

**Comment by akohlmey** [comment]
closed due to inactivity and the related pull request withdrawn by submitter.
