### ISSUE TITLE
[BUG] _Replace With Suitable Title_

### ISSUE THREAD

**Issue by mehdifar943** [lammps/lammps#2543]
Dear lammps group
the command ID Group-Id setforce 0 0 0 not works in Reax method and the atoms in this group-id move during simulation after appling this command in lammps-stable 29 Oct 2020.
also for this group id was set the velocity 0 0 0 but after the run simulation atoms of this group id move.
velocity  freezegrp set 0.0 0.0 0.0 sum no units box
fix 3 freezegrp setforce 0.0 0.0 0.0

**Comment by akohlmey** [comment]
it works perfectly for me when adding the lines:
```
group freezegrp id 1:10
velocity freezegrp set 0.0 0.0 0.0 sum no units box
fix 3 freezegrp setforce 0.0 0.0 0.0
```
to the `in.reaxc.rdx` examples. so the reason must be some mistake somewhere in your input or a misinterpretation of how some other feature of LAMMPS works.
as I already mentioned in the other issue you submitted, fix setforce works independent of reaxff.
you have failed to provide convincing evidence now for the second time and thus the issue will be closed as invalid.
