### ISSUE TITLE
[BUG] Unclear/wrong documentation of fix ti/spring (package user-misc)

### ISSUE THREAD

**Issue by t-brink** [lammps/lammps#2574]
**LAMMPS Version and Platform**

I used LAMMPS 7Aug19 on Linux, but the relevant source code and documentation is the same in git master.

**Expected Behavior**

The fix ti/spring has two vector outputs, the first being a coupling parameter λ and the second being dλ/dt according to the documentation (<https://lammps.sandia.gov/doc/fix_ti_spring.html>). It explicitly says "the second one is the time derivative of lambda".

**Actual Behavior**

The second output is in fact dλ/ds, where s is the timestep (the integer, not δt). In order to obtain dλ/dt, one needs to multiply with 1/δt, where δt is the timestep size. The code and documentation are a bit sloppy here with the distinction between time and timestep.

I don't propose to change the behavior in order to stay backwards compatible, but the documentation should be updated to make it clearer. This cost me quite some time to figure out, especially since the paper that is cited uses the value dλ/dt to compute the free energy.

**Comment by sjplimp** [comment]
Thanks for pointing this out @t-brink.  See PR #2579 and please check if the edited doc page text now seems clear?

**Comment by t-brink** [comment]
Seems clearer to me now, thanks for the quick reaction.
