### ISSUE TITLE
Mismatched documentation & argument for -mpi / -mpicolor

### ISSUE THREAD

**Issue by LunarLanding** [lammps/lammps#2575]
Given the short form is the same, I am not surprised this went unnoticed.

https://github.com/lammps/lammps/blob/f2479e7d05d54e48519ced058cb52ee4db6bada1/src/lammps.cpp#L138

https://github.com/lammps/lammps/blob/f2479e7d05d54e48519ced058cb52ee4db6bada1/src/lammps.cpp#L1113

https://github.com/lammps/lammps/blame/master/doc/src/Run_options.rst#L13

**Comment by akohlmey** [comment]
@LunarLanding thanks for the report. This will be fixed in the next patch release.
