### ISSUE TITLE
Absense of CONTRIBUTING.md

### ISSUE THREAD

**Issue by intomg1990** [lammps/lammps#2577]
Why does there is no CONTRIBUTING.md file to guide possible contributions to the project?

**Comment by akohlmey** [comment]
> Why does there is no CONTRIBUTING.md file to guide possible contributions to the project?

There is: https://github.com/lammps/lammps/blob/master/.github/CONTRIBUTING.md
And there is a ton of information for development in the manual: https://docs.lammps.org/Manual.html#programmer-documentation
