### ISSUE TITLE
Track updating the citation reminder strings

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2597]
**Summary**

In order to complete the refactoring of the citation reminder we need to update all citation reminders to include a brief 1-line reference in the first line of the added string. By preference a DOI or some URL. This issue serves to keep track of the progress since it lists all files which currently have a citation reminder included.

Additional files may need to have citation reminders added (based on their documentation). Please see https://docs.lammps.org/Modify_style.html#citation-reminder-suggested for recommendations on when to add a reminder (and how many and when not).

**LAMMPS Version and Platform**

Starting with LAMMPS  10 Feb 2021

**Details**

- [x] compute_centroid_stress_atom.cpp
- [x] neighbor.cpp
- [ ] ASPHERE/pair_gayberne.cpp
- [ ] BOCS/fix_bocs.cpp
- [ ] COLVARS/fix_colvars.cpp
- [ ] DIELECTRIC/atom_vec_dielectric.cpp
- [x] DIFFRACTION/compute_saed.cpp
- [x] DIFFRACTION/compute_xrd.cpp
- [ ] DPD-MESO/pair_edpd.cpp
- [ ] DPD-MESO/pair_mdpd.cpp
- [ ] DPD-MESO/pair_tdpd.cpp
- [ ] DPD-REACT/fix_shardlow.cpp
- [ ] DPD-REACT/pair_multi_lucy.cpp
- [ ] DPD-REACT/pair_multi_lucy_rx.cpp
- [ ] EFF/atom_vec_electron.cpp
- [ ] EXTRA-COMPUTE/compute_stress_cartesian.cpp
- [ ] EXTRA-COMPUTE/compute_stress_cylinder.cpp
- [ ] EXTRA-COMPUTE/compute_stress_spherical.cpp
- [ ] EXTRA-FIX/fix_ave_correlate_long.cpp
- [ ] EXTRA-FIX/fix_electron_stopping_fit.cpp
- [ ] EXTRA-FIX/fix_filter_corotate.cpp
- [ ] EXTRA-FIX/fix_flow_gauss.cpp
- [ ] EXTRA-FIX/fix_pafi.cpp
- [ ] EXTRA-FIX/fix_rhok.cpp
- [ ] EXTRA-FIX/fix_ti_spring.cpp
- [ ] EXTRA-FIX/fix_ttm_mod.cpp
- [ ] EXTRA-MOLECULE/dihedral_table_cut.cpp
- [ ] EXTRA-PAIR/pair_e3b.cpp
- [ ] EXTRA-PAIR/pair_lj_relres.cpp
- [ ] EXTRA-PAIR/pair_momb.cpp
- [ ] GPU/fix_gpu.cpp
- [ ] INTERLAYER/pair_ilp_graphene_hbn.cpp
- [ ] INTERLAYER/pair_ilp_tmd.cpp
- [ ] INTERLAYER/pair_kolmogorov_crespi_full.cpp
- [ ] INTERLAYER/pair_saip_metal.cpp
- [x] KIM/kim_command.cpp
- [x] KIM/kim_init.cpp
- [x] KIM/pair_kim.cpp
- [ ] LATBOLTZ/fix_lb_fluid.cpp
- [ ] MANIFOLD/fix_nve_manifold_rattle.cpp
- [ ] MANIFOLD/fix_nvt_manifold_rattle.cpp
- [ ] MANYBODY/pair_atm.cpp
- [ ] MANYBODY/pair_edip_multi.cpp
- [ ] MANYBODY/pair_local_density.cpp
- [ ] MC/fix_bond_swap.cpp
- [ ] MC/fix_charge_regulation.cpp
- [ ] MISC/pair_agni.cpp
- [ ] MISC/pair_srp.cpp
- [ ] MISC/pair_srp_react.cpp
- [ ] ML-HDNNP/pair_hdnnp.cpp
- [ ] ML-RANN/pair_rann.cpp
- [ ] OPENMP/pair_reaxff_omp.cpp
- [ ] OPT/pair_ilp_graphene_hbn_opt.cpp
- [ ] ORIENT/fix_orient_bcc.cpp
- [ ] ORIENT/fix_orient_eco.cpp
- [ ] ORIENT/fix_orient_fcc.cpp
- [ ] PERI/atom_vec_peri.cpp
- [ ] PHONON/fix_phonon.cpp
- [ ] POEMS/fix_poems.cpp
- [ ] PTM/compute_ptm_atom.cpp
- [ ] REACTION/fix_bond_react.cpp
- [ ] REAXFF/fix_acks2_reaxff.cpp
- [ ] REAXFF/fix_qeq_reaxff.cpp
- [ ] REAXFF/pair_reaxff.cpp
- [ ] SPIN/fix_nve_spin.cpp
- [ ] SPIN/min_spin_cg.cpp
- [ ] SPIN/min_spin_lbfgs.cpp
- [ ] SPIN/neb_spin.cpp
- [ ] SRD/fix_srd.cpp
- [ ] UEF/fix_nh_uef.cpp

**Comment by ellio167** [comment]
KIM citation update completed with #2625 and #2649

**Comment by hammondkd** [comment]
I can volunteer for this, but I'm having trouble ascertaining what you're looking for. For example, neighbor.cpp seems to have a DOI in the first line. If that one is correct, I'll emulate that example for the rest of them. If not, please give an example of what you're looking for.

**Comment by akohlmey** [comment]
Thanks for volunteering. I have updated the list, and checked/regularized a few entries in commit c2115c27e8b64aa32f5ad9f507c888aa3f4b56ba
So neighbor.cpp was almost there. src/DIFFRACTION/compute_saed.cpp and src/DIFFRACTION/compute_xrd.cpp are suitable examples, if you replace the '_' with ' '. Please also see: https://docs.lammps.org/Modify_style.html#citation-reminder-suggested
