### ISSUE TITLE
Stability issues when using USER-INTEL

### ISSUE THREAD

**Issue by dkokron** [lammps/lammps#2598]
**Summary**
I'm seeing very different stability behavior for the examples/USER/drude/ethanol/in.ethanol.nh case when switching to user-intel from defaults.

**LAMMPS Version and Platform**
using git:master (LAMMPS (24 Dec 2020)) compiled with intel-19.1.3.304 and HPE message passing toolkit (MPT-2.23) running on Xeon (skylake) and SLES12sp5.  Config output is attached as config.txt
[config.txt](https://github.com/lammps/lammps/files/5967044/config.txt)

**Expected Behavior**
The case runs fine on a single rank using defaults
mpiexec -np 1 lmp < in.ethanol.nh -nocite
[expected.txt](https://github.com/lammps/lammps/files/5967053/expected.txt)

**Actual Behavior**
Switching to user-intel results in an unstable simulation that blows up.
mpiexec -np 1 lmp -pk intel 0 -sf intel < in.ethanol.nh -nocite
[actual.txt](https://github.com/lammps/lammps/files/5967068/actual.txt)

**Steps to Reproduce**
Edit cmake/presets/intel.cmake

git diff cmake/presets/intel.cmake
diff --git a/cmake/presets/intel.cmake b/cmake/presets/intel.cmake
index d101a0f69..040c6c7e2 100644
--- a/cmake/presets/intel.cmake
+++ b/cmake/presets/intel.cmake
@@ -1,9 +1,18 @@
 # preset that will enable Intel compilers with support for MPI and OpenMP (on Linux boxes)
+set(PKG_KSPACE ON CACHE BOOL "" FORCE)
+set(PKG_MISC ON CACHE BOOL "" FORCE)
+set(PKG_MLIAP ON CACHE BOOL "" FORCE)
+set(PKG_MOLECULE ON CACHE BOOL "" FORCE)
+set(PKG_SNAP ON CACHE BOOL "" FORCE)
+set(PKG_RIGID ON CACHE BOOL "" FORCE)
+set(PKG_USER-DRUDE ON CACHE BOOL "" FORCE)
+set(PKG_USER-INTEL ON CACHE BOOL "" FORCE)
 
 set(CMAKE_CXX_COMPILER "icpc" CACHE STRING "" FORCE)
 set(CMAKE_C_COMPILER "icc" CACHE STRING "" FORCE)
 set(CMAKE_Fortran_COMPILER "ifort" CACHE STRING "" FORCE)
 set(MPI_CXX "icpc" CACHE STRING "" FORCE)
+set(MPICXX_CXX "icpc" CACHE STRING "" FORCE)
 set(MPI_CXX_COMPILER "mpicxx" CACHE STRING "" FORCE)
 unset(HAVE_OMP_H_INCLUDE CACHE)

cmake -C ../cmake/presets/minimal.cmake -C ../cmake/presets/intel.cmake -D PKG_USER-INTEL=yes -D LMP_USE_MKL_RNG=yes -D FFT=MKL -D FFT_SINGLE=no -D BUILD_MPI=yes -D CMAKE_TUNE_FLAGS="-O2 -no-prec-div -qoverride-limits -xCOMMON-AVX512 -qopt-zmm-usage=high" ../cmake

make -j 6 VERBOSE=1 >& make.log

cd examples/USER/drude/ethanol

mpiexec -np 1 lmp -pk intel 0 -sf intel < in.ethanol.nh -nocite

**Comment by dkokron** [comment]
Switching to -xCORE-AVX2 from-xCOMMON-AVX512 does not change the behavior when using user-intel.

**Comment by akohlmey** [comment]
Note sure if this is a bug or a limitation of the optimizations in the USER-INTEL package. For improve speed the code in the package caches data in optimized data structures. If your input contains features that modify such cached data without also triggering the update of the cache, you can see problems and inconsistent behavior. Somebody with intimate knowledge of the USER-INTEL code needs to verify this.
