### ISSUE TITLE
[BUG] real MPI routines called instead of STUBS mpi library when using serial-lammps as a python .so lib

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#2606]
**Summary**

If you have an MPI python program (e.g. using mpi4py) and want to use entirely serial lammps processes, the names in the STUBS mpi library conflict with the names of the real MPI library, and the latter are actually used at runtime.

It appears that this can be worked around by adding `| os.RTLD_DEEPBIND` to the `RTLD_GLOBAL` in the various 
```
self.lib = CDLL(join(modpath,"liblammps" + lib_ext),RTLD_GLOBAL) 
```
calls.  This forces lammps to to use the liblammps.so-provided fake MPI routines, rather than the real MPI library.

**LAMMPS Version and Platform**

github master 16004e8f454, CentOS 7 + gfortran 7.3.1

**Expected Behavior**

python mpi4py-using script able to run serial LAMMPS

**Actual Behavior**

seg faults and MPI errors in serial-compiled lammps when run from a python script that is using mpi4py.  One example is
```
[tin:23589:0:23589] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x19)
==== backtrace (tid:  23589) ====
 0 0x0000000000089cb0 PMPI_Type_size()  ???:0
 1 0x00000000009617ec LAMMPS_NS::LAMMPS::LAMMPS()  /home/cluster2/bernstei/src/work/LAMMPS/lammps-github/src/Obj_shared_tin_serial/../lammps.cpp:601
 2 0x0000000000543e6a lammps_open()  /home/cluster2/bernstei/src/work/LAMMPS/lammps-github/src/Obj_shared_tin_serial/../library.cpp:172
 3 0x0000000000005e2c ffi_call_unix64()  ???:0
 4 0x0000000000005755 ffi_call()  ???:0
 5 0x0000000000010680 _ctypes_callproc()  ???:0
 6 0x00000000000097c6 ???()  /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so:0
 7 0x00000000000a8d20 _PyObject_FastCallDict()  ???:0
```

Since this was compiled for serial, it shouldn't be calling `PMPI_Type_size` at all

**Steps to Reproduce**

Compile lammps with `mode=shared` and `MAKE/Makefile.serial`.  I also added `-fopenmp` and `-DLAMMPS_EXCEPTIONS`, the `make install-python`.

run in python
```
from mpi4py import MPI

from lammps import lammps

lmp = lammps('tin_serial', ['-echo', 'log', '-log', 'none', '-screen', 'none', '-nocite'], comm=None)
```

**Comment by akohlmey** [comment]
Unfortunately, that workaround is not sufficiently portable.

**Comment by bernstei** [comment]
OK - I definitely don't feel like I understand what other implications it would have, or what other systems it might fail on.  I'd be happy to go with the different names + proprocessor #defines approach that's currently being discussed in issue #2605, if someone can implement that.

**Comment by akohlmey** [comment]
> OK - I definitely don't feel like I understand what other implications it would have, or what other systems it might fail on. I'd be happy to go with the different names + proprocessor #defines approach that's currently being discussed in issue #2605, if someone can implement that.

It is a "unix-only" feature and requires python 3.3 (IIRC), so it would require additional tests and would not resolve the problem for all setups. we have not yet fully broken with Python 2.7 support.
