### ISSUE TITLE
[BUG] RPATH not set correctly for KIM-API with *installed* version of liblammps

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#2623]
**Summary**

When building lammps with the kim-api installed in a non-system location and doing a `make install`, the resulting lmp executable does not have the needed RPATH setting to find the libkim-api library.  However, the build-dir version of the lmp executable is correct.

**LAMMPS Version and Platform**

Behavior is observed on macOS with current master branch.

**Expected Behavior**

executing `lmp` with valid input is successful 

**Actual Behavior**

dyld: Library not loaded: @rpath/liblammps.0.dylib
  Referenced from: /Users/relliott/unison-sync/KIM/git/lammps/build/test-install/./bin/lmp
  Reason: image not found
Abort trap: 6

**Steps to Reproduce**

* download kim-api and lammps and put in a directory:
```
$ mkdir try-it
$ tar Jxvf kim-api-2.2.1.txz
$ cd kim-api-2.2.1
$ mkdir build
$ cd build
$ CC=gcc CXX=g++ FC=gfortran cmake -DCMAKE_INSTALL_PREFIX=${PWD}/test-install -DCMAKE_BUILD_TYPE=Debug ..
$ make -j4 install
$ cd ../../
$ source ./kim-api-2.2.1/build/test-install/bin/kim-api-activate
$ git clone lammps ....
$ cd lammps
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=${PWD}/test-install -DPKG_KIM=ON ../cmake
$ make -j4
$ otool -L lmp
$ otool -l lmp | grep LC_RPATH -A2  % has setting
$ make install
$ otool -L test-install/bin/lmp
$ otool -l test-install/bin/lmp | grep LC_RPATH -A2  % does not have setting
```

**Comment by akohlmey** [comment]
I don't recall exactly where I read this, but if I remember correctly, that is the documented behavior, i.e. CMake will strip RPATH settings when installing binaries.

**Comment by akohlmey** [comment]
Yup, google finds this: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling
Shouldn't `source ./kim-api-2.2.1/build/test-install/bin/kim-api-activate` set `LD_LIBRARY_PATH` (on Linux and similar) or `DYLD_LIBRARY_PATH` (on MacOS)?
