### ISSUE TITLE
[Feature Request] Add generic way to set newton flag from command line

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#2628]
**Summary**

It would be very convenient if there was a way to set `newton` flag on/off from the command line. This can be done with the `package` command if using the GPU package and Kokkos packages, but not for USER-INTEL or other packages.

**Detailed Description**

Add something like `-newton off` and `-newton on` to the command line args.

**Further Information, Files, and Links**

None.

**Comment by akohlmey** [comment]
You can have many settings changed from the command line with index style variables also for the newton settings. For example.
```
variable  newton_pair     index  on
variable  newton_bond     index  on

newton           ${newton_pair} ${newton_bond}
```

` ./lmp -var newton_pair off -in input` will then set newton for pairwise off.
Am using this quite successfully for unit testing (which tests for all kinds of default and changed settings with the same input template).

**Comment by stanmoore1** [comment]
Yes I am aware of this option, it works but I have to modify every input script.

**Comment by akohlmey** [comment]
And how about this?
```
cat in.newton in.full > in.temp
./lmp -in in.temp -var newton_pair off
```

**Comment by stanmoore1** [comment]
It works too, but is clunky. Especially when we can just set it from the command line for KOKKOS.

**Comment by stanmoore1** [comment]
Could we add a generic package command, like `-pk none newton off`?

**Comment by akohlmey** [comment]
> Could we add a generic package command, like `-pk none newton off`?

now that is something that **I** would consider clunky and non-intuitive.
I am not very happy with those the existing options to override the newton settings as this violates the principle of least surprise. 
Where does it end? What is going to be the next added command line flag?

You can put the "clunky" script code into a wrapper script and then hide the clunkiness and then even go so far that you assemble input from multiple templates etc. or write the whole thing in python and import LAMMPS from python.
There are so many ways to keep things convenient without changing code leading to a situation where we have two different commands/options to do the same thing. now, the newton setting (like log and echo) is rather basic and so this is a bit of a corner case.

Anyway, I have said my piece and will shut up now.

**Comment by stanmoore1** [comment]
How about a generic way to append an input line at the top of the input file? Something like `-input/add "newton off"`. This would keep the input file cleaner.

**Comment by stanmoore1** [comment]
I have a bunch of benchmarking scripts that can easily modify the command line as they are automatically generating a batch script. Modifying the input is more tedious. If I have 20 benchmarks and 5 packages, then I have to change up to 100 inputs manually. (In practice each package doesn't have it's own specific input, but there is some specialization.)

**Comment by akohlmey** [comment]
That is what I was trying to get across. If you do scripting, you can just as well as adding a command line flag, have the script build a temporary input file from the additional line(s) and the intended input and then run the combined script as input and delete it after you're done. I don't see how that is different from adding a line of input through an additional flag. The original input would not have to be changed and an index variable would also not be needed.

**Comment by stanmoore1** [comment]
>I don't see how that is different from adding a line of input through an additional flag. 

It is different in my mind. I think adding something on the command line is much cleaner than spawning a shell and cat'ing together multiple inputs into a temporary file, but to each his own.

**Comment by stanmoore1** [comment]
@sjplimp @athomps @rbberger Any opinions on this?

**Comment by rbberger** [comment]
@stanmoore1 how about
```bash
lmp < <(cat <(echo newton off) <(cat in.lj))
```

It's one command-line. :wink:

Anyway, we could also just add it to the GPU/Intel package.

**Comment by stanmoore1** [comment]
> @stanmoore1 how about
> 
> ```shell
> lmp < <(cat <(echo newton off) <(cat in.lj))
> ```
> 
> It's one command-line. 😉

Hahaha!

**Comment by stanmoore1** [comment]
Closing for now. If I get sufficiently annoyed in the future, I will submit a PR to add the newton flag option to the Intel package.

**Comment by sjplimp** [comment]
What about adding a command-line option -cmd "newton off" to invoke any command first thing after lammps.cpp has initialized everything.  And to do it multiple times if -cmd is specified multiple times.  I could see that being useful in other contexts.  At least for commands that can come anywhere at the top of the input script.  Like python -c "print(2+3)".  Bonus points for being pythonic

**Comment by sjplimp** [comment]
I now see this is what Stan suggested with -input/add "newton off".   -cmd is better.  Any Python fan should like it.  Would say -c but -cite has already grabbed it.
