### ISSUE TITLE
Provide clear and detailed guidelines and requirements for potential contributions to LAMMPS

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2643]
**Summary**

We need to provide more specific and explicit guidelines and lists of requirements for contributions to LAMMPS.
This information is currently scattered across multiple files with different level of detail and different target audiences.
This should be condensed to a single location with all information and that should also indicate clearly which are
strict requirements (i.e. code will not be included unless those are met) and what is stating a preference (i.e. which are
optional or where the degree of compliance can be negotiated).

**Details**

https://github.com/lammps/lammps/blob/master/.github/CONTRIBUTING.md
https://github.com/lammps/lammps/blob/master/doc/include-file-conventions.md
https://github.com/lammps/lammps/blob/master/doc/documentation_conventions.md
https://github.com/lammps/lammps/blob/master/doc/github-development-workflow.md
https://docs.lammps.org/Modify_contribute.html

A draft document that may be edited and will be expanded follows below.

------

# Requirements for contributing code to LAMMPS

The following is a summary of the current requirements for including
contributions into the LAMMPS software distribution.  The LAMMPS
developers are committed to providing a software package that is
versatile, high-quality, portable, and easy to maintain or modify.
The requirements and preferences listed in this document are aimed
to maintain or improve on that status.

It is indicated which requirements are strict, and which represent a
preference but are negotiable or optional

Please feel free to contact the LAMMPS core developers in case you need
additional explanations or clarifications or in case you need assistance
in realizing the (strict) requirements for your contributions.

## Licensing requirements (strict)

Contributing authors agree that their contributions can be
distributed under the LAMMPS license conditions. This is the GNU public
license in version 2 (not 3 or later) for the publicly distributed
versions, e.g. on the LAMMPS homepage or on GitHub.  On request we also
make a version of LAMMPS available under LGPL 2.1 terms; this will
usually be the latest available or a previous stable version.

Contributions may be under a different license so long as that
license does not conflict with the aforementioned terms. Contributions
that use code with a conflicting license can be split into two parts:

1. the core parts (i.e. parts that must be in the `src` tree) that
   are licensed under compatible terms and bundled with the LAMMPS
   sources
2. an external library that must be downloaded and compiled
   (either separately or as part of the LAMMPS compilation)

Please note, that this split licensed mode may complicate including the
contribution in binary packages.

## Using Pull Requests on GitHub (preferred)

All contributions to LAMMPS are processed as pull requests on GitHub
(this also applies to the work of the core LAMMPS developers).  A
tutorial for submitting successful pull requests is included in the
HowTo section of the LAMMPS manual.  If this is still problematic,
contributors may contact any of the core LAMMPS developers for help or
to create a pull request on their behalf.  This latter way of submission
may delay the integration as it depends on the amount of time required
to prepare the pull request and free time available by the LAMMPS
developer in question to spend on this task.

## Integration Testing (strict)

Contributed code, like all pull requests, must pass the integration
tests on GitHub before it can be merged with the LAMMPS distribution.
These tests compile LAMMPS in a variety of environments and settings
and run the bundled unit tests.  At the discretion of the LAMMPS developer
managing the pull request, additional tests may be activated that test
for "side effects" on running a collection of input decks and create
consistent results.  Also, the translation of the documentation to HTML
and PDF is tested for.

Some "disruptive" changes may break tests and require updates to the
testing tools or scripts or tests themselves.  This is rare.  If in
doubt, contact the LAMMPS developer that is assigned to the pull request
for further details and explanations and suggestions of what needs to be
done.

## Documentation (strict) and Examples (preferred)

Contributions that add new styles or commands or augment existing ones
must include the corresponding new or modified documentation in
ReStructuredText format (.rst files in the "doc/src/" folder). The documentation
shall be written in american english and the .rst file must use only
ASCII characters so it can be cleanly translated to PDF files (via sphinx
and pdflatex). Special characters may be included via embedded
math expression typeset in a LaTeX subset.

Contributions that add or modify the library interface or "public" APIs
from the C++ code or the Fortran module must include suitable doxygen
comments in the source and corresponding changes to the documentation
sources for the "Programmer Guide" guide section of the LAMMPS manual.

In most cases, it is preferred that example scripts (simple, small, fast to complete on 1 CPU) 
are included that demonstrate the use of new or extended functionality. These are typically
under the examples or examples/USER directory.  A few guidelines for such example input decks.

- commands that generate output should be commented out (except when the
  output is the sole purpose or the feature, e.g. for a new compute).
- no commands like "log", "echo", "package", "processors", "suffix"
  may be used in the input file (exception: "processors * * 1" or similar is acceptable
  when used to avoid unwanted domain decomposition of empty volumes).
- outside of the log files no generated output should be included
- custom thermo_style settings may not include output measuring CPU or other time
- input files should be named "in.name", data files should be named
  "data.name" and log files should be named "log.version.name.compiler.ncpu"
- the total file size of all the inputs and outputs should be small
- where possible potential files from the "potentials" folder or data file from
 other folders should be re-used through symbolic links

## Programming Style Requirements

The LAMMPS developers aim to have a consistent programming style and
naming conventions across the entire code base, as this helps with
maintenance, debugging, and understanding the code, both for developers and users.

### Command or Style names and keywords (mostly strict)

All user-visible command or style names should be all lower case
and should only use letters, numbers, or forward slashes.  They
should be descriptive and initialism should be avoided unless they
are well established (e.g. lj for Lennard-Jones).  For a compute
style "some/name" the source files must be called `compute_some_name.h`
and `compute_some_name.cpp`. The "include guard" would then be
`LMP_COMPUTE_SOME_NAME_H` and the class name `ComputeSomeName`.

### Whitespace and permissions (preferred)

Source files should not contain TAB characters unless required by
the syntax (e.g. in makefiles) and no trailing whitespace.  Text
files should be added with Unix-style line endings (LF-only); use
dos2unix on Linux machines to convert.  Text files should have a
line ending on the last line.

All files should have 0644 permissions, i.e writable to the user
only and readable by all and no executable permissions.  Executable
permissions (0755) should only be on shell scripts or python or similar
scripts for interpreted script languages.

### Indentation and Placement of Braces (strongly preferred)

LAMMPS uses 2 characters per indentation level and lines should be
kept within 100 characters wide.

For new files added to the "src" tree, a clang-format configuration file
compatible with clang-format version 8 or later is provided in the "src"
folder under the name `.clang-format`.  With that file present files can
be reformatted according to the configuration with a command like:
`clang-format -i new-file.cpp`.  Ideally, this is done while writing the
code or before a pull request is submitted. Blocks of code where
the reformatting from clang-format yields undesirable output may be
protected with placing a pair `// clang-format off` and `// clang-format on`
comments around that block.

The file "src/utils.cpp" may be consulted as example.

**Comment by sjplimp** [comment]
@akohlmey I made some small edits.  If this is going to end up long, it should have some form of a TOC at the top to guide people where to look.  I also think that interspersing Strict and Preferred may not be best.  E.g. listing all the Strict things first would be better.  So a big Strict section, then a big Preferred section.

**Comment by akohlmey** [comment]
> @akohlmey I made some small edits. If this is going to end up long, it should have some form of a TOC at the top to guide people where to look.

Let us get all the bits and pieces in places first and worry about the specific format later. Adding a TOC is trivial to do at the end.

> I also think that interspersing Strict and Preferred may not be best. E.g. listing all the Strict things first would be better. So a big Strict section, then a big Preferred section.

I would find that rather confusing. I was going from the generic to the specific, trying to follow the decision process and the timeline of how you would be doing things. I am open for reordering subsections on equivalent levels, but even then there often there is no easy separation. So having to split things into spatially distant sections will require that a) the reader remembers what was written in a different and possibly quite distant section and b) that details and phrases will have to be repeated (and thus making this document even longer) so they can be read and understood by themselves, while the current ordering can be more compact since the context is already given.

**Comment by rbberger** [comment]
@akohlmey Did an initial pass over it, fixing up some typos.

**Comment by tabedzki** [comment]
For what it is worth, I like the current format where each section has its strictness associated with the topic rather than the topics associated by strictness. It is easier to read as an outside contributor.

**Comment by ellio167** [comment]
I'm wondering why `GPL-2.0-only` instead of `GPL-2.0-or-later` is chosen for the LAMMPS license?  It seems this was changed from `GPL-2.0-or-later` to `GPL-2.0-only` on March 5, 2021 (#2644). Just thinking it might be good to have a record of the reason somewhere.

**Comment by akohlmey** [comment]
> I'm wondering why `GPL-2.0-only` instead of `GPL-2.0-or-later` is chosen for the LAMMPS license? It seems this was changed from `GPL-2.0-or-later` to `GPL-2.0-only` on March 5, 2021 (#2644). Just thinking it might be good to have a record of the reason somewhere.

When we had discussed the exact license terms (and providing an LGPL version on request), the discussion ended with GPL v2 and LGPLv2.1 as the selected licenses. There are conditions in the v3 versions that some of us didn't like. It always said GPLv2 and LGPLv2.1 on the pull request submit form. I suppose nobody noticed before the commit your are referring to that some of the files in the distribution were contradicting our intentions.

**Comment by akohlmey** [comment]
FWiW, the topic of GPLv3 vs GPLv2 came last up when adding the USER-PACE package and that is one of the reasons why the bulk of the code is external.

**Comment by ellio167** [comment]
> FWiW, the topic of GPLv3 vs GPLv2 came last up when adding the USER-PACE package and that is one of the reasons why the bulk of the code is external.

Thanks for the reply.  However, doesn't the USER-PACE example highlight the sort of problem that can come up?  In particular, a binary of LAMMPS with USER-PACE is currently being distributed through the conda-forge project (https://github.com/conda-forge/lammps-feedstock).  This is, I think, a violation of the LAMMPS license and should not be allowed.  However if LAMMPS was licensed under `GPL-2.0-or-later` then there would be no problem with distribution of the conda-forge binary (it would be licensed as GPL-3.0).

**Comment by ellio167** [comment]
But I guess I still don't understand the reluctance to use `GPL-2.0-or-later` for LAMMPS.  That is a specific license, distinct from `GPL-2.0-only` and I would expect the LAMMPS project would only accept content under that license (and the, ideally, `LGPL-2.1-or-later`).

Is there a concern that others would take lammps and add `GPL-3.0` content so that everything in their modified distribution was now `GPL-3.0` and that this would prohibit the LAMMPS project from incorporating the modifications back into the official LAMMPS distribution?  Or something else?

**Comment by akohlmey** [comment]
@ellio167 even for GPL-2.0-or-later **all** contributions to LAMMPS **must** be GPLv2 or else they force us to use GPLv3 for the entire distribution, since GPLv3 doesn't have a 3.0-or-earlier clause. Remember the license applies to **distribution** and all GPL licences are deliberately "infectious" to enforce at the minimum their own terms for distribution.

As stated earlier, GPLv3 has restrictions over GPLv2 that we didn't want to have applied to LAMMPS.

At the end this is really only a problem for **binary** distribution of LAMMPS and the USER-PACE package is the only package where this currently makes a difference and - as stated earlier - the USER-PACE developers made an informed decision.
