### ISSUE TITLE
[BUG] GPU binning/neighbor build broken when using CUDA with GPU package

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#2656]
**Summary**

Since the February upgrade of the GPU package, running benchmarks with the GPU package will fail.

The problem seems to be caused when GPU binning is enabled.

Both `neigh no` and `neigh hybrid` work. `neigh yes`, the default, will fail.

Forcing `LAL_USE_OLD_NEIGHBOR` does not help.

**LAMMPS Version and Platform**

current master
last working commit: 06e484d3e0a03e0a1bf3479ede1aa0c89876dced
first broken commit: e7e2d2323be2885eb2e496f08ff6fb6de47ab1f7

NVIDIA Titan V, CUDA 11.2, Driver: 460.56

**Expected Behavior**

Benchmark completes successfully.

**Actual Behavior**

Benchmark fails due to non-numeric values.

```
ERROR on proc 0: Non-numeric atom coords - simulation unstable (src/domain.cpp:548)
```

**Steps to Reproduce**

```
$ mkdir build
$ cmake -C ../cmake/presets/minimal.cmake -D PKG_GPU=on -D GPU_API=CUDA -D GPU_ARCH=sm_70 ../cmake
$ make -j 4
$ ./lmp -in ../bench/in.lj -sf gpu -pk gpu 0 neigh yes
```

| Command-line | State |
| --- | --- |
| `./lmp -in ../bench/in.lj -sf gpu -pk gpu 0 neigh yes` | FAILS |
| `./lmp -in ../bench/in.lj -sf gpu -pk gpu 0 neigh no` | OK |
| `./lmp -in ../bench/in.lj -sf gpu -pk gpu 0 neigh hybrid` | OK |

**Further Information, Files, and Links**

**Comment by rbberger** [comment]
@wmbrownIntel @ndtrung81 looks like we have a regression with CUDA.

**Comment by ndtrung81** [comment]
@rbberger thanks for pointing this out. There is something specific to CUDA 11.2 that makes the neighbor build kernel gives incorrect results as indicated in the current source code. This doesn't happen to CUDA 11.1.

**Comment by wmbrownIntel** [comment]
@rbberger FYI, on modern NVIDIA GPUs it will be better for performance to compile without the USE_CUDPP flag when forcing the old neighbor build (and this will eliminate the error). Unfortunately, as Trung noted and you might already be aware, there seems to be a compiler bug impacting the new neighbor build algorithm with CUDA 11.2 (so it reverts to the old neighbor build for this specific version).

@ndtrung81 Can you remove or comment out USE_CUDPP from any of the legacy Makefiles we provide for the GPU package? This should fix any issue for users.

Regardless of performance, I was planning on keeping this GPU binning option available (and working) for any potential future work to make this more performant. I will submit a patch, probably this week.

Thank you both!

**Comment by akohlmey** [comment]
@wmbrownIntel commit d1b4af60a35b4489b9f182f3e3728073b15b2c3a should do what you ask for until better options are available. We are currently working towards getting the unit tests running with the GPU package ( many tests already run with the code in PR #2308 ) and we are about to get additional hardware for expanding those tests to run on different hardware/backends as part of the automated testing. That should help to detect issues like this one sooner in the future.
