### ISSUE TITLE
[BUG] fix gcmc doesn't work when USER-INTEL is used in MD simulation

### ISSUE THREAD

**Issue by ciiii0001** [lammps/lammps#2672]
**Summary**
As documented, *fix gcmc* can be used with *fix nvt* to run grand canonical MD simulation. However, if USER-INTEL package is used in such simulation, *fix gcmc* seems stop working.

**LAMMPS Version and Platform**
Both tested on a cluster and my own computer.
cluster: LAMMPS patch_10Mar2021, Red Hat Enterprise Linux Server release 7.3 (Linux version 3.10.0), Intel Xeon E5-2690A V4
my computer: pre-built binary from http://packages.lammps.org/windows.html (29Oct2020, 64bit non-MPI), Win10 20H2, AMD Ryzen 5 2600X

**Expected Behavior**
The atom count should increase or decrease (increase in this case) due to GCMC exchanges, like this in thermo output
Step Atoms
       0        2
     100        3
     200        3
     300        6
     400        9

The behavior is tested correct when using no acceleration packages, or using GPU (CUDA), or KOKKOS (CUDA), or USER-OMP.

**Actual Behavior**
The atom count doesn't change over time (like thermo output below). It can be further comfirmed by looking at dump file.
Step Atoms 
       0        2 
     100        2 
     200        2 
     300        2 
     400        2 

This behavior occurs when using USER-INTEL.

**Steps to Reproduce**
Here is a demo input: 
[demo.zip](https://github.com/lammps/lammps/files/6170101/demo.zip)
run with USER-INTEL: *lammps_executable_path -sf intel -i in.in*
run without USER-INTEL: *lammps_executable_path -i in.in*

**Comment by akohlmey** [comment]
@ciiii0001 thanks for the detailed report and a well made demo input deck that allowed to investigate the issue easily and quickly.  I think I have identified the reason and the following fix will be in the next patch release.
```
  diff --git a/src/MC/fix_gcmc.cpp b/src/MC/fix_gcmc.cpp
  index e8087f1344..b8eecf95ca 100644
  --- a/src/MC/fix_gcmc.cpp
  +++ b/src/MC/fix_gcmc.cpp
  @@ -2330,7 +2330,9 @@ double FixGCMC::energy_full()
     // unlike Verlet, not performing a reverse_comm() or forces here
     // b/c GCMC does not care about forces
     // don't think it will mess up energy due to any post_force() fixes
  +  // but Modify::pre_reverse() is needed for USER-INTEL
   
  +  if (modify->n_pre_reverse) modify->pre_reverse(eflag,vflag);
     if (modify->n_post_force) modify->post_force(vflag);
     if (modify->n_end_of_step) modify->end_of_step();
   
  diff --git a/src/MC/fix_widom.cpp b/src/MC/fix_widom.cpp
  index 4a06dbafbd..a1bdc32515 100644
  --- a/src/MC/fix_widom.cpp
  +++ b/src/MC/fix_widom.cpp
  @@ -1057,7 +1057,9 @@ double FixWidom::energy_full()
     // unlike Verlet, not performing a reverse_comm() or forces here
     // b/c Widom does not care about forces
     // don't think it will mess up energy due to any post_force() fixes
  +  // but Modify::pre_reverse() is needed for USER-INTEL
   
  +  if (modify->n_pre_reverse) modify->pre_reverse(eflag,vflag);
     if (modify->n_pre_force) modify->pre_force(vflag);
     if (modify->n_end_of_step) modify->end_of_step();
   

```

**Comment by ciiii0001** [comment]
Thanks for your quick response and fix! I edited the source according to your commit and it works.
