### ISSUE TITLE
[BUG] Format error when read_data nocoeff

### ISSUE THREAD

**Issue by jdevemy** [lammps/lammps#2673]
**Summary**

When running a Lammps simulation with an hybrid pair_style and a read_data put after the pair_style line, Lammps crashes with the error:

`fmt::format_error: string pointer is null`

**LAMMPS Version and Platform**

Last dev version from github : **LAMMPS (10 Mar 2021)**

**Expected Behavior**

Not crashing

**Actual Behavior**

It crashes

**Steps to Reproduce**

Here's a simple example with an input and data file:

[bug_format.zip](https://github.com/lammps/lammps/files/6171357/bug_format.zip)

**Further Information, Files, and Links**

The exception comes from `neighbor.cpp` code, in the `print_pairwise_info` method.

The line `char *pname = force->pair_match_ptr((Pair *) rq->requestor);` returns `null` and so the format raises an exception.

The `null` comes because the `force->pairstyle` has been set to `zero` in the `read_data.cpp` code, and has not been reput to the old values.
In `read_data.cpp`, when `nocoeff` the pair is saved to `saved_pair` and restore, but `force->pairstyle` remains at `zero`.

With the `03 Mar 2020`, the bug does not arise, but the output contains `(null)`:
` 
 (1) pair (null), perpetual, skip from (3)
      attributes: half, newton on
      pair build: skip
      stencil: none
      bin: none
  (2) pair (null), perpetual, skip from (3)
      attributes: half, newton on
      pair build: skip
      stencil: none
      bin: none
...
`
This part of the code is a little too tricky for me, it's why I didn't provide you a fix.

Thanks !

**Comment by akohlmey** [comment]
Thanks for the report and for providing a simple reproducing input deck. There are two issues at hand: 1. the format output should be protected from NULL pointers (even though they should not happen in the first place), and 2. not only the force style classes need to be saved, but they style names as well. This will be done in a forthcoming patch.

**Comment by jdevemy** [comment]
Thanks @akohlmey for the quick fix!
