### ISSUE TITLE
[BUG] Documentation of `angle_style cosine/periodic` differs from implementation

### ISSUE THREAD

**Issue by acroy** [lammps/lammps#2676]
**Summary**

The documentation of `angle_style cosine/periodic` differs from the implementation. Apparently, the expressions "force constant" and "prefactor" have been interchanged in the manual. Additionally, there is a factor 2 appearing in the energy computation which is not documented.

**LAMMPS Version and Platform**

This concerns all platforms.  

**Expected Behavior**

The [manual states](https://lammps.sandia.gov/doc/angle_cosine_periodic.html) that the expression for the energy is

E = C [1 - B (-1)^n cos(n &#920;)]

Further, regarding the coefficients one reads "Note that the prefactor C is specified and not the overall force constant K = C/n^2".

**Actual Behavior**

According to the [source code](https://github.com/lammps/lammps/blob/c4e1255f3e94b502f7071e793c40f6fdf173fbfc/src/MOLECULE/angle_cosine_periodic.cpp) one finds for the initialisation of the coefficients (lines 198-221) that
```
    k[i] = c_one/(n_one*n_one);
    b[i] = b_one;
    multiplicity[i] = n_one;
```
and later in the evaluation (line 298 and also line 140)
```
  return 2.0*k[type]*(1.0-b[type]*powsign(multiplicity[type])*c);
```
The specified coefficient C (here called c_one) is not used as the _prefactor_ (which is here called k), but corresponds to the _force constant_.  Moreover, there is an additional factor 2 which is not documented. Accordingly, the documentation should state that "the force constant K has to be specified and the prefactor C=2 K/n^2 will be used".

**Further Information, Files, and Links**
If one takes, for example, B=1 and n=1,3,5 then the energy is minimal for &#920;=&#960;/n. Expanding the energy expression at the minimum gives

E = (1/2) C n^2 (&#920; - &#960;/n)^2 = K (&#920; - &#960;/n)^2

as expected if one sets C=2 K/n^2. It should possibly be noted that sometimes 2K is denoted as force constant.

**Comment by akohlmey** [comment]
Thanks for reporting. However the proposed changes don't appear consistent to me. To avoid changing the code itself, the energy function in the documentation has to become: E = 2C [1 - B (-1)^n cos(n Θ)]. It also appears that the documentation incorrectly associates this angle style with DREIDING, while the angle potential in the corresponding publication is implemented in LAMMPS as angle style `cosine/squared`.

The term prefactor in the documentation is a synonym for coefficient and not related to the implementation.
This should be corrected in the next patch release of LAMMPS.

**Comment by acroy** [comment]
However, the prefactor used in the energy calculation is 2*[user-specified-value-C]/[user-specified-value-n]^2 and not 2*[user-specified-value-C]. The normalisation is critical here. IMO the implementation is perfectly fine, only the docs need to be updated.

**Comment by akohlmey** [comment]
> However, the prefactor used in the energy calculation is 2*[user-specified-value-C]/[user-specified-value-n]^2 and not 2*[user-specified-value-C]. The normalisation is critical here. IMO the implementation is perfectly fine, only the docs need to be updated.

let me reiterate: the use of the term "prefactor" in the documentation has **nothing** to do with the implementation.

**Comment by acroy** [comment]
I am sorry for being persistent, but how should one know **from the documentation** that in fact E = 2C/n^2 [1 - B (-1)^n cos(n  Θ)] is calculated if you write that it is E = 2C [1 - B (-1)^n cos(n Θ)]?

**Comment by akohlmey** [comment]
You are correct to be persistent. The expression for the energy is missing the 1/n**2 term. Please see the following LAMMPS input for confirmation. It computes the angle energy for 3 cases and shows that for this case the difference between the manually computed energy `E_angle` and the energy LAMMPS computes, `eangle` is zero.

```

units real
atom_style molecular
atom_modify sort 0 1.0
comm_modify cutoff 0.1
region box block -10 10 -10 10 -10 10
create_box 1 box angle/types 1 extra/angle/per/atom 1 extra/special/per/atom 2

angle_style cosine/periodic
mass * 1.0
create_atoms 1 single 0.0 0.0 0.0
create_atoms 1 single 0.0 0.0 0.0
create_atoms 1 single 0.0 0.0 0.0
create_bonds single/angle 1 1 2 3


variable c index 1.1
variable n index 1 2 3 4

label nextn
variable b index 1 -1

label nextb

variable angle index 90.0 180.0 45.0
variable C equal v_c
variable B equal v_b
variable N equal v_n
variable ANGLE equal v_angle
variable E_angle equal 2.0/(v_n*v_n)*v_C*(1.0-(v_B*(-1.0)^v_n)*cos(v_n*v_angle/180.0*PI))
variable ediff equal v_E_angle-eangle

thermo_style custom eangle v_C v_B v_N v_ANGLE v_E_angle v_ediff
angle_coeff 1 $c $b $n

set atom 1 x 1.0 y 0.0 z 0.0
set atom 2 x 0.0 y 0.0 z 0.0
set atom 3 x 0.0 y 1.0 z 0.0

run 0 post no
next angle

set atom 1 x 1.0 y 0.0 z 0.0
set atom 2 x 0.0 y 0.0 z 0.0
set atom 3 x -1.0 y 0.0 z 0.0

run 0  post no
next angle

set atom 1 x 1.0 y 0.0 z 0.0
set atom 2 x 0.0 y 0.0 z 0.0
set atom 3 x 1.0 y 1.0 z 0.0

run 0  post no

variable angle delete

next b
jump SELF nextb

next n
jump SELF nextn
```

**Comment by acroy** [comment]
Thanks for following up on this. Your input file nicely shows the "problem" (the code is fine, but the docs don't match).

**Comment by akohlmey** [comment]
> Thanks for following up on this. Your input file nicely shows the "problem" (the code is fine, but the docs don't match).

actually, upon closer review, I have found that the computation of the equilibrium angle is incorrect for `B == -1`.
in summary, pull request #2678 has now the following changes:
- correct description of energy function and force constant K in angle style `cosine/periodic` docs
- correct computation of equilibrium angle in angle style `cosine/periodic` for `B == -1`
- update unit test gold standard for angle style `cosine/periodic`
- move attribution of being the angle style for DREIDING to angle style `cosine/squared`

**Comment by paulboone** [comment]
Thank you @acroy for finding and reporting this. I was just setting up cosine/periodic this week and relied on the docs (which are usually both excellent and correct) and I didn't double-check the source code.
