### ISSUE TITLE
[BUG] Deposit rigid molecules failed with wrong atom positions

### ISSUE THREAD

**Issue by davidfir3** [lammps/lammps#2684]
**Summary**
I was trying to deposit rigid molecules onto the surface of a substrate via "fix deposit" command (fix d pentacene deposit 50 0 250000 86 mol pentacene region surface local 30 30 5 vz -0.1 -0.1 units box attempt 100 rigid pentacenenvt). It seems that all atoms of rigid molecules will be put at (0, 0, 0) if the target group ( "pentacene") is empty before deposition, causing severe overlapping.
---------------------Input script---------------------------------------------------------------------------------------------------------

```
# ----------------- Init Section -----------------

include "system.in.init"

# ----------------- Atom Definition Section -----------------
 
read_data silica75x75x25.data extra/atom/types 67 extra/bond/types 253 extra/angle/types 155 extra/dihedral/types 47 extra/improper/types 5 extra/special/per/atom 40 extra/bond/per/atom 5 extra/angle/per/atom 3 extra/dihedral/per/atom 9 extra/improper/per/atom 4

# ----------------- Settings Section -----------------

include "system.in.settings"

# ----------------- Run Section -----------------

#Initiate silica substrate
group silica id <> 1 9375
region fixedsilica block 0 75 0 75 0 15 units box
group fixedsilica region fixedsilica
group mobilesilica subtract silica fixedsilica
group mobile subtract all fixedsilica

group pentacene subtract all silica

velocity all create 500 123456 mom yes rot yes dist gaussian
run 0
velocity all scale 500


#Minimization
# minimize 1.0e-6 1.0e-7 1000 10000

#Output
compute_modify thermo_temp dynamic/dof yes
compute Tsilica mobilesilica temp
compute Tpentacene pentacene temp
compute_modify Tpentacene dynamic/dof yes
thermo_style custom step temp c_Tsilica c_Tpentacene atoms
thermo 10

#Init new pentacene mol
molecule pentacene pentacene.txt
region surface block 0 75 0 75 55 55 units box

#Run simulation
run 1
fix silicanvt mobilesilica nvt temp 500.0 500.0 100.0
fix pentacenenvt pentacene rigid/nvt/small molecule temp 500.0 500.0 100.0 mol pentacene
fix_modify pentacenenvt dynamic/dof yes #requred for fix deposit with "rigid" keyword
fix d pentacene deposit 50 0 250000 86 mol pentacene region surface local 30 30 5 vz -0.1 -0.1 units box attempt 100 rigid pentacenenvt
timestep 1

#Loop
label lp
variable i loop 50

    dump 1 all custom 100 dump$i.lammpstrj id mol type x y z ix iy iz
    run 250000
    undump 1
    write_data system$i.data nocoeff nofix

next i
jump SELF lp
```
---------------------Error message---------------------------------------------------------------------------------------------------------
```
Step Temp c_Tsilica c_Tpentacene Atoms
       1          500     494.8438            0     9375
      10          nan    455.58963          nan     9411
      20         -nan    505.86573         -nan     9411
      30          nan    547.59824          nan     9411
ERROR on proc 0: Non-numeric atom coords - simulation unstable (src/domain.cpp:548)
```
----------------------------------------------------------------------------------------------------------------------------------------------

It works fine if the target group has already had molecules or molecules to be deposited are not rigid (without rigid keyword and using a normal nvt fix).  So I'm convinced that it's not the problem of input files (including data file and molecule template file).

**LAMMPS Version and Platform**
LAMMPS Version: 10 Mar 2021 Git info (master / patch_10Mar2021-150-g47b7653d4)
OS:  Linux 5.4.72-microsoft-standard-WSL2 on x86_64

**Expected Behavior**
Rigid molecules should be inserted into target region.

**Actual Behavior**
All atoms are put at (0, 0, 0)

**Comment by akohlmey** [comment]
@davidfir3 please try using fix rigid/small instead of fix rigid/nvt/small

**Comment by akohlmey** [comment]
@davidfir3 after some more debugging I can confirm that currently only fix rigid/small is compatible with fix deposit. There were changes to `fix rigid/{nve,nvt,nph,npt}/small` that render them incompatible with adding rigid objects on the fly. A check for this will be added to the code and LAMMPS will then abort with an error message.

**Comment by davidfir3** [comment]
@akohlmey Thanks for your reply. I have tried fix rigid/small and it works well on cpu. However, it's strange that when I tried to run the same script on gpu with "-sf gpu -pk gpu 1" keywords, "Error Lost Atoms" occurred followed by many lines of "cuda driver error 4".
```
Step Temp c_Tsilica c_Tpentacene Atoms
       1          500     494.8438            0     9375
ERROR: Lost atoms: original 9411 current 9153 (src/thermo.cpp:427)
Last command:     run 250000
Cuda driver error 4 in call at file '/home/osc111station/lammps/lib/gpu/geryon/nvd_timer.h' in line 98.
```
Another thing is that when I tried to manually deposit one molecule using the script below, it worked well on cpu but failed on gpu again with a "Cuda driver error 700 in call at file '/home/osc111station/lammps/lib/gpu/geryon/nvd_memory.h' in line 502." message. Is there any bugs here?
```
# ----------------- Init Section -----------------

include "system.in.init"

# ----------------- Atom Definition Section -----------------
 
read_data silica75x75x25.data extra/atom/types 67 extra/bond/types 253 extra/angle/types 155 extra/dihedral/types 47 extra/improper/types 5 extra/special/per/atom 40 extra/bond/per/atom 5 extra/angle/per/atom 3 extra/dihedral/per/atom 9 extra/improper/per/atom 4
#Init new pentacene mol
molecule pentacene pentacene.txt
region surface block 0 75 0 75 55 55 units box
create_atoms 0 random 1 566 surface mol pentacene 231 units box
# ----------------- Settings Section -----------------

include "system.in.settings"

# ----------------- Run Section -----------------

#Initiate silica substrate
group silica id <> 1 9375
region fixedsilica block 0 75 0 75 0 15 units box
group fixedsilica region fixedsilica
group mobilesilica subtract silica fixedsilica
group mobile subtract all fixedsilica

group pentacene subtract all silica
velocity all create 500 123456 mom yes rot yes dist gaussian
run 0
velocity all scale 500
velocity pentacene set 0 0 -0.1 units box

#Minimization
# minimize 1.0e-6 1.0e-7 1000 10000

#Output
compute_modify thermo_temp dynamic/dof yes
compute Tsilica mobilesilica temp
compute Tpentacene pentacene temp
compute_modify Tpentacene dynamic/dof yes
thermo_style custom step temp c_Tsilica c_Tpentacene atoms
thermo 1000


#Run simulation
run 1
fix silicanvt mobilesilica nvt temp 500.0 500.0 100.0
fix pentacenenvt pentacene rigid/nvt/small molecule temp 500.0 500.0 100.0
timestep 1

dump 1 all custom 100 dumpinit.lammpstrj id mol type x y z xu yu zu
run 250000
write_data silica75x75x25with1pentacene.data nocoeff nofix
```

**Comment by ndtrung81** [comment]
@daviddfir3 did you happen to use pair hybrid in system.in.settings? if so, you can try "-sf gpu -pk gpu 1 neigh no". There are also some unresolved issues with the neighbor builds on the GPU, particularly with pair hybrid.

**Comment by davidfir3** [comment]
@ndtrung81 that is exactly what I am doing. But "neigh no" doesn't work, shown as below. But still thank you. And thank you @akohlmey, too.
```
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 2196 RUNNING AT DESKTOP-1JDHGEG
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by ndtrung81** [comment]
@davidfir3 would you mind sharing a complete yet simplified input deck that reproduces the issue (i.e. including a small-sized data file and system.in.settings)?

**Comment by davidfir3** [comment]
@ndtrung81 Sure.
[test.zip](https://github.com/lammps/lammps/files/6237711/test.zip)
