### ISSUE TITLE
Kokkos Fix ReaxC Bonds gives incomplete output in parallel

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#270]
Kokkos Fix ReaxC Bonds gives incomplete output in parallel, bugfix release is pending.

Here is the fix:

<pre>
===================================================================
--- KOKKOS/fix_reaxc_bonds_kokkos.cpp   (revision 15856)
+++ KOKKOS/fix_reaxc_bonds_kokkos.cpp   (revision 15857)
@@ -103,6 +103,7 @@
     ((PairReaxCKokkos<LMPDeviceType>*) reaxc)->PackBondBuffer(k_buf,nbuf_local);
   else
     ((PairReaxCKokkos<LMPHostType>*) reaxc)->PackBondBuffer(k_buf,nbuf_local);
+  buf[0] = nlocal;

   // Receive information from buffer for output
   RecvBuffer(buf, nbuf, nbuf_local, nlocal_tot, numbonds_max);
@@ -110,6 +111,8 @@
   memory->destroy_kokkos(k_buf,buf);
 }

+/* ---------------------------------------------------------------------- */
+
 double FixReaxCBondsKokkos::memory_usage()
 {
   double bytes;
Index: KOKKOS/fix_reaxc_bonds_kokkos.h
===================================================================
--- KOKKOS/fix_reaxc_bonds_kokkos.h     (revision 15856)
+++ KOKKOS/fix_reaxc_bonds_kokkos.h     (revision 15857)
@@ -32,7 +32,7 @@
   void init();

  private:
-  double nbuf;
+  int nbuf;
   void Output_ReaxC_Bonds(bigint, FILE *);
   double memory_usage();
 };

**Comment by akohlmey** [comment]
Fixed in commit 9806da69f3f9dea9aa8e66b141c3b3f146e9aa56
