### ISSUE TITLE
Installation failed for LAMMPS version 29Oct2020 compiled with intel

### ISSUE THREAD

**Issue by AmbreSA** [lammps/lammps#2709]
**Description**

I tried to compile LAMMPS version 29Oct2020 (stable) with the compiler intel icc 2020 and openmpi 4, but I got the following errors and the installation stopped :

``
ld: cannot find /.../Intel/.../compilers_and_libraries_2020.0.166/linux/compiler/lib/intel64_lin/i_ofldbegin_target.o: No such file or directory
ld: cannot find -lioffload_target
``

How can I avoid these errors ? I don't want to use the offload feature.

**Comment by akohlmey** [comment]
@AmbreSA  There is not enough information here to make any assessment of where things went wrong. Please report in detail the steps you did to compile LAMMPS and what platform you are running on.

**Comment by AmbreSA** [comment]
I use these options of cmake to compile LAMMPS :  

``
     -C %(builddir)s/lammps-stable_29Oct2020/cmake/presets/all_off.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=on -DPKG_PYTHON=on -DBUILD_LIB=on -DCMAKE_INSTALL_LIBDIR=%(installdir)s/lib -DLAMMPS_EXCEPTIONS=on -DCMAKE_INSTALL_PREFIX=%(installdir)s -DPKG_ASPHERE=on -DPKG_BODY=on -DPKG_CLASS2=on -DPKG_COLLOID=on -DPKG_CORESHELL=on -DPKG_DIPOLE=on -DPKG_GRANULAR=on -DPKG_KSPACE=on -DPKG_MANYBODY=on -DPKG_MC=on -DPKG_MISC=on -DPKG_MOLECULE=on -DPKG_MPIIO=on -DPKG_OPT=on -DPKG_PERI=on -DPKG_POEMS=on -DPKG_QEQ=on -DPKG_REAX=on -DPKG_REPLICA=on -DPKG_RIGID=on -DPKG_SHOCK=on -DPKG_SNAP=on -DPKG_SPIN=on -DPKG_SRD=on -DPKG_USER-ATC=on -DPKG_USER-AWPMD=on -DPKG_USER-BOCS=on -DPKG_USER-CGDNA=on -DPKG_USER-CGSDK=on -DPKG_USER-COLVARS=on -DPKG_USER-DIFFRACTION=on -DPKG_USER-DPD=on -DPKG_USER-DRUDE=on -DPKG_USER-EFF=on -DPKG_USER-FEP=on -DPKG_USER-INTEL=on -DPKG_USER-LB=on -DPKG_USER-MANIFOLD=on -DPKG_USER-MEAMC=on -DPKG_USER-MESO=on -DPKG_USER-MGPT=on -DPKG_USER-MISC=on -DPKG_USER-MOFFF=on -DPKG_USER-OMP=yes -DPKG_USER-PHONON=on -DPKG_USER-PTM=on -DPKG_USER-QTB=on -DPKG_USER-REAXC=on -DPKG_USER-SMTBQ=on -DPKG_USER-SDPD=on -DPKG_USER-SPH=on -DPKG_USER-TALLY=on -DPKG_USER-UEF=on -DPKG_VORONOI=on -DVORO_LIBRARY=$EBROOTVOROPLUSPLUS/lib/libvoro++.a -DVORO_INCLUDE_DIR=$EBROOTVOROPLUSPLUS/include/voro++ -DTBB_LIBRARY=$EBROOTTBB/tbb/lib/intel64/gcc4.8/libtbb.so -DTBB_INCLUDE_DIR=$EBROOTTBB/tbb/include -DTBB_MALLOC_LIBRARY=$EBROOTTBB/tbb/lib/intel64/gcc4.8/libtbbmalloc.so -DTBB_MALLOC_INCLUDE_DIR=$EBROOTTBB/tbb/include -DCMAKE_PREFIX_PATH=$EBROOTGSL_ROOT -DCMAKE_C_FLAGS="-I$EBROOTTBB/tbb/include -qopenmp -qno-openmp-offload $EBVARCFLAGS" -DCMAKE_CXX_FLAGS="-I$EBROOTTBB/tbb/include -qopenmp -qno-openmp-offload -I$EBROOTMKL/mkl/lib/intel64/ $EBVARCXXFLAGS" -DCMAKE_Fortran_FLAGS="-I$EBROOTTBB/tbb/include -qopenmp -qno-openmp-offload $EBVARFCFLAGS" -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DPKG_GPU=ON -DGPU_API=cuda -DCUDA_CUDA_LIBRARY=$EBROOTCUDA/lib64/stubs/libcuda.so -DGPU_ARCH="-gencode arch=compute_60,code=[sm_60,compute_60] -gencode arch=compute_70,code=[sm_70,compute_70] -gencode arch=compute_80,code=[sm_80,compute_80]" -DCMAKE_EXE_LINKER_FLAGS="-L$EBROOTIFORT/lib/intel64 -DINTEL_ARCH=cpu 
``

The name model of the platform I am running on is Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz.

**Comment by akohlmey** [comment]
This essentially indecipherable and impossible to debug. Some of these settings make no sense or are even contradicting the documentation. Please note that platform includes the OS (I assume Linux, but which kind of Linux?). Can you please narrow this down to the smallest number of packages and explicit settings that reproduces the link failure and then also provide the CMake output. It would also be extremely helpful to see more of the error message or the preceding command.

**Comment by akohlmey** [comment]
@AmbreSA did you manage to narrow down which CMake configuration option(s) are responsible for causing your compilation/linking troubles?
