### ISSUE TITLE
[BUG] GPU package fails with both CUDA and OpenCL on NVIDIA drivers 465.24.02 and 465.19.01 (CUDA 11.3)

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#2718]
**Summary**

Compiling and trying to run with the GPU package on NVIDIA drivers v465 either with CUDA 11.3 or OpenCL fails.

Current workarounds:
* Compile with CUDA 11.2 and running on 11.3 drivers seems to work for CUDA only
* For OpenCL, downgrade to CUDA 11.2 drivers (v460.27.04) is necessary

**LAMMPS Version and Platform**

current master

**Expected Behavior**

```
$ cd examples/melt
$ ../../build/lmp -in in.melt -sf gpu
```

This should run and complete without error

**Actual Behavior**

```
$ ../../build/lmp -in in.melt -sf gpu
LAMMPS (10 Mar 2021)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6795962 1.6795962 1.6795962
Created orthogonal box = (0.0000000 0.0000000 0.0000000) to (16.795962 16.795962 16.795962)
  1 by 1 by 1 MPI processor grid
Created 4000 atoms
  create_atoms CPU = 0.000 seconds

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:
- GPU package (short-range, long-range and three-body potentials):
The log file lists these citations in BibTeX format.

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE


--------------------------------------------------------------------------
- Using acceleration for lj/cut:
-  with 1 proc(s) per device.
-  Horizontal vector operations: ENABLED
-  Shared memory system: No
--------------------------------------------------------------------------
Device 0: NVIDIA TITAN V, 80 CUs, 11/12 GB, 1.5 GHZ (Mixed Precision)
--------------------------------------------------------------------------

Initializing Device and compiling on process 0...Done.
Initializing Device 0 on core 0...Done.

Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
Cuda driver error 1 in call at file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/nvd_kernel.h' in line 380.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

OpenCL variant terminates with error `CL_INVALID_OPERATION`:

```
OpenCL error in file '.../lib/gpu/geryon/ocl_kernel.h' in line 370 : -59.
```
https://github.com/lammps/lammps/blob/7e2d40c5faee0a0f20182b76096fe12e28ce02e4/lib/gpu/geryon/ocl_kernel.h#L370

CUDA variant terminates with error (`cudaErrorInvalidValue`)
```
Cuda driver error 1 in call at file 'lib/gpu/geryon/nvd_kernel.h' in line 380.
```
https://github.com/lammps/lammps/blob/7e2d40c5faee0a0f20182b76096fe12e28ce02e4/lib/gpu/geryon/nvd_kernel.h#L380

**Steps to Reproduce**

* Install the latest CUDA 11.3 toolkit and drivers
* Compile with GPU package with either `GPU_API` set to `cuda` or `opencl`
* Try to run examples/melt/in.melt with gpu support

```bash
mkdir build_ocl
cd build_ocl
cmake -C ../cmake/presets/minimal.cmake -D PKG_GPU=on -D GPU_API=opencl ../cmake
make
cd ../examples/melt
../../build_ocl/lmp -in in.melt -sf gpu
```

```bash
mkdir build_cuda
cd build_cuda
cmake -C ../cmake/presets/minimal.cmake -D PKG_GPU=on -D GPU_API=cuda ../cmake
make
cd ../examples/melt
../../build_cuda/lmp -in in.melt -sf gpu
```

**Further Information, Files, and Links**
* Tested on Arch Linux (5.11.12-arch1-1) with CUDA Driver v465.24.02 (NVIDIA Titan V)
* Tested on Ubuntu 18.04 (4.15.0-142-generic) with CUDA Driver v465.19.01 (NVIDIA GTX 2080)
* Tested on Ubuntu 20.04 Singularity container (CUDA 11.2) running on Ubuntu 18.04 host with v465.19.01 (CUDA 11.3) drivers  (GPU with CUDA works, GPU on OpenCL fails)
* Tested on Ubuntu 20.04 container (CUDA 11.3) running on Ubuntu 18.04 host with v465.19.01 (CUDA 11.3) drivers (both GPU with CUDA and OpenCL fail)
* Kokkos with CUDA does not seem to be affected
* Intel(R) OpenCL HD Graphics (OpenCL 3) does not have any issue

**Comment by rbberger** [comment]
@stanmoore1 you have someone from NVIDIA we can contact on this?

**Comment by weinbe2** [comment]
> @stanmoore1 you have someone from NVIDIA we can contact on this?

Yep! I've reproduced it, but I don't have a clue what's causing it yet, so I'll need to dig in further.

One test I did is building and running with the `patch_10Feb2021` branch (which predates the big libgpu update), and that compiled and ran just fine, which means a `git bisect` adventure is in order. Hopefully that'll suggest a short-term workaround while I figure out what truly went awry...

@rbberger , if you have the cycles to do some `git bisect`ing to trace down where the issue got introduced, I'd be grateful, but otherwise I'll put this at the top of tomorrow (Thursday)'s to-do list.

**Comment by weinbe2** [comment]
Update: a first round of `git bisect` showed there was a stretch where the driver error was `Cuda driver error 4 in call at file 'geryon/nvd_timer.h' in line 98.`, which eventually changed to this current error, `Cuda driver error 1 in call at file 'lib/gpu/geryon/nvd_kernel.h' in line 380.`. This changed at `a28d9a6e69d7f44414401412519259eebd04371e`, which was a workaround for GPU neighbor build headaches.

Obviously this commit isn't the actual problem, so another round of `git bisect` is in order where this fix gets put in by hand as appropriate; the `git bisect bad` can start at above commit, and the `git bisect good` can start at `patch_10Feb2021` (for lack of pinpointing this better).

**Comment by rbberger** [comment]
@weinbe2 Looks like the lal_neighbor files have more explicit USE_OLD_NEIGHBOR defines only for CUDA 11.2, which will have to be updated. That would explain why compiling it with CUDA 11.2 worked. Still leaves the OpenCL issue.

**Comment by rbberger** [comment]
@ndtrung81 @wmbrownIntel I'm working on a workaround. Seems like the new NVIDIA driver advertises OpenCL 3.0 support, but fails in unsupported function calls

**Comment by rbberger** [comment]
Turns out to be quite simple. `dev.cl_device_version() >= 210` has to be replaced with `dev.has_subgroup_support()`. The NVIDIA driver does advertise that it doesn't support those functions.
