### ISSUE TITLE
[Feature Request] Remove support for obsolete CUDA hardware and toolkits in GPU package

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2730]
**Summary**

There is a lot of legacy code in the GPU package to support old hardware and old CUDA toolkits.

**Detailed Description**

After a quick look at the CUDA HW/SW compatibility list at: https://en.wikipedia.org/wiki/CUDA#GPUs_supported it seems that the "Fermi" generation hardware (SM 2.x) has been obsoleted by the CUDA toolkit for quite some time (since version 9.0) and the next generation ("Kepler" 3.x) is about to become obsolete (only 3.5 is still supported in CUDA toolkit version 11.3). That translates to me that we would obsolete all "Fermi" and older hardware in LAMMPS and thus logically only support the CUDA toolkit 5.0 and later (this is the first to support "Kepler"). But even that could be pushed some to version 8.0 and later, if there would be a benefit from removing redundant code, since that is also pretty old software.

On the other hand we should keep in mind that the other GPU support facility, Kokkos is moving closer to the limit of available technology, so there is a benefit in not pushing as aggressively with the GPU package.

**Comment by akohlmey** [comment]
BTW: I would assume that similar things are true for OpenCL support, especially now with the improved OpenCL support and automatic "tuning" in the current codebase.

**Comment by rbberger** [comment]
@ndtrung81 @wmbrownIntel @arghdos While we're at it, can we agree on how to clean up the `lib/gpu` codebase? Right now there is a mix of tabs and spaces. For debugging I had to run clang-format over it. But since there isn't an agreed-upon style I don't want to create a PR and break everyone's branches.

**Comment by arghdos** [comment]
@rbberger -- refreshing after a clang format pass works for me, I don't think I've got anything that would be broken by that.

One thing I've run into over in Kokkos land is that the style tends to go through changes between clang versions.  It would probably be worth just saying "use clang-format from clang-8" (this is the version Kokkos uses)

**Comment by akohlmey** [comment]
> @rbberger -- refreshing after a clang format pass works for me, I don't think I've got anything that would be broken by that.
> 
> One thing I've run into over in Kokkos land is that the style tends to go through changes between clang versions. It would probably be worth just saying "use clang-format from clang-8" (this is the version Kokkos uses)

In our experiments with clang-format, the changes in the resulting format are minimal after clang-format 8, if you stick mostly with the defaults. Of course config options only available in later versions are taboo.

**Comment by akohlmey** [comment]
Resolved with PR #3213
