### ISSUE TITLE
[BUG] Compile flag in USER-Intel not protected

### ISSUE THREAD

**Issue by ab5424** [lammps/lammps#2731]
**Summary**

In line https://github.com/lammps/lammps/blob/master/cmake/Modules/Packages/USER-INTEL.cmake#L82 `foreach` loops over every flag but `-fp-model fast=2` should be protected as a single flag.

**LAMMPS Version and Platform**

Latest release, all platforms. cmake 3.19.6

**Expected Behavior**

I'm not quite sure how to protect it, I tried quotation marks and a backslash before the space but that doesn't seem to work.

**Actual Behavior**

The test runs with both flags separately and fails.

In file CMakeError.log:

```
Performing C++ SOURCE FILE Test COMPILER_SUPPORTS-fp-model failed with the following output:
Change Dir: /lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local_rwth/bin/gmake cmTC_80fd8/fast && /usr/local_rwth/bin/gmake  -f CMakeFiles/cmTC_80fd8.dir/build.make CMakeFiles/cmTC_80fd8.dir/build
gmake[1]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_80fd8.dir/src.cxx.o
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc   -restrict    -DCOMPILER_SUPPORTS-fp-model -fp-model -std=c++11 -o CMakeFiles/cmTC_80fd8.dir/src.cxx.o -c /lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp/src.cxx
icpc: command line warning #10159: invalid argument for option '-fp-model'
Warning #2216: '=' assumed following macro name "COMPILER_SUPPORTS" in command-line definition

Linking CXX executable cmTC_80fd8
/rwthfs/rz/cluster/home/ab542498/python/miniconda3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_80fd8.dir/link.txt --verbose=1
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc  -restrict  CMakeFiles/cmTC_80fd8.dir/src.cxx.o -o cmTC_80fd8 
gmake[1]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test COMPILER_SUPPORTSfast=2 failed with the following output:
Change Dir: /lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local_rwth/bin/gmake cmTC_35157/fast && /usr/local_rwth/bin/gmake  -f CMakeFiles/cmTC_35157.dir/build.make CMakeFiles/cmTC_35157.dir/build
gmake[1]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_35157.dir/src.cxx.o
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc -DCOMPILER_SUPPORTSfast=2  -restrict    fast=2 -std=c++11 -o CMakeFiles/cmTC_35157.dir/src.cxx.o -c /lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp/src.cxx
icpc: error #10236: File not found:  'fast=2'
gmake[1]: *** [CMakeFiles/cmTC_35157.dir/src.cxx.o] Error 1
gmake[1]: *** Deleting file `CMakeFiles/cmTC_35157.dir/src.cxx.o'
gmake[1]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_35157/fast] Error 2


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test COMPILER_SUPPORTSfast=2 failed with the following output:
Change Dir: /lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local_rwth/bin/gmake cmTC_a7cf8/fast && gmake[1]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
/usr/local_rwth/bin/gmake  -f CMakeFiles/cmTC_a7cf8.dir/build.make CMakeFiles/cmTC_a7cf8.dir/build
gmake[2]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a7cf8.dir/src.cxx.o
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc -DCOMPILER_SUPPORTSfast=2  -restrict    fast=2 -std=c++11 -o CMakeFiles/cmTC_a7cf8.dir/src.cxx.o -c /lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp/src.cxx
icpc: error #10236: File not found:  'fast=2'
gmake[2]: *** [CMakeFiles/cmTC_a7cf8.dir/src.cxx.o] Error 1
gmake[2]: *** Deleting file `CMakeFiles/cmTC_a7cf8.dir/src.cxx.o'
gmake[2]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTC_a7cf8/fast] Error 2
gmake[1]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_intel_cmake_new/CMakeFiles/CMakeTmp'
```

**Steps to Reproduce**

Compile with cmake & USER-Intel

**Further Information, Files, and Links**

none

**Comment by akohlmey** [comment]
as a workaround you can use `-DCMAKE_TUNE_FLAGS="-fp-model fast=2"`

**Comment by junghans** [comment]
Does https://github.com/lammps/lammps/pull/2732 work?

**Comment by ab5424** [comment]
I don't think so, bc the variable `-DCOMPILER_SUPPORTS` now contains unprotected whitespace:

```
Performing C++ SOURCE FILE Test COMPILER_SUPPORTS-fp-model fast=2 failed with the following output:
Change Dir: /lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local_rwth/bin/gmake cmTC_87456/fast && /usr/local_rwth/bin/gmake -f CMakeFiles/cmTC_87456.dir/build.make CMakeFiles/cmTC_87456.dir/build
gmake[1]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_87456.dir/src.cxx.o
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc    -restrict -DCOMPILER_SUPPORTS-fp-model fast=2   -fp-model fast=2 -std=c++11 -o CMakeFiles/cmTC_87456.dir/src.cxx.o -c /lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp/src.cxx
icpc: error #10236: File not found:  'fast=2'
Warning #2216: '=' assumed following macro name "COMPILER_SUPPORTS" in command-line definition

gmake[1]: *** [CMakeFiles/cmTC_87456.dir/src.cxx.o] Error 1
gmake[1]: *** Deleting file `CMakeFiles/cmTC_87456.dir/src.cxx.o'
gmake[1]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_87456/fast] Error 2


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test COMPILER_SUPPORTS-fp-model fast=2 failed with the following output:
Change Dir: /lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local_rwth/bin/gmake cmTC_a8128/fast && gmake[1]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp'
/usr/local_rwth/bin/gmake -f CMakeFiles/cmTC_a8128.dir/build.make CMakeFiles/cmTC_a8128.dir/build
gmake[2]: Entering directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a8128.dir/src.cxx.o
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc    -restrict -DCOMPILER_SUPPORTS-fp-model fast=2   -fp-model fast=2 -std=c++11 -o CMakeFiles/cmTC_a8128.dir/src.cxx.o -c /lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp/src.cxx
icpc: error #10236: File not found:  'fast=2'
Warning #2216: '=' assumed following macro name "COMPILER_SUPPORTS" in command-line definition

gmake[2]: *** [CMakeFiles/cmTC_a8128.dir/src.cxx.o] Error 1
gmake[2]: *** Deleting file `CMakeFiles/cmTC_a8128.dir/src.cxx.o'
gmake[2]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTC_a8128/fast] Error 2
gmake[1]: Leaving directory `/rwthfs/rz/cluster/lammps-stable_29Oct2020/build_mod/CMakeFiles/CMakeTmp'
```

**Comment by ab5424** [comment]
I also tried `-fp-model\ fast=2` but that doesn't work either

**Comment by junghans** [comment]
Good catch, try #2732 again, I removed the special characters from the define.

**Comment by akohlmey** [comment]
What I don't understand is that this is producing a failure. I just checked again. Yes, the check for the flag fails, but that failure is ignored and does not lead to an abort in CMake. At least not for the systems where I tried it (CentOS 7 and Fedora 32) and with the Intel compilers I used (2018 and 2021).

**Comment by junghans** [comment]
I think it is only in `CMakeError.log`, the error basically makes CMake ignore the flag.

**Comment by ab5424** [comment]
@akohlmey Yes, sorry if I didn't mention that cmake doesn't abort. The check fails and the flag isn't passed to the compiler.

**Comment by ab5424** [comment]
@junghans The latest patch fixes the check, but there is something wrong during the actual build. I get multiple `icpc: command line warning #10159: invalid argument for option '-fp-model'`

**Comment by ab5424** [comment]
The flags are now passed as follows:

```
-- C++ Compiler:     /opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc
      Type:          Intel
      Version:       19.1.3.20200925
      C++ Flags:     -restrict -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;FFT_FFTW3;FFT_FFTW_THREADS;LMP_PYTHON;LMP_USER_OMP;LMP_USER_INTEL;LMP_INTEL_USELRT;LMP_USE_MKL_RNG
      Options:       -xHost;-O2;-fp-model fast=2;-no-prec-div;-qoverride-limits;-qopt-zmm-usage=high;-qno-offload;-fno-alias;-ansi-alias;-restrict
```

**Comment by akohlmey** [comment]
> @akohlmey Yes, sorry if I didn't mention that cmake doesn't abort. The check fails and the flag isn't passed to the compiler.

... and for which there is the simple workaround that I already pointed out. We went though multiple iterations of the "check compiler flags" macro  in CMake and more-or-less concluded that it is not fully functional especially with older CMake versions that we want to support. So we settled for passing only the flags that the *can* be confirmed to work and rely on advising people to use -DCMAKE_TUNE_CFLAGS="..." for any additional flags that are compiler version specific.
The alternative would have been to drop the semi-automatic optimization of  compiler flags for intel compilers completely.

I think it is going to be futile to try and fix this. I have some very strong feeling of deja-vu here.

**Comment by junghans** [comment]
> @junghans The latest patch fixes the check, but there is something wrong during the actual build. I get multiple `icpc: command line warning #10159: invalid argument for option '-fp-model'`

Can you do a verbose build (`make VERBOSE=1`) and post one of the compile lines with the error here?

**Comment by ab5424** [comment]
@junghans This is the output. I removed some trailing include flags:

```
/opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc  [...]  -restrict -O2 -g -DNDEBUG   -xHost -O2 "-fp-model fast=2" -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias -restrict -qopenmp -std=c++11 -o CMakeFiles/lammps.dir/home/ab542498/LAMMPS/lammps-stable_29Oct2020/src/USER-MOFFF/pair_buck6d_coul_gauss_dsf.cpp.o -c /LAMMPS/lammps-stable_29Oct2020/src/USER-MOFFF/pair_buck6d_coul_gauss_dsf.cpp
icpc: command line warning #10159: invalid argument for option '-fp-model'
```

The warning doesn't appear for every file tho.

@akohlmey Just to explain why I opened this issue: there were other warnings in my error log (basically the same as https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads). The discussion on stack mentions that this is likely not an issue of the pthreads library (which I have installed on my system) but something else, and I wanted to "clean up" my error log.

Btw, the workaround `DCMAKE...` helped, but also made one remark appear during the build:
`/lammps-stable_29Oct2020/src/USER-INTEL/pair_airebo_intel.cpp(2335): (col. 5) remark: Loop with pragma of unroll = 4 ignored due to non-canonical loop form from OpenMP specification`
I can't tell if that's important.

**Comment by junghans** [comment]
> @junghans This is the output. I removed some trailing include flags:
> 
> ```
> /opt/intel/Compiler/19.1/3.304/rwthlnk/bin/intel64/icpc  [...]  -restrict -O2 -g -DNDEBUG   -xHost -O2 "-fp-model fast=2" -no-prec-div -qoverride-limits -qopt-zmm-usage=high -qno-offload -fno-alias -ansi-alias -restrict -qopenmp -std=c++11 -o CMakeFiles/lammps.dir/home/ab542498/LAMMPS/lammps-stable_29Oct2020/src/USER-MOFFF/pair_buck6d_coul_gauss_dsf.cpp.o -c /LAMMPS/lammps-stable_29Oct2020/src/USER-MOFFF/pair_buck6d_coul_gauss_dsf.cpp
> icpc: command line warning #10159: invalid argument for option '-fp-model'
> ```
> 
> The warning doesn't appear for every file tho.
> 

Give it another shot.

**Comment by ab5424** [comment]
> Give it another shot.

This didn't work either because it still passes the quotation marks to the compiler. But I found https://cmake.org/cmake/help/v3.1/command/separate_arguments.html, this helped. I'll create a pull request.
