### ISSUE TITLE
[BUG] Tracking GPU package issues

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2747]
**Summary**

The purpose of this issue is to track all outstanding issues with the GPU package on the various configurations it supports.
Since we have now GPU package support in the unit tests, the most comprehensive way to check for consistent behavior is to compile LAMMPS via the CMake route with `-DENABLE_TESTING=on` and then run the tests with `ctest` (using `-DBUILD_SHARED_LIBS=on` and `-DLAMMPS_EXCEPTIONS=on` is recommended as well). Since the tests are comparing to reference results from CPU pair styles, LAMMPS should be compiled without optimization to avoid numerical noise due to compiler optimization.

The following exceptions exist for testing the GPU package:
- hybrid styles use neighbor lists on the CPU (preliminary support for GPU neighbor lists existed pre Feb2021) see #2621 
- tersoff styles do not use the "shift" option (new feature, not implemented on GPU)
- dpd styles use a different pRNG thus cannot be compared
- hybrid styles with using the same pair style twice (GPU has static per-pair style contexts)
- hybrid/scaled (new feature, needs to download forces and energies after each substyle kernel has run)
- kspace pppm with tricilinic cell, ad differentiation, slab correction with nozforce (not implemented on GPU)
- no tests with GPU/CPU balancing
- no tests with CPU neighbor lists for non-hybrid styles

For OpenCL please note that LAMMPS does not use the system provided OpenCL library when compiling with CMake, but uses a statically linked OpenCL-ICD-Loader library 3.0.7 / 2021.04.29 compiled from the reference sources. So warnings from `clinfo` about OpenCL 2.x versus OpenCL 3.0 drivers should not represent a problem.

**Expected Behavior**

All unit tests pass with either double, mixed, or single precision (double is checked most tightly for numerical accuracy). And they should work with `-DLAMMPS_SIZES=smallsmall`, `-DLAMMPS_SIZES=smallbig`, and `-DLAMMPS_SIZES=bigbig`.

**Actual Behavior**

Here is the current status:

- Fedora Linux 34 with Intel GPU (HD 620) using OpenCL (3.0 NEO, driver 21.18.19737), gcc 11.1:
  - [lmp-h.txt](https://github.com/lammps/lammps/files/6412353/lmp-h.txt), [clinfo.txt](https://github.com/lammps/lammps/files/6412354/clinfo.txt), [ocl_get_devices.txt](https://github.com/lammps/lammps/files/6412355/ocl_get_devices.txt)
  - last tested with commit: e6178892c72b19e5c1c147a3e644a6e4c44d64b5
  - :heavy_check_mark: beck passes (:boom: beck failed with previous driver)
  - :boom: born/coul/wolf fails
  - :heavy_check_mark: mie/cut passes (:boom: mie/cut failed with previous driver)
  - :heavy_check_mark: vashishta passes (:boom: vashishta failed with previous driver)
  - :boom: pppm fails (confirmed with running the rhodo benchmark, which runs only with `-pk gpu 0 pair/only yes`.
  - :heavy_check_mark: all other tests pass
- Fedora Linux 32 with Nvidia GPU (GeForce GTX 1060, sm_61) using CUDA (11.2, driver 460.67), gcc 10.2:
  - [lmp-h.txt](https://github.com/lammps/lammps/files/6412375/lmp-h.txt), [nvc_get_devices.txt](https://github.com/lammps/lammps/files/6412376/nvc_get_devices.txt), [nvidia-smi.txt](https://github.com/lammps/lammps/files/6412377/nvidia-smi.txt)
  - last tested with commit: b4a70880d999d9e159d23bbf9f03cf1561cf1d38
  - :heavy_check_mark: all tests pass
- Fedora Linux 32 with Nvidia GPU (GeForce GTX 1060) using OpenCL (1.2, driver 460.67), gcc 10.2:
  - [lmp-h.txt](https://github.com/lammps/lammps/files/6412382/lmp-h.txt), [ocl_get_devices.txt](https://github.com/lammps/lammps/files/6412383/ocl_get_devices.txt), [clinfo.txt](https://github.com/lammps/lammps/files/6412384/clinfo.txt)
  - last tested with commit: b4a70880d999d9e159d23bbf9f03cf1561cf1d38
  - :heavy_check_mark: all tests pass
- Windows 10 Version 20H2 with Intel GPU (HD 620) using OpenCL (2.1, driver 24.20.100.6286), mingw64-gcc 10.2:
  - last tested with commit: b4a70880d999d9e159d23bbf9f03cf1561cf1d38 plus small tweaks to compile with MinGW64 version 8.0 cross compilers on Linux 
  - [lmp-h.txt](https://github.com/lammps/lammps/files/6415146/lmp-h.txt), [ocl_get_devices.txt](https://github.com/lammps/lammps/files/6415147/ocl_get_devices.txt)
  - :question:  no unit tests possible
  - :heavy_check_mark: benchmarks: chain, eam, lj, rhodo pass
- macOS 11.2.2 with AMD GPU (Radeon FirePro D700) using OpenCL(1.2), clang 12.0:
  - last tested with commit: 30068d459932be9b161a75f2458529c6e25d15a6
  - :boom: born/coul/wolf/cs fails in mixed precision but passes in double precision
  - :heavy_check_mark: all other unit tests pass
  - [ocl_get_devices.txt](https://github.com/lammps/lammps/files/6446895/ocl_get_devices.txt) [clinfo.txt](https://github.com/lammps/lammps/files/6417258/clinfo.txt) [lmp-h.txt](https://github.com/lammps/lammps/files/6446894/lmp-h.txt)
- Fedora Linux 33 with Nvidia GPU (GeForce GTX Titan) using OpenCL(3.0, driver 465.24.02), gcc 10.3:
  - last tested with commit: 199e750eb193dc9f14e04609cafdbb3d3c83346c (PR #2748)
  - :heavy_check_mark: all unit tests pass
  - [lmp-h.txt](https://github.com/lammps/lammps/files/6418103/lmp-h.txt), [ocl_get_devices.txt](https://github.com/lammps/lammps/files/6418104/ocl_get_devices.txt), [clinfo.txt](https://github.com/lammps/lammps/files/6418105/clinfo.txt)
- Fedora Linux 33 with Nvidia GPU (GeForce GTX Titan, sm_35) using CUDA (11.3, driver 465.24.02), gcc 10.3:
  - last tested with commit: 199e750eb193dc9f14e04609cafdbb3d3c83346c (PR #2748)
  - :heavy_check_mark: all unit tests pass, also since single precision and CUDPP enabled (disabled is default)
  - [nvc_get_devices.txt](https://github.com/lammps/lammps/files/6418114/nvc_get_devices.txt), [nvidia-smi.txt](https://github.com/lammps/lammps/files/6418115/nvidia-smi.txt), [lmp-h.txt](https://github.com/lammps/lammps/files/6418116/lmp-h.txt)

**Comment by rbberger** [comment]
@akohlmey The failure on macOS 11.2.2 with AMD GPU (Radeon FirePro D700) using OpenCL(1.2), clang 12.0 is caused by the OpenCL static loader, or at least something missing there. If you disable it with `USE_STATIC_OPENCL_LOADER=off` it works again.

**Comment by akohlmey** [comment]
> @akohlmey The failure on macOS 11.2.2 with AMD GPU (Radeon FirePro D700) using OpenCL(1.2), clang 12.0 is caused by the OpenCL static loader, or at least something missing there. If you disable it with `USE_STATIC_OPENCL_LOADER=off` it works again.

It will be rather pointless to try and fix this when I look at news like this: https://shapeof.com/archives/2021/4/apple_april_2021_security_update_and_acorn.html

**Comment by akohlmey** [comment]
GPU package is ready for the stable release. We have either fixes or workarounds in place or disallow combinations of flags/features that are known to not work correctly.
