### ISSUE TITLE
[BUG] Infinite loop with failed insertion from fix deposit

### ISSUE THREAD

**Issue by jtclemm** [lammps/lammps#2755]
**Summary**

When using a bonded molecular template, LAMMPS can hang indefinitely if a deposition fails. This bug can be easily reproduced by increasing the deposition rate in the example script in.deposit.molecule and running on 2 processors.

The bug manifests when a new bond topology list is built. The NTopoBond classes calls the `domain->closest_image()` method. This method searches the `atom->sametag` array. When a deposition fails, this array can sometimes contain a closed loop (e.g. index 235 points to 245 points to 255 points to 235) which LAMMPS cycles through indefinitely.

In fix deposit,  nghost is set to zero before adding atoms and clearing the map. When `atom->map_set()` is later called, it only clears data up to nlocal+nghost, leaving junk in the atom array maps which can create these loops (might not happen for hash maps). This doesn't matter if the deposition is successful since fix deposit explicitly calls `atom->map_init()` which also clears data up to `atom->map_tag_max`.

This bug can be easily fixed by clearing the map in fix deposit before setting nghost to zero. I think adding the line
`if (atom->map_style != Atom::MAP_NONE) atom->map_clear();`
should fix the bug (I can no longer reproduce it). Alternatively, the lines:
`    
   if (atom->map_style != Atom::MAP_NONE) { 
      atom->map_init();  
      atom->map_set();  
    }
`
could be moved out of the `if (success)` block so the map is always reinitialized.

As an aside, would it be appropriate to add a small error check to the `domain->closest_image()` method to avoid loops in the `atom->sametag` array? One could record the initial atom index and error if the index is seen again. Ideally LAMMPS should never create these loops to begin with, but it might help debugging potential errors in the future?

If either of these solutions sound good, I'm happy to submit a PR with the changes (unless it's easier to add it to one of the collected small fixes PRs). 

Thanks!

**LAMMPS Version and Platform**

Current LAMMPS master

**Expected Behavior**

LAMMPS should not hang after failed depositions with bonds.

**Actual Behavior**

LAMMPS can hang after failed depositions with bonds.

**Steps to Reproduce**

Change line 37 in the molecule deposit example to:
`fix		4 addatoms deposit 100 0 1 12345 region slab near 1.0 &`
and run on 2 processors, it should hang somewhere after 600 timesteps.

**Further Information, Files, and Links**

NA

**Comment by jtclemm** [comment]
Just realized the exact same bug also appears in fix pour and maybe in fix bond/react (if an insertion fails, it doesn't call map->init() despite setting nghost = 0).

**Comment by jrgissing** [comment]
fix bond/react might be avoiding this error by forcing a reneighboring even on failed insertions, but I will try to trigger this error. thanks for the report

**Comment by akohlmey** [comment]
I can easily add the necessary changes to a "collection" branch that I have open, but this is a topic where I would prefer wait until we have heard the wise words from @sjplimp  first.

**Comment by sjplimp** [comment]
@jtclemm Good find and thanks for the careful explanation.  @akohlmey I think both changes Joel suggested are necessary.  Clear the map before the nghost = 0 line in pre_exchange().  And move the map_init and map_set below the success if test at the end.  And add a if (success) test on map_init.  Basically, whether fail or succeed on the deposit, the map is always cleared and then set. Only map_init if succeed.  And you can remove the // old code comments at the end of the while attempt loop. Something similar in fix pour. I can do the PR if you want, or you can add it to one of yours and I can check it.

**Comment by akohlmey** [comment]
Changes are included and the corrected behavior confirmed.

**Comment by jtclemm** [comment]
Great, thank you. Just tested the latest commit in that pull requested and confirmed it fixed the bug. LAMMPS no longer hangs.
