### ISSUE TITLE
[BUG] fix charge/regulation uses variable length arrays

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2757]
**Summary**

Variable length arrays (= arrays declared with a dimension that is a variable which is not a compile time constant) are not valid C++ code (they are allowed and commonly used in old-style Fortran and allowed in C99) even though many C++ compilers accept them unless strict C++ standard compliance is requested.

**LAMMPS Version and Platform**

Current master, commit 54884c978af868bc0c31474898a0ee39552b1066

**Expected Behavior**

LAMMPS complies to the C++11 standard.

**Steps to Reproduce**

Compile LAMMPS with the `-Wvla` flag added produces:

```
lammps/src/MC/fix_charge_regulation.cpp: In member function ‘void LAMMPS_NS::FixChargeRegulation::forward_ions_multival()’:
lammps/src/MC/fix_charge_regulation.cpp:727:7: warning: variable length array ‘mm’ is used [-Wvla]
  727 |   int mm[salt_charge_ratio + 1];// particle ID array for all ions to be inserted
      |       ^~
lammps/src/MC/fix_charge_regulation.cpp: In member function ‘void LAMMPS_NS::FixChargeRegulation::backward_ions_multival()’:
lammps/src/MC/fix_charge_regulation.cpp:781:7: warning: variable length array ‘mm’ is used [-Wvla]
  781 |   int mm[salt_charge_ratio + 1];  // particle ID array for all deleted ions
      |       ^~
lammps/src/MC/fix_charge_regulation.cpp:782:10: warning: variable length array ‘qq’ is used [-Wvla]
  782 |   double qq[salt_charge_ratio + 1];  // charge array for all deleted ions
      |          ^~
lammps/src/MC/fix_charge_regulation.cpp:783:7: warning: variable length array ‘mask_tmp’ is used [-Wvla]
  783 |   int mask_tmp[salt_charge_ratio + 1];  // temporary mask array
      |       ^~~~~~~~
```

**Comment by akohlmey** [comment]
@tc387 please suggest how we should address this?
We can use explicit allocation with new/delete or std::auto_ptr, or those arrays could be made class members and then grown, if needed.

**Comment by tc387** [comment]
@akohlmey, thank you for fixing this. These are temporary arrays that store values that are reused if the Monte Carlo move is rejected. The arrays are expected to be very short (2 or 3 elements) when simulating realistic systems. The length of these arrays is constant once the fix has been initialized. We could easily make them class members if you think there would be any benefit to that compared to the current on-the-fly allocation.

**Comment by tc387** [comment]
> > We could easily make them class members if you think there would be any benefit to that compared to the current on-the-fly allocation.
> 
> Up to you. I just did the change that requires the fewest code changes.

Let's keep it as it is then. 
"if it ain't broke don't fix it"
