### ISSUE TITLE
KOKKOS minimize with fix box/relax on GPU device is not deterministic

### ISSUE THREAD

**Issue by nishiyamat** [lammps/lammps#2764]
**Summary**

When using `KOKKOS minimize` with `fix box/relax` on a GPU Device for a slightly disordered structure, I got various results even when I repeatedly started from the same structure, in contrast to running on `serial` that reproduces the same result for the structure.

**LAMMPS Version and Platform**

commit 54884c978af868bc0c31474898a0ee39552b1066 (HEAD -> master, origin/master, origin/HEAD)
Date:   Wed May 5 23:54:55 2021 -0400
This test was run in the Docker container based on `nvidia/cuda:11.2.1-devel-ubuntu20.04`
Device 0: "Tesla P100-PCIE-16GB"
CUDA Driver Version / Runtime Version: 11.2 / 11.2

**Expected Behavior**

 The initial structure was an fcc crystal of 500 atoms slightly displaced with a fixed random seed `87287`. Here is an example with random displacements of `0.1 box`.
<img src="https://user-images.githubusercontent.com/49854960/118085799-f563fa80-b3fd-11eb-9957-29f256a4d22b.png" width="192">
The particles interact through the standard 12/6 Lennard-Jones potential with a cutoff of `2.5`.

First, I have repeatedly run the same input script 100 times using `serial` minimize with `fix box/relax`. As I expected, I found that each `serial` execution converged to the same point with `Stopping criterion = force tolerance`.

**Actual Behavior**

Then I have repeatedly run the same input script 100 times using `Kokkos` minimize with `fix box/relax` on GPU. I found that `Stopping criterion = linesearch alpha is zero` and various results obtained when initial displacement was `0.1 box`, even though the initial structure was the same for each run.

The results are summarized below. The headings in each column correspond to the maximum displacement of each atom which is defined in the input script. The two plots on the left side of each column are the total energy and volume of `serial` execution, and the plots on the right side are the results of `Kokkos` with GPU device. The trajectories are indicated by gray lines, and the convergence points are indicated by symbols. The graph inset is an enlargement around the convergence points. In the left column (d=0), i.e. without any displacement, both `serial` and `Kokkos` with GPU device converged well. On the other hand, in the right column (d=0.1), `serial` converged but `Kokkos` using GPU device went into various states.
d=0|d=0.1
:---:|:---:
![image](https://user-images.githubusercontent.com/49854960/118085209-f7798980-b3fc-11eb-876b-11fd0b834511.png)|![image](https://user-images.githubusercontent.com/49854960/118085326-2f80cc80-b3fd-11eb-972c-4b107980bb8b.png)

**Steps to Reproduce**

[Archive.zip](https://github.com/lammps/lammps/files/6471618/Archive.zip) contains
- Dockerfile
- in.min.lj

Running container from LAMMPS root path for example:
```Bash
docker build --no-cache -t lammps-gpu-debug -f docker/Dockerfile .
docker run --gpus all -it -v $(pwd):/workspace --name lammps-gpu-debug -t lammps-gpu-debug
```
then build LAMMPS in the container with CMake([Build_cmake](https://lammps.sandia.gov/doc/Build_cmake.html), [Build_extras](https://lammps.sandia.gov/doc/Build_extras.html)):
```bash
cd /workspace; mkdir build; cd build
cmake -C ../cmake/presets/minimal.cmake -C ../cmake/presets/kokkos-cuda.cmake ../cmake -D Kokkos_ARCH_MAXWELL50=no -D Kokkos_ARCH_PASCAL60=yes
cmake --build . --parallel 12
```
For `serial` execution:
```bash
lmp -in in.min.lj
```
or for `Kokkos` execution with GPU:
```
lmp -in in.min.lj -k on g 1 -sf kk
```
Executing several times with `Kokkos`, the final step will stop at various states.

**Further Information, Files, and Links**

When the displacement in the initial structure is small, e.g. d ≤ 0.01 box, the variation of convergence becomes relatively small. The force may not converge though, but the total energy or volume can converge. Thus it suggests that starting from the less disordered structure be important when using `KOKKOS minimize` with `fix box/relax` on GPU. Hence I'm using a practical workaround for it; `minimize without fix box/relax` before `minimize with fix box/relax`.

I'm not sure whether it is the expected behavior of GPU or a bug. I think some digits might be lost accidentally in the asynchronous sum of the inner product using `parallel_reduce` in the linesearch.

If it is well-known, please feel free to close this issue.

**Comment by akohlmey** [comment]
When you run on a GPU and the code uses atomic operations, then the order of how numbers are summed up will change. Since floating-point math is not associative, and you lose relative precision when you sum up numbers of different magnitude, this can change the result by some small margin. Thus if you have a minimization on a system with a rough potential hypersurface it is quite possible to have diverging results in successive runs, since the order of atomic adds will change.

**Comment by akohlmey** [comment]
No reaction within a week

**Comment by stanmoore1** [comment]
I'll take a look eventually ;)

**Comment by nishiyamat** [comment]
Thank you for your answer and I'm sorry for not responding. I understand that the result will diverge if there is no associative property and the order of addition is indefinite. I'm convinced by your explanation, and it should not be a bug.

I unexpectedly found a similar case about NVE sampling. Probably due to the same cause as this issue, so I would like to leave a comment here. Modifying [bench/in.lj](https://github.com/lammps/lammps/blob/master/bench/in.lj) to run 3000 times,  trajectories of temperature started to diverge from around 1,500 steps when I use `Kokkos` with GPU (lower), although `serial` reproduced the identical trajectory (upper). 2 calculations are plotted for each figure. Of course,  these results will be correct as long as the trajectories sample the same phase space.
![image](https://user-images.githubusercontent.com/49854960/118954693-fa462280-b998-11eb-95ff-062a54a9cf86.png)
Thank you again for your help with this matter.

**Comment by akohlmey** [comment]
@nishiyamat yes, this has the same cause. Since MD is chaotic the tiniest change in force will eventually grow exponentially and thus lead to diverging trajectories. When compiling with compiler optimization (which is what you do when you want good performance) any change like a different compiler, a different vectorization or CPU architecture setting, a different optimization level or a different CPU/GPU hardware, or running in parallel with a different number of MPI ranks will all result in forces being summed in a different order or with different instructions which will lead to the tiny differences for the "butterfly effect" to manifest itself. How quickly depends on multiple factors. In thermodynamic output, it usually takes more than 1000 steps until divergence becomes visible.
