### ISSUE TITLE
Compile KOKKOS ERROR (setting src/KOKKOS/kokkos_type.h  #define PRECISION 1

### ISSUE THREAD

**Issue by zhangzhen507** [lammps/lammps#2767]
I use lammps-stable_29Oct2020 and compile KOKKOS has ERRORS:

I modify the src/KOKKOS/kokkos_type.h 
#define PRECISION 1
`// define precision
// handle global precision, force, energy, positions, kspace separately

#ifndef PRECISION
#define PRECISION 1
#endif
#if PRECISION==1
typedef float LMP_FLOAT;
#else
typedef double LMP_FLOAT;
#endif

#ifndef PREC_FORCE
#define PREC_FORCE PRECISION
#endif

#if PREC_FORCE==1
typedef float F_FLOAT;
#else
typedef double F_FLOAT;
#endif`

`/home/sr6/lun.yao/lammps/lammps_install/lammps-stable_29Oct2020/src/KOKKOS/pair_zbl_kokkos.h(43): error: return type is not identical to nor covariant with return type "double" of overridden virtual function "LAMMPS_NS::Pair::init_one"
          detected during:
            instantiation of class "LAMMPS_NS::PairZBLKokkos<DeviceType> [with DeviceType=LMPDeviceType]" 
/home/sr6/lun.yao/lammps/lammps_install/lammps-stable_29Oct2020/src/force.cpp(291): here
            instantiation of "LAMMPS_NS::Pair *LAMMPS_NS::Force::pair_creator<T>(LAMMPS_NS::LAMMPS *) [with T=LAMMPS_NS::PairZBLKokkos<LMPDeviceType>]" 
(16): here
`

The comiling command:
1. cmake -C ../cmake/presets/minimal.cmake -C ../cmake/presets/kokkos-cuda.cmake -DKokkos_ARCH_VOLTA70=yes -DKokkos_ENABLE_CUDA=yes -DKokkos_ENABLE_OPENMP=yes -DBUILD_OMP=yes -DCMAKE_CXX_COMPILER=/home/sr6/lun.yao/lammps/lammps_install/lammps-stable_29Oct2020/lib/kokkos/bin/nvcc_wrapper -DPKG_MANYBODY=yes -DPKG_USER-REAXC=yes -DBUILD_SHARED_LIBS=yes -DCMAKE_INSTALL_PREFIX=/home/sr6/lun.yao/lammps/lammps_install/lmp_kokkos_force_float ../cmake
2. make -j20

**Comment by akohlmey** [comment]
If you modify LAMMPS and it doesn't compile afterwards, the modification was incorrect.
Does it say anywhere in the LAMMPS manual that the KOKKOS package supports any other precision setting that double precision?

**Comment by zhangzhen507** [comment]
No there is not say in the LAMMPS manual that it supports any other precision setting. 
I just checked the src/KOKKOS/kokkos_type.h and found out there is a micro definition 

#ifndef PRECISION
#define PRECISION 1
#endif
#if PRECISION==1
typedef float LMP_FLOAT;
#else
typedef double LMP_FLOAT;
#endif

#ifndef PREC_FORCE
#define PREC_FORCE PRECISION
#endif

#if PREC_FORCE==1
typedef float F_FLOAT;
#else
typedef double F_FLOAT;
#endif

So , I just want to try to set PRECISION to 1 to make KOKKOS use float instead of double.
I assume the PRECISION can be set to 1. But not sure it can work or not.
Would you please tell us could KOKKOS support float type ?
And does someone is doing (was doing) mixed precision on KOKKOS ?

**Comment by akohlmey** [comment]
You are assuming wrong. Support for single precision in the KOKKOS package is **not** included in any released version of LAMMPS.  If it was included, there would be information about it in the manual. No feature in LAMMPS is included without it being documented.

There has been work on implementing single precision support (see PR #2125) but that PR got too far out of sync with upstream and thus has to be redone/updated.

@stanmoore1 may be able to provide additional information.

**Comment by akohlmey** [comment]
At the moment the only option to get single or mixed precision support with GPUs in LAMMPS is the GPU package.

**Comment by stanmoore1** [comment]
Kokkos precision is still a work in progress, only double precision is currently supported, see https://lammps.sandia.gov/doc/Speed_kokkos.html#restrictions.
