### ISSUE TITLE
Typographical error in atom_modify command documentation

### ISSUE THREAD

**Issue by PabloBrianese** [lammps/lammps#2779]
**Summary**
[Documentation](https://github.com/lammps/lammps/blob/master/doc/src/atom_modify.rst) reads "atom-style ... map" but looks as though it should be "array-style ... map".
Line 83 of text file.

**LAMMPS Version and Platform**

Branches [master](https://github.com/lammps/lammps/blob/master/doc/src/atom_modify.rst), [stable](https://github.com/lammps/lammps/blob/stable/doc/src/atom_modify.rst), and [unstable](https://github.com/lammps/lammps/blob/unstable/doc/src/atom_modify.rst) on GitHub show the same block of text.

**Details**

LAMMPS offers keywords to store global atom IDs either on an array or on a hash table.
Consistently, these are called "array-style map" and "hash-style map" in the documentation.
But the text also mentions "atom-style maps" where it seems to mean "array-style map".
In addition to this expression "atom-style" being a lot more vague than the precise "array-style" and "hash-style", grepping for "atom-style map" through the repository returns no matches.
For example, running `find lammps -exec grep -r atom-style {} + | grep map` in a terminal, where `lammps` is the directory where LAMMPS was cloned to, returns nothing.
This indicates to me that "atom-style maps" do not exist and that this is a copy-paste error.

The precise text im refering to is

>   When the *map* keyword is not specified in your input script, LAMMPS
>   only creates a map for :doc:`atom_styles <atom_style>` for molecular
>   systems which have permanent bonds (angles, etc).  No map is created
>   for atomic systems, since it is normally not needed.  However some
>   LAMMPS commands require a map, even for atomic systems, and will
>   generate an error if one does not exist.  The *map* keyword thus
>   allows you to force the creation of a map.  The *yes* value will
>   create either an *array* or *hash* style map, as explained in the next
>   paragraph.  The *array* and *hash* values create an atom-style or
>   hash-style map respectively.

Adding line numbers and a reference (in bold text) to the line that seems problematic, this reads

>   75  When the *map* keyword is not specified in your input script, LAMMPS
>   76  only creates a map for :doc:`atom_styles <atom_style>` for molecular
>   77  systems which have permanent bonds (angles, etc).  No map is created
>   78  for atomic systems, since it is normally not needed.  However some
>   79  LAMMPS commands require a map, even for atomic systems, and will
>   80  generate an error if one does not exist.  The *map* keyword thus
>   81  allows you to force the creation of a map.  The *yes* value will
>   82  create either an *array* or *hash* style map, as explained in the next
>   83  paragraph.  The *array* and *hash* values create an atom-style or    **<-- line that confuses me**
>   84  hash-style map respectively.

I could very well be wrong, and I will be very sorry if that is the case. I am trying to help.

**Comment by stanmoore1** [comment]
Yes I agree.

**Comment by akohlmey** [comment]
will be fixed in PR #2778
