### ISSUE TITLE
Kokkos/CUDA errors out when mixing Kokkos and non-Kokkos angle, bond, kspace, etc. styles 

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#279]
Using a non-Kokkos kspace or molecular topology style with a Kokkos pair style gives the error:

<pre>
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Experimental::Impl::SharedAllocationRecord< Kokkos::CudaHostPinnedSpace , void >::get_record ERROR
Traceback functionality not available

**Comment by stanmoore1** [comment]
I have fixed this locally and the changes will be in master soon.

<pre>
Index: atom_vec_kokkos.h
===================================================================
--- atom_vec_kokkos.h   (revision 15872)
+++ atom_vec_kokkos.h   (working copy)
@@ -83,8 +83,13 @@
                    std::is_same<typename ViewType::execution_space,LMPDeviceType>::value,
                    Kokkos::CudaHostPinnedSpace,typename ViewType::memory_space>::type,
                  Kokkos::MemoryTraits<Kokkos::Unmanaged> > mirror_type;
-    if(buffer_size < src.capacity())
+    if (buffer_size == 0) {
+       buffer = Kokkos::kokkos_malloc<Kokkos::CudaHostPinnedSpace>(src.capacity());
+       buffer_size = src.capacity();
+    } else if (buffer_size < src.capacity()) {
        buffer = Kokkos::kokkos_realloc<Kokkos::CudaHostPinnedSpace>(buffer,src.capacity());
+       buffer_size = src.capacity();
+    }
     return mirror_type( buffer ,
                              src.dimension_0() ,
                              src.dimension_1() ,
@@ -104,8 +109,13 @@
                    std::is_same<typename ViewType::execution_space,LMPDeviceType>::value,
                    Kokkos::CudaHostPinnedSpace,typename ViewType::memory_space>::type,
                  Kokkos::MemoryTraits<Kokkos::Unmanaged> > mirror_type;
-    if(buffer_size < src.capacity())
+    if (buffer_size == 0) {
+       buffer = Kokkos::kokkos_malloc<Kokkos::CudaHostPinnedSpace>(src.capacity()*sizeof(typename ViewType::value_type));
+       buffer_size = src.capacity();
+    } else if (buffer_size < src.capacity()) {
        buffer = Kokkos::kokkos_realloc<Kokkos::CudaHostPinnedSpace>(buffer,src.capacity()*sizeof(typename ViewType::value_type));
+       buffer_size = src.capacity();
+    }
     mirror_type tmp_view( (typename ViewType::value_type*)buffer ,
                              src.dimension_0() ,
                              src.dimension_1() ,
</pre>

**Comment by akohlmey** [comment]
fixed in commit 8756a1017dc8eb46f8917c68b7cac620611d8df4
