### ISSUE TITLE
Documentation error for Kolmogorov-Crespi (KC) potential

### ISSUE THREAD

**Issue by GHBrown** [lammps/lammps#2791]
**Summary**

I believe the documentation for the Kolmogorov-Crespi potential is incorrect on the LAMMPS documentation [website](https://docs.lammps.org/pair_kolmogorov_crespi_full.html#kolmogorov1).

(I'm not sure of the best place to bring up documentation issues, so feel free to move or remove this issue.)

**LAMMPS Version and Platform**

Not applicable, documentation issue only.

**Details**

Here is the specification of the potential from the paper:

![paper](https://user-images.githubusercontent.com/26174146/120681069-9aec1600-c460-11eb-9aac-7fb9aba2394f.png)

And here is the potential in the documentation (note the difference in parentheses/brackets in V):

![docs](https://user-images.githubusercontent.com/26174146/120681249-cc64e180-c460-11eb-8da1-a00b8aa49d8d.png)

The documentation only describes an existing implementation of the potential, so this issue is unlikely to affect any calculations, but based on my understanding of the potential I believe the first image from the paper gives the correct specification of the potential.

**Comment by akohlmey** [comment]
@GHBrown thanks for reporting. This is the correct place and the correct style for such reports. This indeed seems to be a typo. Not sure whether this happened during conversion from latex to sphinx or was like this from the beginning.
I have included a suitable change to a pending draft pull request, but I also notified the original contributor to comment.

**Comment by oywg11** [comment]
@GHBrown Thanks for reporting this issue. This is indeed a typo. I also don't remember whether this issue exists from the beginning or not. 
@akohlmey Thanks for fixing this issue.
I rechecked that the source codes implemented the correct KC formula.

**Comment by ghbrown** [comment]
I'm afraid the website still appears to have the incorrect formula. I have done my best to clear my browser cache, etc., but the incorrect version remains.

Would somebody mind confirming this?

**Comment by akohlmey** [comment]
> I'm afraid the website still appears to have the incorrect formula. I have done my best to clear my browser cache, etc., but the incorrect version remains.
> 
> Would somebody mind confirming this?

The page you are looking at is no longer the documentation for the development version. That was changed recently when https://lammps.sandia.gov was retired in favor of https://www.lammps.org/ and then https://docs.lammps.org/ was changed to show the manual for the latest patch version, same as the doc pages on the Sandia server. The development version is now at:
https://docs.lammps.org/latest/pair_kolmogorov_crespi_full.html

**Comment by ghbrown** [comment]
I see, thanks!

**Comment by akohlmey** [comment]
> I see, thanks!

Since we released the next patch version yesterday, you should now see the corrected formula also on the regular documentation website.
