### ISSUE TITLE
python passes type instead of dtype to core library

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#2792]
A recent change to function definitions in `python/lammps/core.py` renamed the `type` argument to `dtype`, which makes sense given the conflict with the python function, but unfortunately that change was not carried on to where the argument is then used, e.g.:
https://github.com/lammps/lammps/blob/6f00e98945efe690d1aa59ea446556f970f6cfa7/python/lammps/core.py#L1137

This seems to be the case in a few places in that file, but I don't know where else it might lurk.  It may be a good idea to revisit the commit that changed type->dtype in the definition of functions like `gather_atoms()`

**Comment by akohlmey** [comment]
this should be fixed in PR #2787 
please have a look.

**Comment by bernstei** [comment]
That definitely fixes the specific problem I ran into, yes.
