### ISSUE TITLE
[Feature Request] fluid/lb ---Visualization_for_Lattice_Boltzmann_Method---

### ISSUE THREAD

**Issue by hjiang37** [lammps/lammps#2797]
Summary

Is there an option to output visualization files for the fluid domain calculated by the lb/fluid?

Detailed Description

So far, I can only print the fluid information to the screen by using the "printfluid" option in fix lb/fluid and then use Matlab to read the screen and extract the wanted data. It is doable, but not very efficient considering a large number of grids and timesteps. I'm wondering if there are any existing options I missed that can directly output the fluid domain for visualization such as dump functions. I saw there is a "write_restart" option that can dump *.dat files in every N timesteps.  Can I use these "*.dat" files to visualize the fluid and how?

Thanks,
Hao

**Comment by akohlmey** [comment]
This is a question you better ask the developers of the USER-LB package directly.
