### ISSUE TITLE
[BUG] _Fix_wall: thermo output (energy and force) does not update _

### ISSUE THREAD

**Issue by lingtikong** [lammps/lammps#2799]
**Summary**
The thermo info written from the fix_wall only takes the initial values and does not update during the following run.
It is casued by the  fact that eflag is set to 1 after the first call to either compute_scalar or compute_vector and remains 1, which skips the following update of ewall_all.

Possible solution: in the end of post_force of fix_wall.cpp, add
eflag = 0

It works for me.

**LAMMPS Version and Platform**

lammps-27May2021

**Expected Behavior**
The energy (scalar) and force (vector) should update at every timestep.

**Actual Behavior**
They just takes the initial values and won't update.

**Comment by akohlmey** [comment]
This has been fixed in commit 3a73dd831aed1914b500a1d467d0604b0e497da2 which was part of pull request #2786 which is merged to upstream and thus will be in the next patch release.
