### ISSUE TITLE
[Feature Request] Stillinger criterion in fix gcmc

### ISSUE THREAD

**Issue by evenmn** [lammps/lammps#2800]
**Summary**

The `fix gcmc` command takes an argument `overlap_cutoff`, which is the smallest accepted separation distance between two atoms. Similarly, it would be natural that the command could take the opposite argument, `max_sep` (?), which is the maximum distance between an added atom and all other atoms in the box/region. This is what is known as the Stillinger cluster criterion [1].

**Detailed Description**

I am currently working on evaluating water MD potentials, and to measure properties such as the surface tension. For this, it would be very useful to define a cluster using the Stillinger cluster criterion (SCC) when performing GCMC simulations. SCC is just a way to define which atoms that belong to a cluster by assigning atoms separated by a distance smaller than r_1 to the same cluster.

First, I wrote a code that defined the region that is part of a cluster according to SCC. Then, I realized that the ´fix gcmc´ command does not support dynamic regions. It does not seem like it is possible to achieve this with the current version of LAMMPS, but I could be wrong.

Anyway, it should not be very much work to implement this as an argument to ´fix gcmc´ as it would be just the opposite of the ´overlap_cutoff´ argument. The difference is that the distance to all particles has to be larger than r_1 to set the interaction energy to max, but for ´oveerlap_cutoff´ only one separation distance has to be smaller than r_0 for the interaction energy to be set to max.

**Further Information, Files, and Links**

[1] [Rigorous Basis of the Frenkel‐Band Theory of Association Equilibrium](https://aip.scitation.org/doi/10.1063/1.1776907)

**Comment by akohlmey** [comment]
@evenmn Is this still something you are working on? Please let us know.

**Comment by evenmn** [comment]
I am currently not working on this. It turned out to be more complicated than what I first thought, and I fear that I will need other Monte Carlo samling techniques (like aggregate-volume bias Monte Carlo) to achieve what I want. To implement other samling techniques would require significant changes of the MC package, which I neither have time or knowledge to do at this point. If other people have the need of this feature and would like to implement it, that would be great, but meanwhile I turn my attention to other (less user-friendly) Monte Carlo packages.

**Comment by akohlmey** [comment]
@evenmn thanks for responding. Making LAMMPS more MC-friendly is not a priority, since many MC operations are conflicting with the domain decomposition parallelization that is at the core of the code design. That is part of the reason why fix gcmc has become so complex and convoluted. So in general we will stick to MC operations that need to be called infrequently for its common use cases.
