### ISSUE TITLE
[Feature Request] Way to suppress LAMMPS's output when called through lammps.py in a loop

### ISSUE THREAD

**Issue by antoinerincent** [lammps/lammps#2808]
Hi!

For different tasks I often launch LAMMPS in a loop in Python, using lammps.py, and I've noticed that when launching lammps this way in the main(), LAMMPS doesn't output anything in the console, but when done so in a loop (or rather, when launching lammps a lot of times in a short span of time), the entire thermo output is printed. I'd like to be able to suppress said output because when lammps gets called multiple times per second, it just ends up flooding the console with information.

I've tried using different pythonic ways to suppress the output, notably : 
```
sys.stdout = open(os.devnull, 'w')
lmp = lammps()
...
lmp.close()
sys.stdout = sys.__stdout__
```
```
class HiddenPrints:
  def __enter__(self):
    self._original_stdout = sys.stdout
    sys.stdout = open(os.devnull, 'w')

  def __exit__(self, exc_type, exc_val, exc_tb):
    sys.stdout.close()
    sys.stdout = self._original_stdout

def main():
  with HiddenPrints():
    lmp = lammps()
    ...
    lmp.close()
```

Both of which have been unsuccessful at stopping lammps from flooding the python console, which I'm guessing is due to the fact that lammps.py's default output goes to fetch __stdout__ on its own, bypassing these methods. 

Am I mistaken in my assessment? How would you recommend going about suppressing the output?
Thanks a lot for your time, it's much appreciated!

**Comment by akohlmey** [comment]
Please try:
```
lmp = lammps(cmdargs=['-screen', 'none'])
```
Please see https://docs.lammps.org/Python_create.html, https://docs.lammps.org/Python_module.html#lammps.lammps
and https://docs.lammps.org/Run_options.html for details.

**Comment by antoinerincent** [comment]
That did the trick, thank you so much! I hadn't thought of simply using the run options!
