### ISSUE TITLE
[BUG] Memory leaks in USER-RANN package

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2811]
**Summary**

There are multiple memory leaks reported when running the USER-RANN example or with valgrind's memcheck tool `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes <path/to/>lmp -in in.rann` (please note https://docs.lammps.org/Errors_debug.html#using-valgrind-to-get-a-stack-trace and https://github.com/lammps/lammps/tree/master/tools/valgrind ) or enabling memory checking during unit testing
with `ctest -T memcheck -R ManybodyPairStyle:rann` (please note https://docs.lammps.org/Build_development.html#code-coverage-and-unit-testing).

**LAMMPS Version and Platform**

Pull request branch from PR #2810

```
OS: Linux "Fedora 34 (Thirty Four)" 5.12.11-300.fc34.x86_64 on x86_64

Compiler: GNU C++ 11.1.1 20210531 (Red Hat 11.1.1-3) with OpenMP 4.5
C++ standard: C++11
MPI v3.1: MPICH Version:        3.4.1
MPICH Release date:     Fri Jan 22 14:17:48 CST 2021
MPICH ABI:      13:10:1

Accelerator configuration:

USER-OMP package API: OpenMP
USER-OMP package precision: double

GPU present: no

Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_EXCEPTIONS
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
sizeof(bigint):   64-bit
```

**Expected Behavior**

No memory leak reports except those due to OpenMP or MPI (can be suppressed by using the suppressions in tools/valgrind)

**Actual Behavior**

Memory leak reports in the attached files.

**Steps to Reproduce**

- Compile LAMMPS with CMake using (at least) `-DENABLE_TESTING=on` and `-DPKG_USER-RANN=on` 
- Run `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes </path/to>/lmp -in in.rann` in examples/USER/rann folder. Output: [rann-valgrind.txt](https://github.com/lammps/lammps/files/6696171/rann-valgrind.txt)

- Run `ctest -T memcheck -R  ManybodyPairStyle:rann` in build folder. Output: [MemoryChecker.266.txt](https://github.com/lammps/lammps/files/6696170/MemoryChecker.266.txt)

**Comment by akohlmey** [comment]
@kipbarrett didn't get around to running these tests before we merged your pull request. This is something that needs to be addressed. A good strategy if usually to initialize all pointer variables to `nullptr` and then unconditionally use `delete[]` or `memory->destroy()` on them before allocating and for complex setups to have a `deallocate()` function as a companion to `allocate()`.

The leakage is quite significant and can be a problem for people that use LAMMPS via the library interface (e.g. from python scripts) to do a large number of small runs with different configurations or settings. Please note that the unit test check is more thorough since it does a whole bunch of different write/read_restart and write/read_data and other unusual command sequences that have triggered memory leaks that went unnoticed for long times.

**Comment by kipbarrett** [comment]
You're right. It does look to be pretty significant. I've used the library interface for potential development before, so I do understand how these can add up.

I can't work on it till after next week, but hopefully after that I'll be able to clear this up quickly.

**Comment by akohlmey** [comment]
> I can't work on it till after next week, but hopefully after that I'll be able to clear this up quickly.

Thanks. I am sending you an invite to be listed as an "outside collaborator" with Triage permission.
Accepting that will allow me to assign this issue to you and also add your github account to the CODEOWNERS file, so you will be automatically notified as a reviewer on changes that touch any files in your contributed package.
As we expand testing and static code analysis to identify bugs and programming style issues and also am trying to gradually "modernize" some of the more old-fashioned parts of the LAMMPS code, there is has been some regular "spill" of changes into contributed code packages, so it can be helpful to be aware of what is going on.
