### ISSUE TITLE
[Feature Request] I Would Like To Improve the Performance of the Fourier/Simple Angle Style

### ISSUE THREAD

**Issue by GenieTim** [lammps/lammps#2819]
**Summary**

The [fourier/simple](https://docs.lammps.org/angle_fourier_simple.html) angle style does not have an optimized version. Namely, it is using the cmath cos() and acos() functions which appear to be a bottleneck in my use case. 
I would like to implement the corresponding improvements and propose them, but would request some guidance on the accepted accuracy of approximations before opening a pull request.

**Detailed Description**

I am currently involved in the simulation of polymer networks, namely PDMS. According to a recent paper [1], an angle term of the form of $\kappa * k_B * T * (1 - cos(x))$ should be used with $\kappa = 0.013$. 
This can be modeled in LAMMPS with a fourier/simple angle style with K = $\kappa * T * k_B$ and c = n = 1.
We noticed that adding this angle term leads to a slow-down of ca. 40-50%. 
I identified the bottleneck to be the cmath cosine and arcus cosine as used currently. I also noticed that while the documentation mentions optimized versions with differing accurracy ("Styles with a gpu, intel, kk, omp, or opt suffix are functionally the same as the corresponding style without the suffix. They have been optimized to run faster, depending on your available hardware..."), those do not seem to actually exist for this angle style, except for the OMP version. 
I thereafter implemented a version of the angle style with approximations for [cos](https://stackoverflow.com/questions/18662261/fastest-implementation-of-sine-cosine-and-square-root-in-c-doesnt-need-to-b/28050328#28050328) and [acos](https://stackoverflow.com/questions/3380628/fast-arc-cos-algorithm/26030435#26030435), which reduced the slow-down of adding the angle term to ca. 5-10%.

I would like to contribute to LAMMPS and offer such a performance-improved version, but before I open a corresponding pull-request, I would like to know what "acceptable accuracy policy" you have for the optimized versions, meaning, what floating-point accuracy would you expect from the trigonometric approximations?
Also, two software design questions: I assume this would be a new style (suffix opt), correct? And the trigonometric approximation fuctions, should they live in the namespace of this angle style or in e.g. the MathExtra namespace?

**Further Information, Files, and Links**

Performance observations on [Euler](https://scicomp.ethz.ch/wiki/Euler) on 6 nodes, average of 15 subsequent observations:

Network of 200 chains with 500 beads per chain and 100 cross-linkers with a functionality of 3.89, FENE bonds, LJ-potential and Langevin thermostat with parameters as described in [1]:

Without angle term: 137(3) ktau/day
With angle term: 101(3) ktau/day
With angle term, fast cos: 130(5) ktau/day

Network of 5000 chains with 20 beads per chain and 2500 cross-linkers with a functionality of 3.97, FENE bonds, LJ-potential and Langevin thermostat with parameters as described in [1]:

Without angle term: 128.9(4) ktau/day
With angle term: 93(5) ktau/day
With angle term, fast cos: 118(4) ktau/day

**References**

[1] [Macromolecules 2020, 53, 6, 1901–1916](https://pubs.acs.org/doi/abs/10.1021/acs.macromol.9b02428)

**Comment by akohlmey** [comment]
@GenieTim Instead of modifying the angle style in question, the LAMMPS way to go about this would be to create a derived class AngleFourierSimpleApprox, associate it with the fourier/simple/approx angle style and then override only the compute function. See  the angle_fourier_simple_omp.{cpp,h} files in the USER-OMP package. In fact, you may see some additional performance improvements by adopting the dbl3_t and int4_t data types from USER-OMP to replace the (bad) array of arrays data access with a (better) array of structs data access pattern. Also the templating trick used there (the compute function calls a templated eval() function with different flags) can help speed up calculations by making several if statements become compile time choices and thus improve the performance.

Let us know if you need to know more.

**Comment by GenieTim** [comment]
Closing with #2825, prefering the angle style fourier/simple/omp over fourier/simple/approx.
