### ISSUE TITLE
[BUG] Dump NetCDF Argument Expansion

### ISSUE THREAD

**Issue by ezavod** [lammps/lammps#2840]
**Summary**

The dump command can [accept wildcard expressions (see dump examples)](https://docs.lammps.org/dump.html#examples) in the form of `c_myF[*]` which is expanded to `c_myF[1] c_myF[2] c_myF[3] ...`.
Such expressions result in an error when using NetCDF as style.

**LAMMPS Version and Platform**

Latest master branch (95792ac9283347d9d5ebca875eb2203a4bac43dd).

**Expected Behavior**

Dump wildcard expansions without error.

**Actual Behavior**

`ERROR: Internal error. (src/NETCDF/dump_netcdf.cpp:257)`

**Steps to Reproduce**

Write something similar to this in your input:
```
compute 1 all stress/atom NULL
dump 3 all custom 100 lj_dump.lammpstrj id type x y z c_1[*]
dump 4 all netcdf 100 lj_dump.nc x y z c_1[*]
```

<details>
<summary>Minimal working example</summary>

based on [this example](https://dev.arc.vt.edu/userguide/lammps/)

```
variable x index 1
variable y index 1
variable z index 1
variable   t index 300

variable xx equal 20*$x
variable yy equal 20*$y
variable zz equal 20*$z

units         lj
atom_style    atomic

lattice       fcc 0.8442
region        box block 0 ${xx} 0 ${yy} 0 ${zz}
create_box    1 box
create_atoms  1 box
mass     1 1.0

velocity all create 1.44 87287 loop geom

pair_style    lj/cut 2.5
pair_coeff    1 1 1.0 1.0 2.5

neighbor 0.3 bin
neigh_modify  delay 0 every 20 check no

fix      1 all nve

compute 1 all stress/atom NULL

dump 3 all custom 100 lj_dump.lammpstrj id type x y z c_1[*]
dump 4 all netcdf 100 lj_dump.nc x y z c_1[*]

run      $t
```
</details>

**Further Information, Files, and Links**

As far as I can tell, the arguments are correctly expanded in the `DumpCustom` base class.
Naively replacing the expanded arguments fixes the problem for me:
```patch
diff --git a/src/NETCDF/dump_netcdf.cpp b/src/NETCDF/dump_netcdf.cpp
index e13bea910f..bd07c26896 100644
--- a/src/NETCDF/dump_netcdf.cpp
+++ b/src/NETCDF/dump_netcdf.cpp
@@ -98,14 +98,13 @@ DumpNetCDF::DumpNetCDF(LAMMPS *lmp, int narg, char **arg) :
   }

   n_perat = 0;
-  for (int iarg = 5; iarg < narg; iarg++) {
-    int i = iarg-5;
+  for (int i = 0; i < nfield; i++) {
     int idim = 0;
     int ndims = 1;
     char mangled[1024];
     bool constant = false;

-    strcpy(mangled, arg[iarg]);
+    strcpy(mangled, earg[i]);

     // name mangling
     // in the AMBER specification
```
I'm happy to contribute this as PR if this makes things easier for you.

**Comment by akohlmey** [comment]
@ezavod Thanks for your report and suggestions.
The necessary changes and some additional refactoring and cleanups as well as a port to the netcdf/mpiio dump style are now in PR #2836.

**Comment by ezavod** [comment]
Thanks for the immediate response and resolution of this issue.
