### ISSUE TITLE
Only first digit of index is read in ArgInfo class

### ISSUE THREAD

**Issue by athomps** [lammps/lammps#2858]
**Summary**

Only first digit of index is read in ArgInfo class.  This means that `c_mygrid[383][7]` is parsed as `c_mygrid[3][7]`.

**LAMMPS Version and Platform**

LAMMPS (2 Jul 2021)

**Expected Behavior**

Parse as `c_mygrid[383][7]`

**Actual Behavior**

Parse as `c_mygrid[3][7]`

**Steps to Reproduce**

Create a compute with more than 9 rows and access using thermo custom

**Further Information, Files, and Links**

I think the problem is in this line of arg_info.cpp

`          index1 = std::stoi(arg.substr(has_idx1 + 1, arg.size() - (has_idx2 + 2)));`

**Comment by akohlmey** [comment]
@athomps thanks for the report. This seems to be a cut-n-paste bug. It is puzzling that this was undetected for such a long time and wasn't caught by the unit tests. So I expanded the unit tests and found another bug.

**Comment by akohlmey** [comment]
@athomps a fix for this is in PR #2856

**Comment by athomps** [comment]
Thanks for fixing.  I was having trouble making sense of my output for a new compute I am working on, but I assumed I was just confused.  Then I happened to notice that the check for index > size_cols was not working, which led me to the problem.
