### ISSUE TITLE
fix deposit inserts atoms unexpectedly

### ISSUE THREAD

**Issue by nickjulian** [lammps/lammps#2864]
**Summary**
Atoms are inserted on the first step of _every_ run command, preventing the use of multiple run commands shorter than the specified insertion period.

**LAMMPS Version and Platform**
 tag: patch_28Jul2021 , commit: b59f23068fce267abadc315e53961c6254fee33a, Fedora 32

**Expected Behavior**
Atoms/molecules are expected to be inserted every M steps after the fix deposit command has been specified by 
"fix ID group-ID deposit N type M seed keyword values" regardless of whether the run command has stopped and resumed before reaching M steps.

**Actual Behavior**
Atoms/molecules are inserted after the first step of each run command, independently of the total number of steps run since the deposit fix.

**Steps to Reproduce**
Run the attached example input file, which is a modification of the fix deposit example where I've increased M to 1,000,000 and appended lines to run 1, run 1, run 1 . It's expected that only 1 atom would be inserted, but new atoms appear after the first step of each new run command.

**Further Information, Files, and Links**
[in_deposit_atom_bugNJ20210804.txt](https://github.com/lammps/lammps/files/6935164/in_deposit_atom_bugNJ20210804.txt)

**Comment by akohlmey** [comment]
@nickjulian thanks for the report. This should be fixed by commit 9a60ab0c23063f790b2509dfdef63b860afa16c3

**Comment by nickjulian** [comment]
@akohlmey Excellent, thank you very much!
