### ISSUE TITLE
[BUG] fix adapt not scaling etail for hybrid pair styles

### ISSUE THREAD

**Issue by GarrettTow** [lammps/lammps#2894]
**Summary**

fix adapt does not properly scale tail correction energy when using a hybrid pair style.

**LAMMPS Version and Platform**

LAMMPS version 30Jul2021
Compilers: Intel oneAPI 2021.1.1 and cray-mpich 8.1.5
SUSE Linux Enterprise Server 15 SP2 Release 15.2
CPU: AMD Epyc 7H12

**Expected Behavior**

Fix adapt should scale both the explicit pairwise contributions and the corresponding tail correction, if enabled.

**Actual Behavior**

When using standard pair styles, fix adapt works as expected. When using hybrid pair styles, fix adapt only scales the explicit pairwise contribution and not the associated tail correction. Fix adapt/fep does not have this issue.

**Steps to Reproduce**

Here is a simple input script (a modified version of the LJ benchmark input) to demonstrate the issue:
*************************************************
variable        x index 1
variable        y index 1
variable        z index 1
variable        xx equal 20*$x
variable        yy equal 20*$y
variable        zz equal 20*$z
units           lj
atom_style      atomic
lattice         fcc 0.8442
region          box block 0 ${xx} 0 ${yy} 0 ${zz}
create_box      1 box
create_atoms    1 box
mass            1 1.0
velocity        all create 1.44 87287 loop geom
pair_style      lj/cut 2.5
pair_coeff      1 1 1.0 1.0 2.5
pair_modify     tail yes
neighbor        0.3 bin
neigh_modify    delay 0 every 20 check no
fix             1 all nve
variable        vdwldiff equal "evdwl - etail"
thermo          1
thermo_style    custom evdwl etail v_vdwldiff
variable        lambda equal 0.1
fix             2 all adapt 0 pair lj/cut epsilon 1 1 v_lambda scale yes reset yes
run             0
unfix 2
pair_style      hybrid lj/cut 2.5
pair_coeff      1 1 lj/cut 1.0 1.0 2.5
pair_modify     tail yes
fix             3 all adapt 0 pair lj/cut epsilon 1 1 v_lambda scale yes reset yes
run 0
**************************************************

Comparing the "etail" thermo dump quantity from both run 0 commands shows that the hybrid pair style does not have the 0.1 scale factor applied.

Note that unfixing the fix adapt and reinitializing was done to test if reinitialization was needed after changing pair styles.

**Further Information, Files, and Links**

See this mailing list thread for more information: https://sourceforge.net/p/lammps/mailman/lammps-users/thread/CADTmJ6EUPeHHZ%2BvaNUK4kXME3y%3DFfiSooq4Sm37zFG6F8xCh5Q%40mail.gmail.com/#msg37340065

If replacing this portion of fix_adapt.cpp:

  if (anypair) {
    for (int m = 0; m < nadapt; m++) {
      Adapt *ad = &adapt[m];
      if (ad->which == PAIR) {
        ad->pair->reinit();
      }
    }
  }

With this line from fix_adapt_fep.cpp:

  if (anypair) force->pair->reinit();

then the discrepancy disappears for fix adapt and the tail correction is properly scaled. This may help with tracking the issue.

**Comment by akohlmey** [comment]
@GarrettTow @sjplimp I've looked this over and the solution from fix adapt/fep is the correct approach.
By adapting only the affected pair style, its own settings get updated and also the tail correction, but the global sum is not updated. Since the existing code already adapts **all** pair and **all** bond styles, just calling `force->pair->reinit()` and `force->bond->reinit()` is having the same effect *plus* it also updates the global settings in case of hybrid styles. PR #2913 has the corresponding change
