### ISSUE TITLE
tad example fails with segmentation fault

### ISSUE THREAD

**Issue by nadyawilliams** [lammps/lammps#2918]
**Summary**

Running tad example from the source distribution fails with segmentation fault.

**LAMMPS Version and Platform**

LAMMPS patch_31Aug2021 compiled from source on CentOS 7.9 with gcc/8.4.0
and using  libraries from  openmpi/4.0.3, ffmpeg/4.1.3, hdf5/1.10.5, gsl/2.6, fftw/3.3.8 
compiled on the same server. Package REPLICA is turned on in the packages preset.

**Expected Behavior**

After running cmake/make  (no errors) and creating an lmp executable i expect the examples/* to run
without issues

**Actual Behavior**

Running a command in examples/tad fails with a segmentation fault apparently half way through the run.

**Steps to Reproduce**

The command was run in examples/tad/:
mpirun  -np 3 lmp -partition 3x1 -in in.tad 

Resulting  log files and the output from the command are attached below

**Further Information, Files, and Links**

[segfault-tad.tar.gz](https://github.com/lammps/lammps/files/7095410/segfault-tad.tar.gz)

**Comment by akohlmey** [comment]
Thanks for your report. I have confirmed it and commit c186b2429288e5832bd31b64b4db9368eeac1a5e should correct it.

**Comment by nadyawilliams** [comment]
Thank you for a fast  response. Your patch fixed the issue. Best regards.
