### ISSUE TITLE
Typo in docs on compute cluster/atom

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#292]
In the [docs](http://lammps.sandia.gov/doc/compute_cluster_atom.html), it says
[...]
Thus it can be inefficient to compute/dump this quantity too frequently or to have multiple compute/dump commands, each of a **clsuter**/atom style.
[...]

It makes sense to report these (I should rather create a PR maybe?), but they are of low pri I assume. Should I keep reporting them if I find more?

**Comment by akohlmey** [comment]
Yes, reporting those is helpful. No need to open a PR for them. I usually have a "blanket PR" open to collect such small issues and one-liners (this is #289 currently). This way Steve doesn't get overloaded with trivial PRs.

**Comment by andeplane** [comment]
Awesome, thanks.

**Comment by akohlmey** [comment]
FWIW, If you find multiple such issues and/or do prefer to submit a PR, you could look up the name of this blanket branch in in _my_ repo and submit PRs to that branch there.
