### ISSUE TITLE
Rename main git branches and release status for patch releases

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2920]
**Summary**

The current names of the main git branches were chosen in an ad hoc fashion and not all of them represent well what kind of content is in those branches.

Now that we have converged to a more stable development workflow and release schedule, the branches' names should reflect their status. Thus I propose the following two changes:

master -> develop or development or devel
unstable -> patches or patch or release or releases

This more accurately reflects the current situation. With the current level of testing and the requirement to pass tests before merging to "master" that branch much more reflects what previously the patch releases were (generally stable, occasional small breakage), which the "unstable" branch with the patch releases are close to previous 'stable' releases. The current stable releases push that limit.

With that in mind, we should also reconsider how we flag patch releases on GitHub. At the moment, those are labeled "pre-releases", but they could also be "full releases". The main difference is what is
displayed as the "latest release". Currently it will show the latest stable release, but with the suggested setting, it would show the latest patch release. Putting more emphasis on patch releases will make more people download and use them, which helps to receive feedback faster (and thus new bugs are faster found and fixed. But people are running a higher risk of being exposed to bugs, especially in new features. A final aspect to consider would be the impact on maintainers of binary packages: do we want to encourage them to make all patch releases available or have them stick to the stable releases?

**Backward Compatibility**

Renaming the branches does not change the commit history. And since git traverses the tree of commits backwards from their "heads", it will only change the label attached to the tag or branch.

**Comment by stanmoore1** [comment]
I prefer "develop" over either "development" or "devel".

**Comment by akohlmey** [comment]
> I prefer "develop" over either "development" or "devel".

Noted. Added as third alternative.

**Comment by stanmoore1** [comment]
I think this is a good change, btw, and more in line with what developers coming from other projects would expect.

**Comment by rbberger** [comment]
:+1: for "develop" for master. and I always thought "unstable" to be a bit weird name that would scare away someone. "patch" sounds like a good alternative.

**Comment by rbberger** [comment]
One other suggestion instead of "patch" would be "release".

**Comment by stanmoore1** [comment]
Or "patches" and "releases".

**Comment by stanmoore1** [comment]
Are we keeping the "stable" branch?

**Comment by akohlmey** [comment]
> One other suggestion instead of "patch" would be "release".

Noted. added that as well. That would be most consistent when also the tags are changed from `patch_XXX` to `release_XXX` and we would only distinguish between "releases" and "stable releases". We are not making patch files available anymore since they tend to be too large and contain too many changes between current "patch releases"

**Comment by akohlmey** [comment]
> Are we keeping the "stable" branch?

I am very much for it. That would IMO be the best version to be followed by binary packages and for many people with limited experience in compiling software. It will be 1-2 times a year. The "patch releases" every few weeks are a bit too often. But then again, I am not a packager and don't have that perspective. That is why I added @junghans so he can chime in as well, if he feels like it.

**Comment by junghans** [comment]
Re: binary packages, these are quite a bit of work making them, especially when things change. However, from time to time I already had to package patch releases to stay in sync with the binary kokkos package, so more "stable" releases would be nice.

**Comment by stanmoore1** [comment]
Or should "master" become the new "stable" branch? That is what Kokkos does.

**Comment by akohlmey** [comment]
> so more "stable" releases would be nice.

That is not likely. Same as for the packaging, under the current circumstances preparing a stable release is a considerable amount of work. It also requires some careful planning ahead of time when to which changes. At the moment all intervals are still growing, but at the current rate of changes (patch) release every 3-5 weeks is a reasonable amount of changes, so I plan to work on not letting this interval grow more.

Considering the effort required for a well done stable release (if it is not significantly more reliable than a patch release it is not worth doing. and thus as the patch releases become more reliable, there is more effort for the stable releases to make them even better), having one per year seems more appropriate.  This is all based on the dynamic with which changes happen to LAMMPS and how much effort and time it currently takes to integrate "disruptive" changes without much collateral damage.
That other projects have other timelines, priorities, and dynamics is unfortunate but difficult to change.

What would probably be more adequate is a scheme similar to what they do for the Linux kernel: every version is a "release", but then occasionally a "long-term" version is picked and somebody (else) cherry-picks only the bugfixes into a feature branch for that stable release and releases bugfix-only updates. Unfortunately, we don't have the manpower and sponsoring the Linux kernel developers have :disappointed:

**Comment by akohlmey** [comment]
> Or should "master" become the new "stable" branch? That is what Kokkos does.

My expectation for a "master" branch is that it is the bleeding edge of development where people directly commit their changes. The fact that so many connotations and expectations are attached to that kind of name for a branch is a major motivation for renaming it (plus the unfortunate choice of "unstable", which was somewhat true when we started with git. "no-quite-stable" would have been more appropriate)

**Comment by junghans** [comment]
> That is not likely. 

Then let's stick with packaging of stable then unless there is another reason (e.g. kokkos) to package a patch release.

Currently,  anitya triggers a packaging request for some distros each stable release (see https://release-monitoring.org/project/13516/ by basically looking into https://download.lammps.org/tars/releases/stable/). 

Also we could distribute the packaging a bit, @ellio167 can already package Fedora. In Spack "packaging" is usually just a one-line change [unless all package options get renamed ;-) ] but @RemiLacroix-IDRIS is helping with that. Not many users seem to care about Gentoo and openSUSE, so it is not very high priority.

**Comment by junghans** [comment]
We should also think about what branch should be the default on github as this is what people get when cloning the code.

**Comment by akohlmey** [comment]
> We should also think about what branch should be the default on github as this is what people get when cloning the code.

When somebody clones a git repo it should be safe to assume that development is on their mind. So it should be the same branch as before, just with a different name. :wink:

**Comment by akohlmey** [comment]
> Then let's stick with packaging of stable

I think the most popular binary packages are the ubuntu ones. So I added @mkanski to the discussion. If I remember correctly, he provides "stable" and "nightly" versions. I vaguely recall asking for not making the "nightly" the default some time ago.

**Comment by mkanski** [comment]
I'm afraid you've mistaken me for someone else, @akohlmey I have no experience with building binary packages.

**Comment by akohlmey** [comment]
@mkanski sorry about that.

**Comment by akohlmey** [comment]
Second attempt. Added @gladk to this discussion with the hope to have the ubuntu packaging perspective (unless I picked the wrong user id again).

**Comment by akohlmey** [comment]
Just noticed that the new LAMMPS paper mentions the "master" branch. So we may have to see if we can update it when reviewing the galley proofs or we are stuck with "master". Not a good idea to change this right after such a paper was published.

**Comment by gladk** [comment]
For Debian/Ubuntu stable packages it does not matter what is the name of the branch would be. Daily package builds are disabled some time ago due to the lack of time to fix build failures.

**Comment by athomps** [comment]
@akohlmey We can probably make this change when we get the galley proofs back.  I have added a note to the overleaf project, in `Galley Revisions/Notes.tex`

**Comment by akohlmey** [comment]
Updated proposal:

master -> develop   (unless we cannot change the paper, then it would remain "master")
unstable -> release
stable  (unchanged)

Patch releases are going to be tagged with release_<Date> and stable release continue with stable_<Date>.
When releasing on GitHub also patch releases are going to be flagged as a "full" release (and not a "pre-release"). Also would be calling them a "Release" and a "Stable Release" and drop the "patch" attribute.

An even more radical change would be to not use the date but major/minor version numbers for stable/patch versions, but that seems one step too far.

**Comment by junghans** [comment]
> An even more radical change would be to not use the date but major/minor version numbers for stable/patch versions, but that seems one step too far.

That would be a good idea down the road. It is really not great that our versions are not easily sortable, e.g. on https://download.lammps.org/tars/ `lammps-9Oct2020.tar.gz` is the last and `lammps-10Apr2012.tar.gz` the first tarball in the list. Distro packages and CMake already use the `YYYYMMDD` version format in some form to allow for version comparisons (we provide tarballs versioned that way already as well: https://download.lammps.org/tars/releases/).

The problem with major/minor version numbers is that it implies some sort of backwards compatibly (see https://semver.org/#summary) that (I believe) we currently don't have. Hence I prefer the `YYYYMMDD` as it implies no backward compatibility at all.

**Comment by gladk** [comment]
For Debian/Ubuntu stable packages it does not matter what is the name of the branch would be. Daily package builds are disabled some time ago due to the lack of time to fix build failures.

**Comment by akohlmey** [comment]
After looking at possible changes for the paper, renaming of the branches `master -> develop` and `unstable -> release` can be done and would be consistent with the changes. More significant changes would require more rewriting and it is too late for that, thus the more frequent ("monthly") releases will still be called "patch releases" and tagged with `patch_<date>`.

**Comment by stanmoore1** [comment]
> After looking at possible changes for the paper, renaming of the branches `master -> develop` and `unstable -> release` can be done and would be consistent with the changes. More significant changes would require more rewriting and it is too late for that, thus the more frequent ("monthly") releases will still be called "patch releases" and tagged with `patch_<date>`.

I support this.
