### ISSUE TITLE
Callback functions in LAMMPS library

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#294]
When using LAMMPS as a library, it would be nice to be able to register a callback function which could be called in multiple places during a command. We use this in Atomify to allow synchronization of the LAMMPS state for visualization when desired. 

It could be implemented as an array of std::function objects on the LAMMPS object and each will be called in 
1) the integrators in each run step
2) the minimize in each run step
3) after each command

The callback function will get the LAMMPS object and an ENUM to specify at what place it was called from. 

What are your thoughts on this?

**Comment by akohlmey** [comment]
This can be done with a custom fix without having to change other parts of LAMMPS. Fixes already have multiple entry points into the timestep/minimization progression and which of those are active is determined in Fix::setmask(). Please see fix external for an example to add a callback to LAMMPS via a fix.

**Comment by andeplane** [comment]
Yeah I know that you could implement parts of this as a fix. But I would have to add the fix at the right time (i.e. after create_box etc) which removes parts of what I want to. And are fixes called every command, or just during run commands? I would like to visualize things right after the create_box command. And after read_data command. 

I tried to set box_defined to 1 before adding a fix, then setting it back to 0, but I didn't like that hack.

**Comment by akohlmey** [comment]
For special cases, fixes can be cleared to be defined before a box is created. See:
```
void Modify::add_fix(int narg, char **arg, int trysuffix)
{
  if (narg < 3) error->all(FLERR,"Illegal fix command");

  // cannot define fix before box exists unless style is in exception list
  // don't like this way of checking for exceptions by adding fixes to list,
  //   but can't think of better way
  // too late if instantiate fix, then check flag set in fix constructor,
  //   since some fixes access domain settings in their constructor
  // MUST change NEXCEPT above when add new fix to this list

  const char *exceptions[NEXCEPT] =
    {"GPU","OMP","INTEL","property/atom","cmap","cmap3","rx"};

```
I don't see the need to have a callback between commands. **You** issue these commands, it is up to you to run whatever event handler you want to run in between. The only commands that take a long time and do many steps are `run` and `minimize` (or those that call them like `temper` or `prd`) and for those going via a fix seems an adequate approach.

**Comment by andeplane** [comment]
Ok, adding this fix to the exception would work, I agree.

I don't want to handle the script logic myself (reimplementing much of the parser). Commands such as label, include, jump, if-tests (they might work with lammps_command though, not sure), so I really hoped I could let LAMMPS do all script parsing. 

If a user has an include command and I want to synchronize a potential create_box command in another file, I don't see how I would be able to do this without impementing a lot of the parsing rules myself. Does this make sense?

**Comment by akohlmey** [comment]
i see your predicament. However, this is also something that should be implemented primarily in the library interface code and not in LAMMPS itself. The best location place a hook in the baseline code would probably be the Input::parse() method. More importantly, you have two problems that you need to address: 1) update of the GUI (or other stuff) after each issued command, 2) update of the GUI etc. during timestepping (i.e. during `run` or `minimize`). For the second part, using a fix is the way to go. The first part is something that needs to be discussed with @sjplimp.

**Comment by akohlmey** [comment]
Hmmm... come to think of it. It would probably the simplest approach to add a END_OF_COMMAND flag to the list of possible fix invocations and then call `modify->end_of_command()` from `Input::parse()`

**Comment by andeplane** [comment]
Yeah that could work. On this topic I would like to know the line number and the current file for error reports. Maybe the wrong thread to discuss this though. 

Either to get access to the current command string (so I can search the file(s)), or better, have access to the file stack and line number. Any comments on this?

**Comment by andeplane** [comment]
This includes more than just errors. I have a "current line" indicator which shows where in the script lamps currently is. Also, not all commands should synchronize atomify. Only commands with visible changes maybe.

I've had problems with moltemplate files (potentially thousands of lines of information that should not be synchronized with only 60 fps), so the fix should be able to check what Command type we just performed. Just some loud thoughts that can be more clear.

**Comment by akohlmey** [comment]
A current line indicator is tricky because of the way how continuation lines and include files are handled. I need to think a bit about this. I would very much also have a input filename/line indicator reported with error messages. I had looked into this several years ago and eventually given up. Perhaps there is a different approach that can be made to work.

Handling the update frequency is something that is very easily doable on your side. Simply don't run an update until a certain (wall) time has passed. That kind of logic doesn't need to be on the LAMMPS side.

**Comment by andeplane** [comment]
I'm not 100% satisfied with the wall time test because ideally I would like to enable breakpoints (pause at line X) and other features where you would need to be able to test if the previous command matches certain criteria. It then makes sense to be able to have access to these things. The discussion in _current file and line indicator_ could solve this problem also.

**Comment by akohlmey** [comment]
You can test for something like line number **in addition** to time being passed. At any rate, you are looking at this from the wrong side of the looking glass. Everything you mention, can and **should** be handled outside of the core LAMMPS code. You can cache information, you can check things. All that should be provided from LAMMPS is a hook to have some function called; ideally in a fix as indicated.

**Comment by andeplane** [comment]
Yes of course. Please try to see that I agree with you and I want to touch internals of lammps as little as possible. A fix that does these things and potentially a library call to access call stack and command information solves everything.

**Comment by andeplane** [comment]
I've started testing an implementation where I added two more steps in the fix cycle:
POST_PARSE_COMMAND and POST_EXECUTE_COMMAND, both of which are nice for Atomify. You can take a look here: [https://github.com/ovilab/lammps/tree/post_command](https://github.com/ovilab/lammps/tree/post_command).

**Comment by andeplane** [comment]
I have explored this more. I added the _fix_external_ to list of exceptions of _box_exist_ test, but met a problem with the _replicate_ command because the fix sets atom->nextra_grow > 0 through atom->add_callback. 

Any suggestions? I understand that this is of very low priority :) 

What i probably will do to not break anything is to add another fix _fix_external_callback_only_ or something that doesn't do force changes, hence no communication.

**Comment by akohlmey** [comment]
this issue has been inactive for a long time. what is the status? i see mentioning of 3 additional fix hooks. that is asking a lot for a niche application. isn't there a way to narrow this down to 1?

**Comment by andeplane** [comment]
I haven't worked on this for a while and currently I'm happy with the END_OF_STEP because I'm not providing script error informations. First release of Atomify will be like this. I suggest we close it, and if (when) I do more work on it I'll open a PR.

I agree that we don't need that many hooks, 1 should be enough.
