### ISSUE TITLE
[Feature Request] Apply semi-automated code refactoring with clang-tidy

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#2946]
**Summary**

Now that we require a C++11 standard compiler to compile LAMMPS from some time, we should try to take more advantage of  C++11 language features. In part this has already been done, e.g. with PR #2358 where NULL was replaced by nullptr, but there are some other items where new language features can help improving the code by triggering compilation errors or warnings when applied. As the experience with PR #2358 has show, this refactoring can be tedious work, but the LLVM project has [a tool called clang-tidy](https://clang.llvm.org/extra/clang-tidy/) which can not only provide static code analysis but also in some cases [can refactor the code automatically](https://www.kdab.com/clang-tidy-part-1-modernize-source-code-using-c11c14/).
Thus the suggestion is to apply **some** of these modernizations in order to detect possible bugs and make it harder to introduce bugs in new code. Once we have settled on a set of items we can also add a check that will scan all pull requests to identify possible mismatches.

One of the most obvious modernization worth using is to add the `override` keyword for virtual methods. This can avoid issues that already happened multiple times in LAMMPS where arguments were added to a function in a base class, but with default values (to ensure backward compatibility). That would change the function signature and overridden versions in derived classes would suddenly become overloads with a different signature and thus no longer be called as intended and therefore causing unexpected and sometimes difficult to debug behavior.

**List of possible modernizations**

The the clang-tidy homepage has a [list of available checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html) and indications whether it can update the code accordingly. The purpose of this feature request is to compile a list of changes that are meaningful and improve the code without changing it too much. Below is a list of links to currently available modernization features (features that don't apply to LAMMPS are not listed). The list is approximately ordered by significance. Some checks do not trigger any existing code, but could be used for checking new contributions.

* **Use always**
  - [x] [Use `override` keyword]()
  - [x] [Remove redundant void arguments](https://clang.llvm.org/extra/clang-tidy/checks/modernize-redundant-void-arg.html)
  - [x] [Use nullptr instead of NULL](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html)
  - [x] [Replace obsolete std::auto_ptr with std::unique_ptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-auto-ptr.html)
  - [x] [Replace obsolecent std::random_shuffle](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-random-shuffle.html)
  - [x] [Remove/replace deprecated C headers](https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-headers.html)
  - [x] [Label default constructors with `= default`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-default.html)
  - [x] [Label disabled constructors with `= delete`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-delete.html)
* **Use on a case by case basis**
  - [x] [Modernize loops](https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html)
  - [x] [Replace 1 and 0 used to initialize `bool` variables with `true` and `false`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-bool-literals.html)
  - [x] [Use pass by value in constructors where beneficial](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html)
  - [x] [Return braced a initializer instead of a typed one](https://clang.llvm.org/extra/clang-tidy/checks/modernize-return-braced-init-list.html)
  - [ ] [Make more use of the `auto` data type](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html)
  - [x] [Use emplace with containers](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html)
  - [x] [Use noexcept](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-noexcept.html)

**Procedure**

The changes would have to be introduced one change per commit and with running compilation, regression and unit testing after every iteration followed by any required tweaks or bugfixes as additional commit(s). That way it should be possible to identify which specific modernization has been causing any issues later and then selectively revert it, if needed.

**Further changes**

While not available as an automatic transformation, we should also take advantage of the `delete` keyword to explicitly disallow the use of unwanted constructors in base classes. For example, most classes in LAMMPS cannot be correctly instantiated using the default constructor. Adding `delete` will make any such use a compile time error and also explicitly indicate to the reader of the source that this is not meant to be used.

**Comment by athomps** [comment]
The `override` keyword is a good thing.

**Comment by akohlmey** [comment]
A few examples where `auto` can be useful (and are suggested by clang-tidy).
```
Irregular *irregular = new Irregular(lmp);
AngleHybrid *hybrid = (AngleHybrid *)force->angle;
double **x = atom->x;
double **f = atom->f;
int *type = atom->type;
int nlocal = atom->nlocal;
double *special_lj = force->special_lj;
int newton_pair = force->newton_pair;
```
Would become
```
auto irregular = new Irregular(lmp);
auto hybrid = (AngleHybrid *)force->angle;
auto x = atom->x;
auto f = atom->f;
auto type = atom->type;
auto nlocal = atom->nlocal;
```
This reduces repetitive typing and the risk of typos but also code that may fail when using LAMMPS_BIGBIG when `sizeof(bigint) != sizeof(int)` and thus assigning a bigint pointer to an int pointer suddenly becomes an error.
