### ISSUE TITLE
[BUG] fix_brownian.cpp: g2 calculation is not correct.

### ISSUE THREAD

**Issue by MARS-CODE** [lammps/lammps#2948]
**Summary**

In the latest version of lammps, when I run lammp brownian simulation. I notice there a problem with gamma_t in "fix brownian". When I debug the code, I found g2 calculation is incorrect. It should be g2 /= sqrt(gamma_t) to consistent with the brownian motion defined in "https://docs.lammps.org/fix_brownian.html";

**Comment by akohlmey** [comment]
@MARS-CODE Thanks for your report. I have assigned this to @samueljmcameron who contributed this code to LAMMPS and is probably the person most competent to confirm or reject your assessment and to suggest what - if anything - should be changed in the distribution.

**Comment by MARS-CODE** [comment]
@akohlmey @samueljmcameron  Thank you, Axel. I think the bug is quite obvious.

**Comment by MARS-CODE** [comment]
@samueljmcameron Could you kindly let me know your idea about this bug?

**Comment by akohlmey** [comment]
PR #2991 was merged today
