### ISSUE TITLE
Link to Offsite Package page broken in documentation

### ISSUE THREAD

**Issue by p-bro** [lammps/lammps#2950]
The link to the offsite package repository https://www.lammps.org/offsite.html is broken. The incorrect link is referred to in multiple places in the documentation. I was able to identify the broken link in the following files:

doc/src/Tools.rst line 10
doc/src/Modify_contribute.rst line 119

The correct link should probably be "https://www.lammps.org/external.html".

**Comment by akohlmey** [comment]
@p-bro thanks for the report. You are correct those links should be changed and there is one more that is pointing to the wrong location. This will be included in pull request ASAP.
