### ISSUE TITLE
[BUG] mismatch in path for pace style

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#2954]
**Summary**

directions (for Makefile style) compilation of pace pair_style lead to the actual code in `lib/pace/src/USER-PACE`, but the compilation lines look for it in `lib/pace/src/ML-PACE`. 

**LAMMPS Version and Platform**

git master branch 8d8c710982, Linux

**Expected Behavior**

successfully compile lammps

**Actual Behavior**

`make mode=shlib mymachine` ends with the following output:
```
g++ -g -O0  -fPIC -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_EXCEPTIONS  -I../STUBS    -I../../lib/pace/src/ML-PACE  -c ../pair_lj_mdf.cpp
../pair_pace.cpp:46:10: fatal error: ace_evaluator.h: No such file or directory
 #include "ace_evaluator.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Checking the content of the `lib/pace` subdirectory shows
```
> ls -l ../lib/pace/src/
total 44
-rw------- 1 bernstei bernstei 35149 Apr  9 07:08 LICENSE
-rw------- 1 bernstei bernstei  1342 Apr  9 07:08 README.md
drwx------ 2 bernstei bernstei  4096 Apr  9 07:08 USER-PACE/
```
**Steps to Reproduce**

```
cd lammps
git checkout master
git pull
cd src
make pu
make clean-mymachine
rm liblammps*
rm lmp_mymachine
make lib-pace
make lib-pace "args=-b"
make yes-ml-pace
make mode=shlib mymachine
```

**Comment by akohlmey** [comment]
@bernstei thanks for reporting. This should be fixed in  commit 9906486578f738948010d2f09f6d13934a82d3f1
