### ISSUE TITLE
PKG_COLVARS

### ISSUE THREAD

**Issue by saeid-lab** [lammps/lammps#2960]
Hello everybody,

I'm trying to compile the latest stable version of lammps along with a few packages including colvars. 
` git clone -b stable https://github.com/lammps/lammps.git lammps`

Operating system: CentOS Linux release 7.2.1511
Libraries installed on this OS:
```
intel compiler and intelmpi v2017.4.196
cmake v3.15.5
fftw v3.3.8
mkl v2017.4.196
```

starting with Cmake:
`cmake ../cmake/ -DCMAKE_INSTALL_PREFIX=../sep21 -DLAMMPS_MACHINE=sky -DPKG_COLVARS=yes -DPKG_RIGID=yes -DPKG_MOLECULE=yes -DPKG_KSPACE=yes -DBUILD_TOOLS=yes -DFFT=MKL -DBUILD_LAMMPS_SHELL=no -DBUILD_MPI=on -DPKG_BODY=on -DPKG_MANYBODY=on -DPKG_MC=on -DPKG_QEQ=on -DPKG_DIPOLE=on -DPKG_USER-QMMM=on -DPKG_USER-MISC=on -DPKG_USER-REACTION=on -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpiicpc -DCMAKE_Fortran_COMPILER=mpiifort
`

After running Cmake:

```
-- The following tools and libraries have been found and configured:
 * Git
 * MPI
 * OpenMP
 * PkgConfig
 * MKL

-- <<< Build configuration >>>
   Operating System: Linux
   Build type:       RelWithDebInfo
   Install path:     /home/***/shared/Softwares/lmp_27sep/sep21
   Generator:        Unix Makefiles using /usr/bin/gmake
-- Enabled packages: BODY;DIPOLE;KSPACE;MANYBODY;MC;MOLECULE;QEQ;RIGID;USER-MISC;USER-QMMM;USER-REACTION
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /opt/soft/all/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin/mpiicpc
      Type:          Intel
      Version:       17.0.4.20170411
      C++ Flags:     -restrict -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=3;LAMMPS_GZIP;LAMMPS_FFMPEG;FFT_MKL;FFT_MKL_THREADS
      Options:       -xHost
-- Fortran Compiler: /opt/soft/all/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin/mpiifort
      Type:          Intel
      Version:       17.0.4.20170411
      Fortran Flags: -O2 -g
-- C compiler:       /opt/soft/all/intel/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin/mpicc
      Type:          Intel
      Version:       17.0.4.20170411
      C Flags:       -O2 -g -DNDEBUG
-- <<< Linker flags: >>>
-- Executable name:  lmp_sky
-- Static library flags:    
-- <<< MPI flags >>>
-- MPI_defines:      
-- MPI includes:     
-- MPI libraries:    ;
-- <<< FFT settings >>>
-- Primary FFT lib:  MKL
-- Using double precision FFTs
-- Using threaded FFTs
-- <<< Building Tools >>>
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PKG_COLVARS

```

As it is mentioned in the [manual](https://docs.lammps.org/Build_extras.html#colvars) colvars should be installed simply by adding `-D PKG_COLVARS=yes`. but I'm getting the warning from cmake.

What is the problem with this configuration?

Best
Saeid

**Comment by akohlmey** [comment]
The problem is that you are not reading a version of the documentation that matches your LAMMPS version.
We have recently reorganized/renamed many packages and dropped the "USER-"prefix. Please see the documentation of the stable version.
https://docs.lammps.org/stable/Build_extras.html#user-colvars

BTW: there will be a new stable version in just a few days, so you may want to try out the "unstable" branch instead (which is "almost stable") and then upgrade when the new stable version is out. but in the mean time, you can provide valuable feedback in case there are any issues building and using the new version so we can address them before making the new stable release.
