### ISSUE TITLE
[BUG] fix/brownian uses drag incorrectly

### ISSUE THREAD

**Issue by mphoward** [lammps/lammps#2970]
**Summary**

fix/brownian does not give the expected translational diffusion coefficient when gamma_t is not equal to 1.0.

**LAMMPS Version and Platform**

LAMMPS (31 Aug 2021), university HPC resource.

The BROWNIAN package does not seem to have been substantially changed in the git history after the version I tested.

**Expected Behavior**

The mean squared displacement for Brownian walkers in three dimensions should be:
```
<dr^2> = 6 D t = 6 (kT/gamma_t) t
```
I think this expression is consistent with how gamma_t is used in the equations of motion in the docs (https://docs.lammps.org/fix_brownian.html) and its units:

> The units of gamma_t are mass/time.

If I plot <dr^2> vs. t, I expect to get a line with slope 6 kT/gamma_t.

**Actual Behavior**

When I plot this curve for gamma_t = 1.0, I get the right slope. When I plot this curve for gamma_t = 2.0, I get a steeper slope:

![msd](https://user-images.githubusercontent.com/6749016/135514277-e6a14e1f-7b0f-438a-8927-3cb59f132caa.png)

**Steps to Reproduce**
This script was used to generate the plot above with gamma_t = 2.0:
```
units lj
atom_style atomic

region box block 0 100 0 100 0 100
create_box 1 box
create_atoms 1 random 10000 42 box
mass 1 1.0

timestep 1e-4
fix bd all brownian 1.0 42 gamma_t 2.0

compute msd all msd
thermo 1
thermo_style custom step c_msd[*]
thermo_modify norm no

run 10
```

**Further Information, Files, and Links**
I believe that this line:
https://github.com/lammps/lammps/blob/c30ba70fab466105925d02e8ec810f5fc7f9448b/src/BROWNIAN/fix_brownian.cpp#L48
should be `/=` rather than `*=`. I have not checked if a line like this appears in any other files in the BROWNIAN package.

**Comment by mphoward** [comment]
Sorry, I just realized this is a duplicate of #2948 but adds some extra detail.

**Comment by MARS-CODE** [comment]
@mphoward , We see exactly the same bug, I think. :)
