### ISSUE TITLE
[BUG] Errors while running with GPU or KOKKOS package on Nvidia A40

### ISSUE THREAD

**Issue by realac** [lammps/lammps#2981]
**Summary**
When I compiled the lammps using CUDA:
```
cmake3 -C ../cmake/presets/basic.cmake -DCMAKE_INSTALL_PREFIX=/data/apps/lammps -D PKG_GPU=on -D GPU_API=cuda -D GPU_ARCH=sm_86 -DBUILD_MPI=yes -DBUILD_OMP=yes ../cmake
```

There is no error reported while building, but when I run it, the code failed
``The error “Cuda driver error 100 in call at file ‘/data/sourcecode/lammps/lammps-stable_29Sep2021/lib/gpu/geryon/nvd_device.h’ in line 323`` was shown.
I tried the latest version and the previous one, the code always failed at `` CU_SAFE_CALL_NS(cuInit(0))``

I tried to compile with **-D GPU_API=opencl**
The work still failed.
In the output:
```
LAMMPS (29 Sep 2021)
using 1 OpenMP thread(s) per MPI task
**ERROR: Invalid OpenCL platform ID. (src/GPU/gpu_extra.h:77)**
Last command: package gpu 0
```

I also tried to compile using KOKKOS package, but it still failed.
The ERROR message:
```
terminate called after throwing an instance of ‘std::runtime_error’
what(): cudaGetDeviceCount(&m_cudaDevCount) error( cudaErrorNoDevice): no CUDA-capable device is detected /data/sourcecode/lammps/lammps-20Sep2021/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:224
Traceback functionality not available

terminate called after throwing an instance of ‘std::runtime_error’
what(): cudaGetDeviceCount(&m_cudaDevCount) error( cudaErrorNoDevice): no CUDA-capable device is detected /data/sourcecode/lammps/lammps-20Sep2021/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:224
Traceback functionality not available
```

**LAMMPS Version and Platform**

lammps-stable_29Sep2021
CPU:Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, GPU: A40
CentOS 7.5.1804, devtoolset-9, intel compilers and libraries 2018.3

**nvidia-smi -a**
```
==============NVSMI LOG==============

Timestamp                                 : Mon Oct  4 20:35:36 2021
Driver Version                            : 460.91.03
CUDA Version                              : 11.2

Attached GPUs                             : 1
GPU 00000000:AF:00.0
    Product Name                          : A40
    Product Brand                         : NVIDIA
    Display Mode                          : Enabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : 1322221067760
    GPU UUID                              : GPU-4888bf68-bd14-684b-f7d5-f8523223c705
    Minor Number                          : 0
    VBIOS Version                         : 94.02.5C.00.03
    MultiGPU Board                        : No
    Board ID                              : 0xaf00
    GPU Part Number                       : 900-2G133-0000-000
    Inforom Version
        Image Version                     : G133.0200.00.05
        OEM Object                        : 2.0
        ECC Object                        : 6.16
```
**nvc_get_devices**
```
Found 1 platform(s).
CUDA Driver Version: 11.20
Device 0: “A40”
Type of device: GPU
Compute capability: 8.6
Double precision support: Yes
Total amount of global memory: 44.5645 GB
Number of compute units/multiprocessors: 84
Number of cores: 16128
Total amount of constant memory: 65536 bytes
Total amount of local/shared memory per block: 49152 bytes
Total number of registers available per block: 65536
Warp size: 32
Maximum number of threads per block: 1024
Maximum group size (# of threads per block) 1024 x 1024 x 64
Maximum item sizes (# threads for each dim) 2147483647 x 65535 x 65535
Maximum memory pitch: 2147483647 bytes
Texture alignment: 512 bytes
Clock rate: 1.74 GHz
Run time limit on kernels: No
Integrated: No
Support host page-locked memory mapping: Yes
Compute mode: Default
Concurrent kernel execution: Yes
Device has ECC support enabled: Yes
```

**The input file for the test job:**

```
variable        x index 1
variable        y index 1
variable        z index 1

variable        xx equal 120*$x
variable        yy equal 120*$y
variable        zz equal 120*$z

units           lj
atom_style      atomic

lattice         fcc 0.8442
region          box block 0 ${xx} 0 ${yy} 0 ${zz}
create_box      1 box
create_atoms    1 box
mass            1 1.0

velocity        all create 1.44 87287 loop geom

pair_style      lj/cut 2.5
pair_coeff      1 1 1.0 1.0 2.5

neighbor        0.3 bin
neigh_modify    delay 0 every 20 check no

fix             1 all nve

dump            1 all custom 100 lj.dump id type x y z vx vy vz

thermo          1000
run             10000
```

**Comment by akohlmey** [comment]
Does this happen when running in parallel or in serial?

**Comment by rbberger** [comment]
@realac I reformatted the issue a bit so it's easier to read. can you please also post the full LAMMPS command-line you used to launch your calculation?

**Comment by weinbe2** [comment]
@realac this sounds like an issue with your CUDA install/driver on this machine as opposed to an issue with LAMMPS specifically. Have you tried compiling and running any other (simpler) codes? A good place to start is the `0_Simple/vectorAdd` sample that comes with the CUDA toolkit.

**Comment by realac** [comment]
> @realac I reformatted the issue a bit so it's easier to read. can you please also post the full LAMMPS command-line you used to launch your calculation?

**Comment by realac** [comment]
> Does this happen when running in parallel or in serial?

It happens both for parallel and serial version.

**Comment by realac** [comment]
> @realac I reformatted the issue a bit so it's easier to read. can you please also post the full LAMMPS command-line you used to launch your calculation?

@rbberger 
**For serial version:**
/data/apps/lammps/bin/lmp -sf gpu -pk gpu 1 < in.first > out.first

**For mpi version:**
mpirun -np 2 /data/apps/lammps/bin/lmp -sf gpu -pk gpu 1 < in.first > out.first

**using KOKKOS package**
mpirun -np 2 /data/apps/lammps/bin/lmp -k on g 1 -sf kk < in.first > out.first

**Comment by realac** [comment]
> @realac this sounds like an issue with your CUDA install/driver on this machine as opposed to an issue with LAMMPS specifically. Have you tried compiling and running any other (simpler) codes? A good place to start is the `0_Simple/vectorAdd` sample that comes with the CUDA toolkit.

@weinbe2 
**It runs well for `0_Simple/vectorAdd`** 
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done

Moreover, I also can manage to run VASP-GPU version, DeepMD based on Tensorflow and the code of our group based on Pytorch.

**Comment by weinbe2** [comment]
Have you tried a `Makefile` based build as opposed to a `cmake` build? I can't see a particular reason why LAMMPS would have issues given other simple (and complex) codes are working. I've seen `cmake` sometimes have issues properly finding all the right pieces of the CUDA toolkit, especially for non-standard installation paths (i.e., not `/usr/local/cuda`), or if there are multiple installs improperly flying around on a machine (where you could get weird dynamic linking mix-and-match).

A Kokkos build should be particularly easy, given a fresh clone:

```
cd [path/to/lammps]/src
sed -i 's/Volta70/Ampere86/g' MAKE/OPTIONS/Makefile.kokkos_cuda_mpi
make yes-kokkos && make -j kokkos_cuda_mpi
```
