### ISSUE TITLE
Repositroy history contains >100MB blobs that don't work with github...

### ISSUE THREAD

**Issue by twhitehead** [lammps/lammps#2987]
I've been working for the group that makes the LATBOLTZ package. They have a private repo for doing their development. We recently grafted this on top of the official LAMMPS repo to make it easier to merge stuff between the two.

When we went to push the LAMMPS history up to the group's private GitHub repo, we discovered that you can't [because it contains blobs that are ≥ 100MB](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#about-size-limits-on-github)
```
$ git clone git@github.com:lammps/lammps.git
$ cd lammps
$ git remote add test git@github.com:twhitehead/lammps-new.git
$ git push test
Enumerating objects: 282216, done.
Counting objects: 100% (282216/282216), done.
Delta compression using up to 4 threads
Compressing objects: 100% (43087/43087), done.
Writing objects: 100% (282216/282216), 542.35 MiB | 116.00 KiB/s, done.
Total 282216 (delta 237308), reused 282216 (delta 237308), pack-reused 0
remote: Resolving deltas: 100% (237308/237308), done.
remote: Checking connectivity: 282216, done.
remote: warning: File potentials/C_10_10.mesocnt is 82.67 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: Trace: cf8cc866b35da41fba645fc43296bc193c258d3322279e94dab41d7230e725ee
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File lib/atc/libatc.a is 167.51 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:twhitehead/lammps-new.git
 ! [remote rejected]       master -> master (pre-receive hook declined)
error: failed to push some refs to 'github.com:twhitehead/lammps-new.git'
```

It seems this file is the only one ≥100MB
```
$ git rev-list --all --objects --filter  --filter=blob:limit=100M > list-limit
$ git rev-list --all --objects --filter  > list-all
$ diff -U0 list-limit list-all 
--- list-limit	2021-10-08 16:48:19.248893632 -0400
+++ list-all	2021-10-08 16:48:54.344711723 -0400
@@ -235510,0 +235512 @@
+00a6afc0bb7f405772ae780c9fdfb0ebb19b8980 lib/atc/libatc.a
$ git cat-file -s 00a6afc0bb7f405772ae780c9fdfb0ebb19b8980
175645572
```
```
$ git log --all --oneline -- lib/atc/libatc.a
d56c9dfd27 Removal of superfluous files from lib-atc repository.
7855ef6dda ATC version 2.0, date: Aug7
```
We have tried to come up with various workarounds, but everything we have tried so far hasn't worked. It seems so long as this large file is on the history the most you can do with GitHub is make one public fork LAMMPS repo via the GitHub fork button. Anything else requires uploading the history again, and that fails.

Not that it matters, but I guess the original must have been uploaded before this limit was put in place.

**Comment by akohlmey** [comment]
You don't need the entire history for the purpose you describe since git resolves differences "backwards". That means, you only need the history up to the oldest hash that you would ever need to reference. Thus it should be possible to do a `git clone --depth 10000` or so and you won't have those binaries and still have information of over a couple years worth of recent commits included.

Those binaries date back to the time when LAMMPS was managed in a subversion repo at Sandia and somebody had an ill-advised automatic commit setup. The git repo was first hosted as mirror of the subversion repo outside of github. I didn't import the repo to GitHub, so I don't know how this came to be. Unfortunately, those undesired binaries were discovered only quite a long time after their import (and removal) and one of the design choices of git is that you "cannot rewrite history", i.e. if we have squashed the commits that added and removed those big files, we would have had a significant divergence for any existing git clone, so we didn't do it.

**Comment by twhitehead** [comment]
Okay. I will move the conversation to the mailing list. I will note here though, for anyone who happens to come across this looking for an answer, that truncating the history also does not work as [github won't let push shallow copies](
https://github.community/t/set-receive-shallowupdate-on-to-allow-pushing-from-shallow-clones/2424)

Here is a sample session form trying to push a version I pruned starting at commit d56c9dfd27 (the furthest back you can go without introduction the >100MB file into the history). You can see it dies at the end with `shallow update not allowed`.
```
$ git push test
Enumerating objects: 227023, done.
Counting objects: 100% (227023/227023), done.
Delta compression using up to 4 threads
Compressing objects: 100% (40073/40073), done.
Writing objects: 100% (227023/227023), 450.94 MiB | 118.00 KiB/s, done.
Total 227023 (delta 185864), reused 227023 (delta 185864), pack-reused 0
remote: Resolving deltas: 100% (185864/185864), done.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File 60a06741834fe168033ae0f46956e73159386ab3 is 82.67 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:twhitehead/lammps-new.git
 ! [remote rejected]     develop -> develop (shallow update not allowed)
error: failed to push some refs to 'github.com:twhitehead/lammps-new.git'
```
