### ISSUE TITLE
TIP4P pair_styles don’t work

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#299]
The tip4p pair_styles don’t work correctly with triclinic. For example, I get a significantly different thermo output if I use “change_box triclinic” with all zero tilt factors, using pair_style lj/cut/tip4p/cut.

**Comment by akohlmey** [comment]
The first suspect that comes to mind, would be the Domain::closes_image() function with 3 arguments, as that seems to be used exclusively with TIP4P pair styles.

**Comment by stanmoore1** [comment]
I did a little poking around and it seems to have to do with differences in the neighbor lists for orthogonal vs triclinic. If I use a non-triclinic neighborlist then it works fine, even though triclinic flag turned on. The triclinic neighborlist seems to not play nice with where the rsq distance is modified for the oxygen charge.  Tilt factors are all zero, so the Domain::closest_image() is equivalent for orthogonal and triclinic cases. Unfortunately, I don't have much more time to work on this.

**Comment by stanmoore1** [comment]
I have a little time to work on this, getting closer.

**Comment by stanmoore1** [comment]
This isn't just a bug in triclinic, it affects orthogonal tip4p too! Here is the bugfix, below. I will submit a pull request.

<pre>
diff --git a/src/domain.cpp b/src/domain.cpp
index 54183f6..492ac67 100644
--- a/src/domain.cpp
+++ b/src/domain.cpp
@@ -947,19 +947,19 @@ void Domain::minimum_image(double &dx, double &dy, double &dz)
 {
   if (triclinic == 0) {
     if (xperiodic) {
-      if (fabs(dx) > xprd_half) {
+      while (fabs(dx) > xprd_half) {
         if (dx < 0.0) dx += xprd;
         else dx -= xprd;
       }
     }
     if (yperiodic) {
-      if (fabs(dy) > yprd_half) {
+      while (fabs(dy) > yprd_half) {
         if (dy < 0.0) dy += yprd;
         else dy -= yprd;
       }
     }
     if (zperiodic) {
-      if (fabs(dz) > zprd_half) {
+      while (fabs(dz) > zprd_half) {
         if (dz < 0.0) dz += zprd;
         else dz -= zprd;
       }
@@ -967,7 +967,7 @@ void Domain::minimum_image(double &dx, double &dy, double &dz)
 
   } else {
     if (zperiodic) {
-      if (fabs(dz) > zprd_half) {
+      while (fabs(dz) > zprd_half) {
         if (dz < 0.0) {
           dz += zprd;
           dy += yz;
@@ -980,7 +980,7 @@ void Domain::minimum_image(double &dx, double &dy, double &dz)
       }
     }
     if (yperiodic) {
-      if (fabs(dy) > yprd_half) {
+      while (fabs(dy) > yprd_half) {
         if (dy < 0.0) {
           dy += yprd;
           dx += xy;
@@ -991,7 +991,7 @@ void Domain::minimum_image(double &dx, double &dy, double &dz)
       }
     }
     if (xperiodic) {
-      if (fabs(dx) > xprd_half) {
+      while (fabs(dx) > xprd_half) {
         if (dx < 0.0) dx += xprd;
         else dx -= xprd;
       }
</pre>

**Comment by stanmoore1** [comment]
This is only an issue when the cutoff is larger than the box.

**Comment by stanmoore1** [comment]
This is fixed in the svn branch.

**Comment by stanmoore1** [comment]
Fixed in 142770cb2a6978ba0b4884edc3f0806df3959c94. Closed #299.
