### ISSUE TITLE
[Update documentation] pair_style granular command damping mass velocity

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#3016]
**Summary**

In the documentation of pair_style granular command, for damping mass velocity, \eta_{n0} should be of units 1/time.
The documentation suggests it should be of units mass/time.

**LAMMPS Version and Platform**
LAMMPS 27 Oct 2021
**Details**
For 'damping velocity', damping force F_damp = \eta_{n0} *velocity. Thus, \eta_{n0} should have units of mass/time
For 'damping mass_velocity', damping force F_damp = \eta_{n0} * meff * velocity. Thus, \eta_{n0} should have units of 1/time since meff has units of mass.

However documentation suggests that \eta_{n0} should have units of mass/time in both the cases i,.e for 'damping velocity' and 'damping mass velocity'.

Please see attached screenshot.
![Screenshot from 2021-11-03 15-36-33](https://user-images.githubusercontent.com/25865956/140042907-19a93a80-b982-49c1-a3f6-27c039392e02.png)

**Comment by dsbolin** [comment]
Thanks for catching that. Correct, for _damping mass_velocity_, units of the dampig coefficient are  _1/time_. @akohlmey , what's the easiest way for me to help correct this?

**Comment by akohlmey** [comment]
Just send me the edits you would like to make.

**Comment by dsbolin** [comment]
In doc`/src/pair_granular.rst`, this:
```
For *damping mass_velocity*, the normal damping is given by:

.. math::

   \eta_n = \eta_{n0} m_{eff}

Here, :math:`\eta_{n0}` is the damping coefficient specified for the normal
contact model, in units of *mass*\ /\ *time*
```

should be:
```
For *damping mass_velocity*, the normal damping is given by:

.. math::

   \eta_n = \eta_{n0} m_{eff}

Here, :math:`\eta_{n0}` is the damping coefficient specified for the normal
contact model, in units of 1 /\ *time*
```

i.e. just replace `mass/time` with `1/time` in the appropriate section.

**Comment by akohlmey** [comment]
@dsbolin done see PR #3020
