### ISSUE TITLE
[BUG] Unintentional Precision Loss With -ffast-math via HIP

### ISSUE THREAD

**Issue by tchntt** [lammps/lammps#3023]
**Summary**

If I compile LAMMPS with Makefile.hip and the precision DOUBLE_DOUBLE for GPU package, I get low precision due to the flag -ffast-math. Removing the flag restore the intended precision.

I recommend removing the flag from Makefile.hip by default to prevent unintentional precision loss.

**LAMMPS Version and Platform**

Ubuntu 20.04
OCT 27 2021 with ROCM 4.1.1
gfx906 GPU 
Intel Xeon W2265 CPU

**Details**

Example log files are attached, one compiled with -ffast-math and the other without the flag.
Both are compiled with DOUBLE_DOUBLE precision.

[log-ffast-math-HIP.zip](https://github.com/lammps/lammps/files/7507101/log-ffast-math-HIP.zip)

**Comment by Vsevak** [comment]
@tchntt could you please provide the corresponding input file?

**Comment by tchntt** [comment]
[ffastmath_hip_gfx906.zip](https://github.com/lammps/lammps/files/7528425/ffastmath_hip_gfx906.zip)

Here, I have generated a CSL with GB_code and tried minimization with the fnorm termination criterion of 1e-12.

Without -ffath-math, the convergence was achieved.
With -ffast-math, the fnorm couldn't go below the order of 1e-8.

The log files are attached. (The potentials used can be found in the LAMMPS potentials folder)

I will test with Vega 64 this weekend to see if this is machine specific (gfx900 vs gfx906), and will update if I get different results.

Thank you.
