### ISSUE TITLE
MacOS M1 with Monterey

### ISSUE THREAD

**Issue by Nick12-hub** [lammps/lammps#3024]
Can lammps be installed on MacOS M1 with Monterey？In fact it is currently not solved by homebrew, please tell us another good way, thanks!

**Comment by akohlmey** [comment]
There should be no problem *per se* to compile LAMMPS from source using the CMake method. There is no code in LAMMPS that is specific to the M1 CPU architecture and very few items that are specific to MacOS. Instructions for compiling LAMMPS from source are in the manual.

Homebrew configuration issues is something you should report to the homebrew project. The LAMMPS developers have no influence over that.

**Comment by Nick12-hub** [comment]
> 使用 CMake 方法从源代码编译 LAMMPS_本身_应该没有问题。LAMMPS 中没有特定于 M1 CPU 架构的代码，也没有特定于 MacOS 的项目。从源代码编译 LAMMPS 的说明在手册中。
> 
> 您应该向 Homebrew 项目报告 Homebrew 配置问题。LAMMPS 开发人员对此没有影响。

Yes, you're right, I solved the problem, thanks!
