### ISSUE TITLE
[BUG] stable_27Oct2021 atom_style smd cannot hybrid with other styles

### ISSUE THREAD

**Issue by edmondztt** [lammps/lammps#3028]
**Summary**

Hi,

I'm trying to use 
atom_style hybrid smd sphere  
however it always gives a segmentation fault, shown in gdb:
Thread 1 "lmp_omp" received signal SIGSEGV, Segmentation fault.
0x00005555559d4936 in LAMMPS_NS::AtomVecSMD::create_atom_post (this=0x555555cb0dd0, ilocal=0)
    at ../atom_vec_smd.cpp:147
147	  x0[ilocal][0] = x[ilocal][0];
I tried other styles instead of sphere as well, no luck.

**LAMMPS Version and Platform**

Lammps version 27Oct2021, platform ubuntu 20.04

**Steps to Reproduce**

This was run in the examples/PACKAGES/machdyn/funnel_flow/ folder, with the modified input script attached.
[in.funnel_flow-testhybrid.txt](https://github.com/lammps/lammps/files/7551105/in.funnel_flow-testhybrid.txt)

**Comment by akohlmey** [comment]
@edmondztt thanks for your report. I have confirmed the bug and am working on a fix now.

**Comment by akohlmey** [comment]
Commit 2b480f87f1a548267a8adacc69864a591cab40ce should eliminate the segfault
