### ISSUE TITLE
[BUG] Pylammps 'NoneType' object is not iterable in examples/simple.ipynb

### ISSUE THREAD

**Issue by Nyrb1001** [lammps/lammps#3037]
**Summary**
After initializing the 3d Lennard-Jones melt (found in simple.ipynb):
L = IPyLammps()
L.units("lj")
....
L.thermo(50)

I can perform a single L.run(150), but the second time I run the event with either L.run(150) or 
L.run(100);
I'll get the type error:'NoneType' object is not iterable. If I keep sending the same command, eventually it will run without returning the error, but it will then return it again at other, seemingly random runs. The log.lammps file appears to output the correct values.

**LAMMPS Version and Platform**

LAMMPS (27 Oct 2021) installed via cmake in virtual environment (conda)
WSL-2 running Ubuntu 20.04.2 LTS
Python 3.8.12
Running in Jupyter Lab

**Expected Behavior**
Running simulation in multiple steps will not return Nonetype error.

**Steps to Reproduce**

Running simple.ipynb from top to bottom will reproduce the result on the L.run(100); line. Or, rerun the L.run(150) cell.

**Further Information, Files, and Links**
Here are the (seemingly okay?) log.lammps outputs:

### No type error

> run 150
> Neighbor list info ...
>   update every 20 steps, delay 0 steps, check no
>   max neighbors/atom: 2000, page size: 100000
>   master list distance cutoff = 2.8
>   ghost atom cutoff = 2.8
>   binsize = 1.4, bins = 5 5 5
>   1 neighbor lists, perpetual/occasional/extra = 1 0 0
>   (1) pair lj/cut, perpetual
>       attributes: half, newton on
>       pair build: half/bin/atomonly/newton
>       stencil: half/bin/3d
>       bin: standard
> Per MPI rank memory allocation (min/avg/max) = 2.619 | 2.619 | 2.619 Mbytes
> Step Temp E_pair E_mol TotEng Press 
>        0         1.44   -6.7733681            0   -4.6218056   -5.0244179 
>       50   0.70303849   -5.6796164            0    -4.629178   0.50453907 
>      100   0.72628044   -5.7150774            0   -4.6299123   0.29765862 
>      150   0.78441711    -5.805142            0   -4.6331125 -0.086709661 
> Loop time of 0.0215201 on 1 procs for 150 steps with 256 atoms
> 
> Performance: 3011138.704 tau/day, 6970.228 timesteps/s
> 101.2% CPU use with 1 MPI tasks x 1 OpenMP threads
> 
> MPI task timing breakdown:
> Section |  min time  |  avg time  |  max time  |%varavg| %total
> \---------------------------------------------------------------
> Pair    | 0.016973   | 0.016973   | 0.016973   |   0.0 | 78.87
> Neigh   | 0.002974   | 0.002974   | 0.002974   |   0.0 | 13.82
> Comm    | 0.00091413 | 0.00091413 | 0.00091413 |   0.0 |  4.25
> Output  | 9.5509e-05 | 9.5509e-05 | 9.5509e-05 |   0.0 |  0.44
> Modify  | 0.0003101  | 0.0003101  | 0.0003101  |   0.0 |  1.44
> Other   |            | 0.0002531  |            |       |  1.18
> 
> Nlocal:        256.000 ave         256 max         256 min
> Histogram: 1 0 0 0 0 0 0 0 0 0
> Nghost:        1415.00 ave        1415 max        1415 min
> Histogram: 1 0 0 0 0 0 0 0 0 0
> Neighs:        9589.00 ave        9589 max        9589 min
> Histogram: 1 0 0 0 0 0 0 0 0 0
> 
> Total # of neighbors = 9589
> Ave neighs/atom = 37.457031
> Neighbor list builds = 7
> Dangerous builds not checked

### Type error for this run

> run 150
> Per MPI rank memory allocation (min/avg/max) = 2.619 | 2.619 | 2.619 Mbytes
> Step Temp E_pair E_mol TotEng Press 
>      150   0.78441711    -5.805142            0   -4.6331125 -0.086709661 
>      200   0.72383129   -5.7134714            0   -4.6319657   0.29223788 
>      250   0.76070846    -5.769333            0   -4.6327275  0.075484061 
>      300   0.73251832   -5.7259162            0   -4.6314308   0.37767741 
> Loop time of 0.0217076 on 1 procs for 150 steps with 256 atoms
> 
> Performance: 2985134.170 tau/day, 6910.033 timesteps/s
> 101.6% CPU use with 1 MPI tasks x 1 OpenMP threads
> 
> MPI task timing breakdown:
> Section |  min time  |  avg time  |  max time  |%varavg| %total
> \---------------------------------------------------------------
> Pair    | 0.017392   | 0.017392   | 0.017392   |   0.0 | 80.12
> Neigh   | 0.0027107  | 0.0027107  | 0.0027107  |   0.0 | 12.49
> Comm    | 0.00094325 | 0.00094325 | 0.00094325 |   0.0 |  4.35
> Output  | 6.6253e-05 | 6.6253e-05 | 6.6253e-05 |   0.0 |  0.31
> Modify  | 0.00032739 | 0.00032739 | 0.00032739 |   0.0 |  1.51
> Other   |            | 0.0002683  |            |       |  1.24
> 
> Nlocal:        256.000 ave         256 max         256 min
> Histogram: 1 0 0 0 0 0 0 0 0 0
> Nghost:        1405.00 ave        1405 max        1405 min
> Histogram: 1 0 0 0 0 0 0 0 0 0
> Neighs:        9566.00 ave        9566 max        9566 min
> Histogram: 1 0 0 0 0 0 0 0 0 0
> 
> Total # of neighbors = 9566
> Ave neighs/atom = 37.367188
> Neighbor list builds = 7
> Dangerous builds not checked

**Comment by rbberger** [comment]
@Nyrb1001 It's a limitation of how PyLammps works. It has to be able to capture the output and that is only possible if Python is run without buffering. So before you launch jupyterlab, make sure to set this environment variable:
```
export PYTHONUNBUFFERED=1
jupyter lab
```

**Comment by Nyrb1001** [comment]
Ah, yes! Thank you very much. Works as intended now.
Apologies for the silly mistake - I'm a little new to all this.
