### ISSUE TITLE
more flexible behavior from KIM package compilation script

### ISSUE THREAD

**Issue by bernstei** [lammps/lammps#3042]
Our cmake executable is named `cmake3`, but this https://github.com/lammps/lammps/blob/1a4511bb8db2ec6555e82805f7e015b08bd4248d/lib/kim/Install.py#L144 hardwires just `cmake`.  I made a symlink, but it might be nice for that to be user controllable, e.g. via a `CMAKE` env or make var.

Also, it would be useful to make cmake use the same compilers as the rest of the LAMMPS compilation if it compiles a .  Ours, when run by the `Install.py` script,  seems to default to incorrect ones (seemed to be something conda related, even though we used `args="-b"` to compile a local copy of kim).  I'll try to give a reproducible process to show this behavior and post here.

**Comment by bernstei** [comment]
Note: all of these behaviors are being observed with regular make compilation of lammps, not cmake.

**Comment by akohlmey** [comment]
@bernstei This is not really something that can be easily addressed from the build system and specifically not with the conventional make based approach. Even with CMake there are difficulties passing settings to and external projects as I have recently discovered why trying to build LAMMPS on multi-config build systems.

The main issue is a conceptual one: you should not expect that building the KIM-API as part of the LAMMPS build is providing you a proper and consistent and complete KIM-API installation. Rather, you should be installing the KIM-API as a *separate* installation *first*. Only the separate and either system-wide or per-user installation of the KIM-API will provide you with a proper installation that also gives you direct access to the management tools and extended features.

The integration into the LAMMPS build system is mainly for the purpose of automated testing.

**Comment by akohlmey** [comment]
> Note: all of these behaviors are being observed with regular make compilation of lammps, not cmake.

May I ask what it is that makes you prefer the conventional make procedure over using CMake?

**Comment by bernstei** [comment]
re: self-build vs. separate install - I'm perfectly happy with your explanation, but I suggest that the lack of support for "-b" in normal user installations should be documented more explicitly in https://docs.lammps.org/Build_extras.html#kim

> May I ask what it is that makes you prefer the conventional make procedure over using CMake?

In this case nothing - just what my colleague is used to doing.  I myself have mostly switched to cmake, although I don't entirely love the way packages are selected.  Maybe it's just that I'm not used to how that's done with cmake yet.

**Comment by akohlmey** [comment]
> re: self-build vs. separate install - I'm perfectly happy with your explanation, but I suggest that the lack of support for "-b" in normal user installations should be documented more explicitly in https://docs.lammps.org/Build_extras.html#kim

I've assigned this issue to a couple of the KIM-API developers. Hopefully they can look into it.

> > May I ask what it is that makes you prefer the conventional make procedure over using CMake?
> 
> In this case nothing - just what my colleague is used to doing. I myself have mostly switched to cmake, although I don't entirely love the way packages are selected. Maybe it's just that I'm not used to how that's done with cmake yet.

Ok. A few suggestions from my personal usage:
- if you want a more GNU make like process, you can configure first using a suitable preset (e.g. basic.cmake) and then use the GUI or TUI version of cmake (e.g. ccmake) to "tweak" those settings interactively, e.g. adding or removing individual packages or features. I find that is a very effective combination, specifically because one doesn't have to remember all the names of the different packages.
- if you need to use different configurations at the same time, you have easily have multiple build folders connected to the same source tree (i often have 5-10 build folders with different compilers and MPI library and combinations of packages in my development tree and when switching branches CMake is usually detecting that it needs to be re-run and thus I rarely need to manually clean and/or reconfigure those).

**Comment by ellio167** [comment]
> re: self-build vs. separate install - I'm perfectly happy with your explanation, but I suggest that the lack of support for "-b" in normal user installations should be documented more explicitly in https://docs.lammps.org/Build_extras.html#kim

Hello!  I'm happy to make improvements to the KIM `Install.py` script, but it's not really clear to me what those might be.  the `-b` options is functional, it seems it just doesn't behave as you expect it to.  The default behavior of the KIM cmake build on your system is not what you want.  This is something that is very system dependent and, as Axel says, is very difficult to manage via the lammps traditional make system.  Thus, it seems that unfortunately, your system falls into the category of too "non-standard" to work "out-of-the-box" with the lammps traditional make system.

Adjusting for the name of the `camke` executable is certainly doable.  Another possible enhancement would be to provide a mechanism to pass compiler names on the `-b` command line.  These seem like reasonable changes that would partially address your concerns.  Would something along these lines be workable for you?

**Comment by akohlmey** [comment]
> Another possible enhancement would be to provide a mechanism to pass compiler names on the `-b` command line.

That would not be necessary. You can set preferred compiler names/commands for CMake also via environment variables.
https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html

**Comment by ellio167** [comment]
> > Another possible enhancement would be to provide a mechanism to pass compiler names on the `-b` command line.
> 
> That would not be necessary. You can set preferred compiler names/commands for CMake also via environment variables. https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html

Agreed, that is true.  Maybe it would be helpful to add an example of doing this to the lammps kim build documentation (https://docs.lammps.org/Build_extras.html#kim)?

**Comment by bernstei** [comment]
At least making it explicit that if even you use traditional make for lammps the kim library building process will still use cmake, and therefore may need some related variables set, would be helpful.

**Comment by ellio167** [comment]
I've created #3044 to address these issues.
