### ISSUE TITLE
[Question] recommended way to glue with PySCF?

### ISSUE THREAD

**Issue by zc62** [lammps/lammps#3045]
**Summary**

A question about how to most efficiently couple LAMMPS to the PySCF package

**LAMMPS Version and Platform**

Current version, Linux

**Details**

Hope this is not a too terrible place to ask general questions, as I cannot find anything about this topic in previous issues or the mailing list.

I see that LAMMPS has multiple ways to use other software packages to calculate the forces for MD simulations. In the python module I found the [`fix_external_get_force`](https://github.com/lammps/lammps/blob/8589ecd6c120888a8ca29b36a6a4afad55e022f2/python/lammps/core.py#L1810) function, but it seems that it still uses the `fix` command way to execute external programs, which makes the utilization of python no different from directly running the binary. Or they can be combined via the server/client mode, and I see that a couple of wrapper scripts are written in python.

My question is then, is it possible that I can use pyscf to calculate the forces in a way like:
```python
import pyscf
from lammps import lammps
lmp = lammps()

# lammps reads the input file
# lammps generates the current step geometry in a python string (xyz format)
# pass the string to build a pyscf molecule and calculate the forces
# pass the forces back to lammps to continue the MD step
```

If not possible, if I feel that both the `fix` command method and the server/client mode will work, which one is preferable?

**Comment by akohlmey** [comment]
Please post questions like this to either the "LAMMPS Development" category in the Discourse forum on MatSci.org or the lammps-users mailing list.
