### ISSUE TITLE
Compiler Error upon KSPACE extension

### ISSUE THREAD

**Issue by pstaerk** [lammps/lammps#3051]
## Summary
I want to extend my LAMMPS with an additional KSPACE style which speeds up the Ewald summation for MC. However, the compilation unfortunately fails with

```
/lammps/src/KSPACE/gcmc_ewald.h: In member function ‘void LAMMPS_NS::Force::create_factories()’:
/lammps/src/KSPACE/gcmc_ewald.h:16:23: error: ‘GCMCEwald’ was not declared in this scope
   16 | KSpaceStyle(gcmcewald,GCMCEwald);
      |                       ^~~~~~~~~
/lammps/src/force.cpp:126:41: note: in definition of macro ‘KSpaceStyle’
  126 |   (*kspace_map)[#key] = &kspace_creator<Class>;
      |                                         ^~~~~
/lammps/src/force.cpp:126:26: error: no matches converting function ‘kspace_creator’ to type ‘std::map<std::__cxx11::basic_string<char>, LAMMPS_NS::KSpace* (*)(LAMMPS_NS::LAMMPS*)>::mapped_type’ {aka ‘class LAMMPS_NS::KSpace* (*)(class LAMMPS_NS::LAMMPS*)’}
  126 |   (*kspace_map)[#key] = &kspace_creator<Class>;
      |                          ^~~~~~~~~~~~~~~~~~~~~
/lammps/src/KSPACE/gcmc_ewald.h:16:1: note: in expansion of macro ‘KSpaceStyle’
   16 | KSpaceStyle(gcmcewald,GCMCEwald);
      | ^~~~~~~~~~~
In file included from /lammps/src/force.cpp:15:
/lammps/src/force.h:161:40: note: candidate is: ‘template<class T> static LAMMPS_NS::KSpace* LAMMPS_NS::Force::kspace_creator(LAMMPS_NS::LAMMPS*)’
  161 |   template <typename T> static KSpace *kspace_creator(LAMMPS *);
```

## Steps to reproduce
The easiest way to reproduce the error is to copy the `ewald.h` and `ewald.cpp` and refactor it to something like `gcmc_ewald.h` etc. (and rename the class, obviously). Then try to run the CMAKE build steps.

**LAMMPS Version and Platform**
I am building on Ubuntu 20.04 LTS, with gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.
My current Lammps Version is "8 Apr 2021" .

**Details**
I have checked if the automatically generated `style_kspace.h` contains my header etc. Have grepped for all occurrences of `ewald.h` to check if I have forgotten to also include my `gcmc_ewald.h` etc. But all of this has not helped unfortunately.
By the [online guide to extend LAMMPS](https://docs.lammps.org/Modify.html) it seems that my steps should be the only ones needed.

**Comment by akohlmey** [comment]
This is not a LAMMPS issue but a programmer issue. You obviously did not create the gcmc_ewald.h and gcmc_ewald.cpp files correctly. If I perform those steps, I get no problems compiling. However it is impossible to say *what* your mistake(s) are from remote.
