### ISSUE TITLE
[BUG] dump netcdf does not follow the Amber convention, creating `double` variables instead of `float`

### ISSUE THREAD

**Issue by Luthaf** [lammps/lammps#3061]
**Summary**

The Amber convention for NetCDF trajectories (http://ambermd.org/netcdf/nctraj.xhtml) required all variables to use 32-bit float, but LAMMPS always creates files with the `cell_lengths`, `cell_angles`, `time` variable using double/64-bit float values.

From reading the code, it also seems to be possible to create variables for `coordinates`/`velocities`/`forces` (and the extensions `scaled_coordinates` and `unwrapped_coordinates`) using 64-bit variables with `dump_modify double yes`, although this is not documented in the website. The default behaviour here is following the standard.

I realised this was an issue when trying to re-implement a netcdf3 file parser without relying on the official `netcdf-c` library for [chemfiles](https://github.com/chemfiles/chemfiles). It seems likely that this issue have been hidden by `netcdf-c`dynamically  converting from one datatype to the other dynamically as required. The other implementation I know about which is not based on `netcdf-c` is [scipy's](https://docs.scipy.org/doc/scipy-1.7.1/reference/generated/scipy.io.netcdf_file.html), where the exact datatype matters less since everything is dynamic in Python.

**LAMMPS Version and Platform**

This is happening on the latest `develop` branch: https://github.com/lammps/lammps/blob/2d4f030f113f179411bb3bc6afe97adec8bd62b5/src/NETCDF/dump_netcdf.cpp#L383-L391, and has been the case since at least 2015 (when I generated the file I'm using for testing).

**Expected Behavior**

I'm not sure what the best thing to do is here. I will have to write some code to handle `double` variables anyway in chemfiles to allow users to read existing files, so one possible resolution would be to acknowledge this divergence from the standard somewhere, and keep it as is.

Alternatively, the default could be changed to follow the standard, and users wanting to use double precision variable could still do this with `dump_modify`.

---

I'm willing to send PR implementing whatever change is decided, both to the code and documentation.

**Comment by pastewka** [comment]
I agree that we should have an option to follow the AMBER specification exactly. My suggestion would be to simply extend the `double` switch to include *all* variables, including `cell_lengths`, `cell_angles` and `time`. (I actually think `time` is not covered in the AMBER specification but please correct me, but it makes sense to just export everything as either double or float.)

This would mean simply moving the `xtype` definition up in the code and replacing `NC_DOUBLE` by `xtype`. @Luthaf - if you are happy to do that, please go ahead. Please make an accompanying change in `dumpi_nc_mpiio.cpp`.

I am surprised though that this makes trouble at all. The NetCDF C library should convert these data types on the fly.

**Comment by Luthaf** [comment]
> I am surprised though that this makes trouble at all. The NetCDF C library should convert these data types on the fly.

It does, and that's why I'm only realising this now! I found about this when hand-writing a new netcdf3 parser, without using netcdf-c (I'm writing this new parser to remove dependency on HDF5 and get smaller builds for WASM, it also seems to be a bit faster).

> I actually think time is not covered in the AMBER specification but please correct me, but it makes sense to just export everything as either double or float.

`time` is defined in the specification, as the time in picoseconds. See the section 6.2 of http://ambermd.org/netcdf/nctraj.xhtml

> This would mean simply moving the xtype definition up in the code and replacing NC_DOUBLE by xtype. @Luthaf - if you are happy to do that, please go ahead. Please make an accompanying change in dumpi_nc_mpiio.cpp.

Will do!

**Comment by pastewka** [comment]
Sounds good, thanks for taking care of this!

**Comment by pastewka** [comment]
(PS: I'd be interested in seeing that NetCDF-3 parser. The NetCDF C library is a huge mess. We use NetCDF-3 for many things in my group and having NetCDF C as a dependency is always troublesome.)

**Comment by Luthaf** [comment]
Sure, I'll ping you when It is ready! It is currently written using a couple of internal chemfiles utilities, but could be made standalone with a bit of work. It also only implements the subset of netcdf-3 required to parse the AMBER convention and nothing else, but this could also be changed with more work.

**Comment by pastewka** [comment]
Sounds good!
