### ISSUE TITLE
[BUG] Undefined reference in fmt/format-inl.h

### ISSUE THREAD

**Issue by JMuff22** [lammps/lammps#3063]
When building LAMMPS with any extra packages build fails with line 

`` src/fmt/format-inl.h:217: error: undefined reference to 'std::runtime_error::operator=(std::runtime_error&&)' ``

This occurs when building with cmake or make. For example:

`` cmake ../cmake  -DBUILD_MPI=yes -DLAMMPS_MACHINE=mpi ``

and ` cmake --build . ` builds LAMMPS correctly, as expected. However 

`` cmake ../cmake -DPKG_KSPACE=yes -DBUILD_MPI=yes -DLAMMPS_MACHINE=mpi ``

Produces the error quoted above. This happened the same via `make` in the `/src/` directory.  I tested on my old previous version of LAMMPS (Oct 2021) and also on the latest stable build (`git checkout origin/stable`). 

This is occurring on my university cluster running Linux CentOS Linux 7 and the following module versions:
- OpenMPI/3.1.4-GCC-8.3.0
- FFTW/3.3.8-intel-2018b
-  GNU Compilers (GCC) 7.3.0

Note that this does not occur if I build LAMMPS locally, therefore the issue must be something on my university cluster, however the error indicates not.

**Comment by akohlmey** [comment]
> This is occurring on my university cluster running Linux CentOS Linux 7 and the following module versions:
> 
> * OpenMPI/3.1.4-GCC-8.3.0
> * FFTW/3.3.8-intel-2018b
> * GNU Compilers (GCC) 7.3.0

Please note that you are loading an older GCC environment that what is indicated to be used with your MPI library. That can lead to all kinds of problems, e.g. linking to the wrong C++ runtime library or using inconsistent C++ standard include files. The linkage error you report refers to a function of the C++ runtime, so this would be a plausible explanation.

**Comment by JMuff22** [comment]
Ok thanks I will contact the sys admins to update the GCC compilers to the same version as the MPI library.
