### ISSUE TITLE
[BUG] MPIIO package has become unreliable

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#3066]
**Summary**

In recent times there has been an increasing number of crashes for calculations using MPIIO package output files (restart or dump). The MPIIO package has been largely unmaintained for quite a while now. We need somebody with sufficient knowledge of MPI-IO to look into it and fix the apparent bugs and refactor the code to be better aligned with recent refactoring elsewhere in LAMMPS.

Otherwise, the MPIIO package needs to be deprecated and eventually removed. PR #3064 adds warnings to the LAMMPS output when using MPIIO output and adds warnings to the documentation.

**Comment by rbberger** [comment]
The MPI-IO dump styles are outdated and have **several** TODO items if someone wants to pick it up:
* [ ] Upgrade code copied from base classes (incl. usage of `utils::strdup`)
* [ ] Upgrade dumps to include added magic string, endian, and revision information, as well as unit_style, time, and columns
* [ ] Properly handle `int` and `tagint`
* [ ] Review the OPENMP parts, simplify code, optimize and rework allocations
* [ ] Remove misused OPENMP constructs (e.g. `omp barrier` outside of parallel region)
* [ ] Review all allocations with `new`, `malloc`, and `memory->create`, simplify, and verify they have to happen only once or multiple times, possible make use of `MyPage`

**Comment by akohlmey** [comment]
Problems are more visible now. Also in our unit tests after upgrading to Ubuntu 20.04LTS. Similar issues were reported for FreeBSD in issue #3875
