### ISSUE TITLE
atom_style body and fix rigid

### ISSUE THREAD

**Issue by Tron-x** [lammps/lammps#307]
excuse me!what is the different between the atom_style body and the fix rigid? if i want to take the water molecular (which include three point) as a rigid body ,which one should i use? the lammps doucument make me a little  dazed. for example the document write:
(nparticle: rigid body with N sub-particles )
but next (You should not use body particles to model a rigid body made of simpler particles (e.g. point, sphere, ellipsoid, line segment, triangular particles)

**Comment by akohlmey** [comment]
Please post questions about LAMMPS to the lammps-users mailing list. http://lammps.sandia.gov/mail.html The issue tracker is for reporting problems in the LAMMPS source code.
