### ISSUE TITLE
[BUG] Issues with CD-EAM pair style

### ISSUE THREAD

**Issue by grsmirnov** [lammps/lammps#3074]
**Summary**

There are several bugs in the CD-EAM pair style. This results in incorrect behavior while running multiple simulations from one input file. 
The summary of the bugs is below:
1) The main EAM pair style constructs the index for spline tables as `m = MAX(1,MIN(m,nrho-1))`, while CD-EAM pair style uses  `index.m = index.m <= (nrho-1) ? index.m : (nrho-1)`. The case of `m=0` is undefined in the `PairEAM::interpolate` function, so sometimes CD-EAM functions read garbage from the zero index.
2) The variable `D_i` is not initialized (line 301, MANYBODY/pair_eam_cd.cpp) and we have undefined behavior at line 391.
3) It is necessary to add  `&& rho[j] != 0.0` at line 357 of pair_eam_cd.cpp (like in the `if` condition at line 305). The `ASSERT()` macro does nothing in the current implementation.
I attach the file [patch.txt](https://github.com/lammps/lammps/files/7801872/patch.txt) to fix these isssues. There are also small improvements for better readability of the code. The `ASSERT()` macro was used in the original USER-CD-EAM/pair_cdeam.cpp for debugging purposes. This code is completely lost in the current version. I believe it is safe to remove all the `ASSERT()` calls from the code.

**LAMMPS Version and Platform**

The bugs exist since the first implementation of the USER-CD-EAM package. They are also exist in the latest pair_cd_eam version.

**Expected Behavior**

The same result in single and loop mode simulations.

**Actual Behavior**

The incorrect energies while running LAMMPS in loop mode with `pair_style eam/cd`.

**Steps to Reproduce**
[The simple script to compute the diatom energy vs r.](https://github.com/lammps/lammps/files/7801689/fecr.input.txt)
FeCr.cdeam is from lammps/potentials directory.
Please observe the incorrect energy at 4.2 Å.

**Comment by akohlmey** [comment]
@grsmirnov thanks a lot for your bug report and patch. I have incorporated in PRs #3071 #3029 and added a few more (cosmetic) cleanups on top of it. The change should become public in the next patch release and next update to the stable version.
