### ISSUE TITLE
[Feature Request] GCMC for 2NN MEAM potential

### ISSUE THREAD

**Issue by LiWen-HUST** [lammps/lammps#3077]
**Summary**

GCMC for 2NN MEAM potential

**Detailed Description**

fix gcmc, fix atom/swap and related commands in LAMMPS can solve the MC-MD simulation. However limited potential can be used. MEAM and 2NN MEAM potentials are wide used in alloy systems. It will be really usefull if MC-MD in LAMMPS support MEAM and 2NN MEAM potential.

**Further Information, Files, and Links**

[1] Jang H S, Lee B J. Effects of Zn on< c+ a> slip and grain boundary segregation of Mg alloys[J]. Scripta Materialia, 2019, 160: 39-43.

**Comment by akohlmey** [comment]
@LiWen-HUST Please elaborate on what specific limitations you are talking about, where they are documented, and what kind of errors LAMMPS is producing if you are trying to use the fixes you mention with pair style meam.
I am not aware of any specific issues with the two fixes you mention.

**Comment by akohlmey** [comment]
There has been no response to confirm and document any limitations as requested. Assuming the request is invalid.
