### ISSUE TITLE
ERROR: Unknown body style

### ISSUE THREAD

**Issue by sethbrin** [lammps/lammps#308]
When i use `make serial` to build the project, and run the example which in the dir `example/body`
`../../src/lmp_serial < in.body`, i get the following error
```
LAMMPS (21 Dec 2016)
ERROR: Unknown body style (../atom_vec_body.cpp:96)
```

**Comment by stanmoore1** [comment]
This is not a bug in LAMMPS. This issue should be posted on the LAMMPS mail list, not the GitHub issue tracker, which is only for software bugs and suggestions for enhancements to LAMMPS.
