### ISSUE TITLE
[BUG] MolPairStyle:lj_long_tip4p_long segfaults in v20210929.2 on 32-bit x86

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#3080]
From https://koji.fedoraproject.org/koji/taskinfo?taskID=80961431 in the 32-bit build (https://koji.fedoraproject.org/koji/taskinfo?taskID=80961490):
```
241/475 Test #159: MolPairStyle:lj_long_tip4p_long ....................***Exception: SegFault  6.00 sec
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from PairStyle
[ RUN      ] PairStyle.plain
[       OK ] PairStyle.plain (3280 ms)
[ RUN      ] PairStyle.omp
[buildhw-x86-12:3499508] *** Process received signal ***
[buildhw-x86-12:3499508] Signal: Segmentation fault (11)
[buildhw-x86-12:3499508] Signal code: Address not mapped (1)
[buildhw-x86-12:3499508] Failing at address: 0x53c98718
[buildhw-x86-12:3499508] [ 0] linux-gate.so.1(__kernel_rt_sigreturn+0x0)[0xf7f4e580]
[buildhw-x86-12:3499508] [ 1] /builddir/build/BUILD/lammps-stable_29Sep2021_update2/openmpi/liblammps_openmpi.so.0(+0x1179713)[0xf705a713]
[buildhw-x86-12:3499508] [ 2] /builddir/build/BUILD/lammps-stable_29Sep2021_update2/openmpi/liblammps_openmpi.so.0(+0x1194905)[0xf7075905]
[buildhw-x86-12:3499508] [ 3] /lib/libgomp.so.1(+0x1b53f)[0xf51ba53f]
[buildhw-x86-12:3499508] [ 4] /lib/libc.so.6(+0x8baf1)[0xf5931af1]
[buildhw-x86-12:3499508] [ 5] /lib/libc.so.6(+0x1118cc)[0xf59b78cc]
[buildhw-x86-12:3499508] *** End of error message ***
```

Build log: [build_x86.txt.zip](https://github.com/lammps/lammps/files/7830372/build_x86.txt.zip)

Sorry, I wasn't able to test v20210929.2 before the release.

**Comment by akohlmey** [comment]
@junghans I won't be able to look into this for a while since I won't have the time to set up a suitable 32-bit test environment.
It would be extremely helpful to have a stack trace from an executable with debug info included to have a clue where to look.

I am adding the volunteer needed label for now.
This could be a chance for somebody to gain experience in debugging LAMMPS and tracking down issues.

**Comment by junghans** [comment]
@akohlmey ok I have no direct access to 32-bit hardware either, but I will kick off a debug build on koji shortly.

As the other 32-bit builds (armv7hl and s390x) fail as well [in different tests though], should we just not build 32-bit binary packages for now?

**Comment by akohlmey** [comment]
> As the other 32-bit builds (armv7hl and s390x) fail as well [in different tests though], should we just not build 32-bit binary packages for now?

Yes, it has become a very small user segment so I don't expect any complaints.

**Comment by junghans** [comment]
> Yes, it has become a very small user segment so I don't expect any complaints.

Will do.


64-bit powerpc has a couple of big differences as well:
```
204/476 Test #204: AtomicPairStyle:buck_coul_cut_qeq_point ............***Failed    0.20 sec
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from PairStyle
[ RUN      ] PairStyle.plain
/builddir/build/BUILD/lammps-stable_29Sep2021_update2/unittest/force-styles/test_pair_style.cpp:371: Failure
Expected: (err) <= (epsilon)
  Actual: 3.945511637178746 vs 7.5000000000000004e-13
```
[build_ppc64le.log.txt.zip](https://github.com/lammps/lammps/files/7831493/build_ppc64le.log.txt.zip)

Do we want to look at those as 64-bit powerpc is use in some of the HPC machines or ignore that?

**Comment by akohlmey** [comment]
Tests with QEQ are notoriously unstable. In the development tree they should all be labeled accordingly.

I am very puzzled as to which change is triggering these issues. Either it is something incredibly stupid that I didn't notice or it could be some side effect due to differences in stack sizes or memory alignments creating "wild pointers" and actually something else is corrupting data somehow.

Please note that errors from unit tests are **relative** errors, so if - by chance - there is a small difference for a very small value the error will look larger than it actually is. Test inputs are designed so that the resulting forces and stresses will usually be sufficiently large, but it is not always given.  Ideally there would be a second threshold that switches between relative and absolute error depending on the value that is being compared.

**Comment by stanmoore1** [comment]
>Do we want to look at those as 64-bit powerpc is in use in some of the HPC machines or ignore that?

If it fails on Power9 (e.g. OLCF Summit) then I care...

**Comment by junghans** [comment]
There are all the tests that failed ppc64le:
```
        104 - MolPairStyle:hybrid-scaled (Failed)
        204 - AtomicPairStyle:buck_coul_cut_qeq_point (Failed)
        205 - AtomicPairStyle:buck_coul_cut_qeq_shielded (Failed)
        222 - AtomicPairStyle:edip (Failed)
        227 - AtomicPairStyle:kim_lj (Failed)
        231 - AtomicPairStyle:meam_sw_spline (Failed)
        234 - AtomicPairStyle:reaxff (Failed)
        235 - AtomicPairStyle:reaxff_lgvdw (Failed)
        236 - AtomicPairStyle:reaxff_noqeq (Failed)
        237 - AtomicPairStyle:reaxff_tabulate (Failed)
        248 - ManybodyPairStyle:bop_save (Failed)
        251 - ManybodyPairStyle:drip (Failed)
        252 - ManybodyPairStyle:drip_real (Failed)
        257 - ManybodyPairStyle:ilp-graphene-hbn (Failed)
        258 - ManybodyPairStyle:ilp-graphene-hbn_notaper (Failed)
        259 - ManybodyPairStyle:kolmogorov_crespi_full (Failed)
        263 - ManybodyPairStyle:lebedeva_z (Failed)
        269 - ManybodyPairStyle:mliap_so3 (Failed)
        276 - ManybodyPairStyle:rann (Failed)
        385 - FixTimestep:momentum (Failed)
        457 - DihedralStyle:quadratic (Failed)
        459 - DihedralStyle:table_cut_linear (Failed)
        461 - DihedralStyle:table_linear (Failed)
```

@stanmoore1 see the attached build log above.

**Comment by junghans** [comment]
And yup koji is a power9 machine as well:
```
CPU info:
Architecture:                    ppc64le
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Model name:                      POWER9 (architected), altivec supported
Model:                           2.2 (pvr 004e 1202)
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       8
Hypervisor vendor:               KVM
Virtualization type:             para
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; RFI Flush, L1D private per thread
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Mitigation; RFI Flush, L1D private per thread
Vulnerability Spec store bypass: Mitigation; Kernel entry/exit barrier (eieio)
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization, ori31 speculation barrier enabled
Vulnerability Spectre v2:        Mitigation; Software count cache flush (hardware accelerated), Software link stack flush
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
```

**Comment by akohlmey** [comment]
> There are all the tests that failed on ppc64le:

@stanmoore1 almost all of them are known to be somewhat unstable for the kind of testing that is done in the force-style folder.
This applies to potentials using tabulation, especially spline tables, interlayer potentials, and charge equilibration. With those some properties that are tested for are ultra-sensitive to the tiniest changes, e.g. when switching platforms and/or compilers.

In the develop branch there is now a tag "unstable" that can instruct the ctest tool to skip those.

**Comment by stanmoore1** [comment]
OK good to know

**Comment by junghans** [comment]
> > There are all the tests that failed on ppc64le:
> 
> @stanmoore1 almost all of them are known to be somewhat unstable for the kind of testing that is done in the force-style folder. This applies to potentials using tabulation, especially spline tables, interlayer potentials, and charge equilibration. With those some properties that are tested for are ultra-sensitive to the tiniest changes, e.g. when switching platforms and/or compilers.
> 
> In the develop branch there is now a tag "unstable" that can instruct the ctest tool to skip those.

Did the labels made it in to the stable release as well?

**Comment by akohlmey** [comment]
> Did the labels made it in to the stable release as well?

No.

**Comment by junghans** [comment]
Too bad, hopefully in the next stable version.

I will just use:
```
ctest ----exclude-regex "\(MolPairStyle:hybrid-scaled\|AtomicPairStyle:buck_coul_cut_qeq_point\|AtomicPairStyle:buck_coul_cut_qeq_shielded\|AtomicPairStyle:edip\|AtomicPairStyle:kim_lj\|AtomicPairStyle:meam_sw_spline\|AtomicPairStyle:reaxff\|AtomicPairStyle:reaxff_lgvdw\|AtomicPairStyle:reaxff_noqeq\|AtomicPairStyle:reaxff_tabulate\|ManybodyPairStyle:bop_save\|ManybodyPairStyle:drip\|ManybodyPairStyle:drip_real\|ManybodyPairStyle:ilp-graphene-hbn\|ManybodyPairStyle:ilp-graphene-hbn_notaper\|ManybodyPairStyle:kolmogorov_crespi_full\|ManybodyPairStyle:lebedeva_z\|ManybodyPairStyle:mliap_so3\|ManybodyPairStyle:rann\|FixTimestep:momentum\|DihedralStyle:quadratic\|DihedralStyle:table_cut_linear\|DihedralStyle:table_linear\)"
```

this time.

**Comment by junghans** [comment]
Not beautiful but packages are done:
https://src.fedoraproject.org/rpms/lammps/blob/24b5bf5fda789d195cace47e11b4f5fa397069e1/f/lammps.spec#_228-244

Let's leave the issue open due to the segfault on i686.

**Comment by akohlmey** [comment]
@junghans @rbberger could you trigger a compilation/test run on the 32-bit platforms for the development branch and check whether the 32bit segfaults are limited to the stable branch?

**Comment by akohlmey** [comment]
For the record, I have been - so far - unable to reproduce the segfault with a 32-bit ubuntu in a virtual machine with either develop or stable branch. What is odd on Fedora 35: attempting to install 32bit compiler support forces the compiler and dependent packages to be downgraded from 11.2.1-7 to 11.2.1-1 and trying to build a singularity images creates problems because there doesn't seem to be an i686 equivalent to the gcc package available and not installing it results in errors due to missing files.

**Comment by junghans** [comment]
On any 64-bit Fedora you should be able to build the 32-bit package with something like:
```
dnf install fedpkg
fedpkg -a lammps
cd lammps
usermod -a -G mock <username>
spectool -g lammps.spec
fedpkg srpm
mock -r fedora-rawhide-i386 --forcearch i386 --dnf --init
mock -r fedora-rawhide-i386 --forcearch i386 --dnf --no-clean lammps*.src.rpm
```

**Comment by rbberger** [comment]
Just some corrections for later reference. The above fails. You can't force i386 for everything, because mock will fail with missing dependencies.
```
dnf install fedpkg
fedpkg co lammps
cd lammps
usermod -a -G mock <username>
spectool -g lammps.spec
fedpkg srpm
mock -r fedora-rawhide-i386 --dnf --init
mock -r fedora-rawhide-i386 --dnf --no-clean lammps*.src.rpm
```

**Comment by junghans** [comment]
You are right for the `--forcearch` is obsolete and now auto-detected from the `-r` environment, but for people without a FAS account one still need the `-a` option after `fedpkg clone`.

**Comment by rbberger** [comment]
Can not reproduce. I've tried it with mock and with a vanilla 32bit VM.

**Comment by akohlmey** [comment]
@junghans there has been no followup on this and nobody seems to be able to reproduce this independently. I will close this now. To re-open we need a way to confirm this independently so that we can track it down.

**Comment by junghans** [comment]
It is gone in master, so we fixed it somehow.
