### ISSUE TITLE
[BUG]cmake/Modules/FindCythonize.cmake hardcodes python version 3.6 when other places don't

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#3098]
[Here](https://github.com/lammps/lammps/blob/develop/cmake/Modules/FindCythonize.cmake#L16) ```find_package``` looks for specific python version 3.6, but in other similar places it doesn't.

**Comment by akohlmey** [comment]
No it does not require specifically Python 3.6, it requires a version **compatible** with Python 3.6. This typically means 3.6 or later. To only specifically require **only** require version 3.6, the additional keyword `EXACT` would be required.
Please see the cmake documentation for the `find_package()` command for additional details.
