### ISSUE TITLE
Bond/break issue

### ISSUE THREAD

**Issue by Revanth9727** [lammps/lammps#3107]
**Summary**

**LAMMPS Version and Platform**

[test1.txt](https://github.com/lammps/lammps/files/7974306/test1.txt)

**Comment by Revanth9727** [comment]
The bond/break is not working as expected as it only takes in the last few command sets of the bond/break and bond/create

**Comment by mkanski** [comment]
This is an expected behaviour. You are using the same fix names, so the fixes are replaced. If you want multiple `fix bond/break` to be active during a run, they must have different names.
