### ISSUE TITLE
[BUG] FEP examples incorrect dlambda charges

### ISSUE THREAD

**Issue by bsikora** [lammps/lammps#3108]
I could be incorrect in assuming this, but I believe the input files for the FDTI and FEP examples are incorrect for the 1-0 transformations. The input file sets dlambda to a negative value (which is correct), but then proceeds to multiple the charge by said value. If I am not mistaken, you are then switching the charge on said atom during the perturbation cycle. The charge on the atom should be perturbed by a slight amount, but the charge sign should remain the same. In the current format I don't believe this is occurring.

https://github.com/lammps/lammps/tree/develop/examples/PACKAGES/fep

Example: https://github.com/lammps/lammps/blob/develop/examples/PACKAGES/fep/CH4hyd/fep10/in.fep10.lmp

**Comment by agiliopadua** [comment]
I think you are incorrect. In the lambda 1->0 transformation, we want the charges to be perturbed towards zero, and so the perturbation dlambda < 0. As such, a dq_i = q_i * dlambda < 0 is added to positive charges and a dq_i > 0 is added to negative charges. Have you checked the tests included, or tried your version with an example?

**Comment by bsikora** [comment]
You are correct. I misread the FEP command as setting rather than adding to. In this regard your delta charge will want an opposite side. Thanks!
