### ISSUE TITLE
[BUG] hybrid sw lj/cut produces nan thermo data when using GPU package

### ISSUE THREAD

**Issue by mppotter** [lammps/lammps#3109]
**Summary**

Using the gpu package with `pair_style hybird sw/gpu lj/cut/gpu` produces erroneous thermo data and/or cuda driver errors. Unlike #2621, this issue is not fixed by using the "-pk gpu 0 neigh no" flag.

**LAMMPS Version and Platform**

LAMMPS commit https://github.com/lammps/lammps/commit/76c57d54c16cf6ec9c45b39159a30f30313f6395 
Red Hat Enterprise Linux 8.4
CUDA Toolkit 11.0
IBM Power 9 processor @ 3.15 GHz, NVIDIA Tesla V100 GPU w/ 32 GiB mem

**Expected Behavior**

The simulation should produce reasonable thermodynamic data (as it does without the GPU package flags).

**Actual Behavior**

The thermo data is returned as either `nan`, or some arbitrarily large number.

**Steps to Reproduce**

Run the attached script (with the attached files in the same directory) using `mpirun -np 4 ~/lmp -sf gpu -pk gpu 0 neigh no -in in.issue.txt`.

**Further Information, Files, and Links**

The thermo output seems to depend on the N in `-np N`. For N=4, thermo data is `nan`, but for N=1, LAMMPS raises a Lost Atom error without the `nan` thermo data.
[GeSi.sw.txt](https://github.com/lammps/lammps/files/7980673/GeSi.sw.txt)
[Gr.data.txt](https://github.com/lammps/lammps/files/7980674/Gr.data.txt)
[in.issue.txt](https://github.com/lammps/lammps/files/7980735/in.issue.txt)

**Comment by ndtrung81** [comment]
@mppotter Thanks for reporting the issue, which I can reproduce on my side. Will take a look at it.

**Comment by ndtrung81** [comment]
I have tested the given input deck with lammps-patch_10Feb2021, and note that the reported issues do not show up. They could be due to the substantial changes to the sw/gpu pair style (and the related code in the GPU library) introduced since lammps-patch_10Mar2021.
