### ISSUE TITLE
Bond create and break issue

### ISSUE THREAD

**Issue by Revanth9727** [lammps/lammps#3112]
I have three different types of atoms and three different types of bond types, which are used for each atom type. But the number of bonds attached is way less than the number of bonds that are broken, so by the end of the simulation I am left with only particles. 
Could you help me with this?
[test1.txt](https://github.com/lammps/lammps/files/7982599/test1.txt)

**Comment by akohlmey** [comment]
This is not the right place to post such requests and questions. Please post your message in either the [LAMMPS category of the MatSci forum](https://www.lammps.org/forum.html) or the [lammps-users mailing list](https://www.lammps.org/mail.html).
Before posting, please read the corresponding documentation of the commands in the LAMMPS manual **very** carefully, especially the notes about limitations and restrictions.
