### ISSUE TITLE
How to extract the unconvected coordinates and the peculiar velocities in a shear flow system-LAMMPS

### ISSUE THREAD

**Issue by georgiamp** [lammps/lammps#3137]
Currently, I experiment with a molecular water system. I perform nonequilibrium molecular dynamics runs in LAMMPS, using the SLLOD equations of motion in conjunction with the Lees-Edwards periodic boundary conditions. 
I perform NEMD simulationS for several shear rate values under the NVT ensemble to reach a steady-state. After
the system reaches a nonequilibrium steady state, I want to compute the diffusion coefficient by two different
techniques: either the Green-Kubo relations (which relate integrals of the momentum autocorrelation functions over the nonequilibrium steady-state to the diffusion coefficients directly); or the Einstein relations (which relate the unconvected mean
square displacements of the molecules at time t to products of the diffusion coefficients and t); To do so, the unconvected coordinates and the SLLOD peculiar momenta must be used.

I have understood that using the command 
dump traj_dump all custom 1 file.lammpstrj id mol element type xu yu zu x y z vx vy vz fx fy fz
the convected coordinates, and the actual momenta are printed out, i.e., the terms corresponding to the external force are included.

I wonder if there is any way of directly extracting the unconvected coordinates and the peculiar velocities of the atoms every N timesteps. Are there any specific commands that I can use?

Below is the input script that I use, setting the nonequilibrium run simulation.
I really appreciate any help you can provide.

units real
atom_style full
log 
dimension 3
boundary p p p

read_data restart_file
pair_style lj/cut/coul/long 10 10
kspace_style ewald 1.0e-4
pair_modify tail yes
pair_coeff 1 1   0.155297  3.16562
pair_coeff 2 2   0.0   0.000
pair_modify mix arithmetic
bond_style harmonic
bond_coeff 1 412.00935 1.0

angle_style harmonic
angle_coeff 1 45.739 109.47

special_bonds lj 0.0 0.0 0.0 coul 0.0 0.0 0.0

reset_timestep 0

neighbor 3.0 bin
neigh_modify every 1 delay 0 check yes

variable shear_rate index ${shear_rate}

fix integrator all nvt/sllod temp 300.0 300.0 100.0 		# check thermostat
fix 2 all deform 1 xy vel ${shear_rate} remap v units box

dump traj_dump all custom 100 traj_${simname}.lammpstrj id mol element type xu yu zu x y z vx vy vz fx fy fz
dump_modify traj_dump sort id

run_style verlet
timestep	1
run	      100000

**Comment by akohlmey** [comment]
Please post questions like this to the LAMMPS forum on matsci.org or the lammps-users mailing list. This is not the correct place for them.
