### ISSUE TITLE
Can LAMMPS use the potential made by VASP 6.3?

### ISSUE THREAD

**Issue by LZYUCL** [lammps/lammps#3143]
After the newly updated, **_VASP 6.3_** has the ability to build potential using machine learning method. Can LAMMPS use the potential (for example: **ML_AB, ML_FF**) from VASP? 
Thank you!

**Comment by akohlmey** [comment]
This is not the right place to ask this kind of question. Please post it to the MatSci.org forum or the lammps-users mailing list.
