### ISSUE TITLE
Log parsing and plotting in python 2

### ISSUE THREAD

**Issue by aliehlen** [lammps/lammps#3151]
**Summary**

I am new to lammps and went to use the log parsing/plotting tools, specifically the files logplot.py and log2txt.py in lammps/tools/python/. Most of these tools are written in python 2 and some are called in a way that doesn't work on linux systems. I have a few commits that fix this, and I wanted to ask if I should open a PR for those.

**LAMMPS Version and Platform**

I'm on commit 7ea26161 and running this on Fedora 35.

**Details**

I have 3 commits that I can submit as a PR but I first wanted to run them by you to make sure they are all reasonable. This is what's included:
1. The scripts are in python 2, so they need upgrading. They also have some confusing variable names (`list` and `map`), so I have fixed those, too. However, I have upgraded only logplot.py and log2txt.py. Is it okay to submit an upgrade to just some of the scripts in this folder?
2. logplot.py calls python using `#!/usr/bin/env python -i`, which I can't get to work in linux, so I removed the -i so that it can run (non-interactively) in linux. Is that okay?
3. log2txt.py also creates a file of unnamed columns. In all use cases I can think of, it's preferable to also include column names so that humans or plotting software can more easily read it later. I would also propose to write out column names, but if you don't think that's a generally useful change, I can keep that in my own version.

**Comment by akohlmey** [comment]
@aliehlen it would be better if you just submitted a pull request (and used the drop down list to switch from regular to draft pull request). we can discuss the details based on your changes while looking at them and that makes it easier to make suggestions.
