### ISSUE TITLE
[BUG] Per-atom virials (stress) not correct with LJ/Class2

### ISSUE THREAD

**Issue by rayshan819** [lammps/lammps#3157]
**Summary**

The per-atom virials with LJ/Class2 is not correct and the symptom is a different pressure computed from reduced compute stress/atom. 

**LAMMPS Version and Platform**

LAMMPS version is 7Jan22, built with Intel MPI, executed on CentOS Linux with 1 MPI rank.

**Expected Behavior**

The expected behavior is that the pressure calculated from the reduced compute stress/atom should equal to the thermo_style press keyword:

compute                 peratom all stress/atom NULL
compute                 p all reduce sum c_peratom[1] c_peratom[2] c_peratom[3]
variable.                 press equal -(c_p[1]+c_p[2]+c_p[3])/(3*vol)

thermo_style         custom step pe temp etotal press v_press

But the last two columns differ with LJ/Class2

**Steps to Reproduce**

Please run the attached input deck to reproduce the issue, thanks.

[lj_class2_stress_bug.zip](https://github.com/lammps/lammps/files/8163950/lj_class2_stress_bug.zip)

**Comment by akohlmey** [comment]
@rayshan819 I am not convinced that this is a bug. It could be a manifestation of the limitations of floating point math.
Stress is particularly sensitive since the individual contributions vary a lot in magnitude.

If there was a bug it would apply to **all** pairwise additive potentials (lj/cut, morse, etc.) since the virial stress is derived from forces and forces have been validated for a lot of those pair styles.

**Comment by stanmoore1** [comment]
The virial stress is not derived from the forces if the per-atom stress is computed, there are two different code paths.

**Comment by stanmoore1** [comment]
To clarify, I mean the code only uses `virial_fdotr_compute` if the per-atom stress is not computed.

**Comment by athomps** [comment]
I could see how something special (and wrong) might be happening for LJ/Class2.  In the case of perf-atom stress, it sends ij, ijk, and ijkl forces to tally functions.  Probably the global stress is right and the per-atom is wrong.

**Comment by athomps** [comment]
The fix numdiff/virial would help settle the question of which is correct, if either.

**Comment by akohlmey** [comment]
> I could see how something special (and wrong) might be happening for LJ/Class2. In the case of perf-atom stress, it sends ij, ijk, and ijkl forces to tally functions. Probably the global stress is right and the per-atom is wrong.

But it would not apply to the pair style, right?

**Comment by akohlmey** [comment]
The explanation is much simpler. The input had "pair_modify tail yes". That is only applied to the global stress. Hence the difference.

**Comment by akohlmey** [comment]
documented in https://docs.lammps.org/compute_stress_atom.html

**Comment by rayshan819** [comment]
Thank you, Axel, Stan, and Aidan for your comments. 

Thanks to Axel for pointing out the culprit!  I forgot about checking the tail correction.

Many thanks,
Ray
