### ISSUE TITLE
fmtlib workaround no longer required

### ISSUE THREAD

**Issue by joeatodd** [lammps/lammps#3160]
**Summary**

There's a [workaround](https://github.com/lammps/lammps/blob/798975b8090c5cc41b434ebcbe4baa59aa395701/src/fmt/format-inl.h#L1009-L1017) for [this bug](https://github.com/intel/llvm/issues/4048) which has recently been [fixed](https://github.com/intel/llvm/pull/4257). As such, the workaround should no longer be required with the tip of DPC++.

@akohlmey

**Comment by akohlmey** [comment]
Thanks for letting us know. I will keep that in mind the next time I update the fmtlib code.
