### ISSUE TITLE
fix nve/body

### ISSUE THREAD

**Issue by Tron-x** [lammps/lammps#317]
when i use body module，at end I use fix all nev/body ,but the total energy is nonconservation of energy
the in file is
![qq 20170103123022](https://cloud.githubusercontent.com/assets/7659413/21599985/7001f614-d1b0-11e6-8ce3-dac0df0b30a9.png)
the result is

![qq 20170103122848](https://cloud.githubusercontent.com/assets/7659413/21599998/95296896-d1b0-11e6-8bb7-d17f18f1efbf.png)

so is this module not well completed?

**Comment by akohlmey** [comment]
Please post questions about using LAMMPS correctlyl to the lammps-users mailing list. http://lammps.sandia.gov/mail.html
The issue tracker is for reporting problems in the LAMMPS source code.

**Comment by Pakketeretet2** [comment]
Maybe we should mention this in the tutorial and/or on github? A note that
says that if people think there's a bug, they first discuss it in the
mailing list, and if it is ruled as a bug, they or the developers file a
bug report?

**Comment by akohlmey** [comment]
I wanted to look into using a template for github issues, that asks necessary questions and explains what to report and how. Adding a comment about is likely to be counterproductive. In my personal experience, people who are struggling tend to see such "do not do this" remarks as encouragement exactly do what they should not do, as they have already run out of any other ideas.
