### ISSUE TITLE
[Feature Request] Enforce precise fractions/atom counts with `delete_atoms porosity`

### ISSUE THREAD

**Issue by mjclarke94** [lammps/lammps#3249]
The recent closing of #1425 made me realise I missed out a key aspect of the use case I mentioned there. The ability to use the `delete_atoms porosity` command on a group of atoms is extremely useful (thanks for implementing!), but this bit can be a deal breaker for the use case I was looking at:

> There is no guarantee that the exact fraction of atoms will be deleted, or that the same atoms will be deleted when running on different numbers of processors.

When modelling ion migration through Li-ion batteries, we may choose to charge compensate the removal of some fraction of the Li ions with some number of other defects to compensate (Schottky-pairs). If we are unable to ensure that an exact count/fraction of atoms is being deleted, then we are relying on luck to have the simulation be charge neutral after multiple deletion operations. If this constraint isn't met, the simulation obviously crashes.

I appreciate that enforcing this constraint may be slower so would not suggest it be included as default behaviour. Instead, I suggest the inclusion of an optional `precise` flag. When on, a check that the requested fraction leads to an integer number of atoms `n` being deleted should be performed, and then a `select_without_replacement(size(group),  n , seed)` type calculation could be used to both ensure that the deletion operation is consistent across system architectures/processor counts and can be reliably used to generate charge-neutral systems. (apologies for the pseudo-code!)

The absence of this feature usually required me to either pre-generate my inputs outside of lammps (leading to a large number of sizeable input files) which could instead have simply been replaced with the programmatic generation of my system and a single seed variable being passed in to `lmp_serial` to run several calculations of the same type with the same single file.

I appreciate this is achievable already, but the code required to do so can be quite unfriendly for new users and I imagine it is feature which would be commonly used if made available.

Happy to discuss further if helpful!

**Comment by akohlmey** [comment]
@mjclarke94 a few comments.

> The absence of this feature usually required me to either pre-generate my inputs outside of lammps (leading to a large number of sizeable input files)

Input files? How? You would just need to create a single data file per run with the desired geometry.
It is a deliberate choice that LAMMPS does not implement complex model/system building procedures. There are better tools for that. If necessary those can be invoked from LAMMPS using the shell command.

Another option to do complex operations is to use the python interface where you can easily query the state of a system and do loops and randomized operations and much more. A straightforward approach could be to create a system without regard to charge neutrality and then run a small script to correct the charge imbalance by deleting suitably selected atoms.

It would probably also be possible to do the same without python scripting and just some loop and by defining a suitable atom style variable to delete a few selected atoms for charge neutrality that way.

>  I imagine it is feature which would be commonly used

Commonly used among a rather small segment of LAMMPS users.

**Comment by mjclarke94** [comment]
> How?

If I'm just interested in relatively simple structures (so no grain boundaries etc), then a manually creating a unit cell and using the `duplicate` command gets me a supercell as a starting point in a few lines. Your suggestion of using python is how I generally achieved the introduction of defects programatically to avoid having a 100k atom input file I needed to store somewhere for each simulation (before I started using Aiida that is...), but this additional option could have made it a oneliner and effectively embedded the information about the structure in the input file.

I should probably say that "Feature Request" might be overselling the need for this by a few orders of magnitude! The absence of this feature just happens to be something which occasionally irritated me in my early days of using LAMMPS so figured I'd document it here in case you happen to be making tweaks to the function anyway. I can't imagine it not being implemented will be particularly devastating.

> Commonly used among a rather small segment of LAMMPS users.

Fair point.

**Comment by akohlmey** [comment]
I am still confused by your mention of large input files. A data file for 100k atoms is not much these days, even if you need many of them. Also you can compress those files and read the compressed files, if storage is that dear. The simulation output is usually much more than that. Also, those would be temporary.

I suggest you have a closer look at tools like Atomsk or Packmol. Those are much more suited to build complex systems than LAMMPS.

If it was just me, I would attach a "wontfix" label and close it right now, but I let @sjplimp give his opinion as well.

**Comment by mjclarke94** [comment]
Perhaps "large" is not the best description. If presented with a 100k atom structure, we can work out some things about it (counts of each atom type etc.) but the provenance of _how_ we arrived at that structure is not there. By having the procedure of generating the structure embedded in the simulation itself, we have all the information required to replicate a given study embedded in one location. Something along the lines of
```
box ...
...
replicate 10 10 10
group Li type 1
group Cl type 2
delete_atoms Li NULL 0.01 12345
delete_atoms Cl NULL 0.03 67890
```
Tells me at a glance that I am simulating a supercell with 1% of Li atoms removed, compensated by the removal of 3% of Cl sites. The equivalent code where I just input the pre-generated structure lacks this context and can make it tricky for people looking at the code later to understand what is going on.

**Comment by akohlmey** [comment]
This is still possible with an external tool, if invoked from your LAMMPS input. A simple demonstration:
```
print """
print("Hello from python!")
""" file hello.py screen no

shell python hello.py
```

**Comment by sjplimp** [comment]
Actually, there is recent functionality in LAMMPS that could be leveraged to do this.  Look at the set command doc
page for type/fraction, type/ratio, type/number.  The latter two are new options which pick a random exact number of atoms
to operate on.  This uses a select_subset() method we added to random_mars.cpp.  It iteratively selects atoms randomly
until it reaches the exact requested number.  I think we just need to enable the same thing for the delete_atoms command.
I can submit a PR for this.

**Comment by sjplimp** [comment]
One wrinkle I should mention.  Use of select_subset() means the which atoms are selected will vary with the number of procs being used.  I.e, if you run the same simulation on 1 proc vs 10 procs, using the same random number seed in the delete_atoms command, a different subset of atoms will be deleted.  That is also true of the current inexact delete_atoms porosity.  But it is not true of the inexact set type/fraction.  Is that a problem?
