### ISSUE TITLE
[BUG] _Segmentation fault when witting dump file for atoms in a dynamic group_

### ISSUE THREAD

**Issue by gedska** [lammps/lammps#3270]
**Summary**

This system does not make much sense; however, it helps me to reproduce the bug somewhat consistently. The system consists of a liquid drop placed in the middle of the simulation box prolonged in z axis.

5 dynamic groups are defined within the simulation. NVT_group group contains atoms in the drop and near the drop and is run in NVT ensemble to control the temperature of the system. Atoms, which evaporate into -z direction and cross boundary z = -45 Å, are assigned to group vacuum_group_1. Atoms evaporating into +z direction and crossing boundary z = 65 Å are assigned to group vacuum_group_2. Every 200 simulation steps, atoms in group vacuum_group_1 are relocated to position z = 65 Å using command "set". In same manner, atoms in group vacuum_group_2 are relocated to position z = -45 Å. To resolve the issue of overlapping due to the atom relocations, the atom dynamics near relocated regions (z = -45 Å and z = 65 Å) are solved using NVE/limit.

Such system is steady and works without a problem; however, when I try to write data to dump files for groups vacuum_group_1 and vacuum_group_2 to register the information of relocated atoms before their relocation, the simulation process stops at random iteration of the process due to segmentation fault.

When running in serial, the simulation process stops with message:
Segmentation fault

Meanwhile the process termination message for parallel run is:
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 3406 RUNNING AT DESKTOP-K78ILQN
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**LAMMPS Version and Platform**
Lammps serial and mpi executables (version LAMMPS (29 Sep 2021 - Update 3)) were compiled with make. I run lammps on a HP Z840 Workstation (Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz   2.50 GHz  (2 processors)) in WSL environment (in Windows 10).

**Expected Behavior**
Atoms in groups vacuum_group_1 and vacuum_group_2 should be relocated to their new places in the other side of the drop every 200 timesteps. Since the dynamics of atoms in regions, into which the atoms are relocated, are solved with NVE/lim, the issue of overlapping should be resolved and the the system should be stable for the whole simulation length. Furthermore, the information of relocated atoms should be written into dump files before they are relocated.

**Actual Behavior**
The process stops at random relocation iteration of the simulation when the dump files are ordered for dynamic groups vacuum_group_1 and/or vacuum_group_2.

**Steps to Reproduce**
This issue is reproduced  with the attached input file either when I run in serial or in parallel. The line that I run in serial is:
lmp_serial -in input_main.txt

and in parallel using N cores is:
mpirun -np 12 lmp_mpi -in input_main.txt

I would like to note that this segmentation fault issue happens at random iteration of the relocation process and the simulations finished without the issue on rare occasions. However, the simulations are terminated most of the time.

Input file:
[input_main.txt](https://github.com/lammps/lammps/files/8718535/input_main.txt)

**Comment by akohlmey** [comment]
@gedska please check whether turning off sorting of the dump files avoids the segfaults.

**Comment by akohlmey** [comment]
It looks like commit bfd6efcedb785e42adf4e4066aee9b86c06dad05 avoids any memory access issues that I see with your example input deck and the latest development sources.

**Comment by gedska** [comment]
I have downloaded the Latest patch release (LAMMPS (4 May 2022)) from LAMMPS website. I have also modified dump.cpp file according to the commit before compiling LAMMPS.

dump.cpp file lines 418-422:
  if (sort_flag && sortcol == 0) pack(ids);
  else pack(nullptr);
  if (sort_flag) sort();
  if (sort_flag && ntotal > 1) sort();
  if (balance_flag) balance();

If I leave dump sorting option on in the input file, I run into segfault in the first iteration of the run with the new LAMMPS executable.
If I comment out the dump sorting option lines in the input file, The segfault seems to disappear when running LAMMPS with both old and new executables.

**Comment by gedska** [comment]
I tested both the serial and mpi executables.

**Comment by akohlmey** [comment]
Your change was not correct. You are still calling the sort function for cases that corrupt memory. You would need:
> if (sort_flag && sortcol == 0) pack(ids);
> else pack(nullptr);
> if (sort_flag && ntotal > 1) sort();
> if (balance_flag) balance();

Or better yet:
>  if (sort_flag && (ntotal > 1) && sortcol == 0) pack(ids);
>  else pack(nullptr);
>  if (sort_flag && (ntotal > 1)) sort();
>  if (balance_flag && (ntotal > 1)) balance();

**Comment by gedska** [comment]
I made the suggested change:

  if (sort_flag && (ntotal > 1) && sortcol == 0) pack(ids);
  else pack(nullptr);
  if (sort_flag && (ntotal > 1)) sort();
  if (balance_flag && (ntotal > 1)) balance();

After compiling the executable, the problem seems to be solved even with sorting option on (at least for the 10 times I ran the input file to test).

Thank you for your time. It helped me a lot.
