### ISSUE TITLE
[BUG] Segfault in FixPropertyAtom::grow_arrays

### ISSUE THREAD

**Issue by martok** [lammps/lammps#3287]
**Summary**

In MPI parallel runs, using `create_atoms` twice in a specific way can cause a segfault in `fix property/atom` 's `grow_arrays`. Although this is where it happened to me, I actually think that something before that point is already off the rails.

**LAMMPS Version and Platform**
`Stable 29 Sep 2021 - Update 3 -- 6fd8b2b1772`
also reproduced with `Unstable 4 May 2022 -- bd4bbbddb`

**Steps to Reproduce**

Run this input with at least 2 mpi processes: `mpirun -np 2 lmp_mpi -i test.lmp`:
[test.lmp.txt](https://github.com/lammps/lammps/files/8825457/test.lmp.txt)

Output will be similar to this (minus 2 debug statements, see below) with a segfault at the last command.
[test.log.txt](https://github.com/lammps/lammps/files/8825468/test.log.txt)

The first `create_atoms` goes through fine, but overestimates how many atoms it will create per process by the `LB_FACTOR`. `AtomVec->roundup` pads to a nearest page size, `FixPropertyAtom::grow_arrays` allocates that 10% too many entries.

The second `create_atoms` does not create atoms on one proc, therefore realizes (`nadd=0`, only `atom->nlocal` counts) that it actually has less atoms than assumed in the last call. In this case, `AtomVec->roundup` also rounds to a *lower* granularity than before. This results in a `grow_arrays` call that is actually shrinking the vectors. An integer underflow finally causes the segfault.

This basically can be triggered whenever a second create_atoms lattice call creates less than 10% of the amount of the first call in a domain (and this is not hidden by lucky rounding).

Since basically no `grow_*` call along this path looks like it expects shrinking, catching this in the fix seems not the correct place?

**Comment by akohlmey** [comment]
Yes, the `grow*()` functions should never allow nmax to shrink. So a change like the following should address the issue.
```
  diff --git a/src/atom_vec.cpp b/src/atom_vec.cpp
  index deff0cfd58..dbacf2237a 100644
  --- a/src/atom_vec.cpp
  +++ b/src/atom_vec.cpp
  @@ -207,7 +207,7 @@ void AtomVec::grow(int n)
     if (n == 0)
       grow_nmax();
     else
  -    nmax = n;
  +    nmax = MAX(n,nmax);
     atom->nmax = nmax;
     if (nmax < 0 || nmax > MAXSMALLINT) error->one(FLERR, "Per-processor system is too big");
   
```

@sjplimp do you agree?

**Comment by martok** [comment]
That would make sense (and it fixes the issue).

Alternative maybe slightly more explicit variant:
```diff
diff --git a/src/atom_vec.cpp b/src/atom_vec.cpp
index 5ebaf41ebb..48e37d1534 100644
--- a/src/atom_vec.cpp
+++ b/src/atom_vec.cpp
@@ -205,6 +205,7 @@ void AtomVec::grow(int n)
   void *pdata;

   if (n == 0) grow_nmax();
+  else if (n <= nmax) return;
   else nmax = n;
   atom->nmax = nmax;
   if (nmax < 0 || nmax > MAXSMALLINT)
```

**Comment by akohlmey** [comment]
> Alternative maybe slightly more explicit variant:

I had thought of that one first, but discarded it as too risky. If any of the calls down in the function does a collective MPI call, you would get a deadlock.

**Comment by martok** [comment]
> I had thought of that one first, but discarded it as too risky. If any of the calls down in the function does a collective MPI call, you would get a deadlock.

Hm, true. Doesn't seem to be the case in my tests, but that doesn't mean anything.
