### ISSUE TITLE
[Feature Request] Two-Body-Only Stillinger-Weber Potential

### ISSUE THREAD

**Issue by jkelowitt** [lammps/lammps#3297]
**Summary**

Create a new pair style for a two-body-only Stillinger-Weber potential to avoid the slow down of calculating a three-body term which will always equal zero. 

**Detailed Description**

My group has a several models which use the Stillinger-Weber potential with `lambda=0`. Some examples include a water-methane model (1), a coarse grain model of silica (2), and some solvent-tetramethylammonium models (3). 

These models have a significant number of two-body-only SW interactions. They run slower than necessary due to `sw` computing a three-body term which will always equal zero. 

In order to speed things up, we created an in-house version of `sw` called `sw0`, which removes the entirety of the three-body loop. This results in significant speed ups of ~8x for highly two-body simulations.

We had also tested a one-line change to the `sw` style to try to speed up the three-body term without writing a whole new pair style. This line was added near the top of the three-body loop of `sw` to skip unnecessary calculations:
```cpp
if params[ijkparam].lambda == 0 continue;
```
This modification resulted in a ~5x speed improvement for highly two-body simulations over `sw`. It also caused a ~1.5% speed *decrease* in normal three-body Stilllinger-Weber simulations over `sw`. We considered these performance decreases over `sw0` to be unacceptable for our uses. 

For this reason, I'd like to submit a new pair style, `sw/2b`, which will compute only the two-body term of the Stillinger-Weber potential. 

**Further Information, Files, and Links**

(1) J. Phys. Chem. B 2010, 114, 21, 7302–7311
(2) J. Phys. Chem. C 2021, 125, 48, 26857–26868
(3) J. Chem. Theory Comput. 2017, 13, 1, 245–264

**Comment by akohlmey** [comment]
@jkelowitt I think a new pair style would be overkill in this case. The same effect can be achieved with a keyword that then make the sw pair style skip the call to the "threebody()" function when that keyword is set

**Comment by jkelowitt** [comment]
I like that idea a lot. My issue is that it would have to skip the whole three body loop, rather than just the "threebody()" call, to reach the speeds of the individual pair style. 

I'm also a little concerned about mixing three-body SW with two-body SW. For example if I had this potential file:

```
#           eps    sig     a     *lam*   gam   cos          A            B            p  q    tol
mW  mW  mW  6.189  2.3925  1.8   23.15   1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
xL  xL  xL  0.34   4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
mW  xL  xL  0.8    4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
xL  mW  mW  0.8    4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
mW  mW  xL  0.8    4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
mW  xL  mW  0.8    4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
xL  mW  xL  0.8    4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
xL  xL  mW  0.8    4.5     1.8   0.0     1.2  -0.333333333  7.049556277  0.602224558  4  0.0  0.0
```

I'd like to be able to turn off the three-body interactions for everything except the 'mW mW mW' case. With keywords, it might look something like this:

```
pair_style sw check_3b
pair_coeff  * *  mW.sw  3b_off  mW xL
pair_coeff  * *  mW.sw  3b_on   mW NULL
```

I'm not sure how I feel about needing keywords in two different places for it to work, but the alternatives I've looked at reinvent the `if lambda == 0 continue;` wheel, which end up being slower. If you know of a better way to handle combining the 3 and 2-body SWs together I'd be very interested.

**Comment by akohlmey** [comment]
> pair_style sw check_3b
> pair_coeff  * *  mW.sw  3b_off  mW xL
> pair_coeff  * *  mW.sw  3b_on   mW NULL

This kind of syntax will not work. The second pair_coeff line will wipe out the settings of the first. The regular pair style sw sets a flag (which is required for non-pairwise additive potentials) that there may be only one pair_coeff command.
What would work is to change that flag when threebody is deactivated and then use pair style hybrid like this:
```
pair_style hybrid sw threebody on sw threebody off
pair_coeff * *  sw 1 mW.sw mW NULL
pair_coeff 1 2 sw 2 mW.sw mW xL
pair_coeff 2 2 sw 2 mW.sw mW xL
```
When you have manybody interactions enabled, all permutations of atom types enabled (i.e. non-NULL) must be handled by the same pair style instance. Note: the "threebody on" would be default setting, I've added it here for clarity. This would need some careful testing.

**Comment by jkelowitt** [comment]
Ah, I didn't know about that syntax with hybrid. Knowing that, this method seems to be the best way to go. 

Getting it up and running doesn't look like a ton of work, so I'll write it up, run some sanity checks, then make a PR for it. 

Thank you so much!
