### ISSUE TITLE
[BUG] "... there is something wrong with the pylammps interface" - jan-janssen

### ISSUE THREAD

**Issue by PatrickSJacobs** [lammps/lammps#3302]
**Summary**

The internal Pylammps tutorial file simple.ipynb (.../lammps/python/examples/pylammps/simple.ipynb) does not work properly.

**LAMMPS Version and Platform**

Lammps version 2021.9.29; macOS Monterey (version 12.4); MacBook Pro (13-inch, 2019) (Processor is a 1.4 GHz Quad-Core Intel Core i5)

**Expected Behavior**

The tutorial file's location of error does not seemingly have an output, so I therefore do not have a very good notion of what it is supposed to do other than use the run command to start the simulation. 

**Actual Behavior**

I have attached a pdf file of the error messages I receive:

[simple.pdf](https://github.com/lammps/lammps/files/8919980/simple.pdf)

**Steps to Reproduce**

I simply ran all cells in the jupyter notebook.

**Further Information, Files, and Links**

I have also attached a previous conversation with jan-janssen when I first came across this issue who advised me to open this issue:

[Getting Lammps Up and Running with Python · Issue #111 · conda-forge_lammps-feedstock.pdf](https://github.com/lammps/lammps/files/8920029/Getting.Lammps.Up.and.Running.with.Python.Issue.111.conda-forge_lammps-feedstock.pdf)

**Comment by akohlmey** [comment]
This should work with the latest patch release 2 Jun 2022. There were some known issues with some platforms that apply to the most recent stable release. We will produce a new stable release very soon, so please try the patch version if you can and let us know, if that resolves the problems.

**Comment by PatrickSJacobs** [comment]
Is the latest patch included in the "conda install -c conda-forge lammps" command? The latest version on anaconda is v2021.10.27 .

**Comment by akohlmey** [comment]
This is a question you have to ask the people that do the packaging for conda. This is not something the LAMMPS developers do.

**Comment by PatrickSJacobs** [comment]
Who would I need to reach out to about the packaging for conda?

**Comment by akohlmey** [comment]
You are asking in the wrong place for that. Try searching the web.

**Comment by PatrickSJacobs** [comment]
Hello again, I have looked over the anaconda documentation and according to https://anaconda.org/conda-forge/lammps (please let me know if this is the wrong site to be referencing) the development site listed for the anaconda packages is https://github.com/lammps/lammps, which is this site. Please let me know if I am wrong, but this suggests that the developers for the packaging for conda work within this repository. Who in this repository would know who does the packaging for conda?

**Comment by yafshar** [comment]
@PatrickSJacobs if you are looking for feedstock maintainers, you can find them at the bottom of page at https://github.com/conda-forge/lammps-feedstock

**Comment by akohlmey** [comment]
> Please let me know if I am wrong, but this suggests that the developers for the packaging for conda work within this repository.

No, they don't. I don't know who uploaded this and who is providing the configurations etc.
The developers for the conda packaging of LAMMPS are obviously locate here: https://github.com/conda-forge/lammps-feedstock

I realize that you are now between a rock and a hard place since they sent you here, but short of skipping conda and installing LAMMPS from source according to the LAMMPS manual (which *is* supported by us) there is nothing that we can do. Due to the proximity of releasing a new stable version, we will not provide any updates to the current stable release. We have done so multiple times. So if you can verify the issue persists with the latest version of LAMMPS, we will investigate. However, I cannot reproduce it so far on my machine running Linux.

**Comment by PatrickSJacobs** [comment]
As I stated in my original post, I have also attached a previous conversation with jan-janssen (a feedstock maintainer) when I first came across this issue who advised me to open this issue:

[Getting Lammps Up and Running with Python · Issue #111 · conda-forge_lammps-feedstock.pdf](https://github.com/lammps/lammps/files/8921517/Getting.Lammps.Up.and.Running.with.Python.Issue.111.conda-forge_lammps-feedstock.pdf)

**Comment by akohlmey** [comment]
> As I stated in my original post, I have also attached a previous conversation with jan-janssen (a feedstock maintainer) when I first came across this issue who advised me to open this issue:

But as I now stated multiple times. There is no issue with the current 2 Jun 2022 version. So it goes back to whether the feedstock maintainers for LAMMPS are willing to provide packages of a newer version or not.

**Comment by PatrickSJacobs** [comment]
Thank you for the explanation and your patience. What is the current date for the release of the new stable version?

**Comment by akohlmey** [comment]
> Thank you for the explanation and your patience. What is the current date for the release of the new stable version?

That is not fixed. Perhaps next week. Depends on the results of our internal testing and bug reports.
Please note that PyLammps does some rather nasty things behind your back to make things look good and fancy.
If you want to do serious LAMMPS programming using the python interface, you will likely be better off using the `lammps` class instead of `PyLammps`. That should be more efficient, too.

**Comment by PatrickSJacobs** [comment]
Ok, thank you!

**Comment by rbberger** [comment]
Even with fixes in the new releases, please be aware there are several technical reasons why PyLammps can not work in some scenarios. See https://github.com/lammps/lammps/issues?q=is%3Aissue+is%3Aclosed+NoneType for some workarounds, such as making sure Python output is unbuffered to avoid the `NoneType` error (which basically means there was no output that PyLammps was able to capture). PyLammps was developed before we did some major refactoring of the library interface and the `lammps` Python class. We added a lot of introspection that didn't exist before. Some functionality in PyLammps uses a crude output capture that is hard to get right on all systems/configurations. Nowadays, I fully agree with @akohlmey assessment that you should use the `lammps` class instead.
