### ISSUE TITLE
[BUG] Excess YAML document end markers with MPI

### ISSUE THREAD

**Issue by M-S-Jacobs2727** [lammps/lammps#3308]
**Summary**

When running the in.melt example on 2 cores and dumping with style yaml, I couldn't read the file correctly due to several out of place "..." document end markers. I investigated on multiple number of cores, and I found that, per timestep, there are exactly as many "..." as there are processes.

**LAMMPS Version and Platform**

LAMMPS version 2Jun2022
lmp -h output:
[lammps version output.txt](https://github.com/lammps/lammps/files/8930819/lammps.version.output.txt)

**Expected Behavior**

The dump file should have as many document start markers "---" as end markers "...".

**Actual Behavior**

The number of start markers is correct, but the number of end markers is multiplied by the number of processes.

**Steps to Reproduce**

[in.melt.txt](https://github.com/lammps/lammps/files/8930828/in.melt.txt)
I ran the in.melt example with the yaml style dump command (attached). Then I grepped for the document end markers:

    grep -e "^\.\.\." dump.yaml | wc -l

**Comment by M-S-Jacobs2727** [comment]
A simple fix could be to remove the document end markers entirely (line 127 of dump_yaml.cpp), as they are optional according to the YAML spec.

**Comment by akohlmey** [comment]
@M-S-Jacobs2727 confirmed. You can even get more than one marker per MPI ranks, if you have a larger system.

> A simple fix could be to remove the document end markers entirely (line 127 of dump_yaml.cpp), as they are optional according to the YAML spec.

True. I have to discuss this with @sjplimp having a method for dumps to add a footer may actually not be a bad idea.
