### ISSUE TITLE
[BUG] Lost atoms when using Kokkos ReaxFF with RTX3090

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#3348]
**Summary**

I tried to use an Nvidia RTX 3090 card with Kokkos ReaxFF, but the simulations are unstable - the kinetic energy increases to values like 1e+37 and shortly after LAMMPS exits with a `Lost atoms` error.
I can reproduce the error with an example bundled with LAMMPS (see below).

**LAMMPS Version and Platform**

Large-scale Atomic/Molecular Massively Parallel Simulator - 23 Jun 2022
Git info (develop / patch_23Jun2022-439-g62d0277f34)
OS: Linux "Linux Mint 19.3" 5.4.0-99-generic x86_64

Compiler: GNU C++ 9.2.0 with OpenMP 4.5
C++ standard: C++14
MPI v3.1: Open MPI v4.0.2, package: Open MPI michal@michal, ident: 4.0.2, repo rev: v4.0.2, Oct 07, 2019

Accelerator configuration:

KOKKOS package API: CUDA Serial
KOKKOS package precision: double
Architectures: AMPERE86
CUDAToolkit: /usr/local/cuda/include (found version "11.7.64")
Nvidia driver version: 515.43.04

**Expected Behavior**

Correct execution of the example.

**Actual Behavior**

After some steps, the kinetic energy increases to values like 1e+37 and after that LAMMPS exits with `Lost atoms` error.

**Steps to Reproduce**

Run example from `$LAMMPSHOME/examples/reaxff/HNS/` using the command below:
`lmp -in in.reaxc.hns -k on g 1 -pk kokkos newton on neigh half -sf kk -var x 15 -var y 15 -var z 15`

The error isn't deterministic, but should occur during the run.

**Further Information, Files, and Links**

- I can run the `melt` example with the card (with similar memory usage) and KOKKOS acceleration without any problems.
- The erroneous behavior appears faster when the number of atoms is higher.
- Forcing reneighbouring every step doesn't solve the issue.
- Decreasing timestep to 0.01 doesn't solve the issue, but the kinetic energy before error is lower, only ~1e+24.
- Increasing neighbour skin to 2.0  doesn't help.

**Comment by stanmoore1** [comment]
@mkanski this runs fine for me with CUDA 11.2 on 2xV100. If possible could you try backing up CUDA version to something earlier, just to make sure it isn't a CUDA bug?

**Comment by weinbe2** [comment]
A few quick asks, if it's easy for you to test:

- ~Do you have older versions of CUDA available? Just to confirm/deny a compiler bug.~ @stanmoore1 beat me to it :)
- Can you try compiling for AMPERE80 and running it on your 3090? (In general code compiled for sm_80 will run on sm_86 GPUs, but it's not as ideal.)

Please let me know what you find if you can run either/both of these tests.

**Comment by stanmoore1** [comment]
I tried CUDA 11.6.1 and it also runs fine on 2xV100.

**Comment by mkanski** [comment]
Thanks for the fast reply, @stanmoore1 and @weinbe2. 
I tried downgrading to CUDA 11.2 and compiling for AMPERE80 (with CUDA 11.2 or 11.7), but the issue persists.

If it helps, I had GTX1080 in the same computer before and it worked correctly.

**Comment by crtrott** [comment]
Can someone try this on A100 and see if it reproduces there?

**Comment by crtrott** [comment]
Also could you try run the Kokkos unit tests. We do not have any CI machine with 8.6 compute capability. 

Something like
```
cmake -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ARCH_AMPERE86=ON -DKokkos_ENABLE_TESTS=ON 
```

Using Kokkos 3.6 (and if that breaks also Kokkos develop branch) from https://github.com/kokkos/kokkos

**Comment by mkanski** [comment]
The develop branch compiles without any issues. All tests pass.

I was unable to compile the master branch (or release-candidate-3.6.01) with `-DKokkos_ENABLE_TESTS=ON`, error log below. With tests disabled, Kokkos compiles normally.

```
[ 10%] Building CXX object core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_NumericTraits.cpp.o
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(608): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(608): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(608): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(608): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(609): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(609): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(609): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(609): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(610): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(610): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(610): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(610): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(611): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(611): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(611): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(611): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(612): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(612): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(612): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(612): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(613): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(613): note #2742-D: floating-point values cannot be compared

/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(613): error: expression must have a constant value
/home/michal/TEMP/kokkos/core/unit_test/TestNumericTraits.hpp(613): note #2742-D: floating-point values cannot be compared

12 errors detected in the compilation of "/home/michal/TEMP/kokkos/check/core/unit_test/serial/TestSerial_NumericTraits.cpp".
core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/build.make:593: recipe for target 'core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_NumericTraits.cpp.o' failed
make[2]: *** [core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/serial/TestSerial_NumericTraits.cpp.o] Error 1
CMakeFiles/Makefile2:1404: recipe for target 'core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/all' failed
make[1]: *** [core/unit_test/CMakeFiles/KokkosCore_UnitTest_Serial1.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by weinbe2** [comment]
I'm working on trying to reproduce things on my RTX3080 now (and I'll hop over to an RTX3090 if necessary, but hopefully I won't need to). @mkanski can you please try to reproduce the problem on a problem half the size? Perhaps `-var x 15 -var y 15 -var z 7`.

The reason I ask is because your problem is small enough to fit on the 24GB RTX3090 but not on a V100 (or a 12GB RTX3080), and I'd like to make it as apples-to-apples of a comparison as possible, so if you can reproduce it on a smaller problem it'll make things a smidge easier.

**Comment by mkanski** [comment]
@weinbe2 
Thanks for looking into this. 
I can confirm the issue with the reduced size (15x15x7), although it is triggered later during the simulations. A few of them even reached the end (100 steps).

**Comment by weinbe2** [comment]
Okay, that's good to understand, thanks! @crtrott the Kokkos `ctest` passed without issue on my RTX3080 using the branch `release-candidate-3.6.01` using your `cmake` command. Moving on to building LAMMPS now...

**Comment by weinbe2** [comment]
@mkanski what's your exact LAMMPS compile workflow/command?

**Comment by mkanski** [comment]
I use cmake for building:
```
cmake -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=yes -D PKG_REAXFF=yes ../cmake/
make
```

**Comment by weinbe2** [comment]
> I use cmake for building:
> 
> ```
> cmake -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=yes -D PKG_REAXFF=yes ../cmake/
> make
> ```

I assume not including `-DKokkos_ARCH_AMPERE86=ON` is just a typo/expected to be implicit? Just wanted to make sure!

**Comment by mkanski** [comment]
Yes, I didn't include `-DKokkos_ARCH_AMPERE86=ON`, because cmake automatically detects it.

**Comment by stanmoore1** [comment]
@mkanski can you try adding: `-D Kokkos_ENABLE_IMPL_DESUL_ATOMICS=OFF`?

**Comment by mkanski** [comment]
@stanmoore1 It didn't help, the behaviour is the same.

**Comment by weinbe2** [comment]
@mkanski I tried to reproduce the error on an RTX 3090 with your same exact LAMMPS version, `cmake` command, run command, driver version, and CUDA toolkit version, and had no success---I let reax run for many thousands of iterations. I'm trying to think of other possibilities and will get back to you.

**Comment by weinbe2** [comment]
While you're running reax, can you try running

```
nvidia-smi -i 0 --loop-ms=100 --query-gpu=clocks.current.sm,temperature.gpu,power.draw --format=csv,noheader
```

in a separate terminal? (Modify `-i 0` to another number if your RTX isn't GPU 0, modify `100` to a larger number if you want to see data spit out less frequently.)

I'm wondering if your GPU is overheating. Typically when the GPU temperature (column 2) goes above a certain amount the clocks (column 1) and the power draw (column 3) should go down until the temperature comes down a bit. I've been running this in a separate terminal on my RTX 3090 machine and it's been stable.

**Comment by mkanski** [comment]
The card isn't overheating, but there's something wrong with it. The frequencies (divided by 10 on the graph) aren't stable:
![image](https://user-images.githubusercontent.com/20713012/179305967-c7f06d95-7b11-4568-b11e-9b6156b0afab.png)

What's weird for me is that `in.melt` example works without any issue, although there are also some fluctuations:
![image](https://user-images.githubusercontent.com/20713012/179306783-e5d13f7b-b731-42c0-a05d-9c0d8a5d35ca.png)

**Comment by mkanski** [comment]
@weinbe2
I think I solved it.
The frequencies looked too high for me, as the card is rated to 1695 Mhz in boost mode. I limited the frequency with `nvidia-smi`:
```
sudo nvidia-smi -i 0 -pm 1
sudo nvidia-smi -lgc 0,1695
```
Now the simulation runs stable (and uses less power ;) ). 

Thank you very much for your help. I wouldn't be able to find the source of the issue without you.
I would like to thank @stanmoore1 and @crtrott for their fast help. Sorry for raising a false alarm.

**Comment by weinbe2** [comment]
That's great news! I'm happy I could help with working towards a solution. Nothing to apologize about, this type of open reporting of issues helps all of us learn regardless of the actual underlying problem. This is also all written down if someone happens to hit this issue again, but of course I hope not!
