### ISSUE TITLE
[BUG] _cannot compile MISC package without MC package _

### ISSUE THREAD

**Issue by slamont1** [lammps/lammps#3357]
**Summary**

fix_srp_react.cpp (one of the fixes in the MISC package) contains a header reference to fix_bond_break.h and fix_bond_create.h, which are only included in the MC package. Thus, a fatal error occurs when trying to compile without the MC package, but this dependency is not noted anywhere and many users may not know where to go looking for these files to compile the software correctly.

**LAMMPS Version and Platform**

Current development branch on GitHub.

**Comment by akohlmey** [comment]
@slamont1 Thanks for your bug report. I just submitted a pull request that should address this issue and make certain that pair style (and fix) src/react are only installed when also the MC package is installed.
