### ISSUE TITLE
Makefile.intel_cpu_intelmpi,  $MKLROOT should be $(MKLROOT) ?

### ISSUE THREAD

**Issue by WeiLiPenguin** [lammps/lammps#336]
Hi,

$MKLROOT in makefile  seems become KLROOT 

is that better change to $(MKLROOT) ?

also in the lib/meam/Makefile.lammps.ifort:

-lompstub  change to -liompstubs5 ?

Best Regards!

**Comment by akohlmey** [comment]
I agree with the first suggested change, and have included in pull request #330 ; the second depends on the specific compiler versions and needs to be updated all the time. in fact, intel compilers change their linker flags so often, that almost anything will be incorrect for some version of the intel compilers in use. The makefiles designed for use with the USER-INTEL package are special in that they do require a recent version. for the rest, specifically in lib/*, the provided files are just examples and they almost always need to be changed to a local machine.

**Comment by WeiLiPenguin** [comment]
Thanks for relay!

does the libompstub use to fake the openmp in serial run?
but if I want to use the user-omp  and meam package in the same time...
totally lost...

**Comment by akohlmey** [comment]
as for libompstub, you have to refer to the intel compiler documentation, to find out what it does.
i never used/needed it. if you google around, you should find an intel webpage, that interactively helps you build your linker flags for your specific needs.

mind you, there is **no** OpenMP/USER-OMP support in MEAM and meam/spline/omp doesn't require the meam library.
