### ISSUE TITLE
small underallocation in kokkos.cpp

### ISSUE THREAD

**Issue by brianmaustin** [lammps/lammps#3367]
kokkos.cpp allocates lmp->suffix as a char[7] hold a const string with 7 characters.
This should be a char[8] to accomodate the null character.
```
lmp->suffix = new char[7];
strcpy(lmp->suffix,"kk/host");
```
https://github.com/lammps/lammps/blob/80766244778ed0bf1f18934c5e5ff00fa6b0e00e/src/KOKKOS/kokkos.cpp#L498

**Comment by akohlmey** [comment]
Thanks for reporting, this is fixed in commit e583f54ca7604e6cc524c7698876a0706c4ba441 and will be merged into the development branch soon.
