### ISSUE TITLE
[BUG] AMOEBA dipole induction iteration exits early

### ISSUE THREAD

**Issue by chappertron** [lammps/lammps#3385]
**Summary**

There is an early termination of the AMOEBA induced dipole calculation if epsilon increases vs. previous iteration. Line 372 in `amoeba_induce.cpp` checks if the value of epsilon has increased vs the previous iteration and unnecessarily terminates. If this line is removed, the iteration continues and a solution is found.

As I understand, epsilon does not necessarily need to decrease monotonically in the conjugate gradient method used (see Further Information). In fact, the function the `induce` method is based on from the tinker source code has the equivalent line commented out, (see line 559 in https://github.com/TinkerTools/tinker/blob/release/source/induce.f ).

The issue can easily be fixed by removing or commenting out line 372 in `amoeba_induce.cpp`. 

**LAMMPS Version and Platform**

patch_3Aug2022, Ubuntu x86_64

**Expected Behavior**

Dipole induction iteration is allowed to continue until either the maximum number of iterations is reached or epsilon is below the set threshold.

**Actual Behavior**

Dipole induction iteration is terminated earlier than necessary.

**Steps to Reproduce**

Extending the in.water_box.amoeba example to around 1000 timesteps results in several warnings that `AMOEBA induced dipoles did not converge (src/AMOEBA/amoeba_induce.cpp:395)`. 
Printing or debugging the values of `epsold`, `eps` and `iter` in the `induce` method of `src/AMOEBA/amoeba_induce.cpp` reveals that the errors are occurring when `eps` is greater than `epsold`, and before iteration has reached the maximum number of steps (default of 100).

**Further Information, Files, and Links**

A discussion on why the residual squared (epsilon) does not need to decrease monotonically with iterations in CG method:
https://math.stackexchange.com/questions/396844/non-monotonic-decrease-of-residuals-in-conjugate-gradients

**Comment by akohlmey** [comment]
@chappertron thanks for reporting, I have included your suggested changes in PR #3387

**Comment by chappertron** [comment]
@akohlmey Thank you!
