### ISSUE TITLE
[BUG] AMOEBA dipole convergence warnings ignoring polar-iter option

### ISSUE THREAD

**Issue by chappertron** [lammps/lammps#3386]
**Summary**

The number of iterations for induced dipole convergence in the newly added Amoeba/Hippo forcefields can be controlled with the `polar-iter` parameter in the `.key` file. 
For the purposes of displaying a warning when the number of iterations is exceeded, line 393 in `src/AMOEBA/amoeba_induce.cpp` checks if the number of iterations has exceeded a hardcoded variable `maxiter`, rather than `politer`, which is used defined in the `.key` file.

As such, a warning is always shown if 100 iterations are exceeded, no matter the value of `polar-iter`.

This issue can be easily fixed by changing `maxiter` to `politer` in line 393 of `src/AMOEBA/amoeba_induce.cpp`

**LAMMPS Version and Platform**

patch_3Aug2022 on Ubuntu x86_64.

**Expected Behavior**

Based on the manual (see https://docs.lammps.org/latest/Howto_amoeba.html) the `.key` keyword `polar-iter` should be supported to control the number of iterations allowed for induced dipole convergence.

A warning should be emitted if this number of iterations is exceeded.

**Actual Behavior**

A warning is only emitted if the hard coded 100 iterations are exceeded, or if an unnecessary check that epsilon is lower than the previous iteration (see issue #3385) is satisfied.

**Steps to Reproduce**

Setting the number of iterations to one (with `polar-iter 1` in the `.key` file) in the water box example, a warning should be emitted immediately at every single timestep, however is not.  

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
@chappertron thanks for reporting, I have included your suggested changes in PR #3387

**Comment by chappertron** [comment]
@akohlmey Thank you!
