### ISSUE TITLE
[BUG] Invalid dump line format can trigger segmentation faults

### ISSUE THREAD

**Issue by jtclemm** [lammps/lammps#3404]
**Summary**

When users specify custom format line options using the `dump_modify` command, LAMMPS only performs a minimal number of error checks - namely it checks whether the user provided formatting is too short for dump custom. If the formatting string is too long, this can lead to invalid memory access in [dump custom](https://github.com/jtclemm/lammps/blob/43726c020a1330572a7aa88e14a7a0e1d81ce7d9/src/dump_custom.cpp#L268), as identified by Joe Monti (SNL).  For other dump styles like atom and xyz, LAMMPS does not issue a warning/error if there is an invalid formatting string.

To fix this, maybe LAMMPS should always check whether the format line has the correct length in all relevant dump styles, as done [here](https://github.com/jtclemm/lammps/commit/8b948e08eb7f0fa1b18ba4007eda6edb6a6a07a8). If this is an appropriate solution, I can submit a pull request. Although as an aside, I do not understand why dump xyz defines [5 peratom quantities](https://github.com/lammps/lammps/blob/43726c020a1330572a7aa88e14a7a0e1d81ce7d9/src/dump_xyz.cpp#L37) despite only outputting the id and three coordinates. 

**LAMMPS Version and Platform**

Current development branch

**Expected Behavior**

LAMMPS should provide a clear error (or warning) if the user specified formatting for a dump file is incorrect.

**Actual Behavior**

With a few exceptions, LAMMPS ignores incorrect formatting which can trigger a segmentation fault in dump custom, cfg, etc.

**Steps to Reproduce**

I modified the melt example, linked below, and added several dump options with different formatting options. For each case, I noted whether LAMMPS ignores the errors and runs, issues an error and quits, or seg faults. 

**Further Information, Files, and Links**

[in.melt.txt](https://github.com/lammps/lammps/files/9353932/in.melt.txt)

**Comment by akohlmey** [comment]
@jtclemm I have run your example input and neither experienced a segmentation fault nor saw any valgrind issues about invalid memory access. There might be something different with the printf() implementation you are using.

The problem with the checks you are applying is that they can be very misleading. I have seen people using format strings without blanks (e.g. `%20.15f%20.15f%20.15f`) and I have seen people including extra words into the format string. Both of these would cause false positives. At the current state of affairs, it is not easily possible to do a proper check without writing a complete parser for printf() style format strings.

Better checking *would* be possible if we switch to [`{fmt}` style processing](https://fmt.dev/latest/index.html) (but people are not so familiar with it than with printf()). Any error would throw an exception that can be caught and properly processed.

I had at some point proposed to drop allowing explicit printf() strings altogether and instead provide "width" and "precision" parameters (the latter of course only for floating point data). This can be easily implemented with `{fmt}` by using something like `fmt::format("{:{}.{}}", data[icol], width[icol], prec[icol])`.  With this format errors would be completely avoided.

**Comment by akohlmey** [comment]
> Although as an aside, I do not understand why dump xyz defines [5 peratom quantities](https://github.com/lammps/lammps/blob/43726c020a1330572a7aa88e14a7a0e1d81ce7d9/src/dump_xyz.cpp#L37) despite only outputting the id and three coordinates.

Please look at the `DumpXYZ::pack()` function. It "packs" 5 per-atom properties (tag, type, x-,y-,z-position) into the communication buffer.

**Comment by jtclemm** [comment]
> @jtclemm I have run your example input and neither experienced a segmentation fault nor saw any valgrind issues about invalid memory access. There might be something different with the printf() implementation you are using.

My apologies, I forgot to mention that only the specific dump_modify command should be uncommented to trigger each specific  issue. Here's a set of comments in that file that causes the seg fault: [in.melt.txt](https://github.com/lammps/lammps/files/9354432/in.melt.txt). The seg fault occurs when LAMMPS tries to delete `vformat[i]` after iterating to a value of `i` greater than `nfield` on [line 269](https://github.com/lammps/lammps/blob/43726c020a1330572a7aa88e14a7a0e1d81ce7d9/src/dump_custom.cpp#L269).

>
> The problem with the checks you are applying is that they can be very misleading. I have seen people using format strings without blanks (e.g. `%20.15f%20.15f%20.15f`) and I have seen people including extra words into the format string. Both of these would cause false positives. At the current state of affairs, it is not easily possible to do a proper check without writing a complete parser for printf() style format strings.
> 
> Better checking _would_ be possible if we switch to [`{fmt}` style processing](https://fmt.dev/latest/index.html) (but people are not so familiar with it than with printf()). Any error would throw an exception that can be caught and properly processed.
> 
> I had at some point proposed to drop allowing explicit printf() strings altogether and instead provide "width" and "precision" parameters (the latter of course only for floating point data). This can be easily implemented with `{fmt}` by using something like `fmt::format("{:{}.{}}", data[icol], width[icol], prec[icol])`. With this format errors would be completely avoided.

Hmm, I hadn't thought of missing spaces or extra words in the formatting line. I see now why this is trickier than I thought. 

To solve the segmentation fault, maybe it's then best to just simply break out of the offending loop if `i == nfield`. However, extra words or neglected spaces in the formatting string can lead to strange output due to the parsing of `words`  in the custom dump style (and derived styles). The existing error message "Dump_modify format line is too short" would also be triggered if there were no spaces. Maybe it might be good to alternatively warn the user to double check their output if `(int) words.size() != nfield` specifically in dump_custom.cpp?

**Comment by akohlmey** [comment]
> I see now why this is trickier than I thought.

There are additional issues with the non-portable printf() format requirements on 64-bit integers (on some platforms they are "long int" on others "long long int" etc.) and lots of nitty-gritty details. That is why I have been pushing so hard to replace as much of those cases with `{fmt}`, but thermo_modify and dump_modify are difficult to replace. So either we take away some flexibility (and simplify the code as well) or we have to depend on users making informed choices and live with what we have.

There are two schools of thought among the core LAMMPS developers: 1) the users have to know what they are doing. it is all documented and 2) users don't pay much attention to long-winded manual pages with lots of details, so we need to implement the solution causing the least surprises and warn about bad choices when it is easy to detect them. Sometimes we agree, sometimes we don't. In the last 5 or so years a *lot* of checks were added and not time critical code was changed to put less trust in the user's input. There is still a lot to do (hence the code clinic initiative to get at least some of the easier stuff done faster through crowdsourcing).
To make a code like LAMMPS completely safe from careless users is essentially impossible. There is the saying (I learned it a long time ago from the Linux kernel mailing list): if you try to idiot-proof something, the universe will create a better idiot.

> To solve the segmentation fault, maybe it's then best to just simply break out of the offending loop if `i == nfield`.

that is a good idea. I will add that to a PR I have already open.

> The existing error message "Dump_modify format line is too short" would also be triggered if there were no spaces.

true, I have mixed up custom thermo formatting and custom dump formatting. I have refactored both recently...

**Comment by jtclemm** [comment]
> > To solve the segmentation fault, maybe it's then best to just simply break out of the offending loop if `i == nfield`.
> 
> that is a good idea. I will add that to a PR I have already open.

Since the memory error is the primary issue at hand, that would close this bug report. Better errors/warnings would be nice but, like you said, I see that checking formatting strings is nontrivial. Thanks also for the background on printf() and {fmt}, it is helpful to know about.

**Comment by akohlmey** [comment]
@jtclemm commit 0cac041ad40d18ac652c00809c8ce29ebb6d0a38 should avoid the segfault. I found 3 cases where this change is needed. Please let me know if you notice another one.

Yeah, `{fmt}` is really cools stuff. The more I learn about it, the more I like it. But it takes some time to learn using it well.
I have not yet dug so deep that I've learned to write specializations for custom data types.
