### ISSUE TITLE
[BUG] Incorrect background charge correction term for charged slab systems

### ISSUE THREAD

**Issue by jonwils** [lammps/lammps#3413]
**Summary**

When using the electrostatic slab correction from Yeh & Berkowitz and the background charge correction from Ballenegger for charged systems, the background-background charge interaction term is calculated incorrectly. In pppm.cpp in the slabcorr() and slabcorr_groups() functions, this term is calculated as:

e_slabcorr = MY_2PI\*(dipole_all\*dipole_all - qsum\*dipole_r2 - qsum\*qsum\*zprd\*zprd/12.0)/volume;

Whereas it should use the system extent in the z direction plus vacuum padding:

e_slabcorr = MY_2PI\*(dipole_all\*dipole_all - qsum\*dipole_r2 - qsum\*qsum\*zprd_slab\*zprd_slab/12.0)/volume;

This does not affect the forces.

**LAMMPS Version and Platform**

I am using lammps-29Oct20 on Linux,
but the bug is also present in lammps-23Jun22

**Expected Behavior**

I expect the energy of the system does not change significantly when the vacuum padding of the slab is varied since the energies are corrected.

**Actual Behavior**

When the slab volfactor value is changed, the energy of the system changes significantly. 

**Steps to Reproduce**

Run the attached file and see how etotal varies before and after I set 
kspace_modify slab 5.0
I verified that my code suggestion at the top fixes the problem.

**Further Information, Files, and Links**

[slabtest.zip](https://github.com/lammps/lammps/files/9417134/slabtest.zip)

**Comment by srtee** [comment]
Worth noting that the corrected expression from @jonwils is what is actually in Ballenegger's paper (https://aip.scitation.org/doi/pdf/10.1063/1.3216473).

In that paper $h$ is used for `zprd` (Sec II A, first para) and $L_z$ is `zprd_slab` (Sec III C), so the non-neutral slab energy (equation 29) corresponds to the corrected expression rather than what is currently in the code.

**Comment by stanmoore1** [comment]
@srtee that is helpful, thanks. I'll take a look/submit a PR.
