### ISSUE TITLE
[Feature Request] Retain comments in data file upon read 

### ISSUE THREAD

**Issue by wapisani** [lammps/lammps#3415]
**Summary**

It would be helpful if LAMMPS retained all comments that are present in a data file so that those same comments can be written to new data files.

**Detailed Description**

I usually use the class2 INTERFACE Force Field (IFF) and the atom types in this force field are variations on the atomic symbol. For example, a carbon atom in a benzene/phenyl group is "cp", but a standard carbon atom is "c". A hydrogen atom bonded to carbon is "hc", but a hydrogen atom bonded to oxygen is "ho". I find it helpful to include as a comment the type of pair, bond, angle, dihedral, and improper coefficient on the line that that coefficient appears. A brief example of this is shown below.

Pair Coeffs

1     0.02   2.3      # hc        
2     0.12   3.81     # c_1       
3     0.267   3.3     # o_1       
4     0.064   4.01    # cp

Bond Coeffs

1     1.111   325.5717   -632.199   726.0003        # hc-c_1    
2     1.202   851.1403   -1918.4882   2160.7659     # c_1-o_1   
3     1.489   339.3574   -655.7236   670.2362       # c_1-cp    
4     1.417   470.8361   -627.6179   1327.6345      # cp-cp     
5     1.0982   372.8251   -803.4526   894.3173      # hc-cp 

Angle Coeffs

1     117.8326   45.9187   -22.5264   0.0           # hc-c_1-o_1
2     120.0000   40.0000   0.0   0.0                # hc-c_1-cp 
3     125.532   72.3167   -16.065   2.0818          # o_1-c_1-cp
4     116.064   71.2598   -15.8273   2.0506         # c_1-cp-cp 
5     118.9   61.0226   -34.9931   0.0              # cp-cp-cp  

I use these comments in various Python codes to determine the specific type of bond, angle, dihedral, and improper. LAMMPS does not preserve these comments upon reading the data file and so any future data files that are written do not have these helpful comments. 

I am suggesting that an optional keyword option be included in the read_data command so that it retains the comments in a data file. It may also be helpful to have the ability to have comments associated with specific atoms, bonds, angles, etc. and not just the coefficients. If the LAMMPS data structure has comments, then the write_data command would write out those comments to the data file, perhaps also with an optional keyword.

Thanks!

**Comment by akohlmey** [comment]
> I am suggesting that an optional keyword option be included in the read_data command so that it retains the comments in a data file.

This is not easily possible since comments are removed long before parsing those lines, so it is not possible to parse and associate them with any data.

However, your use case is an application that likely would benefit from the type label feature in PR #2531

**Comment by wapisani** [comment]
I was not aware of that feature. Looks like it would work well for my use case. Thanks! I look forward to using it in the future.
