### ISSUE TITLE
[Feature Request] Implement additional C-style format strings

### ISSUE THREAD

**Issue by jimustafa** [lammps/lammps#3417]
**Summary**

It seems there is a use case for additional C-style format strings for variable declarations. In particular, when looping over a integer with padding enabled, a `%0Xd` format string could make it easy to get the correctly formatted value for previous or subsequent values of the variable. The situation in mind is reading data from a previous simulation where the filename contains the padded loop variable.

**Detailed Description**

Below is a toy example. Still new to LAMMPS, but starting with an equilibrium structure and successively reading/writing the structure as temperature is changed seems like a common pattern.

```
lattice fcc 4
region box block 0 1 0 1 0 1 units lattice
create_box 1 box
create_atoms 1 box

pair_style eam/alloy
pair_coeff * * AlCu.eam.alloy  Al

write_data eq.dat

clear

variable i loop 0 10 pad
label loop

# does not work with padding
if "${i}==0" then "read_data eq.dat" else "read_data data.$(v_i-1).dat"

# this could work
# if "${i}==0" then "read_data eq.dat" else "read_data data.$(v_i-1:%02d).dat"

write_data data.${i}.dat

clear

next i
jump SELF loop
```

**Comment by akohlmey** [comment]
Actually you *can* format with padding in this case. The problem is that variables *always* return floating point values, thus using an integer format specifier would be incorrect and rightfully refused by LAMMPS. If you use the following command instead, you will get the desired output format.
```
if "${i}==0" then "read_data eq.dat" else "read_data data.$(v_i-1:%02.0f).dat"
```
No change to LAMMPS is needed for this.

**Comment by jimustafa** [comment]
Thank you @akohlmey! My bad for missing such an obvious solution.
