### ISSUE TITLE
Variables in Lammps Harmonic/cut potential do not have the correct units. 

### ISSUE THREAD

**Issue by Rinske-alkemade** [lammps/lammps#3423]
Dear Lammps, 

On the documentation page of the _harmonic/cut_ pairstyle (https://docs.lammps.org/pair_harmonic_cut.html), the coefficient _k_ currently is defined in units of energy. However, it should be defined in units of energy/distance^2.  I know that this is not a big issue, however, due to this definition, it took me some time to figure out with which form of the harmonic potential lammps is working. Therefore I still wanted to report it to you, 

Thank you,

Best Rinske

**Comment by akohlmey** [comment]
Thanks for your report. This should be remedied in the next LAMMPS patch release.
