### ISSUE TITLE
[Feature Request] Publish LAMMPSLexer as an independent package

### ISSUE THREAD

**Issue by njzjz** [lammps/lammps#3447]
**Summary**

Publish `LAMMPSLexer` as an independent Python package.

**Detailed Description**

Some external packages need to write LAMMPS code in their Sphinx-based documentation. It will be nice if `LAMMPSLexer` can be installed as an extension.

**Further Information, Files, and Links**

LAMMPSLexer: https://github.com/lammps/lammps/blob/develop/doc/utils/sphinx-config/LAMMPSLexer.py
`Pygments` provides a way to define plugins: https://pygments.org/docs/plugins/
An example: https://github.com/fcurella/jsx-lexer/blob/04d486dfa97ea78383dfeab3875396d43ba0f6de/setup.py#L28-L31

**Comment by akohlmey** [comment]
@njzjz if you want to do this, you are free to do so for as long as the code taken from LAMMPS remains under GPL-2 license and that you indicate where it is taken from. Otherwise you would have to convince @rbberger to do it since he is the principal author.

**Comment by rbberger** [comment]
@njzjz Sounds like a good idea. I'll create that package.

**Comment by rbberger** [comment]
@njzjz @akohlmey Done. Was an interesting exercise. Learned a lot doing so. https://pypi.org/project/pygments-lammps/

**Comment by njzjz** [comment]
> @njzjz @akohlmey Done. Was an interesting exercise. Learned a lot doing so. https://pypi.org/project/pygments-lammps/

Thanks, it works for me!
