### ISSUE TITLE
[Feature Request] Add LAMMPS_VERSION_NUMBER in version.h

### ISSUE THREAD

**Issue by bigd4** [lammps/lammps#3451]
Now `version.h` has following information:
```
#define LAMMPS_VERSION "15 Sep 2022"
```
It may a little hard to diretly use **LAMMPS_VERSION** in **#if.** Althogh **LAMMPS_VERSION_NUMBER** can be got by cmake easily but I don't know how to get it automatically when use make. Would you please add it (like `#define LAMMPS_VERSION_NUMBER 20220915`) in `version.h`?  It may not work for older version but may bring convenience in the future.

**Comment by akohlmey** [comment]
@bigd4 if you need a differently formatted version text, you can easily write a little converter and create and use a custom header, e.g. numversion.h as part of your build procedure.

**Comment by bigd4** [comment]
> @bigd4 if you need a differently formatted version text, you can easily write a little converter and create and use a custom header, e.g. numversion.h as part of your build procedure.

Yes, I realized that I could convert it in `Install.sh` when use make. Thank you very much!
