### ISSUE TITLE
[BUG] Wrong force for bond_style quartic

### ISSUE THREAD

**Issue by TerrySuun** [lammps/lammps#3466]
**Summary**

The evaluation of bond force for bond_style quartic is wrong for the LJ term.

**LAMMPS Version and Platform**

23 Jun 2022
Linux x86_64
source code

**Expected Behavior**

1, correct force for bond_style quartic
2, clear documentation of bond energy terms

**Actual Behavior**

Large force when particle distance r < 1.0

**Steps to Reproduce**

1, Manually calculate force between quartic bonded particles
2, documentation on bond_style quartic is not clear enough about the LJ term.

**Further Information, Files, and Links**

1, In MOLECULE/bond_quartic.cpp, line 125, at the end, the bond force is evaluated to r^(-14), instead of the correct r^(-13), for the first term. The second term should be evaluated to r^(-7) if the same bug is fixed.
Correction for line 125 should be 

fbond += 48.0 * sr6 * (sr6 - 0.5) / r;

2, according to the code, line 122-131 in the same file, the LJ term in bond_style quartic is only evaluated when r < 2^(-1/6), meaning only the repulsive section of the LJ term is in effect. This should be clearly indicated in the documentation.

https://docs.lammps.org/bond_quartic.html

**Comment by akohlmey** [comment]
Please note that fbond is *not* the force, but - for computational efficiency - it is force/r.
You can see this when the force is projected on x, y, z in lines 136-138 and 142-144 where fbond is "only" multiplied by delx/dely/delz. If fbond would be the force, then those projections would require a division by r.

**Comment by TerrySuun** [comment]
Ah, right, I missed this. Any plan on the document update? Hopefully? Otherwise, I'll just close this bug report.

**Comment by akohlmey** [comment]
> This should be clearly indicated in the documentation.

It is a cutoff of `2^(1/6)` i.e. 1.122462048309373 and *not* `2^(-1/6)`

This will be clarified in the next patch release.

**Comment by TerrySuun** [comment]
Yes, my mistake, should be 2^(1/6).
