### ISSUE TITLE
[Feature Request] Allow Kokkos dynamic linking

### ISSUE THREAD

**Issue by yueyericardo** [lammps/lammps#3469]
Currently, Kokkos is forced to be built as a static library. 
https://github.com/lammps/lammps/blob/f136bcbef7ad0c9979e6ac24bbec63ef0f8b7800/cmake/Modules/Packages/KOKKOS.cmake#L81-L84

However, this does not support [plugins](https://docs.lammps.org/Developer_plugins.html). Because, in this way, both the built plugin library and the lammps library would contain some common Kokkos static variables (e.g., [Kokkos::Tools::InitArguments::unset_string_option](https://github.com/kokkos/kokkos/blob/61d7db55fceac3318c987a291f77b844fd94c165/core/src/impl/Kokkos_Profiling.hpp#L68) ), and this would lead to double free error:

```
*** Error in `/blue/roitberg/apps/lammps-ani/external/lammps//build/lmp_mpi': double free or corruption (!prev): 0x0000000004fae9e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x816b9)[0x2b597f7a86b9]
/apps/compilers/gcc/9.3.0/lib64/libstdc++.so.6(_ZNSsD1Ev+0x3e)[0x2b597ef17a1e]
/blue/roitberg/apps/lammps-ani/external/lammps/build/liblammps_mpi.so.0(_ZN6Kokkos5Tools13InitArgumentsD1Ev+0x1c)[0x2b5979825cc0]
/lib64/libc.so.6(__cxa_finalize+0x9a)[0x2b597f76104a]
/blue/roitberg/apps/lammps-ani/external/lammps/build/liblammps_mpi.so.0(+0x1699183)[0x2b5977f10183]
```

I'm wondering whether we could add a flag, for example, `KOKKOS_BUILD_SHARED_LIBS` that would allow users to build Kokko as a shared library?

**Comment by akohlmey** [comment]
Trying to build a plugin with KOKKOS support is asking for trouble. The plugin interface mechanism is not designed to support that.

> Currently, Kokkos is forced to be built as a static library.

That only applies to the case when using the bundled Kokkos library. You can still download and build Kokkos as an external library (which would be required, for example, if you want to couple LAMMPS and another code that both would use Kokkos) and configure it to be dynamically linked in that case.

**Comment by yueyericardo** [comment]
Thanks for the quick reply! I would link with the external Kokkos library then.
