### ISSUE TITLE
[BUG] Redundant copies of nelements/cutsq go out of sync in pair_mliap and its descriptor file

### ISSUE THREAD

**Issue by bathmatt** [lammps/lammps#3494]
**Summary**

redundant copies of nelements/cutsq go out of sync in pair_mliap and its descriptor file.

**LAMMPS Version and Platform**

Develop b44e353d4ae0246dc955ff9a6a3f25ca16b3038f

**Expected Behavior**
exptect these to be the same.  These differences are causing computed values to be wrong, the test data needs reblessing.

**Actual Behavior**
values are different.

**Steps to Reproduce**
Apply the following patch to print out the differences

```
diff --git a/src/ML-IAP/pair_mliap.cpp b/src/ML-IAP/pair_mliap.cpp
index 865019ba55..f6318cd390 100644
--- a/src/ML-IAP/pair_mliap.cpp
+++ b/src/ML-IAP/pair_mliap.cpp
@@ -80,7 +80,14 @@ void PairMLIAP::compute(int eflag, int vflag)
 {
 
   // consistency checks
-
+  if ( nelements != descriptor->nelements )
+    printf("number of elements are out of sync\n");
+  
+  for (int i=0;i< descriptor->nelements;++i)
+    for (int j=0;j< descriptor->nelements;++j)
+      if ( cutsq[i][j] != descriptor->cutsq[i][j])
+        printf("cutsq has gone out of sync\n");
+  
   if (data->ndescriptors != model->ndescriptors)
     error->all(FLERR, "Inconsistent model and descriptor descriptor count: {} vs {}",
                model->ndescriptors, data->ndescriptors);

```

Build the code with the following cmake command

```
cmake -C ../cmake/presets/basic.cmake -C ../cmake/presets/kokkos-openmp.cmake -D BUILD_SHARED_LIBS=on -D LAMMPS_EXCEPTIONS=on -D PKG_PYTHON=on -DPKG_ML-SNAP=ON  -DPKG_KOKKOS=ON -DPKG_ML-IAP=ON  -DCMAKE_BUILD_TYPE=RELEASE   ../cmake/ -D ENABLE_TESTING=on
```

Run the following test from the examples/mliap directory

```
TEST_ARGS=-v /home/mattb/lammps/clean/omp-test/test_pair_style  /home/mattb/lammps/LAMMPS/unittest/force-styles/tests/manybody-pair-mliap_snap_chem.yaml

```

obviously changing all the paths accordingly.  

You will see a lot of reports of differences.

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
I cannot reproduce this. Please note that unit tests are not guaranteed to match closely when compiled in Release mode due to the differences in compilers when compiling code aggressively. Please try with RelWithDebInfo instead.
Also, what is your OS and version? Do you use custom compilers?
I am running on Fedora 36 with GCC 12 and the unit tests for KOKKOS also run on Fedora (but still version 34) and non-Kokkos on Ubuntu 18.04LTS.

**Comment by bathmatt** [comment]
When you say you cannot reproduce this, what do you mean, you cannot see the output saying there are differences or you cannot get the test to fail?

**Comment by bathmatt** [comment]
Just to reiterate.  The bug is that the code has two different values for variables like cutsq and nelements for the same pair, mliap_pair.  The mliap_data uses the descritpor value, 

      if (rsq < descriptor->cutsq[ielem][jelem]) {

and this is different the the value set in pair_mliap.  This is the bug.  The bug needs to be fixed and the test needs to be re blessed.  Right now the test passes because the gold results are wrong...

**Comment by akohlmey** [comment]
There is some confusion there.

`nelements` is a variable describing the size of the `elements[]` array of strings. This is what several manybody potentials use to map their potential parameters to LAMMPS atom types. Pair style mliap does not use that so `nelements` will be 0. This is a bit unfortunate, but cannot be changed.

Similarly, the descriptor (same as a potential file) may have more entries for elements than what are actually used in the pair style. At least that is what the code in the coeff() function implies. The map[] array provides the mapping of LAMMPS atom type to descriptor entry. That is why the init_one() function accesses descriptor->cutsq[map[i][map[j]]

Thus your proposed "consistency check" is bogus.

**Comment by akohlmey** [comment]
The correct consistency check would be:
```
  for (int itype=1; itype <= atom->ntypes; ++itype)
    for (int jtype=1; jtype <= atom->ntypes; ++jtype)
      if (cutsq[itype][jtype] != descriptor->cutsq[map[itype]][map[jtype]])
        fmt::print("cutsq consistency check for type i={} j={}: {} vs {}\n",
                   itype, jtype, cutsq[itype][jtype], descriptor->cutsq[map[itype]][map[jtype]]);
```
and that does not show any inconsistencies for the test.

**Comment by stanmoore1** [comment]
Let's back up a step. @bathmatt you are seeing numerical differences in the unit tests between Kokkos and non-Kokkos? But currently the automated unit tests on the PR are failing with a segfault?

**Comment by akohlmey** [comment]
> Let's back up a step. @bathmatt you are seeing numerical differences in the unit tests between Kokkos and non-Kokkos? But currently the automated unit tests on the PR are failing with a segfault?

@stanmoore1 
This is about the develop branch (check out the commit hash), which has no KOKKOS support for ML-IAP. Those tests are skipped because of that. This is about the ML-IAP package code itself.

**Comment by stanmoore1** [comment]
@akohlmey OK I missed that, thanks

**Comment by bathmatt** [comment]
@akohlmey when I do that I get a seg fault...

```
(base) mattb@0cb28a7-lcedt:~/lammps/clean/examples/mliap$ git diff
diff --git a/src/ML-IAP/pair_mliap.cpp b/src/ML-IAP/pair_mliap.cpp
index 865019ba55..4d167bee56 100644
--- a/src/ML-IAP/pair_mliap.cpp
+++ b/src/ML-IAP/pair_mliap.cpp
@@ -80,7 +80,14 @@ void PairMLIAP::compute(int eflag, int vflag)
 {
 
   // consistency checks
-
+  if ( nelements != descriptor->nelements )
+    printf("number of elements are out of sync\n");
+  
+  for (int i=1;i< atom->ntypes;++i)
+    for (int j=1;j< atom->ntypes;++j)
+      if ( cutsq[i][j] != descriptor->cutsq[i][j])
+        printf("cutsq has gone out of sync\n");
+  
   if (data->ndescriptors != model->ndescriptors)
     error->all(FLERR, "Inconsistent model and descriptor descriptor count: {} vs {}",
                model->ndescriptors, data->ndescriptors);
(base) mattb@0cb28a7-lcedt:~/lammps/clean/examples/mliap$ 
```

and 

```
(base) mattb@0cb28a7-lcedt:~/lammps/clean/examples/mliap$ TEST_ARGS=-v /home/mattb/lammps/clean/omp-test/test_pair_style  /home/mattb/lammps/LAMMPS/unittest/force-styles/tests/manybody-pair-mliap_snap_chem.yaml
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from PairStyle
[ RUN      ] PairStyle.plain

test_pair_style:7406 terminated with signal 11 at PC=7fac0418826a SP=7ffef350cb80.  Backtrace:
```

This is because cutsq isn't allocated beyond 2 for the descriptor, and

(gdb) p atom->ntypes
$3 = 8

**Comment by bathmatt** [comment]
deleted the prev comment...  i missed a check

**Comment by bathmatt** [comment]
> Let's back up a step. @bathmatt you are seeing numerical differences in the unit tests between Kokkos and non-Kokkos? But currently the automated unit tests on the PR are failing with a segfault?

Those have been fixed and not committed..
Well, to your repo.

**Comment by bathmatt** [comment]
OK, I will dig into what is happening a bit more, I'm seeing the code use a mix of data it looks like, things are getting into the pairs that looks outside the smaller radius cutoff  which was changed.  I will look more tomorrow and close if it is my mistake, and take 100 lashes.

**Comment by bathmatt** [comment]
Thanks for the correct compare,

**Comment by bathmatt** [comment]
The explanation the mapping between pair->cutsq and descriptor->cutsq resolved this issue.
