### ISSUE TITLE
[BUG] Hyperlinks to functions in documentation aren't resolving the first time

### ISSUE THREAD

**Issue by hammondkd** [lammps/lammps#3496]
**Summary**

When I build the documentation, the links to Fortran functions in doc/html/Fortran.html don't work (e.g., the links to `file()`, `command()`, `commands_list()`, and `commands_string()` under the "1.3.3. Executing LAMMPS commands" heading). Neither do the ones in doc/fasthtml/Fortran.html when I do a `make fasthtml`.

However, they *do* work if I issue the following commands (from the "doc" directory):
```
make clean
make fasthtml
touch src/Fortran.rst
make fasthtml
```
The HTML files after the first `make fasthtml` do not have hyperlinked cross-references, but those after the second one do. I suspect there is an operation (or two) that either needs to be done twice, or in another order.

**LAMMPS Version and Platform**

LAMMPS (23 Jun 2022) [also happens with latest "develop" branch on October 21, 2022]

I'm running this on Fedora 36.

**Expected Behavior**

Hyperlinks work after first run and in the `make html` version.

**Actual Behavior**

Formatting is fine, but hyperlinks are not created in the `make fasthtml` unless the file is re-touched and `make fasthtml` is run again. Hyperlinks never work in `make html`, from the tests I have done.

**Steps to Reproduce**

 (1) cd [lammps_root]/doc
 (2) `make clean`
 (3) `make html fasthtml`
 (4) Direct browser to [lammps_root]/doc/html/Fortran.html
 (5) Scroll down to "Executing LAMMPS commands" and hover over `*command()*` or `*file()*` (it won't be a link)
 (6) Direct browser to [lammps_root]/doc/fasthtml/Fortran.html
 (7) Scroll down to "Executing LAMMPS commands" and hover over `*command()*` or `*file()*` (it won't be a link)
 (8) `touch [lammps_root]/doc/src/Fortran.rst`
 (9) `make fasthtml html`
 (10) Repeat steps (4) through (7) or reload the pages from before; it will look the same, except this time step (7) will give you hyperlinks that work

**Comment by akohlmey** [comment]
@hammondkd this is an interesting observation. I've noticed that this behavior is the same across all different outputs, so I suspect this is some internal limitation of the sphinxfortran extension. Unfortunately, I have no idea how to debug or even fix this in the extension. But based on your observations with the "fasthtml" target, I have implemented a workaround in commit 165b6b4ba3b5d7291d4cf15068b03013972a681d
