### ISSUE TITLE
error: triclinic box skew is too large

### ISSUE THREAD

**Issue by e-724** [lammps/lammps#3505]
Please **do not** post requests for help (e.g. with installing or using LAMMPS) here.
Instead send an e-mail to the lammps-users mailing list.

This issue tracker is for tracking LAMMPS development related issues only.

Thanks for your cooperation.

#模型基本设置
units    metal                       
atom_style  atomic                      
boundary        p p p                        
read_data SiO2.data
#fix 1 all box/relax yes yes yes 
#box tilt large
change_box all x scale 0.960 y 0.960  z 0.960
box tilt large
fix 1 all box/relax 
#fix 1 all deform 1 x scale 0.960 y scale 0.960 z scale 0.960
#fix 1 all box/relax scaleyz value no  scalexz value no  scalexy value  no
#设置力场
pair_style vashishta
pair_coeff * * SiO.1997.vashishta O Si
#设置邻居列表参数
neighbor  0.3 bin                     
neigh_modify  every 20 delay 0 check no
#nve系综
timestep 0.001
#fix 1 all box/relax scaleyz value  yes scalexz value yes scalexy value  yes
#fix		1 all nve      
#fix 1 all deform 1 x scale 0.960 y scale 0.960 z scale 0.960  
#fix 1 all box/relax 0.960 0.960 0.960              
thermo		500                           
thermo_style custom step pe ke temp vol press
min_style        cg#算法
minimize        1.0e-12 1.0e-12 1000 1000#最小化条件 
#fix 1 all box/relax scaleyz value  yes scalexz value yes scalexy value  yes
#run  10000	                    
#计算单原子能量=总势能/原子个数
variable Ecoh equal pe/count(all)  
print "Cohesive Energy (eV/atom):  ${Ecoh}"

**Comment by e-724** [comment]
This problem how to solve it why turn off

**Comment by akohlmey** [comment]
> This problem how to solve it why turn off

As the submission template already said. This is not the right place to ask for help.

There are explanations in the manual about the requirements for triclinic boxes in LAMMPS.
Your simulation obviously does not comply with it. Thus it is not so much a LAMMPS issue,
but a question of you not following the requirements. You should study what is said in the
manual and if you have still questions, you can post questions in the LAMMPS category of the 
Materials Science Discourse forum at https://matsci.org/lammps
