### ISSUE TITLE
ERROR: Triclinic box skew is too large

### ISSUE THREAD

**Issue by e-724** [lammps/lammps#3506]
I want to optimize the lattice parameters of low-temperature phase quartz, and this problem appears, how can I solve it?

in.SiO2

#模型基本设置
units    metal                       
atom_style  atomic                      
boundary        p p p                        
read_data SiO2.data
#fix 1 all box/relax yes yes yes 
#box tilt large
change_box all x scale 0.960 y 0.960  z 0.960
box tilt large
fix 1 all box/relax 
#fix 1 all deform 1 x scale 0.960 y scale 0.960 z scale 0.960
#fix 1 all box/relax scaleyz value no  scalexz value no  scalexy value  no
#设置力场
pair_style vashishta
pair_coeff * * SiO.1997.vashishta O Si
#设置邻居列表参数
neighbor  0.3 bin                     
neigh_modify  every 20 delay 0 check no
#nve系综
timestep 0.001
#fix 1 all box/relax scaleyz value  yes scalexz value yes scalexy value  yes
#fix		1 all nve      
#fix 1 all deform 1 x scale 0.960 y scale 0.960 z scale 0.960  
#fix 1 all box/relax 0.960 0.960 0.960              
thermo		500                           
thermo_style custom step pe ke temp vol press
min_style        cg#算法
minimize        1.0e-12 1.0e-12 1000 1000#最小化条件 
#fix 1 all box/relax scaleyz value  yes scalexz value yes scalexy value  yes
#run  10000	                    
#计算单原子能量=总势能/原子个数
variable Ecoh equal pe/count(all)  
print "Cohesive Energy (eV/atom):  ${Ecoh}"

**Comment by akohlmey** [comment]
This is not a bug, and this is not the right place to discuss this. Please see my comment to the other issue you created.
Please refrain from creating further issues. They will be closed and locked.
