### ISSUE TITLE
[Bug] Correction of BO in ReaxFF

### ISSUE THREAD

**Issue by advancesoftcorp** [lammps/lammps#3515]
In the following code, valency_val is used to calculate Deltap_boc.
But, valency_boc has to be used ?

https://github.com/lammps/lammps/blob/9cbc77f41cb4cbec517693925a7df2747c01cbb4/src/REAXFF/reaxff_bond_orders.cpp#L271-L272

**Comment by athomps** [comment]
@advancesoftcorp  This is somewhat surprising, but not obviously wrong.  Due to limited resources, we have to adopt the "innocent until proven guilty" principle. Do you have any proof that is wrong?

**Comment by advancesoftcorp** [comment]
Sorry, I have misunderstood the definitions of the variables. The code is not wrong.
I had believed that valency_boc = Val(boc) and valency_val = Val(angle), where Val(boc) and Val(angle) are defined at supporting information of https://pubs.acs.org/doi/10.1021/jp709896w as Eq.(3b) and (13e).
However, it seems that valency_val = Val(boc) and valency_boc = Val(angle).

**Comment by athomps** [comment]
@advancesoftcorp It is interesting that the variable names seem to be the reverse of their mathematical counterparts. but in the absence of an actual error in the code, I think we should leave it as is.
