### ISSUE TITLE
The time "other" represents

### ISSUE THREAD

**Issue by F-Rockman** [lammps/lammps#3557]
**Summary**

In the output of Lammps, the time "other" means all the remaining time. I want to know what Lammps exactly do during "other" in addition to the running overhead. Thank you!

**Comment by akohlmey** [comment]
Please note, that this is not the right place to ask such questions. A better place is the LAMMPS forum at https://matsci.org/lammps

To answer your question, the category Other contains *exactly* what its name says: it literally is the walltime left after subtracting all the other categories. That is how it is determined.

**Comment by F-Rockman** [comment]
OK, I see. Thank you for your reply.
