### ISSUE TITLE
DPD with special bonds

### ISSUE THREAD

**Issue by vklip** [lammps/lammps#3563]
**Summary**

Using non-standard special_bonds weights in DPD packages breaks the fluctuation-dissipation theorem and thus samples wrong temperatures.

**Expected Behavior**

Correct temperatures with special bond weights which are not 0 or 1.

The problem is, that the weighting factor (called dpd_factor within the code) scales the complete forces. This is consisted with how normal LJ interactions are treated, but if the dpd_factor is not 0.0 or 1.0, it breaks the fluctuation dissipation theorem, as dissipative forces and random forces would have to be scaled differetly. This can be very easily solved by  not scaling the total forces, but the dissipative force by dpd_factor and the random force by sqrt(dpd_factor). 

While this case seems to be niche, it is easily solvable and would improve the usage of special bonds in DPD packages.

**Comment by akohlmey** [comment]
@vklip I have confirmed your issue and implemented and tested the necessary changes in pull request #3575. With those changes, target temperatures are now maintained when special_bond factors are not 0 or 1.
