### ISSUE TITLE
Inconsistency in documentation of fix dpd/ext(/tstat)

### ISSUE THREAD

**Issue by vklip** [lammps/lammps#3564]
According to the documentation (https://docs.lammps.org/pair_dpd_ext.html#pair-style-dpd-ext-tstat-command)
the transverse coefficients are supposed to be given before the parallel coefficients. In its implementation the parallel coefficients are read first.

**Comment by akohlmey** [comment]
Thanks for your note. I have confirmed the issue and the documentation will be updated soon.
