### ISSUE TITLE
[BUG] _Fix rigid/npt does not keep bond lengths and angles rigid in SWM4-ndp water molecules

### ISSUE THREAD

**Issue by gullbrekken** [lammps/lammps#3578]
**Summary**

`Fix rigid/npt` does not keep bond lengths and angle rigid of the SWM4-ndp water molecules when the Nosé-Hoover thermostat is used with `fix drude/transform/direct` and `fix drude/transform/inverse.`

**LAMMPS Version and Platform**

LAMMPS (3 Nov 2022)
Operating system: CentOS Linux release 7.9.2009 (Core)
Hardware/CPU: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz

**Expected Behavior**

`Fix rigid/npt` keeps bond lengths and angles constant, or with very small variations (machine precision).

**Actual Behavior**

Bond lengths (O-M and O-H) vary with at least up to 0.3 Å over time (several ns). H-O-H angle also varies by 0.3 degrees in much shorter time.

**Steps to Reproduce**

Run in.example.txt using data.swm4-ndp.txt as data (system) file.

**Further Information, Files, and Links**

Input file, data file and output files attached.

[in.example.txt](https://github.com/lammps/lammps/files/10315674/in.example.txt)
[log.lammps.txt](https://github.com/lammps/lammps/files/10315675/log.lammps.txt)
[OH_bond.dump.txt](https://github.com/lammps/lammps/files/10315676/OH_bond.dump.txt)
[OM_bond.dump.txt](https://github.com/lammps/lammps/files/10315677/OM_bond.dump.txt)
[data.swm4-ndp.txt](https://github.com/lammps/lammps/files/10315678/data.swm4-ndp.txt)
[HOH_angle.dump.txt](https://github.com/lammps/lammps/files/10315679/HOH_angle.dump.txt)

**Comment by gullbrekken** [comment]
FYI: `Fix langevin/drude` keeps bond lengths and angle rigid in the SWM4-ndp water molecules.

Edit: When using `fix langevin/drude` in combination with `fix rigid/npt`, the water molecule is rigid.

**Comment by ndtrung81** [comment]
@gullbrekken If you moved the line `fix RIGID ATOMS rigid/npt molecule temp ${TK} ${TK} 100 iso ${PBAR} ${PBAR} 500` after the line `fix drude/transform/inverse`, would the water bonds and angles be rigid?

**Comment by gullbrekken** [comment]
@ndtrung81 Yes, that seems to work better. The H-O-H angles are maintained at 104.52 degrees. The O-M bonds also look correct. The O-H bonds are a lot better maintained than before. Average O-H bond length after 2000 steps is now 0.9575 Å as opposed to 0.9563 Å (original results). Initially, the O-H bonds are 0.9572 Å. Definitely good enough for me :)

**Comment by gullbrekken** [comment]
The Drude particles are not correctly thermostatted if the `fix RIGID ATOMS rigid/npt molecule temp ${TK} ${TK} 100 iso ${PBAR} ${PBAR} 500` is moved after the `fix drude/transform/inverse` line. They have a temperature of about 7 K instead of 1 K ...

**Comment by akohlmey** [comment]
@gullbrekken you have a conceptual problem with fix rigid/npt here. When adjusting the box for non-rigid particles, particles are converted to fractional coordinates, the box adjusted and the coordinates converted back. That will scale the positions according to the change in the box. with rigid objects, the same procedure is applied to the center of mass of the rigid objects, but the positions are always "reconstructed" from the internal geometry of the object, the center of mass and the orientation. That way the relative geometry is (mostly) preserved. however, that results in a problem for your drude oscillator particles, their positions are rescaled as if you would be using fix npt (without rigid). So their positions are no longer consistent with the atom they were connected to.

Not sure what is a good way to address this. You could experiment with only changing the box and not rescaling positions:
```
group none empty
fix RIGID ATOMS rigid/npt molecule temp ${TK} ${TK} 100 iso ${PBAR} ${PBAR} 500 dilate none
```
But that now introduces some inconsistency between molecules in the center and molecules at the edges/sides of the box. A consistent solution would require the drude oscillator particles to be temporarily included into the rigid bodies they belong to, but I have no idea how one would go about implementing it.

**Comment by gullbrekken** [comment]
@akohlmey The drude temperature is correct as long as the `fix RIGID ATOMS rigid/npt molecule temp ${TK} ${TK} 100 iso ${PBAR} ${PBAR} 500` line is between the `fix drude/transform/direct` and `fix drude/transform/inverse`  lines. So I think the drude particles are behaving correctly, it's just that the water molecules aren't sufficiently rigid the way it is implemented now. Your explanation regarding why the drude particles' temperatures is wrong when `fix RIGID ATOMS rigid/npt molecule temp ${TK} ${TK} 100 iso ${PBAR} ${PBAR} 500` is outside of the coordinate system conversion is correct, I think.

**Comment by akohlmey** [comment]
We are adding a warning for this use case to the code. Not sure what else we can do. There is probably some special case code needed, but that is beyond my level of knowledge of the methods involved.
