### ISSUE TITLE
[BUG] _atomic forces after calling dynamical_matrix command

### ISSUE THREAD

**Issue by vitorcoluci** [lammps/lammps#3583]
**Summary**

Calculation using the dynamical_matrix command has presented differences in atomic forces before and after calling the command. I believe the problem is that a force updating ( via update_force() ) is missing after line 342 in ˜/lammps-23Jun2022/src/dynamical_matrix.cpp . This is correctly done in lines 300 and 317 in dynamical_matrix.cpp.

**LAMMPS Version and Platform**

LAMMPS (23 Jun 2022 - Update 1)
MacOS 11.6, iMac Chip Apple M1

**Expected Behavior**

The atomic forces should not be modified by calling the command.

**Actual Behavior**

The atomic forces before calling the command are different from after calling it.

**Steps to Reproduce**

The input below sets up an calculation of an atomic chain where the forces are printed before and after calling the dynamical_matrix command. 

*Lammps input:*

units metal
dimension    3
boundary     p f f
atom_style   molecular
lattice custom 1.0 a1 1.0 0.0 0.0 a2 0.0 15.0 0.0 a3 0.0 0.0 15.0 basis 0.0 0.0 0.0
region    box1 block -5.5 5.5 -10.0 10.0 -10.0 10.0 units box
region    box2 block -5.0 5.0 -5.0 5.0 -5.0 5.0 units box
create_box  1 box1 bond/types 1 extra/bond/per/atom 2
create_atoms 1 region box2
mass 1 12.0

bond_style      harmonic
bond_coeff 1 1.724 1.0

kspace_style none
pair_style morse 1.6
pair_coeff * * 0.0 1.0 1.0 1.6 

create_bonds many all all 1 0.9 1.2
neighbor       0.0 bin
neigh_modify   once yes

run_style verlet
timestep 0.0001
run 0 post no

write_dump all custom before.dat id x y z vx vy vz fx fy fz
dynamical_matrix all regular 0.001 file D-matrix.dat
write_dump all custom after.dat id x y z vx vy vz fx fy fz

**Further Information, Files, and Links**

The resulting files *before.dat* and *after.dat* show the differences in the atomic forces.

*----before.dat-----*

ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
11
ITEM: BOX BOUNDS pp ff ff
-5.5000000000000000e+00 5.5000000000000000e+00
-1.0000000000000000e+01 1.0000000000000000e+01
-1.0000000000000000e+01 1.0000000000000000e+01
ITEM: ATOMS id x y z vx vy vz fx fy fz
1 -5 0 0 0 0 0 0 0 0
2 -4 0 0 0 0 0 0 0 0
3 -3 0 0 0 0 0 0 0 0
4 -2 0 0 0 0 0 0 0 0
5 -1 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 1 0 0 0 0 0 0 0 0
8 2 0 0 0 0 0 0 0 0
9 3 0 0 0 0 0 0 0 0
10 4 0 0 0 0 0 0 0 0
11 5 0 0 0 0 0 0 0 0

*----after.dat----*

ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
11
ITEM: BOX BOUNDS pp ff ff
-5.5000000000000000e+00 5.5000000000000000e+00
-1.0000000000000000e+01 1.0000000000000000e+01
-1.0000000000000000e+01 1.0000000000000000e+01
ITEM: ATOMS id x y z vx vy vz fx fy fz
1 -5 0 0 0 0 0 -1.724e-06 0 -1.724e-09
2 -4 0 0 0 0 0 3.06244e-15 0 0
3 -3 0 0 0 0 0 0 0 0
4 -2 0 0 0 0 0 0 0 0
5 -1 0 0 0 0 0 -3.82805e-16 0 0
6 0 0 0 0 0 0 0 0 0
7 1 0 0 0 0 0 0 0 0
8 2 0 0 0 0 0 1.14841e-15 0 0
9 3 0 0 0 0 0 2.29683e-15 0 0
10 4 0 0 0 0 0 1.724e-06 0 -1.724e-09
11 5 0 0 0 0 0 0 0 3.448e-09

**Comment by akohlmey** [comment]
Forces are only in a defined state *directly* after a "run" command. Any command that will execute a force computation (on a potentially manipulated system) will modify them and any command that will modify the system (e.g. add new atoms or change atom types or pair styles) will lead to an undefined state. The best illustration for that principle is that forces are not set before the *first* run (or minimize or similar) command.

Thus, if you want consistent forces with your geometry, you *must* execute a "run 0" command.
