### ISSUE TITLE
[BUG] Can't build CUDA KOKKOS with CUDA 12 and cmake

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#3584]
**Summary**

Trying to use cmake for LAMMPS compilation with KOKKOS fails if CUDA 12 is installed.

**LAMMPS Version and Platform**

Current develop

**Expected Behavior**

Cmake should correctly prepare files for compilation.

**Actual Behavior**

An error appears:
`nvcc fatal   : Value 'sm_35' is not defined for option 'gpu-architecture'`

Followed by errors from the cmake itself:

```
CMake Error at /tmp/lammps/lib/kokkos/cmake/kokkos_compiler_id.cmake:12 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /tmp/lammps/lib/kokkos/cmake/kokkos_compiler_id.cmake:53 (kokkos_internal_have_compiler_nvcc)
  /tmp/lammps/lib/kokkos/cmake/kokkos_tribits.cmake:215 (INCLUDE)
  /tmp/lammps/lib/kokkos/CMakeLists.txt:188 (KOKKOS_SETUP_BUILD_ENVIRONMENT)


-- SERIAL backend is being turned on to ensure there is at least one Host space. To change this, you must enable another host execution space and configure with -DKokkos_ENABLE_SERIAL=OFF or change CMakeCache.txt
-- Using -std=c++14 for C++14 standard as feature
CMake Error at /tmp/lammps/lib/kokkos/cmake/kokkos_test_cxx_std.cmake:132 (MESSAGE):
  Invalid compiler for CUDA.  The compiler must be nvcc_wrapper or Clang or
  NVC++ or use kokkos_launch_compiler, but compiler ID was GNU
Call Stack (most recent call first):
  /tmp/lammps/lib/kokkos/cmake/kokkos_tribits.cmake:242 (INCLUDE)
  /tmp/lammps/lib/kokkos/CMakeLists.txt:188 (KOKKOS_SETUP_BUILD_ENVIRONMENT
```

**Steps to Reproduce**

Install CUDA 12.0, and run following lines:
```
git clone https://github.com/lammps/lammps
cd lammps
mkdir build
cd build
cmake -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=yes ../cmake
```

The issue also appears if a GPU architecture is specified, e.g. `-D Kokkos_ARCH_AMPERE86=yes` is added.

**Further Information, Files, and Links**

The issue arises from the `nvcc_wrapper` script which uses `sm_35` as a default architecture and it was removed in CUDA 12:
https://github.com/lammps/lammps/blob/f84b64bc869003320ccc3b83e8cfe428d9b87f0f/lib/kokkos/bin/nvcc_wrapper#L15-L16

This problem is solved if the line with `sm_35` is commented and the next one uncommented, but I think it should documented somewhere.

**Comment by akohlmey** [comment]
Please note that this is not really a bug in LAMMPS but a Kokkos issue. An update to the latest Kokkos release is still pending... https://github.com/lammps/lammps/pull/3532

**Comment by akohlmey** [comment]
We'll probably have to update the GPU package as well.

**Comment by mkanski** [comment]
Yes, you are right. Do you think I should open a bug report there and close this one?

**Comment by akohlmey** [comment]
> Yes, you are right. Do you think I should open a bug report there and close this one?

I would expect that the Kokkos folks are already aware of it. There is supposed to be a new major release (4.0) soon. My expectation is that that version will address it. Of course, it doesn't hurt to check.

I would leave the issue open since a) we may consider backporting the possible fix to the already pending PR and b) it is good to keep this as a reminder to check for compatibility (also for the GPU package).

Once the pending Kokkos update PR is merged, it may be possible for you to compile/link with a Kokkos 4.0 pre-release version and check for compatibility with CUDA 12.

I will leave the ultimate decision to @stanmoore1 since Kokkos is his turf.

**Comment by akohlmey** [comment]
> We'll probably have to update the GPU package as well.

GPU package make and cmake settings and documentation have been updated in d9abc3fcc0f84757f1a666b509b6a0d810a9e925 as part of PR #3574

**Comment by stanmoore1** [comment]
Yes this has been fixed in upstream Kokkos, see https://github.com/kokkos/kokkos/commit/f64e5a66db145ffb8c6dd61b649ab914ddbc058a. I've heard that Kokkos 4.0 is coming out soon (in the next few weeks).

**Comment by stanmoore1** [comment]
I will backport that change to https://github.com/lammps/lammps/pull/3532 since it is just changing the default version.

**Comment by busce004** [comment]
I encountered the same error  trying to install Kokkos with cuda 12.1.   In  trying various work-arounds I found the following results which might help.  

Notable is the recognition of the  device parallel , but host parallel is still "NoTypeDefined"   At this point, I do not know if lammps will operate with Kokkos  or fall back into serial mode.    

The simple commands:
cmake   ..    -DKokkos_ENABLE_CUDA:BOOL=ON   ../cmake

resulted in:

Setting default Kokkos CXX standard to 14
-- The project name is: Kokkos
-- Compiler Version: 12.0.140
-- kokkos_launch_compiler (/home/ao/Desktop/kokkos-3.7.01/bin/kokkos_launch_compiler) is enabled...
-- Using -std=c++14 for C++14 standard as feature
-- CUDA auto-detection of architecture failed with /usr/bin/c++. Enabling CUDA language ONLY to auto-detect architecture...
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- The CUDA compiler identification is NVIDIA 12.0.140
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Detected CUDA Compute Capability 86
-- Setting Kokkos_ARCH_AMPERE86=ON
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL

Architectures:
--  AMPERE86
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.0.140") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found TPLCUDA: TRUE  
-- Using internal desul_atomics copy
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xx/Desktop/kokkos-3.7.01/build


and the command

 cmake   ..    
-DKokkos_ENABLE_CUDA:BOOL=ON \
-D Kokkos_ENABLE_CUDA=ON \
-D Kokkos_ARCH_AMPERE80=ON \
-D Kokkos_ENABLE_CUDA_LAMBDA=ON \
 ../cmake

resulted in

-- Setting default Kokkos CXX standard to 14
-- The project name is: Kokkos
-- Compiler Version: 12.0.140
-- kokkos_launch_compiler (/home/ao/Desktop/kokkos-3.7.01/bin/kokkos_launch_compiler) is enabled...
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  AMPERE86
-- Using internal desul_atomics copy
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xx/Desktop/kokkos-3.7.01/build

the commands produced the  "NoTypeDefined" error
cmake ../
-D Kokkos_ENABLE_CUDA=ON \
-D Kokkos_ARCH_AMPERE80=ON \
-D Kokkos_ENABLE_CUDA_LAMBDA=ON \
-D Kokkos_ENABLE_SERIAL=OFF \
-D Kokkos_ENABLE_TESTS=ON \
 -D CMAKE_CXX_COMPILER=/usr/local/cuda/bin/nvcc  \
../cmake

OS linux mint 21.1,  RTX 3090, toolkit 12.1  g++  11.3

**Comment by akohlmey** [comment]
> OS linux mint 21.1, RTX 3090, toolkit 12.1 g++ 11.3

Please note that this information is inconsistent. The cmake output shows that CUDA 12.0 was found and used.

Please create a new build folder (or delete the current one), then edit the file cmake/presets/kokkos-cuda.cmake as needed for your system (typically that would just be the GPU arch).

Then in the new build folder use the cmake command line as if you want to configure it for CPU and add -C ../cmake/presets/kokkos-cuda.cmake.

This should pick up on all the necessary settings and configure successfully. I have not yet tested with 12.1.
Best provide the full CMake output and the CMakeCache.txt file in case there still are issues.

**Comment by busce004** [comment]
Thank you Alex for the response.  greatly appreciated - it's been a long haul.
I'm not sure what you meant by inconsistent.  With the simpler first cmake command Kokkos had to go hunt for the toolkit, but it seems to have been found in both cases- at least by Kokkos.  I am still  not sure Lammps will agree with me.  I am also concerned about  'host parallel'  to make use of the multicore cpu and hope that adding enable_threads might cure the 'NoTypeDefined'  (btw,  the bold type was not intentional )

**Comment by busce004** [comment]
I can compile lammps to run with cuda or with kokkos in serial mode, but not both.  Essentially I cannot get the backend to read kokkos =gpu when compiling lammps. here are the conditions:


Issue: in running lammps cannot get cuda and kokkos to both function

OS:  Release Linux Mint 21.1 Vera 64-bit,  AMD TR 32 core, 64G RAM, 2xRTX3090,lammps-8Feb2023, kokkos 3.7

What works;
	compilation of kokkos such that Kokkos backend recognizes Threads, cuda
	
	cuda 12 compiled using default nvidia downloads. CUDA functions well on gromacs, vmd, maestro , nvidia-smi

	With a single compilation of kokkos and  changing the box size to use 320,000 atoms in the bench lj model provided  in   lammps
	mpirun -np 4 lmp-kocu -sf gpu -pk gpu 2 -in in.lj   189 MAS/s

	mpirun -np 8 lmp-kocu -k on t 8 -sf kk -in in.lj     14 MAS/s


what does not work , 
       mpirun -np 8 lmp-kocu -k on t 8 -sf kk g 2 -in in.lj  
       results in : "GPUs are requested but Kokkos has not been compiled using a GPU-enabled backend "
 

Requested: what further information does cmake require to convince Lammps that the kokkos backend =CUDA ?
Suspect compiler mismatch between cuda ( nvcc ), kokkos, and lammps


===============================Details:=====================================

kokkos compilation:

 =========================== compilation /install with no errors or warnings ===================
cmake  ../ -D Kokkos_ENABLE_THREADS=ON  -D Kokkos_ENABLE_CUDA=ON  -DKokkos_ARCH_AMPERE80=ON -D Kokkos_ENABLE_CUDA_LAMBDA=ON  ../cmake

Kokkos_ENABLE_CUDA=ON  -DKokkos_ARCH_AMPERE80=ON -D Kokkos_ENABLE_CUDA_LAMBDA=ON  ../cmake
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- The project name is: Kokkos
-- Compiler Version: 12.0.140
-- kokkos_launch_compiler (/home/ao/Desktop/kokkos-3.7/bin/kokkos_launch_compiler) is enabled...
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: Kokkos::Threads
--       Host Serial: NONE
-- 
-- Architectures:
--  AMPERE80
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.0.140") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found TPLCUDA: TRUE  
-- Found TPLLIBDL: /usr/include  
-- Found TPLTHREADS: TRUE  
-- Using internal desul_atomics copy
-- Kokkos Devices: THREADS;CUDA, Kokkos Backends: THREADS;CUDA
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xx/Desktop/kokkos-3.7/build

======================================================================

======== Lammps compilation ====this compiled/installed but ======================

cmake  ../cmake/presets/most (or minimal ) 
.cmake  -D PKG_GPU=on -D GPU_API=cuda  -DCMAKE_CUDA_ARCHITECTURES=86 -D Kokkos_ENABLE_OPENMP=ON -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=ON  ../cmake 
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Running check for auto-generated files from make-based build system
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for C++ include omp.h
-- Looking for C++ include omp.h - found
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: CXX 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found GZIP: /usr/bin/gzip  
-- Found FFMPEG: /usr/bin/ffmpeg  
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Setting default Kokkos CXX standard to 14
-- The project name is: Kokkos
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: Kokkos::OpenMP
--       Host Serial: NONE
-- 
-- Architectures:
-- Found TPLLIBDL: /usr/include  
-- Using internal desul_atomics copy
-- Kokkos Devices: OPENMP, Kokkos Backends: OPENMP
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "12.0") 
CMake Warning at Modules/Packages/GPU.cmake:102 (message):
  Untested CUDA Toolkit version 12.0.  Use at your own risk
Call Stack (most recent call first):
  CMakeLists.txt:672 (include)


-- Generating style headers...
-- Generating package headers...
-- Generating lmpinstalledpkgs.h...
-- Found ClangFormat: /usr/bin/clang-format (found suitable version "14.0.0", minimum required is "8.0") 
-- The following tools and libraries have been found and configured:
 * Git
 * MPI
 * OpenMP
 * JPEG
 * PNG
 * ZLIB
 * TPLLIBDL
 * Threads
 * CUDA
 * ClangFormat (required version >= 8.0)

-- <<< Build configuration >>>
   LAMMPS Version:   20230208
   Operating System: Linux Linux Mint 21.1
   CMake Version:    3.22.1
   Build type:       RelWithDebInfo
   Install path:     /home/ao/.local
   Generator:        Unix Makefiles using /usr/bin/gmake
-- Enabled packages: GPU;KOKKOS
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          GNU
      Version:       11.3.0
      C++ Flags:     -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;LAMMPS_FFMPEG;$<BUILD_INTERFACE:LMP_KOKKOS>;LMP_GPU
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:    
-- <<< MPI flags >>>
-- MPI_defines:      MPICH_SKIP_MPICXX;OMPI_SKIP_MPICXX;_MPICC_H
-- MPI includes:     /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi
-- MPI libraries:    /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so;
-- <<< GPU package settings >>>
-- GPU API:                  CUDA
-- CUDA Compiler:            /usr/local/cuda/bin/nvcc
-- GPU default architecture: sm_50
-- GPU binning with CUDPP:   OFF
-- CUDA MPS support:         OFF
-- GPU precision:            MIXED
-- Kokkos Devices: OPENMP
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ao/Desktop/lammps-8Feb2023/build-test


=======================  leaving out ENABLE OPENMP leads to no parallel device defined ===============
cmake  ../cmake/presets/most.cmake  -D PKG_GPU=on -D GPU_API=cuda  -DCMAKE_CUDA_ARCHITECTURES=86 -D Kokkos_ENABLE_THREADS=on -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=ON  ../cmake 

-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Running check for auto-generated files from make-based build system
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Looking for C++ include omp.h
-- Looking for C++ include omp.h - found
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: CXX 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found GZIP: /usr/bin/gzip  
-- Found FFMPEG: /usr/bin/ffmpeg  
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Setting default Kokkos CXX standard to 14
-- The project name is: Kokkos
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: Kokkos::Threads
--       Host Serial: NONE
