### ISSUE TITLE
incorrect mass density in fix_ave_chunk.cpp when using norm sample or norm none

### ISSUE THREAD

**Issue by vargaslo** [lammps/lammps#359]
The density/mass is correctly calculated when using "norm all", but not for "norm sample" or "norm none".
I believe the unit conversion is missing for the latter two cases. In line 856, the mass density is multiplied by a factor of mv2d (mass/volume to density conversion). This same factor is missing in line 867 for the case of DENSITY_MASS.

**Comment by vargaslo** [comment]
Maybe I spoke too soon. I am not sure I correctly diagnosed this yet.

**Comment by akohlmey** [comment]
then please confirm it, best by attaching a simple input demonstrating the issue or delete the issue if the code is working as it says in the documentation. thanks.

**Comment by vargaslo** [comment]
units real

# create simulation box (volume = 1000 cubic Angstrom)
region world block 0 10  0 10  0 10
create_box 1 world

# add 100 atoms (total mass = 100 g/mol)
mass 1 1.0
pair_style lj/cut 12.
pair_coeff 1 1 0. 0.
create_atoms 1 random 100 2546954 NULL

# binning into a single bin for simplicity (bin size 10A)
compute binchunks all chunk/atom bin/1d z lower 10.

# Calculate density profile of bins (density should be 0.1 g/mol/A3 or 0.166 g/cm3)
fix profile1 all ave/chunk 2 3 10 binchunks density/mass file mass_density_profile_1.out ave running overwrite norm all
fix profile2 all ave/chunk 2 3 10 binchunks density/mass file mass_density_profile_2.out ave running overwrite norm sample
fix profile3 all ave/chunk 2 3 10 binchunks density/mass file mass_density_profile_3.out ave running overwrite norm none

run 100

**Comment by akohlmey** [comment]
ok. i see what you mean. I'll label this as a bug, but i'll have to discuss with other developers how to approach solving this without having to create too much duplicated and difficult to maintain code.

**Comment by sjplimp** [comment]
Believe I've fixed this - will be in next patch, later this week.

Steve
