### ISSUE TITLE
[Feature Request] Enabling required packages automatically (with CMake)

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#3609]
**Summary**

With CMake it is possible to install a required package instead of stopping with a error.

**Detailed Description**

Currently, we have a few "hard" dependencies between packages.
- ML-IAP requires ML-SNAP
- ATC requires MANYBODY
- AMOEBA requires KSPACE
- DIELECTRIC requires KSPACE and EXTRA-PAIR
- CG-DNA requires MOLECULE and ASPHERE
- ELECTRODE requires KSPACE
- EXTRA-MOLECULE requires MOLECULE

Currently, if the prerequisite package is not installed, LAMMPS will stop with an error.
While it is simple to just install the package and continue, it would be even more convenient if LAMMPS would just automatically install the package by itself and thus there would be no error at all. This would be particularly convenient for people that use automated tools or scripts to compile and install or package LAMMPS. In that use case a new dependency would simple install an additional package instead of breaking the script and requiring an update.

Implementing this in CMake would be straightforward. With the traditional make build procedure it is rather more complicated, since this also would have to trigger re-running the dependencies, so there is a risk of it becoming slow and small risk of a deadlock, if a dependency requires another dependency. So I am hesitant to implement it for both build systems. I don't think that this is a big problem, since most automated builds and package creation scripts are likely using CMake.

I am asking for feedback on this before implementing it, because this change would introduce different behavior between the two build systems and - so far - we have tried to keep them to a minimum. Please comment below.

**Comment by athomps** [comment]
This would be a useful feature for users who are building LAMMPS with Cmake.  The difference in behavior is acceptable, since in the case of traditional make  it is pretty clear what the problem is and what the required action is, while in the case of CMake, there will no longer be a problem.

**Comment by sjplimp** [comment]
I agree - seems like a good idea
