### ISSUE TITLE
[BUG] _Issue with fix nvt/kk_

### ISSUE THREAD

**Issue by mavanish** [lammps/lammps#3616]
Hello, LAMMPS community,
 
We recently came across an issue when using Kokkos accelerator package with fix nvt. When the fix operates on a group other than “all”, there is a difference in the resulting temperature between nvt (run on CPUs) and nvt/kk (CPUs+GPUs). Moreover, this difference appears to depend on the number of thermostatted atoms. The attached script reproduces this issue for a box of FCC atoms with fix nvt operating on a subset of the total atoms. One can readily see that the temperature of the mobile region (c_myTemp) reported by LAMMPS is different between nvt and nvt/kk. I dumped the velocities, and it appears that nvt/kk results in higher velocities and potential energy for the thermostatted atoms. Following are the details of the runs:
 
LAMMPS version: 22 Dec 2022 (latest patch release), built with gcc, mpich.
Command line arguments= ['-k', 'on', 'g', '4', '-sf','kk','-pk', 'kokkos', 'neigh', 'half', 'newton', 'on']
 
Thank you for your attention. I hope the explanation is clear enough.  Please let me know if any further details are required.
[in.lmp.txt](https://github.com/lammps/lammps/files/10502709/in.lmp.txt)

Regards,
Avanish and Nithin

**Comment by stanmoore1** [comment]
@dravanish thanks for the bug report. I can reproduce the issue.

**Comment by stanmoore1** [comment]
I fixed this issue for Kokkos in 16225ac. @akohlmey is there a reason why `fix npt` and others use group `all`, see https://github.com/lammps/lammps/blob/develop/src/fix_npt.cpp#L35? It looks like a potential bug.

**Comment by stanmoore1** [comment]
I missed this comment for `fix npt`:
```
  // compute group = all since pressure is always global (group all)
  // and thus its KE/temperature contribution should use group all
```

**Comment by mavanish** [comment]
Thanks, I installed it by fixing those two lines, and the issue seems to be resolved.

**Comment by stanmoore1** [comment]
@dravanish Thanks for the confirmation!
