### ISSUE TITLE
[BUG] LAMMPS incorrectly converts non-numerical strings to numbers for evaluating math functions

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#3618]
**Summary**

I encountered an undocumented feature when using index-style (or string-style) variables in math functions. LAMMPS will quietly convert pure strings to 0 in such cases. Additionally, if the string starts with a number, e.g. "5a", LAMMPS will ignore everything after the first non-digit character and will use the first part as a number. I think an error should be raised instead.

**LAMMPS Version and Platform**

Current develop
Linux Mint 20.3

**Expected Behavior**

LAMMPS should raise an error about trying to use a non-numerical string in math functions.

**Actual Behavior**

LAMMPS assigns a string a value of 0 or use only the numerical part of the string in further calculations.

**Steps to Reproduce**

Use the following lines as an input script:

```
variable i index "a"
print "$(5+v_i)"
```

LAMMPS will output 5 as if variable `i` was equal to 0.

Second case:

```
variable i index "5a"
print "$(5+v_i)"
```

Here, LAMMPS will output 10 as if variable `i` was equal to 5.

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
@mkanski thanks for the bug report. I have confirmed it and a fix is on the way
5d941da4e911f0ef08a79e7476d131a72fe68307

The variable code is one of the few places, where we could not replace the calls to `atoi()` or `atof()` that were previously used all over the place in LAMMPS with `utils::inumeric()` or `utils::numeric()`, respectively. The behavior you observe is why those utility functions were introduced in the first place. In old versions of LAMMPS the same thing would happen to all kinds of input data.

**Comment by akohlmey** [comment]
If you want to have some more "fun" with this, you could search through the source code for uses of atoi() / atof() and see if you can construct inputs like this case where there still need to be checks added (if possible). I had done multiple passes of that over the years and am a bit surprised that you have found a case that has escaped the search. That said, the variable.cpp code is rather complex and difficult to change correctly without breaking something.

**Comment by mkanski** [comment]
Thanks for the fast fix, @akohlmey. I encountered this bug by chance due to a missing character in a bash script (`i` instead of `$i`) and it took me a moment to find why all simulation cycles were exactly the same. 

Frankly, the code in variable.cpp is a little too convoluted for me, so I'd prefer to stay as far from it as possible. :)
