### ISSUE TITLE
GitHub tarball checksum changed, broke automatic downloads in CMake (reverted by GitHub for now)

### ISSUE THREAD

**Issue by rbberger** [lammps/lammps#3626]
**Summary**

On [January 30, 2023](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/), GitHub downloads from `archive/` URLs returned tarballs with new checksums due to a new default compressor in `git archive`.

E.g. Kokkos 3.7.01 became 6a10752f4ef24fa58943f4ff5e20654c for MD5.

This broke automatic CMake downloads on all past releases.

**Update 1:** https://github.com/orgs/community/discussions/45830#discussioncomment-4823799 GitHub is pulling back their change (for now)

**LAMMPS Version and Platform**

all previous and current versions with CMake automatic downloads that use a MD5/SHA256 checksum.

**Details**

- https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1029861300
- https://twitter.com/thesayynn/status/1620129657977987073
- https://github.com/orgs/community/discussions/45830
- https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

**Comment by rbberger** [comment]
Keeping this open for now, since relying on GitHub archive URLs might break again in the future. One possible long-term solution is mirroring LAMMPS automatic download dependencies (like the kokkos tarball) directly on `lammps.org`.

**Comment by akohlmey** [comment]
I don't like making download.lammps.org the primary source of all external libraries, but after looking through the CMake documentation for external projects, it seems we can enter multiple URLs which are tried in succession, so download.lammps.org could serve as a fallback.

That will buy us some time in case the the checksums change again. It makes the refactoring of accessing remote content more urgent.

**Comment by rbberger** [comment]
https://github.com/orgs/community/discussions/46034
