### ISSUE TITLE
[BUG] _Replace With Suitable Title_

### ISSUE THREAD

**Issue by athomps** [lammps/lammps#3634]
**Summary**

For`file` variables, `reader[n]` is not set to `nullptr` in `remove()`. This causes segfaults in some scripts.

**LAMMPS Version and Platform**

All

**Expected Behavior**

No seg-fault should occur.

**Actual Behavior**

Seg-fault

**Steps to Reproduce**

This script gives a seg-fault

```
variable a file foo.txt
next a
variable b equal 1
```

`foo.txt` should contain a single line

The solution is:

```
diff --git a/src/variable.cpp b/src/variable.cpp
index e5b192c..78346ab 100644
--- a/src/variable.cpp
+++ b/src/variable.cpp
@@ -1201,6 +1199,7 @@ void Variable::remove(int n)
   delete reader[n];
+  reader[n] = nullptr;
```

I am posting it as a bug, not a PR, because there may be similar instances.

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
I think this fix will only work for this special case where there is no other variable. If I read the code correctly, the fix should be more like this commit 6707ab61823b4c2ce41cda6b328dde0202e18413

This bug must have been in the code for quite some time...
Definitely a fix for the update, too.

**Comment by akohlmey** [comment]
> This bug must have been in the code for quite some time...

According to git blame for about ten years.

**Comment by athomps** [comment]
Yes, your version is much cleaner and more comprehensive.  I confirmed that it eliminates the segfault.
