### ISSUE TITLE
[BUG] compute reduce command gives same output for sum and ave (average)

### ISSUE THREAD

**Issue by vikaskok** [lammps/lammps#3640]
**Summary**

LAMMPS 'compute reduce' command when applied to fix wall/gran (GRANULAR package) seems to give same output for sum as well as average.

**LAMMPS Version and Platform**
lammps-stable-03nov2022

**Expected Behavior**
'compute reduce sum' is expected to give a (scalar) sum of the numbers in an array, and 'compute reduce ave' is expected to give a scalar average of the numbers in an array
**Actual Behavior**
'compute reduce sum': gives a (scalar) average of the numbers in an array - incorrect behaviour.
'compute reduce ave': gives a (scalar) average of the numbers in an array - correct behaviour.

**Steps to Reproduce**
I am attaching a script to reproduce the issue.
It will read two atoms into simulation box, drop them on to the floor (y-dir) under gravity.
During the run, total force and average force on walls is output via thermo command. It can be seen that both sum and ave force on y-walls is same in thermo output.
I am also attaching a log file of my run.
**Further Information, Files, and Links**
https://docs.lammps.org/compute_reduce.html
[atoms.txt](https://github.com/lammps/lammps/files/10674440/atoms.txt)
[computecheck.in.txt](https://github.com/lammps/lammps/files/10674444/computecheck.in.txt)
[log .lammps.txt](https://github.com/lammps/lammps/files/10674448/log.lammps.txt)

**Comment by akohlmey** [comment]
This is not a bug but documented behavior. You are using reduced units and then the default for thermodynamic output is to be normalized.  The sum of a property can be normalized (and thus LAMMPS does it), the average cannot (and thus LAMMPS does not do it). As it happens, the normalized value of a sum is the average and thus you have the same output.

Add `thermo_modify norm no` after the custom `thermo_style` to your input and you should see the difference.

**Comment by vikaskok** [comment]
Thank you so very much @akohlmey for the resolution.
I have tried the suggestion and it worked. The difference is now reflected in thermo output as well as in the data files generated using "fix print" command (which is what I needed).
