### ISSUE TITLE
[BUG] Fix gcmc region extends outside simulation box when using triclinic region

### ISSUE THREAD

**Issue by tomdemeyere** [lammps/lammps#3642]
**Summary**

fix gcmc command throws "fix gcmc region extends outside simulation" when using a triclinic box and a prism region that has any dimension larger than their box dimension minus their tilt.

**LAMMPS Version and Platform**

Operating System: Red Hat Enterprise Linux
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.9:GA:server
Kernel: Linux 3.10.0-1160.36.2.el7.x86_64
Architecture: x86-64

LAMMPS (23 Jun 2022 - Update 2) issue happening both on intel and gnu compiled versions

**Expected Behavior**

fix gcmc should run normally with the selected prism region as it does not physically go beyond the boundary of the box

**Actual Behavior**

ERROR: Fix gcmc region extends outside simulation box (src/MC/fix_gcmc.cpp:144)

**Steps to Reproduce**

When the user defines a triclinic box such as:

0.0      22.85  xlo xhi
0.0      13.22  ylo yhi
0.0      40.0  zlo zhi
10.08 0  0  xy xz yz

Define a subregion as region mc prism 0 EDGE 0 EDGE 25 32 10.08 0 0 which should restrict where atoms can be acted upon only along the z direction. With this setup any fix gcmc command using this region will not run, throwing "ERROR: Fix gcmc region extends outside simulation box (src/MC/fix_gcmc.cpp:144)". The biggest possible region is then: mc prism 0 $(22.85 - 10.08) 0 EDGE 25 32 10.08 0 0

**Further Information, Files, and Links**

Axel Kohlmeyer gave me a quick fix that is available at https://matsci.org/t/gcmc-region-triclinical-box-error/46594

Unfortunately, this fix seems to only work when LAMMPS is ran in serial mode. Using MPI will end up in either ERROR: Fix gcmc region extends outside simulation box (src/MC/fix_gcmc.cpp:**150**) or LAMMPS being frozen.

**Comment by tomdemeyere** [comment]
Sorry for the delay,

Actually it seems that the issue is also here when using rectangular boxes

The attached files will only run when mpi is not used. You can switch between the rectangular and trinical system if needed (uncomment region mc and change read_data)

[Archive.zip](https://github.com/lammps/lammps/files/10721749/Archive.zip)

**Comment by athomps** [comment]
PR #3652 should fix this.
