### ISSUE TITLE
[Feature Request] Always use the -DLAMMPS_EXCEPTIONS branch and remove the non-exception code path

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#3678]
**Summary**

Using the exception handling in LAMMPS has matured quite a bit over time. It is used by default by most precompiled binary packages and there have been no exception specific bug reports for quite some time.

While the major shortcoming - there is no mechanism to propagate exceptions across MPI - still exists, the number of benefits from enabling exceptions is growing.
The python module and LAMMPS shell benefit from it massively, also unit testing and auxiliary libraries are increasingly making use of exceptions, so adding a general catch-all handler is a good idea, too.

**Detailed Description**

This would mostly mean removal of the non-exception case of alternate code paths.
This would also allow to simplify some of the code.

**Comment by dxhisboy** [comment]
I think another thing to consider is how it will affect offloaded computation workloads, for example, CUDA, OpenCL or KOKKOS kernels.

> While the major shortcoming - there is no mechanism to propagate exceptions across MPI - still exists, the number of benefits from enabling exceptions is growing.

I think this can be handled by a catch in the `main` function that calls `MPI_Abort` to propagate across MPI.

**Comment by akohlmey** [comment]
> I think another thing to consider is how it will affect offloaded computation workloads, for example, CUDA, OpenCL or KOKKOS kernels.

It has been possible for a long time to compile with -DLAMMPS_EXCEPTIONS and check it out. I am not aware of any issues. If you have concerns, it is easy for you to test.

> I think this can be handled by a catch in the `main` function that calls `MPI_Abort` to propagate across MPI.

This is what is already done (and has been for quite a while).

**Comment by dxhisboy** [comment]
> It has been possible for a long time to compile with -DLAMMPS_EXCEPTIONS and check it out. I am not aware of any issues. If you have concerns, it is easy for you to test.

AFAIK Sunway's computation cores cannot support exceptions mechanism. Although it is never supported officially, I'm working on porting specific potentials to Sunway's computation cores since 2017. Removing `-DLAMMPS_EXCEPTIONS` is affordable, that can be translated to a special function call via compiler plugins in my opinion.

> This is what is already done (and has been for quite a while).

Sorry for disturbing. But it has been a long time from last time I peek `main.cpp`.

**Comment by akohlmey** [comment]
> AFAIK Sunway's computation cores cannot support exceptions mechanism. Although it is never supported officially. I'm working for a long time on it.

This is irrelevant. The exceptions this is about are thrown by the Error class instead of calling MPI_Abort() (for `Error::one()`) or MPI_Barrier() followed by MPI_Finalize() and exit() (for `Error::all()`).

**Comment by dxhisboy** [comment]
> > AFAIK Sunway's computation cores cannot support exceptions mechanism. Although it is never supported officially. I'm working for a long time on it.
> 
> This is irrelevant. The exceptions this is about are thrown by the Error class instead of calling MPI_Abort() (for `Error::one()`) or MPI_Barrier() followed by MPI_Finalize() and exit() (for `Error::all()`).

Thank you for reply, so I do not have further concern for removing `-DLAMMPS_EXCEPTIONS`.
