### ISSUE TITLE
sprintf deprecation warning on macOS

### ISSUE THREAD

**Issue by MacChemist** [lammps/lammps#3682]
I'm trying to install Lammps on macOS with cmake. When trying to build it, there are some errors with sprintf. Same problem was here with Gromacs.
https://github.com/beltoforion/muparser/issues/117
What should I do?
<img width="1330" alt="Zrzut ekranu 2023-03-8 o 10 42 55" src="https://user-images.githubusercontent.com/116869111/223678406-a2fbd455-037a-48d9-a956-a88246d33d3f.png">

**Comment by akohlmey** [comment]
> What should I do?

You could tell the Apple software engineers that they are morons.

These are just warnings and the places were LAMMPS uses `sprintf()` would not become any "safer" by using `snprintf()`, not to mention that an application software like LAMMPS does not pose a security risk for as long as it is used for what it was designed for. Check out https://github.com/lammps/lammps/blob/develop/SECURITY.md for more details on that.

You can try silencing the warning by adding `-DCMAKE_TUNE_FLAGS=-Wno-deprecated-declarations` to your cmake configuration line, but that is just the same as ignoring the warning.
