### ISSUE TITLE
[Feature Request] Inclusion of bond stretching contribution to "compute stress/mop"

### ISSUE THREAD

**Issue by evoyiatzis** [lammps/lammps#3683]
**Summary**

Currently,  "compute stress/mop" cannot treat systems with intramolecular interactions. A first improvement is to include contributions from bond stretching terms.

**Detailed Description**

The current implementation derives the force of individual pair contributions from the pair->single method. Similarly, the force of individual bond contributions can be derived from the bond->single method or the bond->born_matrix.

 The geometric criterion for inclusion or exclusion of a contribution of bonded particles to the local pressure tensor can be the same as the current criterion for inclusion of non-bonded interactions.

A method similar to the born_matrix->compute_bonds() can perform the summation of bond contributions. 

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
FYI, contact info of the authors of compute stress/mop is in the pull request https://github.com/lammps/lammps/pull/1092 (from 2018, so it may not be up-to-date but a starting point).

**Comment by evoyiatzis** [comment]
Thanks for the suggestion!
