### ISSUE TITLE
Some Kokkos atom_vec styles don't use ubuf union

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#369]
Some Kokkos atom_vec styles directly use a `double` buffer instead of the `ubuf` union, which could in theory lead to issues for very large systems

**Comment by stanmoore1** [comment]
Though the integer would have to be larger than what a double can hold and that would be very large indeed

**Comment by akohlmey** [comment]
The problem with 64-bit integers vs. storing them in doubles becomes an issue primarily with image flags, where the 64-bit integer is split into 3 21-bit signed integers and the least significant one will become corrupted, when the most significant one will become too big. This is primarily relevant for long-running flow simulations.

As a temporary measure, it might be advisable to spit out a warning stating that compilation with `-DLAMMPS_BIGBIG` is possible, but not supported and some known issues exist.

**Comment by stanmoore1** [comment]
Fixed by PR #457. Closed #369.
