### ISSUE TITLE
[BUG] Negative pressure for a dilute polymer solution

### ISSUE THREAD

**Issue by Birfy** [lammps/lammps#3692]
**Summary**

Unphysical negative pressure for a dilute polymer solution. 

**LAMMPS Version and Platform**

LAMMPS (23 Jun 2022 - Update 3) on Linux. 

**Expected Behavior**

I simulated a single polymer chain of 64 beads with no pairwise interactions in a large periodic box with lx=ly=lz=40 (which essentially is a very dilute solution). The bonded interaction are the FENE bond potential with K=30, R_0=1.5, epsilon=1.0, sigma=1.0. According to the ideal gas law, the expected osmotic pressure is positive and proportional to the concentration of the polymer, in this case 1/V where V is the volume of the simulation box.

**Actual Behavior**

The pressure obtained is negative which has an unphysical meaning that the dilute solution is collapsing. I computed the components of the pressure, which are

total pressure: -1.20174e-6
pressure from kinetic energy: 0.00100034
pressure from bond: -0.00100154

The pressure from kinetic energy equals to the concentration of beads, which seems correct. However, the bond contribution to pressure seems to overkill the total pressure to be negative.

**Steps to Reproduce**

Please use the attached input.in and input.data for reproducing this issue. The pressure is outputted in the file output_pressure.txt.

**Further Information, Files, and Links**

input.in

```
# General
units lj
dimension 3
boundary p p p
atom_style bond

# Neigbor lists
neighbor 0.50 bin
neigh_modify every 1 delay 1 check yes

#Initial State
read_data input.data

# Pairwise Potential (Non bonded interactions)
pair_style zero 1.5
pair_coeff * *

# Bonded interactions
bond_style fene
bond_coeff 1 30.0 1.5 1.0 1.0
special_bonds fene

# Fixes, Ensemble
compute presske all pressure thermo_temp ke # compute pressure of kinetic energy
compute pressbond all pressure thermo_temp bond # compute pressure of bond energy
compute press all pressure thermo_temp bond ke # compute pressure
fix 1 all nve
fix 2 all langevin 1.0 1.0 2.0 123
fix 3 all ave/time 1 $(1e7) $(1e7) c_press c_presske c_pressbond file output_pressure.txt

# Run
timestep 0.01
thermo $(1e6)
run $(1e7)
```

input.data

```
LAMMPS data file via write_data, version 29 Oct 2020, timestep = 10000000

64 atoms
1 atom types
63 bonds
1 bond types

-20.0 20.0 xlo xhi
-20.0 20.0 ylo yhi
-20.0 20.0 zlo zhi

Masses

1 1

Atoms # bond

64 1 1 0.0 -8.615420831184595 -1.7694740471080483 0 0 0
63 1 1 0.0 -8.195358650958925 -0.9321781698762801 0 0 0
62 1 1 0.0 -7.282286246267325 -0.614826833187781 0 0 0
30 1 1 0.0 -0.22176729546970675 14.218435200651836 0 0 0
31 1 1 0.0 -0.7261898423236703 13.434705429098647 0 0 0
37 1 1 0.0 -0.04342337177100708 9.047368714263726 0 0 0
61 1 1 0.0 -7.734862466790034 0.22421818069463706 0 0 0
59 1 1 0.0 -6.561659889423628 1.5757928023318115 0 0 0
60 1 1 0.0 -7.400412246108671 1.111818894640205 0 0 0
56 1 1 0.0 -4.266493721445711 2.378331187439085 0 0 0
58 1 1 0.0 -5.7261271818046025 2.0077020817709545 0 0 0
57 1 1 0.0 -4.838733946634068 1.6396162325152364 0 0 0
55 1 1 0.0 -4.162448471426493 3.367725976134382 0 0 0
54 1 1 0.0 -4.6334609661400625 4.232928617294472 0 0 0
53 1 1 0.0 -3.8758250359921393 4.86259074847762 0 0 0
45 1 1 0.0 -0.21452420500252456 6.686801564325522 0 0 0
52 1 1 0.0 -4.534170341138975 5.569537583268911 0 0 0
48 1 1 0.0 -3.1119966646700954 7.457289138593515 0 0 0
47 1 1 0.0 -2.184417850762277 7.158706134267046 0 0 0
46 1 1 0.0 -1.1493923991333832 7.155772303130409 0 0 0
29 1 1 0.0 -0.13262339723160652 15.168511178838115 0 0 0
51 1 1 0.0 -5.188622124403278 6.387590756703884 0 0 0
50 1 1 0.0 -5.045959370234591 7.316791549043234 0 0 0
49 1 1 0.0 -4.031825968789022 7.1659068526800835 0 0 0
32 1 1 0.0 -0.20891314540963013 12.630666868725422 0 0 0
34 1 1 0.0 -0.054799916750357565 11.043237938915203 0 0 0
4 1 1 0.0 11.910108378633064 8.253951793070271 0 0 0
3 1 1 0.0 12.685419600691992 7.696533334245705 0 0 0
5 1 1 0.0 11.015256032151038 8.457664711753637 0 0 0
6 1 1 0.0 10.55971356208393 7.5246081706041705 0 0 0
7 1 1 0.0 9.596630463948216 7.890427585425415 0 0 0
8 1 1 0.0 8.676839045344748 7.443717240945482 0 0 0
9 1 1 0.0 7.7081203372157026 7.542316317145208 0 0 0
10 1 1 0.0 6.915931062107758 8.076942370637017 0 0 0
11 1 1 0.0 7.123730726159015 9.054649132258566 0 0 0
12 1 1 0.0 6.475339311582538 9.761378075036593 0 0 0
13 1 1 0.0 7.484156789009213 10.124982837453187 0 0 0
14 1 1 0.0 8.321934336119806 10.611634821448316 0 0 0
42 1 1 0.0 2.55175089512963 6.817305161027888 0 0 0
15 1 1 0.0 7.7270355545591025 11.362865096841015 0 0 0
16 1 1 0.0 6.771760023360677 11.302581131752092 0 0 0
41 1 1 0.0 2.0285968648742485 7.667390594360149 0 0 0
17 1 1 0.0 5.841526685198769 11.591706156663626 0 0 0
2 1 1 0.0 13.241030961755227 8.479031716642202 0 0 0
1 1 1 0.0 14.235158654016349 8.250944213487355 0 0 0
18 1 1 0.0 4.818396548575705 11.469457728865661 0 0 0
19 1 1 0.0 4.829045595831774 12.522764790405555 0 0 0
27 1 1 0.0 1.351757539899257 16.465715183555822 0 0 0
20 1 1 0.0 3.888067750303565 12.617732899804139 0 0 0
21 1 1 0.0 3.1697013326421954 13.201276479613247 0 0 0
44 1 1 0.0 0.7071360028768153 6.581773567053778 0 0 0
26 1 1 0.0 2.126974442113554 15.943229509387862 0 0 0
25 1 1 0.0 1.4286395144573931 15.358075309129113 0 0 0
23 1 1 0.0 1.4946135464912114 13.739650204165022 0 0 0
22 1 1 0.0 2.17081654076949 13.051493655440366 0 0 0
40 1 1 0.0 2.4212077370895333 8.530743709855837 0 0 0
24 1 1 0.0 0.8924221677218671 14.508573441884018 0 0 0
39 1 1 0.0 1.7818574192417784 9.282782890665414 0 0 0
43 1 1 0.0 1.6512906664655889 6.647175355256373 0 0 0
38 1 1 0.0 0.8127425939207082 9.308664200466024 0 0 0
28 1 1 0.0 0.49496481885485405 15.879707841574607 0 0 0
33 1 1 0.0 0.38255748251603355 11.920632576310927 0 0 0
35 1 1 0.0 0.8272158922361736 10.527460560093767 0 0 0
36 1 1 0.0 0.022268828704906655 10.00689319014236 0 0 0

Velocities

64 0.0 0.07129526784201665 0.0011277151016431193
63 0.0 -1.320656198023292 -0.017466192685790614
62 0.0 -0.2613609257871994 -1.4737018849988914
30 0.0 -0.6281218967367079 -0.11474976553310527
31 0.0 0.06970098259547171 0.3577742065790216
37 0.0 0.28221913277410937 -0.7757443365136057
61 0.0 -1.0866288927005776 0.6189249530390416
59 0.0 -1.3062407312011752 -2.9752817634642335
60 0.0 1.0495374520943481 -0.7400228907777957
56 0.0 0.5827597261799714 2.77185698092168
58 0.0 -0.9012469085045532 -0.8549330573374472
57 0.0 -0.6498586731615086 -0.7593040597671349
55 0.0 -0.3063589642757279 -0.34320958104472754
54 0.0 1.532987389834143 -1.2571009699395115
53 0.0 1.3334010758930706 1.1854463113087133
45 0.0 -1.060778361972903 -0.5213892775276513
52 0.0 -1.398386595043374 -1.5356364525517994
48 0.0 -0.099084613421117 -0.5562455051425687
47 0.0 -0.8629554676825049 -0.02318221768872373
46 0.0 0.961820522363486 -1.0108711812204674
29 0.0 0.2821548963997261 -1.6245798740325124
51 0.0 0.2545551655213559 -0.6457512070589675
50 0.0 2.711785433310391 0.882213406001327
49 0.0 -0.4852662293851477 -0.5396103955462705
32 0.0 0.14116548040047 0.43897235484255925
34 0.0 -0.024935182780864613 1.8242792065884283
4 0.0 -0.5533806122396243 1.2010075154307964
3 0.0 0.18992264466100864 0.33029655675137704
5 0.0 0.7757232002195761 -1.8829582533453673
6 0.0 1.2911223574789854 1.3055179655968185
7 0.0 -0.9775586133047482 -0.7214369958426888
8 0.0 0.07108937342560873 -1.1982955459460012
9 0.0 -1.2740622909769423 -1.6742390535812874
10 0.0 1.0134590195950635 0.6950098877431576
11 0.0 0.20635620962975387 2.2486624967501014
12 0.0 0.44697185125353306 -2.808541845912419
13 0.0 1.532352001090376 2.005046376007086
14 0.0 -0.7081518930442929 3.1813663305310325
42 0.0 0.7622348416216134 -1.6340746397748112
15 0.0 -1.4223318504579452 0.5241035450935407
16 0.0 -0.6105067238500981 0.7612223667945389
41 0.0 -0.1937188280694772 0.7726614216168133
17 0.0 -1.3821532961446101 -1.1661010880756084
2 0.0 1.1144273806918161 2.465719964750053
1 0.0 -0.5281883999019962 1.4894169385062845
18 0.0 0.9595019193931329 2.2868643006185545
19 0.0 -0.65520145267049 0.18646181038241516
27 0.0 0.3332373449796956 1.2058699134471493
20 0.0 1.3812077461874366 0.23008549695484323
21 0.0 -0.3005937496557704 -1.0029558555943223
44 0.0 2.5318232922085464 -0.3949055719310963
26 0.0 0.9301818039771207 -0.8870007617080472
25 0.0 -1.6471921016493936 0.6364843777578106
23 0.0 -2.860144350201573 1.6376219776277905
22 0.0 -0.509516373844251 -0.11235840681249287
40 0.0 -1.9541019024530928 -2.3801363406860503
24 0.0 0.6636907259888192 0.3013741456774414
39 0.0 1.4395864033913521 0.8722276230155108
43 0.0 -0.14137907906217695 -1.625866192129622
38 0.0 1.5248128429329644 -1.0091497834088716
28 0.0 1.3888866939972646 1.0495516436386167
33 0.0 -0.47691071100145266 -1.7682233893092936
35 0.0 0.15732564563734253 1.246533584221537
36 0.0 -1.4003239543631336 1.321322963602471

Bonds

1 1 63 64
2 1 62 63
3 1 30 31
4 1 31 32
5 1 37 38
6 1 61 62
7 1 59 60
8 1 60 61
9 1 56 57
10 1 58 59
11 1 57 58
12 1 55 56
13 1 54 55
14 1 53 54
15 1 45 46
16 1 52 53
17 1 48 49
18 1 47 48
19 1 46 47
20 1 29 30
21 1 51 52
22 1 50 51
23 1 49 50
24 1 32 33
25 1 34 35
26 1 4 5
27 1 3 4
28 1 5 6
29 1 6 7
30 1 7 8
31 1 8 9
32 1 9 10
33 1 10 11
34 1 11 12
35 1 12 13
36 1 13 14
37 1 14 15
38 1 42 43
39 1 15 16
40 1 16 17
41 1 41 42
42 1 17 18
43 1 2 3
44 1 1 2
45 1 18 19
46 1 19 20
47 1 27 28
48 1 20 21
49 1 21 22
50 1 44 45
51 1 26 27
52 1 25 26
53 1 23 24
54 1 22 23
55 1 40 41
56 1 24 25
57 1 39 40
58 1 43 44
59 1 38 39
60 1 28 29
61 1 33 34
62 1 35 36
63 1 36 37

```

**Comment by Bibobu** [comment]
I was intrigued and ran your simulation. I noticed that the timestep you're using is twice the default of lj units.

Using a smaller timestep like 5e-3 (default) or 1e-3 gives the following results:

| dt | av. presske | av. pressbond| av. press |
|----|------------------|---------------------|---------------|
|0.01 | 0.00100034 | -0.0010015 | -1.2017e-6 |
|0.005 | 0.00100074 | -0.0009896 | 1.112133e-5 |
|0.001 | 0.00100036 | -0.0009844 | 1.596106e-5 |

Using a damping factor of 1. gives the following:
| damp | av. presske | av. pressbond| av. press |
|----|------------------|---------------------|---------------|
|1. | 0.0009997 | -0.00098805 | 1.16942441e-5 |

Could it simply be a bad combination of parameters between langevin and dt?

Note that to compute the std and standard error to the mean (SEM) I actually computed the averages from `ave/time 1 10 10`. The SEM values are <1e-6 so the results are comparable with your value.

**Comment by Birfy** [comment]
Thank you for looking into this issue!!! I tried smaller time steps and the pressure approaches the expected ideal gas law when dt approaches 0.001.

However, as far as I know, dt=0.01 is a prevalent choice for polymer simulations with FENE bond potentials, some even use dt=0.012, for example in [this article](https://doi.org/10.1063/1.1628670). I think this commonly chosen dt leads to errors in pressure (essentially leads to a negative first virial coefficient), especially in dilute polymer solutions.

Since dt=0.001 is too time-consuming for polymer simulations. I found a [newer article](https://doi.org/10.1063/5.0123431) using the [Gronbech-Jensen/Farago](https://docs.lammps.org/fix_langevin.html#gronbech-jensen) integrator with dt=0.01, however, it still does not produce the expected pressure for this simple system. Moreover, the [Gronbech Jensen/Gronbech-Jensen](https://docs.lammps.org/fix_langevin.html#id1) integrator with dt=0.01 seems to produce the expected pressure.

Here are the results using different time steps and integrators (I use a damping factor of 2 for all these simulations)
| Method | Command | Pressure |
| --- | --- | --- |
| Ideal Gas Law (Expected) | None | 1.5625e-5 |
| Default Langevin, dt=0.01 | fix 1 all langevin 1.0 1.0 2.0 123 | -1.20174e-06 |
| Default Langevin, dt=0.001 | fix 1 all langevin 1.0 1.0 2.0 123 | 1.59611e-05 |
| Gronbech-Jensen/Farago Integrator, dt=0.01 | fix 1 all langevin 1.0 1.0 2.0 123 gjf vfull | -4.64903e-07 |
| Gronbech Jensen/Gronbech-Jensen Integrator, dt=0.01 | fix 1 all langevin 1.0 1.0 2.0 123 gjf vhalf | 1.574e-05 |

**Comment by akohlmey** [comment]
Ok, so this issue resolves itself.

It is not LAMMPS' job to produce expected results when unsuitable parameters are chosen. It does not matter what is efficient or what others are using. The obvious side effects from an aggressive  timestep can be easily hidden with aggressive thermostatting and there are a non-zero number of people around that do not know the difference or do not pay attention or do not check. Based on the information provided in the discussion, I don't see any action items to concern LAMMPS.

**Comment by athomps** [comment]
I second Axel's comments. Also, these deviations in *osmotic* pressure are extremely small.  I think if you compare them to some meaningful reference e.g. the osmotic second virial coefficient, you will find that they are orders of magnitude smaller. An unphysical sign on a small value does not automatically imply an unphysical simulation.  I don't think this should be called a bug.

**Comment by Birfy** [comment]
Thank you for your comments!! I agree this is not a bug. 

This puzzles me for a while when simulating a dilute or semi-dilute solution, or when simulating a single chain in a box. Indeed, this negative pressure is only significant when concentration is low and the second and third virial terms are small compared to the ideal gas term.

**Comment by athomps** [comment]
You can test this further by turning off periodic boundary conditions entirely `boundary s s s`, which corresponds to a non-interacting solute.  The osmotic pressure is identically zero, meaning that the `Pke` should exactly balance `Pvirial`.  As you have seen, in MD this is only true up to some approximation that depends on time integration scheme, thermostat, etc.

**Comment by Birfy** [comment]
Thank you so much for your clarification and suggestions!!
