### ISSUE TITLE
[BUG] NVIDIA HPC sdk compiler cannot compile fmtlib_format.cpp

### ISSUE THREAD

**Issue by zezhong-zhang** [lammps/lammps#3700]
**Summary**

NVIDIA HPC sdk compiler cannot compile fmtlib_format.cpp

**LAMMPS Version and Platform**
LAMMPS Version: https://github.com/lammps/lammps/releases/tag/stable_23Jun2022_update3
Platform: Ubuntu 18.04
GPU: Nvidia GPU Titan V

**Expected Behavior**
I hope to compile lammps with cuda awareness, able to run parallel on multiple gpus on HPC. Thus I took the openmpi within [recent Nvidia HPC sdk](https://docs.nvidia.com/hpc-sdk/archive/23.1/) as the compiler. 

**Actual Behavior**
Cannot compile `fmtlib_format.cpp`, errors says  `ctz` and `ctzll` undefined

**Steps to Reproduce**
- Dependencies version: already `make install` recent [fmt](https://github.com/fmtlib/fmt)
- install [recent Nvidia HPC sdk](https://docs.nvidia.com/hpc-sdk/archive/23.1/) and add to $PATH 

`which mpicxx`

> /home/zezhong/data/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi/bin/mpicxx

`mpicxx --version`
> nvc++ 23.1-0 64-bit target on x86-64 Linux -tp skylake-avx512 
> NVIDIA Compilers and Tools
> Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

```
mkdir -p ${lammps_root}/src/Obj_mpi
cd ${lammps_root}/src/Obj_mpi
mpicxx -g -O3 -lfmt ../fmtlib_format.cpp
```
Error: 
> "../fmt/format-inl.h", line 1952: error: identifier "ctz" is undefined
>     int t = ctz(n);
>             ^
> 
> "../fmt/format-inl.h", line 1980: error: identifier "ctzll" is undefined
>     int t = ctzll(n);
>             ^
> 
> 2 errors detected in the compilation of "../fmtlib_format.cpp".

**Further Information, Files, and Links**
If the Openmpi within nvidia hpc sdk is not supposed to work, could you suggest the right compiler for the multiple gpu compilation?

**Comment by akohlmey** [comment]
> I hope to compile lammps with cuda awareness, able to run parallel on multiple gpus on HPC. Thus I took the openmpi within [recent Nvidia HPC sdk](https://docs.nvidia.com/hpc-sdk/archive/23.1/) as the compiler.

This is not going to make the difference you aim for. To enable GPU support you can install the GPU package and also the KOKKOS package with the suitable configuration. The GPU package can be compiled for OpenCL (needs no special tools during compilation, but compatible OpenCL runtime library installation) or CUDA (needs the CUDA toolkit). The KOKKOS package for GPU acceleration on Nvidia GPUs requires CUDA (no OpenCL option).

You do not need the Nvidia HPC SDK to use CUDA. It is merely a different compiler (formerly known as the PGI compiler developed by the Portland Group, which has been taken over by Nvidia some time ago). Its GPU related specialty is support for OpenACC, which LAMMPS does not use. So you can use a standard GCC or Clang compiler and the regular CUDA tool kit just as well. The PGI / Nvidia HPC compiler is known to have had many problems over the years and thus not recommended.

Detailed instructions for configuring and compiling LAMMPS with GPU support are in the LAMMPS manual.

**Comment by akohlmey** [comment]
Compatibility with the latest Nvidia HPC compiler should be in the latest feature (not stable) release (8 Feb 2023).

**Comment by zezhong-zhang** [comment]
Thanks @akohlmey for your suggestion. Indeed I can compile with the recent lammps release (8 Feb 2023), but the generated `lmp_gpu` cannot run with the following error:

>  [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ../../../../../orte/mca/ess/singleton/ess_singleton_module.c at line 388
> [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ../../../../../orte/mca/ess/singleton/ess_singleton_module.c at line 166
> --------------------------------------------------------------------------
> Sorry!  You were supposed to get help about:
>     orte_init:startup:internal-failure
> But I couldn't open the help file:
>     /proj/nv/libraries/Linux_x86_64/23.1/openmpi/221618-rel-1/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!

> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> Sorry!  You were supposed to get help about:
>     mpi_init:startup:internal-failure
> But I couldn't open the help file:
>     /proj/nv/libraries/Linux_x86_64/23.1/openmpi/221618-rel-1/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
> --------------------------------------------------------------------------
> *** An error occurred in MPI_Init
> *** on a NULL communicator
> *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> ***    and potentially your MPI job)
> [ec-4029:07177] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

Just wondering is the MPI compilation of lammps decoupled from the `mpirun` for the cuda-awareness? For instances,  if I use gcc and CUDA for compilation, could the executable be used for multiple gpu with `mpirun`? Because previously when I tried this, it cannot parallel the job properly.

**Comment by akohlmey** [comment]
This error sounds like you have an issue with your installation of the nvidia HPC SDK.
Or you may be using the wrong mpirun executable, i.e. one from a different installation.

CUDA-awareness is not required for MPI with the GPU package.

Yes, we use GCC and plain CUDA toolkit for compilation of LAMMPS and running on multiple GPUs all the time.

**Comment by zezhong-zhang** [comment]
I tried to use plain gcc (version 11.1) CUDA (version 11.2) and it seems the library compilation finished successfully. 
```
cd src
make yes-gpu
make lib-gpu
```
But `make gpu -j10` fails with the log here [make.log](https://github.com/lammps/lammps/files/11051293/make.log)

**Comment by akohlmey** [comment]
Please try without `-j10`, i.e. use serial make.
Or switch to using the CMake based build system. I would recommend the latter, as this is far more tested these days.

**Comment by akohlmey** [comment]
If there is still and error, please provide the *entire* screen output. Your make.log file looks like it is missing something.

**Comment by zezhong-zhang** [comment]
My apologies I thought `make gpu 2>&1 > make.log` works but not output the error message. The full log file is attached without `-j10`.
[make.log](https://github.com/lammps/lammps/files/11051687/make.log)
I will test the CMake method.

**Comment by akohlmey** [comment]
@zezhong-zhang I looked at the updated make output and that shows something that cannot happen unless you are using a modified makefile. You must use the -fPIC flag for all object files that are compiled, but those in the src folder were apparently compiled without.

Using CMake should avoid that, because the setting for -fPIC is added globally and the compilation is not split into multiple parts using multiple makefiles.

**Comment by zezhong-zhang** [comment]
@akohlmey many thank! I will try to familiar myself with CMake. Hope to run lammps on multiple GPU!

**Comment by zezhong-zhang** [comment]
So I tried using cmake

```
mkdir -p lammps-patch_8Feb2023/build/
cd lammps-patch_8Feb2023/build/
cmake -D PKG_PLUGIN=ON -D PKG_KSPACE=ON -D LAMMPS_INSTALL_RPATH=ON -D BUILD_SHARED_LIBS=yes -D CMAKE_INSTALL_PREFIX=${deepmd_root} -D CMAKE_INSTALL_LIBDIR=lib -D CMAKE_INSTALL_FULL_LIBDIR=${deepmd_root}/lib -D CMAKE_INSTALL_FULL_INCLUDEDIR=${v}/include ../cmake
make

```
The deepmd package was build following https://docs.deepmodeling.com/projects/deepmd/en/master/install/install-lammps.html. 

The cmake output 

-- Running check for auto-generated files from make-based build system
-- Generating style headers...
-- Generating package headers...
-- Generating lmpinstalledpkgs.h...
-- Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE) (Required is at least version "8.0")
-- The following tools and libraries have been found and configured:
 * Git
 * MPI
 * OpenMP
 * PNG
 * ZLIB
 * PkgConfig
 * FFTW3
 * Python

-- <<< Build configuration >>>
   LAMMPS Version:   20230208
   Operating System: Linux Ubuntu 18.04
   CMake Version:    3.26.0
   Build type:       Debug
   Install path:     /home/zezhong/data/deepmd-kit/deepmd_root
   Generator:        Unix Makefiles using /usr/bin/make
-- Enabled packages: KSPACE;PLUGIN
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          GNU
      Version:       11.1.0
      C++ Flags:     -g
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_PNG;LAMMPS_GZIP;LAMMPS_FFMPEG;FFT_FFTW3;FFT_FFTW_THREADS;LMP_PLUGIN
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Shared library flags:    
-- <<< MPI flags >>>
-- MPI_defines:      MPICH_SKIP_MPICXX;OMPI_SKIP_MPICXX;_MPICC_H
-- MPI includes:     /media/hdd_3/zezhong/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi/openmpi-3.1.5/include;/home/zezhong/data/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi/openmpi-3.1.5/include
-- MPI libraries:    /home/zezhong/data/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi/openmpi-3.1.5/lib/libmpi_cxx.so;/home/zezhong/data/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi/openmpi-3.1.5/lib/libmpi.so;
-- <<< FFT settings >>>
-- Primary FFT lib:  FFTW3
-- Using double precision FFTs
-- Using threaded FFTs
-- Configuring done (4.5s)
-- Generating done (0.2s)
-- Build files have been written to: /home/zezhong/data/lammps-patch_8Feb2023/build

which generates the `lmp` successfully, see [cmake.log](https://github.com/deepmodeling/deepmd-kit/files/11063118/cmake.log).

But the issue is the same as the build-in mode, `./lmp -h` will freeze without any output or error. I would really like to know why this happened and how to fix it?

**Comment by akohlmey** [comment]
For issues with LAMMPS when it includes the deepmd package, you have to contact the deepmd developers. It is not part of LAMMPS and we cannot help because we don't know what is changed by them.

If you have no output from `./lmp -h` then this is likely an issue with your NVHPC SDK installation. You can try
`env PAGER=cat ./lmp -h` which may help getting some output (whether helpful or not).

Overall, we regularly compile LAMMPS with GNU gcc and Clang with GPU support included and test it, also on multi-GPU machines. So it *does* work.

**Comment by akohlmey** [comment]
Another option to try is: `mpirun -np 1 ./lmp -h`

**Comment by zezhong-zhang** [comment]
Great thanks @akohlmey,  indeed `mpirun -np 1 ./lmp -h` can generate the normal output. I will close the issue now, cheers!
