### ISSUE TITLE
ReaxFF package missing un Ubuntu package

### ISSUE THREAD

**Issue by miroi** [lammps/lammps#3704]
Hello,

on my Linux Ubuntu I installed  lammps package, but as I see, there is missing ReaxFF , https://docs.lammps.org/Packages_details.html#pkg-reaxff .

Any clue how to add ReaxFF quickly ?  

~~~
.
Large-scale Atomic/Molecular Massively Parallel Simulator - 29 Sep 2021 - Update 2
.
.
Installed packages:

ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE EXTRA-PAIR GRANULAR KIM 
KSPACE MANYBODY MC MISC MOLECULE MPIIO OPT PERI POEMS PYTHON QEQ REPLICA RIGID 
SHOCK SRD VORONOI 
.
~~~

**Comment by akohlmey** [comment]
LAMMPS binary packages (or compilation scripts) for Linux and other operating systems are not maintained by the LAMMPS developers, but some package maintainers of that distribution project. The only exception to that rule are the Windows binary installer packages.

Thus what is included or not in these pre-packaged binaries, is the choice of the respective package maintainers. If you want to have changes made there, then you have to contact those maintainers. There is usually a distribution specific procedure for suggesting changes. It is not possible to add packages after the fact.

Beyond that, the way to get a custom LAMMPS executable is to compile from source yourself.
