### ISSUE TITLE
LAMMPS-64bit-Python-stable-MPI and missing mpich2mpi.dll on Windows 64 bit

### ISSUE THREAD

**Issue by miroi** [lammps/lammps#3707]
Hello,

I installed latest 64bit LAMMPS-64bit-Python-stable-MPI package on my MS Windows, plus Microsoft MPI v10.0 (from https://www.microsoft.com/en-us/download/details.aspx?id=57467).

However, I got error about missing mpich2mpi.dll file. Any clue please where to get this file to make lamms on MS Windows running ? Thanks.

**Comment by akohlmey** [comment]
Two things:
- this is not the right place to discuss such issues. https://matsci.org/c/lammps/lammps-installation/44 is.
- you installed the wrong MPI library for the installer you are using. This is explained in detail here: https://packages.lammps.org/windows.html

If you *do* want to use the MSMPI library, you have to download a *different* LAMMPS installer package from https://rpm.lammps.org/windows/lammps-testing/index.html 
As the URL indicates, those are not yet considered production ready, please see: https://matsci.org/t/lammps-windows-installer-packages-with-support-for-ms-mpi-testers-needed/45299

**Comment by akohlmey** [comment]
To explain the difference. The Microsoft MPI library was built with the Microsoft Visual Studio Compilers on Windows, while the LAMMPS Windows installer packages are built with a MinGW64 cross-compiler on Linux. The MS-MPI library is out-of-the-box not compatible with the GNU compiler based MinGW64 build environment. Some special trickery is needed to convert the MS provided SDK to make it compatible with GNU compilers and that is quite error prone.

**Comment by miroi** [comment]
Hello !

In between I found https://www.mpich.org/static/downloads/1.4/ , the working file for download is mpich2-1.4-win-x86-64.

**Comment by akohlmey** [comment]
> Hello !
> 
> In between I found https://www.mpich.org/static/downloads/1.4/ , the working file for download is mpich2-1.4-win-x86-64.

This *is* linked from the website documenting how to install the Windows installer packages. Please note that there are special installation instructions that must be followed (they are not needed for the MS-MPI version, which is - besides the old age of the v1.4 binaries and incomplete installer the reason why we are working to transition to MS-MPI)
