### ISSUE TITLE
atom->map_tag_max used before being set in fix_phonon.cpp

### ISSUE THREAD

**Issue by lingtikong** [lammps/lammps#3708]
I was contacted by a user of fix-phonon, reporting error while using fix-phonon. By debuging the code, I found the error was caused by using atom->map_tag_max in line 598 of fix_phonon.cpp while its value was still -1.
Please check how to fix this, thanks.

Lingti Kong

**Comment by akohlmey** [comment]
Thanks for the note. It would have been *significantly* more helpful if you had used the "Bug Report" template and provided the information requested in it. I am particularly curious to learn how it would be possible to reach the fix phonon constructor without first creating/reading a system, which in turn should initialize the atom map.

Enforcing an initialized map is straightforward by adding a call to `atom->init_map()` as done in commit 317ce2853882ac20c14a62ef5ebeff6b253763cf
