### ISSUE TITLE
[BUG] ace/kk wrong energy with large chunksizes and few local atoms

### ISSUE THREAD

**Issue by Leimeroth** [lammps/lammps#3732]
**Summary**

When running simulations with the KOKKOS accelerated version of ACE on multiple GPUs the calculated energies are sometimes wrong, presumably when the number of atoms in a region is smaller than the chunksize. This can occur for example when simulating nanofoams or when using a lot of processes for rather small cells.

**LAMMPS Version and Platform**

Lammps from github at Nov. 3. 2022, Ubuntu, running on 4 NVIDIA A40 GPUs

**Expected Behavior**

Calculating correct energies or throwing an error.

**Actual Behavior**

Energy values are completely arbitrary high numbers like 5.125e166

**Steps to Reproduce**

Run a lammps simulation with attached files with chunksize 4096 and 1024. With 4096 it failed from step 200 onward, while no problems occurred for 1024.
 
**Further Information, Files, and Links**

As far as I understand chunksize is used to allocate GPU memory, so I assume if the number of local atoms is smaller than chunksize old sections of the memory are allocated but not overwritten with actual values.

[anneal.txt](https://github.com/lammps/lammps/files/11220635/anneal.txt)
[run.txt](https://github.com/lammps/lammps/files/11220636/run.txt)
[structure.txt](https://github.com/lammps/lammps/files/11220637/structure.txt)

**Comment by stanmoore1** [comment]
I can reproduce the bug.

**Comment by stanmoore1** [comment]
@Leimeroth this should be fixed with #3733, can you confirm?
