### ISSUE TITLE
[BUG] Fix wall/gran command not working as expected 

### ISSUE THREAD

**Issue by gmaurial** [lammps/lammps#3742]
[wallharmo_test.txt](https://github.com/lammps/lammps/files/11285819/wallharmo_test.txt)
[granwall_test.txt](https://github.com/lammps/lammps/files/11285821/granwall_test.txt)

From Lammps user :

I want to simulate a system of two species of particles confined in a box. A wall at the middle should act only on one type of particle. For the interaction with the middle wall, I wanted to use the command fix wall/gran from the granular package. However, I am almost sure that this command does not differentiate the groups of particles. 

**LAMMPS Version and Platform**

1- Lammps version : 28 March 2023
2- Run on Ubuntu 22.04.2 LTS version

**Observations**
With wall gran I see all the particles bouncing on the wall while with harmonic only particles in group 1 interact, which is what I want.

I attached the code composed of 4 spherical particles (the 2 types on each side) in a box with a wall at the middle. One is with the granular interaction (using hertz/history) and the other one with the harmonic interaction.

It is my first time reporting so please feel free to let me know if any important information are missing.

Maurial Gabriel

**Comment by akohlmey** [comment]
@gmaurial I cannot reproduce the issue with LAMMPS version 23 June 2022. Only with 28 March 2023.

For that case, there is a logic error in the fix styles that can be corrected with the following changes:
```
  diff --git a/src/GRANULAR/fix_wall_gran.cpp b/src/GRANULAR/fix_wall_gran.cpp
  index 3a73e9c411..454c1dfece 100644
  --- a/src/GRANULAR/fix_wall_gran.cpp
  +++ b/src/GRANULAR/fix_wall_gran.cpp
  @@ -454,7 +454,7 @@ void FixWallGran::post_force(int /*vflag*/)
     }
   
     for (int i = 0; i < nlocal; i++) {
  -    if ((!mask[i]) & groupbit) continue;
  +    if (!(mask[i] & groupbit)) continue;
   
       dx = dy = dz = 0.0;
   
  diff --git a/src/GRANULAR/fix_wall_gran_region.cpp b/src/GRANULAR/fix_wall_gran_region.cpp
  index 9f9716094f..30bece318c 100644
  --- a/src/GRANULAR/fix_wall_gran_region.cpp
  +++ b/src/GRANULAR/fix_wall_gran_region.cpp
  @@ -193,7 +193,7 @@ void FixWallGranRegion::post_force(int /*vflag*/)
     }
   
     for (i = 0; i < nlocal; i++) {
  -    if ((!mask[i]) & groupbit) continue;
  +    if (!(mask[i] & groupbit)) continue;
       if (! region->match(x[i][0], x[i][1], x[i][2])) continue;
   
       nc = region->surface(x[i][0], x[i][1], x[i][2], radius[i] + model->pulloff_distance(radius[i], 0.0));
```

**Comment by gmaurial** [comment]
Thank you for your answer. For the version I made a mistake it was actually the latest version 28 March 2023 not 23 Jun 2022.

**Comment by jtclemm** [comment]
Yes, that looks like it was my mistake. What Axel proposed is what was intended, I obviously wasn't very careful with adding the extra parentheses.

Thank you for catching the error and filing a bug report!
