### ISSUE TITLE
[Feature Request] make kspace to use collective via a tunable parameter

### ISSUE THREAD

**Issue by wzamazon** [lammps/lammps#3760]
**Summary**

Currently kspace use collective only on bluegene, see code https://github.com/lammps/lammps/blob/4a608dced6ea63850dddc0c8963a660b14c74d1b/src/kspace.cpp#L58.

This request is to have a tunable parameter (such as an environment variable) to control this behavior

**Detailed Description**

Some MPI library has a good implementation of `MPI_Alltoallv`, utilizing them would result in better performance. It would be

**Comment by akohlmey** [comment]
@wzamazon You have to have a closer look at the documentation in https://docs.lammps.org/kspace_modify.html.
The keyword to change this setting that you are asking for exists for nearly 10 years already. The code you are pointing to merely sets the default.

That said, if your KSpace performance is significantly impacted by which kind of MPI calls are used for the grid transpose in the 3d-FFTs, then you have too many MPI processes participating in the 3d-FFTs already. Thus to improve performance you would be better off reducing the number of MPI ranks involved in the 3d-FFTs by either using MPI + OpenMP parallelization or using run style verlet/split to run KSpace on a separate partition of MPI ranks.
