### ISSUE TITLE
[BUG] atom/swap accepts all moves when using the intel package

### ISSUE THREAD

**Issue by uihsnv** [lammps/lammps#3784]
**Summary**

All atom swaps performed by the fix `atom/swap` are accepted in violation of the metropolis criteria, when using the Intel package.

**LAMMPS Version and Platform**

Version: 23 Jun 2022 - Update 3
OS: Linux
CPU: Intel i5-12500

**Further Information, Files, and Links**

[IntelSwapTest.txt](https://github.com/lammps/lammps/files/11504018/IntelSwapTest.txt)
[Swap_withIntel.log](https://github.com/lammps/lammps/files/11504020/Swap_withIntel.log)
[Swap_withoutIntel.log](https://github.com/lammps/lammps/files/11504021/Swap_withoutIntel.log)

Attached are an input script as well as log files from running the script with the following commands:

With Intel: `OMP_NUM_THREADS=1 mpirun -np 4 lmp -in IntelSwapTest.txt -log Swap_withIntel.log -suffix intel -package intel 0 omp 0`

Without Intel: `OMP_NUM_THREADS=1 mpirun -np 4 lmp -in IntelSwapTest.txt -log Swap_withoutIntel.log`

**Comment by uihsnv** [comment]
If a bug-fix will take a while, it would be nice if for now, LAMMPS produced an error when atom/swap is used along with the Intel package. If you think it appropriate, it would be great if this is also added to the point release of the stable version.

**Comment by wmbrownIntel** [comment]
@uihsnv I have fixed this issue and am wrapping up other outstanding issues / feature requests that will be in a pull request within the next few days. Thank you for your simple reproducer.
