### ISSUE TITLE
[Feature Request] Add map of the id of dihedral and improper angles 

### ISSUE THREAD

**Issue by tengzhang48** [lammps/lammps#3786]
**Summary**

It would be nice to add a map of the id of dihedral and improper angles. A similar function is "atom-map" to find the current atom id using the id in the initial data file. 

**Detailed Description**

I am interested in some simulations that require more than 4 particle information for the calculation, such as 8 nodes of a cube. One possible solution I am thinking is to create a pair of interaction including one dihedral angle and 1 improper angle with shared id number. However, their id number will be changed during the simulation. Therefore, I cannot successfully pair the nodal information. The application background is finite element simulations. Although the main focus LAMMPS is molecular simulation, explicit FEM simulations can be formulated in a similar way of coarse-grained molecular model and implemented in LAMMPS. Thanks to the various existing functions in LAMMPS and great parallel efficiency, this will be a very powerful tool for simulating many coupled problems. 

**Further Information, Files, and Links**

Is it possible to turn off the updates of the ids of dihedral and improper angles? Will this lead to a decreased performance?

**Comment by akohlmey** [comment]
> One possible solution I am thinking is to create a pair of interaction including one dihedral angle and 1 improper angle with shared id number. However, their id number will be changed during the simulation.

This sounds like a bad design choice...

> However, their id number will be changed during the simulation.

... and this even worse.

Please provide a more detailed description of the model and how you would compute interactions and define tuples. Best would be some schemes and sketches that describe which interactions need to be computed how for *any* particle. I am quite convinced that there is an alternate approach.

**Comment by tengzhang48** [comment]
Thanks for your quick response. Here is a schematics of the interaction I would like to compute
![image](https://github.com/lammps/lammps/assets/58086633/3bf8ba52-20dc-4c7d-b33a-c5fb542d8f4a)
More specifically, I need to compute the energy change associated with the volume change of the hexahedral element. Some commonly used formula is
 $1/2\lambda(ln(V/V_0))^2-\mu ln(V/V0)$ 
where  $\mu$ is the shear modulus and $\lambda$ is the Lame constant. If I can have the id of the 8 nodes, it is not very different to compute the energy defined in the equation and its derivatives for forces.

Currently, we store 4 more nodes of the hexahedral element in the coefficient of improper angles and can run the simulations. Although it seems not to affect the performance too much, this requires to define as many improper types as the number of improper angles.

**Comment by akohlmey** [comment]
I think you should look at the PERI package and the Peridynamics implementation in LAMMPS for inspiration. There the list of the points defining a voxel (aka "partners") are determined from the neighbor list and stored to migrate with the atoms in the internal fix PERI_NEIGH command. Peridynamics can model brittle materials, so partners may be dropped if their distance is too large, but you need not implement that.

Abusing improper dihedrals for such purpose feels very "wrong".

**Comment by tengzhang48** [comment]
Thanks @akohlmey. Yes, it is a very good suggestion. I will learn the PERI package.
