### ISSUE TITLE
LAMMPS Workshop & Symposium 2023

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#3788]
We will be holding the biennial LAMMPS Workshop & Symposium this year from Aug 8-11, 2023 and we have decided to make it a virtual event again using Zoom. The Zoom logistics will be handled by Temple University as it was done for the last workshop in 2021.

It is a chance for beginners and users to learn more about LAMMPS and what people are using it for, as well as a venue to present your modeling results to others and get useful feedback or trigger collaborations. This year there will be a mix of invited, contributed, and lightning talks (in place of posters), as well as a beginners tutorial and developers discussion, and possibly one-hour breakout sessions devoted to specific topics. We are also trying something new, giving you a chance to talk for few minutes with a LAMMPS developer to ask questions about how to develop or formulate your model within LAMMPS.

The workshop website is at: https://www.lammps.org/workshops/Aug23/
The registration form is [here](https://docs.google.com/forms/d/e/1FAIpQLSf3LUjky-KRdgfCCrK1P-bjQfMoU--KN00NEFXlSBFa4Ykiww/viewform?usp=sf_link)

As always, the price is free!

**Comment by stanmoore1** [comment]
Today is the last day to register to attend the 2023 LAMMPS Workshop & Symposium next week.
