### ISSUE TITLE
[BUG] Re-grouping gives erroneous counts

### ISSUE THREAD

**Issue by ATM-Jahid** [lammps/lammps#3794]
**Summary**

I have groups defined for each type of atom. Then, some atoms in a region are changed to a fixed type. Re-grouping is then done to get an accurate count of the types.

However, re-grouping with the same ID as the initial group command gives inaccurate results. I tried using different IDs for grouping and got the correct counts.

**LAMMPS Version and Platform**

LAMMPS (28 Mar 2023 - Development)

**Expected Behavior**

Re-grouping should work even when the same ID is used.

**Actual Behavior**

Re-grouping does not work sometimes.

**Steps to Reproduce**

Relevant input and log files are linked below. The first simulation provides correct results and the second one provides incorrect results.

**Further Information, Files, and Links**

[in.1](https://pastebin.com/QwsahEmJ)
[log.1](https://pastebin.com/XwVPRkre)

[in.2](https://pastebin.com/NWKaaA9n)
[log.2](https://pastebin.com/vav1knnr)

**Comment by akohlmey** [comment]
What you are observing is documented behavior. The group command *adds* atoms to a group. If the group does not exist before, it is created. But if it exists its members remain. Thus, if you want to re-create a group from scratch, you first need to delete the group.
