### ISSUE TITLE
[BUG] REACTER in a loop with deposit

### ISSUE THREAD

**Issue by jeanlucf22** [lammps/lammps#3798]
**Summary**

We have been using the REACTER algorithm successfully in various cases. However we ran into an issue when using it in a more complicated workflow. Specifically within a loop in combination with the fix 'deposit'

**LAMMPS Version and Platform**

LAMMPS (28 Mar 2023 - Development), Intel Xeon, x86_64, icc (ICC) 18.0.1
 
**Expected Behavior**

We expect the run to continue for more MD steps and loop iterations

**Actual Behavior**

Segfault in 2nd loop iterations:

Caught signal 11 (Segmentation fault: address not mapped to object at address 0xdc0)
==== backtrace (tid:  29681) ====
 0 0x000000000004d455 ucs_debug_print_backtrace()  ???:0
 1 0x0000000000c7fe50 LAMMPS_NS::Atom::add_molecule_atom()  /home/q8j/GIT/lammps/src/atom.cpp:2132
 2 0x0000000000eb5610 LAMMPS_NS::FixDeposit::pre_exchange()  /home/q8j/GIT/lammps/src/fix_deposit.cpp:562
 3 0x00000000004ebeb3 LAMMPS_NS::Modify::pre_exchange()  /home/q8j/GIT/lammps/src/modify.cpp:414
 4 0x000000000066a914 LAMMPS_NS::Verlet::run()  /home/q8j/GIT/lammps/src/verlet.cpp:273
 5 0x00000000005ceecf LAMMPS_NS::Run::command()  /home/q8j/GIT/lammps/src/run.cpp:176
 6 0x0000000000442cc4 LAMMPS_NS::Input::execute_command()  /home/q8j/GIT/lammps/src/input.cpp:853
 7 0x000000000043fccb LAMMPS_NS::Input::one()  /home/q8j/GIT/lammps/src/input.cpp:392
 8 0x0000000000443896 LAMMPS_NS::Input::ifthenelse()  /home/q8j/GIT/lammps/src/input.cpp:947
 9 0x0000000000441cd8 LAMMPS_NS::Input::execute_command()  /home/q8j/GIT/lammps/src/input.cpp:756
10 0x000000000043fccb LAMMPS_NS::Input::one()  /home/q8j/GIT/lammps/src/input.cpp:392
11 0x00000000005cf3a7 LAMMPS_NS::Run::command()  /home/q8j/GIT/lammps/src/run.cpp:231
12 0x0000000000442cc4 LAMMPS_NS::Input::execute_command()  /home/q8j/GIT/lammps/src/input.cpp:853
13 0x000000000043f69d LAMMPS_NS::Input::file()  /home/q8j/GIT/lammps/src/input.cpp:302
14 0x0000000000417a55 main()  /home/q8j/GIT/lammps/src/main.cpp:105
15 0x0000000000022555 __libc_start_main()  /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:266
16 0x0000000000417919 _start()  ???:0

**Steps to Reproduce**

All the input files needed to reproduce bug are at:
https://github.com/jeanlucf22/LAMMPS_bug_REACTER

Essentially, the run command is:

./lmp -in run.in 2>&1 > out

which leads to the segfault in less than a minute, with a single MPI task and 1 thread.
Note: this is just a reproducer, simplified as much as we could from the original workflow. We are aware that the workflow as in this reproducer could be written differently, without a loop.

**Further Information, Files, and Links**

Force field and successful initial use of REACTER was described in
https://pubs.acs.org/doi/full/10.1021/acs.jpcc.1c04149

**Comment by jrgissing** [comment]
Hi Jean-Luc,

Thanks for the thorough bug report. Looks like this is caused by 'fix deposit' trying to access per-atom properties that had been deleted. The bug shows up due to the multiple 'fixing' and 'unfixing' of bond/react in your example. Please see #3800 for the bugfix. 

Jake
