### ISSUE TITLE
[BUG] `lj/cut/coul/cut(long)` produces wrong atomic potential energy with GPU package

### ISSUE THREAD

**Issue by cihe13375** [lammps/lammps#3813]
**Summary**
When using `lj/cut/coul/cut` or `lj/cut/coul/long` styles with GPU package, the atomic potential energy computed by `pe/atom` is incorrect. 

**LAMMPS Version and Platform**
28 Mar 2023, ubuntu 22.04, GTX 1660Ti, CUDA

**Expected Behavior**

The per-atom energy should be same when running with or without the `/gpu` suffix.

**Actual Behavior**

The per-atom energy is different when using the `/gpu` suffix compared to not using it.

**Steps to Reproduce**
[issue.tar.gz](https://github.com/lammps/lammps/files/11713444/issue.tar.gz)
```
lmp -i test.in
lmp -sf gpu -pk gpu 1 -i test.in
```
Note that the `sumabs` of all atomic potential energy (`c_2` in thermo output) is significantly different for two runs, while `epair` is very close.
`lj/cut/coul/long` has the same problem which can be verified by changing the `pair_style` line to:
```
pair_style lj/cut/coul/long 11.0
kspace_style pppm 1e-4
```

**Further Information, Files, and Links**
1) the problem is (probably) gone if the LJ coeff is zero: `pair_coeff * * 0.0 1.0`
2) the problem is (probably) gone with a super large neighbor skin: `neighbor 80 bin` (only use this with GPU package)
3)  `/intel` is fine.

**Comment by akohlmey** [comment]
I can confirm that the two outputs also differ significantly when adding the line `write_dump all custom dump.test id c_1 modify sort id`

**Comment by ndtrung81** [comment]
@cihe13375 thanks for reporting the issue and sharing the input deck and extra info. A couple of observations:

1) I can see that `-sf gpu -pk gpu 1 neigh no` gives consistent results with the CPU run.
2) in the initial configuration in `test2.lmp` there is overlap between atoms of types 2. When I used `lj/cut/coul/cut` and deleted all the atoms of type 2, the GPU and CPU results are consistent.

I will take a closer look at the issue to see while `neigh yes` gives mismatched `pe/atom` energies.

@akohlmey I think these two gpu pair styles have been tested rigorously. Maybe there is something particular with the input deck that triggers errors in the binning step on the CPU with `neigh yes` (in most platforms I tried, it is actually `neigh hybrid` now).

**Comment by akohlmey** [comment]
@ndtrung81 since the total potential energy and the value from compute reduce sum match, but the contributions for individual atoms in the dump do not, the logical conclusion would be that the per-atom energies are computed correctly, but tallied for the wrong atoms. I also checked lj/cut (matches) and coul/cut (does not match) and that suggests that there is something inconsistent when accessing the (GPU) neighbor lists with coulomb.

**Comment by akohlmey** [comment]
@ndtrung81 I don't think this behavior is specific to the test input. I just ran the rhodo benchmark and saw the same inconsistencies of the per-atom potential energy when adding the two lines:
```
compute pe all pe/atom
dump 1 all custom 100 rhodo.lammpstrj id c_pe
```

**Comment by ndtrung81** [comment]
@akohlmey thanks very much for the helpful info. I think I found the bug in the GPU lib and tried to fix it as below. The patch is also attached. It is related to indexing the `eatom` array passed to the GPU lib for tallying the per-atom energies when the `coul` term is present. Could you please help me double check this change on your end?
```
diff --git a/lib/gpu/lal_answer.cpp b/lib/gpu/lal_answer.cpp
index 1911be8431..fc8e2cfe7a 100644
--- a/lib/gpu/lal_answer.cpp
+++ b/lib/gpu/lal_answer.cpp
@@ -260,10 +260,10 @@ double AnswerT::energy_virial(double *eatom, double **vatom,
     ecoul+=ecv;
     if (_ef_atom) {
       if (_ilist==nullptr) {
-        for (int i=0; i<_ev_stride; i++)
-          eatom[i]+=engv[i];
-        for (int i=_ev_stride; i<iend; i++)
-          eatom[i]+=engv[i];
+        for (int i=0, ii=0; i<_ev_stride; i++)
+          eatom[ii++]+=engv[i];
+        for (int i=_ev_stride, ii=0; i<iend; i++)
+          eatom[ii++]+=engv[i];
       } else {
         for (int i=0, ii=0; i<_ev_stride; i++)
           eatom[_ilist[ii++]]+=engv[i];
```
[pe-atom-coul-gpu.diff.txt](https://github.com/lammps/lammps/files/11726506/pe-atom-coul-gpu.diff.txt)

**Comment by akohlmey** [comment]
@ndtrung81 After adding your patch, I get consistent results for lj/cut/coul/cut, coul/cut, and lj/charmm/coul/long using OpenCL on an Intel GPU in mixed precision. So this seems to indeed resolve the reported issue.

**Comment by cihe13375** [comment]
@ndtrung81 Thanks for the fix! I'm getting correct results on `lj/cut/coul/long` and `lj/cut/coul/cut` with the patch applied.
