### ISSUE TITLE
[BUG] _Loop_not_adding_forces_

### ISSUE THREAD

**Issue by enriquemasa** [lammps/lammps#3820]
I am trying to compute the critical resolve shear stress and I have a loop that adds forces to some atoms to apply the required stress. The first step is alright but from the second on it seems like the force is not added. I am probably doing something wrong but can't find it.
This is my loop:
****************************
label                   loopa
variable                a  loop 1 20

variable                appliedStress equal -0.01*$a # in GPa
variable		stress_eVA equal ${appliedStress}/160.21766
variable		area equal lx*lz
variable		totalForce equal ${stress_eVA}*${area}
variable		numAtomsTop equal count(upper)
variable		forcePerAtomTop equal ${totalForce}/${numAtomsTop}
variable		numAtomsBottom equal count(lower)
variable		forcePerAtomBottom equal -1.0*${totalForce}/${numAtomsBottom}

variable 		engtop atom -v_forcePerAtomTop*c_dispTop[3]
variable 		engbot atom -v_forcePerAtomBottom*c_dispBottom[3]

fix	             	tshear     upper  addforce v_forcePerAtomTop 0.0 0.0 energy v_engtop
fix	             	bshear     lower  addforce v_forcePerAtomBottom 0.0 0.0 energy v_engbot

fix_modify      	tshear energy yes
fix_modify      	bshear energy yes

restart		        50000 restart.dat

undump			OUT1

reset_timestep		0

dump 			OUT1 all custom 10000 Cu_edgeDipole-Syz.$a id type x y z c_3 c_1 vx vy vz c_4[1] c_4[2] c_4[3]
minimize 0.0 1.0e-4 10000 100000
minimize 0.0 1.0e-4 10000 100000
minimize 0.0 1.0e-4 10000 100000
minimize 0.0 1.0e-4 10000 100000
minimize 0.0 1.0e-4 10000 100000
minimize 0.0 1.0e-4 10000 100000

next    a
jump SELF loopa
******************

variable a has the right values, and forces seem to be right but the stress does not build up.

LAMMPS (15 Jun 2023)
  using 16 OpenMP thread(s) per MPI task

Just running on CPUs, although I have seen the same behavior on GPUs.

Adding forces at each step of the loop.

It does not add forces

I am attaching the whole input file. It does not allow me to attach the whole sample or the potential file.

**Further Information, Files, and Links**

[in.EdgeDipole.CRSS.txt](https://github.com/lammps/lammps/files/11762339/in.EdgeDipole.CRSS.txt)

**Comment by akohlmey** [comment]
It would have expected that you put:
```
fix_modify tshear virial yes
fix_modify bshear virial yes
```
in your input.

Please note that the input file is useless without the data file and the potential file.

**Comment by akohlmey** [comment]
Please also note that your input is no proof that *forces* are not added. It would be, if you use e.g. pair style zero and then dump the forces and show the dump. Of course for that you would only be able to do `run 0` and not minimize. But to provide proof of fix addforce not working as advertised, that would suffice.

**Comment by enriquemasa** [comment]
It seems to be adding the forces to the atoms following what you suggested, but the second minimization and subsequent loops do not seem to consider those forces. Atoms do not move and the minimization just takes 1 step with no change in stress.

**Comment by akohlmey** [comment]
If a minimization is converged and you are not making any changes, why should a second minimization do anything else but confirm that the system is already at the minimum?

**Comment by enriquemasa** [comment]
what I meant is the minimization in the second loop and beyond, after the forces are added.

**Comment by akohlmey** [comment]
Here is a rewrite of your script for a dummy system with proper variable references and moving stuff that doesn't belong into the loop body outside.

```
units           lj
atom_style      atomic
boundary        p p m

lattice         fcc 0.8442 origin 0.2 0.2 0.2
region          box block 0 10 0 10 0 10
create_box      1 box
create_atoms    1 box
mass            1 1.0

region lower    block 0 2 0 10 0 10
region upper    block 8 10 0 10 0 10
region boundary union 2 upper lower

group lower region lower
group upper region upper

change_box all triclinic

pair_style      lj/cut 2.5
pair_coeff      1 1 1.0 1.0 2.5

neighbor        0.3 bin

dump           id all custom 1 addforce.lammpstr id x y z fx fy fz

thermo          10

minimize 0.0 1.0e-4 10000 100000

undump id

compute                 dispTop upper displace/atom
compute                 dispBottom lower displace/atom

variable a index 1
variable                appliedStress equal -0.01*v_a # in GPa
variable                stress_eVA equal v_appliedStress/160.21766
variable                area equal lx*lz
variable                totalForce equal v_stress_eVA*v_area
variable                numAtomsTop equal count(upper)
variable                forcePerAtomTop equal v_totalForce/v_numAtomsTop
variable                numAtomsBottom equal count(lower)
variable                forcePerAtomBottom equal -1.0*v_totalForce/v_numAtomsBottom

variable                engtop atom -v_forcePerAtomTop*c_dispTop[3]
variable                engbot atom -v_forcePerAtomBottom*c_dispBottom[3]

fix                     tshear     upper  addforce v_forcePerAtomTop 0.0 0.0 energy v_engtop
fix                     bshear     lower  addforce v_forcePerAtomBottom 0.0 0.0 energy v_engbot
fix_modify              tshear energy yes
fix_modify              bshear energy yes

# redefine variable a
variable a delete
label loopa
variable a loop 1 20

reset_timestep 0

print "---- a=${a} applied stress=${appliedStress} forcePerAtomTop=${forcePerAtomTop} forcePerAtomBottom=${forcePerAtomBottom} ----"

dump           id all custom 1 addforce.${a}.lammpstrj id x y z fx fy fz

minimize 0.0 1.0e-4  10000 1000000

undump         id
next a
jump SELF loopa

```

**Comment by akohlmey** [comment]
As shown by my demo script, the issue is due to a combination of placing commands inside the loop that should be outside and using variable expansion (${name}) instead of variable references (v_name). There is no modification to LAMMPS itself required.

**Comment by enriquemasa** [comment]
Thanks Axel,

It seems to be working fine now. I'll make sure to go back and check the difference between $ and v_ .
