### ISSUE TITLE
Inaccurate information of fix amoeba/pitorsion command manual

### ISSUE THREAD

**Issue by tengzhang48** [lammps/lammps#3837]
Hello,

**Summary**

Based on the code, "fix amoeba/pitorsion" is for 6-body interactions. However, the detailed description on the lammps online manual is still using 5-body data structure as examples. 

**LAMMPS Version and Platform**

This is the most current version of the lammps online manual https://docs.lammps.org/fix_amoeba_pitorsion.html

**A related discussion**

I notice there are several fix commands for multi-body interactions, more than 4. Is this a good way to implement new multi-body interactions?

Thanks.

Best,
Teng

**Comment by sjplimp** [comment]
@tengzhang48 thanks for submitting this doc page bug report - PR #4201 should address it

also, yes fixes like fix amoeba/pitorsion, fix amoeba/bitorsion, and fix cmap are good ways to implement many-body terms in a covalent force fields (more than 4 atoms in an enumerated interaction).  This is how LAMMPS does it b/c the default data structs in the Atom class only include 2,3,4-body interactions.  The fixes augment this.

**Comment by tengzhang48** [comment]
Sounds great. Thanks a lot @sjplimp
