### ISSUE TITLE
LAMMPS (17 Nov 2016) ERROR: Unknown pair style (../force.cpp:240)

### ISSUE THREAD

**Issue by natashaDnepr** [lammps/lammps#387]
Good afternoon!

I try to perform simulation of crystallization of alloy with LAMMPS package.

The initialization file and the file with potential are here: [in-file](https://bpaste.net/show/1c7a66ba0b60), [potential](http://www.ctcms.nist.gov/potentials/Download/Ni-Al-YM09/Mishin-Ni-Al-2009.eam.alloy).

However, the execution fails with the following output:
```
> ../../src/lmp_g++_openmpi < ../in.AlNi.prism_npt-1
LAMMPS (17 Nov 2016)
Lattice spacing in x,y,z = 3.7 3.7 3.7
Created triclinic box = (0 0 0) to (74 74 74) with tilt (0 0 0)
  1 by 1 by 1 MPI processor grid
Created 20000 atoms
16000 atoms in group al
4000 atoms in group ni
Setting atom values ...
  16000 settings made for type
Setting atom values ...
  4000 settings made for type
ERROR: Unknown pair style (../force.cpp:240)
```

My system information:
```
> lsb_release -idrc && echo Kernel Release: `uname -r`
Distributor ID: SUSE LINUX
Description:    openSUSE Leap 42.1 (x86_64)
Release:        42.1
Codename:       n/a
Kernel Release: 4.1.38-47-default
> gcc --version | grep 'gcc'
gcc (SUSE Linux) 4.8.5
```

This LAMMPS version was installed from GitHub.

I also have an older version of LAMMPS installed from repository,
```
> lammps -help | grep 'LAMMPS'
LAMMPS (12 Apr 2013)
```

It does run the simulation, but returns incorrect results. As I know, this was fixed at later versions in 2016 year, so I need to use recent versions of LAMMPS.

Could somebody help to overcome the error, obtained with the later version on my system, please?

Thank you in advance.

Regards, Natalia

**Comment by akohlmey** [comment]
this is not a LAMMPS code issue, but a user problem. please post your question to the lammps-users mailing list instead. thanks, axel.
