### ISSUE TITLE
[BUG] Bug report on the LAMMPS-GUI tool: incorrect parsing of fixed points values

### ISSUE THREAD

**Issue by Bibobu** [lammps/lammps#3882]
**Summary**

While trying to test the new GUI interface with my straight forward LJ crystal script I got errors when using values between one and zero in the fixed point format (0.xxx). The problem is that fixed points commands are not parsed correctly, only the integer part is parsed.

**LAMMPS Version and Platform**

2 aug 2023 as a backend of the GUI, the GUI version is v1.1 from https://download.lammps.org/static/ (5 aug 2023).

The binary used is linux_86-64 on a Fedora 37 system (v1.0 in lammps rep also compiled correctly but showed similar behaviour).

**Expected Behavior**

Floating point values should be parsed correctly.

**Actual Behavior**

Fixed point values are not parsed correctly. A command like `velocity all create 0.8 4734` yields a 0 temperature. A command like `fix 1 all nvt 1 1 0.1` throws an error. Values in scientific notation (`8e-1`) work fine.

**Steps to Reproduce**
An example script that shows the problem:
```
units lj
atom_style atomic
lattice fcc 0.8

region mycube block 0 5 0 5 0 5
create_box 1 mycube
create_atoms 1 box
```

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
I cannot reproduce this. Can you attach a (gzipped for protection) input file that causes the problem.

**Comment by akohlmey** [comment]
A possible explanation would be that you are inserting a UTF-8 character that looks like a decimal point but is not the ASCII one **and** for that we do not have an automatic translation.

Another possible explanation would be an unusual interaction with your locale setting. You could do `export LC_ALL=C` in a console window before launching the executable to see if it make a difference.

What happens if you use the console version? https://download.lammps.org/static/lammps-linux-x86_64-stable.tar.gz

Also, please check out the examples in the LAMMPS sources. There should be plenty with numbers that has a decimal point.

**Comment by Bibobu** [comment]
Please find attached the two input files `test_gui.lmp` and `test_gui_2.lmp` with corresponding screenshots of the outputs. In the former case, the temperature is set to 0, in the latter, the lattice command is invalid.

Using the static command line version runs fine with these inputs. So the files seems to be correctly encoded with a UTF-8 dot character.

[bug_parse_gui.tar.gz](https://github.com/lammps/lammps/files/12280559/bug_parse_gui.tar.gz)

An alternative I see might be a problem from my use of the Wayland compositor in the Gnome desktop environment.

**Comment by akohlmey** [comment]
> An alternative I see might be a problem from my use of the Wayland compositor in the Gnome desktop environment.

Both inputs run without error on my machine (Fedora 38, XFCE4, X11),

Could be an issue with Qt converting the text from the plain text editor widget incorrectly. Perhaps an additional explicit conversion step may be needed.

**Comment by akohlmey** [comment]
These issues are the reason why I am looking for a person with experience in Qt programming. I am just too dependent on what tutorials, stackoverflow, and the documentations suggest and thus may be missing important steps.
![gui-success](https://github.com/lammps/lammps/assets/289251/0c6eda23-71a2-42ad-9ca0-f142c7b3014e)

**Comment by Bibobu** [comment]
I tried running Gnome on X11 and got similar issues. As far as it goes it might be good time for me to update my system to Fedora 38 and see if the problem goes away but not identifying where it stems from is unsatisfying, as it might happen to other users. When my update is done, I'll tell you how this turns out.

Unfortunately, I think I have even less programming experience than you in Qt. So I think this issue might have to wait for now.

**Comment by mkanski** [comment]
I can reproduce this by overwriting `LC_ALL` with something that uses comma instead of a dot as a decimal separator.
For example, if you start LAMMPS GUI with:
`LC_ALL="pl_PL.UTF-8" ./lammps-gui`
then the GUI will ignore everything after the dot.

The easiest solution I see is to explicitly export `LC_ALL` in the `lammps-gui` wrapper.

**Comment by akohlmey** [comment]
Thanks. That is a good idea. Will do ASAP.

**Comment by Bibobu** [comment]
I can confirm that running `LC_ALL="en_GB.UTF-8" ./lammps-gui test_gui.lmp` solved the issue. As my default locale was set to `fr_FR.UTF-8` that might be the cause of the problem.

**Comment by akohlmey** [comment]
I have added the C locale setting for the wrapper script, but also changed the locale setting from within the LAMMPS GUI app to C (when it is used outside of the wrapper). This should hopefully resolve this issue.

**Comment by akohlmey** [comment]
I've updated the binaries on the download server. They should now show version 1.1.2
As a bonus feature, there is a "View" menu item, where log and plot window can be hidded or shown and the setting is also stored in the settings file, so on the next startup, the app will remember the last state. Same with window sizes that should also be stored on close. You can also choose to replace log/plot windows or create new ones with each run.
