### ISSUE TITLE
[BUG] Sporadic numeric breakdowns with ReaxFF+QEq using Kokkos on NVIDIA and AMD GPUs with tag stable_2Aug2023

### ISSUE THREAD

**Issue by ohearnk** [lammps/lammps#3895]
**Summary**

Running scaling experiments on the [AMD Accelerator Cloud](https://community.amd.com/t5/instinct-accelerators/take-a-test-drive-in-the-amd-accelerator-cloud/ba-p/500901) on MI210 / MI250 GPUs, I recently encountered numeric breakdowns in simulations with ReaxFF+QEq using Kokkos with the recently released stable_2Aug2023.  The previous stable release stable_23Jun2022_update4 does not exhibit these breakdowns.  These breakdowns first appear as QEq convergence failures but could possibly be from other code regions.

Breakdowns appear with code built from both HIP v5.5.1 and v5.6.0 (latest), and OpenMPI v4.1.5.  As two counterpoints, no breakdowns occur on NVIDIA GPUs with the latest LAMMPS Kokkos code (testing on the MSU High Performce Computing Center with GCC v11.2.0, OpenMPI v4.1.1, and CUDA v11.8 on K20s, K80s, V100's, and A100s).  Also, no breakdowns occur in ReaxFF+QEq simulations with [PuReMD](https://github.com/msu-sparta/PuReMD) with the MPI+HIP code (with either HIP v5.5.1 or v5.6.0).  So, my best guess is that the issue lies in either updates to the Kokkos codepaths for ReaxFF+QEq or within Kokkos itself (the latter being more likely IMO).

**LAMMPS Version and Platform**

Tested LAMMPS Kokkos using the HIP backend on tag stable_2Aug2023 (issues present) and stable_23Jun2022_update4 (no issues present) with the bundled Kokkos versions.

**Expected Behavior**

No numeric breakdowns in ReaxFF+QEq NVE simulations.

**Actual Behavior**

Tests are weak scaling experiments on 2.5 ps NVE simulations using bulk water (6540 atoms / GPU) and amorphous silica (6000 atoms / GPU) systems.  Failures observed are indicated below for the MI210 GPUs (B = Numeric Breakdown, S = No Numeric Breakdown (Stable)).  Note also that the table results below match for the MI250 GPUs.

| Num. GPUs | Silica  | Water |
| ----------------- | --------   | --------- |
| 1 | S  | S  |
| 2 | B  | B  |
| 4 | B  | B |
| 8 | B  | B  |
| 16 | B  | B  |

<details>

<summary>Example numeric breakdown from simulation log (2 GPUs)</summary>

LAMMPS (2 Aug 2023)
KOKKOS mode is enabled (src/KOKKOS/kokkos.cpp:107)
  will use up to 2 GPU(s) per node
WARNING: Kokkos with GPU-enabled backend assumes GPU-aware MPI is available, but cannot determine if this is the case
         try '-pk kokkos gpu/aware off' if getting segmentation faults (src/KOKKOS/kokkos.cpp:333)
  using 1 OpenMP thread(s) per MPI task
package kokkos
# https://lammps.sandia.gov/doc/Speed_kokkos.html
# 1) Documentation recommends neigh half netwon on for Pascal or newer
# 2) Non-threaded comm
package kokkos neigh half newton on comm no gpu/aware off

units real
dimension 3
boundary p p p
timestep 0.25

atom_style charge/kk
read_data silica_12000.in
Reading data file ...
  orthogonal box = (0 0 0) to (72.954 50.174 52.11)
  2 by 1 by 1 MPI processor grid
  reading atoms ...
  12000 atoms
  read_data CPU = 0.050 seconds

neighbor 2.0 bin
neigh_modify delay 25 every 1 check no

mass 1 15.999
mass 2 28.085

pair_style reax/c/kk control_reaxc_silica_12000.in checkqeq yes enobonds yes lgvdw no
WARNING: Ignoring inactive control parameter: simulation_name (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: energy_update_freq (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: traj_title (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_info (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_forces (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_velocities (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: bond_info (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: angle_info (src/REAXFF/reaxff_control.cpp:98)
pair_coeff * * ffield-bio O Si
fix 1 all qeq/reax/kk 1 0.0 10.0 1.0e-6 reax/c
fix 2 all nve
thermo 1

run 10000
Neighbor list info ...
  update: every = 1 steps, delay = 25 steps, check = no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 12, bins = 7 5 5
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reax/c/kk, perpetual
      attributes: half, newton off, ghost, kokkos_device
      pair build: half/bin/newtoff/ghost/kk/device
      stencil: full/ghost/bin/3d
      bin: kk/device
Per MPI rank memory allocation (min/avg/max) = 100.5 | 100.5 | 100.5 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press
         0   0             -1756515.8      0             -1756515.8     -4832.2623
... [omitted for brevity]
       924   407.7388      -1771072.3      0             -1756488.9     -15001.863    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 925: (0.0034089705278667636, 8.202736259749625e-05) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       925   409.05698     -1760648.5      0             -1746017.8     -14591.171    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 926: (0.00047669053470497343, 4.855523484923519e-06) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       926   412.74142     -1754023.5      0             -1739261.1     -14861.524    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 927: (0.000798907789285451, 8.40539103707961e-06) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       927   413.55657     -1754036.7      0             -1739245.1     -14966.363    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 928: (0.0006887345563637311, 4.862389623175481e-06) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       928   415.06372     -1754201.3      0             -1739355.8     -15028.405    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 929: (0.0003984610146505404, 7.90057231538473e-06) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       929   417.24709     -1754312.6      0             -1739389.1     -15126.449    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 930: (0.0005157861987969273, 1.5025693344467912e-05) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       930   420.08461     -1754469.5      0             -1739444.5     -15153.869    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 931: (0.0009473999369665235, 4.713812643437911e-05) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       931   423.57004     -1754640        0             -1739490.3     -15150.898    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 932: (0.0018842876259078114, 0.00018660282042079617) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       932   427.72837     -1754949.7      0             -1739651.2     -15155.499    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 933: (0.010386927873345993, 0.0007588381375953284) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       933   432.52777     -1753616.1      0             -1738146       -16164.26     
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 934: (0.06020833967628494, 0.002719940613320235) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       934   464.11306     -1747347.6      0             -1730747.8     -47986.91     
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 935: (0.30690435309977737, 0.010392990993000431) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       935   12625.648     -656147.01      0             -204568.75     -701565.1     
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 936: (0.010908376528624593, 0.0069639587821034585) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       936   45400.137     -1751856.1      0             -128041.25      372363.97    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 937: (0.036846910589488614, 0.0006652353789875321) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       937   45390.41      -1738083.2      0             -114616.22      372264.26    
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 938: (1.6967933088483045, 0.04510842037202593) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       938   1.0555862e+11 -5.6382473e+09  0              3.7698496e+12  9.0372877e+11
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 939: (5.816356181484759, 0.2540221302727568) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       939   4.2246802e+11  3.0781185e+08  0              1.5110611e+13  3.6212012e+12
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 940: (14.654582355835263, 0.09975255139699808) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       940   9.7931097e+11 -2.9942963e+09  0              3.5023766e+13  8.3904118e+12
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 941: (65.92259262193036, 0.9453357133938135) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       941   6.7363938e+12  4.1322985e+10  0              2.4098017e+14  5.7721937e+13
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 942: (101.87217911799104, 1.7404090090275826) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       942   3.5060537e+13  9.9598267e+09  0              1.2540111e+15  3.0048396e+14
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 943: (117.70036783127006, 2.062191646951662) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       943   8.7424448e+13 -2.5022563e+10  0              3.1268625e+15  7.4934313e+14
WARNING: Fix qeq/reaxff/kk cg_solve convergence failed after 200 iterations at step 944: (1732.2627358975913, 31475087029.356102) (src/KOKKOS/fix_qeq_reaxff_kokkos.cpp:818)
       944   2.8820619e+22  4.0529376e+14  0              1.0308196e+24  2.4703961e+23
       945   1.1528247e+23 -59322.327      0              4.1232783e+24  9.8815845e+23
       946   1.1528247e+23 -59560.316      0              4.1232783e+24  9.8815845e+23
       947   1.1528247e+23 -59318.955      0              4.1232783e+24  9.8815845e+23
       948   1.1528247e+23 -59318.283      0              4.1232783e+24  9.8815845e+23
       949   1.1528247e+23 -59317.134      0              4.1232783e+24  9.8815845e+23
ERROR: Lost atoms: original 12000 current 119 (src/thermo.cpp:488)
Last command: run 10000

</details>

If needed, see additional logs in the attached tarballs.  Also, note that does not seem to be a discernable pattern to at the simulation step on which the breakdown occurs (for either silica or water).

**Steps to Reproduce**

Build instructions on the AMD Accelerator Cloud:

```bash
git clone https://github.com/lammps/lammps.git
cd lammps
git checkout stable_2Aug2023
module load rocm-5.6.0/ucx-1.14.1/ompi/4.1.5
mkdir build_kokkos_hip_zen3_vega90A
cd build_kokkos_hip_zen3_vega90A
cmake -C ../cmake/presets/hip_amd.cmake -DBUILD_OMP=yes -DOpenMP_CXX_VERSION=5.0 -DBUILD_MPI=yes \
  -DPKG_KOKKOS=yes -DKokkos_ENABLE_SERIAL=yes -DKokkos_ENABLE_OPENMP=yes -DKokkos_ENABLE_CUDA=no \
  -DKokkos_ENABLE_HIP=yes -DKokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=yes \
  -DKokkos_ARCH_ZEN3=yes -DKokkos_ARCH_VEGA90A=yes -DCMAKE_TUNE_FLAGS="-munsafe-fp-atomics" -DKokkos_ENABLE_DEPRECATION_WARNINGS=no \
  -DPKG_REAXFF=yes -DPKG_QEQ=yes ../cmake
cmake --build .
```

**Further Information, Files, and Links**

Attached are the relevant data needed to run the simulations.  Also, below is a shell script used for generating and submitting Slurm jobs for execution on the AAC.   For the shell script, note that you can replace the `sbatch` command with `cat` to dump the individual Slurm job files for isolated testing if needed.

<details>

<summary>Shell script for Slurm job generation and submission on AAC</summary>

```bash
#!/bin/bash

# Simulation global parameters
NSTEPS="10000"
#TOLERANCE=(1.0e-6 1.0e-10 1.0e-14)
TOLERANCE=(1.0e-6)
BASE_DIR="${PWD}"


function submit_jobs
{
    for ((i=0;i<${#DATASET[@]};i++))
    do
        for TOL in ${TOLERANCE[@]}
        do
            for ((j=0;j<${#TOTAL_PROCS[@]};j++))
            do
                JOB_NODES="$(((${TOTAL_PROCS[${j}]}+${JOB_TASKS_PER_NODE}-1)/${JOB_TASKS_PER_NODE}))"
		if (( "${TOTAL_GPUS[${j}]}" > "${JOB_GPUS_PER_NODE}" ))
		then
		    GPUS_PER_NODE="${JOB_GPUS_PER_NODE}"
		else
		    GPUS_PER_NODE="${TOTAL_GPUS[${j}]}"
		fi
                SIM_NAME="lammps-kokkos-${DATASET[${i}]}-proc${TOTAL_PROCS[${j}]}-${TOL}"
                sbatch << EOF
#!/bin/bash --login
#SBATCH --exclusive
#SBATCH --partition="${JOB_PARTITION}"
#SBATCH --nodes="${JOB_NODES}"
#SBATCH --ntasks="${TOTAL_PROCS[${j}]}"
#SBATCH --tasks-per-node="$((${TOTAL_PROCS[${j}]}/${JOB_NODES}))"
#SBATCH --cpus-per-task="${JOB_CORES_PER_TASK}"
#SBATCH --gpus-per-node="${JOB_GPUS_PER_NODE}"
#SBATCH --time="${JOB_TIME}"
#SBATCH --job-name="${SIM_NAME}"
#SBATCH --error="slurm-lammps-kokkos-${DATASET[${i}]}-proc${TOTAL_PROCS[${j}]}-%j.out"
#SBATCH --output="slurm-lammps-kokkos-${DATASET[${i}]}-proc${TOTAL_PROCS[${j}]}-%j.out"

module load rocm-5.6.0/ucx-1.14.1/ompi/4.1.5

cd "${BASE_DIR}"

DIR="${RESULTS_DIR}"
pushd "\${DIR}" &> /dev/null

mpirun -np ${TOTAL_GPUS[${j}]} \
	${JOB_RESOURCE_FLAGS} --report-bindings \
	"${LAMMPS_EXE}" \
	-kokkos on t "1" g "${GPUS_PER_NODE}" \
	-suffix kk \
	-in "control_lammps_${DATASET[${i}]}.in" \
	-nocite \
	-log "${DATASET[${i}]}.log" \
	-screen none

popd &> /dev/null
EOF
            done
        done
    done
}


function submit_jobs_zen3_vega90a_mi210
{
    # Cluster parameters for MI210 GPUs are as follows per node:
    #   128 cores (2 sockets w/ AMD EPYC 7763) with 2-way hyperthreading
    #   512 GB RAM
    #   8 GPUs (8 AMD MI210's [6656 stream processors @ 1.7 GHz, 64 GB HBM2e @ 1.6 GHz w/ ECC])
    JOB_PARTITION='1CN128C8G2H_2IB_MI210_Ubuntu22'
    JOB_TASKS_PER_NODE='128'
    JOB_CORES_PER_TASK='1'
    JOB_GPUS_PER_NODE='8'

    RESULTS_DIR="weak_scaling_lammps_kokkos_hip_zen3_vega90A_mi210"
    LAMMPS_EXE="${HOME}/lammps/build_kokkos_hip_zen3_vega90A/lmp"

    # 1 GPU
    DATASET=( 
        'silica_6000' \
        'water_6540' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(1)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:1:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 2 GPU
    DATASET=( 
        'silica_12000' \
        'water_13080' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(2)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:2:socket --bind-to core --rank-by core'
    submit_jobs

    # 4 GPU
    DATASET=( 
        'silica_24000' \
        'water_26160' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(4)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 8 GPUs
    DATASET=( 
        'silica_48000' \
        'water_52320' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(8)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 16 GPUs
    DATASET=( 
        'silica_96000' \
        'water_104640' \
    )
    TOTAL_PROCS=("$((2*${JOB_TASKS_PER_NODE}))")
    TOTAL_GPUS=(16)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 32 GPUs
    DATASET=( 
        'silica_192000' \
        'water_209280' \
    )
    TOTAL_PROCS=("$((4*${JOB_TASKS_PER_NODE}))")
    TOTAL_GPUS=(32)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
}


function submit_jobs_zen3_vega90a_mi250
{
    # Cluster parameters for MI250 GPUs are as follows per node:
    #   96 cores (2 sockets w/ AMD EPYC 7643) with 2-way hyperthreading
    #   512 GB RAM
    #   4 GPUs (4 AMD MI250's [13312 stream processors @ 1.7 GHz, 128 GB HBM2e @ 1.6 GHz], exposed as 2 chips each) 
    #   4 Infiniband interconnects
    JOB_PARTITION='1CN96C8G1H_4IB_MI250_Ubuntu22'
    JOB_TASKS_PER_NODE='96'
    JOB_CORES_PER_TASK='1'
    JOB_GPUS_PER_NODE='8'

    RESULTS_DIR="weak_scaling_lammps_kokkos_hip_zen3_vega90A_mi250"
    LAMMPS_EXE="${HOME}/lammps/build_kokkos_hip_zen3_vega90A/lmp"

    # 1 GPU
    DATASET=( 
        'silica_6000' \
        'water_6540' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(1)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:1:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 2 GPU
    DATASET=( 
        'silica_12000' \
        'water_13080' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(2)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:2:socket --bind-to core --rank-by core'
    submit_jobs

    # 4 GPU
    DATASET=( 
        'silica_24000' \
        'water_26160' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(4)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 8 GPUs
    DATASET=( 
        'silica_48000' \
        'water_52320' \
    )
    TOTAL_PROCS=("${JOB_TASKS_PER_NODE}")
    TOTAL_GPUS=(8)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 16 GPUs
    DATASET=( 
        'silica_96000' \
        'water_104640' \
    )
    TOTAL_PROCS=("$((2*${JOB_TASKS_PER_NODE}))")
    TOTAL_GPUS=(16)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
    
    # 32 GPUs
    DATASET=( 
        'silica_192000' \
        'water_209280' \
    )
    TOTAL_PROCS=("$((4*${JOB_TASKS_PER_NODE}))")
    TOTAL_GPUS=(32)
    JOB_TIME="00:10:00"
    JOB_RESOURCE_FLAGS='--map-by ppr:4:socket --bind-to core --rank-by core'
    submit_jobs
}


submit_jobs_zen3_vega90a_mi210
#submit_jobs_zen3_vega90a_mi250

```

</details>

[weak_scaling_lammps_kokkos_hip_zen3_vega90A_mi210.tar.gz](https://github.com/lammps/lammps/files/12398598/weak_scaling_lammps_kokkos_hip_zen3_vega90A_mi210.tar.gz)
[weak_scaling_lammps_kokkos_hip_zen3_vega90A_mi250.tar.gz](https://github.com/lammps/lammps/files/12398599/weak_scaling_lammps_kokkos_hip_zen3_vega90A_mi250.tar.gz)

**Comment by stanmoore1** [comment]
@ohearnk thanks I will take a look.

**Comment by stanmoore1** [comment]
@arghdos @weinbe2 FYI

**Comment by stanmoore1** [comment]
I can reproduce the breakdown on 2 GPUs

**Comment by ohearnk** [comment]
ACK.

**Comment by ohearnk** [comment]
I have now been able to reproduce the convergence failures on NVIDIA GPUs as well (K80s, V100s).  Logs are similar to the AMD GPU cases.  Inputs are from the same weak scaling experiments.

<details>

<summary>Build instructions for K80s (Intel16 cluster at MSU HPCC)</summary>

```bash
git clone https://github.com/lammps/lammps.git
cd lammps
git checkout stable_2Aug2023
module load GCC/11.2.0 OpenMPI/4.1.1-CUDA-11.8.0 CUDA/11.8.0 CMake/3.22.1
mkdir build_kokkos_broadwell_kepler_k80
cd build_kokkos_broadwell_kepler_k80
cmake -C ../cmake/presets/gcc.cmake -DCMAKE_CXX_FLAGS_DEBUG="-Wall -Og -g -std=c++14" \
 -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O2 -DNDEBUG -std=c++14" \
 -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -std=c++14" -DBUILD_OMP=yes \
 -DBUILD_MPI=yes -DPKG_KOKKOS=yes -DKokkos_ENABLE_SERIAL=yes -DKokkos_ENABLE_OPENMP=yes \
 -DKokkos_ENABLE_CUDA=yes -DKokkos_ARCH_BDW=yes -DKokkos_ARCH_KEPLER37=yes \
 -DKokkos_ENABLE_DEPRECATION_WARNINGS=no \
 -DCMAKE_CXX_COMPILER=${HOME}/lammps/lib/kokkos/bin/nvcc_wrapper \
 -DPKG_REAXFF=yes -DPKG_QEQ=yes ../cmake
cmake --build .
```

</details>



<details>

<summary>Build instructions for V100s (Intel18 cluster at MSU HPCC)</summary>

```bash
git clone https://github.com/lammps/lammps.git
cd lammps
git checkout stable_2Aug2023
module load GCC/11.2.0 OpenMPI/4.1.1-CUDA-11.8.0 CUDA/11.8.0 CMake/3.22.1
mkdir build_kokkos_skylake_volta_v100
cd build_kokkos_skylake_volta_v100
cmake -C ../cmake/presets/gcc.cmake -DCMAKE_CXX_FLAGS_DEBUG="-Wall -Og -g -std=c++14" \
 -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O2 -DNDEBUG -std=c++14" \
 -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -std=c++14" -DBUILD_OMP=yes \
 -DBUILD_MPI=yes -DPKG_KOKKOS=yes -DKokkos_ENABLE_SERIAL=yes -DKokkos_ENABLE_OPENMP=yes \
 -DKokkos_ENABLE_CUDA=yes -DKokkos_ARCH_SKL=yes -DKokkos_ARCH_VOLTA70yes \
 -DKokkos_ENABLE_DEPRECATION_WARNINGS=no \
 -DCMAKE_CXX_COMPILER=${HOME}/lammps/lib/kokkos/bin/nvcc_wrapper \
 -DPKG_REAXFF=yes -DPKG_QEQ=yes ../cmake
cmake --build .
```

</details>

**Comment by stanmoore1** [comment]
@ohearnk thanks, I'm bisecting out the bad commit now

**Comment by stanmoore1** [comment]
From git bisect:
```
8ef4e933b25610a841a8107412cdb7a69cbb50da is the first bad commit
commit 8ef4e933b25610a841a8107412cdb7a69cbb50da
Author: Stan Gerald Moore <stamoor@sandia.gov>
Date:   Fri Jun 2 10:17:38 2023 -0600

    Fix bug when Kokkos border comm is on host

 src/KOKKOS/comm_kokkos.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

Will debug.

**Comment by stanmoore1** [comment]
@ohearnk this should be fixed by https://github.com/lammps/lammps/pull/3898, can you confirm? Please note that you need GPU-aware MPI to get good performance; similarly setting `package kokkos comm no` on GPUs will greatly hurt performance on GPUs.

Edit: to clarify, you want: `package kokkos neigh half newton on` instead of `package kokkos neigh half newton on comm no gpu/aware off` in your input scripts.

**Comment by ohearnk** [comment]
@stanmoore1 I can confirm with the patch that both NVIDIA and AMD simulations run without errors now (verified up to 32 GPUs across 4 nodes).  Thanks for the quick work.

As to GPU-aware MPI comms, I am aware of the performance uplift (thanks for the reminder).  Last time I checked on the RocM side with OpenMPI, there was not yet support as of OpenMPI v4.1.5 (I believe it is in pre-release for v5.0.x) -- hence this is why I turned it off on the AAC for now.  I'll revisit turning it on once v5.0.x is stable and installed.

**Comment by skyreflectedinmirrors** [comment]
>). Last time I checked on the RocM side with OpenMPI, there was not yet support as of OpenMPI v4.1.5 (I believe it is in pre-release for v5.0.x)

FWIW, that should be supported when building OMPI w/ a ROCm-aware UCX: https://github.com/openucx/ucx/wiki/Build-and-run-ROCM-UCX-OpenMPI

**Comment by ohearnk** [comment]
> FWIW, that should be supported when building OMPI w/ a ROCm-aware UCX: https://github.com/openucx/ucx/wiki/Build-and-run-ROCM-UCX-OpenMPI

In my head, I was thinking about the functions in the OpenMPI extensions API for checking at runtime for [CUDA-aware](https://www.open-mpi.org/doc/current/man3/MPIX_Query_cuda_support.3.php) and [ROCm-aware](https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man3/MPIX_Query_rocm_support.3.html) support (the former is in v4.1.5 and the latter will be in v5.0.x).

I may have been equating existence of the runtime checking functions with support being wired up.  To confirm, can ROCm-aware support can be toggled on with OpenMPI v4.1.5 + UCX v1.14.1 + ROCm v5.6.0 on the AAC only with appropriate UCX-specific flags with `mpirun`?  And if so, is this documented somewhere?

**Comment by skyreflectedinmirrors** [comment]
Ah, yeah -- I believe you are correct, the extension API to detect GPU aware support on ROCm isn't present until 5.0, but you can still turn on GPU-aware support.

Typically this requires selecting UCX as the transport layer (e.g.,):

```
--mca pml ucx --mca btl ^vader,tcp,openib,uct
```

in your `mpirun` command, and turning it on LAMMPS via  `gpu/aware on` in the kokkos flags.

There's a bit longer of a write-up for ROCm here: https://gpuopen.com/learn/amd-lab-notes/amd-lab-notes-gpu-aware-mpi-readme/
