### ISSUE TITLE
Compilation fails with package USER-CUDA on r14624

### ISSUE THREAD

**Issue by anshumang** [lammps/lammps#39]
../verlet_cuda.cpp: In member function ‘virtual void LAMMPS_NS::VerletCuda::setup()’:
../verlet_cuda.cpp:126:17: error: ‘class LAMMPS_NS::Update’ has no member named ‘max_wall’
     if (update->max_wall > 0) {
                 ^
../verlet_cuda.cpp:128:35: error: ‘class LAMMPS_NS::Update’ has no member named ‘max_wall’
       double totalclock = update->max_wall;
                                   ^
../verlet_cuda.cpp: In member function ‘virtual void LAMMPS_NS::VerletCuda::run(int)’:
../verlet_cuda.cpp:658:17: error: ‘class LAMMPS_NS::Update’ has no member named ‘time_expired’
     if (update->time_expired()) {
                 ^

**Comment by akohlmey** [comment]
This has already been fixed in commit b5e95a0a14c6dceda8d0659656cbef5a871461b3 / r14677
