### ISSUE TITLE
The build with MESONT package enabled fails

### ISSUE THREAD

**Issue by giandex** [lammps/lammps#3901]
Hi, I'm preparing the LAMMPS slackbuild package for slackbuilds.org. The script builds the installation package from the source. It works with several packages but the compilation fails if the MESONT package is enabled

LAMMPS version: lammps-stable-2Aug2023
platform: Slackware Current

Details
Adding to cmake the flag -D PKG_MESONT=yes

the output stream returns this

```
[ 59%] Building CXX object CMakeFiles/lammps.dir/tmp/SBo/lammps-stable_2Aug2023/src/lattice.cpp.o
In file included from /tmp/SBo/lammps-stable_2Aug2023/cmake/build/styles/style_bond.h:3,
                 from /tmp/SBo/lammps-stable_2Aug2023/src/force.cpp:17:
/tmp/SBo/lammps-stable_2Aug2023/src/MESONT/bond_mesocnt.h:28:10: fatal error: bond_harmonic.h: File o directory non esistente
   28 | #include "bond_harmonic.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
[ 60%] Building CXX object CMakeFiles/lammps.dir/tmp/SBo/lammps-stable_2Aug2023/src/math_eigen.cpp.o
[ 60%] Building CXX object CMakeFiles/lammps.dir/tmp/SBo/lammps-stable_2Aug2023/src/math_extra.cpp.o
[ 60%] Building CXX object CMakeFiles/lammps.dir/tmp/SBo/lammps-stable_2Aug2023/src/math_special.cpp.o
make[2]: *** [CMakeFiles/lammps.dir/build.make:2932: CMakeFiles/lammps.dir/tmp/SBo/lammps-stable_2Aug2023/src/force.cpp.o] Error 1
make[2]: *** Attesa per i processi non terminati....
In file included from /tmp/SBo/lammps-stable_2Aug2023/cmake/build/styles/style_bond.h:3,
                 from /tmp/SBo/lammps-stable_2Aug2023/src/lammps.cpp:19:
/tmp/SBo/lammps-stable_2Aug2023/src/MESONT/bond_mesocnt.h:28:10: fatal error: bond_harmonic.h: File o directory non esistente
   28 | #include "bond_harmonic.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lammps.dir/build.make:3254: CMakeFiles/lammps.dir/tmp/SBo/lammps-stable_2Aug2023/src/lammps.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/lammps.dir/all] Error 2
```
The header should be included as it happens for other packages (for example INTEL), the code appears similar. What would be wrong? I think this is not a bug but could depend on something in my system, but I have no ideas
Thanks for your reply

PS: the build of version patch-24Mar2022 with MESONT enabled works fine, but several things has changed since this version

**Comment by giandex** [comment]
sorry, part of the output is in Italian language

"bond_harmonic.h: File o directory non esistente" means "bond_harmonic.h: File or directory not found"

**Comment by akohlmey** [comment]
> What would be wrong?

You are missing the MOLECULE package. The MESONT package was recently expanded to include a bond style and that is dependent on a bond style that is part of the MOLECULE package. This is a bug in LAMMPS. It should have printed and error stating that the MOLECULE package is required by MESONT. We'll remedy this with the next release/update.

If you are building for a packaging system, you should *first* load the "most.cmake" present file (`cmake -C cmake/presets/most.cmake`) that contains all packages that can be "safely" included for most systems and then look for additional packages that you may want to include. Please note that installing the MESONT package will also trigger the download of a very large potential file for use with that package, that is not bundled with LAMMPS because of its size and the rare use of the MESONT package. The download can be prevented with `-DDOWNLOAD_POTENTIALS=no`.

**Comment by giandex** [comment]
Thanks for your help, Akohlmey, very precious, the problem should be just the package MOLECULE, because I didn't enable it. Tomorrow I'll try enabling it. For the download there is no problem: the script starts only if the user has downloaded both the sources and the C_10_10.mesocnt file. Then the script is moved in the build directory. Already tested, this prevents the download during the build.
I have to test all the packages to know what requires external dependencies: users must know what optional or needed dependencies have to be installed before the build.
Thanks a lot at the moment

**Comment by akohlmey** [comment]
> I have to test all the packages to know what requires external dependencies: users must know what optional or needed dependencies have to be installed before the build.

This sounds like you are making your life needlessly complicated. Why not just look it up in the documentation?
https://docs.lammps.org/Build_extras.html We put this information there for a reason. :wink:

**Comment by giandex** [comment]
You are right, in fact I'm following the documentation, but I didn't find references about a package MOLECULE needed also with MESONT. Anyway thanks for your help, your suggestion has solved my problem: I've build just now adding to cmake the flags "-D WITH_MESONT -D WITH_MOLECULE", the compilation worked fine! Greetings
