### ISSUE TITLE
[BUG] numpy.extract_atom() ignores ghost atoms

### ISSUE THREAD

**Issue by jvita** [lammps/lammps#3902]
**Summary**

It looks to me that the Python wrapper `lammps.numpy.extract_atom()` does not extract the ghost atom information. See [line 91 in `lammps/python/lammps/numpy_wrapper.py`](https://github.com/lammps/lammps/blob/c072719a44ee03df80b1c23ed0d40c34d3c36b22/python/lammps/numpy_wrapper.py#L91).

Is this intentional (perhaps to avoid memory issues)?

**LAMMPS Version and Platform**

`develop` branch

**Expected Behavior**

If my understanding is correct, this line should be:
```python
nelem = self.lmp.extract_global("nmax")
```

in order to ensure that the full array of length `nmax` is parsed, as is indicated should happen in the docstring of the function.

However, given the possibly large size of this array, it would seem sufficient to at least do:
```python
nelem = self.lmp.extract_global("nlocal") + self.lmp.extract_global("nghost")
```

**Actual Behavior**

The line currently is:
```python
nelem = self.lmp.extract_global("nlocal")
```

which means that the returned array is never larger than `nlocal`.

**Steps to Reproduce**

Example script (run with >1 procs):
```python
from lammps import lammps
from mpi4py import MPI

rank = MPI.COMM_WORLD.Get_rank()

def main():
    
    lmp = lammps()

    # build the cell
    lmp.command('units           lj')
    lmp.command('atom_style      atomic')
    lmp.command('lattice         fcc 0.8442')
    lmp.command('region          box block 0 20 0 20 0 20')
    lmp.command('create_box      1 box')
    lmp.command('create_atoms    1 box')

    # make sure there are ghost atoms
    lmp.command('comm_modify cutoff 5.0')

    # for neighbor list rebuild
    lmp.command('mass 1 1.0')
    lmp.command('pair_style zero 1.0 full')
    lmp.command('pair_coeff * *')
    lmp.command('run 0 post no')

    # check expected vs. actual array size
    nlocal = lmp.extract_global('nlocal')
    nghost = lmp.extract_global('nghost')

    xyz = lmp.numpy.extract_atom('x')

    print(f'Rank {rank}: expected = at least {nlocal+nghost}; actual = {xyz.shape[0]} rows')


if __name__ == '__main__':
    main()
```

The output of the above script (with 2 procs) will be:
```bash
Rank 0: expected = at least 40315; actual = 16000 rows
Rank 1: expected = at least 40315; actual = 16000 rows
```

**Further Information, Files, and Links**

None

**Comment by akohlmey** [comment]
@jvita I would not call this a bug but more a misleading documentation. You are ignoring the optional keywords.
You should be able to do:
```python
nmax = lmp.extract_global('nmax')
xyz = lmp.numpy.extract_atom('x',nelem=nmax)
```

What the documentation *intends* to express is that the underlying C++ code typically dimensions per-atom arrays to "nmax". You can actually request even larger values (we should probably check against it and error out). The default setting is "autodetect" and in that case the "auto" refers to telling the difference between arrays of dimension "0:ntypes+1" and per-atom arrays, which are out of caution only returned up to "nlocal". The optional arguments allow you to override the automatic setting to whatever you want (including nlocal+nghost for the size).

**Comment by jvita** [comment]
Ah, my mistake: you're exactly correct that, although the note documentation is misleading, the optional arguments allow for the desired functionality. Sorry about that!
