### ISSUE TITLE
Support for general triclinic simulation boxes

### ISSUE THREAD

**Issue by sjplimp** [lammps/lammps#3907]
**Summary**

Allow users to input general triclinic boxes and atom configurations to LAMMPS, and likewise produce analogous outputs.

Background: 

A general triclinic (tri) simulation box has arbitrary edge vectors A,B,C.  LAMMPS currently only allows use of a restricted tri box where A is along the x-axis, B is in the xy plane with a +y-coord, and C has a +z-coord.  This is for consistency with neighbor list building, ghost communication, and other orthogonal simulation box operations, as well as for efficient parallelization.

Any general tri box can be rotated to become a restricted tri box, so conceptually this is not a restriction.  However, it can be more convenient for users to specify general tri boxes and coordinates, and generate output for the same.

Key idea: 

Allow input and output of general tri boxes and corresponding atom properties (e.g. coordinates).  Do this by performing transformations from general <--> restricted coordinates at the time of input and output.  Internally, LAMMPS continues to store and perform simulations with restricted tri boxes.  All the listed enhancements are optional new features, no change to current features.

**Detailed Description**

Categories of enhancements:

(1) add variables to Domain class for A,B,C
    add methods to convert A,B,C to a rotation matrix,
    and to transform vectors from general-to-restricted and vice versa,
    ditto for virial/pressure tensors
    when the restricted tri box changes (NPT, fix deform, etc) change A,B,C as well

(2) add options to input commands that specify the simulation box and its atoms:
      create_box, create_atoms with lattice, read_data, read_restart, read_dump

(3) add options to output commands for the box and atom properties:
      dump custom: header box info, xtri, ytri, ztri, same for v and f
      thermo output: A,B,C vectors and pressure tensor components

(4) enhanced or new library interface methods with general tri box/atom options:
      lammps_extract_box(), lammps_reset_box()
      lammps_extract_atom(), lammps_gather_atoms(), lammps_scatter_atoms()
      lammps_create_atoms()

(5) support for (4) in the Python interface to LAMMPS

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
@jan-janssen FYI

**Comment by akohlmey** [comment]
Implemented in PR #3984
