### ISSUE TITLE
Kolmogorov-Crespi potential implementation

### ISSUE THREAD

**Issue by jaapkroe** [lammps/lammps#392]
Dear LAMMPS developers,

We have used LAMMPS in conjunction with a simplified version of the Kolmogorov-Crespi potential described in [Physical Review B 71, 2354150 (2005)]. A earlier version of this implementation was used in [Physical Review Letters, 113, 135504 (2014)]. 
The simplification made here is that all normals are considered taken along the z-axis.

We hope you would consider including it in LAMMPS for others to use or extend upon. 
Hopefully this is the right place to submit this. 

Below is a zip-file with the source files (pair_KC0.cpp and pair_KC0.h), a small doc (pair_KC0.txt) and tex for equations (pair_KC0.tex) and a small test with input/output tested with the latest stable release (lammps-17Nov16). 

[pair_KC0.zip](https://github.com/lammps/lammps/files/804558/pair_KC0.zip)

Kind regards,
Jaap Kroes

**Comment by Pakketeretet2** [comment]
Thanks for your submission.
Normally it's more convenient to file a pull request. See: http://lammps.sandia.gov/doc/tutorial_github.html, especially in the case modifications are required.
If it's OK as is, Axel can probably include it.

**Comment by akohlmey** [comment]
a few small changes need to be done for inclusion into the distribution.
- the name of the style needs to be changed. our current convention is that any upper-case style name is internal only, i.e. not documented. also, KC0 is quite nondescript; how about: kolmogorov/crespi/zero?
- similarly, i would rename the source files accordingly. consequently, the doc files need to reflect this as well
- the current convention for system header files is to use `<` and `>` and double quotes only for include files that are part of lammps
- this pair style would be added to the USER-MISC package, so we would need an e-mail address naming a contact for maintenance inquiries
- there is a small memory leak reported by valgrind. it looks as if the words array is not freed at the end

finally a question? is this potential meaningful to be used by itself? it looks as if the intended purpose would be to use it as an additional term via hybrid/overlay. if this is correct, then it might be worth adding a check (e.g. whether strcmp(force->pair_style,"hybrid/overlay") == 0 ).

**Comment by jaapkroe** [comment]
I have made the changes and made a github pull request.
Only one small issue I couldn't figure out is how to get the tex files to automatically converted to JPG for the documentation. I should probably add it somewhere but I couldn't find it.

**Comment by akohlmey** [comment]
Thanks for the effort. Please note, the code in PR #394 doesn't currently compile. the automated check fails with the following:
```
../pair_kolmogorov_crespi_z.cpp: In member function ‘virtual void LAMMPS_NS::PairKolmogorovCrespiZ::settings(int, char**)’:
../pair_kolmogorov_crespi_z.cpp:200:31: error: too few arguments to function ‘int strcmp(const char*, const char*)’
   if (strcmp(force->pair_style)!="hybrid/overlay")
                               ^
In file included from ../pair_kolmogorov_crespi_z.cpp:26:0:
/usr/include/string.h:144:12: note: declared here
 extern int strcmp (const char *__s1, const char *__s2)
            ^
make[1]: *** [pair_kolmogorov_crespi_z.o] Error 1
```
For generating the .jpg, you can use, e.g. pdflatex, then pdftoppm | pnmcrop | pnmtojpeg
this requires using pagestyle empty.

**Comment by jaapkroe** [comment]
Ok, also these last issues should be fixed now.
I thought the idea was the jpg was automatically generated from the tex file, but I added the jpg now.

**Comment by akohlmey** [comment]
i made a few more minor tweaks to complete the integration and signaled steve that this pair style can be included in the next patch. thanks again for your contribution and help in integrating it.
