### ISSUE TITLE
[BUG] Fix_Plumed documentation example contains typo

### ISSUE THREAD

**Issue by Miniland1333** [lammps/lammps#3920]
**Summary**

In the documentation for the plumed fix, the example in https://docs.lammps.org/fix_plumed.html#examples seems to be slightly incorrect. Instead of `fix pl all plumed all plumed plumedfile plumed.dat outfile p.log`, the example should instead be `fix pl all plumed plumedfile plumed.dat outfile p.log`
My guess is that `all plumed` was accidentally copy-pasted twice when the documentation was being written.

The source code for this documentation is located at: https://github.com/lammps/lammps/blame/develop/doc/src/fix_plumed.rst

**LAMMPS Version and Platform**

This bug is affecting the most recent version of the LAMMPS online manual, https://docs.lammps.org/fix_plumed.html
Based on the commit history for fix_plumed.rst, it looks like this typo in the example has existed for quite a while.

**Expected Behavior**

As described in the manual, the syntax should be `fix ID group-ID plumed keyword value ...`
https://docs.lammps.org/fix_plumed.html

Thank you for looking into this small issue.

**Comment by akohlmey** [comment]
Thanks for reporting. This should be addressed in the next feature release.
