### ISSUE TITLE
[BUG] fix wall/region with region style ellipsoid

### ISSUE THREAD

**Issue by jrs94** [lammps/lammps#3925]
Dear LAMMPS developers,

There is what appears to be a bug when using ```fix wall/region ``` with a region defined using “style ellipsoid”. 

**Summary**

When using ```fix wall/region ``` with a region defined using “style ellipsoid”, instead of interacting with the wall, particles go through the wall and this results in an error.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Update 1)
Ubuntu 16.04.7 LTS and 22.04 LTS

**Expected Behavior**

From LAMMPS manual for ```fix wall/region ```: "Treat the surface of the geometric region defined by the region-ID as a bounding wall which interacts with nearby particles according to the specified style." This includes regions defined using "style ellipsoid".

**Actual Behavior**

The particles do not interact with the bounding wall, and instead go through the wall and this results in an error.

```ERROR on proc 0: Particle outside surface of region used in fix wall/region (…/fix_wall_region.cpp:307)```

**Steps to Reproduce**

Define a region with style ellipsoid,
```region region-ID ellipsoid x y z a b c ```
then the wall
```fix ID group-ID wall/region region-ID style args ... cutoff```

Then run the MD simulation. I tested it with a WCA all on the inside of the region; see below.

**Further Information, Files, and Links**

I made a minimal input file to test this (in.test1 and corresponding log.test1). It consists of a single particle starting in the centre of the box, surrounded by a repulsive (WCA) ellipsoid. Instead of being repelled by the wall, it goes through and generates an error.

As a sanity check, I then defined a spherical region using the ellipsoid region style by setting a=b=c (in.test2).

```region elip ellipsoid 0 0 0 $((v_r)) $((v_r)) $((v_r)) side in ```

The same thing happens and it generates the same error (log.test2_elip). However, when I define the same spherical region using the sphere region style,

``` region S sphere 0 0 0 $((v_r)) side in ```

it works as expected with no errors (in.test2 and log.test2_sphere). So it seems that there is something off with the “fix wall/region” and “region style ellipsoid” combination.

Please see the attached input/log files for reference. Note that species 2 is just there to help visualize the regions. 

[files.zip](https://github.com/lammps/lammps/files/12774785/files.zip)

Here is essentially in.test2 for convenience:

```
units           lj
atom_style      atomic
dimension       3

# sphere radius
variable r equal 8

## box length
variable L equal 21

region box0 block $((-v_L/2)) $((v_L/2)) $((-v_L/2)) $((v_L/2)) $((-v_L/2)) $((v_L/2)) units box
create_box 2 box0

## same regions defined via style ellipsoid and sphere
region elip ellipsoid 0 0 0 $((v_r)) $((v_r)) $((v_r))  side in
region S sphere 0 0 0 $((v_r)) side in

create_atoms 2 random 1000 1818 elip ## just to help visualize ellipsoid
create_atoms 1 single 0 0 0

group 1 type 1

# non-interacting WCA potentials for everything
pair_style lj/cut $((2^(1/6)))
pair_coeff * * 0.0 1.0
mass * 1.0

timestep 0.002

fix wall all wall/region elip lj126 1.0 1.0 $((2^(1/6))) ## does not work
#fix wall all wall/region S lj126 1.0 1.0 $((2^(1/6))) ## works

velocity 1 set 1 1 0

fix nve 1 nve

thermo_style custom step temp pe etotal press vol density
thermo 100

dump traj all custom 100 dump.traj id type x y z

run 100000

```

**Comment by akohlmey** [comment]
@evoyiatzis I have already confirmed the bug and it seems to be originating in the "surface" functions of the ellipsoid style.

I have been able to identify the following issues with the code, but they don't affect the example, since the value of xc, yc, and zc is the same for the example:
```
  diff --git a/src/region_ellipsoid.cpp b/src/region_ellipsoid.cpp
  index 3520b55813..e31e63c27a 100644
  --- a/src/region_ellipsoid.cpp
  +++ b/src/region_ellipsoid.cpp
  @@ -190,8 +190,8 @@ int RegEllipsoid::surface_interior(double *x, double cutoff)
       double b_r = b - cutoff;
       double c_r = c - cutoff;
       double delx_r = b_r * c_r * (x[0] - xc);
  -    double dely_r = a_r * c_r * (x[1] - xc);
  -    double delz_r = a_r * b_r * (x[2] - xc);
  +    double dely_r = a_r * c_r * (x[1] - yc);
  +    double delz_r = a_r * b_r * (x[2] - zc);
       double r_r = delx_r * delx_r + dely_r * dely_r + delz_r * delz_r;
       double rc_r = a_r * a_r * b_r * b_r * c_r * c_r;
   
  @@ -236,7 +236,7 @@ int RegEllipsoid::surface_interior(double *x, double cutoff)
       double a_r = a - cutoff;
       double b_r = b - cutoff;
       double delx_r = b_r * (x[0] - xc);
  -    double dely_r = a_r * (x[1] - xc);
  +    double dely_r = a_r * (x[1] - yc);
       double r_r = delx_r * delx_r + dely_r * dely_r;
       double rc_r = a_r * a_r * b_r * b_r;
   
  @@ -281,8 +281,8 @@ int RegEllipsoid::surface_exterior(double *x, double cutoff)
       double b_r = b + cutoff;
       double c_r = c + cutoff;
       double delx_r = b_r * c_r * (x[0] - xc);
  -    double dely_r = a_r * c_r * (x[1] - xc);
  -    double delz_r = a_r * b_r * (x[2] - xc);
  +    double dely_r = a_r * c_r * (x[1] - yc);
  +    double delz_r = a_r * b_r * (x[2] - zc);
       double r_r = delx_r * delx_r + dely_r * dely_r + delz_r * delz_r;
       double rc_r = a_r * a_r * b_r * b_r * c_r * c_r;
   
  @@ -327,7 +327,7 @@ int RegEllipsoid::surface_exterior(double *x, double cutoff)
       double a_r = a + cutoff;
       double b_r = b + cutoff;
       double delx_r = b_r * (x[0] - xc);
  -    double dely_r = a_r * (x[1] - xc);
  +    double dely_r = a_r * (x[1] - yc);
       double r_r = delx_r * delx_r + dely_r * dely_r;
       double rc_r = a_r * a_r * b_r * b_r;
 
```

However, there is still an issue in computing `contact[0].dely` and `contact[0].delz` which will lead to incorrectly projected forces. The values of `contact[0].r` and `contact[0].delx` agree with the case of a sphere.

Debugging will be easier, if you change fix wall/region to only operate on group "1" instead of group "all". The trajectory will be the same.

**Comment by evoyiatzis** [comment]
I will have a look at it @akohlmey 

Note that line 285 should read as
double delz_r = a_r * b_r * (x[2] - zc);
instead of 
double delz_r = a_r * b_r * (x[2] - yc);
as shown in the diff above.

**Comment by akohlmey** [comment]
Thanks for the note. I've edited the post accordingly.
