### ISSUE TITLE
[BUG] Dynamic groups do not update when run with KOKKOS.

### ISSUE THREAD

**Issue by bnebgen-LANL** [lammps/lammps#3929]
**Summary**

Dynamic groups do not update when run with KOKKOS.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Development - patch_2Aug2023-439-g49f08e6231)

**Expected Behavior**

the attached input produces 3 dump files. As the temperature increases, atoms cease to be in the FCC configuration and are thus removed from the group fccg. These atoms are then no longer printed in the dump file.

**Actual Behavior**

When run with the KOKKOS package, the group fccg is not updated and thus all atoms are printed in every dump file at every time step. 

Variables and computes are updating properly, as can be seen in the dump files.

**Steps to Reproduce**

Correct behavior:
<lmp> -in render.txt
Then examine contents of dump-fcc.2000.lammpstraj
Incorrect behavior
<lmp> -in render.txt -k on g 1 -sf kk (Or whatever accelerator you are using)
Then examine contents of dump-fcc.2000.lammpstraj

[render.txt](https://github.com/lammps/lammps/files/12792483/render.txt)

**Comment by stanmoore1** [comment]
@bnebgen-LANL I can reproduce this, debugging now.

**Comment by stanmoore1** [comment]
@bnebgen-LANL should be fixed by 6da8fff
