### ISSUE TITLE
Docker/podman image for last version of LAMMPS?

### ISSUE THREAD

**Issue by asterismo** [lammps/lammps#3934]
Hi, is there any docker/podman container image for the latest version of lammps?

```
podman image search lammps
NAME                                        DESCRIPTION
docker.io/amdih/lammps                      
docker.io/scalems/lammps                    
docker.io/lammps/buildenv                   LAMMPS Build Environments
docker.io/lammps/lammps                     Public lammps project of the LAMMPS MD softw...
docker.io/malramsay/lammps                  
docker.io/costrouc/lammps                   LAMMPS with all combinations: serial, mpi, n...
docker.io/costrouc/lammps-cython            A high performance python LAMMPS wrapper
docker.io/parallelworks/lammps              docker for lammps based on ubuntu 16.04 
docker.io/cbgeo/lammps                      LAMMPS MD code
docker.io/alahiff/lammps-intel-avx512-2018  LAMMPS built using the Intel 2018 compiler f...
docker.io/autamus/lammps                    LAMMPS stands for Large-scale Atomic/Molecul...
docker.io/alahiff/lammps-openmpi-omp        
docker.io/alahiff/lammps-openmpi            
docker.io/pagrubel/lammps-beeuser           
docker.io/malramsay/lammps_gpu              Container which will run LAMMPS with GPU acc...
docker.io/alahiff/lammps-intel-avx2-2018    LAMMPS built using the Intel 2018 compiler f...
docker.io/ntiwari2/lammps                   
docker.io/materialsmodeling/lammps-ase      Compilation of lammps with MPI, OpenMP, Pyth...
docker.io/nexusprime/lammps_images          ubuntu images running lammps
docker.io/freelizhun/lammps                 lammps for mpirun
docker.io/pagrubel/lammps2_bee              
docker.io/alahiff/lammps-intel-avx512-2019  
docker.io/alahiff/lammps-intel-avx512       LAMMPS built using the Intel 2017 compiler f...
docker.io/alahiff/lammps-mpi                https://github.com/lammps/lammps
docker.io/aximthered/lammps                 
quay.io/cbgeo/lammps                        
quay.io/cmisale1/lammps

```

**Comment by akohlmey** [comment]
The LAMMPS team currently doesn't create any such images except for testing or personal purposes.

If you are on a Linux machine you can download and use https://github.com/lammps/lammps/releases/download/stable_2Aug2023_update1/lammps-linux-x86_64-2Aug2023_update1.tar.gz
 
This is compiled and linked with a static libc and should thus work on most Linux machines with x86_64 machines. I only has multi-threading parallelization and no MPI, since for MPI support, you need to compile against a matching local MPI installation.
You can also download the corresponding LAMMPS GUI packages, which also contain the LAMMPS executable (again, without MPI for portability).

More recent versions compiled from the development version are posted here: https://download.lammps.org/static/
This is the permanent download repo for all "static" Linux versions but currently also serve LAMMPS GUI packages (with LAMMPS included) until there is a new feature release version and they those will be posted to the GitHub release page.
These are tested on a range of platforms and should get you started almost as well as a docker/podman/singularity image. 

There are unmaintained docker files in the lammps-packages repo at:    https://github.com/lammps/lammps-packages/tree/master/docker

**Comment by akohlmey** [comment]
I forgot to ask, is there a specific reason why you need a container image and what properties does that image need?
The typical way for people to get LAMMPS on their machines is to compile from source. If you want to get a binary adapted for your specific needs, except no substitute. We have been working very hard to make the compilation process and simple and straightforward as possible. There are even two build methods, the traditional one where you need to edit a customized make file and a more recent CMake based one that tries to automate as many steps as possible (including download and compile of some supporting libraries). Details are in the LAMMPS manual.  Building suitably generic binaries is often limited to distributions (where there is dependency tracking and "rules" about packaging leading to consistent behavior) but there are volunteers that provide LAMMPS also for Conda and PyPy (i.e. pip) or systems that automate the build from source like homebrew, or arch linux or Gentoo's ports (also on FreeBSD). All of these efforts are spearheaded by motivated individuals, but their availability often changes over time. The LAMMPS developers currently are too busy with staying on top of maintaining and updating the source to do that, too. 

The motivation for the static and LAMMPS GUI binaries is particularly to have an option for people that are interested in learning to use LAMMPS to get started quickly and figure out whether LAMMPS is suitable for their needs without having to invest too much time into learning how to build it. Once they have decided to keep using LAMMPS, they often also graduate to building their own or pick a distribution method that suits them and their needs.

**Comment by asterismo** [comment]
I'm gathering information on how can i run lammps across 5 PCs as a cluster mith slurm workload manager and OpenMPI. I was hoping to get slurm in the host Debian OS and molecular dynamics software like LAMMPS, Siesta, Gromacs in containers for not messing up with libraries and such. What would be the best approach? I see many lammps images with OpenMPI at the description, are those the ones you mentioned for personal uses? Maybe those are compiled with OpenMPI in the image as well.

**Comment by asterismo** [comment]
I also see many slurm images

```
podman image search slurm
NAME                                              DESCRIPTION
docker.io/uscbiostats/slurmr                      Interactive and R CMD Check versions for the...
docker.io/uscbiostats/slurmr-dev                  
docker.io/wrenchproject/eduwrench-slurm-terminal  Interactive terminal to interact with a simu...
docker.io/slurmio/hello-nginx                     
docker.io/datadrivenhpc/slurmctld                 SLURM Master Node
docker.io/xenonmiddleware/slurm                   SLURM batch scheduler for Xenon integration...
docker.io/slurmio/ldap-auth                       
docker.io/nielsbohr/slurm-notebook                
docker.io/rancavil/slurm-node                     Slurm Cluster Node
docker.io/giovtorres/slurm-docker-cluster         A Slurm cluster using docker-compose
docker.io/rancavil/slurm-master                   Slurm master controller
docker.io/willthelaw/slurm-docker-ubuntu          Basic Docker containers for SLURM
docker.io/rancavil/slurm-jupyter                  JupyterLab client for Slurm Cluster
docker.io/kfox1111/slurm                          
docker.io/hannahnw124/slurm_sing_nfs              
docker.io/slurms/slugbuilder                      
docker.io/brianmay/slurm                          Slurm image for Karaage
docker.io/mso4sc/slurm_exporter                   Prometheus exporter to get SLURM metrics fro...
docker.io/ohsucompbio/slurm                       Centos 7 based container with slurm for inte...
docker.io/slurms/slugrunner                       
docker.io/slurm/get-started                       
docker.io/gaijin03/slurm_build_centos7            Image for building slurm on centos7
docker.io/datadrivenhpc/slurmd                    SLURM Node
docker.io/agaveapi/slurm                          Slurm scheduler running as a controller and...
docker.io/ucbscf/slurm-exporter                   
quay.io/ohsu-comp-bio/slurm                       Repo: <https://github.com/ohsu-comp-bio/dock...
quay.io/biocontainers/perl-hpc-runner-slurm       # Perl-Hpc-Runner-Slurm  > Submit bioinforma...
quay.io/jkincl/slurm                              
quay.io/ibmdpdev/slurm-pod                        
quay.io/zhonger/slurm                             
quay.io/avishnia/prometheus-slurm-exporter        
quay.io/biocontainers/perl-hpc-runner-scheduler   # Perl-Hpc-Runner-Scheduler  > Base library...
quay.io/codedefenders/codedefenders               # Code Defenders  This Code Defenders, a mut...
quay.io/biocontainers/perl-hpc-runner             # Perl-Hpc-Runner  > Hpc runner::slurm, runn...
quay.io/bgruening/galaxy-docs-slurm               
quay.io/cdis/slurm-base                           
quay.io/nyuad_cgsb/hpc-slurm                      
quay.io/bgruening/galaxy-slurm                    
quay.io/kklin/slurm                               
quay.io/kklin/crunch-dispatch-slurm               
quay.io/bgruening/galaxy-slurm-node-discovery     

```

**Comment by akohlmey** [comment]
@asterismo I would start by compiling from source using CMake. A minimal build should always be possible with `cmake -S cmake -B build -C cmake/presets/basic.cmake` and `cmake --build build`. Then you can add packages that you may need individually, most conveniently with `ccmake build`, or switch to the "most.cmake" preset.

By using container images you add more uncertainties. They make the most sense for cases where compiling more complex e.g. for GPU accelerated packages or for packages requiring larger external packages like OpenKIM.

**Comment by akohlmey** [comment]
> I also see many slurm images

I cannot comment on using slurm images. We don't do that at Temple where I lead an HPC group. We provide containers only for very complex software with lots of dependencies (e.g. Sage Math) and environment modules for most software that is system-wide installed. Many of our users rather prefer to build software on their own, often because they make modifications.

**Comment by akohlmey** [comment]
If you want feedback from LAMMPS *users*, it may be better to post in the LAMMPS forum on MatSci.org: https://matsci.org/c/lammps/lammps-installation/44
Otherwise, you will probably get more on-topic feedback from the people that have uploaded their container images. I suspect, though, that only very few of them are continuously updating and maintaining them, since it is quite a bit of work.

**Comment by asterismo** [comment]
@akohlmey thank you very much for all the info
