### ISSUE TITLE
[Feature Request] Add support for LLNL's FLUX scheduler

### ISSUE THREAD

**Issue by ausellis0** [lammps/lammps#3935]
**Summary**

LLNL's Flux scheduler currently fails to run with LAMMPS due to lack of correctly defined MPI environment variables here:
https://github.com/lammps/lammps/blob/49f08e6231169d3f76aced42f4135ae6d3c24c49/src/KOKKOS/kokkos.cpp#L140-L181C27

Run command: 
```
flux run -N1 -n4 -c8 -g1 \
  ${INSTALL_DIR}/lmp \
  -k on g 4 -sf kk -pk kokkos cuda/aware on neigh full comm device neigh/qeq full newton on -v x 8 -v y 8 -v z 8 -v steps 600 -in in.lj -nocite -log log.lammps
```

Error message:
```
Error: Could not determine local MPI rank for multiple GPUs with Kokkos because MPI library not recognized (src/KOKKOS/kokkos.cpp:180)
```

**Detailed Description**

Maybe need to add implementation details for FLUX which should be something like:
```
      if ((str = getenv("FLUX_TASK_LOCAL_ID"))) {
        if (ngpus > 0) {
          int local_rank = atoi(str);
          device = local_rank % ngpus;
          if (device >= skip_gpu) device++;
          set_flag = 1;
        }
      }
```
See: https://github.com/flux-framework/flux-core/issues/669

Although, when I added this to `/src/KOKKOS/kokkos.cpp` and rebuilt, I'm getting errors:
```
ERROR: Requested GPU with id '1' but only 1GPU(s) available! Raised by Kokkos::initialize().
ERROR: Requested GPU with id '2' but only 1GPU(s) available! Raised by Kokkos::initialize().
ERROR: Requested GPU with id '3' but only 1GPU(s) available! Raised by Kokkos::initialize().
```
So, I believe it is not capturing an env variable (like ${FLUX_LOCAL_RANKS}) and just defaulting to a single visible device for all ranks.

**Further Information, Files, and Links**

N/A

**Comment by ausellis0** [comment]
@stanmoore1, have you used the FLUX scheduler on the LLNL systems now that it's the default for EAS3 systems? 

CC: @IanBogle

**Comment by stanmoore1** [comment]
Hi @ausellis0 thanks for the report. Yes I saw this last week, the fix is already pending here: https://github.com/lammps/lammps/pull/3930/commits/367d0ac90518d751af2d872e9cde355c7cef7f22

**Comment by stanmoore1** [comment]
Regarding the `ERROR: Requested GPU with id '2' but only 1GPU(s) available! Raised by Kokkos::initialize()` I think FLUX is setting `ROCR_VISIBLE_DEVICES` differently than SLURM so only 1 device is visible to each MPI rank. If I use `-k on g 1 ` instead of `-k on -g 8` it seemed to do the right thing and ran on all 8 GPUs as shown by `rocm-smi` ,as long as I spaced out the cores with `-c`. I haven't had a chance to try out all the binding options though.
