### ISSUE TITLE
[BUG] in.balance example is unstable

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#3942]
**Summary**

If I change the pRNG seed then the `/examples/balance/in.balance` loses atoms:

```
ERROR: Lost atoms: original 361 current 355 (../thermo.cpp:491)
Last command: run             10000
```

```patch
$ git diff .
diff --git a/examples/balance/in.balance b/examples/balance/in.balance
index 3a1298a..0c6e2c4 100644
--- a/examples/balance/in.balance
+++ b/examples/balance/in.balance
@@ -20,7 +20,7 @@ region          circle sphere $(v_d/2+1) $(v_d/2/sqrt(3.
 create_atoms    1 region circle
 mass            1 1.0
 
-velocity        all create 0.5 87287 loop geom
+velocity        all create 0.5 87290 loop geom
 velocity        all set $v $w 0 sum yes
 
 pair_style      lj/cut 2.5
```

**LAMMPS Version and Platform**

Latest develop, RHEL7

**Expected Behavior**

No crashes with different random number seed

**Actual Behavior**

Lost atoms

**Steps to Reproduce**

Run on 1 MPI rank with the RNG seed in the above diff

**Further Information, Files, and Links**

N/A

**Comment by stanmoore1** [comment]
I originally found this running Kokkos. The small roundoff errors build up over time giving a different trajectory for Kokkos vs non-Kokkos, leading to lost atoms for Kokkos. Then I was able to reproduce without Kokkos using a different random seed. So I think a high amount of trajectories in the phase space crash the example--I didn't have to try hard to find a seed that caused a crash.

**Comment by mkanski** [comment]
I think the issue is resolved if you add `timestep 0.001` to the input file.

**Comment by ohenrich** [comment]
@stanmoore1 It may be unrelated, but I'm very sure I observe a bug related to the `fix balance` in the latest stable versions `stable_2Aug2023` and also its update `stable_2Aug2023_update1`.

Attached are (the now corrected) input and data file for a long piece of double-stranded DNA, which uses the `ASPHERE`, `MOLECULE`, `CG-DNA` and` RIGID` packages.

When decomposing the system in one dimension using `fix balance shift z`, I observe local denaturing of the double-stranded DNA and overstretched FENE bonds at the top process boundary, so e.g. between process 3 and 4 if running on 4 MPI-tasks, or process 7 and 8 if running on 8 MPI-tasks. Sometimes, the runs crash later on with lost atoms. This shouldn't and doesn't happen in earlier versions up to `stable_23Jun2022_update4`.

Could this be a problem with the communication buffers, for instance when communicating less frequently used quantities like in this case quaternions?

[in.tpm.txt](https://github.com/lammps/lammps/files/13070894/in.tpm.txt)
[data.1.tpm.txt](https://github.com/lammps/lammps/files/13070895/data.1.tpm.txt)

**Comment by stanmoore1** [comment]
@mkanski I don't see any "dangerous builds" for the neighborlist, not sure why the timestep would affect the results as long as interactions are not being missed? @sjplimp any ideas?

**Comment by mkanski** [comment]
@stanmoore1 Sorry for the delay, I took another look at this and actually there are "dangerous builds" here. They are just hidden by the crash. If you decrease number of steps in your example from 10000 to 2250, you should see 155 dangerous builds.

**Comment by stanmoore1** [comment]
@mkanski yes that is true, however, if one turns off `fix balance` and keeps the same timestep size, then there are no dangerous builds. Also when `fix balance` runs successfully with no crash by simply changing the random seed, then there are also no dangerous builds. So to me it seems like the dangerous builds are coming from a bug in balance that causes the simulation to blow up, and not that the timestep is too large and dangerous builds are causing the crash.

**Comment by stanmoore1** [comment]
I did more checking and I can reproduce the crash without `fix balance` so I believe @mkanski is correct: the timestep is too large and should be reduced.  I also visualized the crash, see movie below (I visualized every timestep, probably skip to the end). It looks like energy is not being conserved.

https://github.com/lammps/lammps/assets/18146301/4bf098c5-5593-4c33-9f94-a4a643565e3e

**Comment by stanmoore1** [comment]
@akohlmey should we add this change to https://github.com/lammps/lammps/pull/3950? It may require a rebless of the regression test:

```patch
diff --git a/examples/balance/in.balance b/examples/balance/in.balance
index 3a1298a..46b750c 100644
--- a/examples/balance/in.balance
+++ b/examples/balance/in.balance
@@ -51,4 +51,6 @@ fix             10 all balance 50 0.9 rcb
 thermo_style    custom step temp epair press f_10[3] f_10
 thermo          100
 
+timestep        0.001
+
 run             10000
```

**Comment by stanmoore1** [comment]
@ohenrich I can reproduce your crash for `CG-DNA`, I bisected the bad commit as:
```
$ git bisect bad
51ac15bdc79aca959b51ec38588749985113bc11 is the first bad commit
commit 51ac15bdc79aca959b51ec38588749985113bc11
Author: Stan Gerald Moore <stamoor@sandia.gov>
Date:   Mon Jul 11 17:06:12 2022 -0600

    Fix sorting issue

 src/neighbor.cpp | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)
```
If you add `pair_modify neigh/trim no` to your balance input it doesn't crash, so it has to do with changes to the neigh list. I will debug.

**Comment by akohlmey** [comment]
> @akohlmey should we add this change to #3950? It may require a rebless of the regression test:

That is not a big problem and I can make the change, it just means that we also have to check the maintenance branch.
We should probably update *all* examples that use the same test setup, e.g. also in.balance.bond.fast and in.balance.bond.slow

**Comment by akohlmey** [comment]
> > @akohlmey should we add this change to #3950? It may require a rebless of the regression test:
> 
> That is not a big problem and I can make the change, it just means that we also have to check the maintenance branch. We should probably update _all_ examples that use the same test setup, e.g. also in.balance.bond.fast and in.balance.bond.slow

@stanmoore1 I've made the change to the indicated 3 inputs and used the opportunity to update all logs (there have been changes to the inputs without updating the logs and also bugfixes to the load balancing code).

**Comment by stanmoore1** [comment]
Thank you @akohlmey!
