### ISSUE TITLE
dump_yaml keywords field formatting

### ISSUE THREAD

**Issue by duboisel** [lammps/lammps#3946]
**Summary**

YAML format for lammps dump is very conveniant because easily parsable by many other languages for post processing.

There is a very small issue when trying to dump custom compute that calculates a per-atom array.

for exemple:
```
compute sna  all sna/atom  4.5 0.9963 2 0.5 0.5 1.0 1.0 
dump out all yaml 100 dump.yaml id type element x y z c_sna[*]
``` 
will results in the following "keywords" field in the yaml file
```
keywords: [ id, type, element, x, y, z, c_sna[1], c_sna[2], c_sna[3], c_sna[4], c_sna[5],  ]
``` 
Parsing such a file will likely raise an error because of the square bracket ([, ]) next to the compute (c_sna) key.

A simple fix would be quoting keys inside the keywords field as is it done for the yaml thermo style:
```
keywords: [ 'id', 'type', 'element', 'x', 'y', 'z', 'c_sna[1]', 'c_sna[2]', 'c_sna[3]', 'c_sna[4]', 'c_sna[5]',  ]
``` 
This is a minor change in the EXTRA-DUMP/dump_yaml.cpp
at line 70: replacing
```c++
for (int i = 0; i < nfield; ++i) thermo_data += fmt::format("{}, ", keywords[i]);
``` 
by
```c++
for (int i = 0; i < nfield; ++i) thermo_data += fmt::format("'{}', ", keywords[i]);
``` 
same at line 110: replacing
```c++
for (const auto &item : utils::split_words(columns)) fmt::print(fp, "{}, ", item);
```
by
```c++
for (const auto &item : utils::split_words(columns)) fmt::print(fp, "'{}', ", item);
```

**Comment by akohlmey** [comment]
@duboisel thanks for your submission and suggestion for an enhancement of the dump yaml command. I don't think this can be implemented "as is" since it will likely break existing readers for the file format that bypass yaml parsing. Some tests and experiments are thus going to be required.

**Comment by akohlmey** [comment]
Please see commit 0fc9b194dc36176e2eb2dd472cc50087c9e7e1da for a backward compatible change.

BTW: the yaml parsing issue can be avoided with the existing code by using the dump_modify colname command.
