### ISSUE TITLE
[BUG] No interatomic force calculations with snap/kk

### ISSUE THREAD

**Issue by Bibobu** [lammps/lammps#3952]
**Summary**

When compiling the develop version of lammps (2 aug 2023) with Kokkos package using CUDA 12.0 and A100D GPU, no interatomic forces are computed for SNAP/kk. The results are different when compared to the CPU version of the potential.

**LAMMPS Version and Platform**

* Lammps version: 2 august 2023
* OS: Ubuntu 22.04
* CUDA version 12.0
* GPU A100D, driver version 525.125.06

**Expected Behavior**

The test cases from lammps/potentials should give similar results using SNAP or SNAP/kk.

**Actual Behavior**

A Molybdenum HCP crystal using Mo_Zuo_2020 potential (pure SNAP potential) see its atoms flying around using SNAP/kk. An Ta crystal gives extremely different energy values (+10k eV).

**Steps to Reproduce**

The code was launched using the command `lmp -i in.lmp -k on g 1 -sf kk -pk kokkos newton on neigh half comm no` in the Kokkos case.

**Further Information, Files, and Links**

A zip file of the Ta test case is provided with inputs and outputs.

[Ta_test_case.zip](https://github.com/lammps/lammps/files/13167471/Ta_test_case.zip)

**Comment by stanmoore1** [comment]
@Bibobu I think this is fixed already with https://github.com/lammps/lammps/pull/3943/commits/2401cba84a5e9b07f50fe3a71a4cb6ec1048b025?

**Comment by Bibobu** [comment]
Oh my bad. I might have gotten your previous message on the forum wrong. I thought it only concerned the error catching. 

Was this PR merged? I tried pulling from the develop branch before recompiling. I'll try pulling from the PR asap then.

**Comment by stanmoore1** [comment]
No worries, yes the PR was merged last Friday, see https://github.com/lammps/lammps/pull/3943.

**Comment by Bibobu** [comment]
I can confirm that the PR solved the issue. I also had forgotten to pull and recompile since friday on the machine where I ran the last tests so obviously the issue was still there.

The problem was between my computer and my chair.

Thanks for the reminder, and sorry for the time waste.

**Comment by akohlmey** [comment]
> Thanks for the reminder, and sorry for the time waste.

No worries. It is better to report a bug that has already been fixed than to *not* report a bug that is *not* yet fixed.

**Comment by stanmoore1** [comment]
@Bibobu No worries!
