### ISSUE TITLE
[BUG] _fourier dihedral style not found, make solution clear in error message if possible

### ISSUE THREAD

**Issue by bcdandurand** [lammps/lammps#3956]
Not sure whether this should be called a bug. 
Normally when a feature is not present for running a particular example, the error message clearly indicates which package needs to have been compiled. 

When I tried to run any of the input scripts from examples/relres, I got an error message indicating that the `dihedral_style fourier` does not exist.
```
$~/lammps/examples/relres$ ../../build/lmp -in in.22DMH.relres
LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
ERROR: Unrecognized dihedral style 'fourier' (src/force.cpp:510)
Last command: dihedral_style  fourier
``` 

After I rebuilt with -D PKG_EXTRA-MOLECULE (in addition to the other required packages), the problem was fixed. What I'm requesting is that, in a future release, the error message be modified to make it clear that rebuilding with this extra package (or whatever solution is better) will fix this problem.

**Comment by akohlmey** [comment]
This feature already exists. However, it has a bug since it was not checking for dihedral styles (and instead checking for compute style twice). The expected output in your scenario would be
```
ERROR: Unrecognized dihedral style 'fourier' is part of the EXTRA-MOLECULE package which is not enabled in this LAMMPS binary. (src/force.cpp:520)
Last command: dihedral_style fourier
```

You can confirm that this works in principle by trying the same with, e.g. a non-included pair style.

This will be fixed in the next LAMMPS release.
