### ISSUE TITLE
create_atoms duplicating molecule IDs when used with MPI parallelism

### ISSUE THREAD

**Issue by scmartin** [lammps/lammps#3977]
**Summary**

I am initializing a system using `create_atoms` to randomly insert molecules using a molecule template file. The molecule template file assigns molecule IDs to segments within a molecule to allow for easier manipulation of the different segments later on. When running the script to generate the box in serial, each fragment is given a unique molecule ID as expected. However, if this is done using MPI parallelism, molecule IDs begin to be duplicated for multiple fragments, and the problem gets worse as the molecule IDs get larger. This looks like there is some kind of race condition in the code that assigns the molecule IDs in this particular situation.

**LAMMPS Version and Platform**

LAMMPS version 2 Aug 2023
running on RedHat Enterprise 7.9 on Intel(R) Xeon(R) CPU E5-2695 v4 processors.

**Expected Behavior**

When each molecule is added to the system by `create_atoms`, the molecule IDs should pick up where the previous molecule's molecule IDs left off. Each actual molecule contains multiple molecule IDs, but the molecule ID should only be used for a single segment in a single molecule.

**Actual Behavior**

In serial, the expected behavior is observed. When performed in parallel using MPI, a given molecule ID is sometimes assigned to multiple different segments on different molecules. 

**Steps to Reproduce**

1. In a molecule template file (molecule.mol), include a Molecules section with multiple molecule IDs. 
2. Use the molecule command `molecule moly test_molecule.mol`
3. In a LAMMPS input script, given a region named `simbox` use a command like `create_atoms 0 random 100 12345 simbox mol moly 98454`
4. Run lammps using either serial execution: `lammps -in in.molecule`; or parallel: `mpirun lammps -in in.molecule`

**Comment by akohlmey** [comment]
This bug seems to be fixed with the change in https://github.com/lammps/lammps/pull/4073/commits/1421d53b8c3a2de1fc8bd5ad77c042a598798f4d
