### ISSUE TITLE
Port RPM package build process from LAMMPS-ICMS to upstream version

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#400]
Building RPM packages currently requires the use of the (deprecated) LAMMPS-ICMS branch. Related files in upstream LAMMPS should be deleted and moved to the https://github.com/lammps/lammps-packages project on github.

**Comment by junghans** [comment]
I will push that to Fedora and OpenSuse once we have a working spec file.

**Comment by akohlmey** [comment]
@junghans i don't think that is going to be worth the effort. they all have their _rules_ as for how _proper_ spec files have to be built. i'd rather make the rpm (and windows) installation work in such a way, that is consistent with what a typical manual installation would look like with a few tweaks for convenience.
With the Jenkins setup here at Temple, we are already capable of building rpm and other package formats and exporting this to a set of repositories. In fact, the build process will become part of the release testing.
We'll be able to have three _channels_ of packages: **stable**, **unstable** and daily.
If the fine folks from Fedora or OpenSuse will that the scripts and spec files and adapt them for their needs and _rules_, they are free to do so, and i am happy to respond to constructive criticism, but my expectations on the latter are very low. I've already been _lectured_ several times about how things are supposed to be from people that don't have a clue how scientists use scientific software...

**Comment by junghans** [comment]
I am maintaining a handful of packages in fedora and usually making a package is easy if the buildsystem is standard, which it isn't for LAMMPS, so I will just start from your spec file and see how it goes.

There is a really old version of LAMMPS for OpenSuse here:
https://build.opensuse.org/package/show/science/lammps

**Comment by junghans** [comment]
And here is a lammps rpm:
https://build.opensuse.org/package/show/science/lammps
build with #573.

**Comment by junghans** [comment]
And one for fedora:
https://koji.fedoraproject.org/koji/taskinfo?taskID=20725103

**Comment by junghans** [comment]
Fedora is done: https://src.fedoraproject.org/rpms/lammps and binary packages should show up for the users in the next couple of days.

OpenSuse is still in progress: https://build.opensuse.org/request/show/517053

These rpms are really just a start and as we are working on #616, so can make things more user friendly.

**Comment by junghans** [comment]
It hit Fedora 25, one can test with:
```
dnf install lammps --enablerepo=updates-testing
```

**Comment by junghans** [comment]
And Fedora 26 and CentOS7 as well:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-628075ea93
https://bodhi.fedoraproject.org/updates/FEDORA-2017-f348e9d287
https://bodhi.fedoraproject.org/updates/FEDORA-2017-34fadcf36d
