### ISSUE TITLE
[BUG] Documentation-Code Mismatch for Default Error Argument in fix halt

### ISSUE THREAD

**Issue by zrzrv5** [lammps/lammps#4016]
**Summary**

Discrepancy between `fix halt` documentation and default optional argument in the code.

**LAMMPS Version and Platform**
LAMMPS (23 Jun 2022 - Update 1)  

**Expected Behavior**

The `fix halt` [documentation](https://docs.lammps.org/fix_halt.html#default) states that the default error argument is hard, but the code in [`fix_halt.cpp` ](src/fix_halt.cpp)at line 92 sets `eflag = SOFT` as the default.

**Comment by akohlmey** [comment]
@zrzrv5 thanks for the report. This will be remedied with the next LAMMPS feature release.
