### ISSUE TITLE
[Contribution] add macos gpu support in Kokkos package using VkFFT library

### ISSUE THREAD

**Issue by alphataubio** [lammps/lammps#4020]
**Summary**

# #add macos gpu support in Kokkos package using VkFFT library.

**Detailed Description**

Since my applications are related to solvated protein-dna complexes, most of the time ~80% in my lammps simulations are in kspace. without further detailed profiling im pretty sure it's all FFT related. i have limited access to an academic cluster but unlimited access to my mac mini at home with 8 gpus. this feature would allow a lot of engineering students to run some moderate lammps simulations on their mac laptops without having to always rely on submitting small to medium jobs to clusters.

im not asking to add the feature, im offering a contribution and posting as an issue here first given section 3.2 of lammps documentation. i would appreciate some guidance on what files to add/modify in kokkos package however, and how to use the unit tests to validate new code.

my first idea was to code kokkos fft functions natively for apple metal gpu from scratch, but a mature stable github library is already available called VKFFT so it would be a matter of integrating VkFFT into the Kokkos package and adding the METAL as a GPU architecture:

https://github.com/DTolm/VkFFT

i have compiled the VkFFT test suite on my mac mini m1 and it runs great.

 ps: i cant figure out how to add KOKKOS label to my issue

**Comment by akohlmey** [comment]
> most of the time ~80% in my lammps simulations are in kspace. without further detailed profiling im pretty sure it's all FFT related.

If you are spending 80% of the time with Kspace you are likely using some inefficient settings somewhere.
Can you provide a representative input and the corresponding command line and the output of "lmp -h"?

> ps: i cant figure out how to add KOKKOS label to my issue

You need Triage permission for that.

Update1 2023-12-17:
If you want GPU acceleration you should check out, if you have working OpenCL support. Then you can compile LAMMPS with the GPU package and make some use of the GPU (for pair style computation, which should be the dominant term for properly balanced runs *and* can run concurrently to bonded and kspace on the CPU).

Update2 2023-12-17: FWIW, you can determine the percentage of time spent in FFT (for CPU based computation) by adding `kspace_modify fftbench yes` to your input. For the peptide example for example on my NUC machine with an Intel Core i5-10210U CPU I get:
```lammps
Loop time of 1.02114 on 4 procs for 300 steps with 2004 atoms

Performance: 50.767 ns/day, 0.473 hours/ns, 293.788 timesteps/s, 588.751 katom-step/s
99.5% CPU use with 4 MPI tasks x 1 OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 0.71829    | 0.73097    | 0.74999    |   1.4 | 71.58
Bond    | 0.00097526 | 0.0023216  | 0.0036839  |   2.6 |  0.23
Kspace  | 0.087296   | 0.10457    | 0.11656    |   3.6 | 10.24
Neigh   | 0.10846    | 0.10849    | 0.10853    |   0.0 | 10.62
Comm    | 0.033467   | 0.033928   | 0.034897   |   0.3 |  3.32
Output  | 0.00019469 | 0.00021081 | 0.00025859 |   0.0 |  0.02
Modify  | 0.03706    | 0.037191   | 0.037275   |   0.0 |  3.64
Other   |            | 0.003461   |            |       |  0.34

FFT time (% of Kspce) = 0.0156599 (14.98)
FFT Gflps 3d (1d only) = 10.505403 44.463748
```

So only 10% of the total time is spent on Kspace and only 15% of that on the FFTs, so 1.5% of the total time.

**Comment by alphataubio** [comment]
i havent done the kspace_modify fftbench yet.

> If you are spending 80% of the time with Kspace you are likely using some inefficient settings somewhere.

based on this comment, i reviewed my old log files and the pattern is clear. it was back when i was trying to do implied solvent using fix langevin and fix nve. once i got to solvated protein-dna complex, kspace went down to ~20%. also the default from charmmgui was "kspace_style pppm/kk 1e-6". fft was probably converging very slow trying to get to 1e-6 relative error on a mostly empty domain ( i needed lots of extra space around the nucleosome so the histone tails would have room to swing around and not hit the boundary conditions.)

>2cv5-dna/slurm-13040165.out:Kspace   | 93.59
>2cv5-dna/slurm-13040165.out:Kspace   | 94.15
>2cv5-dna/lammps/slurm-13336902.out:Kspace   | 95.42
>2cv5-dna/lammps/slurm-13326282.out:Kspace   | 95.33
2cv5-prot/slurm-13004263.out:Kspace   | 65.57
2cv5-prot/slurm-13004263.out:Kspace   | 59.45
2cv5-prot/slurm-13004982.out:Kspace   | 73.15
2cv5-prot/slurm-13004982.out:Kspace   | 73.96
2cv5-prot/slurm-13005945.out:Kspace   | 88.60
2cv5-prot/log.lammps:Kspace   | 99.21
2cv5-prot/slurm-13002964.out:Kspace   | 82.53
2cv5-prot/slurm-13002964.out:Kspace | 54.50
2cv5-prot/slurm-13007993.out:Kspace   | 88.34
2cv5-prot/slurm-13007993.out:Kspace   | 85.80
2cv5-prot/nohup.out:Kspace  | 98.23
2cv5-prot/slurm-13005084.out:Kspace  | 88.27
2cv5-prot/slurm-13005084.out:Kspace   | 85.96
2cv5-prot/slurm-13132755.out:Kspace   | 99.21
2cv5-prot/slurm-13004073.out:Kspace  | 80.55
2cv5-prot/slurm-13004073.out:Kspace   | 79.52
2cv5-solution-dna/lammps/slurm-13398261.out:Kspace   | 22.62
2cv5-solution-dna/lammps/slurm-13398261.out:Kspace   | 26.82
2cv5-solution-dna/lammps/slurm-13390489.out:Kspace  | 20.06
2cv5-solution-dna/lammps/slurm-13390489.out:Kspace   | 24.24
2cv5-solution-prot-dna/lammps/slurm-13427969.out:Kspace   | 34.04
2cv5-solution-prot-dna/lammps/slurm-13427969.out:Kspace  | 37.95
2cv5-solution-prot-dna/lammps/slurm-13427734.out:Kspace   | 32.36

**Comment by akohlmey** [comment]
It is not very efficient to use a FFT grid based solver with lots of empty space since the performance of that solver is mostly based on the number of grid points (and thus the volume of the cell) and not so much on the number of atoms. This can be augmented by increasing the coulomb cutoff which will reduce the time spent in KSpace by indirectly changing the reciprocal space cutoff and thus the number of required gridpoints. This is usually quite efficient, since you have few particles and thus the O(N**3) scaling with the cutoff becomes relevant only with a very large cutoff.

 If not all particles are charged, further time can be saved by using pppm/cg instead of pppm.

1.0e-6 is an extremely conservative choice for kspace convergence. 1.0e-5 is often sufficient. With fixed volume, you can even drop it to 1.0e-4.

I noticed that the CHARMM-GUI produced inputs set "newton off". Removing that line also often results in a speedup.

**Comment by alphataubio** [comment]
HOWEVER i still want to contribute as much apple gpu METAL code to kokkos as possible. we have a 50 cpu years allocation on an academic cluster shared by my research group of several grad students at the university hospital. i have a mac mini m1 with 8 cpu years idling in my basement office 24/7, plus 8 gpu years doing almost nothing ever. even VMD barely uses one gpu. 

as a NeXT alumni, im a big fan of hardware abstraction layers (remember ave tevanian and his phd thesis...) so thats why im willing to do the extra work upfront to have my lammps codes being portable. we have heterogenous clusters in alliancecan.ca: AMD only no gpu, v100 on power9, p100/v100/t4/a100 on broadwell/cascade/skylake, ... plus my macs at home

this would be quite handy for many engineering/chemistry students everywhere running lammps on their mac laptops instead of having to set them up with cluster accounts.

**Comment by akohlmey** [comment]
> this would be quite handy for many engineering students running lammps on the mac laptops instead of having to set them up with cluster accounts.

The first step in that direction would be to try out compiling the GPU package with OpenCL support. After all, Apple invented OpenCL, did they not? I am getting a very decent 10x speedup from a lowly Intel UHD GPU in an Intel core i5 mobile CPU in my Intel NUC box at home with the GPU package and OpenCL.

KOKKOS support is a different story. You probably first have to work with the Kokkos library developers to have general support for Apple Metal GPU acceleration. I only know about CUDA, HIP/ROCm, and SYCL as GPU backends in Kokkos.
https://kokkos.github.io/

**Comment by alphataubio** [comment]
opencl is just another extra layer with more overhead, im not wasting any effort there my humble opinion sorry.

i think kokkos long-term is where everything should be going. apple silicon m1,m2,m3,... cpus and gpus is just another architecture that satisfies the Kokkos Abstract Machine Model. and there will be many more.

so yes building a native apple backend for kokkos is a "dream-in-color" long-term project i wont be tackling just yet so ill close this issue for now. ill make a contribution offer to the kokkos github instead if/when i can find some funding from somewhere after my classes for the winter term are done.

thanks @akohlmey as always for your support and advice, your cmap bugfix just made a huge difference to my solvated protein-dna complexes simulations !
