### ISSUE TITLE
[BUG] OpenMP: omp.h not found by CMake when using oneapi preset

### ISSUE THREAD

**Issue by donatas-surblys** [lammps/lammps#4033]
**Summary**

OpenMP detection fails with cmake when using the oneapi.cmake preset, because it has two openmp flags: -qopenmp -qopenmp-simd
This causes the flags to get quoted in the detection script, which makes it fail.
Therefore, CMake always fails the OpenMP test, and turns the flags off, even when it is available.

**LAMMPS Version and Platform**

Tested with latest stable version of 2Aug2023_update2 and the latest develop branch.
Tested with CMake versions 3.20.4 and 3.28.1.
Tested with Intel oneapi versions 2023.0.0 and 2024.0.2.
Tested with RHEL 7.5 and openSUSE Leap 15.5.

**Expected Behavior**

As Intel oneapi has OpenMP capabilities, the CMake script should have detected it, as in the following log:
> -- Looking for C++ include omp.h 
> -- Looking for C++ include omp.h - found

**Actual Behavior**

Currently, CMake doesn’t detect the OpenMP when used with the oneapi preset, which turn off OpenMP capabilities:
> -- Looking for C++ include omp.h
> -- Looking for C++ include omp.h - not found

**Steps to Reproduce**

Install the Intel HPC kit.
```
cd <LAMMPS folder>
mkdir test
cd test
cmake -C ../cmake/presets/oneapi.cmake ../cmake
```

**Further Information, Files, and Links**

The reason is that the two OpenMP flags are used quoted in the test script, resulting in an unknown argument error, as seen in the log:

> Change Dir: /home/test_user/rvc/lammps/test/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_e55b4/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_e55b4.dir/build.make CMakeFiles/cmTC_e55b4.dir/build
> gmake[1]: Entering directory '/home/test_user/rvc/lammps/test/CMakeFiles/CMakeTmp'
> Building CXX object CMakeFiles/cmTC_e55b4.dir/CheckIncludeFile.cxx.o
> /opt/intel/oneapi/compiler/2024.0/bin/icpx   -qopenmp -qopenmp-simd -fPIE -std=c++11 -MD -MT CMakeFiles/cmTC_e55b4.dir/CheckIncludeFile.cxx.o -MF CMakeFiles/cmTC_e55b4.dir/CheckIncludeFile.cxx.o.d -o CMakeFiles/cmTC_e55b4.dir/CheckIncludeFile.cxx.o -c /home/test_user/rvc/lammps/test/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
> Linking CXX executable cmTC_e55b4
> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e55b4.dir/link.txt --verbose=1
> /opt/intel/oneapi/compiler/2024.0/bin/icpx  -qopenmp -qopenmp-simd "-qopenmp -qopenmp-simd" CMakeFiles/cmTC_e55b4.dir/CheckIncludeFile.cxx.o -o cmTC_e55b4  -liomp5
> icpx: error: unknown argument: '-qopenmp -qopenmp-simd'
> gmake[1]: *** [CMakeFiles/cmTC_e55b4.dir/build.make:100: cmTC_e55b4] Error 1
> gmake[1]: Leaving directory '/home/test_user/rvc/lammps/test/CMakeFiles/CMakeTmp'
> gmake: *** [Makefile:127: cmTC_e55b4/fast] Error 2

It’s possible to make the detection work if you force a single OpenMP flag:

> cmake -C ../cmake/presets/oneapi.cmake -DOpenMP_CXX_FLAGS=-qopenmp ../cmake

This might be because the following omp.h detection function in LAMMPSUnits.cmake only expects one OpenMP flag, but this is beyond my area of expertise:
```
# helper function to check for usable omp.h header
function(check_omp_h_include)
  find_package(OpenMP COMPONENTS CXX QUIET)
  if(OpenMP_CXX_FOUND)
    set(CMAKE_REQUIRED_FLAGS ${OpenMP_CXX_FLAGS})
    set(CMAKE_REQUIRED_INCLUDES ${OpenMP_CXX_INCLUDE_DIRS})
    set(CMAKE_REQUIRED_LINK_OPTIONS ${OpenMP_CXX_FLAGS})
    set(CMAKE_REQUIRED_LIBRARIES ${OpenMP_CXX_LIBRARIES})
    check_include_file_cxx(omp.h _have_omp_h)
  else()
    set(_have_omp_h FALSE)
  endif()
  set(HAVE_OMP_H_INCLUDE ${_have_omp_h} PARENT_SCOPE)
endfunction()

```

**Comment by akohlmey** [comment]
Can you please try with the two attached variants for the preset file and report back if any or both can address the issue?
[oneapi-var-1.cmake.txt](https://github.com/lammps/lammps/files/13832309/oneapi-var-1.cmake.txt)
[oneapi-var-2.cmake.txt](https://github.com/lammps/lammps/files/13832307/oneapi-var-2.cmake.txt)

**Comment by donatas-surblys** [comment]
Both of them worked. The relative info is as follows.

Command:
`cmake -C ../oneapi-var-1.cmake.txt ../cmake`

Output:
> -- Looking for C++ include omp.h
> -- Looking for C++ include omp.h - found
> -- Found OpenMP_CXX: -qopenmp;-qopenmp-simd  
> -- Found OpenMP: TRUE  found components: CXX 

Log:
> Determining if the include file omp.h exists passed with the following output: 
> Change Dir: /home/test_user/rvc/lammps/test_v1/CMakeFiles/CMakeTmp 
>  
> Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_1decc/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_1decc.dir/build.make CMakeFiles/cmTC_1decc.dir/build 
> gmake[1]: Entering directory '/home/test_user/rvc/lammps/test_v1/CMakeFiles/CMakeTmp' 
> Building CXX object CMakeFiles/cmTC_1decc.dir/CheckIncludeFile.cxx.o 
> /opt/intel/oneapi/compiler/2024.0/bin/icpx   -qopenmp -fPIE -std=c++11 -MD -MT CMakeFiles/cmTC_1decc.dir/CheckIncludeFile.cxx.o -MF CMakeFiles/cmTC_1decc.dir/CheckIncludeFile.cxx.o.d -o CMakeFiles/cmTC_1decc.dir/CheckIncludeFile.cxx.o -c /home/test_user/rvc/lammps/test_v1/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx 
> Linking CXX executable cmTC_1decc 
> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_1decc.dir/link.txt --verbose=1 
> /opt/intel/oneapi/compiler/2024.0/bin/icpx  -qopenmp -qopenmp -qopenmp-simd CMakeFiles/cmTC_1decc.dir/CheckIncludeFile.cxx.o -o cmTC_1decc  -liomp5  
> gmake[1]: Leaving directory '/home/test_user/rvc/lammps/test_v1/CMakeFiles/CMakeTmp' 

Command:
cmake -C ../oneapi-var-2.cmake.txt ../cmake

Output:
> -- Looking for C++ include omp.h
> -- Looking for C++ include omp.h - found
> -- Found OpenMP_CXX: -fiopenmp  
> -- Found OpenMP: TRUE  found components: CXX 

Log:
> Determining if the include file omp.h exists passed with the following output:
> Change Dir: /home/test_user/rvc/lammps/test_v2/CMakeFiles/CMakeTmp 
> 
> Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_cd5c5/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_cd5c5.dir/build.make CMakeFiles/cmTC_cd5c5.dir/build
> gmake[1]: Entering directory '/home/test_user/rvc/lammps/test_v2/CMakeFiles/CMakeTmp'
> Building CXX object CMakeFiles/cmTC_cd5c5.dir/CheckIncludeFile.cxx.o
> /opt/intel/oneapi/compiler/2024.0/bin/icpx   -fiopenmp -fPIE -std=c++11 -MD -MT CMakeFiles/cmTC_cd5c5.dir/CheckIncludeFile.cxx.o -MF CMakeFiles/cmTC_cd5c5.dir/CheckIncludeFile.cxx.o.d -o CMakeFiles/cmTC_cd5c5.dir/CheckIncludeFile.cxx.o -c /home/test_user/rvc/lammps/test_v2/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
> Linking CXX executable cmTC_cd5c5
> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cd5c5.dir/link.txt --verbose=1
> /opt/intel/oneapi/compiler/2024.0/bin/icpx  -fiopenmp -fiopenmp CMakeFiles/cmTC_cd5c5.dir/CheckIncludeFile.cxx.o -o cmTC_cd5c5  /opt/intel/oneapi/compiler/2024.0/lib/libiomp5.so /usr/lib64/libpthread.so
> gmake[1]: Leaving directory '/home/test_user/rvc/lammps/test_v2/CMakeFiles/CMakeTmp'

**Comment by akohlmey** [comment]
@donatas-surblys thanks for testing. I'll add version 1 to PR #4018

**Comment by donatas-surblys** [comment]
Sorry, I just noticed that the OpenMP detection is fixed, but the compilation fails because the compile gets an "'-qopenmp;-qopenmp-simd'" argument.

> /opt/intel/oneapi/compiler/2024.0/bin/icpx -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_OMP_COMPAT=4 -DLAMMPS_SMALLBIG -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_MPICC_H -I/home/test_user/rvc/lammps/src -I/home/test_user/rvc/lammps/test_v1/styles -isystem /opt/intel/oneapi/mpi/2021.11/include -Wall -Wextra -g -O2 -DNDEBUG -fPIC -Wno-tautological-constant-compare -Wno-unused-command-line-argument "-qopenmp;-qopenmp-simd" -std=c++11 -MD -MT CMakeFiles/lammps.dir/home/test_user/rvc/lammps/src/angle.cpp.o -MF CMakeFiles/lammps.dir/home/test_user/rvc/lammps/src/angle.cpp.o.d -o CMakeFiles/lammps.dir/home/test_user/rvc/lammps/src/angle.cpp.o -c /home/test_user/rvc/lammps/src/angle.cpp
> icpx: error: unknown argument: '-qopenmp;-qopenmp-simd'

**Comment by akohlmey** [comment]
I cannot reproduce this on my machine with an Intel 2022 compiler and CMake 3.27. As with other CLang based compilers is the (new) Intel compiler a bit problematic for the FindOpenMP.cmake module since it can somehow detect the necessary compiler flags but not the OpenMP version.

The quoted flags should not at all happen with the v2 cmake preset. But having a recent CMake version is key in that case, since older CMake versions do not fully recognize the new Intel compiler in all its modules.

**Comment by donatas-surblys** [comment]
Thank you for the tip. I had the compile fail on the machine with an older CMake version. The compile passed when I updated CMake to the newest version.

So, in summary:
cmake version 3.20.4 fails with the above error.
cmake version 3.28.1 works.

**Comment by jfikar** [comment]
For Rocky 9.4 (RHEL 9.4):
cmake-3.26.5-2.el9.x86_64: fails, i.e. you get the `"-qopenmp;-qopenmp-simd"` in multiple makefiles
cmake-3.29.4 compiled by hand: works

But the new cmake complains about something in Lammps, which is going to be removed in the future versions of cmake

```
-- Downloading https://github.com/ICAMS/lammps-user-pace/archive/refs/tags/v.2023.11.25.fix.tar.gz
CMake Deprecation Warning at /home/fik/lammps-patch_17Apr2024/build/lammps-user-pace-v.2023.11.25.fix/CMakeLists.txt:12 (cmake_policy):
  The OLD behavior for policy CMP0109 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```
