### ISSUE TITLE
ave/chunk command does not calculate the average

### ISSUE THREAD

**Issue by mlaurien** [lammps/lammps#404]
I wanted to calculate an average density of my system over 1000 timesteps every 1000 timesteps using
_ave/chunk_ with the _ave one_ specification.
         _compute         1 all chunk/atom bin/3d x lower 1.0 y lower 1.0 z lower 1.0 units reduced_
         _fix                   1  all ave/chunk 1 1000 1000 1 density/mass ave one file densities.txt_
I cross-checked the results averaging the thermodynamic output of the density and realized that _ave/chunk_  does not average all 1000 values but only prints out the first value of all 1000 assigned to it. The same happens if I assign 800, 100.. values. I guess it might be a bug in the code.
I used the LAMMPS (17 Nov 2016) version.
[in.aveChunk.txt](https://github.com/lammps/lammps/files/827905/in.aveChunk.txt)
[aveChunk.restart2.txt](https://github.com/lammps/lammps/files/827906/aveChunk.restart2.txt)

**Comment by akohlmey** [comment]
Please also test with the latest patch release, which is 7 March 2017 currently to make certain, that this is not something that has already been addressed. Thanks.

**Comment by mlaurien** [comment]
I just tested with the 7 March '17 version and the problem remains.

**Comment by sjplimp** [comment]
Fixed this issue as well.  Note that to get what you are likely after,
time-averaged density of the entire system, you could just
use fix ave/time with an equal-style variable set to "density" which
is a thermo keyword.  If you want to do that with fix ave/chunk,
either for the overall density or per-bin density (chunks = bins),
then you need to use norm = sample.  It now gives the same
answer as fix ave/time.  If you use norm = one (the default), it
will only use the final volume of the system (on the last sampling step)
and be similar to what you getting before.  That is consistent
with the way the "norm" keyword is defined.  This is now spelled
out more clearly in the fix ave/chunk doc page.

Will be in a patch released later this week.
Steve
