### ISSUE TITLE
[BUG] Cmake build: Unittest unrecognized command line option when enabling KOKKOS Cuda

### ISSUE THREAD

**Issue by jobs-git** [lammps/lammps#4052]
**Summary**

As the title says. This is the error:
```bash
c++: error: unrecognized command-line option ‘-Xcudafe’
c++: error: unrecognized command-line option ‘--diag_suppress=unrecognized_pragma’
```

**LAMMPS Version and Platform**
Lammps-2Aug2023
Lammps-23Jun2022

**Expected Behavior**

The cmake build proceeds as usual

**Actual Behavior**

Error is produced, resulting to failed cmake build

**Steps to Reproduce**
1. Unpack the lammps-stable.tar.gz, create a build directory inside it then go to that directory
2. Launch cmake as follows:
```bash
cmake -C ../cmake/presets/basic.cmake -C ../cmake/presets/kokkos-cuda.cmake -DPKG_REAXFF=ON -DPKG_KOKKOS=ON -DPKG_GPU=ON -DGPU_API=CUDA -DGPU_ARCH=sm_60 -DBIN2C=/usr/local/cuda/bin/bin2c -DENABLE_TESTING=ON -DBUILD_SHARED_LIBS=OFF
```
3. Perform the following:
```bash
cmake --build .
```

**Comment by akohlmey** [comment]
The unittest tree does not support KOKKOS with GPUs anyway so if you want a production binary, you don't need to enable testing and if you want to do testing, you don't need to include KOKKOS with CUDA.

There are currently no plans to add this kind of support to the unittest tree.
