### ISSUE TITLE
add 'overlap' keyword to fix gcmc

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#409]
In some pair styles such as `pair_buck`, `pair_born` and `user-reaxc`, two atoms placed close to each other might have an arbitrary large, negative potential energy due to the form of the potential. For dynamics this is usually not happening due to repulsion, but `fix gcmc` might either insert or translate atoms past the repulsion barrier. This results in an physically invalid accepted state since ∆E<0 (I've seen ∆E=-1e6 for a single insertion).

I have experienced this with the `user-reaxc`. One solution which can solve this problem is to add a keyword _overlap cutoff_ which will reject any MC step that moves an atom so that any distance becomes smaller than _cutoff_. If _cutoff_ is chosen wisely, this will correspond to reject a step due to ∆E=+large, so the physics will remain what I intended to do.

**Comment by athomps** [comment]
This is a good idea.  The implementation for the default energy calc is a one-line addition. For the full_energy option, we can add a distance check over all local and ghost atoms.

**Comment by athomps** [comment]
I just checked this change into upstream.  It uses the keyword overlap_cutoff.

**Comment by andeplane** [comment]
I tested this and it seems to have problems with MPI (it hangs). I suspect that when one processor returns on line 2204 due to overlapping atoms, another processor may not, and proceed to modify->preforce on line 2215. 

This in turn may initiate MPI blocking in i.e. fix_qeq_reax.cpp where preforce calls calculate_Q which contains a comm->forward_comm_fix.

**Comment by athomps** [comment]
Good catch. I must not have tested this. I just fixed it in upstream.

Aidan


--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011

**Comment by andeplane** [comment]
Another thing that could be useful: If the overlap_cutoff is too high (meaning normal dynamics can produce distances lower than the cutoff), the energy on line 703 `energy_stored = energy_full();` will initially have the `MAXENERGYSIGNAL` energy which can result in only accepted insertions/deletions/translations. 

I suggest that if the `energy_stored` is of the order `MAXENERGYSIGNAL` an warning is printed at least.

**Comment by athomps** [comment]
I agree. Added a check every time old energy is calculated and a warning message if > MAXENERGYSIGNAL. Checked in to upstream.

W: Energy of old configuration in fix gcmc is > MAXENERGYTEST.

This probably means that a pair of atoms are closer than the
overlap cutoff distance for keyword overlap_cutoff.

--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011

**Comment by andeplane** [comment]
One more thing: currently the test is `rsq < overlap_cutoff`, and not `rsq < overlap_cutoff*overlap_cutoff` which would be the correct test.

**Comment by athomps** [comment]
Good point. I changed it in upstream.

--
      Aidan P. Thompson
      01444 Multiscale Science
      Sandia National Laboratories
      PO Box 5800, MS 1322      Phone: 505-844-9702
      Albuquerque, NM 87185     Fax  : 505-845-7442
      E-mail:athomps@sandia.gov Cell : 505-218-1011

**Comment by andeplane** [comment]
This can be closed now since all changes are on github.
