### ISSUE TITLE
[BUG] Memory leak of lammps_gather_concat functions in library.cpp

### ISSUE THREAD

**Issue by liqa1024** [lammps/lammps#4100]
## Summary

Memory leak of `lammps_gather_concat` function in [library.cpp](https://github.com/lammps/lammps/blob/develop/src/library.cpp) when `type=0`.

## LAMMPS Version and Platform

stable_2Aug2023_update3, windows and linux.

## Expected Behavior

No memory leak.

## Actual Behavior

Memory leak when use `lammps_gather_concat` function in library.h when `type=0`.

## Steps to Reproduce

**THIS CODE WILL FILL YOUR MEMORY VERY QUICKLY!!!**

```c
#include "library.h"
#include <stdlib.h>

int main(int argc, char **argv) {
    const char *lmpargv[] = {"liblammps", "-log", "none"};
    int lmpargc = sizeof(lmpargv)/sizeof(const char *);
    
    void *handle = lammps_open_no_mpi(lmpargc, (char **)lmpargv, NULL);
    
    lammps_command(handle, "units           metal");
    lammps_command(handle, "boundary        p p p");
    lammps_command(handle, "lattice         fcc 3.61");
    lammps_command(handle, "region          box block 0 5 0 5 0 5");
    lammps_command(handle, "create_box      1 box");
    lammps_command(handle, "create_atoms    1 box");
    lammps_command(handle, "mass            1 63.55");
    
    int *id = (int *)malloc(sizeof(int) * 5*5*5*4);
    
    while (true) {
        lammps_gather_concat(handle, "id", 0, 1, id);
    }
    
    free(id);
    
    lammps_close(handle);
    lammps_mpi_finalize();
    return 0;
}
```

**THIS CODE WILL FILL YOUR MEMORY VERY QUICKLY!!!**

## Further Information, Files, and Links

It seems like both `lammps_gather_atoms_concat` and `lammps_gather_concat` have this problem. For example, in [line 2861 of 
 library.cpp](https://github.com/lammps/lammps/blob/develop/src/library.cpp#L2861), memory is allocated for `copy`, which should be redundant because the recent free ([line 2890](https://github.com/lammps/lammps/blob/develop/src/library.cpp#L2890)) corresponds to the allocation memory in [line 2875](https://github.com/lammps/lammps/blob/develop/src/library.cpp#L2875).

**Comment by akohlmey** [comment]
@CHanzyLazer I can confirm the leak you are observing. Will have a closer look.

**Comment by akohlmey** [comment]
@CHanzyLazer 
the memory leak should be plugged with the following commit
https://github.com/lammps/lammps/pull/4103/commits/f8da51828a11eefe52f1ca8a2f09890d160aa897
This change is also included in the "maintenance" branch.

Please note that this part of the library interface is subject to some upcoming refactoring in the "develop" branch that will remove redundant functions and change the API.

Please see [this page](https://docs.lammps.org/Manual_version.html) for information about the relation between the different LAMMPS branches.
