### ISSUE TITLE
[BUG] Small error in in.ttm.mod example (Si.ttm_mod)

### ISSUE THREAD

**Issue by NicholasAsper** [lammps/lammps#4106]
**Summary**

γ_p and y_s values are switched with each other.

Ideally, users should be referencing papers when stating values, but I thought I'd report this to clear up confusion. 

**LAMMPS Version and Platform**

Latest/Windows 

**Expected Behavior**

gamma_p, mass/time units
24.443
gamma_s, mass/time units
39.235

**Actual Behavior**
gamma_p, mass/time units
39.235
gamma_s, mass/time units
24.443

**Further Information, Files, and Links**

T. Jarrin, A. Jay, M. Raine, N. Mousseau, A. Hémeryck and N. Richard, "Simulation of Single Particle Displacement Damage in Si₁₋ₓGeₓ Alloys—Interaction of Primary Particles With the Material and Generation of the Damage Structure," in IEEE Transactions on Nuclear Science, vol. 67, no. 7, pp. 1273-1283, July 2020, doi:

Antoine Jay, Melanie Raine, Nicolas Richard, Normand Mousseau, Vincent Goiffon, et al.. Simulation of Single Particle Displacement Damage in Silicon – Part II: Generation and Long-Time Relaxation of Damage Structure. IEEE Transactions on Nuclear Science, 2017, 64 (1), pp.141-148.
ff10.1109/TNS.2016.2628089ff. ffhal-01407740f

**Comment by 2838573741** [comment]
Hello, sorry to bother you! Recently I'm doing TTM-MD for femtosecond laser ablation of SiC, and I'd like to ask you for your advice, generally the unit of description for electron-lattice coupling coefficient in the literature is W/(m^3*K), but in the official document of lammps, this gamma_p is required to be in units of [mass/time], which is a bit confusing for me. These two units can't be converted either
