### ISSUE TITLE
An error in the "fix ttm command" description in the LAMMPS manual

### ISSUE THREAD

**Issue by phanomenaler** [lammps/lammps#4115]
**Summary**
In the LAMMPS manual's description of the "fix ttm command",about the keyword "infile", an example of a file that initializes the electronic temperature was given. However, there are some problems with the description in the example, which may cause users to misunderstand when using this command.

LAMMPS Version and Platform
Latest/Windows

**Detailed Description**
Here is the example  on a 1 by 2 by 3 grid  given in the manual:

```
# UNITS: metal COMMENT: initial electron temperature
1 1 1 1.0
1 1 2 1.0
1 1 3 1.0
1 2 1 2.0
1 2 2 2.0
1 2 3 2.0

```
According to the code  (src/EXTRA-FIX/fix_ttm_grid.cpp:334)  
```
 if (ix < 0 || ix >= nxgrid || iy < 0 || iy >= nygrid || iz < 0 || iz >= nzgrid)
          throw TokenizerException("Fix ttm/grid invalid grid index in input", "");
  ```
The index of the grid position should start at 0, not 1，so the example should be written in the following form in order to be read correctly:

```
# UNITS: metal COMMENT: initial electron temperature
0 0 0 1.0
0 0 1 1.0
0 0 2 1.0
0 1 0 2.0
0 1 1 2.0
0 1 2 2.0

```

**Comment by akohlmey** [comment]
No, the input example is correct.
You are discarding the fact that in lines 330-332 the grid indices are read *and* reduced by 1.
