### ISSUE TITLE
Implementing Custom pair_style in KOKKOS

### ISSUE THREAD

**Issue by pw0908** [lammps/lammps#4117]
**Summary**

I am trying to implement my own pair style in KOKKOS (to run my simulations on GPU). Everything compiles fine when I build LAMMPS. However, when I run the code using this pair style, I get a generic "free(): invalid pointer" error. 

**LAMMPS Version and Platform**

I am using the develop branch of LAMMPS, which I have forked in my own [repository](https://github.com/pw0908/lammps/commits/develop/) on Ubuntu 22.04 using CUDA 12.0. 

The new pair_style is called bornsolv.

**Details**

Pretty much what the summary said. I haven't had the time to generate an MWE to simulate a smaller system to reproduce the error. I'm just curious if there's something I've forgotten to include when adding a custom pair_style in KOKKOS.

As far as I can tell, my implementation has all the same elements as lj_cut for KOKKOS.

**Comment by akohlmey** [comment]
This sounds more like something that we should discuss here: https://matsci.org/c/lammps/lammps-development/42

> I get a generic "free(): invalid pointer" error.

That most likely means that you are trying to use `delete` on a pointer that has not properly been initialized to NULL or would be a GPU memory pointer

If you run under the debugger, you should be able to find out where the free() call happens from a stack trace.

I would suggest you compile LAMMPS and your pair style with KOKKOS/OpenMP to find out if the same issue persists.
Then it would be straightforward to pinpoint the culprit using valgrind's memcheck.

**Comment by stanmoore1** [comment]
This can also happen if you don't add `copymode` in the base class destructor, see https://github.com/lammps/lammps/blob/develop/src/pair_lj_cut.cpp#L50

**Comment by pw0908** [comment]
That fixed it! Thanks! 

I'll open a pull request soon. Is there a checklist of things I should do before opening a PR (tests, docs, etc.)?

**Comment by stanmoore1** [comment]
@pw0908 lots of info here: https://docs.lammps.org/Modify.html, e.g. https://docs.lammps.org/Modify_requirements.html
