### ISSUE TITLE
ERROR: Pair coeff for hybrid has invalid style: library.meam

### ISSUE THREAD

**Issue by ZAhra-Rjz** [lammps/lammps#4136]
Hi,
I have a SiC surface and want to see the adsorption of Si atoms on my surface. for this reason I used hybrid/overlay to be able to use different potentials like this:
pair_style      hybrid/overlay meam lj/cut 10.0
pair_coeff      * * library.meam C Si SiC.meam C Si
pair_coeff      1 2 lj/cut 0.0 0.0
pair_coeff      2 2 lj/cut 0.0 0.0

but when I run my script, I get this error:
ERROR: Pair coeff for hybrid has invalid style: library.meam (../pair_hybrid_overlay.cpp:63)
Last command: pair_coeff        * * library.meam C Si SiC.meam C Si

Do you know the reason? and can you guide me?
maybe hybrid/overlay doesn't work with meam?

**Comment by akohlmey** [comment]
This is not the right place to ask such questions. It is not a an issue if the LAMMPS code, but a user error. It should be posted to the LAMMPS forum on MatSci.org.
Apparently, you already did and have received a suitable response.
