### ISSUE TITLE
[Feature Request] Implement MPI collective operations in KOKKOS implementation of KSPACE

### ISSUE THREAD

**Issue by hagertnl** [lammps/lammps#4140]
Creating this issue to track the implementation of `kspace_modify collective yes` in Kokkos-enabled KSPACE package.
This has already been implemented in the non-Kokkos version of KSPACE.

**Detailed Description**

Collective code in the regular (non-Kokkos) node here:
https://github.com/lammps/lammps/blob/develop/src/KSPACE/remap.cpp#L113-L203
which is missing from the Kokkos version: https://github.com/lammps/lammps/blob/develop/src/KOKKOS/remap_kokkos.cpp#L106

The Kokkos version needs to support both GPU-aware MPI on and off, which is already done for the point-to-point version.

**Further Information, Files, and Links**

**Comment by hagertnl** [comment]
@stanmoore1 I started working on this and had a quick question -- do you know why the send/recv buffers for the Alltoallv are allocated during the execution stage of the remap (https://github.com/lammps/lammps/blob/6836bca5f8c40d87ae5bfd3baf7211ff81a74696/src/KSPACE/remap.cpp#L128) while the buffers for the MPI_Send/Irecv's are allocated during the plan phase (https://github.com/lammps/lammps/blob/6836bca5f8c40d87ae5bfd3baf7211ff81a74696/src/KSPACE/remap.cpp#L586)?

I am considering moving the Alltoallv buffer allocation to be in the same place as the Send/Irecv's to avoid excessive memory allocations, since we do know the sizes ahead of time. Thanks!

**Comment by stanmoore1** [comment]
@hagertnl I think that would be a good optimization--I don't see a reason to allocate memory inside the execution stage.
