### ISSUE TITLE
I still face the same problem. Adding -pk gpu 4 neigh no seems not works for me ,the related file have uploaded

### ISSUE THREAD

**Issue by ruio248** [lammps/lammps#4147]
I still face the same problem. Adding -pk gpu 4 neigh no seems not works for me ,the related file have uploaded
[test_code.zip](https://github.com/lammps/lammps/files/15103106/test_code.zip)
## issue 1 
(base) ruihao@ruihao:/media/ruihao/lammps$ mpirun -np 4 lmp -sf gpu -pk gpu 1 neigh no -in in
LAMMPS (2 Aug 2023 - Update 2)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
DumpFolderName
Lattice spacing in x,y,z = 3.14 3.14 3.14
Created orthogonal box = (-188.4 -188.4 -188.4) to (188.4 188.4 188.4)
  1 by 2 by 2 MPI processor grid
Created 3456000 atoms
  using lattice units in orthogonal box = (-188.4 -188.4 -188.4) to (188.4 188.4 188.4)
  create_atoms CPU = 0.072 seconds
3162509 atoms in group NO_FIX
293491 atoms in group FIX
2698631 atoms in group FREE
463878 atoms in group BATH
1 atoms in group CENTER
WARNING: Calling write_dump before a full system init. (src/write_dump.cpp:65)

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:
- GPU package (short-range, long-range and three-body potentials): doi:10.1016/j.cpc.2010.12.021, doi:10.1016/j.cpc.2011.10.012, doi:10.1016/j.cpc.2013.08.002, doi:10.1016/j.commatsci.2014.10.068, doi:10.1016/j.cpc.2016.10.020, doi:10.3233/APC200086
The log file lists these citations in BibTeX format.

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

ERROR: GPU package styles must not be used multiple times (src/pair_hybrid.cpp:608)
Last command: run             2000
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 429.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 430.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 429.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 430.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 429.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 430.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 429.
Cuda driver error 4 in call at file '/home/ruihao/lammps/lammps-2Aug2023/lib/gpu/geryon/nvd_device.h' in line 430.
## issue 2 
(base) ruihao@ruihao:/media/ruiha/lammps$ mpirun -np 4 lmp -sf gpu -pk gpu 4 neigh no -in in
LAMMPS (2 Aug 2023 - Update 2)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
ERROR: Could not find/initialize a specified accelerator device (src/GPU/gpu_extra.h:57)
Last command: package gpu 4 neigh no

_Originally posted by @ruio248 in https://github.com/lammps/lammps/issues/4131#issuecomment-2076200342_

**Comment by akohlmey** [comment]
Re first issue:

> ERROR: GPU package styles must not be used multiple times (src/pair_hybrid.cpp:608)

Please note this error message. Your input has:
```
pair_style      hybrid/overlay eam/alloy zbl 1.4 1.8 zbl 0.9 1.50 zbl 0.20 0.35
```
where zbl is used three times. As the error message indicates, this usage mode is not supported for GPU acceleration. You must at most have one instance of the zbl pair style in your hybrid command.

Re second issue:

> ERROR: Could not find/initialize a specified accelerator device (src/GPU/gpu_extra.h:57)
> Last command: package gpu 4 neigh no

This error message is self explanatory. You don't have 4 GPUs available on one of the compute nodes that you are running on. This may be due to a variety of reasons, but they are all local issues and thus need to be resolved by communicating with the support staff of the compute facility you are using. There is nothing that can be done on the LAMMPS side.

**Comment by stanmoore1** [comment]
You could try the KOKKOS package instead.
