### ISSUE TITLE
[BUG] run_style verlet/split fails for certain types of examples

### ISSUE THREAD

**Issue by bcdandurand** [lammps/lammps#4149]
**Summary**

I am working on experimental modifications of the VerletSplit class. So far, I tested the use of `run_style  verlet/split` on a number of example applications, and for one in particular, I run into an issue that appears to be fixed with a slight change of code. I would like to request that the development team for `VerletSplit.cpp` make changes for future releases as exemplified below to address the issue raised below.

**LAMMPS Version and Platform**

LAMMPS (7 Feb 2024). I'm currently working on a local git branch that is not modified from this version.

**Steps to Reproduce**

I modified my local copy of `lammps/examples/SPIN/dipole_spin/in.spin.iron_dipole_pppm` in the following manner:

1) In order to be able to run the example on more than 8 processors with MPI, I changed 
`region                 box block 0.0 12.0 0.0 12.0 0.0 12.0`    
to 
`region          box block 0.0 24.0 0.0 24.0 0.0 24.0`

2) I added the line `run_style       verlet/split` before the `run` statement

I built lammps with the additional packages needed to run this application. My build.sh script (run from my lammps/build directory) appears as follows:

```
#!/bin/bash

cmake -D PKG_SPIN=yes -D PKG_DIPOLE=yes -D PKG_MANYBODY=yes -D PKG_MOLECULE=yes -D PKG_KSPACE=yes -D PKG_RIGID=yes -D PKG_EXTRA-PAIR=yes -D PKG_EXTRA-MOLECULE=yes -D PKG_OPENMP=no -D PKG_MDI=yes -D PKG_DIELECTRIC=yes -D PKG_REPLICA=yes -D PKG_MISC=yes -D CMAKE_BUILD_TYPE=Release ../cmake
make
```

(I'm sure not all of these packages are needed for the SPIN application mentioned.) When I run, 

`$ mpirun -n 10 ~/lammps/build/lmp -partition 8 2 -in in.spin.iron_dipole_pppm`

I got memory violation errors which I traced to `VerletSplit::rk_setup`. After I replaced the line
`  MPI_Gatherv(atom->q,n,MPI_DOUBLE,atom->q,qsize,qdisp,MPI_DOUBLE,0,block);`
with
`  if(atom->q_flag)  MPI_Gatherv(atom->q,n,MPI_DOUBLE,atom->q,qsize,qdisp,MPI_DOUBLE,0,block);`
(i.e., adding the if statement) and re-building, the simulation appears to run as expected. The rationale for the change is that when the atom->q_flag is false, the buffers are not allocated/initialised even on the sending side.

**Further Information, Files, and Links**

While the fix provided above appears to work for the above example, this ticket is to request that the development team responsible for maintaining the VerletSplit class address for future releases the apparent issue that certain types of MPI communications are not always applicable for certain applications in this and perhaps other forms that may be anticipated.

**Comment by sjplimp** [comment]
@bcdandurand Thanks for flagging this issue.  You are correct that the current verlet/split only works for systems with charge.  It does not work for systems with dipoles or spin, though there are KSpace methods that support those options.  This is b/c verlet/split was written a long time ago, before those other KSpace options existed.

To make verlet/split work with the SPIN or the DIPOLE KSpace options would require several more changes than what you flag here.
I'm not clear if you are planning to work on that yourself?  Or if you are asking us to enhance verlet/split for those new use cases.  Either way it will require a new pull request be submitted with the changes, and some testing to be done.  Are you wanting to be involved?

For now I will submit a pull request that tests for use cases verlet/split does not yet support and throw an error.  Anything further will need to wait at least a few weeks until the developers release a new stable version of LAMMPS.

**Comment by akohlmey** [comment]
@bcdandurand FYI, we are going to close this bug report since the issue will be (for now) resolved with PR #4291. If you want to add support for the additional features to run style verlet/split yourself, you can submit a pull request with your (proposed) changes, after you have worked out the details.
Otherwise, you can submit a "Feature Request" issue to ask for it to be implemented by somebody else.

**Comment by bcdandurand** [comment]
Thank you @sjplimp and @akohlmey 
I'm working on experimental modifications to SplitVerlet.cpp toward introducing asynchrony through a local clone. I do not have the expertise to make the adjustments required for the use of pppm/dipole/spin myself, yet I would hesitate to request that VerletSplit be modified for the following reason. Since the time I submitted the ticket, I modified VerletSplit and KSPACE/PPPM so that the K space partition only solves the Poisson equation (in line with the Richards et al 2009 "Beyond Homogeneous Decomposition..." paper). Here, the R space partition computes and communicates brick densities to the K space partition, then K space computes the grid potentials and communicates them back to the R space processors which finish the rest of PPPM::compute(). I would need to port the modifications for the derivative classes of PPPM, which appears to be straightforward. With these changes, the need to communicate any atom information is avoided and the split verlet approach should thus be more versatile. If all goes well, I plan to port the modifications to a fork and submit a pull request.

**Comment by sjplimp** [comment]
@bcdandurand Thanks for the additional info.  Can you provide a few more details as to how this idea is different on than what the current verlet/split in LAMMPS is doing?  One advantage of the current approach is that it doesn't require mods to the PPPM class(es).  Also I think of it as already async since the KSpace portion is running simultaneous with the the RSpace and non-Coul forces.  Is there an anticipated speed-up advantage to the newer approach?

Also, I suggest when you submit an initial PR you limit it a single use case.  E.g. canonical PPPM, not all the variants.  That way we can see if we have suggestions before you do a lot of additional work.

**Comment by bcdandurand** [comment]
@sjplimp As to the additional asynchrony that would be added, this may not be beneficial (in terms of accuracy or even speed) over what currently exists, and so I'll defer explaining this for the moment until there is something more substantial/worthwhile to report. 

As to the other modification of the verlet/split, yes, you are correct in that it would require modification to PPPM and derivative classes. These changes are not too drastic, and can easily be organised through the addition of virtual interfaces. The changes are centred around a partitioning of PPPM::compute() into three parts, with the R space calling compute1(), computing and communicating the brick densities to the K space partition, which then calls compute2() to compute the vd[xyz]_brick cell values, which are communicated back to the R partition of processes, which then calls compute3() to finish accumulating the long-range forces to the kspace->force components.

As you suggest, I would start with a port to a fork for the PPPM instance at first (and not subclasses) to get possible suggestions. I'll reply again when I have pushed changes to a fork of the repository that is worth considering for discussion.
