### ISSUE TITLE
[BUG] Cohesion + damping `coeff_restitution` can result in nan positions

### ISSUE THREAD

**Issue by cgadal** [lammps/lammps#4180]
**Summary**

Set-up: 

- moving sphere impacting a fixed shere
- contact model is `pair_coeff      * * dmt ${E} ${e_rest} ${nu} ${g_dmt} tangential mindlin NULL ${x_t} ${mu_s} rolling none twisting none damping coeff_restitution`

Using the recently added damping mode 'coeff_restitution' (#4068) with the DMT cohesion, this can result in nan positions of the moving sphere after or before collision depending on values of $E$, $\gamma$ (`g_dmt`), the velocity of the incoming bead or $dt$.

**LAMMPS Version and Platform**

Develop branch, commit dad0d2651b9cdac5b9731ffaa16621c4a6c22451 on Ubuntu 22.

**Expected Behavior**

The colliding sphere should bounce away or stay stuck, depending on the cohesion force intensity. In any case, no nans should arise in its position. 

**Actual Behavior**

For low values of `g_dmt` or large impact velocity, it bounces back properly. 

However, for higher values of  `g_dmt`  or lower impact velocity (where I assume it's supposed to remain stuck to the fixed bead but I can check for sure), the position of the moving bead goes to nan at the time step right after it almost reaches its initial position.

Additionally, 

- for a working set of  `g_dmt` or impact velocity, decreasing $E$ can make the issue arise (which might be expected as a softer ball will remain stuck easier)
- decreasing strongly $dt$ can also make the issue arise. 
- it seems independent of the chosen restitution coefficient `e_rest`

**Steps to Reproduce**

In the input script given below, here are some set of values to reproduce or not the problem. Note that the system is periodic along the collision axis, such that the moving particle can come back from the other side and collide again, and again.

- `E = 1e6`, `g_dmt = 0` , `u0 = 1`, `dt = (1/5)*t_coll` -> OK, multiple collisions
- `E = 1e6`, `g_dmt = 0.0004` , `u0 = 1`, `dt = (1/5)*t_coll` -> Two first collisions ok, but particle is lost as soon as it touches the fixed one for the third time
- `E = 1e6`, `g_dmt = 0.0004`, `u0 = 1`, `dt = (1/30)*t_coll` -> First collision ok, but particle is lost as soon as it touches the fixed one for the second time
- `E = 1e6`, `g_dmt = 0.004`, `u0 = 1`, `dt = (1/5)*t_coll` -> Particle is lost at the end of the first collision
- `E = 1e6`, `g_dmt = 0.0004`, `u0 = 0.1`, `dt = (1/5)*t_coll` -> Particle lost at time step 2.
- `E = 1e5`, `g_dmt = 0.0004` , `u0 = 1`, `dt = (1/5)*t_coll` ->Particle is lost at the end of the first collision

Note: the time step is given as a fraction fo the collision time `t_col` to account for any change in impact velocity.

**Further Information, Files, and Links**

```
# Vibrating box with quantities of proper dimensions
variable        name string bead_collision

###############################################
# input parameters
###############################################

variable E equal 100000        # [Pa]
variable g_dmt equal 0.0004     # [N/m2]
variable e_rest equal 0.8       # restitution coefficient
variable U0    equal 1          # [m/s]
variable prefact_dt equal 1/5  # prefactor dt/t_collision

# timestep calculation
# needed variables 
variable    diam equal 0.0001                           # particle diameter
variable    rho equal 2650                              # density of grains, rho [kg/m^3]
variable    vol_part equal (4/3)*PI*(${diam}/2)^3       # particle volume [m3]
variable    mass equal ${rho}*${vol_part}               # particle mass [kg]
variable    nu equal 0.4                                # Poisson ratio
variable    Eff equal ${E}/(1-v_nu^2)/2             # Effective Young's modulus [Pa]
variable    k_n equal (4/3)*${Eff}                      # Corresponding Hertz stiffness [Pa]


variable    t_coll  equal 3.21*(v_mass/v_k_n/2)^(2/5)*(1/v_U0)^(1/5)
variable    dt      equal ${prefact_dt}*${t_coll}                        # time step, dt [s]

###############################################
# Input script
###############################################

# #### Initialization 

atom_style      sphere
units           si

# #### System definition

region          boxreg block 0 0.0005 0 0.0005 0 0.0005
create_box      2 boxreg
change_box      all boundary p p f

# create the two particles
create_atoms    1 single 0.00025 0.00025 0.00025
create_atoms    2 single 0.00015 0.00025 0.00025

group           fixed_part type 1
group           mobile_part type 2

set             group all diameter ${diam}
set             group all density ${rho}

velocity        mobile_part set ${U0} 0 0

# #### Simulation settings

# ## contact forces
pair_style      granular

# regular hertz contact force
pair_coeff      * * dmt ${E} ${e_rest} ${nu} ${g_dmt} tangential mindlin NULL 1 0.5 rolling none twisting none damping coeff_restitution  

# ## simulation parameters
neighbor        ${diam} bin
neigh_modify    delay 0 every 1 check yes
timestep        ${dt}

# ## fixes
fix             1 all nve/sphere                  # mandatory for granular style simulations
fix             fix_part fixed_part freeze

# ## computations
comm_modify     vel yes   # mandatory for granular style simulations

# ## writting to file
dump            1 all custom 1 ${name}.dump id type radius mass x y z vx vy vz

# #### Run simulation
timer           loop
run             10000
```

**Comment by cgadal** [comment]
I can't check as I don't have my computer with me anymore, but while reading the code, the variable damping coefficient has been implemented as:

$$\eta_{n} \propto \sqrt{\frac{m_{eff}*F_{n}}{\delta}}$$

instead of 

$$\eta_{n} \propto \sqrt{\frac{m_{eff}*F_{hertz}}{\delta}} \propto \sqrt{A\delta},$$
where $A$ is a constant function of the sphere parameters.

Hence for the dmt contact model, one can obtain this kind of coefficient:

$$\eta_{n} \propto \sqrt{A\delta + \frac{f_{\rm c}}{\delta}}$$
 
which I can imagine would lead to the apparition of nans for asymptotically small values of $\delta$.

Note that the current implementation ensures a constant restitution coefficient whatever the normal force model is. This is not what is implemented in LIGGGHTS, where only the hertz/hooke part of the normal force is taken into account even in the presence of cohesion.

I will check that this is the case on Monday if no one has confirmed this, but I'd suggest we stick the implementation to what's mentioned in https://www.cfdem.com/media/DEM/docu/gran_model_hertz.html or https://arxiv.org/pdf/2106.09576.pdf (p 7 eq 13b).

**Comment by jtclemm** [comment]
Thank you for finding and reporting the issue.

I thought the new damping model restricted usage to non-cohesive contact models, similar to Tsuji damping, but looking at the code I can see that was overlooked. To my knowledge, there is currently no effort to support DMT/JKR with the CoeffRestitution damping model, so I think the immediate solution to fix the bug is to simply add the intended error message for these scenarios. 

However, even with non-cohesive contacts, the square root can produce nan's due to machine precision errors (though extremely rare) so safeguards should also be added (as found in the Tsuji model)

https://github.com/lammps/lammps/blob/e8ee0d9e71fa65aaea0f6da8d89de42e4130490e/src/GRANULAR/gran_sub_mod_damping.cpp#L143-L145

**Comment by cgadal** [comment]
Is there a reason why it should not support cohesive models? To my knowledge, assuming a constant restitution coefficient and then adding a cohesion force has been several times in various studies. 

More generally, has there been any discussion on moving the cohesion part to a new class, similarly to damping models, s it was done in LIGGGHTS? Adding a constant cohesion force such as in the DMT remain extremely phenomenological, and could also be used with a Hooke (linear spring dashpot) model of the normal force? The JKR model as been derived properly for Hertwian contact, but we could rise a warning in the documentation stating this ?

This would help develop several new phenomenological models for cohesion that could be tried with both Hooke and Hertz models.

And, coming back to the initial issue, the CoeffRestitution damping model would keep the same forme (with the safeguard you mentioned), only accounting for the cohesionless normal force model.

**Comment by jtclemm** [comment]
> Is there a reason why it should not support cohesive models? To my knowledge, assuming a constant restitution coefficient and then adding a cohesion force has been several times in various studies.

It's more a matter of someone developing and testing the additional features. There are lots of capabilities that'd be great to have in LAMMPS (many are being actively developed), but most features are only added when someone has a need and implements it. You can also always create a separate feature request describing such changes for volunteers though. 

> More generally, has there been any discussion on moving the cohesion part to a new class, similarly to damping models, s it was done in LIGGGHTS?

I'm not familiar with the structure of granular pair styles in LIGGGHTS, but I agree that could be a nice solution. At the least, it probably would be good to separately store repulsive and attractive forces in the normal model. Again, however, it's a matter of someone prioritizing the development.

**Comment by cgadal** [comment]
> > Is there a reason why it should not support cohesive models? To my knowledge, assuming a constant restitution coefficient and then adding a cohesion force has been several times in various studies.
> 
> It's more a matter of someone developing and testing the additional features. There are lots of capabilities that'd be great to have in LAMMPS (many are being actively developed), but most features are only added when someone has a need and implements it. You can also always create a separate feature request describing such changes for volunteers though.
> 

I understand. Note that if we simply switch the implementation of $\eta_n$ to its explicit formula (the one given in the doc), we could simply raise a warning in the doc and while running lammps stating that this has not been derived for cohesive models.

> > More generally, has there been any discussion on moving the cohesion part to a new class, similarly to damping models, s it was done in LIGGGHTS?
> 
> I'm not familiar with the structure of granular pair styles in LIGGGHTS, but I agree that could be a nice solution. At the least, it probably would be good to separately store repulsive and attractive forces in the normal model. Again, however, it's a matter of someone prioritizing the development.

I will work a lot with cohesive granular and lammps in the coming months/years. If that's okay, I will create a separate feature request and start working on this.
