### ISSUE TITLE
I encounter the error that:'MPI_ABORT was invoked on rank 71 in communicator MPI_COMM_WORLD with errorcode 1.'  in the lammps running process,however,I am not able to solve it ,please give me some advice Thank you!

### ISSUE THREAD

**Issue by LHW20242** [lammps/lammps#4186]
Please help me  solve the following problems:

I ran the lammps calculation in Sugon Supercomputer, but an operation error occurred. The job was terminated before the step size I set was calculated. Is there a way to solve this?

The number of atoms is 7078, and the lammps version is LAMMPS (7 Aug 2019)

The error message is as follows
'ERROR on proc 71: step300299-ran out of space on angle_list: top=1052, max=1016 (../reaxc_valence_angles.cpp:414)
Last command: run              900000  
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.'

'MPI_ABORT was invoked on rank 71 in communicator MPI_COMM_WORLD
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.'

Thanks!
The error file is as follows：
[slurm_16064284.txt](https://github.com/user-attachments/files/15598970/slurm_16064284.txt)

**Comment by akohlmey** [comment]
> The number of atoms is 7078, and the lammps version is LAMMPS (7 Aug 2019)

This is a *very* old version of LAMMPS with known and fixed bugs. Please update to a more recent version.

> The error message is as follows
> 'ERROR on proc 71: step300299-ran out of space on angle_list: top=1052, max=1016 (../reaxc_valence_angles.cpp:414)
> Last command: run 900000

This kind of error often happens with ReaxFF when the system changes a lot, e.g. when compressing a dilute sample or when atoms or molecules aggregate for some reason. There are two possible remedies (which ran be used together):
- compile (a current) LAMMPS (version) with the KOKKOS package (with just the serial backend, if you don't want to use GPU support or OpenMP) and use the KOKKOS version of ReaxFF which has a more robust memory management.
- break your "run 900000" command down into multiple steps, e.g. with:
```
variable i loop 9
label loop

run 100000

next i
jump SELF loop
```
This way ReaxFF will re-initialize its heuristics based memory buffers for every run command and adapt more easily to the changes in the system.

**Comment by LHW20242** [comment]
> > The number of atoms is 7078, and the lammps version is LAMMPS (7 Aug 2019)
> 
> This is a _very_ old version of LAMMPS with known and fixed bugs. Please update to a more recent version.
> 
> > The error message is as follows
> > 'ERROR on proc 71: step300299-ran out of space on angle_list: top=1052, max=1016 (../reaxc_valence_angles.cpp:414)
> > Last command: run 900000
> 
> This kind of error often happens with ReaxFF when the system changes a lot, e.g. when compressing a dilute sample or when atoms or molecules aggregate for some reason. There are two possible remedies (which ran be used together):
> 
> * compile (a current) LAMMPS (version) with the KOKKOS package (with just the serial backend, if you don't want to use GPU support or OpenMP) and use the KOKKOS version of ReaxFF which has a more robust memory management.
> * break your "run 900000" command down into multiple steps, e.g. with:
> 
> ```
> variable i loop 9
> label loop
> 
> run 100000
> 
> next i
> jump SELF loop
> ```
> 
> This way ReaxFF will re-initialize its heuristics based memory buffers for every run command and adapt more easily to the changes in the system.

Thank you for your suggestion

**Comment by akohlmey** [comment]
@LHW20242 did you resolve your issue?

**Comment by LHW20242** [comment]
> @LHW20242 did you resolve your issue? 你解决你的问题了吗？

yes,I update to a more recent version,It works now, thank you very much
