### ISSUE TITLE
[Feature Request] Implement adjustments to b2y and b2x used in the k_transpose kernel launch

### ISSUE THREAD

**Issue by tpcbtw** [lammps/lammps#4206]
**Summary**
When running large-scale simulations with GPU acceleration in LAMMPS, a "Cuda driver error 1" can occur due to the CUDA block count exceeding 65535. This issue is particularly noticeable with over 500k atoms of `atom_type full` on a single GPU. A temporary fix involves limiting _num_blocks, but the root cause is the small block size in the `k_transpose` kernel. Adjusting the block size and adding checks in `LAL_Device::init()` is required for a permanent solution.

**Detailed Description**
When running large-scale simulations with GPU acceleration in LAMMPS, a "Cuda driver error 1" can occur. This error arises when the number of CUDA blocks (GX) exceeds the limit of 65535.

During previous discussions, it was noted that failures particularly occur when 500k atoms of `atom_type full` are assigned to a single GPU. The input causing this issue is provided here.[in.lj.txt](https://github.com/user-attachments/files/15988974/in.lj.txt)

Adding a simple code snippet in `nvd_kernel.h` within the run() function just before `CU_SAFE_CALL(cuLaunchKernel)` to `limit _num_blocks` below 65535 can temporarily fix the issue. However, the root cause lies in the small block size (8) for the `k_transpose` kernel when atom_style full is used.

To resolve this, the block size should be adjusted from 8 (default) to 4, then 2, and finally 1 to keep the block count below the maximum limit. Implementing this requires adjustments to b2y and b2x used in the k_transpose kernel launch and possibly adding a check in `LAL_Device::init()` for the max block count to return an error code (e.g., -17) to be handled by `check_flag()` in `gpu_extra.h`.

**Further Information, Files, and Links**
#4156  
@ndtrung81

**Comment by tpcbtw** [comment]
#4156

**Comment by ndtrung81** [comment]
@tpcbtw @Eddy-Barraud if you have a chance, you can try the changes in #4319

**Comment by Eddy-Barraud** [comment]
> @tpcbtw @Eddy-Barraud if you have a chance, you can try the changes in #4319

Thank you very much @ndtrung81 for this PR, it effectively increases the maximum number of beads per mpi proc with dpd/coul/slater/long pair style and atom style full. I couldn't check if my 5e06 beads works with 1 MPI proc (server outage), but at least i can confirm it runs with 3e06 beads on a single MPI rank, which wasn't working in the past.
