### ISSUE TITLE
[BUG] Issue with Python lmp.command("create_bonds single/angle") When Running in Parallel Using MPI

### ISSUE THREAD

**Issue by Mainv4** [lammps/lammps#4217]
**Summary**

Hello,

I am encountering an issue when running a LAMMPS simulation from Python  in parallel using MPI. The script works perfectly when executed without MPI, but it seems to hang at the line where it creates bonds based on the angles array when run with MPI. There is no error message; the process just stalls.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023) on Mac and Linux

**Expected Behavior**

The expected behavior is for the script to proceed without hanging, successfully creating bonds based on the angles array, similar to its behavior when not using MPI.

**Actual Behavior**

When running the script in parallel using MPI, it hangs at the following lines without any error message:

```python
for j in range(len(angles)):
    lmp.command("create_bonds single/angle 1 %i %i %i" % (int(angles[j][2]), int(angles[j][3]), int(angles[j][4])))
```

**Steps to Reproduce**

1. Prepare a Python script with the following content:

```python
from mpi4py import MPI
import numpy as np
import random
from lammps import lammps

def step(angles, nchains, lchain, alpha_in, alpha_out, proba_move):
    # Function code here

def launch_simulation(nchains, lchain, n_runs, length_run, dmp_freq, alpha_in, alpha_out, proba_move, seed, Pe, kappa, angles_in, data_file_in):
    me = MPI.COMM_WORLD.Get_rank()
    lmp = lammps(cmdargs=["-log", "none", "-screen", "none", "-nocite"])
    lmp.file("../run.in")
    if data_file_in == "":
        lmp.command("read_data single_chain.data")
    lmp.command("velocity all create 1.0 {}".format(seed))
    lmp.command("thermo 10000")
    lmp.command("thermo_style custom step temp epair emol press")
    lmp.command("pair_coeff * * 10.0 1.0")
    lmp.command("bond_coeff 1 300.0 1.5 10.0 1.0")
    lmp.command("angle_coeff 1 tangentialpropulsion 0.")
    lmp.command("fix 1 all nve")
    lmp.command("fix 2 all langevin 1.0 1.0 0.05 {}".format(seed))
    lmp.command("group polymers type 1")
    lmp.command("neigh_modify exclude molecule/inter polymers")
    lmp.command("angle_coeff 1 tangentialpropulsion {}".format(Pe))
    lmp.command("angle_coeff 2 cosine {}".format(kappa))
    lmp.command("dump dmp all custom {} dump.lammpstrj id type xu yu zu ix iy iz".format(dmp_freq))
    lmp.command("dump_modify dmp sort id")
    lmp.command("dump_modify dmp format line \"%d %d %.6f %.6f %.6f %d %d %d\"")
    lmp.command("write_data initial_state.data nocoeff")
    lmp.command("restart 10000 poly_sim.restart1 poly_sim.restart2")
    angles = []
    for i in range(n_runs):
        if me == 0:
            angles = step(angles, nchains, lchain, alpha_in, alpha_out, proba_move)
            with open("angles.dat", "a") as f:
                angle_str = " ".join([str(angles[j][3]) for j in range(len(angles))])
                f.write(str((i+1)*length_run)+" "+angle_str+"\n")
        lmp.command("run %i"%(length_run))
        lmp.command("delete_bonds all angle 1 remove special")
        for j in range(len(angles)):
            lmp.command("create_bonds single/angle 1 %i %i %i" % (int(angles[j][2]), int(angles[j][3]), int(angles[j][4])))
    lmp.command("write_data Final.data nocoeff")
    MPI.Finalize()

if __name__ == "__main__":
    from argparse import ArgumentParser
    parser = ArgumentParser(description='Launch a molecular dynamics simulation with LAMMPS in which the active sites migrate along the chain according to the TASEP model')
    parser.add_argument('--nchains', type=int, help='Number of chains', default=1)
    parser.add_argument('--lchain', type=int, help='Length of the chain', default=300)
    parser.add_argument('--n_runs', type=int, help='Number of steps', default=40000)
    parser.add_argument('--length_run', type=int, help='Length of the run', default=1000)
    parser.add_argument('--dmp_freq', type=int, help='Frequency of the dump', default=10000)
    parser.add_argument('--alpha_in', type=float, help='Rate of adding active sites at the beginning of the chain', default=0.01)
    parser.add_argument('--alpha_out', type=float, help='Rate of removing active sites at the end of the chain', default=1)
    parser.add_argument('--proba_move', type=float, help='Probability of moving to the right', default=0.5)
    parser.add_argument('--seed', type=int, help='Seed for the random number generator', default=1)
    parser.add_argument('--Pe', type=float, help='Peclet number', default=1)
    parser.add_argument('--kappa', type=float, help='Angle coefficient', default=0)
    args = parser.parse_args()
    launch_simulation(args.nchains, args.lchain, args.n_runs, args.length_run, args.dmp_freq, args.alpha_in, args.alpha_out, args.proba_move, args.seed, args.Pe, args.kappa, np.array([]), "")
```

2. Run the script using the following command:

```bash
mpirun -np 4 python3 test.py --nchains 10 --lchain 300 --n_runs 1000 --length_run 1000 --alpha_in 0.5 --alpha_out 1 --proba_move 0.5 --seed 1234 --Pe 1 --dmp_freq 100
```

**Note:** A custom `tangentialpropulsion` function has been added for the angle potential. However, this is not necessary for reproducing the test and can be replaced with any other type of angle potential.

**Further Information, Files, and Links**

[files.zip](https://github.com/user-attachments/files/16071446/files.zip)

**Comment by akohlmey** [comment]
> ```python
> for i in range(n_runs):
>         if me == 0:
>             angles = step(angles, nchains, lchain, alpha_in, alpha_out, proba_move)
>             with open("angles.dat", "a") as f:
>                 angle_str = " ".join([str(angles[j][3]) for j in range(len(angles))])
>                 f.write(str((i+1)*length_run)+" "+angle_str+"\n")
>         lmp.command("run %i"%(length_run))
>         lmp.command("delete_bonds all angle 1 remove special")
>         for j in range(len(angles)):
>             lmp.command("create_bonds single/angle 1 %i %i %i" % (int(angles[j][2]), int(angles[j][3]), int(angles[j][4])))
> ```

The problem is here. You are reading the "angles" data only on MPI rank 0, thus the "create_bonds" command is issued only on MPI rank 0. That is not correct. Any LAMMPS command *must* be executed on all MPI ranks with the exact same arguments. Due to the domain decomposition, LAMMPS has to determine on which subdomain(s) the angles have to be created, that requires communication, but in your case those MPI calls are unanswered because you only execute the LAMMPS command on MPI rank 0.

**Comment by Mainv4** [comment]
Thank you very much for your quick response, which makes sense. That said, even if you remove the ``me==0`` conditions, the script won't run. However, things now stall at the line ```lmp.command("run %i"%(length_run))```. But I also notice that my python script seems to be trying to run the simulation even though all the tasks associated with creating the angles have not been completed. 

I'm well aware that this isn't a bug, but a misuse on my side of the python interface to run lammps in parallel.

Would you please be able to give me the missing point in order to be able to run this python script correctly using MPI? 

Thank you in advance.

**Comment by akohlmey** [comment]
> Would you please be able to give me the missing point in order to be able to run this python script correctly using MPI?

That is *your* code and not part of LAMMPS and thus *you* have to debug it. 

I am not saying that there may not be LAMMPS bug looming as well, but at the current state of affairs, we will only look into it, if you can reproduce the issue without python but with a simple regular LAMMPS input file (you just make whatever you do in python explicit).

**Comment by Mainv4** [comment]
Thank you again for your reply. I solved the issue by adding the line 
```python
angles = MPI.COMM_WORLD.bcast(angles, root=0)
``` 
under the lines 
```python 
if me == 0:
    angles = step(angles, nchains, lchain, alpha_in, alpha_out, proba_move)
```
