### ISSUE TITLE
Add doc info about how to run python script on subset of all ranks (i.e. rank 0 only)

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#422]
I'm running a python script from LAMMPS input script which does file handling. I want only rank 0 to execute it. I didn't find how to do this in the docs, but one solution was to load MPI4Py in the script and do the test on rank there. 

If this is solution that you think will always work, it could be nice to mention this in the [docs](http://lammps.sandia.gov/doc/python.html).

**Comment by akohlmey** [comment]
you need to provide more detail and perhaps a simple example of what you have done, so we can weigh in whether this is a good idea or what alternatives exist.

**Comment by akohlmey** [comment]
closed for inactivity
