### ISSUE TITLE
[BUG] rpath issue with shared lib on macos sonoma 14.4.1

### ISSUE THREAD

**Issue by alphataubio** [lammps/lammps#4223]
**Summary**

liblammps.dylib not found from cmake installed location

**LAMMPS Version and Platform**

```
Large-scale Atomic/Molecular Massively Parallel Simulator - 17 Apr 2024 - Development
Git info (spica-kk / patch_17Apr2024-556-gbf4aab68d3-modified)


OS: Darwin 23.4.0 arm64

Compiler: Clang C++ Apple LLVM 15.0.0 (clang-1500.3.9.4) with OpenMP 5.0
C++ standard: C++17
MPI v1.0: LAMMPS MPI STUBS for LAMMPS version 17 Apr 2024

Accelerator configuration:

KOKKOS package API: OpenMP Serial
KOKKOS package precision: double
Kokkos library version: 4.3.1
OPENMP package API: OpenMP
OPENMP package precision: double
OpenMP standard: OpenMP 5.0
```

**Steps to Reproduce**

> $ cmake ../cmake -D BUILD_MPI=no -D LAMMPS_MACHINE=kk \
    -D CMAKE_CXX_FLAGS='-isystem /usr/local/include -g -O0' \
    -D ENABLE_TESTING=on -D ENABLE_COVERAGE=off \
    -D Kokkos_ENABLE_DEBUG=on -D BUILD_SHARED_LIBS=yes \
    -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=no  \
    -D Kokkos_ENABLE_SERIAL=yes -D Kokkos_ARCH_HOSTARCH=NATIVE \
    -D BUILD_OMP=yes -D Kokkos_ENABLE_OPENMP=yes  -D PKG_OPENMP=yes  \
    -D PKG_KSPACE=yes -D PKG_CG-SPICA=yes -D PKG_MOLECULE=yes \
    -D PKG_DPD-REACT=yes -D PKG_EXTRA-FIX=yes -D PKG_GRANULAR=yes  \
    -D CMAKE_INSTALL_PREFIX=~/.local; \
    cmake --build . -j 16; make install

**Actual Behavior**

> $ export LC_RPATH=/Users/mitch/.local/lib 
$ export LD_LIBRARY_PATH=/Users/mitch/.local/lib
$ /Users/mitch/.local/bin/lmp_kk -h

```
dyld[59858]: Library not loaded: @rpath/liblammps_kk.0.dylib
  Referenced from: <B8601D07-B8E8-4AC3-89C2-F25BC0A9A434> /Users/mitch/.local/bin/lmp_kk
  Reason: no LC_RPATH's found
```

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
On macOS you should be setting DYLD_LIBRARY_PATH and not LD_LIBRARY_PATH.

**Comment by alphataubio** [comment]
> On macOS you should be setting DYLD_LIBRARY_PATH and not LD_LIBRARY_PATH.

problem solved. thanks.

**Comment by akohlmey** [comment]
Also, you can configure LAMMPS with `-D LAMMPS_INSTALL_RPATH=yes` if you want to work around having to set the search path for shared libraries.
