### ISSUE TITLE
[BUG] Wrong CNA value(and neighbor list) when LAMMPS is run in a loop using next

### ISSUE THREAD

**Issue by schakrabortygithub** [lammps/lammps#4231]
**Summary**

If LAMMPS is run in a loop by using ```next``` and ```jump``` and if there is no data writing activity either using the ```restart``` or ```dump``` command in between the loop then it produces the wrong Common Neighbor Analysis(CNA) values. Probably due to corrupted neighbor list.
More details is in this thread at [LAMMPS Discussion forum](https://matsci.org/t/wrong-cna-value-when-lammps-is-run-in-a-loop-using-next/56414/4).

**LAMMPS Version and Platform**
LAMMPS version: LAMMPS (17 Apr 2024 - Development - patch_17Apr2024-219-g6d5aa1fbc6)
I was able to reproduce the issue in:
(1) Ubuntu(20.04.2 LTS) in WSL 
(2) Rocky Linux(9.2) in Stampede3 at Texas Advanced Computing Center(TACC).

**Expected Behavior**

```compute cna/atom``` should be able to detect fcc structure during the entire simulation in the attached LAMMPS input script.

**Actual Behavior**

The output of the CNA value changes abruptly when there is no writing activity in between the ```run``` within the ```loop```.  But if writing frequency is increased to write the data either using ```dump``` or ```restart``` during one loop then the problem goes away. So, just changing the dump frequency alters the simulation results. Log files also show the difference in the neighbor statistics.

**Steps to Reproduce**
Attached is a minimal LAMMPS input script to reproduce the problem. First, run the script as it is then change the ```dump``` frequency from 100 to 10 to see the difference.

**Further Information, Files, and Links**
#. The problem still appears whether using a single processor or multiple.
#. Using different potentials does not help.
#. Changing the boundary from “ppp” to “sss” to prevent atoms from hopping from one side to other does not help.
#. A dry run without any time integration does not show up the problem.

[script_LAMMPS_Basic.md](https://github.com/user-attachments/files/16200994/script_LAMMPS_Basic.md)

**Comment by sjplimp** [comment]
@schakrabortygithub Thanks for posting this bug report and test script.  It is hopefully fixed in PR #4239.  Please check if that's the case?

**Comment by schakrabortygithub** [comment]
@sjplimp 
Thanks for taking the time to look into this issue! The bug is indeed fixed in PR #4239.
