### ISSUE TITLE
[BUG] fix reaxff/bonds writing double output when doing a second run.

### ISSUE THREAD

**Issue by wverestek** [lammps/lammps#4234]
**Summary**

Not sure if this is intended behavior... fix reaxff/bonds writes double output to the output file when doing a second run.

**LAMMPS Version and Platform**

development branch pulled 2024-07-15

**Expected Behavior**

only one entry per write/timestep

**Actual Behavior**

the bonds snap shot is written twice

**Steps to Reproduce**

pair_style      reaxff NULL
pair_coeff      * * ffield.reax.CHON.2019 C H O N
fix                 qeq all qeq/reaxff 1 0.0 10.0 1.0e-6 reax

...

fix                bdump all reaxff/bonds 100 bonds.reaxff.dump

...

run              100
run              100

**Further Information, Files, and Links**

[example.zip](https://github.com/user-attachments/files/16232627/example.zip)

regards
Wolfgang

**Comment by akohlmey** [comment]
It is certainly inconsistent behavior and addressed in PR #4227  in commit 1d6959efe637c16df96bd9f860979cde4b8f426b

As a workaround, you can try using the second run command with "pre no" added, assuming there are no changes made to the system in between the two run commands that conflict with that setting).

**Comment by wverestek** [comment]
Thanks, for the suggestion.
