### ISSUE TITLE
[BUG] ValueTokenizer fails to read bigint on windows

### ISSUE THREAD

**Issue by alphataubio** [lammps/lammps#4246]
**Summary**

>18: [ RUN      ] PotentialFileReaderTest.convenience_functions
18: D:\a\lammps\lammps\unittest\formats\test_potential_file_reader.cpp(289): error: Expected equality of these values:
18:   reader.next_bigint()
18:     Which is: 2147483647
18:   9223372036854775807i64
18:     Which is: 9223372036854775807
18: [  FAILED  ] PotentialFileReaderTest.convenience_functions (3 ms)

>[ RUN      ] TextFileReaderTest.convenience_functions
20: D:\a\lammps\lammps\unittest\formats\test_text_file_reader.cpp(190): error: Expected equality of these values:
20:   reader.next_bigint()
20:     Which is: 2147483647
20:   9223372036854775807i64
20:     Which is: 9223372036854775807
20: [  FAILED  ] TextFileReaderTest.convenience_functions (0 ms)

**LAMMPS Version and Platform**

see PR https://github.com/lammps/lammps/pull/4245

**Expected Behavior**

read 9223372036854775807

**Actual Behavior**

got 2147483647

**Steps to Reproduce**

```
TEST_F(PotentialFileReaderTest, convenience_functions)
{
    FILE *fp = fopen("potential_reader.file", "w");
    fmt::print(fp, "123\n");
    fmt::print(fp, "-123.45\n");
    fmt::print(fp, "{}\n", DBL_MIN);
    fmt::print(fp, "{}\n", DBL_MAX);
    fmt::print(fp, "{}\n", -DBL_MIN);
    fmt::print(fp, "{}\n", -DBL_MAX);
    fmt::print(fp, "{}\n", MAXSMALLINT);
    fmt::print(fp, "{}\n", MAXTAGINT);
    fmt::print(fp, "{}\n", MAXBIGINT);
    fmt::print(fp, "fooBAR\n");
    fclose(fp);

    BEGIN_HIDE_OUTPUT();
    command("units real");
    PotentialFileReader reader(lmp, "potential_reader.file", "test");
    END_HIDE_OUTPUT();

    ASSERT_DOUBLE_EQ( reader.next_double(), 123 );
    ASSERT_DOUBLE_EQ( reader.next_double(), -123.45 );
    ASSERT_DOUBLE_EQ( reader.next_double(), DBL_MIN );
    ASSERT_DOUBLE_EQ( reader.next_double(), DBL_MAX );
    ASSERT_DOUBLE_EQ( reader.next_double(), -DBL_MIN );
    ASSERT_DOUBLE_EQ( reader.next_double(), -DBL_MAX );
    ASSERT_EQ( reader.next_int(), MAXSMALLINT );
    ASSERT_EQ( reader.next_tagint(), MAXTAGINT );
    ASSERT_EQ( reader.next_bigint(), MAXBIGINT );
    ASSERT_STREQ( reader.next_string().c_str(), "fooBAR" );
    platform::unlink("potential_reader.file");
}
```

**Further Information, Files, and Links**

could be a problem with _atoi64 on windows ?

tokenizer.cpp
>bigint ValueTokenizer::next_bigint()
{
  std::string current = tokens.next();
  if (!utils::is_integer(current)) { throw InvalidIntegerException(current); }
  return ATOBIGINT(current.c_str());
}

lmpwindows.h:
>#undef ATOBIGINT
#define ATOBIGINT _atoi64

**Comment by akohlmey** [comment]
@alphataubio I wanted to get rid of using the atoXX() functions for a long time since they return no error if the conversion failed or was only converting part of the string. Since strtoll() is part of the C++ standard, we don't have to mess with the quasi-posix functions a la windows and instead use the same standard function everywhere. This seems to fix the issue you are reporting. This needs a little extra work for some more cases (actually, I have a WIP branch with most of them, just had planned to work on completing that after the stable release) and more tests. BTW: the test is better added to the ValueTokenizer tests directly. See PR #4242
