### ISSUE TITLE
[BUG] `PyLammps.eval` throws `AttributeError` in ranks except rank 0 with mpi4py 4.0.0

### ISSUE THREAD

**Issue by njzjz** [lammps/lammps#4249]
**Summary**

When using mpi4py 4.0.0 (released two days ago) with pylammps, executing `PyLammps.eval` throws `AttributeError` in all ranks except rank 0.

I don't know whether it is a bug in mpi4py 4.0.0 or a breaking change that PyLammps needs to adopt.

**LAMMPS Version and Platform**

stable_2Aug2023_update3, Linux

**Expected Behavior**

With mpi4py 3.1.6, when doing `PyLammps.eval`, all ranks give the expected result (for example, `-4.77743273563228`).

**Actual Behavior**

With mpi4py 4.0.0, when doing `PyLammps.eval`, got
```
File "/usr/local/lib/python3.11/site-packages/lammps/pylammps.py", line 714, in eval
  value = self.lmp_print('"$(%s)"' % expr).strip()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

`PyLammps.lmp_print` returns the expected value (e.g. `-4.77743273563228`) in rank 0 but `None` in other ranks.

**Steps to Reproduce**

Use docker to run `docker build --progress=plain .` using the following docker file and the test script.

`Dockerfile`:

```dockerfile
FROM python:3.11

ARG LAMMPS_VERSION=stable_2Aug2023_update3
ARG INSTALL_PREFIX=/lammps

RUN apt-get update && apt-get -y install cmake mpich

RUN curl -L -o lammps.tar.gz https://github.com/lammps/lammps/archive/refs/tags/${LAMMPS_VERSION}.tar.gz \
  && tar vxzf lammps.tar.gz \
  && rm lammps.tar.gz \
  && cd lammps-${LAMMPS_VERSION} \
  && mkdir build \
  && cd build \
  && cmake -C ../cmake/presets/all_off.cmake \
     -DLAMMPS_EXCEPTIONS=yes \
     -D BUILD_SHARED_LIBS=yes \
     -D LAMMPS_INSTALL_RPATH=ON \
     -D CMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
     ../cmake \
  && make -j4 \
  && make install \
  && make install-python \
  && cd ../../ \
  && rm -rf lammps-${LAMMPS_VERSION}

ENV LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH

RUN pip install 'mpi4py'  # or change to 'mpi4py<4'
ADD test_mpi.py /test_mpi.py
RUN curl -L -o in.melt https://raw.githubusercontent.com/lammps/lammps/master/examples/melt/in.melt
RUN mpirun -np 4 python /test_mpi.py
```

`test_mpi.py`:

```py
from mpi4py import MPI
from lammps import PyLammps

L = PyLammps()
L.file("in.melt")

print("Potential energy: ", L.eval("pe"))

MPI.Finalize()
```

**Further Information, Files, and Links**

https://github.com/mpi4py/mpi4py/releases/tag/4.0.0

**Comment by akohlmey** [comment]
Using PyLammps for running with MPI in parallel is not a good idea. Some of the PyLammps functionality depends on capturing and parsing output from LAMMPS to the screen, and that makes it quite fragile.

With that in mind, I would consider the behavior of the new mpi4py more correct than the old one. PyLammps has to be considered an experiment to explore how far on can "pythonize" an interface to LAMMPS and as a basis for embedding LAMMPS into jupyter notebooks.

Perhaps @rbberger is willing to look into fixing this. If he doesn't, I suggest we put a warning into the PyLammps constructor that warns about potential problems when running with MPI. Perhaps we should do that anyway.

Besides, for any serious python programming, I suggest to switch to the regular lammps python module. The example script is easily translated into:
```python
from mpi4py import MPI
from lammps import lammps

lmp = lammps()
lmp.file("in.melt")
print("Potential energy: ", lmp.get_thermo("pe"))

lmp.close()
```

**Comment by rbberger** [comment]
There's nothing new here. Evaluations have always only been valid on rank 0. We even pointed that out in the docs: https://docs.lammps.org/Howto_pylammps.html#using-pylammps-and-mpi4py-experimental. I agree with @akohlmey that it should throw an exception if the MPI rank is not zero. But this won't be fixed in PyLammps. Use the actual python module of lammps instead.
