### ISSUE TITLE
USER-COLVARS scriptedFunction ?

### ISSUE THREAD

**Issue by WernerUlrich** [lammps/lammps#425]
Hello,

I try to use the USER-COLVARS package with the user defined collective variables. These are called scriptedFunction(s) in the manual but are not explained quite well. Regarding the fact that I was not able to run anything with it ( I am also very weak in tcl ), I got the question:

Is the scriptedFunction feature available in LAMMPS? 
if {yes} {
I do have some trouble in using it. Could someone please upload a minimum example? There are no examples in the directory for this purpose.
} elseif {no}{
Could I please get some quick instructions like a to-do list on how to implement them into the colvars package itself? (only if thats as easy as it sounds)
}

I already looked at the PLUMED documentation and realized that there is also the option to define own variables, but PLUMED is no more a standard package in LAMMPS :( , but I like LAMMPS.

It would be nice of someone could help me out.
Thank you.

**Comment by giacomofiorin** [comment]
Hi Werner, the `scriptedFunction` feature is available so far for Tcl, i.e. not for LAMMPS.  In NAMD and VMD, you can see for example this script: https://github.com/colvars/colvars/blob/master/examples/10_pathCV.namd.  It is not very difficult, actually.

In LAMMPS, it is possible to add callbacks to the Python interpreter, if available: are you able to write the functions that you seek to implement in Python?

**Comment by WernerUlrich** [comment]
Hi Giacomo,

thank you for the quick answer. This example for NAMD was the point when I started to think that I had to do this in TCL for LAMMPS, too.

But Python would be great. So I think I first need to remember a little python programming and then define a script *.py with the functions myCV and myCV_gradient or something like that.(?)

How would it look in the easiest case like the "Id" example [ Id(x)=x, Id_gradient(x)=1 ]  in the colvar.config script? Just a "scriptedFunction Id" ? The keyword source or things like that were never recognized by the colvar-for-lammps package. Did you mean using the lammps-python interface or is there some kind of colvars-python interfacing?

Thanks again.

**Comment by giacomofiorin** [comment]
Hi Werner, the Python callbacks (calls to Python functions from the C++ code) are not available yet.  The opposite (calling C++ function from Python) is by far the more common use.

@rbberger, can you confirm that for LAMMPS?

I can add calls to Python functions from inside Colvars relatively soon (within a few weeks).

@WernerUlrich in the meantime, can you brush up on your Python?  You could write a script where you implement the function that computes the variable that you want (and also the function of its gradient).  Take particular note of what input you are using (Cartesian coordinates or functions of them).  The Python functions should accept as a single positional argument a list of `float`s.  You should test these two functions yourself by giving them random numbers in the range that you expect for your system.

**Comment by WernerUlrich** [comment]
Hi again,
this sounds great. I think the lammps users working with the python-lammps interface will like it because during work one can rely on one scripting language. Can't wait to test it :)
Thank you.

**Comment by giacomofiorin** [comment]
@WernerUlrich I'd like to emphasize that while the availability of the Python interpreter would make callbacks possible, these would be distinct actions from a Python script that controls the LAMMPS workflow.  You should make the two pieces of Python code distinct.

**Comment by giacomofiorin** [comment]
One more correction: python-style variables do actually implement callbacks for LAMMPS.

**Comment by akohlmey** [comment]
Can we consider this issue closed and #438 as its successor?
@rbberger is planning to do some refactoring of the Python class in LAMMPS, that would then make access to the python interpreter more straightforward.

**Comment by giacomofiorin** [comment]
@akohlmey I agree.
