### ISSUE TITLE
[Feature Request] Box and sub-box volume calculation

### ISSUE THREAD

**Issue by abkein** [lammps/lammps#4260]
**Summary**

I've written code for simulation box volume calculation. I would like to know if this addition would be useful for inclusion in LAMMPS.

**Detailed Description**

One function calculates volume of entire simulation box and other calculates volume of sub-box owned by this proc.
These functions are members of `Domain` class, both suitable for orthogonal, triclinic boxes and 2D.

```c++
/* ----------------------------------------------------------------------
   calculate simulation box volume
------------------------------------------------------------------------- */

double Domain::volume() {
  if (dimension == 2){
    if (triclinic) {
      // Calculate area for 2D box (projection onto xy plane)
      return fabs(avec[0] * (bvec[1] * cvec[2] - bvec[2] * cvec[1]) -
                avec[1] * (bvec[0] * cvec[2] - bvec[2] * cvec[0]) +
                avec[2] * (bvec[0] * cvec[1] - bvec[1] * cvec[0]));
    } else {
      // Calculate area for 2D orthogonal box
      return xprd * yprd;
    }
  } else {
    if (triclinic) {
      // Calculate volume using the triple product of the edge vectors
      double a = avec[0];
      double b = avec[1];
      double c = avec[2];
      double d = bvec[0];
      double e = bvec[1];
      double f = bvec[2];
      double g = cvec[0];
      double h = cvec[1];
      double i = cvec[2];

      return fabs(a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g));
    } else {
      // Calculate volume for orthogonal box
      return xprd * yprd * zprd;
    }
  }
}

/* ----------------------------------------------------------------------
   calculate sub-box volume owned by this proc
------------------------------------------------------------------------- */

double Domain::subvolume() {
  if (dimension == 2) {
    if (triclinic) {
      // WARNING: there could be bugs.
      // Calculate the area of the parallelogram formed by the subdomain's
      // projection onto the xy plane.
      // The area is given by the magnitude of the cross product of the
      // two vectors defining the parallelogram.
      // The vectors are:
      //   (xhi - xlo, 0, 0)
      //   (xy, yhi - ylo, 0)
      // The cross product is:
      //   (0, 0, (xhi - xlo)*(yhi - ylo) - xy*0)
      // The magnitude of the cross product is:
      //   |(xhi - xlo)*(yhi - ylo)|

      double xlo = sublo_lamda[0];
      double xhi = subhi_lamda[0];
      double ylo = sublo_lamda[1];
      double yhi = subhi_lamda[1];

      return fabs((xhi - xlo) * (yhi - ylo));
    } else {
      // Calculate subarea for orthogonal box
      return (subhi[0] - sublo[0]) * (subhi[1] - sublo[1])
    }
  } else {
    if (triclinic) {
      // WARNING: there could be bugs.
      // Calculate subvolume using the triple product of the edge vectors
      // of the sub-box, which are defined by the lamda coordinates.
      double a = (subhi_lamda[0] - sublo_lamda[0]) * prd[0];
      double b = (subhi_lamda[1] - sublo_lamda[1]) * prd[1];
      double c = (subhi_lamda[2] - sublo_lamda[2]) * prd[2];
      double d = yz * (subhi_lamda[1] - sublo_lamda[1]) * prd[1];
      double e = xz * (subhi_lamda[2] - sublo_lamda[2]) * prd[2];
      double f = xy * (subhi_lamda[0] - sublo_lamda[0]) * prd[0];

      return fabs(a * (e * c - f * b) - b * (d * c - f * a) + c * (d * b - e * a));
    } else {
      // Calculate subvolume for orthogonal box
      return (subhi[0] - sublo[0]) * (subhi[1] - sublo[1]) * (subhi[2] - sublo[2]);
    }
  }
}
```

**Further Information, Files, and Links**

**Comment by akohlmey** [comment]
@Architect0rr Thanks for your post.

Please note that LAMMPS had `Thermo::compute_vol()` for a very long time as it computes the output generated for the thermo keyword "vol". Your calculation for the general triclinic case is overkill, since LAMMPS internally requires the box to be aligned with the x-axis and the y axis in the xy-plain, so that the same computation can be done for triclinic and orthogonal.

Where would you need the sub-box volumes? They are only relevant for domain decomposition, i.e. an internal property.

**Comment by abkein** [comment]
>Please note that LAMMPS had Thermo::compute_vol() 

Oh, I didn't notice. Thank you.

>Where would you need the sub-box volumes? 

As an example, it could be used for local atom concentration calculation (`atom->nlocal/domain->subvolume()`). I don't know why someone would need this, but I thought since computes can calculate their local properties, these properties might require volume for their calculation.

>LAMMPS internally requires the box to be aligned with the x-axis and the y axis in the xy-plain

Abstract question: why not carry out all calculations in a general triclinic box, since orthogonal and restricted triclinic boxes are special cases of general? Computational efficiency?

**Comment by akohlmey** [comment]
> > Where would you need the sub-box volumes?
> 
> As an example, it could be used for local atom concentration calculation (`atom->nlocal/domain->subvolume()`). I don't know why someone would need this, but I thought since computes can calculate their local properties, these properties might require volume for their calculation.

You would not want to make this kind of property depend on the specifics of the domain decomposition and thus on the number of processors. BTW: there is already compute composition/atom that does something like that.

In general, we don't like to add APIs "on spec", but rather only add them when there is a "consumer" for it.
Anything that is in the LAMMPS distribution needs to be maintained and kept working, so we want to only spend that effort on features that are used.

> 
> > LAMMPS internally requires the box to be aligned with the x-axis and the y axis in the xy-plain
> 
> Abstract question: why not carry out all calculations in a general triclinic box, since orthogonal and restricted triclinic boxes are special cases of general? Computational efficiency?

There are three reasons:
- History: support for deformed cells was added many years after LAMMPS was conceived
- Simplicity: many things are much easier in orthogonal cells. The support for triclinic is done by converting coordinates into fractional coordinates (so they are orthogonal) and back. General triclinic by rotating the system to the constraints required and then rotating back on output
- Efficiency: many operations in a general cell require lots of additional linear algebra and most simulations don't need non-orthogonal boxes

**Comment by abkein** [comment]
Thank you!
