### ISSUE TITLE
[BUG] KE tensor outputted by "compute temp" is twice as much as the actual value

### ISSUE THREAD

**Issue by zbaibg** [lammps/lammps#4265]
**Summary**

Follow my steps and you can see the KE calcualted by adding x,y,z components of the tensor generated by 'compute temp' is twice as much as the value outputted by 'thermo' in the log file. 

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Update 3)
CentOS Stream release 9
 AMD EPYC 9124 16-Core Processor

**Expected Behavior**

Two values should be the same.

**Actual Behavior**

c_thermo_temp[1]+c_thermo_temp[2]+c_thermo_temp[3] is twice as much as the Kinectic Energy outputted by 'thermo' in the log file. This is not consistent with the description for the output of "compute temp" at https://docs.lammps.org/compute_temp.html

**Steps to Reproduce**

variable ke equal c_thermo_temp[1]+c_thermo_temp[2]+c_thermo_temp[3]
fix PRINT_DEBUG all print 100 "KE = ${ke}"
thermo_style multi
thermo 100

**Further Information, Files, and Links**

By checking compute_temp.cpp, you can find there should be a factor of 1/2 at the 136th line.

**Comment by sjplimp** [comment]
@zbaibg Hi - thanks for calling this to our attention.  You are correct that the various compute temp doc pages incorrectly state that the vector outputs are the KE tensor and include the 1/2 factor.  The code drops the 1/2 factor and uses the output in that form for the pressure tensor computation.

So we changed the doc pages to clarify what the code actually does, and now state that the output tensor components are twice that the of the traditional KE tensor.

You can check out the new doc pages in PR #4290 to see if they are now clear.  There are many variants of compute temp.
