### ISSUE TITLE
[BUG] Examples in package "RHEO" do not run

### ISSUE THREAD

**Issue by souvi-lrcs** [lammps/lammps#4271]
**Summary**

Trying to run any of the example scripts fails with "ERROR: Must have only one fix rheo defined (../pair_rheo.cpp:466)"

**LAMMPS Version and Platform**

Running LAMMPS 27 Jun 2024 Develop branch on Ubuntu 22.04

**Actual Behavior**

Trying to run any of the provided example scripts results in the same error

**Comment by akohlmey** [comment]
Thanks for the report. This is due to a change by me in combination with an insufficient search by fix id that just worked by accident since the inputs define fix rheo first.

Please try the patch in commit fe98a875bb1970944683e8c1c246cfe84d9c71f9

**Comment by souvi-lrcs** [comment]
@akohlmey thank you that worked
