### ISSUE TITLE
Facing issue while installing lmp executable for m3gnet potential. Symbol lookup error

### ISSUE THREAD

**Issue by mm21d013** [lammps/lammps#4284]
I tried installing the lmp executable following the commands in the matgl repository in the link given below:

https://github.com/materialsvirtuallab/matgl/blob/v1.1.3/examples/Using%20LAMMPS%20with%20MatGL.ipynb

However, I face a symbol lookup error for lmp executable that has been installed. The error pops out as follows:

lmp: symbol lookup error: lmp: undefined symbol: _ZTIN3fmt6v9_lmp12format_errorE

Please assist me in removing it.

**Comment by akohlmey** [comment]
This is referring to a modified LAMMPS version that is not maintained by the LAMMPS developers. You have to contact the people that modified it. We know nothing about what modifications they did.
