### ISSUE TITLE
Problems doing 'brew install lammps'.

### ISSUE THREAD

**Issue by jcminerlanl** [lammps/lammps#430]
Hello,

For a little over a week now, many of us have been unable to acquire lammps through Homebrew.

The common thread seems to be that the mscg.h file cannot be found.

The standard method:
$ brew install lammps --HEAD 

Produces the error:
""""""
....
/usr/local/bin/mpicxx -O  -DLAMMPS_GZIP -I../../lib/voronoi/includelink -I../../lib/reax -DLMP_PYTHON -I../../lib/poems -I../../lib/mscg/includelink -DLMP_MPIIO -I../../lib/meam  -DOMPI_SKIP_MPICXX -DFFT_FFTW3 -I/usr/local/opt/fftw/include -DLAMMPS_JPEG -I/usr/local/opt/jpeg/include -I/usr/local/opt/voro++/include/voro++  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7     -c ../fix_mscg.cpp
In file included from ../fix_mscg.cpp:21:
../fix_mscg.h:24:10: fatal error: 'mscg.h' file not found
#include "mscg.h"
""""""

This issue was discussed in homebrew-science (https://github.com/Homebrew/homebrew-science/issues/5155), but we all wanted this issue brought back to lammps itself so that it can be addressed, since the error appears to be an internal one.

Can this matter please be addressed as soon as possible?
The issue seems to affect both the El Capitan OSX and Sierra OSX.

**Comment by jcminerlanl** [comment]
Follow up:
This issue does not present itself if only the following command is attempted:
brew install lammps

The inclusion of --HEAD seems cause the trouble mentioned above.

**Comment by akohlmey** [comment]
No, this is **not** an internal LAMMPS problem. when you install the MSCG package, you need to install an external library (similar to libvoro++ for the VORONOI package). This is documented in the LAMMPS manual and the corresponding README files.
