### ISSUE TITLE
[Feature Request] expose `Atom::find_custom` through the C-API

### ISSUE THREAD

**Issue by Joroks** [lammps/lammps#4303]
**Summary**

Currently, it's not possible to determine the number of per-atom entries of a custom property through the C-API.
Exposing `Atom::find_custom` would fix this.

**Detailed Description**

I'm currently in the process of writing/improving the [csmix-mit/LAMMPS.jl](https://github.com/cesmix-mit/LAMMPS.jl) julia wrapper library for lammps. Wrapping the `lammps_extract_atom` function for custom properties in a safe manner requires me to know how many columns said property has.

As an alternative, I could imagine exposing a `lammps_extract_atom_cols` method, which returns the number of columns for any per-atom property (i.e build-in and custom ones). Currently, I have to hardcode the sizes of the build-in properties, following the table listed [here](https://docs.lammps.org/Classes_atom.html#_CPPv4N9LAMMPS_NS4Atom7extractEPKc). Providing a general method to query the sizes of per atom data could be an elegant solution to both of these problems.

Unfortunately, I don't have much experience with C++/C development. I'm not sure wheter I would be able to implement this request myself.

**Comment by akohlmey** [comment]
@sjplimp do you have any suggestion what should be done here?

For lammps_extract_fix() and lammps_extract_compute() we have an additional parameter "type" where we can flag whether we want the (scalar, vector, array) data or the size of rows/columns. So we can "hide" the query of the number of columns in the extract function. For extract_atom() we don't have that option (and I am hesitant to change that API).

Adding a lammps_extract_atom_dim() function seems to me the more straightforward option, we can then use the LMP_SIZE_ROWS and LMP_SIZE_COLS constants as flag argument. This would also allow to cleanly report that lammps_extract_atom() returns an array of size atom->ntypes for the property "mass" and not atom->nlocal. Perhaps it would also possible to indicate whether ghost atoms are included or not.

**Comment by akohlmey** [comment]
@Joroks Please have a look at https://github.com/lammps/lammps/pull/4304 which should implement what you need. I've used the new API to update both the Python and Fortran wrappers to use the information for dimensioning of arrays. Some more tests need to be added to check for more details, but the core functionality is confirmed.

**Comment by Joroks** [comment]
Thanks! This is exactly what I need!

One potential issue I could see is that it's ambiguous whether ghost atoms are usually included for a given property in the rare scenario where there are no ghost atoms. Directly returning a flag that indicates the presence of ghost atoms could solve this, however, this would then require the caller to also use `lammps_extract_setting` to retrive the size of the array. Overall I think your approach is better though.

On a related note, the [API documentation](https://docs.lammps.org/Library_objects.html#_CPPv422lammps_extract_computePvPKcii) states that `LMP_SIZE_VECTOR` and `LMP_SIZE_ROWS` behave the same. However, this isn't the case in my experience.

**Comment by akohlmey** [comment]
> One potential issue I could see is that it's ambiguous whether ghost atoms are usually included for a given property in the rare scenario where there are no ghost atoms.

It is not ambiguous since `atom->nghost` will be zero for that case and thus nall == nlocal

> On a related note, the API documentation states that LMP_SIZE_VECTOR and LMP_SIZE_ROWS behave the same. However, this isn't the case in my experience.

This only applies to local data, not for global data.
Please provide an example input deck where you see this with local data.

**Comment by Joroks** [comment]
> It is not ambiguous since atom->nghost will be zero for that case and thus nall == nlocal

It's ambiguoos in the sense that I can't know wheter a property usually includes ghosts, when a processor currently happens to have no ghost atoms. 

I'll demonstrate this with a hypothetical:
Let's say I'd want to write a function `extract_ghosts` which only returns the ghost data of the property. If the property usually has ghost data but there are no ghosts on that processor then I'd want to return an empty array. If the property doesn't support ghost data, I'd want this function to error - even when there are currently no ghosts. With the current solution this would not be possible.

I'll admit that this is very much a nitpick and probably a non-issue. I'ts just a small detail that I've noticed.

> This only applies to local data, not for global data.
> Please provide an example input deck where you see this with local data

I'll take a closer look at this and will open a seperate issue once I've confirmed whether this is an error in the documentation. It could also be that I missinterpreted something and that the error is on my part here.

**Comment by akohlmey** [comment]
> Let's say I'd want to write a function `extract_ghosts` which only returns the ghost data of the property.

I cannot imagine a real life use case where you would want to *only* access the ghost atoms. Besides, I don't see why you would want to throw an error instead of just returning an empty array.

I think the API as such is consistent. You have the property array and you get its (useful) dimensions.
