### ISSUE TITLE
[Feature Request] allow `lammps_extract_atom_datatype` to be called without handle

### ISSUE THREAD

**Issue by Joroks** [lammps/lammps#4311]
**Summary**

All per-atom properties are compile time constants. Therefore, it should not require a lammps handle to call `lammps_extract_atom_datatype`. In this case, julias typesystem can ensure type stability due to constant propagation.

**Detailed Description**

Currently, for the julia wraper, users have to provide the return type as a parameter of the `lammps_extract_atom` wrapper in order to ensure type stability. This complicates the API and could be avoided with some slight modifications to the `lammps_extract_atom_datatype` function.

Julias compiler can optimize function calls with constant parameters if they are recogniced as foldable, i.e. if they are consistent, effect free and terminate globally. C function calls can be [marked as such](https://docs.julialang.org/en/v1/base/base/#Base.@assume_effects) as well, if these conditions are indeed fullfilled. This helps julia determine the return type of `lammps_extract_atom` (or to be exact it's wrapper) for any given per atom property at compile time, which improves performance.

A potential blocker would the handling of custom properties. Currently, lammps verifies wheter a custom property exists and returns -1 if it doesn't. This, however, is inconsistent with how `Atom::extract_datatype` handles build-in properties. Here, their datatype is returned, without verifying if they are currently enabled. If custom properties were to be handled consistently with build-in properties (i.e, it's not verified that they are currently in use), a lammps handle would no longer be needed. Thus I could mark this function as foldable.

I've already verified that this optimisation works in the case of `lammps_extract_global_datatype` where the handle is already not needed.

**Comment by akohlmey** [comment]
> This complicates the API and could be avoided with some slight modifications to the `lammps_extract_atom_datatype` function.

Sorry, but no.

We need the handle to access the atom class instance and for internal consistency and convenience within the LAMMPS C/C++ environment. While this may be inconvenient for your work, the internal LAMMPS environment and maintainability is a larger concern for us.

> A potential blocker would the handling of custom properties. 

Indeed this prevents us from making Atom::extract_datatype() static - a prerequisite for omitting the handle - since we need to call Atom::find_custom() to validate the custom property data.
