### ISSUE TITLE
Some PyLammps' functions are not working when `-screen none` is used as part of `cmdargs`

### ISSUE THREAD

**Issue by doronbehar** [lammps/lammps#4328]
**Summary**

So I'm playing with the `PyLammps` interface, and I want to reduce as much as possible the amount of printings done while I use it, so I use `-screen none`, as explained [here](https://matsci.org/t/running-lammps-without-it-printing-anything-besides-warnings-and-errors/52662). With it, I got this error first when I wanted to access the `.atoms` attribute:

```
  File "/nix/store/x91lgzmi4cany6qldkz0n9hvi7mrd5xg-python3-3.12.5-env/lib/python3.12/site-packages/lammps/pylammps.py", line 649, in atoms
    return AtomList(self)
           ^^^^^^^^^^^^^^
  File "/nix/store/x91lgzmi4cany6qldkz0n9hvi7mrd5xg-python3-3.12.5-env/lib/python3.12/site-packages/lammps/pylammps.py", line 120, in __init__
    self.natoms = self._pylmp.system.natoms
                  ^^^^^^^^^^^^^^^^^^
  File "/nix/store/x91lgzmi4cany6qldkz0n9hvi7mrd5xg-python3-3.12.5-env/lib/python3.12/site-packages/lammps/pylammps.py", line 659, in system
    output = self.lmp_info("system")
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/x91lgzmi4cany6qldkz0n9hvi7mrd5xg-python3-3.12.5-env/lib/python3.12/site-packages/lammps/pylammps.py", line 863, in lmp_info
    indices = [index for index, line in enumerate(output) if line.startswith("Info-Info-Info-Info")]
                                        ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

And after reading the implementation I realized that the `lmp_info("system")` simply returns nothing because `-screen` printing is disabled.

I think at least the documentation could be improved, or the `system` `@property` could at least be improved to not rely upon the output, but rather to get that info from the `PyLammps.lmp` interface.

**LAMMPS Version and Platform**

[Stable release 29 August 2024](https://github.com/lammps/lammps/releases/tag/stable_29Aug2024), on NixOS.

**Comment by akohlmey** [comment]
Using PyLammps is a *bad* idea for any production calculation. It was not designed for it and has significant additional overhead. Turning off the screen output will break it.

**Comment by doronbehar** [comment]
Wouldn't you at least agree that it'd be nice to document this?

**Comment by akohlmey** [comment]
> Wouldn't you at least agree that it'd be nice to document this?

The PyLammps module will be deprecated soon, so it is not worth the effort.
