### ISSUE TITLE
Failure to correctly parse an XYZ file

### ISSUE THREAD

**Issue by HemanthHaridas** [lammps/lammps#4334]
Summary
The new version of LAMMPS is unable to correctly parse the xyz files

LAMMPS Version
LAMMPS (29 Aug 2024 - Development - patch_29Aug2024-269-g805c2ae131

Platform
Platform Independent : tested on both MacOS Sonoma (Apple M3) and Rocky Linux 8.8 (Computing Cluster)

Description
I am trying to read a trajectory dumped into an xyz file and rerun the calculation to calculate the components of the forces acting on the atoms. When I tried to do the calculation using the version **LAMMPS (29 Aug 2024 - Development - patch_29Aug2024-269-g805c2ae131)**, it failed with the following error message:
```
Exception: stoi: no conversion
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
  Proc: [[1845,0],0]
  Errorcode: 1

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

I was able to get the expected behavior by replacing the command ```mytype = std::stoi(line);``` at line 185 in src/reader_xyz.cpp to be ```mytype = atoi(line);```.

The expected behavior is a successful completion of the calculation with the following data
```
Per MPI rank memory allocation (min/avg/max) = 11.71 | 11.71 | 11.71 Mbytes
    PotEng    
-145.97803    
-148.7211     
-150.78172    
-152.24371    
-153.03339    
-153.22808    
-152.92975    
-152.19228    
-151.09856    
-149.9398     
Loop time of 0.000468583 on 1 procs for 10 steps with 3 atoms

Total wall time: 0:00:00
```

The xyz file which I used is copied below: 
```
3       
 i =        1, time =       85.000, E =       -76.4214103553
  O         0.0000000000         0.0000000000         0.2044070700
  H         0.6542503700         0.0000000000        -0.5095819300
  H        -0.6542503700         0.0000000000        -0.5095819300
3       
 i =        2, time =       90.000, E =       -76.4261078367
  O         0.0000000000         0.0000000000         0.1844585500
  H         0.6840662200         0.0000000000        -0.4996076700
  H        -0.6840662200         0.0000000000        -0.4996076700
3       
 i =        3, time =       95.000, E =       -76.4293408482
  O         0.0000000000         0.0000000000         0.1645120900
  H         0.7138756700         0.0000000000        -0.4896344400
  H        -0.7138756700         0.0000000000        -0.4896344400
3       
 i =        4, time =      100.000, E =       -76.4312805439
  O         0.0000000000         0.0000000000         0.1398309900
  H         0.7354607900         0.0000000000        -0.4772938900
  H        -0.7354607900         0.0000000000        -0.4772938900
3       
 i =        5, time =      105.000, E =       -76.4319496950
  O         0.0000000000         0.0000000000         0.1176405500
  H         0.7608740900         0.0000000000        -0.4661986700
  H        -0.7608740900         0.0000000000        -0.4661986700
3       
 i =        6, time =      110.000, E =       -76.4314366521
  O         0.0000000000         0.0000000000         0.0954539000
  H         0.7862800900         0.0000000000        -0.4551053400
  H        -0.7862800900         0.0000000000        -0.4551053400
3       
 i =        7, time =      115.000, E =       -76.4295434217
  O         0.0000000000         0.0000000000         0.0753198300
  H         0.8167986700         0.0000000000        -0.4450383100
  H        -0.8167986700         0.0000000000        -0.4450383100
3       
 i =        8, time =      120.000, E =       -76.4270152371
  O         0.0000000000         0.0000000000         0.0508873100
  H         0.8378091900         0.0000000000        -0.4328220500
  H        -0.8378091900         0.0000000000        -0.4328220500
3       
 i =        9, time =      125.000, E =       -76.4235815793
  O         0.0000000000         0.0000000000         0.0264605500
  H         0.8588119800         0.0000000000        -0.4206086700
  H        -0.8588119800         0.0000000000        -0.4206086700
3       
 i =       10, time =      130.000, E =       -76.4187707203
  O         0.0000000000         0.0000000000         0.0036618400
  H         0.8854050400         0.0000000000        -0.4092093100
  H        -0.8854050400         0.0000000000        -0.4092093100
```

**Comment by akohlmey** [comment]
> I was able to get the expected behavior by replacing the command `mytype = std::stoi(line);` at line 185 in src/reader_xyz.cpp to be `mytype = atoi(line);`.

Using atoi() is correcting **nothing**. In this case it is the equivalent of `mytype = 0`. Unlike std::stoi() the atoi() function will not flag an error if the conversion is incomplete or does not happen at all.

There are many versions of the .xyz file format. The "normal" version of dump xyz produces files with numeric atom types and not elements, so the current behavior is not a bug.

A correct fix would require to use the labelmap command to create a map of string to type translations. I will look into adding this feature.

**Comment by pavumox** [comment]
@akohlmey In which occurence(s) the type read by read_dump or rerun actually used? Is it only when using the "add" keyword?

**Comment by akohlmey** [comment]
> @akohlmey In which occurence(s) the type read by read_dump or rerun actually used? Is it only when using the "add" keyword?

That is irrelevant for this issue. If we parse the file, we ought to parse it correctly and not return bogus data.

**Comment by akohlmey** [comment]
@HemanthHaridas Pull request #4331 now contains the changes to use type labels for supporting .xyz files with strings instead of numbers to indicate the atom type.

Thus for the example file given above something like the following line would need to be added:
```
labelmap atom 1 O 2 H
```
Which would identify O atoms as atom type 1 and H atoms as atom type 2.
