### ISSUE TITLE
[BUG]  GRANULAR package fix_pour:  wrong insertion volume calculation (particularly in in SI units)

### ISSUE THREAD

**Issue by cgadal** [lammps/lammps#4337]
**Summary**
The fix_pour does not insert the proper number of particles every the proper number of time steps if the region is a box of width along the y direction smaller than one.

This is due to the line   `if (dy < 1.0) dy = 1.0;` in this portion of code leads to a wrong volume calculation, especially in SI units where lengths are typically much smaller than one.

https://github.com/lammps/lammps/blob/b95f7c2ab2b9cba44c3f690b9bfb16b36cc11b98/src/GRANULAR/fix_pour.cpp#L226-L232

**LAMMPS Version and Platform**

Develop branch, last commit, Ubuntu 20.04

**Expected Behavior**

It should compute the volume using the actual width of the box, even if smaller than one. 

**Steps to Reproduce**

```
atom_style      sphere
units           si

region          boxreg block 0 0.016 0 0.064 0 0.016
create_box      2 boxreg
change_box      all boundary p p f

region          insertbox block 0 0.016 0.0064 0.0576 0.0128 0.016 units box
neighbor        0.0008 bin
neigh_modify    delay 0 every 1 check yes
neigh_modify    exclude type 1 1  # do not compute fixed particles interaction forces

fix             bot_wall all wall/gran granular hooke 263000 0.3 damping coeff_restitution tangential mindlin 75142.8571428572 1 0.4 rolling none twisting none zplane 0 NULL

fix             1 all nve/sphere   # mandatory for granular style simulations
fix             grav all gravity 9.81 vector 0 0 -1 

comm_modify     vel yes   # mandatory for granular style simulations
thermo_style    custom step atoms ke
thermo_modify   lost warn
thermo          ${n_print}
thermo          500

timestep        1.31805410714104e-06
fix             ins all pour 25000 2 10 region insertbox diam range 0.00064 0.00096  dens 2650 

timer           loop
run             100000
```

**Comment by jtclemm** [comment]
I think the 1.0 value is supposed to be the maximum diameter of an atom (which by default is 1.0). Fixing this might just be as simple as replacing 1.0 with _2 * radius_max_. I'll check and make the change.

Thanks for spotting and reporting this issue!
