### ISSUE TITLE
Contradicting information in fix GCMC manual

### ISSUE THREAD

**Issue by marcelbalcik** [lammps/lammps#4340]
**Summary**

It is unclear whether min/max keyword of fix gcmc applies as atom or molecules

**Details**

At the beginning of the fix gcmc manual it reads:
"
  max value = Maximum number of molecules allowed in the system
  min value = Minimum number of molecules allowed in the system
"
where later it is written:

"The max and min keywords allow for the restriction of the number of atoms in the simulation. "

So it is unclear whether the algorithm uses atom number or molecule number in min/max keyword of fix gcmc.

**Comment by akohlmey** [comment]
It is the number of atoms.
Also, the number is computed for the fix group (not the entire system) and may be restricted further by use of the "region" keyword.

I suppose this is a sign of how fix gcmc has evolved over time and people have not always thoroughly updated the documentation.
