### ISSUE TITLE
[BUG] _Reading chemical potential values in semi grand canonical MC in fix_atom_swap.cpp_

### ISSUE THREAD

**Issue by DavideTisi** [lammps/lammps#4342]
**Summary**

in fix_atom_swap.cpp the values of chemical potential mu are stored in the variable mu starting from the element 1 instead of zero

**LAMMPS Version and Platform**
Version: LAMMPS (27 Jun 2024)
I tested on my workstation and on the local cluster 

**Expected Behavior**

I am running a semi-grand canonical simulation using fix atom/swap to swap from 3 atom species (out of 5 in total).
 following the documentation (https://docs.lammps.org/fix_atom_swap.html) my command look like:
 
`fix SGMC all atom/swap 50 200 34995 300 semi-grand yes types 3 4 5 mu -1.25 0.1 0.0`
for what I get from the documentation the values of mu thata are absolutes should be associated to the corresponding atomic type, in my case mu_3= -1.25 mu_4=0.1 mu_5=0.0. 
What I aspect from a simulation that reducing the first value of mu to a very low number I favour the presence of type 3.

**Actual Behavior**
What I saw it happening was that decrising the fist values after mu in the input from -1.25 to even -1000 I was favouring the type 4 instead of three. 

What I think is happening is that there is an error in the reading of the inputs. From lines 178-187 of fic_atom_swap.cpp:

https://github.com/lammps/lammps/blob/b95f7c2ab2b9cba44c3f690b9bfb16b36cc11b98/src/MC/fix_atom_swap.cpp#L178-L186

we can see that the index `nmutypes`, inizialized to zero in line 150 outside the loop, is incremented before its use to store the input values values inside mu (line 185), thus the index starts from 1.  

I tryied to add print statement in lines 399 inside `FixAtomSwap::attempt_semi_grand()` to look at the values of mu usid in the actual MC move, and indeed when the index is relative to species 3 the mu is zero (the vector is always initialized with zeros), the mu relative with species 4 is equal to  -1.25 (or what ever number i put as first in the input) and the mu relative to species 5 is equal to 0.1 ( or what ever number i put as second in the input)

Maybe I am not getting something obvoius, this is also why I open an issue and not a PR, but if I am correct I can make a quick PR. 

Also not that the result of my simulations are not really affected since I wanted to putt the last values to zero what it ends up is just that now the difference in chemical potential (which is the only think that matters in the simulations) are refered to the mu of type 3 instead of 5. 
This also tells that if you have only two species (and you set one chemical potential to zero) this never affect the  results since the difference just change the sign flipping only what I am favouring.

**Comment by akohlmey** [comment]
> Maybe I am not getting something obvoius, this is also why I open an issue and not a PR, but if I am correct I can make a quick PR.

The code is correct. The "mu" array is indexed by atom types and atom types start from 1 instead of 0. The `nmutypes++'` statement is thus required and placed correctly *before* the assignment.
