### ISSUE TITLE
[BUG] Examples using 'neb' fail with 'stable_29Aug2024' with high number of tasks, worked with 'stable_2Aug2023'

### ISSUE THREAD

**Issue by cdm-work** [lammps/lammps#4355]
**Summary**

I was trying to update our copy of the 'lammps' code base from the 'stable_2Aug2023_update1' to 'stable_29Aug2024' (which was the stable tag when I started the effort). I found that some of the tests using the 'neb' command in the input file were failing when run using the new version of 'lammps'. I originally hit the issue using GPU-enabled version of 'lmp', but I was able to trigger the issue with a non-GPU version with 128 tasks.

**LAMMPS Version and Platform**

The issue is occurring with the 'stable_29Aug2024' tagged release; I have also recreated the issue with 'stable_29Aug2024_update1'. The version which I have that works is 'stable_2Aug2023_update1'. The tests are being run on a Cray EX system, using Slurm 23.11.6 as the workload manager. The Cray programming environment was used to build lammps, CPE 24.07, including its MPICH and FFTW libraries. The filesystem shared between the nodes is Lustre.

With a default CPE environment loaded, including 'cray-fftw', these are the commands used to build LAMMPS; assume to be started at the top of the code directory.
```
> mkdir build
> cd build
> CMAKE_COMMON_OPTS=(
    -C ../cmake/presets/most.cmake
    -C ../cmake/presets/nolib.cmake
    -D BUILD_MPI=yes
    -D BUILD_OMP=no
    -D CMAKE_CXX_COMPILER=CC
    -D CMAKE_C_COMPILER=cc
    -D CMAKE_Fortran_COMPILER=ftn
    -D FFT=FFTW3
    -D FFTW3_INCLUDE_DIR=${FFTW_ROOT}/include
    -D FFTW3_LIBRARY=${FFTW_ROOT}/lib/libfftw3.so
    -D USE_SPGLIB=OFF
)
> wget -O ../potentials/C_10_10.mesocnt https://download.lammps.org/potentials/C_10_10.mesocnt
> cmake "${CMAKE_COMMON_OPTS[@]}" ../cmake
> cmake --build .
```

**Expected Behavior**

Using two different example files:
Copy 'examples/fire/in.neb.sivac.qm' to a separate directory and then 'cd' to that directory.
Run the test using this command: `srun -n 128 -N 8 <path_to>/lmp -partition 8x16 -in in.neb.sivac.qm`
The command produces good results, and exits normally.

Copy the contents of the 'examples/neb/' to a separate directory and then 'cd' to that directory.
Run the test using this command: `srun -n 128 -N 8 <path_to>/lmp -partition 8x16 -in in.neb.hop1`
The command produces good results, and exits normally.

**Actual Behavior**

When run with the 'stable_29Aug2024_update1' version, none of the expected output (except the headers line) appears. Instead we get multiple copies of this error, with either example file:
```
MPICH ERROR [Rank 31] [job id 1233976.0] [Thu Oct 10 14:37:00 2024] [nid001007] - Abort(269042437) (rank 31 in comm 0): Fatal error in PMPI_Comm_free: Invalid communicator, error stack:
PMPI_Comm_free(139): MPI_Comm_free(comm=0x4c844d0) failed
PMPI_Comm_free(86).: Null communicator

aborting job:
Fatal error in PMPI_Comm_free: Invalid communicator, error stack:
PMPI_Comm_free(139): MPI_Comm_free(comm=0x4c844d0) failed
PMPI_Comm_free(86).: Null communicator
```

**Steps to Reproduce**

The build and `srun` commands used have been provided in prior sections.

**Further Information, Files, and Links**

I will note that I originally noted this issue with GPU-enabled LAMMPS binaries, primarily against 'nvidia80' but also some issues with AMD 'gfx90a'. With one failing case against nodes with Nvidia A100 GPUs (4 per node), the error observed is similar to what I shared above, but with one additional line:
```
MPICH ERROR [Rank 1] [job id 29976.0] [Thu Oct 10 15:03:38 2024] [nid001008] - Abort(537477893) (rank 1 in comm 0): Fatal error in PMPI_Comm_free: Invalid communicator, error stack:
PMPI_Comm_free(139): MPI_Comm_free(comm=0x58b6370) failed
PMPI_Comm_free(86).: Null communicator

aborting job:
Fatal error in PMPI_Comm_free: Invalid communicator, error stack:
PMPI_Comm_free(139): MPI_Comm_free(comm=0x58b6370) failed
PMPI_Comm_free(86).: Null communicator
Cuda driver error 4 in call at file '/root/jenkins-azure/1065f584/workspace/6424_Migrate_to_stable_29Aug2024@14/x86_64-nvidia80-cr_24_8_cos-dynamic-cray-ofi/TMP/BUILD/cray-test-lammps-24.08.29/lib/gpu/geryon/nvd_timer.h' in line 98.
```

As above, the same test works fine using the 'stable_2Aug2023_update1' version of the binary. I'm making the assumption that the same issue affects both methods of running, but if another issue would be preferred for the GPU version, let me know and I'll create one.

**Comment by akohlmey** [comment]
@cdm-work I cannot reproduce the errors you are seeing with a CPU-only binary.

This seems to be specific to using GPUs. You can force extra output by using the command line flag -nb to completely turn off i/o buffering.

Unfortunately, I currently don't have the means to test this with a GPU enabled binary.

**Comment by cdm-work** [comment]
I repeated my tests using the CPU-only binaries with the addition of the `-nb` option, and I also ran both within separate `script` commands so that I captured the full output. I found that the test using the 'stable_29Aug2024' version of the binary did write out the expected output, but then was followed by the MPI errors I reported. I don't know if the `-nb` option allowed the output to be printed before the errors occurred, or I just didn't see it because the error logs overran my scroll log. There still seems to be some difference between the Lammps versions that triggers a difference in behavior, but maybe it's a latent bug in the Cray MPICH.

**Comment by akohlmey** [comment]
@cdm-work Please try the following change:
```
  diff --git a/src/REPLICA/neb.cpp b/src/REPLICA/neb.cpp
  index 4023f2c0b3..b14748565b 100644
  --- a/src/REPLICA/neb.cpp
  +++ b/src/REPLICA/neb.cpp
  @@ -95,7 +95,7 @@ NEB::NEB(LAMMPS *lmp, double etol_in, double ftol_in, int n1steps_in, int n2step
   
   NEB::~NEB()
   {
  -  MPI_Comm_free(&roots);
  +  if (roots != MPI_COMM_NULL) MPI_Comm_free(&roots);
     memory->destroy(all);
     delete[] rdist;
     if (fp) {
```

**Comment by akohlmey** [comment]
@cdm-work some further explanations.
To trigger this issue, two conditions must be met: 1. you must use more than one MPI rank per replica and you must have an MPI implementation that errors out when using MPI_Comm_free() on a NULL communicator.

The NULL communicator would show after some bugfix for NEB where it would show invalid output. However, that change was missing the check for a NULL communicator in the destructor.

The -nb flag would force all the output to files (as it is supposed to do) and then you get the crash when LAMMPS shuts down. Without the flag LAMMPS aborts in the same flag, but I/O buffers are not flushed to disk during an MPI abort.

**Comment by cdm-work** [comment]
That change appears to have fixed the issue. Adding that change to the code and rebuilding, I cannot replicate the issue; the tests are working as expected. Also did builds for Nvidia A100 and AMD GFX90A, and the same tests are working as expected for both cases.

**Comment by akohlmey** [comment]
@cdm-work thanks for confirming.
