### ISSUE TITLE
[BUG] _A typo in SPH/pair_sph_taitwater.cpp

### ISSUE THREAD

**Issue by Jasmine969** [lammps/lammps#4364]
**Summary**

There is a typo in SPH/pair_sph_taitwater.cpp.

**LAMMPS Version and Platform**

Latest version.

**Expected Behavior**

Line 267: `error->all(FLERR,"All pair sph/taitwater coeffs are not set");`

**Actual Behavior**

Line 267: `error->all(FLERR,"All pair sph/taitwater coeffs are set");`

I checked the `init_one` function in other source files, and think the word "not" may be omitted.

**Comment by jtclemm** [comment]
Good catch, you are right. The error message was incorrect.
