### ISSUE TITLE
[BUG] Segmentation fault when computing PTM

### ISSUE THREAD

**Issue by aaronrfinney** [lammps/lammps#4365]
**Summary**

Both serial and mpi lammps are failing with a segmentation fault. The simulation runs when the following lines are commented out,

```
compute 1 all ptm/atom fcc-hcp-bcc-ico 0.22 
dump 3 all custom 1000 ptm.${run_no}.atom id c_1[*]
dump_modify 3 sort id
```

In addition, there are no errors with this input file and v7Aug2019.

**LAMMPS Version and Platform**

Latest and previous stable versions: 29Aug2024 and 2Aug2023 

Platform is Ubuntu 22.04.5 LTS with Intel® Xeon(R) Gold 6442Y × 96 processor.

**Expected Behavior**

Simulation runs.

**Actual Behavior**

Segmentation fault. 

Output from gdb:
```
Thread 1 "lmp_mpi" received signal SIGSEGV, Segmentation fault.
LAMMPS_NS::NStencil::memory_usage (this=<optimised out>) at ../nstencil.cpp:468
468	      for (int j = 0; j < n; j++) {
```

**Steps to Reproduce**

`lmp_mpi < in.txt`
[in.txt](https://github.com/user-attachments/files/17589474/in.txt)

**Further Information, Files, and Links**

Input file attached.

**Comment by jtclemm** [comment]
Thank you for reporting the issue. This appears to be a bug with the multi style and an occasional neighbor list (interesting that combination was never tested). Essentially, certain multi structures aren't generated for occasional neighbor lists until they are first built, but the memory usage method needs these structures to tally their contributions. I'll double check and put together a patch.

**Comment by jtclemm** [comment]
Could you please confirm whether or not the changes in https://github.com/lammps/lammps/pull/4370 fix your issue? Thanks.

**Comment by aaronrfinney** [comment]
Yes, this is working fine.

Thanks!

PS Apologies for the delay.
