### ISSUE TITLE
[BUG] "fix adapt/fep" does not adapt the pair coefficients derived from mixing rules

### ISSUE THREAD

**Issue by zbaibg** [lammps/lammps#4384]
**Summary**

"fix adapt/fep" does not adapt pair coefficients derived from mixing rules

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Update 3)
CentOS Stream release 9
AMD EPYC 9124 16-Core Processor

**Expected Behavior**

If some pair coefficients are derived from mixing rules ( but not explicitly specified by pair_coeff), they could be adapted by fix adapt/fep.

**Actual Behavior**

If some pair coefficients are derived from mixing rules ( but not explicitly specified by pair_coeff), they could NOT be adapted by fix adapt/fep. This behavior is not written in the [manual ](https://docs.lammps.org/fix_adapt_fep.html )

**Steps to Reproduce**

Here is some simplified scripts that could possibly reflect the problem I met in my simulation:

pair_style hybrid/overlay lj/cut/soft 1 0.5 12.0
pair_coeff 1 1 lj/cut/soft 0.886 2.933 1
pair_coeff 2 2 lj/cut/soft 0.886 2.933 1
variable timestep equal ramp(0,100)
fix ADAPT all adapt/fep 1  pair lj/cut/soft lambda 1 2 v_timestep

In this way, the energy between the particles of type1 and type2 will not be adapted during the simulation. (This energy is non-zero)

If you add "pair_coeff 1 2 lj/cut/soft 0.886 2.933 1" before the "fix adapt/fep", the energy between type 1 and type 2 will then be adapted during the simulation.

The [manual ](https://docs.lammps.org/fix_adapt_fep.html ) does say that pair_coeff need to be used before fix adapt/fep. But I think it just implies that the coefficients derived from mixing rules should also be adapted. Or the manual should be clearer to specify that coefficients derived from mixing rules should be explicitly specified using pair_coeff before "fix adapt/fep".

**Further Information, Files, and Links**

**Comment by agiliopadua** [comment]
Yes, both the `fix adapt` and `fix adapt/fep` commands work as you describe when changing pair parameters (e.g. sigma and epsilon in `lj/cut` and related pair styles, or the prefactor in the soft versions). Maybe the manual can be made more clear, in the sense that all pair coefficients be explicitly given, not obtained from mixing.
