### ISSUE TITLE
[BUG] _The latest version not compatible with pandas

### ISSUE THREAD

**Issue by Jasmine969** [lammps/lammps#4396]
**Summary**

The latest version (LAMMPS-64bit-latest-MSMPI.exe) is not compatible with pandas.

**LAMMPS Version and Platform**

LAMMPS version: LAMMPS-64bit-latest-MSMPI.exe, issued on 2024-11-19.
Platform: Windows 10.
Python version: 3.10.14 (using anaconda)

**Expected Behavior**

The lammps object is expected to be instantiated normally with Python lammps module.

**Actual Behavior**

Traceback (most recent call last):
  File "F:\xxx\test.py", line 4, in <module>
    lammps()
  File "E:\LAMMPS 64-bit 19Nov2024-MSMPI\Python\lammps\core.py", line 159, in __init__
    self.lib = CDLL(libpath,RTLD_GLOBAL)
  File "E:\anaconda3\envs\myenv\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

**Steps to Reproduce**

```python
from lammps import lammps
import pandas as pd
lammps()
```
Running the above code will induce the OSError. But if pandas is imported after lammps is instantiated, it will run normally:

```python
from lammps import lammps
lammps()
import pandas as pd
```

**Comment by akohlmey** [comment]
This is not something that can be fixed on the LAMMPS side, but it rather looks like an issue of your anaconda based python installation. Conda maintained python installations have been creating all kinds of problems if not *all* software is compiled and installed through it. There are people maintaining a conda version of LAMMPS, but I don't know if there is a Windows version for that. Or you can consider installing Python directly from Python.org and use pip to install python packages. This has been working fine for me.

**Comment by Jasmine969** [comment]
Yeah. I just switched from anaconda to Python.org-version. The bug is fixed now.
