### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by poppik** [lammps/lammps#441]
Creating a fix ave/histo with wrong compute name causes segmentation fault. For example, the following input
compute dihedral1 all dihedral/local phi
fix 1 all ave/histo 1 100 100 -180 180 72 c_dihedral_1  mode vector  file histo.dihedral_1 ave running

[Chinook:55975] *** Process received signal ***
[Chinook:55975] Signal: Segmentation fault (11)
[Chinook:55975] Signal code: Address not mapped (1)
[Chinook:55975] Failing at address: 0x129
[Chinook:55975] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f87c2ff48d0]
[Chinook:55975] [ 1] [Chinook:55976] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7fadbb68f8d0]
[Chinook:55976] [ 1] [Chinook:55978] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f13f1f0b8d0]
[Chinook:55978] [ 1] [Chinook:55977] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f11c9c7f8d0]
[Chinook:55977] [ 1] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS11FixAveHistoC1EPNS_6LAMMPSEiPPc+0x784)[0xb4f664]
[Chinook:55978] [ 2] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS11FixAveHistoC1EPNS_6LAMMPSEiPPc+0x784)[0xb4f664]
[Chinook:55976] [ 2] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS11FixAveHistoC1EPNS_6LAMMPSEiPPc+0x784)[0xb4f664]
[Chinook:55975] [ 2] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS11FixAveHistoC1EPNS_6LAMMPSEiPPc+0x784)[0xb4f664]
[Chinook:55977] [ 2] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify11fix_creatorINS_11FixAveHistoEEEPNS_3FixEPNS_6LAMMPSEiPPc+0x31)[0x136d501]
[Chinook:55976] [ 3] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify11fix_creatorINS_11FixAveHistoEEEPNS_3FixEPNS_6LAMMPSEiPPc+0x31)[0x136d501]
[Chinook:55978] [ 3] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify11fix_creatorINS_11FixAveHistoEEEPNS_3FixEPNS_6LAMMPSEiPPc+0x31)[0x136d501]
[Chinook:55975] [ 3] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify11fix_creatorINS_11FixAveHistoEEEPNS_3FixEPNS_6LAMMPSEiPPc+0x31)[0x136d501]
[Chinook:55977] [ 3] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify7add_fixEiPPci+0x951)[0x135ca31]
[Chinook:55978] [ 4] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify7add_fixEiPPci+0x951)[0x135ca31]
[Chinook:55976] [ 4] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input15execute_commandEv+0xd28)[0x89de58]
[Chinook:55978] [ 5] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify7add_fixEiPPci+0x951)[0x135ca31]
[Chinook:55977] [ 4] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input15execute_commandEv+0xd28)[0x89de58]
[Chinook:55976] [ 5] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS6Modify7add_fixEiPPci+0x951)[0x135ca31]
[Chinook:55975] [ 4] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input4fileEv+0x317)[0x89ee87]
[Chinook:55976] [ 6] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input15execute_commandEv+0xd28)[0x89de58]
[Chinook:55977] [ 5] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input4fileEv+0x317)[0x89ee87]
[Chinook:55978] [ 6] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input15execute_commandEv+0xd28)[0x89de58]
[Chinook:55975] [ 5] lmp_kokkos_cuda_openmpi(main+0x46)[0x7b6776]
[Chinook:55976] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fadb9da1b45]
[Chinook:55976] [ 8] lmp_kokkos_cuda_openmpi(main+0x46)[0x7b6776]
[Chinook:55978] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f13f061db45]
[Chinook:55978] [ 8] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input4fileEv+0x317)[0x89ee87]
[Chinook:55975] [ 6] lmp_kokkos_cuda_openmpi(_ZN9LAMMPS_NS5Input4fileEv+0x317)[0x89ee87]
[Chinook:55977] [ 6] lmp_kokkos_cuda_openmpi[0x7dc04f]

There should be an error message.

**Comment by akohlmey** [comment]
Thanks for reporting.
This issue is corrected in pull request #442 which should become available in the next patch.
