### ISSUE TITLE
run_style verlet/kk ignored/not recognised

### ISSUE THREAD

**Issue by Pakketeretet2** [lammps/lammps#448]
I am not sure where this exactly goes wrong, but in the April 11, 2017 version, if I compile kokkos_omp and try to run the melt example, I get "ERROR: KOKKOS package requires run_style verlet/kk (../verlet.cpp:102)",
even though I run LAMMPS like so:
$  ../../src/lmp_kokkos_omp -in in.melt -k on t 2 -sf kk
and verlet/kk is in the installed integrate styles if I run lmp -h.

Dropping a "run_style verlet/kk" in the script doesn't change much either, it leads to the same error.
For completeness, here is the modified script and the log file:

[in.melt.txt](https://github.com/lammps/lammps/files/914805/in.melt.txt)
[log.lammps.txt](https://github.com/lammps/lammps/files/914806/log.lammps.txt)

**Comment by stanmoore1** [comment]
I see this too. Looks like it was broken when an extra arg was added to verlet::setup() function in a recent commit, and not added to the corresponding virtual Kokkos function, so the Kokkos version is no longer getting called.

**Comment by stanmoore1** [comment]
I fixed this in the svn branch, should come through to master soon:

<pre>
$ svn diff
Index: verlet_kokkos.cpp
===================================================================
--- verlet_kokkos.cpp	(revision 16395)
+++ verlet_kokkos.cpp	(working copy)
@@ -64,14 +64,17 @@
    setup before run
 ------------------------------------------------------------------------- */
 
-void VerletKokkos::setup()
+void VerletKokkos::setup(int flag)
 {
   if (comm->me == 0 && screen) {
     fprintf(screen,"Setting up Verlet run ...\n");
-    fprintf(screen,"  Unit style    : %s\n", update->unit_style);
-    fprintf(screen,"  Current step  : " BIGINT_FORMAT "\n", update->ntimestep);
-    fprintf(screen,"  Time step     : %g\n", update->dt);
-    timer->print_timeout(screen);
+    if (flag) {
+      fprintf(screen,"  Unit style    : %s\n", update->unit_style);
+      fprintf(screen,"  Current step  : " BIGINT_FORMAT "\n",
+              update->ntimestep);
+      fprintf(screen,"  Time step     : %g\n", update->dt);
+      timer->print_timeout(screen);
+    }
   }
 
   update->setupflag = 1;
@@ -169,7 +172,7 @@
   if (force->newton) comm->reverse_comm();
 
   modify->setup(vflag);
-  output->setup();
+  output->setup(flag);
   lmp->kokkos->auto_sync = 1;
   update->setupflag = 1;
 }
Index: verlet_kokkos.h
===================================================================
--- verlet_kokkos.h	(revision 16395)
+++ verlet_kokkos.h	(working copy)
@@ -29,7 +29,7 @@
  public:
   VerletKokkos(class LAMMPS *, int, char **);
   ~VerletKokkos() {}
-  void setup();
+  void setup(int flag=1);
   void setup_minimal(int);
   void run(int);
<pre/>

**Comment by Pakketeretet2** [comment]
Thanks for the patch and quick fix! :)

**Comment by stanmoore1** [comment]
Fixed in 2f32fb7f8bda59f8044dda41bd86ab1a6f5db515. Closing #448.
