### ISSUE TITLE
Modify pair_meam_spline to handle multicomponent potentials (nelements > 1)

### ISSUE THREAD

**Issue by DallasTrinkle** [lammps/lammps#453]
Current implementation of pair_meam_spline is restricted to single element types. Incorporate new implementation of pair_meam_spline to allow multicomponent MEAM spline potentials, such as [Ti-O MEAM spline](https://www.ctcms.nist.gov/potentials/Ti-O.html).

**Comment by DallasTrinkle** [comment]
My previous student, Pinchao Zhang, wrote the code for this already, and we've used it with LAMMPS. I am happy to incorporate this into the official release (I've been handing out the code for our new implementation to different groups to use our potential parameters, but other new potentials that get developed would benefit too).

**Comment by akohlmey** [comment]
You are welcome to contribute your changes to LAMMPS as a pull request. Please see the detailed guidelines for contributions to LAMMPS in the manual http://lammps.sandia.gov/doc/Section_modify.html#mod-15 and let us know, if you have additional questions.

**Comment by stanmoore1** [comment]
Implemented in PR #466. Closed #453.
