### ISSUE TITLE
Error in molecule COM in GCMC package

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#459]
I have tried to do GCMC of water molecules with ReaxFF KOKKOS (11 april). Every time `run` is called with an active `fix gcmc`, the `init` function is called, which subtracts the COM of the molecule on [line 588](https://github.com/lammps/lammps/blob/master/src/MC/fix_gcmc.cpp#L588). The problem is that the `comflag` in `molecule.cpp` is then set to `1`, so that next time this happens, the COM is not recomputed. This results in subtracting the initial COM every time `init` is called.

Potential fix:
Manually set
```
onemols[imol]->com[0] = 0;
onemols[imol]->com[1] = 0;
onemols[imol]->com[2] = 0;
```
in `fix_gcmc.cpp` on [line 598](https://github.com/lammps/lammps/blob/master/src/MC/fix_gcmc.cpp#L598).

A more robust method would somehow mark the COM as dirty when any atom position is changed.

**Comment by athomps** [comment]
Molecular::comflag is already public, so a better solution would be checking if (!comflag) in FixGCMC::init()

**Comment by andeplane** [comment]
I'm not sure I agree. Since we are moving the COM to somewhere else, we should at least update it in case other classes are depending on this molecule? The COM value will be wrong unless we update it.

Or am I misunderstanding something maybe?

**Comment by athomps** [comment]
I see. So the correct behavior in FixGCMC::init() is:

1. call compute_com()
2. shift the positions of the template atoms by com
3. set com[0]=com[1]=com[2]=0
4. set comflag=1

The only thing missing was 3, which you added, so I think we are good. However, if some other part of LAMMPS is using the original values of com, then something bad might happen, but the only way to avoid that is to make a new copy of the molecular template.

**Comment by andeplane** [comment]
Yep. The only files using `compute_com` are `fix_gcmc.cpp` and `fix_rigid_small.cpp` it seems. I haven't checked the latter, but it seems like a small job. 

Maybe it should be noted somewhere near the `compute_com` function that the COM values should not be stored outside molecule?
