### ISSUE TITLE
fix gcmc doesn't reject molecule translation correctly when molecule changes processor (energy_full)

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#467]
I'm working with GCMC with water molecules in zeolites using ReaxFF. I've had problems where atoms suddenly are moved closer than what is allowed by the overlap_cutoff. I think the problem is because `atom->nlocal` can change if a molecule has moved, but this number is stored in a local variable in the `attempt_atomic_translation_full` and `attempt_molecule_rotation_full` (see [line 1692](https://github.com/lammps/lammps/blob/master/src/MC/fix_gcmc.cpp#L1692)). Example:

1. a molecule is moved or rotated so that it changes processor
2. the step is rejected
3. all atoms in molecule should be moved back, but some of them don't because `nlocal` on line [1744](https://github.com/lammps/lammps/blob/master/src/MC/fix_gcmc.cpp#L1744) doesn't include the new atoms.

Solution:
use `atom->nlocal` instead (see PR).

**Comment by andeplane** [comment]
It also looks like the rotation has a similar problem. If a rotated molecule is moved to another processor, the rejection step doesn't work since the original atom positions are stored locally in `atom_coord` on [line 1806](https://github.com/lammps/lammps/blob/master/src/MC/fix_gcmc.cpp#L1806). Similarly the `image_orig` will not be set to original value.

**Comment by athomps** [comment]
The purpose of unmap/remap is to apply the imageflag periodic shifts to all the atoms in a molecule so that they are together.  Otherwise rotation about com does not work right. The same thing is done in group->xcm calculation.

**Comment by athomps** [comment]
I agree that current version of attempt_molecule_rotation_full will malfunction if an atom is rotated to/from another process and the move is rejected.

**Comment by andeplane** [comment]
I haven't looked at this in a while. @athomps, will it also malfunction even if we don't have the `full` mode?

**Comment by akohlmey** [comment]
taking this down now due to inactivity. if any new information or issue pops up, please re-open or re-submit.
