### ISSUE TITLE
EAM Files missing

### ISSUE THREAD

**Issue by nishaChandramoorthy** [lammps/lammps#50]
Hi,
The eam files( `src/pair_eam_*.cpp` ) seem to be missing from the latest releases.
Have the eam potentials been included elsewhere?

Thanks!

**Comment by akohlmey** [comment]
On Apr 18, 2016 20:18, "Nisha Chandramoorthy" <notifications@github.com>
wrote:
>
> Hi,
> The eam files( src/pair_eam_*.cpp ) seem to be missing from the latest
releases.
> Have the eam potentials been included elsewhere?

Which release exactly and downloaded from where?

**Comment by akohlmey** [comment]
BTW: have you seen the "Restrictions" section at the end of the EAM pair style documentation?
http://lammps.sandia.gov/doc/pair_eam.html

**Comment by nishaChandramoorthy** [comment]
Thanks for your time!
Building with the manybody package(I think it's not enabled by default)
makes EAM work.
Thanks again!
