### ISSUE TITLE
Neighbor list bug affecting Dump/Local

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#500]
As reported by Kevin Hanley on lammps-users:
Dear LAMMPS developers,
 
In the latest version (19 May 2017), there is a bug which causes the dump file created using Dump/Local to be empty in certain cases. The attached two-particle simulation reproduces this problem.
 
I did a bit of investigating to try to help. The bug was introduced in the 2017-02-15 23:45:33 commit (sha1 = 4a80df3a99b87e7fd57e0b49e257918f024d3888) when changes were made to the neighbor lists. The version of LAMMPS immediately before this commit didn’t contain this bug.
 
In earlier versions of LAMMPS (e.g., 13 Feb 2017), the neighbor lists are created as follows:
 ```
  3 neighbor lists, perpetual/occasional/extra = 1 1 1
  (1) pair gran/hertz/history, size, perpetual
      pair build: half/size/bin/newtoff
      stencil: half/bin/3d/newtoff
      bin: standard
  (2) pair gran/hertz/history, size/history, perpetual
      pair build: none
      stencil: none
      bin: none
  (3) compute pair/local, half, occasional
      pair build: half/bin/newtoff
     stencil: half/bin/3d/newtoff
      bin: standard
``` 
In more recent versions of LAMMPS, ComputePairLocal relies upon a copied neighbor list:
```
  3 neighbor lists, perpetual/occasional/extra = 1 1 1
  (1) pair gran/hertz/history, perpetual
      attributes: half, newton off, size
      pair build: half/size/bin/newtoff
      stencil: half/bin/3d/newtoff
      bin: standard
  (2) pair gran/hertz/history, perpetual, history for (1)
      attributes: half, newton off, history
      pair build: none
      stencil: none
      bin: none
  (3) compute pair/local, occasional, copy from (2)
      attributes: half, newton off
      pair build: copy
      stencil: none
      bin: none
``` 
The empty dump file bug can be fixed temporarily by preventing neighbor lists from being created by copying. I did this by commenting out the call to morph_copy() in Neighbor::init_pair(). This forces a new neighbor list to be created. This is obviously not an efficient solution though so I hope that a better one can be found.
 
A small, unrelated bug-fix in FixShearHistory. The value “4” should be changed to “(dnum+1)” at line 392 (near the end of pre_exchange_newton) to allow for varying numbers of shear parameters. Similarly at line 593 in pack_reverse_comm_size, the “4” should be replaced in the same way.
 
Regards,
 
Kevin
[in.two_particles_Sandia.txt](https://github.com/lammps/lammps/files/1029218/in.two_particles_Sandia.txt)
[Two_Particle_Coordinates.txt](https://github.com/lammps/lammps/files/1029217/Two_Particle_Coordinates.txt)

**Comment by ajsilveira** [comment]
I'd like to add that this bug also produces a segfault when trying to use the run_style respa. I came to that conclusion by  running the same script with versions [fc3505f](https://github.com/lammps/lammps/commit/904609a7a3a5d88cd64594148d7642eb2178aab4) and [4a80df3](https://github.com/lammps/lammps/commit/4a80df3a99b87e7fd57e0b49e257918f024d3888). The first one did work while the second one did not.

**Comment by akohlmey** [comment]
may be related to issue #523

**Comment by sjplimp** [comment]
this should be fixed with a current PR (21 June 17)
