### ISSUE TITLE
reax/c/species hangs in replicated systems

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#505]
Hello,

Recently I encountered a bug in reax/c/species. The simulation hangs if this fix is used in a replicated system. A simple input script showing the problem is attached. I used the 19 May 2017 LAMMPS version.

The solution I have found is to change the chAnchor function (from line 501 in fix_reaxc_species.cpp) to this one:

> AtomCoord FixReaxCSpecies::chAnchor(AtomCoord in1, AtomCoord in2)
>{
>  if (in1.x < in2.x)
>    return in1;
>  else if (in1.x == in2.x && in1.y < in2.y)
>    return in1;
>  else if (in1.x == in2.x && in1.y == in2.y && in1.z < in2.z)
>    return in1;
>  return in2;
>}

[species_bug.zip](https://github.com/lammps/lammps/files/1038077/species_bug.zip)

**Comment by akohlmey** [comment]
Confirmed. I've included a slightly modified version of your suggested fix into pull request #495 which should be included in the next patch.

Thanks for reporting this issue and providing a fix at the same time.
