### ISSUE TITLE
r-RESPA with multi pair cutoff is currently broken

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#523]
At the moment, multi-cutoff r-RESPA does not work as the necessary NPair instances are not created leading to a segfault. The links contain r-RESPA variants of the rhodo benchmark.
[in.rhodo-respa-broken.txt](https://github.com/lammps/lammps/files/1062893/in.rhodo-respa-broken.txt)
[in.rhodo-respa-works.txt](https://github.com/lammps/lammps/files/1062892/in.rhodo-respa-works.txt)

**Comment by akohlmey** [comment]
may be related to issue #500

**Comment by sjplimp** [comment]
should be fixed by latest PR (June 21)
