### ISSUE TITLE
lammps-fix reax/c/species-output a wrong result

### ISSUE THREAD

**Issue by 1922544565** [lammps/lammps#529]
Dear Lammps Community,
 
Please allow me to report a strange phenomenon resulted from fix reax/c/species command.
I built an bicrystal alloy model consisting of total 2995 atoms.

By the atom type setting command: set group alloy type/fraction 1 0.82 12963 type/fraction 2 0.13 23486 type/fraction 3 0.05 23486, 
I intend to set 82% Fe atom, 13% Cr atom and 5% Al atom. 

And the log.lammps shows the following reasonable results: 
  2454 settings made for type/fraction
  397 settings made for type/fraction
  143 settings made for type/fraction

However, the fix reax/c/species command output a different result: Fe2118Cr251Al624.

Although I enabled the reax/c with kokkos package by the following changes, the same problem occurred again.

e.g. pair_style reax/c into pair_style reax/c/kk & fix reax/c/species into fix reax/c/species/kk

My lammps information is as follows: 
Lammps version: 31Mar17;
Packages: Kokkos, User-reaxc, User-misc, molecule, qeq, reax, replica, rigid, kspace, manybody 
Makefile.ubuntu: KOKKOS_DEVICES=OpenMP;
Running command: mpirun -np 4 -k on -sf kk -in in.mini

How do you like such problem? 

I attached the input script, log.lammps and output result by fix reax/c/species or fix reax/c/species/kk commands, please have a check!

Any advices will be highly appreciated! I look forward to your positive response,
Thanks in advance,
Best regards,

Xiaolong Liu from Korea Aerospace University.

**My input script is as follows, please have a check:**

# 1-Initialization 

units real

atom_style charge

atom_modify id yes map hash first alloy

boundary p p p

newton on

dimension 3

# 2-Creation of Fe82Cr13Al5 bicrystal

lattice bcc 2.866
region box block 0 15 -10 10 0 5 side in
create_box 3 box 

region left block 0 15 -10 0 0 5 side in
lattice bcc 2.866 orient x 5 -9 0 orient y 9 5 0 orient z 0 0 1 
create_atoms 3 region left 

region right block 0 15 0 10 0 5 side in
lattice bcc 2.866 orient x 5 9 0 orient y -9 5 0 orient z 0 0 1
create_atoms 3 region right  

group alloy region box
group grain1 region left
group grain2 region right

set group alloy type/fraction 1 0.82 12963 type/fraction 2 0.13 23486 type/fraction 3 0.05 23486 # Fe75Cr20Al5

mass 1 55.85000
mass 2 52.00000
mass 3 26.98000

change_box all x scale 1.2 y scale 1 z scale 1

# 3-Force field

pair_style reax/c lmp_control safezone 4.0

pair_coeff * * ffield.reax Fe Cr Al 

fix QEQ all qeq/reax 1 0.0 10.0 1.0e-6 reax/c

fix_modify QEQ energy yes

delete_atoms overlap 0.35 grain1 grain2 compress yes

fix BR all box/relax iso 0.0 

neighbor 2.5 bin

neigh_modify every 1 delay 0 check yes once no cluster no exclude none page 100000 one 2000 binsize 0.0 

# 4-Compute & thermo setting

compute total_potential_energy all pe

compute total_kinetic_energy all ke

compute reax all pair reax/c

thermo 250

thermo_style custom step time atoms temp press pe ke etotal epair

thermo_modify lost error lost/bond error norm yes flush yes line multi format float %10.4g temp thermo_temp press thermo_press

dump myimageSCC all image 500 dump.*.jpg type type atom yes size 1024 1024 view 30 60 center d 0.5 0.5 0.5 up 0 0 1 zoom 1.0 box yes 0.02 axes yes 0.05 0.1 subbox no 0.0 shiny 1.0

dump_modify myimageSCC append no element Fe Cr Al first yes flush yes thresh none acolor * red/blue/green adiam 1 2.48 adiam 2 2.50 adiam 3 2.86 backcolor black boxcolor white

# 5-Minimization 

min_style cg

min_modify dmax 0.1 line quadratic

minimize 1.0e-4 1.0e-6 100000 1000000

unfix BR

# 6-Equilibration

velocity all create 600 13425 loop local

fix NVT1 all nvt temp 600 600 100 drag 0.2

fix SP all reax/c/species 1 1 100 mole.out element Fe Cr Al 

timestep 0.20

restart 100 restart.*.stgb1

run 1000

unfix NVT1

The following is the log.lammps:
LAMMPS (31 Mar 2017)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (../comm.cpp:90)
  using 1 OpenMP thread(s) per MPI task
# 1-Initialization

units real

atom_style charge

atom_modify id yes map hash first alloy

boundary p p p

newton on

dimension 3

# 2-Creation of Fe82Cr13Al5 bicrystal

lattice bcc 2.866
Lattice spacing in x,y,z = 2.866 2.866 2.866
region box block 0 15 -10 10 0 5 side in
create_box 3 box
Created orthogonal box = (0 -28.66 0) to (42.99 28.66 14.33)
  2 by 2 by 1 MPI processor grid

region left block 0 15 -10 0 0 5 side in
lattice bcc 2.866 orient x 5 -9 0 orient y 9 5 0 orient z 0 0 1
Lattice spacing in x,y,z = 3.89719 3.89719 2.866
create_atoms 3 region left
Created 1505 atoms

region right block 0 15 0 10 0 5 side in
lattice bcc 2.866 orient x 5 9 0 orient y -9 5 0 orient z 0 0 1
Lattice spacing in x,y,z = 3.89719 3.89719 2.866
create_atoms 3 region right
Created 1505 atoms

group alloy region box
3010 atoms in group alloy
group grain1 region left
1520 atoms in group grain1
group grain2 region right
1520 atoms in group grain2

set group alloy type/fraction 1 0.82 12963 type/fraction 2 0.13 23486 type/fraction 3 0.05 23486 # Fe75Cr20Al5
  2454 settings made for type/fraction
  397 settings made for type/fraction
  143 settings made for type/fraction

mass 1 55.85000
mass 2 52.00000
mass 3 26.98000

change_box all x scale 1.2 y scale 1 z scale 1
  orthogonal box = (-4.299 -28.66 0) to (47.289 28.66 14.33)
  orthogonal box = (-4.299 -28.66 0) to (47.289 28.66 14.33)
  orthogonal box = (-4.299 -28.66 0) to (47.289 28.66 14.33)

# 3-Force field

pair_style reax/c lmp_control safezone 4.0

pair_coeff * * ffield.reax Fe Cr Al

fix QEQ all qeq/reax 1 0.0 10.0 1.0e-6 reax/c

fix_modify QEQ energy yes

delete_atoms overlap 0.35 grain1 grain2 compress yes
Neighbor list info ...
  update every 1 steps, delay 10 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 9 10 3
  3 neighbor lists, perpetual/occasional/extra = 2 1 0
  (1) command delete_atoms, occasional
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
  (2) pair reax/c, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/newtoff/ghost
      stencil: half/ghost/bin/3d/newtoff
      bin: standard
  (3) fix qeq/reax, perpetual, copy from (2)
      attributes: half, newton off, ghost
      pair build: copy
      stencil: none
      bin: none
Deleted 15 atoms, new total = 2995

fix BR all box/relax iso 0.0

neighbor 2.5 bin

neigh_modify every 1 delay 0 check yes once no cluster no exclude none page 100000 one 2000 binsize 0.0

# 4-Compute & thermo setting

compute total_potential_energy all pe

compute total_kinetic_energy all ke

compute reax all pair reax/c

thermo 250

thermo_style custom step time atoms temp press pe ke etotal epair

thermo_modify lost error lost/bond error norm yes flush yes line multi format float %10.4g temp thermo_temp press thermo_press

dump myimageSCC all image 500 dump.*.jpg type type atom yes size 1024 1024 view 30 60 center d 0.5 0.5 0.5 up 0 0 1 zoom 1.0 box yes 0.02 axes yes 0.05 0.1 subbox no 0.0 shiny 1.0

dump_modify myimageSCC append no element Fe Cr Al first yes flush yes thresh none acolor * red/blue/green adiam 1 2.48 adiam 2 2.50 adiam 3 2.86 backcolor black boxcolor white

# 5-Minimization

min_style cg

min_modify dmax 0.1 line quadratic

minimize 1.0e-4 1.0e-6 100000 1000000
Neighbor list info ...
  update every 1 steps, delay 0 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12.5
  ghost atom cutoff = 12.5
  binsize = 6.25, bins = 9 10 3
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reax/c, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/newtoff/ghost
      stencil: half/ghost/bin/3d/newtoff
      bin: standard
  (2) fix qeq/reax, perpetual, copy from (1)
      attributes: half, newton off, ghost
      pair build: copy
      stencil: none
      bin: none
Per MPI rank memory allocation (min/avg/max) = 516.4 | 517.7 | 518.8 Mbytes
---------------- Step        0 ----- CPU =      0.0000 (sec) ----------------
Step     =              0 Time     =          0 Atoms    =           2995 
Temp     =          0 Press    =  5.947e+04 PotEng   =     -73.63 
KinEng   =          0 TotEng   =     -73.63 E_pair   =     -73.63 
---------------- Step        1 ----- CPU =      4.8355 (sec) ----------------
Step     =              1 Time     =          1 Atoms    =           2995 
Temp     =          0 Press    =  5.902e+04 PotEng   =     -73.63 
KinEng   =          0 TotEng   =     -73.63 E_pair   =     -73.63 
Loop time of 4.83944 on 4 procs for 1 steps with 2995 atoms

46.4% CPU use with 4 MPI tasks x 1 OpenMP threads

Minimization stats:
  Stopping criterion = energy tolerance
  Energy initial, next-to-last, final = 
        -73.6304892688     -73.6304892688     -73.6348942056
  Force two-norm initial, final = 120792 120044
  Force max component initial, final = 110248 109434
  Final line search alpha, max atom move = 9.07043e-10 9.92614e-05
  Iterations, force evaluations = 1 1

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 1.1209     | 1.2991     | 1.3885     |   9.5 | 26.84
Neigh   | 0          | 0          | 0          |   0.0 |  0.00
Comm    | 0.046011   | 0.14995    | 0.3358     |  28.9 |  3.10
Output  | 0          | 0          | 0          |   0.0 |  0.00
Modify  | 2.8742     | 2.8762     | 2.8782     |   0.1 | 59.43
Other   |            | 0.5142     |            |       | 10.63

Nlocal:    748.75 ave 760 max 740 min
Histogram: 1 0 1 0 0 1 0 0 0 1
Nghost:    6670.25 ave 6676 max 6666 min
Histogram: 1 1 0 0 0 0 1 0 0 1
Neighs:    363701 ave 369048 max 359113 min
Histogram: 1 0 1 0 0 1 0 0 0 1

Total # of neighbors = 1454805
Ave neighs/atom = 485.745
Neighbor list builds = 0
Dangerous builds = 0

unfix BR

# 6-Equilibration

velocity all create 600 13425 loop local

fix NVT1 all nvt temp 600 600 100 drag 0.2

fix SP all reax/c/species 1 1 100 mole.out element Fe Cr Al

timestep 0.20

restart 100 restart.*.stgb1

run 1000
Per MPI rank memory allocation (min/avg/max) = 522 | 523.2 | 524.3 Mbytes
---------------- Step        1 ----- CPU =      0.0000 (sec) ----------------
Step     =              1 Time     =          0 Atoms    =           2995 
Temp     =        600 Press    =  6.479e+04 PotEng   =     -73.63 
KinEng   =      1.788 TotEng   =     -71.85 E_pair   =     -73.63 
---------------- Step      250 ----- CPU =    288.0386 (sec) ----------------
Step     =            250 Time     =       49.8 Atoms    =           2995 
Temp     =       3522 Press    =  1.111e+05 PotEng   =     -86.94 
KinEng   =      10.49 TotEng   =     -76.45 E_pair   =     -86.94 
---------------- Step      500 ----- CPU =    562.3106 (sec) ----------------
Step     =            500 Time     =       99.8 Atoms    =           2995 
Temp     =       2253 Press    =   8.74e+04 PotEng   =     -86.17 
KinEng   =      6.713 TotEng   =     -79.46 E_pair   =     -86.17 
---------------- Step      750 ----- CPU =    840.8746 (sec) ----------------
Step     =            750 Time     =      149.8 Atoms    =           2995 
Temp     =       1821 Press    =  6.923e+04 PotEng   =     -86.88 
KinEng   =      5.427 TotEng   =     -81.45 E_pair   =     -86.88 
---------------- Step     1000 ----- CPU =   1121.8346 (sec) ----------------
Step     =           1000 Time     =      199.8 Atoms    =           2995 
Temp     =       1587 Press    =  4.911e+04 PotEng   =     -87.69 
KinEng   =      4.728 TotEng   =     -82.96 E_pair   =     -87.69 
---------------- Step     1001 ----- CPU =   1124.0221 (sec) ----------------
Step     =           1001 Time     =        200 Atoms    =           2995 
Temp     =       1587 Press    =  4.902e+04 PotEng   =      -87.7 
KinEng   =      4.728 TotEng   =     -82.97 E_pair   =      -87.7 
Loop time of 1124.04 on 4 procs for 1000 steps with 2995 atoms

Performance: 0.015 ns/day, 1561.164 hours/ns, 0.890 timesteps/s
49.7% CPU use with 4 MPI tasks x 1 OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 707.14     | 724.76     | 738.85     |  42.3 | 64.48
Neigh   | 4.8634     | 4.9026     | 4.9392     |   1.3 |  0.44
Comm    | 23.345     | 36.774     | 54.013     | 182.2 |  3.27
Output  | 1.245      | 1.2834     | 1.3314     |   3.0 |  0.11
Modify  | 349.22     | 350.42     | 351.52     |   4.4 | 31.18
Other   |            | 5.891      |            |       |  0.52

Nlocal:    748.75 ave 754 max 741 min
Histogram: 1 0 0 0 0 0 2 0 0 1
Nghost:    6662.75 ave 6669 max 6654 min
Histogram: 1 0 0 0 0 1 0 0 1 1
Neighs:    347293 ave 349017 max 344041 min
Histogram: 1 0 0 0 0 0 1 0 0 2

Total # of neighbors = 1389172
Ave neighs/atom = 463.83
Neighbor list builds = 19
Dangerous builds = 0

unfix NVT1

Please see the log.cite file for references relevant to this simulation

Total wall time: 0:18:58

The following is the output by fix reax/c/species or fix reax/c/species/kk commands:

# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
101          1          1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
201          1          1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
301          1          1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
401          1          1	 1	
# Timestep     No_Moles     No_Specs     Fe2118Cr252Al624	Fe	
501          2          2	 1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al622	Al2	
601          2          2	 1	 1	
# Timestep     No_Moles     No_Specs     Fe2118Cr252Al622	FeAl2	
701          2          2	 1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
801          1          1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
901          1          1	 1	
# Timestep     No_Moles     No_Specs     Fe2119Cr252Al624	
1001          1          1	 1

**Comment by akohlmey** [comment]
LAMMPS is working correctly. the set type/fraction command is not used correctly. please see lammps-users mailing list archive for detailed explanation and a suggestion to address the problem.
