### ISSUE TITLE
Implement short neighborlists on manybody potentials in GPU package

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#543]
In CPU and KOKKOS versions of vashishta, sw and tersoff, we use short neighbor lists that only contains neighbors within cutoff. This is especially useful in vashishta where 3-body forces usually have much smaller cutoff. 

The GPU package is nice since it supports single/mixed precision and works in Atomify, so I'm interested in porting this feature into the GPU package as well. I'm not so familiar with how it actually does neighbor list building etc, so if anyone knows how to do this easily, feel free to do it :D If not I'll probably try to understand how it's done.

**Comment by andeplane** [comment]
I have been in contact with @ndtrung81 and Mike on email about this. I think I know how to do it and will get help on the way. Probably done within a month or two.

**Comment by stanmoore1** [comment]
@andeplane, glad to hear

**Comment by ndtrung81** [comment]
I've been working on this issue, supporting short neighbor lists for sw, vashishta and tersoff. Running tests before submitting a pull request.
