### ISSUE TITLE
reaxc/kk on CUDA not deterministic

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#549]
I'm using the newest patch release of LAMMPS on Ubuntu 16.04, Cuda 8.0.61 and noticed that reaxc is not deterministic in the sense that if I just run the same simulation twice, I get different results, as seen [here](https://www.diffchecker.com/IwexjXWb). I also checked a previous version from mid-march.

# How to reproduce
Take `examples/reax/CHO` [example](https://github.com/lammps/lammps/tree/master/examples/reax/CHO) (other examples too), replace the one run command with
```
thermo_style custom step temp pe
thermo 10
run 1000
```

and run twice with (same problem with all combinations of neigh half/full and neigh/qeq half/full):
`lmp_kokkos_cuda_openmp -package newton on neigh half -k on g 1 -sf kk -in in.CHO`

Other pair_styles are deterministic also on the GPU.

**Comment by stanmoore1** [comment]
If you get results that differ on timestep 0 by significantly more than machine precision, then that could point to a race condition. If you get slowly diverging trajectories over many timesteps, then that is probably normal.

**Comment by stanmoore1** [comment]
@andeplane ReaxFF is tricky since fix qeq uses a tolerance that causes trajectories to diverge much more quickly than other pair styles.

**Comment by andeplane** [comment]
I see, so maybe it's expected then:) I think t0 always is identical. You can close this then.
