### ISSUE TITLE
An issue with bitmap style of pair_style table or pair_write command

### ISSUE THREAD

**Issue by mkanski** [lammps/lammps#580]
## Summary

I would like to report a minor issue connected to pair_write or pair_style table with bitmap style. The LAMMPS warns that a significant part of points from the tabulated potential is inconsistent with -dE/dr.

## Type of Issue

Bug report

## LAMMPS Version (Bug Report)

6 Jul 2017

## Expected Behavior (Bug Report)

For a simple L-J interaction I would expect only only two points inconsistent with -dE/dr (it is the case with table linear or rsq style). 

## Actual Behavior (Bug Report)

The attached input script shows the problem - LAMMPS warns that almost 13k from 131k points are inconsistent.

## Steps to Reproduce (Bug Report)

Create a tabulated potential with pair_write bitmap and use it.

## Further Information, Files, and Links

I'm not actually sure if this is an issue with pair_style table bitmap, which incorrectly warns about inconsistency or with pair_write bitmap which incorrectly saves forces. Although I believe that the first case is much more probable, because if I plot the tabulated potential, it looks fine.

The input script:
[input.txt](https://github.com/lammps/lammps/files/1152940/input.txt)

**Comment by akohlmey** [comment]
confirmed. as the documentation for pair style table states, the ordering of the distance values is not regular, so the heuristic check cannot work. i think this warning can be ignored.
