### ISSUE TITLE
Disabling integration in chosen directions for particles in a region

### ISSUE THREAD

**Issue by khuston** [lammps/lammps#60]
I am simulating polymers near an implicit wall with the Steele 10-4-3 potential. Say the wall spans x and y at a constant z. I would like to restrict movement in the x,y directions for particles within some distance of the wall, preventing free sliding along the wall.

1. Is this already possible through existing lammps features I've missed?
2. If not, and I implement a fix nve/regionfreeze say, would it be worth adding to core lammps? i.e. should I put effort to make this more general than a one-time personal hack?

Thank you for your time.

**Comment by akohlmey** [comment]
On Wed, May 18, 2016 at 6:06 PM, Kyle Huston <notifications@github.com>
wrote:

> I am simulating polymers near an implicit wall with the Steele 10-4-3
> potential. Say the wall spans x and y at a constant z. I would like to
> restrict movement in the x,y directions for particles within some distance
> of the wall, preventing free sliding along the wall.
>
>    1. Is this already possible through existing lammps features I've
>    missed?
>
> ​i don't think there is an existing feature that does this.​

>
>    1. If not, and I implement a fix nve/regionfreeze say, would it be
>    worth adding to core lammps? i.e. should I put effort to make this more
>    general than a one-time personal hack?
>
> ​i am not sure whether the approach of simply excluding position
components from time integration would be a clean way to handle the
situation you describe. you'll have an inconsistency right at the boundary
of your "xy-freezing​" region where particles go from moving in xy to not
moving. also note, that just skipping atoms from (parts of the) time
integration has odd consequences on temperature, as the velocity of the
atoms will be unchanged and thus added to the total energy, yet the system
will behave as if those DOFs are frozen out.

 so i'd think a direction depending friction gradient would be cleaner
approach. you'd have a fix that would be used in addition to your wall and
defines a z-distance dependent friction term for x and y velocities. this
would - unlike your model - remove kinetic energy from the system.

 i'm wondering though, what would make a wall on an atomic level this
"sticky" and outside of a highly polar oxide surface in contact an ionic or
other strongly polar liquid like water, i couldn't come up with a scenario.

axel.




>
>
> Thank you for your time.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lammps/lammps/issues/60>
>



-- 
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by akohlmey** [comment]
No reaction on this for over a week. Closing this issue now.
