### ISSUE TITLE
erroneous molecule topology overflow error

### ISSUE THREAD

**Issue by jrgissing** [lammps/lammps#606]
after encountering this issue recently, it appears this fix never made it into mainline lammps:

http://lammps.sandia.gov/threads/msg64409.html

**Comment by akohlmey** [comment]
Please follow the template for issue reports and provide the various pieces of information to support your claim. It helps us to better assess the validity of a report and thus avoids wasting time.

With that in mind, please note that your claim is incorrect. The two changes mentioned in the e-mail you are pointing to **were** included in the LAMMPS master branch as commits a2e34aab0a8c15e0ae4b57471f18ec98d5ffdac3 and db36c8bcc31ec4ec4dd12b7efef0962199d0e56a and the changes are still present in [create_box.cpp:162](https://github.com/lammps/lammps/blob/master/src/create_box.cpp#L162) and [molecule.cpp:607](https://github.com/lammps/lammps/blob/master/src/molecule.cpp#L607).

**Comment by jrgissing** [comment]
sorry, classic case of not actually testing the fix. i believe there is then a separate issue, will get back to you asap (tonight)
