### ISSUE TITLE
Compilation error with intel compilers

### ISSUE THREAD

**Issue by michelleliu** [lammps/lammps#610]
## Summary

LAMMPS doesn't compile with USER-MISC package using intel compilers. It does compile using gnu compiler.

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

24 Jul 2017 from "unstable" branch

## Expected Behavior (Bug Report)

_Describe the expected behavior. Quote from the LAMMPS manual where needed or explain why the expected behavior is meaningful, especially when it differs from the manual_

## Actual Behavior (Bug Report)
Compilation results in an error about the file "pair_list.cpp" in USER-MISC package.

## Steps to Reproduce (Bug Report)

enable USER-MISC package
compile using intel compilers

## Further Information, Files, and Links

CC -g -O3 -DLAMMPS_MEMALIGN=64  -DLAMMPS_GZIP      -c ../pair_list.cpp
../pair_list.cpp(88): error: expected a ";"
    const dbl3_t * _noalias const x = (dbl3_t *) atom->x[0];
                            ^

../pair_list.cpp(89): error: "restrict" has already been declared in the current scope
    dbl3_t * _noalias const f = (dbl3_t *) atom->f[0];
             ^

../pair_list.cpp(89): error: expected a ";"
    dbl3_t * _noalias const f = (dbl3_t *) atom->f[0];
                      ^

../pair_list.cpp(114): error: identifier "x" is undefined
      const double dx = x[i].x - x[j].x;
                        ^

../pair_list.cpp(160): error: identifier "f" is undefined
          f[i].x += dx*fpair;
          ^

../pair_list.cpp(166): error: identifier "f" is undefined
          f[j].x -= dx*fpair;
          ^

compilation aborted for ../pair_list.cpp (code 2)

**Comment by akohlmey** [comment]
This is a known and documented issue. When using the Intel compilers, you have to use the `-restrict` flag. Otherwise, you get the error as you see for several packages. If you don't want to change the makefile, you need to delete the offending file(s) (e.g. `pair_list.h` and `pair_list.cpp` in this case).
