### ISSUE TITLE
Problem with "pair_modify compute no" in combination with "pair_style hybrid/overlay"

### ISSUE THREAD

**Issue by Non-Markovian** [lammps/lammps#615]
## Summary

The command "pair_modify pair coul/long compute no" in combination with "pair_style hybrid/overlay" seems to turn off _all_ pair-interactions, instead of only the short-range Coulomb.

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

LAMMPS Version: 10.08.2017

## Expected Behavior (Bug Report)

The command "pair_modify pair coul/long compute no" in combination with "pair_style hybrid/overlay" should only turn off the short-range Coulomb interaction.
Documentation: "First, this option allows you to perform a simulation with pair_style hybrid with only a subset of the hybrid sub-styles enabled."

## Actual Behavior (Bug Report)

However, when using this command, _all_ pair-interactions are turned off. In my input-script this can be observed, because the DPD-thermostat is not working properly anymore.

## Steps to Reproduce (Bug Report)

The error can be traced back to Lines 824-827 in pair_hybrid.cpp:
_if (narg-iarg > 0) {
    Pair::modify_params(narg-iarg,&arg[iarg]);
    styles[m]->modify_params(narg-iarg,&arg[iarg]);
}_
When turning off the pair coul/long interaction, the command "compute no" is also send to the "Pair"-class, leading to the command "pair_modify compute no", and consequentially, all pair-interactions are turned off. This can be solved (for my application) by dropping the line "Pair::modify_params(narg-iarg,&arg[iarg]);". However, this could have an impact for other commands.

A minimal example can be found attached. The LJ-interaction (with strength 0) is turned off, which should not change anything. However, also the DPD-thermostat is affected.
[in.example.txt](https://github.com/lammps/lammps/files/1217517/in.example.txt)

**Comment by akohlmey** [comment]
Thanks for your bug report. I have confirmed it and implemented a bugfix in PR #614
