### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by subhammridha** [lammps/lammps#642]
Syntax of the following example code is wrong.
https://github.com/lammps/lammps/blob/b1706060529b82476cab62786e2ccadd342dc437/doc/src/fix_saed_vtk.txt#L40

Instead of what is provided, it should be `fix 1 all saed/vtk 1 1 1 c_1 file Al2O3_001.saed`.

I spent a good deal of time trying to figure out the error thrown by lammps due to the present syntax. Then I went to the examples/USER/diffraction to view the example input file and it seemed that the syntax in this doc file is wrong. It would be better if the syntax is corrected.

**Comment by akohlmey** [comment]
thanks for reporting this. this example clearly violates the basic syntax requirements in LAMMPS for fixes (fix-id and group-id are required to _always_ follow the fix command). i've updated this in PR #641 and this should be included in the next LAMMPS patch release.
