### ISSUE TITLE
getting error on installation of lammps software on make step

### ISSUE THREAD

**Issue by NABIAHAMAD** [lammps/lammps#661]
Hello,
I am installing lammps software on a cluster locally, I do not have root password, then i got the error in make step when i am giving make mpi command error is given as-

make[1]: Entering directory `/UHOME/nabia.dcy2014/lammps/lammps-11Aug17/src/Obj_mpi'
Makefile.package.settings:7: ../../lib/mscg/Makefile.lammps: No such file or directory
make[1]: *** No rule to make target `../../lib/mscg/Makefile.lammps'.  Stop.
make[1]: Leaving directory `/UHOME/nabia.dcy2014/lammps/lammps-11Aug17/src/Obj_mpi'
make[1]: Entering directory `/UHOME/nabia.dcy2014/lammps/lammps-11Aug17/src/Obj_mpi'
Makefile.package.settings:7: ../../lib/mscg/Makefile.lammps: No such file or directory
make[1]: *** No rule to make target `../../lib/mscg/Makefile.lammps'.  Stop.
make[1]: Leaving directory `/UHOME/nabia.dcy2014/lammps/lammps-11Aug17/src/Obj_mpi'
make: *** [mpi] Error 2

What i have to do, Can anyone please help?
Thanks

**Comment by giacomofiorin** [comment]
This is an error with the mscg package, as you can see from the messages.  Try upgrading to the latest patch, and if it doesn't work, consider disabling the MSCG package.

**Comment by NABIAHAMAD** [comment]
Hi,
I am installing latest version of lammps now lammps-22Sep17 but make linux
is giving error as-
make[1]: *** No rule to make target `../../lib/latte/Makefile.lammps'.  Stop.
make[1]: Leaving directory `/UHOME/nabia.dcy2014/tar_files/lammps-22Sep17/src/Obj_linux'
make: *** [linux] Error 2

how to fix this, Can anyone please help?
Thanks

**Comment by akohlmey** [comment]
please read the LAMMPS manual more carefully and do not post such simple non-bug issues in the issue tracker, but to the lammps-users mailing list. this is not an issue with LAMMPS, but with your following the installation instructions.
