### ISSUE TITLE
Pylammps doesn't work with freshs/freshs

### ISSUE THREAD

**Issue by HaoZeke** [lammps/lammps#666]
## Summary

Running pylammps on a cluster gives a TypeError not present on single machines.

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

Latest version (master) [last commit: Aug 4 e84b6d806704a1d0340fbd18d86dd29bab5e2797]

## Expected Behavior (Bug Report)

No failure. 

## Actual Behavior (Bug Report)

It would appear that the method is returning a type error, possibly due to a return statement omission.

## Steps to Reproduce (Bug Report)

The following function, run on a RedHat based HPC exemplifies the error:

```python
def init_A():
        lmp.file('/home/amritag/Github/test_particles/lammps_input')
        L.dump("1 all custom", 1, "traj_nvt.lammpstrj id mol type x y z")
        x = random.uniform(1.050, 1.060)
        L.atoms[0].position = (0.0, 0.0, 0.0)
        L.atoms[1].position = (x, 0.0, 0.0)

        L.run(0)

        if calc_rc() < borderA:
            print "Configuration found"
            print "Exit"
            return
        else:
            while True:
                x = random.uniform(1.05, 1.06)
                L.reset_timestep(0)
                L.atoms[0].position = (0.0, 0.0, 0.0)
                L.atoms[1].position = (x, 0.0, 0.0)

                L.run(2)

                print("I am running again! Equilibriation")

                if calc_rc() < borderA:
                    print "Configuration found"
                    return

```

## Further Information, Files, and Links

The log file is also attached.

[PyLammps Error Log](https://github.com/lammps/lammps/files/1335105/test2.log)

**Comment by rbberger** [comment]
Looks to me like there is some stdout, stderr redirecting going on. Since PyLammps is capturing / redirecting output itself to function, there might be something messed up. How is this executed?

**Comment by HaoZeke** [comment]
Well, here the PyLammps instances are managed by (freshs)[https://github.com/freshs/freshs].
This works fine when it's on a **single computer** (or the HPC head node), but somehow running the freshs server client on the HPC causes PyLammps to error out...

**Comment by rbberger** [comment]
What job system are you using on the cluster? And what is the actual script trying to run this?

**Comment by rbberger** [comment]
btw, this doesn't make sense:
```
        lmp.file('/home/amritag/Github/test_particles/lammps_input')
        L.dump("1 all custom", 1, "traj_nvt.lammpstrj id mol type x y z")
```
where do lmp and L come from?

**Comment by HaoZeke** [comment]
Sorry for the late reply, so the lmp and L commands are just short-hands, defined by:

```python
from lammps import lammps, PyLammps
lmp = lammps()
L = PyLammps(ptr=lmp)
```

The lammps_input file has the pair potentials and box information.

The job system on the cluster is PBS Professional (v 14.2.1)
The script used to execute the commands on the HPC is as shown below: (the install portion is totally extraneous and is from an attempted fix when I thought the clients were having a path problem)

```bash
#!/bin/bash
#PBS -N salt_test
#PBS -q mini
#PBS -l nodes=2:ppn=20                                             
#PBS -o test.log
#PBS -e test.err
#PBS -j oe
cd /home/amritag/Github/freshs/server
export I_MPI_FABRICS=shm:dapl
export I_MPI_MPD_TMPDIR=/scratch/amritag
source /opt/software/intel/initpaths intel64
cd /home/amritag/Github/lammps/python
python install.py
(cd /home/amritag/Github/freshs/server; python main_server.py -c server-lammps-ffs.conf) &
(cd /home/amritag/Github/freshs/client; sleep 30; python /home/amritag/Github/freshs/client/main_client.py -c /home/amritag/Github/freshs/client/client-lammps-ffs.conf > log1) &
(cd /home/amritag/Github/freshs/client; sleep 30; python main_client.py -c client-lammps-ffs.conf > log2) &
(cd /home/amritag/Github/freshs/client; sleep 30; python main_client.py -c client-lammps-ffs.conf > log3) &
(cd /home/amritag/Github/freshs/client; sleep 30; python main_client.py -c client-lammps-ffs.conf > log4) &
wait
```

**Comment by rbberger** [comment]
I was able to recreate the scenario. Right now the code can't handle stdout being redirected on the outside (the `> log1` part).
```bash
python $CLIENT_DIR/main_client.py -c $CLIENT_DIR/client-lammps-ffs.conf > log1
```
As a workaround, please try if the following fixes your problem:
```bash
stdbuf -oL python $CLIENT_DIR/main_client.py -c $CLIENT_DIR/client-lammps-ffs.conf > log1
```

**Comment by HaoZeke** [comment]
That got it to work perfectly!! :) :)
Thanks so much
