### ISSUE TITLE
PyLammps errors when using echo command

### ISSUE THREAD

**Issue by amritagos** [lammps/lammps#678]
## Summary

Simple PyLammps commands don't seem to be working with a hybrid Buckingham potential 

## Type of Issue
Bug Report

## LAMMPS Version (Bug Report)

Master branch ( latest commit - f2c1172741b59e57ba0519015702fb223f599b01[September 23] )

## Expected Behavior (Bug Report)
As per the manual (http://lammps.sandia.gov/doc/tutorial_pylammps.html) the commands in the input file should work.

## Actual Behavior (Bug Report)
The error is concisely given by -

```python
Traceback (most recent call last):
  File "test", line 42, in <module>
    print"ID is %f\n"%(L.atoms[0].id)
  File "/home/amritag/.linuxbrew/Cellar/python/2.7.13_1/lib/python2.7/site-packages/lammps.py", line 481, in id
    return int(self.lmp.eval("id[%d]" % self.index))
  File "/home/amritag/.linuxbrew/Cellar/python/2.7.13_1/lib/python2.7/site-packages/lammps.py", line 686, in eval
    value = self.lmp_print('"$(%s)"' % expr).strip()
AttributeError: 'list' object has no attribute 'strip'
Total wall time: 0:00:00
```

## Steps to Reproduce (Bug Report)

The input file is -

```python
#!/home/amritag/.linuxbrew/opt/python/libexec/bin/python

import sys
import re
import os
import time
import math
import random

# lammps
from lammps import lammps, PyLammps
lmp = lammps()
L = PyLammps(ptr=lmp) #Get PyLammps

#LAMMPS
lmp.file('start.lmp') #To run lammps commands

#Test 
print"ID is %f\n"%(L.atoms[0].id)

#Distance between Na+ and Cl-
d = L.variables['dist_sq']
```

## Further Information, Files, and Links
The lammps commands are in [start.lmp.txt](https://github.com/lammps/lammps/files/1354003/start.lmp.txt), [data.nacl.txt](https://github.com/lammps/lammps/files/1354009/data.nacl.txt)
[in.nacl.txt](https://github.com/lammps/lammps/files/1354010/in.nacl.txt)

**The files have been appended with _.txt_ to be uploaded.**

As per the manual, all the packages required were installed.

**Comment by rbberger** [comment]
This doesn't have anything to do with the used potential. It's your first line of the script:
```
echo both
```
disable that line, and it will work.
```
#echo both
```
The reason for this is that PyLammps works by looking at the output of simple commands, but `echo` modifies the way the output looks. That's why it gets confused.

**Comment by amritagos** [comment]
Thanks, that works..
