### ISSUE TITLE
Minor bug in output.cpp

### ISSUE THREAD

**Issue by dxhisboy** [lammps/lammps#690]
I'm trying to migrate lammps to some customized platform.
The Output::memory_usage() method causes a SIGFPE since the mbavg is not initialized in procs with comm->me > 0.
```c
  MPI_Reduce(&mbytes,&mbavg,1,MPI_DOUBLE,MPI_SUM,0,world);
  MPI_Reduce(&mbytes,&mbmin,1,MPI_DOUBLE,MPI_MIN,0,world);
  MPI_Reduce(&mbytes,&mbmax,1,MPI_DOUBLE,MPI_MAX,0,world);

  mbavg /= comm->nprocs; 
//mbavg is not initialized when comm->me > 0, but it may be move to the if branch

  if (comm->me == 0) {
```

**Comment by akohlmey** [comment]
Thanks for your report. Your observation is correct and your suggestion for a fix is a good one. This will be included in the master branch and patch release at the next opportunity.
