### ISSUE TITLE
NaN coordinates trigger a segfault in AngleTable::uf_lookup()

### ISSUE THREAD

**Issue by giacomofiorin** [lammps/lammps#692]
## Summary

`angle_style table` enforces a table ranging from 0° to 180° in user input.  However, if the coordinates become `nan` due to unstable input, the angle table lookup segfaults. 

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

Current `master`

## Expected Behavior (Bug Report)

LAMMPS should exit with an error.

## Actual Behavior (Bug Report)

LAMMPS throws a segfault in AngleTable::uf_lookup()

## Steps to Reproduce (Bug Report)

Attached below is a set of input files based on the `peptide` example, where one of the angle types is changed to table.  Using a very long integration step (e.g. 50 fs) yields `nan` coordinates at the 1st update, and the segfault immediately after.  

[messed-up-peptide.zip](https://github.com/lammps/lammps/files/1383259/messed-up-peptide.zip)

**Comment by akohlmey** [comment]
can't reproduce the segfault, but PR #691 (already merged to master) should have a fix for this one.

**Comment by giacomofiorin** [comment]
The current master now exits with `Illegal angle in angle style table`.  Nice.
