### ISSUE TITLE
[Feature Request] Long-range point-dipole solver

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#70]
LAMMPS has an Ewald-based long-range dipole solver, but not a more efficient PPPM version. With increasing support for more complex force fields and interest in point dipole polarizable force field, this option would be required for simulating larger systems efficiently.

**Comment by stanmoore1** [comment]
I worked on this some and have some unfinished code if anyone wants a copy. I'll probably work on it more in the future but not for a while.

**Comment by stanmoore1** [comment]
I have a branch of the unfinished code here: https://github.com/stanmoore1/lammps/tree/pppm_dipole. It still needs a lot of work.

**Comment by stanmoore1** [comment]
We now have some funding for this, so I'm going to start working on it soon.

**Comment by stanmoore1** [comment]
The code in https://github.com/stanmoore1/lammps/tree/spin_pppm now works correctly for point dipoles (as far as I can tell). Charge-dipole interactions haven't been implemented yet, and will probably have to wait for a while. I need to clean up/refactor the code to a state that could be merged into LAMMPS.

**Comment by stanmoore1** [comment]
Add a PR for this, see #1053.
