### ISSUE TITLE
Discontinuity of energy in reaxFF

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#71]
Reported by Michał Kański on lammps-users:

Hello all,

I encountered a discontinuity of energy when using ReaxFF. Namely, there is a rapid change of energy (few kcals/mol) when a bond in a diatomic molecule is being broken. The issue also occurs when an atom is being detached from a molecule. I checked the code and I believe that the change occurs, because the undercoordination term is not calculated when an atom does not have any bond. The simplest resolution I have found is removing if-statements from reaxc_multibody.cpp (lines 190, 205, 211) which restrict calculation of undercoordination term to bonded atoms.

Could someone confirm the presence of the issue?

I’m attaching a simple input script which shows the problem. I used the 31 May 2016 version of LAMMPS.

Cheers,
Michal

[discontinuity_reaxFF.in.txt](https://github.com/lammps/lammps/files/296867/discontinuity_reaxFF.in.txt)

**Comment by akohlmey** [comment]
Comment from Aidan:

I took a look at this.  It is not something that is in the original ReaxFF Fortran code, nor in the PureMD stand-alone code from which it is derived.  It seems to have been added in this revision:

```
r11904 | sjplimp | 2014-05-02 15:38:42 -0600 (Fri, 02 May 2014) | 1 line
```
(AK: this corresponds to git commit ddcab1268e9777e339f0181efb8a61099f1dd3ef)

Somebody thought it was necessary to add the numbonds>0 condition, but I can't say why.  

I will copy Ray on this, as I suspect he may have made the change.

Aidan

**Comment by stanmoore1** [comment]
@athomps do you think we should revert the numbonds>0 condition?

**Comment by athomps** [comment]
I think introducing a large discontinuity is bad.

Sent from my iPhone

On Feb 1, 2017, at 3:24 PM, Stan Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


@athomps<https://github.com/athomps> do you think we should revert the numbonds>0 condition?

-

**Comment by stanmoore1** [comment]
Maybe fixed in addd87c0f7a47fd54c3ccfb7edc11a166e2bc2e3, someone needs to confirm

**Comment by mkanski** [comment]
Introducing `enobonds` keyword solved this issue - see the graph below:

![image](https://user-images.githubusercontent.com/20713012/169560102-ab86c95e-5006-4d46-bd21-593d8558cdc6.png)

**Comment by stanmoore1** [comment]
Wow, this looks like a bug. Is there ever a case where someone would want this huge discontinuity?? i.e. do we really need a keyword for this, vs just fix the bug?

**Comment by athomps** [comment]
This has been a known issue for a long time.  That's why enonbonds exists.  If you don't care about energy, it is fine.
