### ISSUE TITLE
fix_rigid_small.cpp

### ISSUE THREAD

**Issue by leopwma** [lammps/lammps#711]
## Summary
When I am compiling lammps, there is error in fix_rigid_small.cpp. Error is as follows.

mpiicpc -axCORE-AVX2 -ip -O3 -qopenmp -DLAMMPS_MEMALIGN=64 -qno-offload -fno-alias -ansi-alias -restrict -xHost -O3 -ip -fp-model fast=2 -no-prec-div -qoverride-limits   -I/usr/local/depot/INTEL2017/intel/compilers_and_libraries_2017.0.098/linux/mkl/include  -DLAMMPS_GZIP -DLMP_MPIIO -I../../lib/voronoi/includelink -DLMP_PYTHON  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1 -DFFT_MKL -DFFT_SINGLE   -I/usr/include/python2.7 -I/usr/include/python2.7  -c ../fix_rigid_small.cpp
../fix_rigid_small.cpp(1503): error: argument of type "void (*)(int, char *)" is incompatible with parameter of type "void (*)(int, char *, void *)"
    comm->ring(m,sizeof(double),buf,1,ring_bbox,NULL);
                                      ^

../fix_rigid_small.cpp(1503): error #165: too few arguments in function call
    comm->ring(m,sizeof(double),buf,1,ring_bbox,NULL);
                                                    ^

../fix_rigid_small.cpp(1553): error: argument of type "void (*)(int, char *)" is incompatible with parameter of type "void (*)(int, char *, void *)"
    comm->ring(m,sizeof(double),buf,2,ring_nearest,NULL);
                                      ^

../fix_rigid_small.cpp(1553): error #165: too few arguments in function call
    comm->ring(m,sizeof(double),buf,2,ring_nearest,NULL);
                                                       ^

../fix_rigid_small.cpp(1585): error: argument of type "void (*)(int, char *)" is incompatible with parameter of type "void (*)(int, char *, void *)"
    comm->ring(m,sizeof(double),buf,3,ring_farthest,NULL);
                                      ^

../fix_rigid_small.cpp(1585): error #165: too few arguments in function call
    comm->ring(m,sizeof(double),buf,3,ring_farthest,NULL);
                                                        ^

compilation aborted for ../fix_rigid_small.cpp (code 2)
make[1]: *** [fix_rigid_small.o] Error 2
make[1]: Leaving directory `/home/leoma/lammps/src/Obj_auto'
make: *** [auto] Error 2

## Type of Issue
Bug report

## Detailed Description (Enhancement Suggestion)
Correct the code please.

## LAMMPS Version (Bug Report)
Both master and stable 

## Expected Behavior (Bug Report)
No error

## Actual Behavior (Bug Report)
../fix_rigid_small.cpp(1503): error: argument of type "void (*)(int, char *)" is incompatible with parameter of type "void (*)(int, char *, void *)"

## Steps to Reproduce (Bug Report)
I am using Intel 2017 compiler. 

## Further Information, Files, and Links
N/A

**Comment by akohlmey** [comment]
just tested "stable" and "master" branches of the current git repo using Intel 2017.4.196.
both build without a problem. it looks too me, that you have updated your repo or switched branches without running "make package-update" and thus have an inconsistency between the ring communicator class and its usage in fix rigid/small. there was a change in the API in mid-june 2017.
