### ISSUE TITLE
compute style

### ISSUE THREAD

**Issue by caomeiweizi** [lammps/lammps#720]
units         metal

dimension     3

newton       on

boundary      p s s 

atom_style    atomic

neighbor      2.0      bin

neigh_modify  check    yes

lattice       diamond  5.43

region        box    block 0 40 0 6 0 6  units lattice

create_box    1  box

create_atoms  1  box

mass          1  28

velocity      all  create  500 458127641 mom yes  rot yes dist gaussian units box

#tersoff potential

pair_style     tersoff

pair_coeff     * * SiC.tersoff Si

fix NVT all nvt temp 500 500 0.05

thermo_style   custom step temp etotal vol

thermo_modify  lost warn

thermo         1000

timestep       0.00055

run            20000

unfix          NVT

fix            nve all nve

run            20000

reset_timestep  0

compute        myKE all ke/atom

compute        myPE all pe/atom

compute        myStress all stress/atom NULL virial

variable       factor_ac equal 1.0

variable       factor_tc equal 1.602763e-19/1.0e-12/1.0e-10

compute        jflux all heat/flux myKE myPE myStress

compute        tc all tc c_thermo_temp c_jflux v_factor_ac v_factor_tc x first 5000  0  10000

fix          tc_out  all ave/time 1 1 1  c_tc file tc_timegraphene.dat

restart      10000   restart.*

dump         edata all  custom  100000 output.xyz  type  x y z

run          30000

The above is the in file, but the operation results are wrong, want to ask what is the problem?

compute        myKE all ke/atom
compute        myPE all pe/atom
compute        myStress all stress/atom NULL virial
variable       factor_ac equal 1.0
variable       factor_tc equal 1.602763e-19/1.0e-12/1.0e-10
compute        jflux all heat/flux myKE myPE myStress
compute        tc all tc c_thermo_temp c_jflux v_factor_ac v_factor_tc x first 5000  0  10000
ERROR: Unknown compute style c_thermo_temp (../modify.cpp:1151)
Last command: compute        tc all  c_thermo_temp c_jflux v_factor_ac v_factor_tc x first 5000  0  10000

**Comment by akohlmey** [comment]
this is completely bogus. the input you copied is inconsistent with the error message. 
the error message is self-explanatory and an obvious user error (there is no compute style `c_thermo_temp`).
even though you don't provide any helpful information as requested by the issue template,
it is obvious, however, that this is due to a user error and is not an issue with LAMMPS and thus invalid.

**Comment by caomeiweizi** [comment]
The wrong command is to calculate the heat flow correlation function and get the thermal conductivity. How should I modify it?

**Comment by caomeiweizi** [comment]
The wrong command is to calculate the heat flow correlation function and get the thermal conductivity. How should I modify it?

**Comment by akohlmey** [comment]
you need to use LAMMPS according to its documentation. i am locking this issue now, this is a conversation that does not belong here.
