### ISSUE TITLE
H5MD dump files corrupted issues in multi-partition mode

### ISSUE THREAD

**Issue by anyuzx** [lammps/lammps#722]
I have been running multiple independent simulations in a single job using the multi-partition mode of LAMMPS. However there is a issue regarding the `h5md` style dump files.  When running on a cluster, if a single trajectory doesn't finish by the scheduled time and the job is terminated, then all the H5MD dump files from all partitions are corrupted. When trying to read these H5MD files, it gives error

```
OSError: Unable to open file (File signature not found)
```

Apparently, the error is from not closing the hdf5 file which is due to the job terminated by the cluster. However for custom style dump files, the dump files seems are updated independently and frequently. So even when the job is terminated early, the trajectories themselves can still be read and updated to current.

It would be nice that individual runs within a partition job is able to close the HDF5 files whenever it is finished regardless of whether the job is finished or not. Thus even if the job is terminated, those trajectories finished before termination are updated to the current and readable.

**Comment by akohlmey** [comment]
have you tried adding an `undump` command to the end of your jobs?
that should enforce closing dump files, even if the LAMMPS object is not yet destroyed.

**Comment by anyuzx** [comment]
thx for the suggestion! I never thought about using this command. I just tested it, it works!
