### ISSUE TITLE
REBO parameters

### ISSUE THREAD

**Issue by CF17** [lammps/lammps#726]
After performing some tests I came to the conclusion that the current version of the REBO potential implemented in LAMMPS is not the one as described in the original publication by Brenner (J. Phys.: Condens. Matter 14 (2002) 783).  Favata and coworkers have pointed out last year the one parameter should be modified between AIREBO and REBO: PCC[2][0] should be 0 for REBO and -0.027603 for AIREBO. But other parameters should similarly be modified.

By looking at the table 8 of the 2002 paper of Brenner and comparing it with table 8 of the 2000 paper of Stuart (AIREBO) we can see that a similar modification needs to be performed for the parameters PCC[1][1] and PCC[0][2]. By changing these three parameters using the values given by Brenner I was able to recover the atomization energies for some of the molecules given in Table 12 of the Brenner paper. 

The modifications necessary are quite straightforward since the calculation of the spline coefficients is now included directly in the LAMMPS code.

**Comment by akohlmey** [comment]
@athomps sending out a reminder that @sjplimp has asked you to have a look at this by assigning the issue to you on github.
