### ISSUE TITLE
Possibly wrong create_atoms command documentation

### ISSUE THREAD

**Issue by LisiLisenok** [lammps/lammps#736]
Current (version 23 Oct 2017):
rotate values = Rx Ry Rz theta
  Rx,Ry,Rz = rotation vector for single molecule
  theta = rotation angle for single molecule (degrees)

Should be
rotate values = theta Rx Ry Rz
  theta = rotation angle for single molecule (degrees)
  Rx,Ry,Rz = rotation vector for single molecule

**Comment by akohlmey** [comment]
Thanks for reporting. Your observation is correct. The corresponding changes have been included in PR #737
