### ISSUE TITLE
 error: no instance of overloaded function "ATC_matrix::Matrix<T>::pow" matches the argument list argument types are: (double, double)

### ISSUE THREAD

**Issue by puneet336** [lammps/lammps#739]
## Summary
i am trying to compile lammps kokkos on RHEL 6.5 with following in my shell environment - 

- cuda/7.5,
- openmpi/1.10.0
- gcc/4.9.3
- python/2.7.13
- jpeg/6b
- fftw/3.3.7 and 
- zlib/1.2.8

now when i run 
make VERBOSE=1 kokkos_cuda_openmpi
i get lot of warning along with an error message which complains that a function is not defined.

## Type of Issue

Seems like a Bug

## Detailed Description (Enhancement Suggestion)

../../lib/atc/Matrix.h(359): error: no instance of overloaded function "ATC_matrix::Matrix<T>::pow" matches the argument list
            argument types are: (double, double)
though if i define a "dummy" pow function in Matrix.h file with signature - 
DenseMatrix<T> pow(double n) const;
, the compilation proceeds.

Am i missing something during the compilation ? 

Though if i define a dummy function in lib/atc/Matrix.h with signature like - 
**DenseMatrix<T> pow(double n, double dummy) const;**
The compilation proceeds, though i understand that the pow function defined in math.h  accepts 2 arguments of double type

. I am unable to understand what might cause this issue.

## LAMMPS Version (Bug Report)

I got the same error with - lammps 11 August 2017 and 31 March 2017

## Attachments/ Compilation Logs
Failure log - [lammps-11aug2017.log](https://github.com/lammps/lammps/files/1517142/lammps-11aug2017.log)
Logs after adding a dummy pow function - [lammps_complete.log](https://github.com/lammps/lammps/files/1517233/lammps_complete.log)

**Comment by stanmoore1** [comment]
@puneet336 thanks for reporting. Is there a reason you need to include the optional USER-ATC package? There is zero support for that in the LAMMPS KOKKOS package.

**Comment by akohlmey** [comment]
@puneet336 your "fix" is incorrect. a more suitable change is in commit https://github.com/lammps/lammps/pull/737/commits/319508bd292b9c36c6fa4c30ea1220776f06ffb7
will still need to test if this passes nvcc, which is known to occasionally choke on valid C++ code.

**Comment by akohlmey** [comment]
yup. nvcc is happy with this change, too.
