### ISSUE TITLE
KOKKOS CMAKE issue

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#753]
@junghans I'm trying to build KOKKOS-enabled LAMMPS "23 Oct 2017" using CMAKE but I'm getting an error:
```
[ 59%] Building CXX object CMakeFiles/lammps.dir/home/stamoor/Documents/lammps_master/src/neighbor.cpp.o
[ 59%] Building CXX object CMakeFiles/lammps.dir/home/stamoor/Documents/lammps_master/src/set.cpp.o
[ 59%] Building CXX object CMakeFiles/lammps.dir/home/stamoor/Documents/lammps_master/src/ntopo_angle_all.cpp.o
lammps_master/cmake/../src/KOKKOS/npair_copy_kokkos.h: In member function 'void LAMMPS_NS::Neighbor::init_styles()':
lammps_master/cmake/../src/KOKKOS/npair_copy_kokkos.h:17:28: error: 'LMPDeviceType' was not declared in this scope
            NPairCopyKokkos<LMPDeviceType>,
                            ^
lammps_master/src/neighbor.cpp:586:38: note: in definition of macro 'NPairStyle'
   pairclass[npclass] = &pair_creator<Class>; \
                                      ^
lammps_master/cmake/../src/KOKKOS/npair_copy_kokkos.h:17:41: error: template argument 1 is invalid
            NPairCopyKokkos<LMPDeviceType>,
```
Any ideas?

I also had to manually set the environment variable KOKKOS_PATH on the make line, we may want to add a note for this to the Readme.

**Comment by stanmoore1** [comment]
This does compile using the original gmake build system.

**Comment by rbberger** [comment]
The reason for it is a difference in the generated `style_nbin.h`. `nbin_kokkos.h` is missing. That one is the first header that includes `kokkos_type.h`. Seems to be one of many mistakes in the CMake build, because the script only considers `[prefix]_name_[extension].h` as valid styles. Bugfix in the works...

**Comment by rbberger** [comment]
@stanmoore1 I don't run into the second issue you mentioned. It just works out of the box on my machine. Please add the line you used to run cmake.

**Comment by stanmoore1** [comment]
@rbberger yeah, I can't duplicate that either, so I think it is fine.
