### ISSUE TITLE
Error in pair_style hybrid and tersoff

### ISSUE THREAD

**Issue by abbasabouei** [lammps/lammps#757]
Dear users
I want to do a simulation like water droplet on silicon surface
so i have 3 atoms and i defince pair style hybrid and used tersoff for silicon
but there is a proble i need to use tersoff onec time in pair_style hybrid command becaues i just have silicon as many body potential.
but if i use once time the lamps give an error like 
"cannot open Ters-off potential file" 
if i use twice tiem while taht is wrong because i just have silicon many body atom 
the Lammps read the Tersoff potential file but after run give this error like
"Pair hybrid sub_style is not used" which is true becauese i use tersoff twice in pair_style hybrid command but i used it onece
I dont khow how to solve it, i think it is the lammps bug i am using the LAMMPS 64-bit 20150316 for windws in windows 7.
the code is as follow 
#TIP4P-Ew Water Between SI Solid Walls
echo both
log log.pt_water.in
dimension        3
boundary        p p p

units        real
atom_style   full
timestep 0.5

read_data   water.dat

#pair_style hybrid lj/long/tip4p/long cut long 2 1 1 1 0.125 9 9 lj/cut 9
pair_style hybrid lj/long/tip4p/long cut long 2 1 1 1 0.125 9 9 tersoff lj/cut 9
pair_coeff      1 *  lj/long/tip4p/long 0 0
pair_coeff      2 2  lj/long/tip4p/long 0.162748420125 3.16435
kspace_style pppm/disp/tip4p 0.0001
pair_coeff * * tersoff 1 Si.tersoff NULL NULL Si
pair_coeff      2 3  lj/cut 0.2404 2.95 

any one can heps?? How to solve it?

**Comment by akohlmey** [comment]
these are not LAMMPS issues but user errors and incorrect input. thus this has no place in the issue tracker. please post to the lammps-users mailing list, but before that you should upgrade your *very* old LAMMPS version to a more recent one.
