### ISSUE TITLE
fix atom/property broken between stable_11Aug2017 and master ??

### ISSUE THREAD

**Issue by zqex** [lammps/lammps#759]
Goal: I'm simulating a glassy material using polydisperse particles. I use fix atom/property to store a per particle sigma (d_size) variable, which is then used in the force field calculation. Monodisperse samples crystallize, hence the need for polydispersity. Previously my code worked as expected, but since doing a git pull, the d_size identically zero, and I can't even reset it with set atom * d_size v_size.

I have attached two scripts that reproduce the error using the plain master branch of LAMMPS, while it works as expected using the stable_11Aug2017 branch.

generate.txt is a script for generating a sample where each particle has a double atom/property d_size property. This is assigned using set atom * d_size v_size, which is sampled from an uniform distribution, and the configuration is stored as a restart file.

continue.txt is a script that loads that restart file, runs a small simulation, and save a few dump files containing d_size. What I observe is that d_size is zero in the second script. I have checked (inserting printf in the fix_atom_property code where restart data are unpacked) and the d_size data is correctly read from the restart file. Secondly, I have tried to set atom * d_size v_size after reading it, but d_size remains zero even after setting it. Uncomment two lines in continue.txt to do this.

[generate.txt](https://github.com/lammps/lammps/files/1615622/generate.txt)
[continue.txt](https://github.com/lammps/lammps/files/1615623/continue.txt)

**Comment by stanmoore1** [comment]
I can reproduce this issue.

**Comment by stanmoore1** [comment]
Looks like d5f8f36442bfc14ba49c4090f465f87afc65a24e broke this, will look into a fix.
