### ISSUE TITLE
Fallback to bin/nsq method when corresponding halffull method does not exist

### ISSUE THREAD

**Issue by dxhisboy** [lammps/lammps#779]
## Summary

_Fallback to bin/nsq method when corresponding halffull method does not exist_

## Type of Issue

_'Suggestion for an Enhancement'_

## Detailed Description (Enhancement Suggestion)

_Since not all kind of half lists have its corresponding "halffull" method, but the "morph_halffull()" function set the request to "halffull" when there is a corresponding full list request, then the halffull request cannot be fulfilled. I suggest to fallback to the "bin" or "nsq" method in that case._
e.g.
```
  irequest = neighbor->request(this,instance_me);
  neighbor->requests[irequest]->newton = 2;
  neighbor->requests[irequest]->ghost = 1;
  neighbor->requests[irequest]->id = 0;
  irequest = neighbor->request(this, instance_me);
  neighbor->requests[irequest]->newton = 2;
  neighbor->requests[irequest]->ghost = 1;
  neighbor->requests[irequest]->id = 1;
  neighbor->requests[irequest]->half = 0;
  neighbor->requests[irequest]->full = 1;
```

_The list with id=0 is a half list of list with id=1, so the morph_halffull make the first request halffull, but there is not a npair_halffull_ghost method, making the program exits with an "unknown pair style"._
_I suggest fallback to bin method in such case, based on the 11Aug17 version, I have the following modification making this work:_
```
729,740d728
<     flag = choose_pair(requests[i]);
<     if (flag < 0) {
<       if (requests[i]->halffull){
<       requests[i]->halffull = 0;
<       flag = choose_pair(requests[i]);
<       }
<     }
<     lists[i]->pair_method = flag;
<     if (flag < 0) {
<       error->all(FLERR,"Requested neighbor pair method does not exist");
<     }
<
749a738,742
>
>     flag = choose_pair(requests[i]);
>     lists[i]->pair_method = flag;
>     if (flag < 0)
>       error->all(FLERR,"Requested neighbor pair method does not exist");
```
_and make the loop like this:_
```
  for (i = 0; i < nrequest; i++) {
    flag = choose_pair(requests[i]);
    if (flag < 0) {
      if (requests[i]->halffull){
        requests[i]->halffull = 0;
        flag = choose_pair(requests[i]);
      }
    }
    lists[i]->pair_method = flag;
    if (flag < 0) {
      error->all(FLERR,"Requested neighbor pair method does not exist");
    }

    flag = choose_bin(requests[i]);
    lists[i]->bin_method = flag;
    if (flag < 0)
      error->all(FLERR,"Requested neighbor bin option does not exist");

    flag = choose_stencil(requests[i]);
    lists[i]->stencil_method = flag;
    if (flag < 0)
      error->all(FLERR,"Requested neighbor stencil method does not exist");
  }
```
So if there is not a halffull method, the request will be handled by bin/nsq method.
## LAMMPS Version
_11Aug17_

**Comment by stanmoore1** [comment]
@dxhisboy I agree that this is a good feature. Can you provide a small reproducer input deck of the failure, and also submit your suggested changes as a pull request? Thanks

**Comment by akohlmey** [comment]
@dxhisboy this has been idle for many months now. Obviously people are waiting for your input...

**Comment by akohlmey** [comment]
No response for 3 1/2 years.
