### ISSUE TITLE
Problem in write_restart parameter parsing code

### ISSUE THREAD

**Issue by stukowski** [lammps/lammps#780]
## Summary

The command
```write_restart rst.%.*.loop nfile 32``` 
works, but after switching the order of ``%`` and ``*``:
```write_restart rst.*.%.loop nfile 32``` 
the same command fails with error message 
```Cannot use write_restart nfile without % in restart file name (../write_restart.cpp:210)```

## Type of Issue

Bug Report

## Detailed Description

Note how this code screws up the argument string if the ``*`` comes first:

https://github.com/lammps/lammps/blob/5e9d257ec2259efe5c614d75d30abb3d729603e6/src/write_restart.cpp#L95-L98

Now this line fails to detect the ``%``, because the string has been truncated by the code above:

https://github.com/lammps/lammps/blob/5e9d257ec2259efe5c614d75d30abb3d729603e6/src/write_restart.cpp#L102

## LAMMPS Version (Bug Report)

LAMMPS (23 Oct 2017)

**Comment by akohlmey** [comment]
Thanks for the detailed and specific bug report. This issue should be addressed with the single line fix in commit 3bc1c6b59e4f622c21637ce24f1fd8644dfb806e
