### ISSUE TITLE
Question regarding the MC example in the manual

### ISSUE THREAD

**Issue by AFarhi** [lammps/lammps#788]
## Summary

In page 411 in the manual it is written "math.exp(natoms*(elast-e)/kT)".
Why should "natoms" appear?

Thanks,
Best,
Asaf
## Type of Issue

'Bug Report'

## LAMMPS Version (Bug Report)

Online manual

## Expected Behavior (Bug Report)

Could lead to incorrect sampling (violate detailed balance).

**Comment by akohlmey** [comment]
please post questions like these to the lammps-users mailing list.
