### ISSUE TITLE
comm_modify cutoff/multi option

### ISSUE THREAD

**Issue by herrmartinwagner** [lammps/lammps#8]
Adds a cutoff/multi option to comm_modify to specify type-dependent communication cutoffs when in mode multi. Also adds explanation about default behaviour of option cutoff when in mode single to doc.

**Comment by akohlmey** [comment]
It is a bit annoying that github doesn't support attachments that are not images. One way to workaround this is to upload the patch to a service like dropbox or google docs and then create a readonly link for sharing. For the sake of testing and archiving, am uploading the patch sent via personal e-mail below.
https://www.dropbox.com/s/ahijw8bn7n91nk0/comm_modify_cutoff_multi.tar.gz?dl=0

**Comment by herrmartinwagner** [comment]
I found an issue with the option I added, in that somehow the normal cutoff option needs to still be specified, else (I think) the communication patterns are not set up correctly and simulations crash. I will (hopefully) get around to modifying and documenting this properly next week.

**Comment by akohlmey** [comment]
there is another issue. you cannot access atom->ntypes before the simulation box is defined. and your code would cause a memory leak, if comm_modify multi is specified multiple times.
i am thus not directly applying your patch but am currently transferring/reimplementing it piece by piece.
i'll keep an eye out for the user cutoff.

**Comment by akohlmey** [comment]
(re-)implemented in commit 0989c9dabe86d194ece0b827f6d32cfe08e50192 in the lammps-icms branch.

can you please (attach as shown above or) send me one or more (simple) test cases, so i can check the implementation before i send it to steve for inclusion into the upstream version. thanks

**Comment by akohlmey** [comment]
i also ran into the single comm cutoff issue in some of my regression tests and think i have found a clean way to handle this now in commit 3748ec5d817e2c32552d4632a1d4b185ce59d37d

**Comment by akohlmey** [comment]
as of commit 5576ecfcfe7f36d8f0381ff768bea2e21c34d008  this feature is completely implemented into LAMMPS-ICMS and the code forward to steve for inclusion into the upstream version. it passes the integration testing as well https://travis-ci.org/lammps/lammps/builds/77402493 and i've added code to the info command to query the communication mode and cutoff status. closing this issue now.
