### ISSUE TITLE
ERROR: Unknown compute style smd/tlsph/num/neighs

### ISSUE THREAD

**Issue by SamuelLarkin** [lammps/lammps#821]
## Summary

When using `compute nn all smd/tlsph/num/neighs` in my in.X file, lammps returns 
```
ERROR: Unknown compute style smd/tlsph/num/neighs (../modify.cpp:1151)
Last command: compute nn all smd/tlsph/num/neighs # number of neighbors for each particle
```

## Type of Issue

'Bug Report'

## Detailed Description (Enhancement Suggestion)
I'm trying to get `Total # of neighbors` from lammps using python.  Given the following input file in.melt:
```
# 2d Lennard-Jones melt
dimension 2
units           lj
atom_style      atomic
region          box block 0 100 0 100 -0.25 0.25
create_box      1 box
create_atoms    1 random 100 123 box
mass            1 1.0
#velocity all create 1. 87287

pair_style      lj/cut 2.5
pair_coeff      1 1 1.0 1.0 2.5

neighbor        0.3 bin
neigh_modify    every 20 delay 0 check no

fix             1 all nvt temp 0.1 0.1 100

#dump           id all atom 50 dump.melt
#dump            2 all image 100000 image.*.jpg type type &
#                axes yes 0.8 0.02
#dump_modify     2 pad 6

thermo          1000
run             1000 #

#compute SAM all neighs
#compute SAM all smd/tlsph/num/neighs
#compute 1 all smd/tlsph/num/neighs
#compute nn all smd/tlsph/num/neighs # number of neighbors for each particle
```
And the following python script
```
from __future__ import print_function

from mpi4py import MPI
from lammps import lammps

comm = MPI.COMM_WORLD

print('--Creating a lammps instance.')
lmp = lammps()
print('Using lammps version: {}'.format(lmp.version()))

print('--Reading the file.')
lmp.file("in.melt")
```

I get the following error message:
```
ERROR: Unknown compute style smd/tlsph/num/neighs (../modify.cpp:1151)
Last command: compute nn all smd/tlsph/num/neighs # number of neighbors for each particle
```
But given the following example from lammps's github repo
https://github.com/lammps/lammps/blob/master/examples/USER/smd/rubber_strip_pull/rubber_strip_pull.lmp
and the documentation
http://lammps.sandia.gov/doc/compute_smd_tlsph_num_neighs.html
I would expect that my command would've worked.

## LAMMPS Version (Bug Report)
LAMMPS (11 Aug 2017)
Using lammps version: 20170811
Installed using conda

## Expected Behavior (Bug Report)
No to report an error given that this command has been existing prior to my lammps version.

## Actual Behavior (Bug Report)
If a command is documented, one would expect to be able to use it without error.

## Steps to Reproduce (Bug Report)
Use the previously describe in.melt and python script, invoke the script
`python lammps.mpi.py`
and witness the error.
or simply
`lammps-daily < in.melt`

## Further Information, Files, and Links
May be there is a simpler way for me to extract the total number of neighbors?

**Comment by stanmoore1** [comment]
@SamuelLarkin It appears the USER-SMD package isn't installed. How are you building LAMMPS?

**Comment by SamuelLarkin** [comment]
Here are the commads I used:
sudo apt-get install libfftw3-devgit
clone https://github.com/lammps/lammps.git
cd lammps/src
\# http://lammps.sandia.gov/download.html#ubuntu
\make yes-all; \make -j 8 no-lib mode=shlib ubuntu; #\make openmpi
\# https://github.com/lammps/lammps/tree/master/python
\make install-python

Note that I'm a complete neophyte when it comes to lammps, I've playing around with it for only a couple of days.  Am I at least using the proper command to get the total number of neighbor in an experiment?

**Comment by akohlmey** [comment]
Hi! Using make no-lib will exclude USER-SMD. details are in the manual.

This is a case of PEBCAC and not a bug

Axel



--
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.
