### ISSUE TITLE
Compiler error for unavailable non-standard function invsqrt from Intel/18

### ISSUE THREAD

**Issue by jprotze** [lammps/lammps#832]
## Summary

Compilation aborts because of a missing include with Intel/18 compiler

## Type of Issue

Bug: missing include

## LAMMPS Version (Bug Report)

11 Aug 2017 (stable)
Is not fixed in master.

## Expected Behavior (Bug Report)

Should compile with Intel/18 compiler

## Actual Behavior (Bug Report)

Compiler error:
```
../pair_tersoff_intel.cpp(1375): error: no instance of overloaded function
"invsqrt" matches the argument list
             argument types are: (float)
     fvec rikinv = invsqrt(rsq2);
                   ^ 
```

## Steps to Reproduce (Bug Report)

Compile lammps with Intel/18 compiler
The compiler version we use is (although this should not matter):
```
icc (ICC) 18.0.1 20171018
Copyright (C) 1985-2017 Intel Corporation.  All rights reserved.
```

## Further Information, Files, and Links

The reason is a changed behavior of the Intel compiler with version 18:
https://software.intel.com/en-us/articles/non-standard-math-functions-invsqrt-removed-from-mathh-from-intelr-c-compiler-180

Suggested change is to add after:

https://github.com/lammps/lammps/blob/unstable/src/USER-INTEL/pair_tersoff_intel.cpp

```
#ifdef __INTEL_COMPILER
#include <mathimf.h>
#endif
```

**Comment by akohlmey** [comment]
the offending line of code shown above does not exist in the master branch anymore. the compilation issue was addressed in commit 07ddb5e62cf6a2d2e4d7557ffc90d9c2a4b402ca
