### ISSUE TITLE
Potential typo in balance.cpp

### ISSUE THREAD

**Issue by Azrael3000** [lammps/lammps#851]
Hi,

I'm a LIGGGHTS developer and recently had a look at the LAMMPS load balancing implementation. I found one odd thing in balance.cpp. In line 302 we have:

    } else if (comm->style == LAYOUT_NONUNIFORM) {

and 3 lines further down:

    } else if (comm->style == LAYOUT_TILED) {

in both cases this makes no sense unless comm->layout is on the left hand side of the comparison.

Cheers,
Arno

**Comment by stanmoore1** [comment]
Yes, I agree this is a bug.

**Comment by akohlmey** [comment]
FYI i've included it in my current bugfix collection pull request #852

**Comment by Azrael3000** [comment]
Thanks for the quick reply and confirmation. I'll let you guys close it whenever you wish.
