### ISSUE TITLE
The *rigid* fixes don't work with the *sphere* atom style

### ISSUE THREAD

**Issue by erozic** [lammps/lammps#853]
## Summary

When I use **rigid** fixes (rigid/nve, rigid/nve/small, rigid/nvt, rigid/nvt/small) while having the **sphere** ```atom_style``` (either by itself or in a hybrid combination) LAMMPS gives the following ERROR when it tries to execute the ```run``` command:
> ERROR: Temperature compute degrees of freedom < 0 (../compute_temp.cpp:101)

## Expected Behavior (Bug Report)

According to the manual, **rigid** fixes should work with the **sphere** ```atom_style```:
> The constituent particles within a rigid body can be point particles (the default in LAMMPS) or finite-size particles, such as spheres or ellipsoids or line segments or triangles...

## Actual Behavior (Bug Report)

What actually happens is that it doesn't work, just throws the error I quoted in the summary and exits.

## Steps to Reproduce (Bug Report)

Just create some particles in a standard setting (periodic boundaries, 3D, "lj" units etc.) while having ```atom_style sphere``` or ```atom_style hybrid sphere whatever``` and apply a **rigid fix** of some sort and it won't work, just throw that error.
I tried creating the particles by ```read_data``` or ```create_atoms```, doesn't make a difference.
I tried the **rigid/nve** and **rigid/nvt** (and the **/small** versions with the ```molecule``` option) variants.

I tried using **nve/sphere** and everything works fine (except there are no rigid bodies of course).
Also, when I replace the **sphere** ```atom_style``` with **atomic** or **molecular**, the **rigid** fixes work fine.

## Further Information, Files, and Links

I attach the files I used to reproduce this behaviour (with various variations commented-out)

[log.lammps.txt](https://github.com/lammps/lammps/files/1852621/log.lammps.txt)
[test.data.txt](https://github.com/lammps/lammps/files/1852622/test.data.txt)
[test.mol.txt](https://github.com/lammps/lammps/files/1852623/test.mol.txt)
[testing.py.txt](https://github.com/lammps/lammps/files/1852624/testing.py.txt)

**Comment by akohlmey** [comment]
you are not computing temperature correctly. the default temperature compute is assuming point particles, and thus determines too few degrees of freedom. use compute temp/sphere and fix_modify to resolve this situation. this has been explained multiple times on the mailing list.

**Comment by erozic** [comment]
@akohlmey Thanks for the answer. It can be found once you know what to look for. I sincerely suggest that you add a comment on this to the documentation, because I have read the documentation very carefully and haven't found anything that would suggest this would be a problem, even to keep something like this on my mind when using particles with extra degrees of freedom (it shows up only in fix nvt/sphere documentation, which I wasn't looking at since I wasn't using it).
I suggest you just add a short comment about it in the documentation for the ```atom_style sphere```, something along the lines of:
> When using sphere particles the additional degrees of freedom per particle should be kept in mind for the correct calculation of thermodynamic quantities, for example see ```compute temp/sphere```

**Comment by akohlmey** [comment]
@erozic here is your golden opportunity to pay back the community that has provided you with all the functionality at no cost. why don't you submit a pull request with the suggested changes to the documentation (or perhaps try to improve the situation even more by also addressing other issues that you didn't feel were explained well enough in the manual).

**Comment by erozic** [comment]
@akohlmey you are quite right. I mean, it just never occurred to me that I can, or that it would be welcomed if I contribute directly instead of just letting you guys know... Sorry, I'm a bit new at this (both LAMMPS and Github). Anyway, will do :)

**Comment by Pakketeretet2** [comment]
No worries. People often don't realize that they can contribute more than
they think. Even simple things like fixing typos in documentation are
always welcome.
