### ISSUE TITLE
LAMMPS slower than expected

### ISSUE THREAD

**Issue by thomashayes911** [lammps/lammps#862]
## Summary

I have implemented a Lennard jones code (with eps=sigma=1) in LAMMPS, but it is much slower than other codes. I sent email to mailing list too, but read more about how bugs are reported an figured out that I could just as well put it here.

## Type of Issue

Bug Report.

## Detailed Description (Enhancement Suggestion)

In the script attached, the Lennard Jones code runs much slower than with my c++ code written at university. 

## LAMMPS Version (Bug Report)

Newest from website.

## Expected Behavior (Bug Report)

Code should run fast.

## Actual Behavior (Bug Report)

Code runs slow.

## Steps to Reproduce (Bug Report)

Run the attached script

`/path/to/lmp_serial -in run.in`

## Further Information, Files, and Links

Here is the script:
[md_lammps.zip](https://github.com/lammps/lammps/files/1866482/md_lammps.zip)

**Comment by akohlmey** [comment]
this is useless. you are not confirming any kind of bug here. please see my answers to your e-mails on the mailing list.

**Comment by andeplane** [comment]
Fixed version! LJ code written in LAMMPS scripting language ;p 

[md_lammps.zip](https://github.com/lammps/lammps/files/1866551/md_lammps.zip)
