### ISSUE TITLE
Unexpected out of range atoms error with pppm/tip4p and triclinic boxes

### ISSUE THREAD

**Issue by akohlmey** [lammps/lammps#869]
## Summary

When using `change_box all triclinic` with kspace style `pppm/tip4p` incorrect energies are computed and for certain numbers of MPI ranks, LAMMPS crashes with `out of range atoms - cannot compute PPPM`. Since no actual tilt is used energies and forces should be the same for both setups for orthogonal and triclinic boxes. but that only seems to work for regular `pppm`, but not for `pppm/tip4p`

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

30 March 2018, on Fedora 27 with GCC 7.3.1, MPICH-3.2.1

## Steps to Reproduce (Bug Report)

Download the attached input deck and copy `examples/USER/tally/data.spce` into the same folder.
do: `mpirun -np 4 lmp_mpi -in in.pppm-orth-vs-tricl.txt`

## Further Information, Files, and Links

[log.pppm-orth-vs-tricl.txt](https://github.com/lammps/lammps/files/1904754/log.pppm-orth-vs-tricl.txt)
[in.pppm-orth-vs-tricl.txt](https://github.com/lammps/lammps/files/1904755/in.pppm-orth-vs-tricl.txt)

input and output to compare SPC/E and TIP4P with orthogonal and triclinic box setting. uses [examples/USER/tally/data.spce](https://raw.githubusercontent.com/lammps/lammps/master/examples/USER/tally/data.spce)

**Comment by akohlmey** [comment]
@stanmoore1 can we have a look at this while i am in ABQ?

**Comment by stanmoore1** [comment]
@akohlmey sure

**Comment by akohlmey** [comment]
@stanmoore1 this is the monthly reminder for this open issue. it would be great, if this could be addressed in the upcoming stable release.

**Comment by stanmoore1** [comment]
@akohlmey I'll try to look at this in the next few days. If it isn't a simple, easy fix I may need to wait to debug it--I'm pretty swamped for the next two weeks.

**Comment by stanmoore1** [comment]
@akohlmey if you have time and want to look at this issue, feel free, otherwise I'll try to squeeze it in.

**Comment by akohlmey** [comment]
@stanmoore1 i had already looked into it and could not figure it out. I'll flag it for being done by fall.

**Comment by akohlmey** [comment]
will have to move this to the next milestone

**Comment by mkanski** [comment]
I believe the bug comes from lines 505-507. Coordinates of all atoms in H2O molecule are converted from fractional coordinates, but it should be done only for local atoms. 

https://github.com/lammps/lammps/blob/898860328b45aa938547490af4261f5d80386f31/src/KSPACE/pppm_tip4p.cpp#L505-L507

Replacing the lines with the snippet below gives almost the same energies for orthogonal and triclinic (without tilt) simulation boxes. I haven't posted this as a pull request, because I have no way of testing it further. 

if (i < atom->nlocal)
    domain->lamda2x(x[i],xo);
  else {
    xo[0] = x[i][0];
    xo[1] = x[i][1];
    xo[2] = x[i][2];
  }
  if (iH1 < atom->nlocal)
    domain->lamda2x(x[iH1],xh1);
  else {
    xh1[0] = x[iH1][0];
    xh1[1] = x[iH1][1];
    xh1[2] = x[iH1][2];
  }
  if (iH2 < atom->nlocal)
    domain->lamda2x(x[iH2],xh2);
  else {
    xh2[0] = x[iH2][0];
    xh2[1] = x[iH2][1];
    xh2[2] = x[iH2][2];
  }

**Comment by Kick-H** [comment]
> I believe the bug comes from lines 505-507. Coordinates of all atoms in H2O molecule are converted from fractional coordinates, but it should be done only for local atoms.
> 
> https://github.com/lammps/lammps/blob/898860328b45aa938547490af4261f5d80386f31/src/KSPACE/pppm_tip4p.cpp#L505-L507
> 
> Replacing the lines with the snippet below gives almost the same energies for orthogonal and triclinic (without tilt) simulation boxes. I haven't posted this as a pull request, because I have no way of testing it further.
> 
> if (i < atom->nlocal)
> domain->lamda2x(x[i],xo);
> else {
> xo[0] = x[i][0];
> xo[1] = x[i][1];
> xo[2] = x[i][2];
> }
> if (iH1 < atom->nlocal)
> domain->lamda2x(x[iH1],xh1);
> else {
> xh1[0] = x[iH1][0];
> xh1[1] = x[iH1][1];
> xh1[2] = x[iH1][2];
> }
> if (iH2 < atom->nlocal)
> domain->lamda2x(x[iH2],xh2);
> else {
> xh2[0] = x[iH2][0];
> xh2[1] = x[iH2][1];
> xh2[2] = x[iH2][2];
> }

It does not matter.

**Comment by Kick-H** [comment]
> ## Summary
> When using `change_box all triclinic` with kspace style `pppm/tip4p` incorrect energies are computed and for certain numbers of MPI ranks, LAMMPS crashes with `out of range atoms - cannot compute PPPM`. Since no actual tilt is used energies and forces should be the same for both setups for orthogonal and triclinic boxes. but that only seems to work for regular `pppm`, but not for `pppm/tip4p`
> 
> ## Type of Issue
> Bug Report
> 
> ## LAMMPS Version (Bug Report)
> 30 March 2018, on Fedora 27 with GCC 7.3.1, MPICH-3.2.1
> 
> ## Steps to Reproduce (Bug Report)
> Download the attached input deck and copy `examples/USER/tally/data.spce` into the same folder.
> do: `mpirun -np 4 lmp_mpi -in in.pppm-orth-vs-tricl.txt`
> 
> ## Further Information, Files, and Links
> [log.pppm-orth-vs-tricl.txt](https://github.com/lammps/lammps/files/1904754/log.pppm-orth-vs-tricl.txt)
> [in.pppm-orth-vs-tricl.txt](https://github.com/lammps/lammps/files/1904755/in.pppm-orth-vs-tricl.txt)
> 
> input and output to compare SPC/E and TIP4P with orthogonal and triclinic box setting. uses [examples/USER/tally/data.spce](https://raw.githubusercontent.com/lammps/lammps/master/examples/USER/tally/data.spce)

I got the same error when I calculated the sII type methane hydrate. This structure is also a tricline box.

**Comment by akohlmey** [comment]
> I got the same error when I calculated the sII type methane hydrate. This structure is also a tricline box.

@Kick-H please provide a small but complete input deck, similar to the one attached to the issue. The error message can happen for **many** different reasons and having a triclinic box may or may not be associated with triggering the situation.

Since you revived this discussion thread, I finally got around to testing the suggestion by @mkanski and found that it **does** address the problem at hand. The energy discrepancies he saw, may be due to some other bug, that we fixed in between, since I can get exactly the same energies now after implementing his suggestion.

**Comment by Kick-H** [comment]
[in.methane.txt](https://github.com/lammps/lammps/files/3723250/in.methane.txt)
[sII-333.data.txt](https://github.com/lammps/lammps/files/3723251/sII-333.data.txt)

There are different results when you running:
mpirun -np 1 lmp_mpi < in.methane.txt,
mpirun -np 4 lmp_mpi < in.methane.txt respectively.

I am not sure if it is exactly the same as the reason you appeared.
I hope that I will not waste your time.

**Comment by akohlmey** [comment]
> [in.methane.txt](https://github.com/lammps/lammps/files/3723250/in.methane.txt)
> [sII-333.data.txt](https://github.com/lammps/lammps/files/3723251/sII-333.data.txt)
> 
> There are different results when you running:
> mpirun -np 1 lmp_mpi < in.methane.txt,
> mpirun -np 4 lmp_mpi < in.methane.txt respectively.
> 
> I am not sure if it is exactly the same as the reason you appeared.
> I hope that I will not waste your time.

the difference in results are just due to floating-point math and running a minimization.
this will result in slightly different final coordinates. if you run the minimization separately, and then start the MD from `after-min.data`, you will see the differences be much smaller.

nevertheless, those trajectories will diverge more quickly than simulations in NVE or NVT ensemble for three reasons:
1. with floating point math summing forces and stresses can lead to small difference when running with a different number of processors, since the order of the summing changes and floating point math is not associative.
2. when using a triclinic box, coordinates are frequently converted back and forth between regular and fractional coordinates, adding significantly to the numerical noise
3. when using fix npt all coordinates are scaled in every step based on the pressure, so small changes in pressure due to floating point math will get enhanced significantly, since pressure is much more sensitive to small changes than forces.

with the changes in my branch https://github.com/lammps/lammps/compare/master...akohlmey:pppm-tip4p-triclinic
this input deck can run with 4 MPI ranks on my machine.

**Comment by akohlmey** [comment]
@Kick-H please note, that my first variant of the fix had a couple of small bugs. What I have submitted as pull request #1719 should work. This will hopefully make it into the next patch release, which is expected soon.

**Comment by Kick-H** [comment]
> @Kick-H please note, that my first variant of the fix had a couple of small bugs. What I have submitted as pull request #1719 should work. This will hopefully make it into the next patch release, which is expected soon.

Thank you very very very very much. You are my hero!
