### ISSUE TITLE
communication between bond/create and bond/break

### ISSUE THREAD

**Issue by anyuzx** [lammps/lammps#874]
When using the bond/create and bond/break at the same time to allow the bond to be formed and broken dynamically, it seems that the atom won't form new bond after the existing bond is broken once this atom reaches the maximum number of bonds. There is a discussion about this in the mailing list http://lammps.sandia.gov/threads/msg55370.html. If I understand correctly, it is because the bond/create only count the bond number at the beginning of the run. I wonder is there any workaround on this issue?

**Comment by mkanski** [comment]
You can divide your run into a sequence of short runs and redeclare fix bond/create between them, e.g.
fix f1 all bond/create ...
run 1000
unfix f1
fix f1 all bond/create ...
run 1000
Theoretically, it should work, although I haven't tested it.

**Comment by jrgissing** [comment]
you might also check out 'fix bond/react' which allows for any number of topology changes (available in USER-MISC of current lammps master branch)

**Comment by sjplimp** [comment]
The only scenario where it is OK to use multiple bond/create and/or bond/break commands
is where they are operating on disjoint groups of atoms.  This is b/c the multiple instances
do not know anything about each other and the status of the bonds they have created or
broken.  The doc page should explain this, and the code should issue a warning if you have multiple instances of these in your script (active at the same time).

However, big picture, Jake is correct.  You should now be using a single fix bond/react command 
to do these kind of more complex models (breaking and creating at the same time).
Fix bond/react is already in the GHub version, will be part of a patch release for LAMMPS (website)
later today.

**Comment by jewettaij** [comment]
Firstly, you should definitely check out fix bond/react.
    Regarding Steve's last point, I posted some code last month that *hopefully* allows the user to use multiple fix bond/create and fix bond/break commands.  It adds a short delay before a bond/create or fix bond/break command.  Once a new bond is created by fix bond/create, this delay before the next fix bond/create (or break) command gives LAMMPS an opportunity to inform all of the processors about the topology change.  (Hopefully.  I have not tested this code with multiple fix bond/create and fix bond/break commands.  Curious to know if it works in parallel.)  The updated code and documentation is in a .tar.gz attachment to this post:
https://sourceforge.net/p/lammps/mailman/message/36298494/
(Documentation for the new feature is located in "fix_bond_create.txt" and "fix_bond_break.txt" files posted there.)
   This change does not effect the bond count, so I am not sure if it would help you in your situation.  (I'm trying to implement a different feature that would help with this problem, but unfortunately it does not work yet.)
    But, again, I would first check fix bond/react to see if that solves your problem.
Andrew

**Comment by anyuzx** [comment]
@akohlmey I haven't got chance to experiment with fix bond/react yet. But I guess this question can be closed. All very good suggestions.
