### ISSUE TITLE
[Feature Request] Improve the efficiency of fix atom/swap command in MC package

### ISSUE THREAD

**Issue by rdzzz** [lammps/lammps#905]
The fix atom/swap command is desired to perform Monte Carlo swap of specific atoms. As far as I'm concerned, it would take little time to swap different atoms. In fact this fix command is far slower than other command like fix npt.
In the source code of this fix, the information of atoms should be **exchanged** between different processors if the cutoffs of the atoms are different. However, after every swap of atoms this exchange are designed to be carried out. This means that if the fix is performed several hundred times **in one timestep**,  the exchange will be carried out the same hundreds times. 
In my opinion, although I don't know the details in the exchange progress, the exchanges in one timestep that costs lots of time should be just carried out just one time. And the low efficiency of this fix command comes from the unnecessary progress. 
The relative code can be found in FixAtomSwap::attempt_swap() function and FixAtomSwap::attempt_semi_grand() function.

**Comment by akohlmey** [comment]
Sorry, but this doesn't make much sense. You seem to be ignoring very fundamental properties of how Metropolis Monte Carlo operates (and the fact, that the success rate of Monte Carlo moves depends a lot on the specifics of the system), but more importantly you are neglecting the requirements of doing Monte Carlo operations in parallel.
