### ISSUE TITLE
Remove register keywords

### ISSUE THREAD

**Issue by andeplane** [lammps/lammps#922]
## Summary

The `register` keyword has been removed from c++-17 and has been deprecated for a long time. I'm trying to compile LAMMPS with IncludeOS which has a special compiler forcing c++17.

## Type of Issue

Enhancement.

## Detailed Description (Enhancement Suggestion)

In LAMMPS, there is 500+ lines using the `register` keyword which is not in use at all anymore. I can do it if you all agree :)

**Comment by akohlmey** [comment]
not a big deal to get it done. `sed -i -e 's,^\( \+\| \+{ \)register ,\1,' *.h *.cpp */*.h */*.cpp` does the trick, only in two places comments need to be fixed after that. most of the use of `register` is in files that need to be re-implemented for completing #371 so, there really isn't much damage done in the first place. see #923
