### ISSUE TITLE
[Feature request] Checking restart file when saving / before loading

### ISSUE THREAD

**Issue by zqex** [lammps/lammps#934]
It would be useful if
1) LAMMPS terminated when restart files can not be correctly saved, or
2) LAMMPS terminated when trying to restart the simulation from a truncated restart file.

I simulate dynamics where I some times needs to store restart rather than dump files, because the bond connectivity changes during a simulation. Later I convert the restart files to data files to save space. Secondly, I often need to run long simulations restarting the simulation e.g. 50-100 times.

When/if I run out of space, then it would be very nice if LAMMPS terminated gracefully with an error, and secondly when trying to restart from a truncated restart file, that LAMMPS would also terminate with an error rather than a crash.

Both should be fairly trivial, just saving a magic string at the end of the restart file and generating an error if this can not be written or are not read.

**Comment by stanmoore1** [comment]
For example:

```c++
  wrote = fwrite(vec,sizeof(char),n,fp);
  if (wrote != n) {
    long lost = (n-wrote)*sizeof(char);
    printf("Lost %ld bytes, errno = %i\n",lost,errno);
    perror("Invalid write in write_char_vec_3");
  }
```

**Comment by akohlmey** [comment]
@stanmore1 if you want to protect against corruption, you have to change the file format. it would benefit from being more self-descriptive in the first place and have a generic container structure with a directory like hierarchy, and to prevent against corruption, you also need to compute and store checksums. at that point, it would probably simpler to use a more generic file format interface like HDF5 which does provide exactly what i was describing. making this fault tolerant and have LAMMPS recover from read/write errors, especially when running in parallel might be quite a challenge. 

this is why i favor heuristic checks. if there are multiple restart files, one could simply do a check on the size and compare the size of the current restart file which is about to be read with the size of older restarts of the same run. as suggested before, this all is not very difficult to set up in a python style variable which can then be queried in an if statement. no wrappers, no major rewrites, no headaches.
**KISS** :smile:

**Comment by stanmoore1** [comment]
@akohlmey I'm not looking to make LAMMPS fault tolerant and recover from errors, I just want to know if the file is corrupt or not. I just want a check that says the size of the files on disk is the same as what the code thought it wrote out.

>if there are multiple restart files, one could simply do a check on the size and compare the size of the current restart file which is about to be read with the size of older restarts of the same run

If there is load balancing, then this could throw off the check from one balance instance to another.

**Comment by stanmoore1** [comment]
In the corruption case I mentioned previously, a small fraction of the bytes in a few of the restart files were lost, so the size on disk was a little less that what the code thought it wrote out. It was fairly subtle.

**Comment by akohlmey** [comment]
a simple check for sufficient available diskspace could be added to `fix halt`.
i see two ways to approach this, a) using platform specific calls like `statfs()`, `quotactl()`, or `getrlimit()`, which are fast and would allow to check different limits that affect filesize (available storage, available quota, ulimit), or b) by just trying to write a file of the required size with one large fwrite() request, and delete the file, if it was successful. the latter may have a significant performance impact, but would be portable and easy to implement.
