### ISSUE TITLE
lammps support for kim-api-v2.0

### ISSUE THREAD

**Issue by ellio167** [lammps/lammps#945]
## Summary

How should the upcoming **kim-api-v2.0** library be interfaced with lammps?

## Type of Issue

Design/implementation discussion

## Detailed Description

The KIM project is ready to start implementing an interface within lammps for the **kim-api-v2.0** library.  We would like to retain support for the **kim-api-v1.Y** library as it currently exists (in the pair_kim pair style).  The best way to go about this is not clear.

This could be done by creating a separate (pair_kim2) pair style.   This should be straight forward, but it would require the lammps user to pay attention to the kim-api version of the model they want to use.  (It would be nice if the user could, mostly, just ignore this.)

Or the existing pair_kim style could be extended to work with both libraries and automatically "do the right thing".   However, I'm not clear on how this would exactly work.  Dealing with linking with one or two libraries depending on various compile-time options seems complicated.

Or maybe there is a hybrid approach, where the existing pair_kim style is converted into a thin wrapper that simply hands off to new separate pair_kim1 (essentially the current pair_kim) or pair_kim2 styles.

Anyway, we are very interested in your thoughts, comments, and suggestions on the best design/plan for this issue.

**Comment by ellio167** [comment]
The creation of this issue prompted a renewed discussion within the KIM development team.  As a result, we decided that simultaneous support for kim-api-v1 and kim-api-v2 within lammps is not really important from the KIM team's perspective.  We also feel that it is more consistent with the LAMMPS development philosophy, to simply change-over from v1 support to v2 support.

@sjplimp, do you agree that we should just "rewrite" pair_kim to work with v2 and submit a pull request once it is ready (and openkim.org has been updated to provide v2 models)?

**Comment by sjplimp** [comment]
@ellio167  yes, I agree - just move to v2 when ready and drop v1.  Backward compatibility is an albatross around the neck of MSoft and Intel (8086), so I say don't worry about it, if possible.

**Comment by junghans** [comment]
> Backward compatibility is an albatross around the neck of MSoft and Intel (8086)

I will use exactly that quote next time, there is a feature in CMake missing ;-)

**Comment by ellio167** [comment]
Great, thanks!

**Comment by uihsnv** [comment]
Is there a road-map for when this migration will happen?

**Comment by ellio167** [comment]
Anytime now.  See #1011

**Comment by uihsnv** [comment]
In their latest release (v2.0.2), they seem to have made some changes to the name that might require adjustments:

> For better consistency with standard practice in the open 
> source community, we have switched from kim-api-v2 to simply kim-api. This 
> change will require very minor adjustments to the build setup for most codes 
> that use/link to the KIM API. See the INSTALL file and the examples for updated 
> procedures.

https://kim-api.readthedocs.io/en/latest/_n_e_w_s_source.html
https://groups.google.com/d/msg/openkim/p5_IAG0jHIs/Hu3F-wpzBgAJ

**Comment by ellio167** [comment]
@uihsnv see #1392
