### ISSUE TITLE
New type of atom_style

### ISSUE THREAD

**Issue by Lacho09** [lammps/lammps#947]
## Summary

Include atom_type cylinder

## Type of Issue

Suggestion for an Enhancement

## Detailed Description (Enhancement Suggestion)

It is not possible to create a cylinder in 3D (in 2D this can be accomplished with the disc option of the fix nve/sphere). Create one cylinder with the fix rigid involves a big number of atoms which slows down the simulation considerably. 
The cylinder is one of the most used geometries in studies involving granular materials, it would be very useful to have that kind of atom.

**Comment by akohlmey** [comment]
you don't need so much a new atom style, but a new pair style. something similar to pair style tri/lj but adjusted for granular interactions. please note, that sharp edges are particularly difficult to handle accurately in MD simulations, so a somewhat softened approximation is going to be helpful.

also, you should have a look at the work of sharon glotzer and her group for how to efficiently approximate shaped bodies through an expansion of that shake in different sized spheres.

**Comment by akohlmey** [comment]
please see the latest updates to the BODY package which allow to build all kinds of granular particle shapes efficiently.
