### ISSUE TITLE
[Windows] invalid file names

### ISSUE THREAD

**Issue by jrgissing** [lammps/lammps#954]
## Summary

File names in lib/kokkos from perhaps #930 contain characters (i think colons) which are invalid for windows files. 

## Type of Issue

git fails to download when using windows machines

## (Enhancement Suggestion)

not sure!

## LAMMPS Version (Bug Report)

6/16/18

## Expected Behavior (Bug Report)

successful git pull regardless of operating system

## Actual Behavior (Bug Report)

failed git pull on windows when not using a sparse checkout to exclude invalid files

## Steps to Reproduce (Bug Report)

git pull on windows

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by akohlmey** [comment]
@jrgissing i suggest you check out the Kokkos project directly ( at https://github.com/kokkos/kokkos/issues ) and file an issue there if there isn't one already.
