### ISSUE TITLE
EdgeIDs in fix bond/react are not optional

### ISSUE THREAD

**Issue by robeme** [lammps/lammps#969]
## Summary

Creating a bond, two angles and one dihedral between two molecules consisting of two atoms each is not possible b/c edge atoms are too close to reaction site. 

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

Allowing to replace the full topology of old topology with the new one.

## LAMMPS Version (Bug Report)

LAMMPS (22 Jun 2018)

## Expected Behavior (Bug Report)

A map file has a header and a body. The header of map file the contains one mandatory keyword and one optional keyword. The mandatory keyword is ‘equivalences’ and the optional keyword is ‘edgeIDs’:

## Actual Behavior (Bug Report)

EdgeIDs are not optional

## Steps to Reproduce (Bug Report)

See attached input file

## Further Information, Files, and Links

[test_bond_react.tar.gz](https://github.com/lammps/lammps/files/2136361/test_bond_react.tar.gz)

**Comment by jrgissing** [comment]
thanks for catching this. please let me know if #970 results in the expected behavior
