### ISSUE TITLE
Problem with harmonic bonds across periodic bonds

### ISSUE THREAD

**Issue by benoitbeliard** [lammps/lammps#985]
## Type of Issue

 'Bug Report' 

## Detailed Description (Enhancement Suggestion)

I am simulating a polymer chain with harmonic bonds in a periodic box. Sometimes, when an atom exits at one side and put back in the other side, the polymer chain becomes as long as the box because this new atom that just came in is bond to the others at the opposite side. I think it is an assignment issue and I looked into the manual and didn't find an answer.

## LAMMPS Version (Bug Report)

Latest version of LAMMPS

## Expected Behavior (Bug Report)

The bond should go cross the boundary so that the polymer keep its size.

## Steps to Reproduce (Bug Report)

data file : 
LAMMPS File for a protein droplet

  36   atoms
  30   bonds
   2   atom types
   1   bond types
-33.0193   33.0193   xlo xhi
-33.0193   33.0193   ylo yhi
-33.0193   33.0193   zlo zhi
Masses

   1      1
   2      1

Atoms #bond

   1      1      1   -24.875637   11.396232   11.389151
   2      1      1   -23.995069   11.870148   11.387532
   3      1      1   -23.114500   12.344064   11.385913
   4      1      1   -22.233932   12.817980   11.384293
   5      1      1   -21.353363   13.291896   11.382674
   6      1      1   -20.472795   13.765812   11.381055
   7      2      1   29.108686   -29.183552   13.927523
   8      2      1   29.054816   -29.319890   14.916719
   9      2      1   29.000946   -29.456228   15.905916
  10      2      1   28.947077   -29.592566   16.895113
  11      2      1   28.893207   -29.728904   17.884309
  12      2      1   28.839338   -29.865242   18.873506
  13      3      1   5.355472   31.830239   10.629107
  14      3      1   6.019654   31.347792   10.058049
  15      3      1   6.683835   30.865345   9.486991
  16      3      1   7.348017   30.382897   8.915933
  17      3      1   8.012198   29.900450   8.344875
  18      3      1   8.676380   29.418002   7.773817
  19      4      2   -9.080564   -22.281892   -22.551716
  20      4      2   -9.020410   -21.316981   -22.807308
  21      4      2   -8.960255   -20.352070   -23.062900
  22      4      2   -8.900100   -19.387158   -23.318493
  23      4      2   -8.839946   -18.422247   -23.574085
  24      4      2   -8.779791   -17.457336   -23.829678
  25      5      2   5.635778   1.296554   26.540300
  26      5      2   5.261181   1.262042   27.466845
  27      5      2   4.886585   1.227530   28.393391
  28      5      2   4.511989   1.193019   29.319936
  29      5      2   4.137392   1.158507   30.246482
  30      5      2   3.762796   1.123995   31.173027
  31      6      2   -9.900654   -5.567243   9.796037
  32      6      2   -10.379512   -5.716710   8.930962
  33      6      2   -10.858370   -5.866177   8.065887
  34      6      2   -11.337228   -6.015644   7.200812
  35      6      2   -11.816085   -6.165111   6.335737
  36      6      2   -12.294943   -6.314578   5.470661

Bonds #harmonic

   1      1      1      2
   2      1      2      3
   3      1      3      4
   4      1      4      5
   5      1      5      6
   6      1      7      8
   7      1      8      9
   8      1      9     10
   9      1     10     11
  10      1     11     12
  11      1     13     14
  12      1     14     15
  13      1     15     16
  14      1     16     17
  15      1     17     18
  16      1     19     20
  17      1     20     21
  18      1     21     22
  19      1     22     23
  20      1     23     24
  21      1     25     26
  22      1     26     27
  23      1     27     28
  24      1     28     29
  25      1     29     30
  26      1     31     32
  27      1     32     33
  28      1     33     34
  29      1     34     35
  30      1     35     36

Bond Coeffs

   1      1      0   
PairIJ Coeffs

   1      1     40      1
   1      2     -4    0.5
   2      2     40      1

Simulation LAMMPS file
boundary p p p
atom_style bond
pair_style soft 1
special_bonds lj 1. 1. 1.
bond_style harmonic
timestep 0.01
read_data datafile
compute new all temp
velocity all create 1 234 temp new
fix 1 all nvt temp 1 1 1
fix 2 all langevin 1 1 0.01 54526
fix 3 all temp/rescale 100 1 1 0.1 1.0
thermo 1000
dump 1 all movie 50 movie.mpg type type bond type 0.1 zoom 1.2 size 720 720
run 200000

**Comment by akohlmey** [comment]
i don't think that this is a bug in LAMMPS, but an unstable simulation due to bad simulation settings.
the strange bond behavior can only be seen when running in serial, since then atoms cannot be "lost" easily. LAMMPS will then look for the "nearest" periodic image, which is the periodic copy of the otherwise lost atom and then the strangely elongated bonds result from that.

when this input running in parallel, i quickly get "lost atoms". and even when reducing the timestep to 0.001 i get a lost atom error. that is usually a sign of bad dynamics, too large a time step, or too short a communication cutoff (check out: comm_modify cutoff). i also noticed, that there are a large number of "dangerous builds" for the neighbor list, which hints, that the neighbor list settings are not ideal either.

**Comment by jewettaij** [comment]
Dear Benoit
    I haven't tried running your files.  Axel suggested increasing the **communication cutoff**.  In my experience, this is often the reason for the kinds of problems you are reporting (especially if you are using a coarse-grained model).
    For more details, see these posts:
https://lammps.sandia.gov/threads/msg76045.html
https://github.com/lammps/lammps/issues/985
https://lammps.sandia.gov/doc/comm_modify.html
   If raising the communication cutoff solves the problem you are having, please report back.  It's useful to know how many people are affected by this problem.
-Andrew

**Comment by benoitbeliard** [comment]
Dear Andrew and Alex,

Thank you very much for your help. It was very helpful.

Best,

Benoit
