### ISSUE TITLE
Inconsistent angle_style dipole manual page

### ISSUE THREAD

**Issue by alexfleury** [lammps/lammps#990]
## Summary

The condition atom_i =/= atom_j =/= atom_k in atoms.cpp (line = 1105) is inconsistent with the informations reported in angle_style dipole command. Therefore, an ""Invalid atom ID in Angles section of data file" stops the program.

## Type of Issue

Bug Report

## LAMMPS Version (Bug Report)

Latest development version and 13Mar18. Lammps11Aug17 does not have this problem.

## Expected Behavior (Bug Report)

Reading of the data should be fine.

From the Lammps manual.
> In the “Angles” section of the data file, the atom ID ‘j’ corresponding to the dipole to restrain must come before the atom ID of the reference atom ‘i’. A third atom ID ‘k’ must also be provided, although ‘k’ is just a ‘dummy’ atom which can be any atom; it may be useful to choose a convention (e.g., ‘k’=’i’) and adhere to it. For example, if ID=1 for the dipolar atom to restrain, and ID=2 for the reference atom, the corresponding line in the “Angles” section of the data file would read: X X 1 2 2.

## Actual Behavior (Bug Report)

A "Invalid atom ID in Angles section of data file" is given. In fact, I have several angles with the dipole style (provided by the package USER-MISC). Each of them follow the convention of reported in the manual (X X i j j). Versions of LAMMPS after 11Aug17 does not read the data file with success.

This is cause by 4th line of this code in src/atoms.cpp (around line 1105).

```
if ((atom1 <= 0) || (atom1 > map_tag_max) ||
        (atom2 <= 0) || (atom2 > map_tag_max) ||
        (atom3 <= 0) || (atom3 > map_tag_max) ||
        (atom1 == atom2) || (atom1 == atom3) || (atom2 == atom3))
      error->one(FLERR,"Invalid atom ID in Angles section of data file");
```

## Steps to Reproduce (Bug Report)

Launching Lammps with the files provided in the link below.

> lmp_yourmachine -in in.test

## Further Information, Files, and Links

[Minimal_test.zip](https://www.dropbox.com/s/ped763ot9uu83u1/Minimal_test.zip?dl=0)

**Comment by akohlmey** [comment]
The information given in the angle style dipole is outdated. For improved consistency checking of input data, we added the check to the angle definitions. This was done after the dipole angle style was added and without knowledge that this angle style is "abusing" the angle style to define a point dipole. However the benefit of the consistency checking outweighs the inconvenience to users of the angle style dipole. If you feel strongly about this, you can always change the code that does the consistency check back to where it was in older LAMMPS versions. In PR #991 i have updated to the documentation to be consistent with current requirements.
