### ISSUE TITLE
Endless loop of compute cluster_atom

### ISSUE THREAD

**Issue by qq473986956** [lammps/lammps#998]
I want choice some cluster by lammps command:  
    **compute         YYcluster YYglo cluster/atom 3.0
    variable           MaxCluster atom "c_YYcluster>=1"**
then I can dump the data as:
    **dump            YYpos3 all custom 10 04.lammpstrj id type x y z v_MaxCluster c_YYcluster**
everythin is fine.   but when I defined a dynamic group as:
    **group             YYgAl  dynamic all var MaxCluster**
There is endless loop.  

1. the version I used often is 17Nov16 , but i also try the 16Mar18 version and also have these problem

2. mpi and serial is same.

3. In case of 17Nov16 version, I find endless loop is locate in compute_cluster_atom.cpp at line 180:
    **clusterID[i] = clusterID[j] = MIN(clusterID[i],clusterID[j]);**
if I add printf() function before and after this line, as:
    **printf("%d %d %lf %lf 1111\n",i,j,clusterID[i],clusterID[j]);
    clusterID[i] = clusterID[j] = MIN(clusterID[i],clusterID[j]);
    printf("%d %d %lf %lf 2222\n",i,j,clusterID[i],clusterID[j]);**
I get information as:
**43 4869 44.000000 478.000000 1111
43 4869 44.000000 44.000000 2222
43 4869 44.000000 478.000000 1111
43 4869 44.000000 44.000000 2222
43 4869 44.000000 478.000000 1111
43 4869 44.000000 44.000000 2222**
the clusterID[j] can change to the min(44) of clusterID[i](44) and clusterID[j](478) , but next loop clusterID[j] will become to original value(478). I want to fix this bug, but I can not find where it is, and I do not know why the value always become to the original value.  can someone help me?  How to fix this bug? Thanks for help.

4. the lammps input file as:

log             03.ThermoMD.log
units           metal
atom_style      atomic

lattice         fcc 4.9095
region          YYr1 block 0 10.0 0 10.0 0.0 10.0 units lattice
create_box      2 YYr1
create_atoms    2 region YYr1

region		YYrlo block INF INF INF 1.5 INF INF
group 		YYglo region YYrlo

pair_style      eam/alloy
pair_coeff      * * alpb-setfl.eam.alloy Al Pb
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes
atom_modify     sort 0 0.0

thermo          1
thermo_style    custom step temp pe etotal press vol pxx pyy pzz enthalpy lz zlo zhi
thermo_modify   flush yes line one

timestep        0.001

compute         YYcluster YYglo cluster/atom 3.0
variable        MaxCluster atom "c_YYcluster>=1"
group           YYgAl  dynamic all var MaxCluster

#compute         YYcom YYgAl com
#fix             YYo2 all ave/time 1 1 1 c_YYcom[1] c_YYcom[2] c_YYcom[3] file 06.ave.com

dump            YYpos3 all custom 10 04.lammpstrj id type x y z v_MaxCluster c_YYcluster

velocity	all create 1600 111111
fix             YYMD all nvt temp 1600 1600 0.1
run             1000 
unfix           YYMD

5. the eam file can download form:  https://www.ctcms.nist.gov/potentials/Al-Pb.html

**Comment by danicholson** [comment]
I think I have figured out where this issue is coming from. 

The dynamic group definition is causing compute cluster/atom to be called in post_integrate(), before the ghost atom positions are updated. This creates a situation where the distances between atoms and ghosts are asynchronous.

In the example above, the atom with tag=44 registers as being part of the same cluster as the ghost version of atom with tag=478. The atom with tag=478 registers as not being in the same cluster as the ghost version of atom with tag=44. This causes the clusterID ghost version of the atom with tag=478 to be set 44 in the inner loop, only to be overwritten back to 478 after forward communication.

I added this line to compute_cluster_atom.cpp
```
...
rsq = delx*delx + dely*dely + delz*delz;
if ((tag[i] == 44 && tag[j] == 478) || (tag[j] == 44 && tag[i] == 478))
    printf("%d %d %d %d %lf\n",tag[i],tag[j],i>atom->nlocal,j>atom->nlocal,rsq);
if (rsq < cutsq) { 
...
```
It gives the following output during the loop:
```
44 478 0 1 8.995846
478 44 0 1 9.010456
478 44 0 1 9.010456
44 478 0 1 8.995846
```
I'm not sure the best way to fix this problem.

**Comment by qq473986956** [comment]
yes, you are right. thanks vary much. do you know how to update the ghost atom positions? if I add a function to update the ghost atom positions in set_group() function in fix_group.cpp, then is it ok?

**Comment by akohlmey** [comment]
@sjplimp this looks like it is something where your special expertise is needed to resolve it (or we'll have to abandon enabling dynamic group support for this?).

**Comment by sjplimp** [comment]
Hmm - just looking at this now.  It is a tricky issue b/c I can't think of a simple way
to check for whether ghost atom comm is needed.  The criterion for the dynamic
group is a variable which invokes cluster/atom.  As @danicholson said, this
is at post_integrate, which is before ghost atom coords are updated, which causes
the issue (good find, David!).  One solution would be to enforce ghost-atom
comm in FixGroup::post-integrate().  That's pretty brute-force (almost never needed),
but I can't think of a good way to determine when it is needed.  A varaible
could call any compute, even pretty indirectly thru another fix or thermo keyword.
Open to suggestions ??

**Comment by sjplimp** [comment]
Another idea might be to enable compute cluster/atom to detect when it is being
called from fix_group at the post_integrate point in the timestep, and it could
do the needed ghost comm.

**Comment by akohlmey** [comment]
@sjplimp i'm thinking more than before, we should (temporarily for the stable release) just disallow dynamic groups with this compute and then revert the change afterwards and look for a reasonable solution without the pressure of worrying about side effects or having to make changes to some low-level code.

**Comment by sjplimp** [comment]
@akohlmey Actually in the problem here, compute cluster/atom is not operating on a dynamic
group.  It is simply doing its thing on group all, but a dynamic group is using the result
to update which are the atoms are in its group.  I think my 2nd suggestion is the way to go.
It will have no side effects, just an added variable that only compute cluster/atom will check.
I'll submit a PR this AM.
